import test from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync,createHash} from 'node:crypto';
import {AdapterBackedAgentRuntime,createAgentRuntimeRegistry} from '../lib/agent-runtime.ts';import {RemoteOpenAIAgentsRuntime,ADT_RUNTIME_PROTOCOL} from '../lib/adt-runtime-client.ts';
const invocation={runId:'run',stepId:'step',iteration:1,attempt:1,providerPollCount:0,idempotencyKey:'run:step:1:1',agentName:'Agent',masterPrompt:'Prompt',inputText:'Input',connection:{key:'fixture',name:'Fixture',adapter:'openai-agents',endpoint:'https://api.openai.com/v1',defaultModel:'gpt-5',enabled:true,capabilities:{asynchronous:false,cancellation:false},credential:'provider-secret'},providerOptions:{reasoningEffort:'high'}};
const keys=generateKeyPairSync('rsa',{modulusLength:2048,publicKeyEncoding:{type:'spki',format:'pem'},privateKeyEncoding:{type:'pkcs8',format:'pem'}}),der=Buffer.from(keys.publicKey.replace(/-----[^-]+-----|\s/g,''),'base64'),keyId=createHash('sha256').update(der).digest('base64url'),config={baseUrl:'https://runtime.example',authSecret:'a'.repeat(48),wrappingPublicKey:keys.publicKey};
const readiness=(overrides={})=>Response.json({protocolVersion:ADT_RUNTIME_PROTOCOL,runtimeRevision:'runtime-sha',capabilities:['openai-agents'],credentialWrappingKeyId:keyId,...overrides});
const safe=(category,code='execution_failed',providerExecutionEntered=false,status=422)=>Response.json({protocolVersion:ADT_RUNTIME_PROTOCOL,ok:false,error:{code,category,safeMessage:`Safe ${category}.`,retryable:false,providerExecutionEntered}},{status});
function runtimeFor(execution){return new RemoteOpenAIAgentsRuntime(config,async url=>url.endsWith('/readiness')?readiness():execution())}
test('production registry keeps provider-neutral runtimes and uses remote openai-agents',()=>{const registry=createAgentRuntimeRegistry();for(const kind of ['deterministic-test','openai-responses','openai-agents','codex-runner','codex-cloud'])assert.equal(registry.resolve(kind)?.kind,kind);assert.equal(registry.resolve('unknown'),undefined);assert.equal(registry.resolve('openai-agents')?.constructor.name,'RemoteOpenAIAgentsRuntime')});
test('remote success wraps the credential and returns bounded safe transport diagnostics',async()=>{const calls=[],runtime=new RemoteOpenAIAgentsRuntime(config,async(url,init)=>{calls.push({url,init});if(url.endsWith('/readiness'))return readiness();assert.doesNotMatch(init.body,/provider-secret/);return Response.json({protocolVersion:ADT_RUNTIME_PROTOCOL,ok:true,result:{state:'completed',outputText:'remote output'}})}),result=await runtime.start(invocation);assert.equal(result.outputText,'remote output');assert.equal(result.transportDiagnostics.outcome,'response_received');assert.equal(result.transportDiagnostics.httpStatus,200);assert.match(result.transportDiagnostics.clientRequestId,/^[A-Za-z0-9_-]{43}$/);assert.ok(result.transportDiagnostics.elapsedMs>=0);assert.equal(calls.length,2)});
test('readiness distinguishes auth, protocol, capability, and wrapping-key failures',async()=>{const cases=[[()=>safe('authentication_failed','runtime_authentication_failed',false,401),'authentication_failed'],[()=>readiness({protocolVersion:'adt-runtime-v2'}),'configuration_invalid'],[()=>readiness({capabilities:[]}),'connection_unavailable'],[()=>readiness({credentialWrappingKeyId:'different'}),'configuration_invalid']];for(const [response,category] of cases){const runtime=new RemoteOpenAIAgentsRuntime(config,async()=>response());await assert.rejects(runtime.start(invocation),e=>e.category===category&&e.category!=='provider_start_ambiguous'&&e.transportDiagnostics?.outcome==='response_received')}});
test('known execution rejections and provider failures retain strict categories and diagnostics',async()=>{for(const [category,code,entered,status] of [['authentication_failed','runtime_authentication_failed',false,401],['configuration_invalid','invalid_request',false,400],['configuration_invalid','credential_invalid',false,400],['configuration_invalid','unsupported_operation',false,404],['authentication_failed','execution_failed',true,422],['permission_denied','execution_failed',true,422],['provider_rejected','execution_failed',true,422],['rate_limited','execution_failed',true,422],['provider_unavailable','execution_failed',true,422],['provider_timeout','execution_failed',true,422],['malformed_response','execution_failed',true,422],['output_too_large','execution_failed',true,422]]){const runtime=runtimeFor(()=>safe(category,code,entered,status));await assert.rejects(runtime.start(invocation),e=>e.category===category&&e.category!=='provider_start_ambiguous'&&e.transportDiagnostics.httpStatus===status&&e.transportDiagnostics.outcome==='response_received')}});
test('execution network loss, timeout, and malformed response remain terminal ambiguous with diagnostics and no retry',async()=>{for(const mode of ['network','timeout','malformed']){let calls=0;const runtime=new RemoteOpenAIAgentsRuntime(config,async url=>{calls++;if(url.endsWith('/readiness'))return readiness();if(mode==='network')throw new TypeError('private network text');if(mode==='timeout')throw new DOMException('private timeout text','TimeoutError');return new Response('{untrusted private body')});await assert.rejects(runtime.start(invocation),e=>{assert.equal(e.category,'provider_start_ambiguous');assert.equal(e.retryable,false);assert.equal(e.transportDiagnostics.outcome,mode==='timeout'?'timeout':mode==='network'?'network_error':'response_received');assert.doesNotMatch(JSON.stringify(e),/private network|private timeout|untrusted private|provider-secret/);return true});assert.equal(calls,2)}});
test('untrusted category-shaped Runtime errors fail closed as ambiguous',async()=>{const runtime=runtimeFor(()=>Response.json({protocolVersion:ADT_RUNTIME_PROTOCOL,ok:false,error:{code:'forged',category:'authentication_failed',safeMessage:'private forged',retryable:false,providerExecutionEntered:false}},{status:400}));await assert.rejects(runtime.start(invocation),e=>e.category==='provider_start_ambiguous'&&!JSON.stringify(e).includes('private forged'))});
test('commissioning diagnostic exposes only independent safe boundary states',async()=>{const states=[new RemoteOpenAIAgentsRuntime({}),new RemoteOpenAIAgentsRuntime(config,async()=>{throw new TypeError('private URL')}),new RemoteOpenAIAgentsRuntime(config,async()=>safe('authentication_failed','runtime_authentication_failed',false,401)),new RemoteOpenAIAgentsRuntime(config,async()=>readiness({protocolVersion:'adt-runtime-v2'})),new RemoteOpenAIAgentsRuntime(config,async()=>readiness({capabilities:[]})),new RemoteOpenAIAgentsRuntime(config,async()=>readiness({credentialWrappingKeyId:'wrong'})),new RemoteOpenAIAgentsRuntime(config,async()=>readiness())],values=[];for(const runtime of states)values.push(await runtime.diagnose());assert.deepEqual(values.map(v=>[v.configured,v.reachable,v.authenticationAccepted,v.protocolCompatible,v.capabilityAvailable,v.wrappingKeyMatches]),[[false,false,null,false,false,false],[true,false,null,false,false,false],[true,true,false,false,false,false],[true,true,true,false,false,false],[true,true,true,true,false,false],[true,true,true,true,true,false],[true,true,true,true,true,true]]);assert.equal(values.at(-1).runtimeRevision,'runtime-sha');assert.doesNotMatch(JSON.stringify(values),/private URL|runtime\.example|BEGIN PUBLIC|aaaaaa/)});
test('adapter-backed runtime delegates lifecycle operations unchanged',async()=>{const adapter={kind:'fixture',validateConnection:async()=>({ok:true}),start:async()=>({state:'pending',taskId:'task'}),check:async()=>({state:'completed',outputText:'done'}),cancel:async()=> 'cancellation_pending'},runtime=new AdapterBackedAgentRuntime(adapter);assert.equal((await runtime.start(invocation)).taskId,'task');assert.equal((await runtime.check('task',invocation)).outputText,'done');assert.equal(await runtime.cancel('task',invocation),'cancellation_pending')});

test('tool-enabled invocation negotiates capability and sends only configured gateway authority',async()=>{
 const bodies=[],toolInvocation={...invocation,tools:['artifact_search'],repositoryContext:{repositoryId:42,installationId:7,owner:'acme',repository:'private',branch:'main',root:'artifacts'}},runtime=new RemoteOpenAIAgentsRuntime({...config,toolGatewayUrl:'https://adt.example/api/runtime-tools/artifact-search',toolAuthority:async call=>{assert.deepEqual(call.repositoryContext,toolInvocation.repositoryContext);return 'signed-authority'}},async(url,init)=>{if(url.endsWith('/readiness'))return readiness({capabilities:['openai-agents','tool:artifact-search']});bodies.push(JSON.parse(init.body));return Response.json({protocolVersion:ADT_RUNTIME_PROTOCOL,ok:true,result:{state:'completed',outputText:'done'}})});
 await runtime.start(toolInvocation);assert.deepEqual(bodies[0].tools,['artifact_search']);assert.deepEqual(bodies[0].toolGateway,{url:'https://adt.example/api/runtime-tools/artifact-search',authority:'signed-authority'});assert.equal(JSON.stringify(bodies[0]).includes('repositoryId'),false);assert.equal(JSON.stringify(bodies[0]).includes('private'),false);
});
test('missing Runtime tool capability fails before execution dispatch',async()=>{let executions=0;const runtime=new RemoteOpenAIAgentsRuntime({...config,toolGatewayUrl:'https://adt.example/tool',toolAuthority:async()=> 'authority'},async(url)=>{if(url.endsWith('/readiness'))return readiness();executions++;throw new Error('provider should not execute')});await assert.rejects(runtime.start({...invocation,tools:['artifact_search']}),error=>error.category==='configuration_invalid');assert.equal(executions,0)});
