import test from "node:test";
import assert from "node:assert/strict";
import {createArtifactSearchGateway} from "../lib/artifact-search-gateway.ts";
import {issueArtifactSearchAuthority} from "../lib/artifact-search-tool.ts";
const runId=crypto.randomUUID(),secret="g".repeat(32),runtimeSecret="r".repeat(32),context={repositoryId:42,installationId:7,owner:"acme",repository:"private",branch:"frozen",root:"frozen-root"},coordinates={stepId:"step-1",iteration:1,attempt:1},authority=(overrides={},key=secret)=>issueArtifactSearchAuthority({version:1,runId,...coordinates,...context,expiresAt:Date.now()+60_000,nonce:crypto.randomUUID(),...overrides},key);
const baseAttempt={runId,stepId:"step-1",iteration:1,attempt:1,agentId:"agent",connectionKey:"agents",status:"starting",providerPollCount:0};
const activeDetail={run:{id:runId,engineVersion:"2",status:"running",currentStepId:"step-1",repositoryContext:context,executionPlan:{planVersion:2,nodes:[{id:"step-1",blockType:"agent",blockVersion:1,config:{agentId:"agent"}}],edges:[],entryNodeId:"step-1",terminalNodeId:"step-1",maxStepExecutions:1},agentSnapshots:{agent:{tools:["artifact_search"]}},connectionSnapshots:{agents:{adapter:"openai-agents",management:"git",credentialSource:"adt-vault"}}},attempts:[baseAttempt]};
const request=(token=authority(),body={runId,tool:"artifact_search",callId:"call-1",arguments:{query:"secret"}})=>new Request("https://adt.invalid/api/runtime-tools/artifact-search",{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify(body)});
const gatewayFor=(detail=activeDetail,loadArtifacts=async()=>[])=>createArtifactSearchGateway({storage:{getRun:async()=>detail},secret,loadArtifacts});
test("dedicated authority binds the exact active attempt and returns only bounded safe fields",async()=>{let loaded;const response=await gatewayFor(activeDetail,async value=>{loaded=value;return[{id:"match",title:"Match",description:"",type:"prompt",tags:[],aliases:[],body:"secret body",excerpt:"",path:"frozen-root/prompts/private.md"}]})(request()),body=await response.json();assert.equal(response.status,200);assert.deepEqual(loaded,context);assert.equal(body.results[0].body,"secret body");assert.equal("path" in body.results[0],false);assert.equal(JSON.stringify(body).includes("private.md"),false)});
test("Runtime request secret cannot manufacture tool authority",async()=>{assert.equal((await gatewayFor()(request(authority({},runtimeSecret)))).status,401)});
test("failed, completed, cancelled, and superseded attempts are rejected before repository access",async()=>{for(const detail of [{...activeDetail,attempts:[{...baseAttempt,status:"failed"}]},{...activeDetail,attempts:[{...baseAttempt,status:"succeeded"}]},{...activeDetail,attempts:[{...baseAttempt,status:"cancelled"}]},{...activeDetail,run:{...activeDetail.run,status:"failed"}},{...activeDetail,run:{...activeDetail.run,status:"succeeded",currentStepId:undefined}},{...activeDetail,run:{...activeDetail.run,status:"cancelling"}},{...activeDetail,attempts:[baseAttempt,{...baseAttempt,attempt:2,status:"starting"}]}]){let loads=0;assert.equal((await gatewayFor(detail,async()=>{loads++;return[]})(request())).status,401);assert.equal(loads,0)}});
test("step, attempt, repository, branch, and root mismatches fail closed before repository access",async()=>{for(const token of [authority({stepId:"step-2"}),authority({attempt:2}),authority({repositoryId:99}),authority({branch:"later"}),authority({root:"later-root"})]){let loads=0;assert.equal((await gatewayFor(activeDetail,async()=>{loads++;return[]})(request(token))).status,401);assert.equal(loads,0)}});
test("replayed and model-selected repository requests are rejected",async()=>{const gateway=gatewayFor(),token=authority();assert.equal((await gateway(request(token))).status,200);assert.equal((await gateway(request(token))).status,422);assert.equal((await gateway(request(authority(),{runId,tool:"artifact_search",callId:"call-2",arguments:{query:"x",repository:"other"}}))).status,422)});

test("legacy credential snapshots cannot use a valid tool authority",async()=>{let loads=0;const legacy={...activeDetail,run:{...activeDetail.run,connectionSnapshots:{agents:{adapter:"openai-agents",management:"git",credentialSource:"cloudflare-binding"}}}};assert.equal((await gatewayFor(legacy,async()=>{loads++;return[]})(request())).status,401);assert.equal(loads,0)});
