import test from "node:test";
import assert from "node:assert/strict";
import {ArtifactSearchAuthorityBudget,ARTIFACT_SEARCH_LIMITS,boundedArtifactSearch,issueArtifactSearchAuthority,verifyArtifactSearchAuthority} from "../lib/artifact-search-tool.ts";

const artifact=(id,body,extra={})=>({id,title:id,description:"",type:"prompt",tags:[],aliases:[],body,excerpt:"",path:`artifacts/prompts/${id}.md`,...extra});
test("artifact search reuses AND, case-insensitive identity, tag, alias, and body semantics",()=>{const values=[artifact("alpha","Private Design Notes",{tags:["Secure"],aliases:["plan"]}),artifact("beta","public")];const result=boundedArtifactSearch(values,{query:"ALPHA secure notes"});assert.deepEqual(result.results.map(value=>value.id),["alpha"]);assert.equal("path" in result.results[0],false);assert.equal("sha" in result.results[0],false)});
test("artifact search validates arguments and truncates individual bodies",()=>{assert.throws(()=>boundedArtifactSearch([],{query:"x".repeat(ARTIFACT_SEARCH_LIMITS.queryCharacters+1)}));const result=boundedArtifactSearch([artifact("alpha","é".repeat(40_000))],{query:"alpha",limit:1});assert.equal(result.results[0].truncated,true);assert.ok(Buffer.byteLength(result.results[0].body)<=ARTIFACT_SEARCH_LIMITS.bodyBytes)});
test("result-count and total-size omissions report truncation",()=>{assert.equal(boundedArtifactSearch([artifact("one","match"),artifact("two","match")],{query:"match",limit:1}).truncated,true);const large=Array.from({length:10},(_,index)=>artifact(`item-${index}`,`match ${"x".repeat(31_000)}`));assert.equal(boundedArtifactSearch(large,{query:"match",limit:10}).truncated,true)});
test("tool authority is repository-bound, expiring, mismatched-safe, and call-bounded",()=>{const secret="s".repeat(32),value={version:1,runId:crypto.randomUUID(),repositoryId:42,installationId:7,owner:"acme",repository:"private",branch:"main",root:"artifacts",expiresAt:Date.now()+60_000,nonce:crypto.randomUUID()},token=issueArtifactSearchAuthority(value,secret);assert.deepEqual(verifyArtifactSearchAuthority(token,secret,value.runId),value);assert.throws(()=>verifyArtifactSearchAuthority(token,secret,crypto.randomUUID()));assert.throws(()=>verifyArtifactSearchAuthority(token,secret,value.runId,value.expiresAt));assert.throws(()=>verifyArtifactSearchAuthority(`${token}x`,secret,value.runId));const budget=new ArtifactSearchAuthorityBudget();for(let i=0;i<ARTIFACT_SEARCH_LIMITS.maxCalls;i++)budget.accept(value,`call-${i}`);assert.throws(()=>budget.accept(value,"call-0"),/replayed/)});
