import test from "node:test";
import assert from "node:assert/strict";
import {createArtifactSearchGateway} from "../lib/artifact-search-gateway.ts";
import {issueArtifactSearchAuthority} from "../lib/artifact-search-tool.ts";
const runId=crypto.randomUUID(),secret="g".repeat(32),context={repositoryId:42,installationId:7,owner:"acme",repository:"private",branch:"main",root:"artifacts"},authority=()=>issueArtifactSearchAuthority({version:1,runId,...context,expiresAt:Date.now()+60_000,nonce:crypto.randomUUID()},secret);
const detail={run:{id:runId,currentStepId:"step-1",repositoryContext:context,workflowSnapshot:{steps:[{id:"step-1",agentId:"agent"}]},agentSnapshots:{agent:{tools:["artifact_search"]}}}};
const request=(token=authority(),body={runId,tool:"artifact_search",callId:"call-1",arguments:{query:"secret"}})=>new Request("https://adt.invalid/api/runtime-tools/artifact-search",{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify(body)});
test("gateway binds authority to run and immutable repository context and returns only bounded safe fields",async()=>{let loaded;const gateway=createArtifactSearchGateway({storage:{getRun:async()=>detail},secret,loadArtifacts:async value=>{loaded=value;return[{id:"match",title:"Match",description:"",type:"prompt",tags:[],aliases:[],body:"secret body",excerpt:"",path:"artifacts/prompts/private.md"}]}}),response=await gateway(request()),body=await response.json();assert.equal(response.status,200);assert.deepEqual(loaded,context);assert.equal(body.results[0].body,"secret body");assert.equal("path" in body.results[0],false);assert.equal(JSON.stringify(body).includes("private.md"),false)});
test("gateway rejects mismatched, replayed, and model-selected repository arguments",async()=>{const gateway=createArtifactSearchGateway({storage:{getRun:async()=>detail},secret,loadArtifacts:async()=>[]}),token=authority();assert.equal((await gateway(request(token))).status,200);assert.equal((await gateway(request(token))).status,422);const mismatch={...detail,run:{...detail.run,repositoryContext:{...context,repositoryId:99}}},other=createArtifactSearchGateway({storage:{getRun:async()=>mismatch},secret,loadArtifacts:async()=>[]});assert.equal((await other(request())).status,401);assert.equal((await gateway(request(authority(),{runId,tool:"artifact_search",callId:"call-2",arguments:{query:"x",repository:"other"}}))).status,422)});
