import test from "node:test";import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import {installTsxHook} from "./render-tsx.mjs";
const require=installTsxHook(),{codexRunnerFailureFeedback}=require("../lib/codex-runner-feedback.ts");
const routes=["status","device","logout","diagnostics","test","jobs"];
for(const route of routes)test(`${route} authenticates before Runner work and returns no-store responses`,async()=>{const source=await readFile(new URL(`../app/api/workflow-connections/codex-runner/${route}/route.ts`,import.meta.url),"utf8");const auth=source.indexOf("requireApiRepositoryAccess(request)"),runner=source.lastIndexOf(route==="status"?"getSafeCodexConnectionStatus":"getCodexRunnerClient");assert.ok(auth>=0);assert.ok(runner>auth);assert.match(source,/auth instanceof Response\)return auth/);assert.match(source,/noStoreHeaders/);for(const secret of ["CODEX_RUNNER_ACCESS_CLIENT_ID","CODEX_RUNNER_ACCESS_CLIENT_SECRET","CODEX_RUNNER_SHARED_SECRET","CF-Access-Client-Id","CF-Access-Client-Secret","X-Codex-Runner-Secret"])assert.doesNotMatch(source,new RegExp(secret))});
for(const route of ["device","logout","test"])test(`${route} rejects missing or cross-origin mutations before Runner work`,async()=>{const source=await readFile(new URL(`../app/api/workflow-connections/codex-runner/${route}/route.ts`,import.meta.url),"utf8");assert.ok(source.indexOf("origin")<source.lastIndexOf("getCodexRunnerClient"));assert.match(source,/origin===new URL\(request.url\).origin/);assert.match(source,/status:403/)});

test("connection UI classifies safe failures and only validated sign-in actions",()=>{assert.deepEqual(codexRunnerFailureFeedback(503,{runnerCode:"device_auth_start_failed",error:"raw"},"connect","https://adt.example"),{message:"ChatGPT device connection could not be started. Try again."});assert.deepEqual(codexRunnerFailureFeedback(401,{signInUrl:"https://adt.example/sign-in?returnTo=%2Fworkflows"},"connect","https://adt.example"),{message:"Sign in to ADT to continue.",signInUrl:"/sign-in?returnTo=%2Fworkflows"});assert.equal(codexRunnerFailureFeedback(401,{signInUrl:"https://evil.example/steal"},"connect","https://adt.example").signInUrl,undefined);assert.match(codexRunnerFailureFeedback(403,{},"logout","https://adt.example").message,/rejected/)});
test("connection UI exposes only allowlisted device guidance",()=>{assert.match(codexRunnerFailureFeedback(503,{runnerCode:"device_auth_start_failed",deviceAuthReason:"device_auth_not_enabled"},"connect","https://adt.example").message,/not enabled or allowed/);assert.match(codexRunnerFailureFeedback(503,{runnerCode:"device_auth_start_failed",deviceAuthReason:"device_auth_upstream_forbidden"},"connect","https://adt.example").message,/rejected/);assert.match(codexRunnerFailureFeedback(503,{runnerCode:"device_auth_start_failed",deviceAuthReason:"device_auth_rate_limited"},"connect","https://adt.example").message,/rate limited/);assert.match(codexRunnerFailureFeedback(503,{runnerCode:"device_auth_start_failed",deviceAuthReason:"device_auth_upstream_unavailable"},"connect","https://adt.example").message,/temporarily unavailable/);assert.doesNotMatch(codexRunnerFailureFeedback(503,{runnerCode:"device_auth_start_failed",deviceAuthReason:"token=SECRET https://evil.invalid"},"connect","https://adt.example").message,/SECRET|evil|token/)});
test("connection UI preserves connection actions and exposes bounded Test Codex",async()=>{const source=await readFile(new URL("../components/CodexRunnerConnection.tsx",import.meta.url),"utf8");for(const token of ["Build","Protocol","Coding jobs","feedback.signInUrl","target=\"_blank\"","rel=\"noreferrer\"","Connect ChatGPT","Disconnect / Logout","Test Codex","Testing Codex…","Run auth diagnostics"])assert.match(source,new RegExp(token));assert.match(source,/setInterval/);assert.match(source,/method:"POST"/);assert.match(source,/if\(testing\)return/);assert.doesNotMatch(source,/dangerouslySetInnerHTML/)});
test("connection UI exposes operational diagnostics without investigation experiments",async()=>{const source=await readFile(new URL("../components/CodexRunnerConnection.tsx",import.meta.url),"utf8");for(const label of ["Runner","Codex App Server","Codex CLI","Codex native libc","Address policy","System resolver first","Kernel IPv6","IPv4 DNS","IPv6 DNS","IPv4 TCP 443","IPv6 TCP 443","IPv4 TLS","IPv6 TLS","Device-auth route HEAD","System CA bundle","Codex home"])assert.match(source,new RegExp(label));assert.doesNotMatch(source,/Rust auth probe|rustls|User-Agent|HTTP\/2|malformed auth POST|client_id/)});

test("Test Codex proxy never forwards browser input or Runner credentials",async()=>{const source=await readFile(new URL("../app/api/workflow-connections/codex-runner/test/route.ts",import.meta.url),"utf8");assert.match(source,/getCodexRunnerClient\(\)\.testCodex\(\)/);assert.doesNotMatch(source,/request\.(?:json|text)|body:|CODEX_RUNNER_|X-Codex-Runner-Secret|prompt/);assert.match(source,/app_server_unavailable/)});
test("connection UI clears stale feedback and diagnostics state",async()=>{const source=await readFile(new URL("../components/CodexRunnerConnection.tsx",import.meta.url),"utf8");assert.match(source,/setCeremony\(await r\.json\(\)\);setFeedback\(undefined\);setStatus/);assert.match(source,/setDiagnostics\(await r\.json\(\)\);setFeedback\(undefined\)/);assert.match(source,/catch\{setDiagnostics\(undefined\);setFeedback/)});

test("Codex operational UI is mobile-friendly, poll-bounded, and ambiguity is actionable",async()=>{const status=await readFile(new URL("../components/CodexRunnerOperationalStatus.tsx",import.meta.url),"utf8"),tile=await readFile(new URL("../components/CodexRunnerConnection.tsx",import.meta.url),"utf8"),run=await readFile(new URL("../app/workflows/runs/[runId]/page.tsx",import.meta.url),"utf8");for(const token of ["Runner is idle","Current work","Recent jobs","Safe failure reason","4000","jobsInFlight","sm:grid-cols"])assert.match(status,new RegExp(token));assert.match(tile,/codex-runner\/status[^>]*>Status/);assert.match(run,/provider_start_ambiguous.*Check Codex Runner status/);assert.doesNotMatch(status,/outputText|fingerprint|threadId|turnId|cwd/)})
test("workspace sandbox probes are sequential and manual refresh stays distinct from job polling",async()=>{const route=await readFile(new URL("../app/api/workflow-connections/codex-runner/workspaces/route.ts",import.meta.url),"utf8"),status=await readFile(new URL("../components/CodexRunnerOperationalStatus.tsx",import.meta.url),"utf8");assert.match(route,/for\(const environment of environments\)/);assert.doesNotMatch(route,/Promise\.all\(environments\.map/);assert.match(status,/refreshAll.*Promise\.all\(\[refreshJobs\(\),refreshDiagnostics\(\)\]\)/s);assert.match(status,/setInterval\(\(\)=>void refreshJobs\(\),4000\)/);assert.doesNotMatch(status,/setInterval\([^;]*refreshDiagnostics/s)})
test("operational view never presents unknown or stale state as current idle",()=>{const React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),{CodexRunnerOperationalView}=require('../components/CodexRunnerOperationalStatus.tsx'),empty={capacity:{maxActive:1,activeJobId:null},jobs:[]},render=state=>renderToStaticMarkup(React.createElement(CodexRunnerOperationalView,{state}));const loading=render({status:'loading'}),unavailable=render({status:'unavailable'}),loaded=render({status:'loaded',data:empty,confirmedAt:'2026-08-18T00:00:00.000Z'}),stale=render({status:'unavailable',previous:empty,confirmedAt:'2026-08-18T00:00:00.000Z'});assert.doesNotMatch(loading,/Runner is idle|No terminal jobs/);assert.match(loading,/Checking current Runner work/);assert.doesNotMatch(unavailable,/Runner is idle|No terminal jobs/);assert.match(unavailable,/Current Runner job state is unknown/);assert.match(loaded,/Runner is idle/);assert.match(loaded,/No terminal jobs are available/);assert.doesNotMatch(stale,/Runner is idle/);assert.match(stale,/Current Runner state is unknown|information below is stale/);assert.match(stale,/last confirmed/i)});
test("ambiguous attempt correlation uses only safe coordinates and highlights a digest match",()=>{const React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),{CodexRunnerOperationalView}=require('../components/CodexRunnerOperationalStatus.tsx'),{codexRunnerAttemptDigest,codexRunnerStatusHref}=require('../lib/codex-runner-correlation.ts'),coordinates={runId:'run-1',stepId:'codex-step',iteration:2,attempt:3},digest=codexRunnerAttemptDigest(coordinates),href=codexRunnerStatusHref(coordinates),job={jobId:'a'.repeat(48),idempotencyDigest:digest,environmentKey:'dev',state:'failed',reason:'timeout',createdAt:'2026-08-18T00:00:00.000Z',updatedAt:'2026-08-18T00:01:00.000Z'},state={status:'loaded',data:{capacity:{maxActive:1,activeJobId:null},jobs:[job]},confirmedAt:'2026-08-18T00:02:00.000Z'};assert.equal(digest,'ee4510f989b673daf44dba53cfffb97254d7ee6c633f0b16ca2b1875c0ae1369');assert.match(href,/runId=run-1.*stepId=codex-step.*iteration=2.*attempt=3/);assert.doesNotMatch(href,/prompt|secret|baseUrl|output/);assert.match(renderToStaticMarkup(React.createElement(CodexRunnerOperationalView,{state,expectedDigest:digest})),/Matches this Workflow attempt/);assert.match(renderToStaticMarkup(React.createElement(CodexRunnerOperationalView,{state,expectedDigest:'b'.repeat(64)})),/No matching Runner record was found in the available history/)});
