import test from 'node:test'; import assert from 'node:assert/strict';
import { deletionConfirmation, deletionRequest, reconcileTombstones, tombstonesAfterResult, visibleArtifacts } from '../lib/deletion-ui.ts';
import { searchArtifacts } from '../lib/search.ts';
const artifact=(id,title,status='draft')=>({id,title,type:'prompt',status,tags:[],aliases:[],body:title,excerpt:title,path:`artifacts/prompts/${id}.md`}); const artifacts=[artifact('one','One'),artifact('two','Two','production')];
test('confirmed deletion snapshot selects exactly the consented operation and SHA',()=>{ assert.deepEqual(deletionRequest({id:'one',title:'One',status:'draft',currentFileSha:'sha-one'}),{endpoint:'/api/artifacts/one',method:'DELETE',body:{currentFileSha:'sha-one'}}); assert.deepEqual(deletionRequest({id:'two',title:'Two',status:'production',currentFileSha:'sha-two'}),{endpoint:'/api/artifacts/two/deletion-proposal',method:'POST',body:{currentFileSha:'sha-two'}}); });
test('confirmation after a successful direct title edit uses the saved title and active revision',()=>{ const loaded={id:'one',title:'Original title',status:'draft',currentFileSha:'old-sha'}; const saved={...loaded,title:'Saved title',currentFileSha:'new-sha'}; assert.equal(deletionConfirmation(saved).heading,'Delete Saved title (one)?'); assert.deepEqual(deletionRequest(saved),{endpoint:'/api/artifacts/one',method:'DELETE',body:{currentFileSha:'new-sha'}}); });
test('direct results create tombstones while proposals and recovery retain cards',()=>{ assert.deepEqual([...tombstonesAfterResult(new Set(),{kind:'deleted',artifactId:'one',commitUrl:'https://github.com/o/r/commit/c'})],['one']); assert.equal(tombstonesAfterResult(new Set(),{kind:'proposal',artifactId:'two',pullUrl:'https://github.com/o/r/pull/1'}).size,0); assert.equal(tombstonesAfterResult(new Set(),{kind:'recovery',artifactId:'two',branchName:'artifact-delete/two-abcdef12',branchUrl:'https://github.com/o/r/tree/artifact-delete/two-abcdef12'}).size,0); });
test('catalogue reconciliation updates authoritative data while preserving local tombstones',()=>{ let tombstones=tombstonesAfterResult(new Set(),{kind:'deleted',artifactId:'one',commitUrl:'https://github.com/o/r/commit/c'}); const stale=[artifact('one','Old'),artifact('two','Updated','archived'),artifact('three','New')]; tombstones=reconcileTombstones(stale,tombstones); assert.deepEqual(visibleArtifacts(stale,tombstones).map(a=>[a.id,a.title,a.status]),[['two','Updated','archived'],['three','New','draft']]); assert.deepEqual(searchArtifacts(visibleArtifacts(stale,tombstones),'Updated').map(a=>a.id),['two']); const confirmed=stale.filter(a=>a.id!=='one'); tombstones=reconcileTombstones(confirmed,tombstones); assert.equal(tombstones.size,0); assert.deepEqual(visibleArtifacts(confirmed,tombstones).map(a=>a.id),['two','three']); });
test('proposal results never create tombstones',()=>{ const result={kind:'proposal',artifactId:'two',pullUrl:'https://github.com/o/r/pull/1'}; assert.equal(tombstonesAfterResult(new Set(),result).size,0); assert.equal(visibleArtifacts(artifacts,tombstonesAfterResult(new Set(),result)).length,2); });
