import test from 'node:test';import assert from 'node:assert/strict';
import {connectionDefinitionSchema,parseConnectionDefinition} from '../lib/workflow-connection-definitions.ts';
import {GitHubWorkflowConnectionDefinitionRepository} from '../lib/workflow-connection-definition-repository.ts';
import {GitAuthoritativeWorkflowProviderConnectionStore,resolveGitSnapshotCredential} from '../lib/git-workflow-provider-connection-store.ts';
import {createWorkflowProviderSecretResolver} from '../lib/workflow-provider-secret-resolver.ts';
import {assertUniqueConnectionDescriptors,codexRunnerConnection,RESERVED_CONNECTION_KEYS} from '../lib/workflow-connections.ts';
import {resolveWorkflowRunConnectionSnapshot} from '../lib/workflow-run-connection-snapshots.ts';
import {testWorkflowConnection} from '../lib/workflow-connection-test.ts';
const secretRef='WORKFLOW_PROVIDER_CONNECTION_OPENAI_PRIMARY';
const definition=(overrides={})=>({schemaVersion:1,id:'openai-primary',name:'OpenAI Responses',runtime:'openai-responses',provider:'openai',model:'gpt-5',credential:{secretRef},...overrides});
const versioned=(value=definition())=>({definition:value,fileSha:'git-sha',sourcePath:`connections/${value.id}.connection.json`});
const d1Descriptor={key:'openai-primary',name:'D1 old',adapter:'openai-responses',defaultModel:'old',enabled:true,management:'d1',capabilities:{asynchronous:true,cancellation:true}};
function fallback(items=[d1Descriptor]){let mutations=0,resolutions=0;return{get mutations(){return mutations},get resolutions(){return resolutions},listSafeDescriptors:async()=>items,getSafeDescriptor:async key=>items.find(x=>x.key===key),resolveCredential:async key=>{resolutions++;return{...items.find(x=>x.key===key),credential:'d1-sentinel'}},assertMutable:async()=>{},upsertConnection:async()=>{mutations++;return d1Descriptor},duplicateConnection:async()=>{mutations++;return d1Descriptor},deleteConnection:async()=>{mutations++}}}
function secrets(values={},onRead=()=>{}){return createWorkflowProviderSecretResolver(ref=>{onRead(ref);return values[ref]})}
const gitWith=(item=versioned())=>({listConnections:async()=>[item],getConnection:async key=>key===item.definition.id?item:undefined});
test('strict v1 contract accepts both OpenAI runtimes and rejects unknown runtimes, plaintext fields, and invalid identities',()=>{assert.equal(connectionDefinitionSchema.parse(definition()).runtime,'openai-responses');assert.equal(connectionDefinitionSchema.parse(definition({runtime:'openai-agents'})).runtime,'openai-agents');assert.throws(()=>connectionDefinitionSchema.parse(definition({runtime:'unknown-runtime'})));for(const ref of ['SESSION_SECRET','GITHUB_APP_PRIVATE_KEY','WORKFLOW_PROVIDER_SECRET_ENCRYPTION_KEY','CODEX_RUNNER_SHARED_SECRET','WORKFLOW_PROVIDER_CONNECTION_bad'])assert.throws(()=>connectionDefinitionSchema.parse(definition({credential:{secretRef:ref}})));for(const id of RESERVED_CONNECTION_KEYS)assert.throws(()=>connectionDefinitionSchema.parse(definition({id})));assert.throws(()=>connectionDefinitionSchema.parse({...definition(),apiKey:'plaintext'}));assert.throws(()=>parseConnectionDefinition(definition(),'connections/other.connection.json'),/identity/)});
test('provider secret resolver rejects unrelated bindings before lookup and resolves the dedicated namespace',()=>{let reads=0;const resolver=secrets({[secretRef]:'provider-sentinel',SESSION_SECRET:'session-sentinel'},()=>reads++);for(const ref of ['SESSION_SECRET','GITHUB_APP_PRIVATE_KEY','WORKFLOW_PROVIDER_SECRET_ENCRYPTION_KEY','CODEX_RUNNER_SHARED_SECRET'])assert.throws(()=>resolver.resolve(ref),/unavailable/);assert.equal(reads,0);assert.equal(resolver.resolve(secretRef),'provider-sentinel');assert.equal(reads,1)});
test('repository proves the configured ref before accepting an absent connections directory',async()=>{const calls=[];const repo=new GitHubWorkflowConnectionDefinitionRepository(async path=>{calls.push(path);return path==='/contents'?Response.json([]):new Response('',{status:404})});assert.deepEqual(await repo.listConnections(),[]);assert.deepEqual(calls,['/contents','/contents/connections']);for(const status of [401,403,404,500])await assert.rejects(new GitHubWorkflowConnectionDefinitionRepository(async path=>path==='/contents'?new Response('',{status}):new Response('',{status:404})).listConnections(),/unavailable/);await assert.rejects(new GitHubWorkflowConnectionDefinitionRepository(async()=>new Response('bad',{status:200})).listConnections(),/malformed/)});
test('repository loads valid definitions and fails if a discovered definition disappears',async()=>{const entries=[{name:'openai-primary.connection.json',path:'connections/openai-primary.connection.json',type:'file'}],request=async path=>path==='/contents'?Response.json([]):path==='/contents/connections'?Response.json(entries):Response.json({content:Buffer.from(JSON.stringify(definition())).toString('base64'),sha:'abc'});assert.equal((await new GitHubWorkflowConnectionDefinitionRepository(request).listConnections())[0].definition.id,'openai-primary');const disappearing=new GitHubWorkflowConnectionDefinitionRepository(async path=>path==='/contents'?Response.json([]):path==='/contents/connections'?Response.json(entries):new Response('',{status:404}));await assert.rejects(disappearing.listConnections(),/disappeared/)});
test('Git readiness requires live credential and configured-model validation',async()=>{for(const scenario of [{credential:undefined,validate:async()=>{}},{credential:'invalid',validate:async()=>{throw new Error('authentication_failed')}},{credential:'valid',validate:async()=>{throw new Error('model_unavailable')}},{credential:'valid',validate:async()=>{throw new Error('provider_unavailable')}}]){const store=new GitAuthoritativeWorkflowProviderConnectionStore(gitWith(),fallback(),secrets(scenario.credential?{[secretRef]:scenario.credential}:{}),scenario.validate);const descriptor=(await store.listSafeDescriptors())[0];assert.equal(descriptor.enabled,false);assert.equal(JSON.stringify(descriptor).includes(String(scenario.credential)),false)}let validated=0;const ready=new GitAuthoritativeWorkflowProviderConnectionStore(gitWith(),fallback(),secrets({[secretRef]:'valid'}),async(credential,model)=>{validated++;assert.equal(credential,'valid');assert.equal(model,'gpt-5')});assert.equal((await ready.listSafeDescriptors())[0].enabled,true);assert.equal(validated,1)});
test('Git authority deduplicates D1, never falls back on secret failure, and snapshot resolution is narrow',async()=>{const old=fallback(),store=new GitAuthoritativeWorkflowProviderConnectionStore(gitWith(),old,secrets({}),async()=>{});assert.deepEqual((await store.listSafeDescriptors()).map(x=>[x.key,x.management]),[['openai-primary','git']]);await assert.rejects(store.resolveCredential('openai-primary'),/unavailable/);assert.equal(old.resolutions,0);const ready=new GitAuthoritativeWorkflowProviderConnectionStore(gitWith(),old,secrets({[secretRef]:'provider-sentinel'}),async()=>{}),snapshot=await resolveWorkflowRunConnectionSnapshot((await ready.listSafeDescriptors())[0],ready);assert.equal(snapshot.credentialSecretRef,secretRef);assert.equal(JSON.stringify(snapshot).includes('provider-sentinel'),false);assert.equal(resolveGitSnapshotCredential(snapshot.key,snapshot,secrets({[secretRef]:'provider-sentinel'})).credential,'provider-sentinel');for(const ref of ['SESSION_SECRET','GITHUB_APP_PRIVATE_KEY','WORKFLOW_PROVIDER_SECRET_ENCRYPTION_KEY','CODEX_RUNNER_SHARED_SECRET'])assert.throws(()=>resolveGitSnapshotCredential(snapshot.key,{...snapshot,credentialSecretRef:ref},secrets({[ref]:'unrelated-sentinel'})),/unavailable/)});
test('OpenAI Agents Git snapshots preserve provenance and secretRef while resolving credentials only at execution',async()=>{const sdkDefinition=definition({runtime:'openai-agents'}),store=new GitAuthoritativeWorkflowProviderConnectionStore(gitWith(versioned(sdkDefinition)),fallback(),secrets({[secretRef]:'sdk-provider-sentinel'}),async()=>{}),descriptor=(await store.listSafeDescriptors())[0],snapshot=await resolveWorkflowRunConnectionSnapshot(descriptor,store);assert.equal(snapshot.adapter,'openai-agents');assert.deepEqual(snapshot.capabilities,{asynchronous:false,cancellation:false});assert.equal(snapshot.credentialSecretRef,secretRef);assert.equal(snapshot.repositoryRevision,'git-sha');assert.equal(JSON.stringify(snapshot).includes('sdk-provider-sentinel'),false);assert.equal((await store.resolveCredential(snapshot.key,snapshot)).credential,'sdk-provider-sentinel')});
test('same-ID Git authority preserves the original credential source for pre-migration D1 snapshots',async()=>{const old=fallback(),store=new GitAuthoritativeWorkflowProviderConnectionStore(gitWith(),old,secrets({[secretRef]:'git-provider-sentinel'}),async()=>{});assert.deepEqual((await store.listSafeDescriptors()).map(x=>[x.key,x.management]),[['openai-primary','git']]);assert.equal((await store.resolveCredential('openai-primary')).credential,'git-provider-sentinel');const historical=await store.resolveCredential('openai-primary',d1Descriptor);assert.equal(historical.credential,'d1-sentinel');assert.equal(historical.management,'d1');assert.equal(old.resolutions,1)});
test('read-only guards run before credential, validation, or D1 mutation work',async()=>{let reads=0,validations=0;const old=fallback(),store=new GitAuthoritativeWorkflowProviderConnectionStore(gitWith(),old,secrets({[secretRef]:'provider-sentinel'},()=>reads++),async()=>{validations++});for(const operation of [()=>store.assertMutable('openai-primary'),()=>store.deleteConnection('openai-primary'),()=>store.duplicateConnection('openai-primary',{connectionKey:'copy',adapter:'openai-responses',model:'gpt-5'}),()=>store.duplicateConnection('other',{connectionKey:'openai-primary',adapter:'openai-responses',model:'gpt-5'})])await assert.rejects(operation(),/read_only/);assert.equal(reads,0);assert.equal(validations,0);assert.equal(old.mutations,0)});
test('reserved IDs and catalogue collisions fail closed while codex-primary stays Runner-owned',async()=>{assert.equal(codexRunnerConnection.key,'codex-primary');assert.equal(codexRunnerConnection.adapter,'codex-runner');for(const id of RESERVED_CONNECTION_KEYS){const old=fallback([]);await assert.rejects(oldStore(old).upsertConnection({connectionKey:id,adapter:'openai-responses',model:'gpt-5',credential:'x'}),/reserved/)}assert.throws(()=>assertUniqueConnectionDescriptors([codexRunnerConnection,{...d1Descriptor,key:'codex-primary'}]),/collision/);function oldStore(old){return new GitAuthoritativeWorkflowProviderConnectionStore({listConnections:async()=>[],getConnection:async()=>undefined},old,secrets({}),async()=>{})}});

test('Git Connection Test resolves the configured model credential only into the provider seam',async()=>{const store=new GitAuthoritativeWorkflowProviderConnectionStore(gitWith(),fallback(),secrets({[secretRef]:'provider-test-sentinel'}),async()=>{});let observed;const adapters=new Map([['openai-responses',{kind:'openai-responses',testConnection:async connection=>{observed={credential:connection.credential,model:connection.defaultModel};return{ok:true,outputText:'ok'}}}]]);assert.deepEqual(await testWorkflowConnection('openai-primary',store,adapters),{ok:true,outputText:'ok'});assert.deepEqual(observed,{credential:'provider-test-sentinel',model:'gpt-5'});assert.equal(JSON.stringify(await store.getSafeDescriptor('openai-primary')).includes('provider-test-sentinel'),false)});
test('OpenAI Agents Connection Test uses the shared provider diagnostic without SDK execution',async()=>{const sdkDefinition=definition({runtime:'openai-agents'}),store=new GitAuthoritativeWorkflowProviderConnectionStore(gitWith(versioned(sdkDefinition)),fallback(),secrets({[secretRef]:'sdk-test-sentinel'}),async()=>{});let diagnostics=0;const adapter={kind:'openai-responses',testConnection:async connection=>{diagnostics++;assert.equal(connection.adapter,'openai-agents');return{ok:true,outputText:'OK'}}};assert.deepEqual(await testWorkflowConnection('openai-primary',store,new Map([['openai-agents',adapter]])),{ok:true,outputText:'OK'});assert.equal(diagnostics,1)});
test('ADT vault definitions require opaque vault IDs and resolve only through the snapshotted vault source',async()=>{const vaultRef=`sec_${'a'.repeat(43)}`,vaultDefinition=definition({credential:{source:'adt-vault',secretRef:vaultRef}});assert.equal(connectionDefinitionSchema.parse(vaultDefinition).credential.source,'adt-vault');for(const credential of [{source:'adt-vault',secretRef},{secretRef:vaultRef},{source:'d1-vault',secretRef:vaultRef}])assert.throws(()=>connectionDefinitionSchema.parse(definition({credential})));let cloudflareReads=0,d1Reads=0;const vault={resolve:async ref=>{assert.equal(ref,vaultRef);return'vault-sentinel'}},store=new GitAuthoritativeWorkflowProviderConnectionStore(gitWith(versioned(vaultDefinition)),fallback(),secrets({},()=>cloudflareReads++),async()=>{},vault),descriptor=(await store.listSafeDescriptors())[0],snapshot=await resolveWorkflowRunConnectionSnapshot(descriptor,store);assert.equal(snapshot.credentialSource,'adt-vault');assert.equal(snapshot.credentialSecretRef,vaultRef);assert.equal(JSON.stringify(snapshot).includes('vault-sentinel'),false);assert.equal((await store.resolveCredential(snapshot.key,snapshot)).credential,'vault-sentinel');assert.equal(cloudflareReads,0);const missing=new GitAuthoritativeWorkflowProviderConnectionStore(gitWith(versioned(vaultDefinition)),{...fallback(),resolveCredential:async()=>{d1Reads++;throw new Error()}},secrets({[vaultRef]:'wrong-source'},()=>cloudflareReads++),async()=>{}, {resolve:async()=>{throw new Error('missing')}});assert.equal((await missing.listSafeDescriptors())[0].configured,false);await assert.rejects(missing.resolveCredential('openai-primary'),/unavailable/);assert.equal(cloudflareReads,0);assert.equal(d1Reads,0)});
