import test from 'node:test';import assert from 'node:assert/strict';
import {connectionDefinitionSchema,parseConnectionDefinition} from '../lib/workflow-connection-definitions.ts';
import {GitHubWorkflowConnectionDefinitionRepository} from '../lib/workflow-connection-definition-repository.ts';
import {GitAuthoritativeWorkflowProviderConnectionStore,resolveGitSnapshotCredential} from '../lib/git-workflow-provider-connection-store.ts';
import {resolveWorkflowRunConnectionSnapshot} from '../lib/workflow-run-connection-snapshots.ts';
const definition=(overrides={})=>({schemaVersion:1,id:'openai-primary',name:'OpenAI Responses',runtime:'openai-responses',provider:'openai',model:'gpt-5',credential:{secretRef:'OPENAI_PRIMARY_API_KEY'},...overrides});
const versioned=(value=definition())=>({definition:value,fileSha:'git-sha',sourcePath:`connections/${value.id}.connection.json`});
const d1Descriptor={key:'openai-primary',name:'D1 old',adapter:'openai-responses',defaultModel:'old',enabled:true,management:'d1',capabilities:{asynchronous:true,cancellation:true}};
function fallback(items=[d1Descriptor]){let mutations=0,resolutions=0;return{get mutations(){return mutations},get resolutions(){return resolutions},listSafeDescriptors:async()=>items,getSafeDescriptor:async key=>items.find(x=>x.key===key),resolveCredential:async key=>{resolutions++;return{...items.find(x=>x.key===key),credential:'d1-test-value'}},upsertConnection:async()=>{mutations++;return d1Descriptor},duplicateConnection:async()=>{mutations++;return d1Descriptor},deleteConnection:async()=>{mutations++}}}
test('strict v1 contract rejects unsafe references, plaintext credential fields, and filename mismatch',()=>{assert.equal(connectionDefinitionSchema.parse(definition()).runtime,'openai-responses');for(const value of [definition({credential:{secretRef:'ENV.KEY'}}),{...definition(),apiKey:'plaintext'},definition({runtime:'openai-agents'}),definition({model:{name:'gpt-5'}})])assert.throws(()=>connectionDefinitionSchema.parse(value));assert.throws(()=>parseConnectionDefinition(definition(),'connections/other.connection.json'),/identity/)});
test('GitHub repository treats only directory 404 as absence and fails repository errors closed',async()=>{const absent=new GitHubWorkflowConnectionDefinitionRepository(async()=>new Response('',{status:404}));assert.deepEqual(await absent.listConnections(),[]);for(const status of [401,403,500])await assert.rejects(new GitHubWorkflowConnectionDefinitionRepository(async()=>new Response('',{status})).listConnections(),/unavailable/)});
test('Git repository loads a canonical definition and rejects unsupported entries',async()=>{const request=async path=>path==='/contents/connections'?Response.json([{name:'openai-primary.connection.json',path:'connections/openai-primary.connection.json',type:'file'}]):Response.json({content:Buffer.from(JSON.stringify(definition())).toString('base64'),sha:'abc'});assert.equal((await new GitHubWorkflowConnectionDefinitionRepository(request).listConnections())[0].definition.id,'openai-primary');await assert.rejects(new GitHubWorkflowConnectionDefinitionRepository(async()=>Response.json([{name:'README.md',path:'connections/README.md',type:'file'}])).listConnections(),/unsupported/)});
test('Git authority deduplicates same-ID D1 and missing secret never falls back',async()=>{const old=fallback(),git={listConnections:async()=>[versioned()],getConnection:async()=>versioned()};const unavailable=new GitAuthoritativeWorkflowProviderConnectionStore(git,old,{});assert.deepEqual((await unavailable.listSafeDescriptors()).map(x=>[x.key,x.management,x.enabled]),[['openai-primary','git',false]]);await assert.rejects(unavailable.resolveCredential('openai-primary'),/unavailable/);assert.equal(old.resolutions,0);const ready=new GitAuthoritativeWorkflowProviderConnectionStore(git,old,{OPENAI_PRIMARY_API_KEY:'test-provider-value'}),resolved=await ready.resolveCredential('openai-primary');assert.equal(resolved.credential,'test-provider-value');assert.equal(JSON.stringify(await ready.listSafeDescriptors()).includes('test-provider-value'),false)});
test('absence retains D1 fallback and Git-owned mutation paths fail safely',async()=>{const old=fallback(),git={listConnections:async()=>[],getConnection:async()=>undefined},store=new GitAuthoritativeWorkflowProviderConnectionStore(git,old,{});assert.equal((await store.listSafeDescriptors())[0].management,'d1');await store.deleteConnection('openai-primary');assert.equal(old.mutations,1);const owned=new GitAuthoritativeWorkflowProviderConnectionStore({listConnections:async()=>[versioned()],getConnection:async()=>versioned()},old,{OPENAI_PRIMARY_API_KEY:'x'});for(const operation of [()=>owned.deleteConnection('openai-primary'),()=>owned.upsertConnection({connectionKey:'openai-primary',adapter:'openai-responses',model:'x',credential:'x'}),()=>owned.duplicateConnection('openai-primary',{connectionKey:'copy',adapter:'openai-responses',model:'x'})])await assert.rejects(operation(),/read_only/)});
test('run snapshot preserves Git semantics and resolves only its snapshotted secret reference',async()=>{const first=versioned(),git={listConnections:async()=>[first],getConnection:async()=>first},store=new GitAuthoritativeWorkflowProviderConnectionStore(git,fallback([]),{OPENAI_PRIMARY_API_KEY:'snapshot-test-value',NEW_KEY:'changed'}),descriptor=(await store.listSafeDescriptors())[0],snapshot=await resolveWorkflowRunConnectionSnapshot(descriptor,store);assert.equal(snapshot.credentialSecretRef,'OPENAI_PRIMARY_API_KEY');assert.equal(JSON.stringify(snapshot).includes('snapshot-test-value'),false);const changed={...snapshot,defaultModel:'changed',credentialSecretRef:'NEW_KEY'};assert.equal(resolveGitSnapshotCredential(snapshot.key,snapshot,{OPENAI_PRIMARY_API_KEY:'snapshot-test-value'}).credential,'snapshot-test-value');assert.equal(snapshot.defaultModel,'gpt-5');assert.notDeepEqual(snapshot,changed);assert.throws(()=>resolveGitSnapshotCredential(snapshot.key,{...snapshot,credentialSecretRef:'constructor'},{OPENAI_PRIMARY_API_KEY:'x'}),/unavailable/)});
