import test from 'node:test';import assert from 'node:assert/strict';
import {aggregateInfrastructureFreshness,infrastructureFreshnessLabel,infrastructureRevisionLabel,parseInfrastructureFreshnessSnapshot} from '../lib/infrastructure-freshness.ts';
import {collectInfrastructureFreshness} from '../lib/infrastructure-freshness-service.ts';
import {adtRuntimeReleaseFreshness,validateExpectedADTRuntimeRelease} from '../lib/adt-runtime-release.ts';
const sha=n=>String(n).repeat(40),component=(state,deployedRevision=sha(1),extra={})=>({state,deployedRevision,...extra});
test('Runtime expected manifest and installed evidence are strictly bounded',()=>{assert.deepEqual(validateExpectedADTRuntimeRelease({protocolVersion:1,releaseRevision:1}),{protocolVersion:1,releaseRevision:1});for(const releaseRevision of [undefined,0,-1,1.5,1_000_001,'1'])assert.equal(adtRuntimeReleaseFreshness({runtimeRevision:sha(1),runtimeReleaseRevision:releaseRevision},{protocolVersion:1,releaseRevision:1}).state,'superseded');assert.equal(adtRuntimeReleaseFreshness(undefined,{protocolVersion:1,releaseRevision:1}).state,'unknown');assert.throws(()=>validateExpectedADTRuntimeRelease({protocolVersion:1,releaseRevision:1,extra:true}))});
test('Runtime release equality, older, newer, and missing semantics',()=>{const expected={protocolVersion:1,releaseRevision:18};assert.equal(adtRuntimeReleaseFreshness({runtimeRevision:sha(1),runtimeReleaseRevision:18},expected).state,'current');assert.equal(adtRuntimeReleaseFreshness({runtimeRevision:sha(1),runtimeReleaseRevision:17},expected).state,'superseded');assert.equal(adtRuntimeReleaseFreshness({runtimeRevision:sha(1),runtimeReleaseRevision:19},expected).state,'unknown');assert.equal(adtRuntimeReleaseFreshness({runtimeRevision:sha(1)},expected).state,'superseded')});
test('production incident: different Worker and Runtime SHAs with equal releases are current without network',async()=>{const worker='f085885ba124062aa3d0e02ce39af5bec27a79c2',runtime='bdaf073a053350942790f7d66209f6ec4eb01999';let networkCalls=0;globalThis.fetch=async()=>{networkCalls++;throw Error('network denied')};const result=await collectInfrastructureFreshness({workerRevision:worker,runtimeFreshness:async()=>adtRuntimeReleaseFreshness({runtimeRevision:runtime,runtimeReleaseRevision:17},{protocolVersion:1,releaseRevision:17}),runnerFreshness:async()=>({state:'current',deployedRevision:sha('a')})});assert.equal(result.state,'current');assert.equal(result.components.runtime.state,'current');assert.equal(networkCalls,0);assert.equal(infrastructureFreshnessLabel(result),'Infra current');assert.match(infrastructureRevisionLabel(result),/Runtime bdaf073/)});

test('first rollout marks the reachable bdaf073 legacy Runtime as update available',async()=>{const runtime='bdaf073a053350942790f7d66209f6ec4eb01999',result=await collectInfrastructureFreshness({workerRevision:'654d1bd0187113b01871f67bea379080908039b0',runtimeFreshness:async()=>adtRuntimeReleaseFreshness({runtimeRevision:runtime},{protocolVersion:1,releaseRevision:1}),runnerFreshness:async()=>({state:'current',deployedRevision:sha('a')})});assert.equal(result.components.runtime.state,'superseded');assert.equal(result.components.runtime.deployedReleaseRevision,undefined);assert.equal(result.components.runtime.expectedReleaseRevision,1);assert.equal(infrastructureFreshnessLabel(result),'Runtime update available');assert.match(infrastructureRevisionLabel(result),/Runtime bdaf073/)});
test('real stale Runtime resolves update available without network',async()=>{const result=await collectInfrastructureFreshness({workerRevision:sha(1),runtimeFreshness:async()=>adtRuntimeReleaseFreshness({runtimeRevision:sha(2),runtimeReleaseRevision:17},{protocolVersion:1,releaseRevision:18}),runnerFreshness:async()=>({state:'current',deployedRevision:sha(3)})});assert.equal(result.components.runtime.state,'superseded');assert.equal(infrastructureFreshnessLabel(result),'Runtime update available')});
test('snapshot parser accepts release diagnostics and rejects unexpected/source evidence',()=>{const components={worker:component('current'),runtime:component('current',sha(2),{deployedReleaseRevision:1,expectedReleaseRevision:1}),runner:component('current',sha(3))},value={state:aggregateInfrastructureFreshness(components),checkedAt:'2026-09-15T20:00:00.000Z',components};assert.deepEqual(parseInfrastructureFreshnessSnapshot(value),value);assert.equal(parseInfrastructureFreshnessSnapshot({...value,components:{...components,runtime:{...components.runtime,sourceHeadRevision:sha(4)}}}),undefined);assert.equal(parseInfrastructureFreshnessSnapshot({...value,components:{...components,runtime:{...components.runtime,deployedReleaseRevision:0}}}),undefined)});
