import test from 'node:test';
import assert from 'node:assert/strict';
import {publishManagedPullRequest} from '../lib/managed-pull-request-publication.ts';

const runId='123e4567-e89b-42d3-a456-426614174000',context={repositoryId:42,installationId:7,owner:'example',repository:'project',branch:'main'},access={owner:'example',repo:'project',repositoryId:42,installationId:7};
function detail(continuation){return{run:{id:runId,repositoryContext:context,agentSnapshots:{agent:{adapterOptions:{environmentKey:'managed',managedGit:true,...(continuation?{continueFrom:continuation}:{})}}},connectionSnapshots:{connection:{adapter:'codex-runner'}}},attempts:[{stepId:'source',status:'succeeded',iteration:1,providerTaskId:'runner-job',agentId:'agent',connectionKey:'connection'}]}}
function database(prior){const writes=[];return{writes,prepare(sql){return{bind(...values){return{first:async()=>sql.startsWith('SELECT ')?prior:undefined,run:async()=>{writes.push({sql,values});return{success:true}}}}}}}}
const prior={repository_id:42,installation_id:7,owner:'example',repository:'project',base_branch:'main',head_branch:'adt/codex/existing',commit_sha:'a'.repeat(40),pull_request_number:9,pull_request_url:'https://github.com/example/project/pull/9',draft:1,publication_created:1,state:'open'};
function harness({changed,continuation=false}){const capabilities=[],prCalls=[],db=database(continuation?prior:undefined),commit=changed?'b'.repeat(40):continuation?'a'.repeat(40):'c'.repeat(40),runnerGateway={publish:async input=>({changed,repository:{owner:'example',repo:'project'},baseBranch:'main',branch:continuation?prior.head_branch:`adt/codex/${input.taskId}`,commitSha:commit})},pullRequest=input=>{prCalls.push(input);return{number:input.number??10,url:`https://github.com/example/project/pull/${input.number??10}`,branch:input.branch,baseBranch:'main',draft:input.draft,state:'open'}},pullRequestClient={createOrUpdate:async input=>({created:true,pullRequest:pullRequest(input)}),update:async input=>pullRequest(input)},credentialProvider=async capability=>{capabilities.push(capability);return{token:`${capability}-token`}};return{capabilities,prCalls,db,commit,input:{detail:detail(continuation?{runId:'prior-run',publishNodeId:'prior-publish'}:undefined),stepId:'source',associationStepId:'publish',title:'Updated title',body:'Updated body',draft:false,access,database:db,runner:{baseUrl:'https://runner.invalid',accessClientId:'id',accessClientSecret:'secret',sharedSecret:'shared'},credentialProvider,runnerGateway,pullRequestClient}}}

test('a new unchanged task fails before any pull-request credential, API mutation, or association',async()=>{const h=harness({changed:false});await assert.rejects(publishManagedPullRequest(h.input),/managed_task_has_no_changes/);assert.deepEqual(h.capabilities,['write']);assert.equal(h.prCalls.length,0);assert.equal(h.db.writes.length,0)});
test('a changed new task pushes and creates its deterministic pull request',async()=>{const h=harness({changed:true}),result=await publishManagedPullRequest(h.input);assert.deepEqual(h.capabilities,['write','pull_requests']);assert.equal(h.prCalls.length,1);assert.equal(result.created,true);assert.equal(result.commitSha,h.commit);assert.equal(h.db.writes.length,1)});
test('an unchanged continuation updates the same PR metadata without creating another branch or PR',async()=>{const h=harness({changed:false,continuation:true}),result=await publishManagedPullRequest(h.input);assert.deepEqual(h.capabilities,['write','pull_requests']);assert.equal(h.prCalls.length,1);assert.equal(h.prCalls[0].branch,prior.head_branch);assert.equal(result.number,prior.pull_request_number);assert.equal(result.created,false);assert.equal(result.commitSha,prior.commit_sha);assert.equal(h.db.writes.length,1)});
test('a changed continuation advances the same branch and updates the same PR',async()=>{const h=harness({changed:true,continuation:true}),result=await publishManagedPullRequest(h.input);assert.equal(h.prCalls[0].branch,prior.head_branch);assert.equal(result.number,prior.pull_request_number);assert.equal(result.created,false);assert.equal(result.commitSha,h.commit)});
