import test from 'node:test';
import assert from 'node:assert/strict';
import {reconcileManagedPullRequestAssociation} from '../lib/workflow-worker-runtime.ts';

const runId='123e4567-e89b-42d3-a456-426614174000',sourceNodeId='codex',publishNodeId='publish',runnerJob='runner-job';
const taskId=async()=>{const bytes=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(`${runId}:${sourceNodeId}:1`)));return[...bytes].slice(0,16).map(value=>value.toString(16).padStart(2,'0')).join('')};
const detail={run:{id:runId,repositoryContext:{repositoryId:42,installationId:7,owner:'example',repository:'project',branch:'main'}},attempts:[{stepId:sourceNodeId,status:'succeeded',iteration:1,providerTaskId:runnerJob}]};
const database=row=>({prepare(){return{bind(){return{first:async()=>row}}}}});
test('starting publish reconciliation is repeatable and reconstructs the exact durable output',async()=>{const row={runner_job_id:runnerJob,repository_task_id:await taskId(),repository_id:42,installation_id:7,owner:'example',repository:'project',base_branch:'main',head_branch:'adt/codex/task',commit_sha:'a'.repeat(40),pull_request_number:9,pull_request_url:'https://github.com/example/project/pull/9',draft:1,publication_created:1,state:'open'},first=await reconcileManagedPullRequestAssociation(database(row),detail,publishNodeId,sourceNodeId),again=await reconcileManagedPullRequestAssociation(database(row),detail,publishNodeId,sourceNodeId);assert.deepEqual(first,again);assert.deepEqual(JSON.parse(first.outputText),{pullRequestNumber:9,pullRequestUrl:row.pull_request_url,headBranch:row.head_branch,commitSha:row.commit_sha,draft:true,created:true});assert.equal((await reconcileManagedPullRequestAssociation(database(undefined),detail,publishNodeId,sourceNodeId)),undefined)});
test('starting publish reconciliation rejects mismatched immutable provenance',async()=>{const valid={runner_job_id:runnerJob,repository_task_id:await taskId(),repository_id:42,installation_id:7,owner:'example',repository:'project',base_branch:'main',head_branch:'adt/codex/task',commit_sha:'a'.repeat(40),pull_request_number:9,pull_request_url:'https://github.com/example/project/pull/9',draft:0,publication_created:0,state:'open'};for(const mutation of [{repository_id:43},{installation_id:8},{owner:'evil'},{repository:'evil'},{base_branch:'other'},{head_branch:'feature/evil'},{commit_sha:'bad'},{runner_job_id:'other'},{repository_task_id:'other'},{pull_request_url:'https://evil.invalid/9'}])await assert.rejects(reconcileManagedPullRequestAssociation(database({...valid,...mutation}),detail,publishNodeId,sourceNodeId),/invalid_managed_pr_association/)});
