import test from 'node:test';
import assert from 'node:assert/strict';
import {publishManagedPullRequest} from '../lib/managed-pull-request-publication.ts';

const runId='123e4567-e89b-42d3-a456-426614174000',artifactContext={repositoryId:1,installationId:2,owner:'zailghe3',repository:'fpo-artifacts',branch:'main'},context={environmentKey:'managed',managed:true,repositoryId:42,installationId:7,owner:'example',repository:'project',baseBranch:'main'},access={owner:'zailghe3',repo:'fpo-artifacts',repositoryId:1,installationId:2};
function detail(continuation){return{run:{id:runId,repositoryContext:artifactContext,managedCodeRepositoryContexts:{agent:context},agentSnapshots:{agent:{adapterOptions:{environmentKey:'managed',managedGit:true,...(continuation?{continueFrom:continuation}:{})}}},connectionSnapshots:{connection:{adapter:'codex-runner'}}},attempts:[{stepId:'source',status:'succeeded',iteration:1,providerTaskId:'runner-job',agentId:'agent',connectionKey:'connection'}]}}
function database(prior){const writes=[];return{writes,prepare(sql){return{bind(...values){return{first:async()=>sql.startsWith('SELECT ')?prior:undefined,run:async()=>{writes.push({sql,values});return{success:true}}}}}}}}
const prior={repository_id:42,installation_id:7,owner:'example',repository:'project',base_branch:'main',head_branch:'adt/codex/existing',commit_sha:'a'.repeat(40),pull_request_number:9,pull_request_url:'https://github.com/example/project/pull/9',draft:1,publication_created:1,state:'open'};
function harness({changed,continuation=false,contents='write'}){const capabilities=[],prCalls=[],runnerCalls=[],db=database(continuation?prior:undefined),commit=changed?'b'.repeat(40):continuation?'a'.repeat(40):'c'.repeat(40),runnerGateway={publish:async input=>{runnerCalls.push(input);return({changed,repository:{owner:'example',repo:'project'},baseBranch:'main',branch:continuation?prior.head_branch:`adt/codex/${input.taskId}`,commitSha:commit})}},pullRequest=input=>{prCalls.push(input);return{number:input.number??10,url:`https://github.com/example/project/pull/${input.number??10}`,branch:input.branch,baseBranch:'main',draft:input.draft,state:'open'}},pullRequestClient={createOrUpdate:async input=>({created:true,pullRequest:pullRequest(input)}),update:async input=>pullRequest(input)},credentialProvider=async capability=>{capabilities.push(capability);return{token:`${capability}-token`,permissions:capability==='write'?(contents?{contents}:{}):{pullRequests:'write'}}};return{capabilities,prCalls,runnerCalls,db,commit,input:{detail:detail(continuation?{runId:'prior-run',publishNodeId:'prior-publish'}:undefined),stepId:'source',associationStepId:'publish',title:'Updated title',body:'Updated body',draft:false,access,database:db,runner:{baseUrl:'https://runner.invalid',accessClientId:'id',accessClientSecret:'secret',sharedSecret:'shared'},credentialProvider,runnerGateway,pullRequestClient}}}

test('a new unchanged task fails before any pull-request credential, API mutation, or association',async()=>{const h=harness({changed:false});await assert.rejects(publishManagedPullRequest(h.input),/managed_task_has_no_changes/);assert.deepEqual(h.capabilities,['write']);assert.equal(h.prCalls.length,0);assert.equal(h.db.writes.length,0)});
test('a changed new task pushes and creates its deterministic pull request',async()=>{const h=harness({changed:true}),result=await publishManagedPullRequest(h.input);assert.deepEqual(h.capabilities,['write','pull_requests']);assert.equal(h.prCalls.length,1);assert.equal(result.created,true);assert.equal(result.commitSha,h.commit);assert.equal(h.db.writes.length,1);assert.deepEqual(h.runnerCalls[0].expectedRepository,{owner:'example',repo:'project',baseBranch:'main'})});
test('an unchanged continuation updates the same PR metadata without creating another branch or PR',async()=>{const h=harness({changed:false,continuation:true}),result=await publishManagedPullRequest(h.input);assert.deepEqual(h.capabilities,['write','pull_requests']);assert.equal(h.prCalls.length,1);assert.equal(h.prCalls[0].branch,prior.head_branch);assert.equal(result.number,prior.pull_request_number);assert.equal(result.created,false);assert.equal(result.commitSha,prior.commit_sha);assert.equal(h.db.writes.length,1)});
test('a changed continuation advances the same branch and updates the same PR',async()=>{const h=harness({changed:true,continuation:true}),result=await publishManagedPullRequest(h.input);assert.equal(h.prCalls[0].branch,prior.head_branch);assert.equal(result.number,prior.pull_request_number);assert.equal(result.created,false);assert.equal(result.commitSha,h.commit)});


test('managed publication validates the returned Contents grant before Runner publication',async()=>{
 for(const contents of ['read',undefined]){const h=harness({changed:true,contents}),marker='credential-private-marker',logs=[],original=console.info;h.input.credentialProvider=async capability=>({token:marker,permissions:capability==='write'?(contents?{contents}:{}):{pullRequests:'write'}});console.info=value=>logs.push(String(value));try{await assert.rejects(publishManagedPullRequest(h.input),/managed_publication_write_permission_missing/)}finally{console.info=original}assert.equal(h.runnerCalls.length,0);assert.deepEqual(logs.map(JSON.parse),[{event:'managed_publication_write_credential',grantedContentsPermission:contents??'missing'}]);assert.doesNotMatch(logs.join('\n'),new RegExp(marker))}
});

function blockContinuationHarness(targetJob,sourceJob,sourceStep='a',targetStep='b',commit='d'.repeat(40)){const h=harness({changed:true}),sourceIdentity={runId,stepId:sourceStep,activationId:`visit-${sourceStep}`,iteration:1,attempt:1},source={runId,stepId:sourceStep,graphActivationId:`visit-${sourceStep}`,status:'succeeded',iteration:1,attempt:1,providerTaskId:sourceJob,agentId:'agent',connectionKey:'connection',providerPollCount:0},target={runId,stepId:targetStep,graphActivationId:`visit-${targetStep}`,status:'succeeded',iteration:1,attempt:1,providerTaskId:targetJob,agentId:'agent',connectionKey:'connection',providerPollCount:0,conversationSource:sourceIdentity},row={...prior,runner_job_id:sourceJob,repository_task_id:'prior-task',publication_created:0};h.input.detail={...h.input.detail,attempts:[source,target]};h.input.stepId=targetStep;h.input.database=database(row);h.db=h.input.database;h.input.runnerGateway={publish:async input=>{h.runnerCalls.push(input);return{changed:true,repository:{owner:'example',repo:'project'},baseBranch:'main',branch:prior.head_branch,commitSha:commit}}};return h}
test('block conversation publication updates its bound source PR and records the follow-up job',async()=>{const h=blockContinuationHarness('b'.repeat(48),'a'.repeat(48)),result=await publishManagedPullRequest(h.input),write=h.db.writes[0].values;assert.equal(result.number,prior.pull_request_number);assert.equal(result.branch,prior.head_branch);assert.equal(result.created,false);assert.equal(write[2],'b'.repeat(48));assert.equal(write[9],prior.head_branch);assert.equal(write[11],prior.pull_request_number)});
test('successive block continuations keep one branch and PR while advancing commits',async()=>{const b=blockContinuationHarness('b'.repeat(48),'a'.repeat(48),'a','b','2'.repeat(40)),p2=await publishManagedPullRequest(b.input),c=blockContinuationHarness('c'.repeat(48),'b'.repeat(48),'b','c','3'.repeat(40));c.input.database=database({...prior,runner_job_id:'b'.repeat(48),repository_task_id:'task-b',commit_sha:p2.commitSha,publication_created:0});c.db=c.input.database;const p3=await publishManagedPullRequest(c.input);assert.equal(p2.number,p3.number);assert.equal(p2.branch,p3.branch);assert.equal(p2.commitSha,'2'.repeat(40));assert.equal(p3.commitSha,'3'.repeat(40));assert.equal(c.db.writes[0].values[2],'c'.repeat(48))});
