import test from 'node:test';import assert from 'node:assert/strict';import {InMemoryToolDefinitionRepository} from '../lib/tool-definition-repository.ts';import {createMcpServer,updateMcpServer,deleteMcpServer,discoverMcpServer,validateAgentMcpGrants,safeVersionedMcp} from '../lib/mcp-tool-service.ts';import {mcpServerDefinitionSchema} from '../lib/tool-definitions.ts';import {mcpToolAlias,resolveAuthorizedMcpTools} from '../lib/mcp-tool-authority.ts';import {persistedAgentDefinitionSchema,hasArtifactSearchGrant} from '../lib/workflow-definitions.ts';
const REPO=101,secretRef=index=>`sec_${String(index).padStart(43,'a')}`,key=(repositoryId,id)=>`${repositoryId}:${id}`;
class Vault{values=new Map;bindings=new Map;deleted=[];next=1;fail={};async create(value){if(this.fail.create)throw Error('vault unavailable');const ref=secretRef(this.next++);this.values.set(ref,value);return ref}async resolve(ref){if(!this.values.has(ref))throw Error('missing');return this.values.get(ref)}async delete(ref){if(this.fail.delete)throw Error('cleanup unavailable');this.deleted.push(ref);this.values.delete(ref)}async bindMcpServerCredential(repositoryId,id,ref,expected){if(this.fail.bind)throw Error('binding unavailable');const k=key(repositoryId,id),current=this.bindings.get(k);if(current===ref)return;if(expected===undefined||expected===null){if(current)throw Error('binding conflict')}else if(current!==expected)throw Error('binding conflict');this.bindings.set(k,ref)}async unbindMcpServerCredential(repositoryId,id,expected){if(this.fail.unbind)throw Error('binding unavailable');const k=key(repositoryId,id);if(expected&&this.bindings.get(k)!==expected)throw Error('binding conflict');this.bindings.delete(k)}binding(repositoryId=REPO,id='docs'){return this.bindings.get(key(repositoryId,id))}}
const input={id:'docs',name:'Docs',endpointUrl:'https://mcp.example/tools',authenticationMode:'bearer',bearerToken:'private-token'};
const failing=(repo,method)=>({list:repo.list.bind(repo),get:repo.get.bind(repo),create:method==='create'?async()=>{throw Error('repository_conflict')}:repo.create.bind(repo),delete:method==='delete'?async()=>{throw Error('repository_conflict')}:repo.delete.bind(repo),update:method==='update'?async()=>{throw Error('repository_conflict')}:repo.update.bind(repo)});
async function made(repo=new InMemoryToolDefinitionRepository(),vault=new Vault(),repositoryId=REPO){return{repo,vault,created:await createMcpServer(repositoryId,input,repo,vault)}}

test('existing bearer blank token preserves its repository-scoped authority',async()=>{const{repo,vault,created}=await made(),old=created.definition.authentication.credentialSecretRef,updated=await updateMcpServer(REPO,{...input,bearerToken:undefined,fileSha:created.fileSha,name:'Updated'},repo,vault);assert.equal(updated.definition.authentication.credentialSecretRef,old);assert.equal(vault.binding(),old);assert.equal(await vault.resolve(old),'private-token')});
test('replacement moves binding before best-effort obsolete cleanup',async()=>{const{repo,vault,created}=await made(),old=created.definition.authentication.credentialSecretRef,updated=await updateMcpServer(REPO,{...input,bearerToken:'replacement',fileSha:created.fileSha},repo,vault),fresh=updated.definition.authentication.credentialSecretRef;assert.equal(vault.binding(),fresh);assert.equal(await vault.resolve(fresh),'replacement');assert.equal(vault.values.has(old),false)});
test('secret creation and Git update failures preserve Git and binding authority',async()=>{for(const stage of ['create','update']){const{repo,vault,created}=await made(),old=created.definition.authentication.credentialSecretRef;if(stage==='create')vault.fail.create=true;await assert.rejects(updateMcpServer(REPO,{...input,bearerToken:'replacement',fileSha:created.fileSha},stage==='update'?failing(repo,'update'):repo,vault));assert.equal((await repo.get('docs')).definition.authentication.credentialSecretRef,old);assert.equal(vault.binding(),old);assert.equal(await vault.resolve(old),'private-token');assert.equal(vault.values.size,1)}});
test('binding replacement failure compensates Git and deletes candidate',async()=>{const{repo,vault,created}=await made(),old=created.definition.authentication.credentialSecretRef;vault.fail.bind=true;await assert.rejects(updateMcpServer(REPO,{...input,bearerToken:'replacement',fileSha:created.fileSha},repo,vault));assert.equal((await repo.get('docs')).definition.authentication.credentialSecretRef,old);assert.equal(vault.binding(),old);assert.equal(vault.values.size,1);assert.equal(await vault.resolve(old),'private-token')});
test('bearer to none unbind failure compensates Git without retiring authority',async()=>{const{repo,vault,created}=await made(),old=created.definition.authentication.credentialSecretRef;vault.fail.unbind=true;await assert.rejects(updateMcpServer(REPO,{...input,authenticationMode:'none',bearerToken:undefined,fileSha:created.fileSha},repo,vault));assert.equal((await repo.get('docs')).definition.authentication.credentialSecretRef,old);assert.equal(vault.binding(),old);assert.equal(await vault.resolve(old),'private-token')});
test('obsolete cleanup failure leaves the fully moved authority coherent',async()=>{const{repo,vault,created}=await made(),old=created.definition.authentication.credentialSecretRef;vault.fail.delete=true;const saved=await updateMcpServer(REPO,{...input,bearerToken:'replacement',fileSha:created.fileSha},repo,vault),fresh=saved.definition.authentication.credentialSecretRef;assert.equal(vault.binding(),fresh);assert.equal((await repo.get('docs')).definition.authentication.credentialSecretRef,fresh);assert.equal(await vault.resolve(fresh),'replacement');assert.equal(await vault.resolve(old),'private-token')});
test('create Git or binding failure cleans candidate and never leaves executable authority',async()=>{for(const stage of ['git','binding']){const repo=new InMemoryToolDefinitionRepository(),vault=new Vault();if(stage==='binding')vault.fail.bind=true;await assert.rejects(createMcpServer(REPO,input,stage==='git'?failing(repo,'create'):repo,vault));assert.equal(await repo.get('docs'),undefined);assert.equal(vault.binding(),undefined);assert.equal(vault.values.size,0)}});
test('delete Git failure preserves authority; unbind failure restores Git and binding',async()=>{for(const stage of ['git','unbind']){const{repo,vault,created}=await made(),old=created.definition.authentication.credentialSecretRef;if(stage==='unbind')vault.fail.unbind=true;await assert.rejects(deleteMcpServer(REPO,'docs',created.fileSha,stage==='git'?failing(repo,'delete'):repo,vault));assert.equal((await repo.get('docs')).definition.authentication.credentialSecretRef,old);assert.equal(vault.binding(),old);assert.equal(await vault.resolve(old),'private-token')}});
test('successful delete removes only its repository binding and secret',async()=>{const{repo,vault,created}=await made();await deleteMcpServer(REPO,'docs',created.fileSha,repo,vault);assert.equal(await repo.get('docs'),undefined);assert.equal(vault.binding(),undefined);assert.equal(vault.values.size,0)});
test('MCP config safe view never exposes credential values',async()=>{const{created}=await made();assert.equal(JSON.stringify(created).includes('private-token'),false);assert.equal(safeVersionedMcp(created).definition.authentication.credentialConfigured,true)});
test('schema rejects unsafe endpoint and production bypass fields',()=>{assert.throws(()=>mcpServerDefinitionSchema.parse({schemaVersion:1,id:'x',name:'X',type:'mcp',transport:'streamable-http',endpointUrl:'http://localhost:3000',authentication:{mode:'none'},allowLocalhost:true}));assert.throws(()=>mcpServerDefinitionSchema.parse({...input,authentication:{mode:'basic'}}))});
test('failed discovery preserves frozen catalogue while successful discovery replaces it',async()=>{const{repo,vault,created}=await made(),runtime={discoverMcp:async()=>[{name:'search',description:'Search',inputSchema:{type:'object'}}]},saved=await discoverMcpServer('docs',created.fileSha,repo,vault,runtime,()=>new Date('2026-01-01T00:00:00Z'));await assert.rejects(discoverMcpServer('docs',saved.fileSha,repo,vault,{discoverMcp:async()=>{throw Error('safe failure')}}));assert.deepEqual((await repo.get('docs')).definition.catalogue,saved.definition.catalogue)});
test('legacy artifact grant and structured grants validate; stale grants fail closed',async()=>{assert.equal(hasArtifactSearchGrant(['artifact_search']),true);assert.ok(persistedAgentDefinitionSchema.parse({schemaVersion:2,id:'a',name:'A',description:'',status:'draft',connectionKey:'c',prompt:{source:'custom',text:'x'},tools:['artifact_search']}));const{repo,vault,created}=await made(),discovered=await discoverMcpServer('docs',created.fileSha,repo,vault,{discoverMcp:async()=>[{name:'search',inputSchema:{type:'object'}}]}),agent={schemaVersion:2,id:'a',name:'A',description:'',status:'draft',connectionKey:'c',prompt:{source:'custom',text:'x'},masterPrompt:'x',tools:[{type:'mcp',serverId:'docs',toolName:'search'}]};await validateAgentMcpGrants(agent,repo);await repo.update({...discovered.definition,catalogue:{...discovered.definition.catalogue,tools:[]}},discovered.fileSha);await assert.rejects(validateAgentMcpGrants(agent,repo),/mcp_grant_unavailable/)});
test('aliases remain bounded and collision-safe',async()=>{const a=await mcpToolAlias('one','artifact_search'),b=await mcpToolAlias('two','artifact_search');assert.notEqual(a,b);assert.match(a,/^[A-Za-z_][A-Za-z0-9_-]{0,63}$/);const repo=new InMemoryToolDefinitionRepository(),vault=new Vault();for(const id of ['one','two']){const made=await createMcpServer(REPO,{...input,id,authenticationMode:'none',bearerToken:undefined},repo,vault);await discoverMcpServer(id,made.fileSha,repo,vault,{discoverMcp:async()=>[{name:'same',inputSchema:{type:'object'}}]})}const tools=await resolveAuthorizedMcpTools({schemaVersion:2,id:'a',name:'A',description:'',status:'draft',connectionKey:'c',prompt:{source:'custom',text:'x'},masterPrompt:'x',tools:[{type:'mcp',serverId:'one',toolName:'same'},{type:'mcp',serverId:'two',toolName:'same'}]},repo,vault);assert.equal(new Set(tools.map(x=>x.alias)).size,2)});
test('create compensation failure leaves a Git definition safely credential-unavailable',async()=>{const repo=new InMemoryToolDefinitionRepository(),vault=new Vault();vault.fail.bind=true;await assert.rejects(createMcpServer(REPO,input,failing(repo,'delete'),vault));const definition=await repo.get('docs');assert.equal(definition.definition.authentication.mode,'bearer');assert.equal(vault.binding(),undefined);assert.equal(vault.values.size,0);await assert.rejects(vault.resolve(definition.definition.authentication.credentialSecretRef),/missing/)});
test('delete compensation failure disables a dangling repository-scoped binding',async()=>{const{repo,vault,created}=await made(),old=created.definition.authentication.credentialSecretRef;vault.fail.unbind=true;await assert.rejects(deleteMcpServer(REPO,'docs',created.fileSha,failing(repo,'create'),vault));assert.equal(await repo.get('docs'),undefined);assert.equal(vault.binding(),old);assert.equal(vault.values.has(old),false);await assert.rejects(vault.resolve(old),/missing/)});
