import test from 'node:test';import assert from 'node:assert/strict';import {OpenAIResponsesAdapter,extractOpenAIResponseText} from '../lib/openai-responses-adapter.ts';import {safeConnectionSnapshot} from '../lib/workflow-connections.ts';
const invocation=(fetcher,options={})=>({adapter:new OpenAIResponsesAdapter(fetcher,20),call:{runId:'run',stepId:'step',iteration:1,attempt:1,providerPollCount:0,idempotencyKey:'key',agentName:'Agent',masterPrompt:'  system\n',inputText:' input \n',connection:{key:'openai-primary',name:'OpenAI Responses',adapter:'openai-responses',endpoint:'https://api.openai.com/v1',defaultModel:'gpt-configured',enabled:true,credential:'test-credential',capabilities:{asynchronous:true,cancellation:true}},providerOptions:options}});
const json=(body,status=200)=>new Response(typeof body==='string'?body:JSON.stringify(body),{status,headers:{'content-type':'application/json'}});
const completed=(id='resp_1',text='done')=>({id,status:'completed',output:[{type:'message',content:[{type:'output_text',text}]}]});
test('connection snapshots omit credentials',()=>{const resolved={key:'openai-primary',name:'OpenAI Responses',adapter:'openai-responses',endpoint:'https://api.openai.com/v1',defaultModel:'gpt',enabled:true,credential:'secret-value',capabilities:{asynchronous:true,cancellation:true}},safe=safeConnectionSnapshot(resolved);assert.equal(JSON.stringify(safe).includes('secret-value'),false)});
test('start sends the bounded Responses wire shape and supports queued and immediate completion',async()=>{let request;const {adapter,call}=invocation(async(_url,init)=>{request=JSON.parse(init.body);return json({id:'resp_queued',status:'queued'})},{reasoningEffort:'high',verbosity:'low',maxOutputTokens:123});const queued=await adapter.start(call);assert.deepEqual({state:queued.state,taskId:queued.taskId,pollAfterMs:queued.pollAfterMs},{state:'pending',taskId:'resp_queued',pollAfterMs:10000});assert.deepEqual(request,{model:'gpt-configured',instructions:'  system\n',input:' input \n',background:true,store:false,reasoning:{effort:'high'},text:{verbosity:'low'},max_output_tokens:123});const immediate=invocation(async()=>json(completed('resp_now',' final ')));const result=await immediate.adapter.start(immediate.call);assert.equal(result.state,'completed');assert.equal(result.outputText,' final ')});
test('text extraction ignores reasoning and preserves message fragment and refusal order',()=>{const response={output:[{type:'reasoning',encrypted_content:'never'},{type:'message',content:[{type:'output_text',text:'one'},{type:'unknown',value:{}},{type:'refusal',refusal:' two'}]},{type:'message',content:[{type:'output_text',text:' three'}]}]};assert.equal(extractOpenAIResponseText(response),'one two three');assert.equal(extractOpenAIResponseText({output:[{type:'reasoning'}]}),undefined)});
test('check maps pending, completion and terminal states',async()=>{for(const status of ['queued','in_progress']){const {adapter,call}=invocation(async()=>json({id:'resp_ok',status}));assert.deepEqual(await adapter.check('resp_ok',call),{state:'pending',pollAfterMs:10000})}const done=invocation(async()=>json(completed()));assert.equal((await done.adapter.check('resp_1',done.call)).outputText,'done');const failed=invocation(async()=>json({id:'resp_1',status:'incomplete'}));assert.equal((await failed.adapter.check('resp_1',failed.call)).state,'failed')});
test('cancel maps cancelled and already terminal without exposing bodies',async()=>{for(const [status,outcome] of [['cancelled','cancelled'],['completed','already_terminal'],['failed','already_terminal'],['incomplete','already_terminal']]){const {adapter,call}=invocation(async()=>json({id:'resp_1',status,error:{message:'private'}}));assert.equal(await adapter.cancel('resp_1',call),outcome)}});
test('create HTTP and transport failures use safe categories',async()=>{for(const [status,category] of [[400,'provider_rejected'],[401,'authentication_failed'],[403,'permission_denied'],[404,'provider_rejected'],[422,'provider_rejected'],[429,'rate_limited'],[500,'provider_start_ambiguous']]){const {adapter,call}=invocation(async()=>json({error:{message:'private'}},status));await assert.rejects(adapter.start(call),e=>e.category===category&&!e.message.includes('private'))}const network=invocation(async()=>{throw new Error('socket with secret')});await assert.rejects(network.adapter.start(network.call),e=>e.category==='provider_start_ambiguous')});
test('malformed successful create and output fail safely',async()=>{for(const body of ['not-json',{status:'queued'},{id:'resp_1',status:'completed',output:[{type:'reasoning'}]},{id:'resp_1',status:'future'}]){const {adapter,call}=invocation(async()=>json(body));await assert.rejects(adapter.start(call),e=>e.category==='malformed_response')}});
test('check classifies HTTP, network, timeout, and validates task IDs',async()=>{for(const [status,category] of [[401,'authentication_failed'],[403,'permission_denied'],[404,'provider_rejected'],[429,'rate_limited'],[500,'provider_unavailable']]){const {adapter,call}=invocation(async()=>json({},status));await assert.rejects(adapter.check('resp_1',call),e=>e.category===category)}const network=invocation(async()=>{throw new Error('private')});await assert.rejects(network.adapter.check('resp_1',network.call),e=>e.category==='provider_unavailable');const timeout=invocation(()=>new Promise(()=>{}));await assert.rejects(timeout.adapter.check('resp_1',timeout.call),e=>e.category==='provider_timeout');await assert.rejects(network.adapter.check('../secret',network.call),e=>e.category==='configuration_invalid')});
test('connection test uses only fixed foreground inputs and returns a bounded safe preview',async()=>{let outbound;const {adapter,call}=invocation(async(url,init)=>{outbound={url:String(url),headers:init.headers,body:JSON.parse(init.body)};return json(completed('resp_test',`  OK${'!'.repeat(150)}  `))});assert.deepEqual(await adapter.testConnection(call.connection),{ok:true,outputText:`OK${'!'.repeat(98)}`});assert.equal(outbound.url,'https://api.openai.com/v1/responses');assert.equal(outbound.headers.authorization,'Bearer test-credential');assert.deepEqual(outbound.body,{model:'gpt-configured',input:'Reply exactly with OK.',store:false});assert.equal('tools' in outbound.body,false);assert.equal('background' in outbound.body,false);assert.equal(JSON.stringify(outbound.body).includes('test-credential'),false)});
test('connection test safely classifies provider and transport failures',async()=>{for(const [status,category,message] of [[400,'provider_rejected','Configured model was rejected.'],[401,'authentication_failed','Authentication failed.'],[403,'permission_denied','Permission denied.'],[429,'rate_limited','Provider rate limited.'],[500,'provider_unavailable','Provider temporarily unavailable.']]){const {adapter,call}=invocation(async()=>json({error:{message:'raw private failure'}},status));assert.deepEqual(await adapter.testConnection(call.connection),{ok:false,category,safeMessage:message})}const timeout=invocation(()=>new Promise(()=>{}));assert.deepEqual(await timeout.adapter.testConnection(timeout.call.connection),{ok:false,category:'provider_timeout',safeMessage:'Connection test timed out.'});const malformed=invocation(async()=>json({id:'resp_test',status:'completed',output:[{type:'reasoning'}]}));assert.deepEqual(await malformed.adapter.testConnection(malformed.call.connection),{ok:false,category:'malformed_response',safeMessage:'Provider returned an invalid response.'})});

test('start correlation is stable, attempt-specific, content-independent, and captures allowlisted response metadata',async()=>{const headers=[];const fetcher=async(_url,init)=>{headers.push(new Headers(init.headers));return new Response(JSON.stringify({id:'resp_ok',status:'queued'}),{status:200,headers:{'content-type':'application/json','x-request-id':'req_example','openai-processing-ms':'123','x-secret':'never'}})};const first=invocation(fetcher),same=invocation(fetcher),different=invocation(fetcher);different.call.attempt=2;different.call.masterPrompt='credential and prompt changed';different.call.inputText='private input';different.call.connection.credential='different-secret';const a=await first.adapter.start(first.call),b=await same.adapter.start(same.call),c=await different.adapter.start(different.call),ids=headers.map(h=>h.get('x-client-request-id'));assert.equal(ids[0],ids[1]);assert.notEqual(ids[0],ids[2]);assert.match(ids[0],/^adt-[a-f0-9]{40}$/);assert.equal(ids.some(id=>id.includes('private')||id.includes('secret')),false);assert.deepEqual(a.transportDiagnostics,{clientRequestId:ids[0],requestId:'req_example',httpStatus:200,elapsedMs:a.transportDiagnostics.elapsedMs,processingMs:123,outcome:'response_received'});assert.ok(a.transportDiagnostics.elapsedMs>=0);assert.equal(JSON.stringify(a.transportDiagnostics).includes('never'),false);assert.equal(b.transportDiagnostics.clientRequestId,ids[1]);assert.equal(c.transportDiagnostics.clientRequestId,ids[2])});
test('start timeout and network failures retain only safe ambiguity diagnostics and issue one POST',async()=>{for(const [fetcher,outcome] of [[()=>new Promise(()=>{}),'timeout'],[async()=>{throw new Error('socket credential prompt secret')},'network_error']]){let posts=0;const wrapped=async(...args)=>{posts++;return fetcher(...args)},value=invocation(wrapped);await assert.rejects(value.adapter.start(value.call),error=>{assert.equal(error.category,'provider_start_ambiguous');assert.equal(error.transportDiagnostics.outcome,outcome);assert.match(error.transportDiagnostics.clientRequestId,/^adt-/);assert.ok(error.transportDiagnostics.elapsedMs>=0);assert.equal(error.transportDiagnostics.requestId,undefined);assert.equal(JSON.stringify(error).includes('socket credential prompt secret'),false);return true});assert.equal(posts,1)}});
test('start HTTP 500 captures response diagnostics without retaining the raw body',async()=>{const value=invocation(async()=>new Response(JSON.stringify({error:{message:'raw body secret'}}),{status:500,headers:{'x-request-id':'req_500'}}));await assert.rejects(value.adapter.start(value.call),error=>{assert.equal(error.category,'provider_start_ambiguous');assert.deepEqual(error.transportDiagnostics,{clientRequestId:error.transportDiagnostics.clientRequestId,requestId:'req_500',httpStatus:500,elapsedMs:error.transportDiagnostics.elapsedMs,processingMs:undefined,outcome:'response_received'});assert.equal(JSON.stringify(error).includes('raw body secret'),false);return true})});

test('production fetch is late-bound while an injected fetch takes precedence',async()=>{const original=globalThis.fetch;let early=0,late=0,injected=0;try{globalThis.fetch=async()=>{early++;return json({id:'resp_early',status:'queued'})};const adapter=new OpenAIResponsesAdapter(undefined,20),call=invocation(async()=>{throw new Error('unused')}).call;globalThis.fetch=async()=>{late++;return json({id:'resp_late',status:'queued'})};assert.equal((await adapter.start(call)).taskId,'resp_late');const explicit=new OpenAIResponsesAdapter(async()=>{injected++;return json({id:'resp_injected',status:'queued'})},20);globalThis.fetch=async()=>{throw new Error('global fetch must not run')};assert.equal((await explicit.start(call)).taskId,'resp_injected');assert.deepEqual({early,late,injected},{early:0,late:1,injected:1})}finally{globalThis.fetch=original}});

test('start safely classifies runtime transport exceptions',async()=>{const cases=[
  [new TypeError('Cannot perform I/O on behalf of a different request; raw secret'),'cross_request_io','internal_error'],
  [Object.assign(new Error('Network I/O attempted outside of a request context: raw secret'),{cause:new TypeError('private cause')}),'invalid_request_context','internal_error'],
  [new Error('Network connection lost: raw secret'),'network_connection_lost','provider_start_ambiguous'],
  [new TypeError('undocumented fetch failure with raw secret'),'fetch_type_error','provider_start_ambiguous'],
];for(const [thrown,reason,category] of cases){const value=invocation(async()=>{throw thrown});await assert.rejects(value.adapter.start(value.call),error=>{assert.equal(error.category,category);assert.equal(error.transportDiagnostics.outcome,'network_error');assert.equal(error.transportDiagnostics.reason,reason);assert.ok(['Error','TypeError'].includes(error.transportDiagnostics.runtimeErrorName));assert.equal(JSON.stringify(error).includes('raw secret'),false);assert.equal(JSON.stringify(error).includes('private cause'),false);return true})}});
