import test from 'node:test';import assert from 'node:assert/strict';
import {listSavedProviderModels} from '../lib/provider-saved-model-discovery.ts';
import {ProviderModelService} from '../lib/provider-model-service.ts';
import {listAnthropicModels} from '../lib/anthropic-models.ts';
const definition={schemaVersion:1,id:'anthropic',name:'Anthropic',runtime:'anthropic-messages',provider:'anthropic',model:'claude-a',configuration:{workspaceId:'wrkspc_A'},credential:{source:'adt-vault',secretRef:`sec_${'a'.repeat(43)}`}};
const repository={getConnection:async()=>({definition,fileSha:'sha',sourcePath:'connections/anthropic.connection.json'})};
test('saved discovery resolves the credential server-side and uses current validated workspace configuration',async()=>{let resolved=0,outbound;const store={resolveForExecution:async key=>{resolved++;assert.equal(key,'anthropic');return{key,adapter:'anthropic-messages',enabled:true,credential:'server-only-key',providerConfiguration:{workspaceId:'wrkspc_A'},capabilities:{asynchronous:false,cancellation:false}}}},service=new ProviderModelService({listAnthropicModels:(credential,configuration)=>listAnthropicModels(credential,configuration,async(_url,init)=>{outbound={headers:new Headers(init.headers)};return Response.json({data:[{id:'claude-b'}],has_more:false})})}),models=await listSavedProviderModels('anthropic','anthropic-messages',{workspaceId:' wrkspc_B '},repository,store,service);assert.deepEqual(models,['claude-b']);assert.equal(resolved,1);assert.equal(outbound.headers.get('authorization'),'Bearer server-only-key');assert.equal(outbound.headers.get('anthropic-workspace-id'),'wrkspc_B');assert.doesNotMatch(JSON.stringify(models),/server-only-key/)});
test('invalid and provider-incompatible browser configuration fails before credential resolution or provider I/O',async()=>{let resolves=0,lists=0;const store={resolveForExecution:async()=>{resolves++;return{credential:'never'}}},models={listForPolicy:async()=>{lists++}};for(const [type,configuration] of [['anthropic-messages',{workspaceId:'invalid'}],['anthropic-messages',{authorization:'secret'}],['openai-responses',{workspaceId:'wrkspc_B'}]])await assert.rejects(listSavedProviderModels('anthropic',type,configuration,repository,store,models));assert.deepEqual({resolves,lists},{resolves:0,lists:0})});
test('cleared workspace configuration reaches saved discovery without a workspace header',async()=>{let headers;const store={resolveForExecution:async()=>({credential:'server-only-key'})},service=new ProviderModelService({listAnthropicModels:(credential,configuration)=>listAnthropicModels(credential,configuration,async(_url,init)=>{headers=new Headers(init.headers);return Response.json({data:[],has_more:false})})});await listSavedProviderModels('anthropic','anthropic-messages',{},repository,store,service);assert.equal(headers.get('anthropic-workspace-id'),null)})
