import test from 'node:test';import assert from 'node:assert/strict';
import {agentDefinitionSchema,canonicalJson,persistedAgentDefinition,persistedAgentDefinitionSchema} from '../lib/workflow-definitions.ts';
import {parseArtifactMarkdown,serializeArtifactMarkdown} from '../lib/artifact-contract.ts';
import {searchArtifacts} from '../lib/search.ts';
import {searchWorkflowAgentPrompts} from '../lib/workflow-agent-prompts.ts';
const base={id:'reviewer',name:'Reviewer',description:'',status:'draft',connectionKey:'deterministic-test'};
test('current custom Agents separate strict persisted input from runtime prompt compatibility',()=>{assert.throws(()=>agentDefinitionSchema.parse({schemaVersion:1,...base,masterPrompt:'Legacy'}));const raw={schemaVersion:2,...base,prompt:{source:'custom',text:'Current'}},a=agentDefinitionSchema.parse(raw),json=canonicalJson(persistedAgentDefinition(a));assert.equal(a.masterPrompt,'Current');assert.deepEqual(persistedAgentDefinitionSchema.parse(raw).prompt,{source:'custom',text:'Current'});assert.match(json,/"schemaVersion": 2/);assert.doesNotMatch(json,/masterPrompt/);assert.throws(()=>persistedAgentDefinitionSchema.parse({...raw,masterPrompt:'Client value'}))});
test('referenced Agents persist only the Artifact ID and do not use compatibility text as prompt data',()=>{const raw={schemaVersion:2,...base,prompt:{source:'artifact',artifactId:'role-narrative-framer'}},a=agentDefinitionSchema.parse(raw),json=canonicalJson(persistedAgentDefinition(a));assert.equal(a.masterPrompt,'');assert.deepEqual(persistedAgentDefinitionSchema.parse(raw).prompt,{source:'artifact',artifactId:'role-narrative-framer'});assert.match(json,/"artifactId": "role-narrative-framer"/);assert.doesNotMatch(json,/masterPrompt|secret body/)});
test('Artifact description is backward compatible, serialized, and centrally searchable',()=>{const old=parseArtifactMarkdown('---\nid: old\ntitle: Old\ntype: prompt\n---\nBody','prompts/old.md');assert.equal(old.description,'');assert.match(serializeArtifactMarkdown(old,old.body),/description: ''/);const raw=serializeArtifactMarkdown({...old,description:'Security review guidance'},old.body);assert.match(raw,/description: Security review guidance/);const described={...old,description:'unique threat modeling phrase'};assert.deepEqual(searchArtifacts([described],'threat modeling').map(x=>x.id),['old']);const summaries=searchWorkflowAgentPrompts([described],'unique threat');assert.equal(summaries[0].description,described.description);assert.equal('body' in summaries[0],false)});
