import test from 'node:test';import assert from 'node:assert/strict';
import {agentDefinitionSchema,canonicalJson} from '../lib/workflow-definitions.ts';
import {parseArtifactMarkdown,serializeArtifactMarkdown} from '../lib/artifact-contract.ts';
import {searchArtifacts} from '../lib/search.ts';
import {searchWorkflowAgentPrompts} from '../lib/workflow-agent-prompts.ts';
const base={id:'reviewer',name:'Reviewer',description:'',status:'draft',connectionKey:'deterministic-test'};
test('V1 Agents read as V2 custom prompts and canonical saves use only prompt',()=>{const a=agentDefinitionSchema.parse({schemaVersion:1,...base,masterPrompt:'Legacy'});assert.deepEqual(a.prompt,{source:'custom',text:'Legacy'});const json=canonicalJson(a);assert.match(json,/"schemaVersion": 2/);assert.doesNotMatch(json,/masterPrompt/)});
test('referenced Agents persist only the Artifact ID',()=>{const a=agentDefinitionSchema.parse({schemaVersion:2,...base,prompt:{source:'artifact',artifactId:'security-review'}});const json=canonicalJson(a);assert.match(json,/"artifactId": "security-review"/);assert.doesNotMatch(json,/masterPrompt|secret body/)});
test('Artifact description is backward compatible, serialized, and centrally searchable',()=>{const old=parseArtifactMarkdown('---\nid: old\ntitle: Old\ntype: prompt\nstatus: draft\n---\nBody','artifacts/prompts/old.md');assert.equal(old.description,'');assert.match(serializeArtifactMarkdown(old,old.body),/description: ''/);const raw=serializeArtifactMarkdown({...old,description:'Security review guidance'},old.body);assert.match(raw,/description: Security review guidance/);const described={...old,description:'unique threat modeling phrase'};assert.deepEqual(searchArtifacts([described],'threat modeling').map(x=>x.id),['old']);const summaries=searchWorkflowAgentPrompts([described],'unique threat');assert.equal(summaries[0].description,described.description);assert.equal('body' in summaries[0],false)});
