import test from "node:test";import assert from "node:assert/strict";import {mkdtemp,mkdir,rm,writeFile} from "node:fs/promises";import {tmpdir} from "node:os";import {join} from "node:path";import {execFileSync} from "node:child_process";import {fileURLToPath} from "node:url";import {isRuntimeInput,parseRelease,validateRunnerRevision} from "../scripts/validate-runner-revision.mjs";
const base={protocolVersion:1,runnerRevision:4,codexVersion:"0.147.0"},current={...base,runnerRevision:5};
const runtime=["codex-runner/src/server.ts","codex-runner/Dockerfile","codex-runner/package.json","codex-runner/package-lock.json","codex-runner/gai.conf","codex-runner/tsconfig.json","codex-runner/release.json"];
test("Runner runtime inputs are deliberately classified",()=>{for(const path of runtime)assert.equal(isRuntimeInput(path),true,path);for(const path of ["codex-runner/test/runner.test.mjs","codex-runner/test/fixtures/a.json","codex-runner/README.md","app/page.tsx"])assert.equal(isRuntimeInput(path),false,path)});
test("every runtime/build input requires a revision bump",()=>{for(const path of runtime)assert.throws(()=>validateRunnerRevision({base,current:base,changedPaths:[path]}),/runnerRevision increase/,path);for(const path of runtime)assert.equal(validateRunnerRevision({base,current,changedPaths:[path]}),true,path)});
test("release fact changes cannot bypass the revision generation",()=>{assert.throws(()=>validateRunnerRevision({base,current:{...base,codexVersion:"0.148.0"},changedPaths:["codex-runner/release.json"]}),/runnerRevision increase/);assert.throws(()=>validateRunnerRevision({base,current:{...base,protocolVersion:2},changedPaths:["codex-runner/release.json","codex-runner/test/protocol.test.mjs"]}),/runnerRevision increase/);assert.equal(validateRunnerRevision({base,current,changedPaths:["codex-runner/release.json"]}),true)});
test("non-runtime changes need no bump and revisions cannot decrease",()=>{for(const path of ["codex-runner/test/runner.test.mjs","codex-runner/test/fixtures/a.json","codex-runner/README.md","app/page.tsx"])assert.equal(validateRunnerRevision({base,current:base,changedPaths:[path]}),true);assert.throws(()=>validateRunnerRevision({base,current:{...base,runnerRevision:3},changedPaths:[]}),/decrease/)});
test("release parser is strict and bounded",()=>{assert.deepEqual(parseRelease(JSON.stringify(base)),base);for(const value of [{...base,extra:true},{...base,runnerRevision:0},{...base,runnerRevision:1.2},{...base,protocolVersion:0},{...base,codexVersion:"0.147"}])assert.throws(()=>parseRelease(JSON.stringify(value)),/malformed/);assert.throws(()=>parseRelease("{"),/malformed/)});
test("CLI validator uses the real merge base in steady-state and behind-base histories",async()=>{const root=await mkdtemp(join(tmpdir(),"adt-runner-revision-")),script=fileURLToPath(new URL("../scripts/validate-runner-revision.mjs",import.meta.url)),git=(...args)=>execFileSync("git",args,{cwd:root,encoding:"utf8"}),run=()=>execFileSync(process.execPath,[script,"main"],{cwd:root,encoding:"utf8",stdio:["ignore","pipe","pipe"]});try{git("init","-q","-b","main");git("config","user.name","ADT Test");git("config","user.email","adt@example.invalid");await mkdir(join(root,"codex-runner","src"),{recursive:true});await mkdir(join(root,"app"),{recursive:true});await writeFile(join(root,"codex-runner","release.json"),JSON.stringify(base));await writeFile(join(root,"codex-runner","src","server.ts"),"export const runner=4;\n");git("add",".");git("commit","-qm","base A");git("checkout","-qb","feature");await writeFile(join(root,"app","page.tsx"),"export default 1;\n");git("add",".");git("commit","-qm","feature ADT change");git("checkout","-q","main");await writeFile(join(root,"codex-runner","src","main-only.ts"),"export const mainOnly=true;\n");git("add",".");git("commit","-qm","base B advances");git("checkout","-q","feature");assert.match(run(),/0 runtime input change/);await writeFile(join(root,"codex-runner","src","server.ts"),"export const runner=5;\n");git("add",".");git("commit","-qm","feature Runner change");assert.throws(run,error=>{assert.doesNotMatch(String(error.stderr),/no merge base/i);return /runnerRevision increase/.test(String(error.stderr))});await writeFile(join(root,"codex-runner","release.json"),JSON.stringify(current));git("add",".");git("commit","-qm","bump Runner revision");assert.match(run(),/2 runtime input change/)}finally{await rm(root,{recursive:true,force:true})}});
