import test from 'node:test';import assert from 'node:assert/strict';
import {issueCheckpointAuthority,issueGraphNodeAuthority,issueRuntimeDiagnosticAuthority,verifyCheckpointAuthority,verifyGraphNodeAuthority,verifyRuntimeDiagnosticAuthority} from '../lib/langgraph-checkpoints.ts';
import {runtimeExecutionPathGateway} from '../lib/runtime-execution-path-gateway.ts';
const secret='diagnostic-authority-secret-is-at-least-32-bytes';
test('diagnostic authorities are purpose and target isolated from execution authorities',async()=>{const checkpoint=await issueRuntimeDiagnosticAuthority('checkpoint',secret),graph=await issueRuntimeDiagnosticAuthority('graph-node',secret),normalCheckpoint=await issueCheckpointAuthority('execution-path',secret),scope={runId:'execution-path',nodeId:'node',workflowGeneration:1,iteration:1,attempt:1},normalGraph=await issueGraphNodeAuthority(scope,secret);assert.equal(await verifyRuntimeDiagnosticAuthority(checkpoint,'checkpoint',secret),true);assert.equal(await verifyRuntimeDiagnosticAuthority(checkpoint,'graph-node',secret),false);assert.equal(await verifyRuntimeDiagnosticAuthority(graph,'checkpoint',secret),false);assert.equal(await verifyCheckpointAuthority(checkpoint,'execution-path',secret),false);assert.equal(await verifyGraphNodeAuthority(graph,scope,secret),false);assert.equal(await verifyRuntimeDiagnosticAuthority(normalCheckpoint,'checkpoint',secret),false);assert.equal(await verifyRuntimeDiagnosticAuthority(normalGraph,'graph-node',secret),false)});
test('gateway diagnostic performs only allowlisted reads and returns bounded safe results',async()=>{const queries=[],db={prepare(sql){queries.push(sql);return{first:async()=>({one:1})}}},token=await issueRuntimeDiagnosticAuthority('checkpoint',secret),request=new Request('https://adt.example/api/runtime-checkpoints',{method:'POST',headers:{authorization:`Bearer ${token}`},body:JSON.stringify({operation:'execution-path-diagnostic',target:'checkpoint'})}),response=await runtimeExecutionPathGateway(request,{operation:'execution-path-diagnostic',target:'checkpoint'},'checkpoint',secret,db),wire=await response.json();assert.equal(response.status,200);assert.deepEqual(wire,{ok:true,authorityAccepted:true,backendAvailable:true});assert.equal(queries.every(sql=>sql.startsWith('SELECT 1 FROM ')),true);assert.doesNotMatch(JSON.stringify(wire),/token|secret|authorization/)});
test('gateway rejects cross-target authority before any backend access',async()=>{let accessed=false,db={prepare(){accessed=true;throw Error('must not access')}},token=await issueRuntimeDiagnosticAuthority('graph-node',secret),request=new Request('https://adt.example/api/runtime-checkpoints',{method:'POST',headers:{authorization:`Bearer ${token}`},body:JSON.stringify({operation:'execution-path-diagnostic',target:'checkpoint'})}),response=await runtimeExecutionPathGateway(request,{operation:'execution-path-diagnostic',target:'checkpoint'},'checkpoint',secret,db);assert.equal(response.status,401);assert.equal(accessed,false);assert.deepEqual(await response.json(),{ok:false,code:'authority_rejected'})});

test('read-only probes are fixed by target and cannot be supplied by callers',async()=>{const prepared=[],db={prepare(sql){prepared.push(sql);return{first:async()=>null}}},token=await issueRuntimeDiagnosticAuthority('graph-node',secret),request=new Request('https://adt.example/api/runtime-graph-node',{method:'POST',headers:{authorization:`Bearer ${token}`}});await runtimeExecutionPathGateway(request,{operation:'execution-path-diagnostic',target:'graph-node'},'graph-node',secret,db);assert.deepEqual(prepared,['SELECT 1 FROM workflow_runs LIMIT 1','SELECT 1 FROM workflow_step_attempts LIMIT 1']);assert.equal(runtimeExecutionPathGateway.length,5)});

test('gateway request readers enforce existing byte bounds and cancel oversized streams',async()=>{const {readRuntimeGatewayRequest,RUNTIME_GATEWAY_REQUEST_LIMITS}=await import('../lib/runtime-gateway-request.ts');assert.deepEqual(RUNTIME_GATEWAY_REQUEST_LIMITS,{checkpoint:1_000_000,'graph-node':270_000,'artifact-search':2048});for(const kind of ['checkpoint','graph-node','artifact-search']){let cancelled=false,pulls=0;const limit=RUNTIME_GATEWAY_REQUEST_LIMITS[kind],body=new ReadableStream({pull(controller){pulls++;controller.enqueue(new Uint8Array(Math.min(limit,4096)))},cancel(){cancelled=true}}),request=new Request('https://adt.example/gateway',{method:'POST',body,duplex:'half'});await assert.rejects(readRuntimeGatewayRequest(request,kind),/body_too_large/);assert.equal(cancelled,true,kind)}});
