import test from "node:test";
import assert from "node:assert/strict";
import {canonicalAdrianEndpoint,securityProfileDefinitionSchema,securityProfilePath} from "../lib/security-profile-definitions.ts";
import {InMemorySecurityProfileDefinitionRepository} from "../lib/security-profile-definition-repository.ts";
import {freezeSecurityProfiles,resolveFrozenSecurityProfile} from "../lib/security-profile-authority.ts";
import {getProviderConnectionType} from "../lib/provider-connection-types.ts";
import {securityProfileTestMessage} from "../lib/security-profile-test-presentation.ts";

const profile={schemaVersion:1,id:"production",name:"Production",description:"",provider:"adrian",endpointUrl:"wss://SECURITY.example:443/events#ignored",decisionTimeoutMs:1500};
test("security profiles canonicalise secure trust targets and reject insecure endpoints",()=>{assert.equal(canonicalAdrianEndpoint(profile.endpointUrl),"wss://security.example/events");assert.throws(()=>securityProfileDefinitionSchema.parse({...profile,endpointUrl:"ws://remote.example"}));assert.throws(()=>securityProfileDefinitionSchema.parse({...profile,endpointUrl:"wss://user:password@security.example/events"}));assert.throws(()=>securityProfileDefinitionSchema.parse({...profile,endpointUrl:"wss://security.example/events?api_key=secret"}));assert.equal(securityProfilePath("production"),"security-profiles/production.json")});
test("security profile repository enforces revisions and returns defensive values",async()=>{const repository=new InMemorySecurityProfileDefinitionRepository(),created=await repository.create(profile);assert.equal(created.definition.endpointUrl,"wss://security.example/events");created.definition.name="mutated";assert.equal((await repository.get("production")).definition.name,"Production");await assert.rejects(repository.update({...profile,name:"Updated"},"stale"));const updated=await repository.update({...profile,name:"Updated"},created.fileSha);assert.equal(updated.definition.name,"Updated");await repository.delete("production",updated.fileSha);assert.equal(await repository.get("production"),undefined)});
test("runtime security is an explicit provider capability",()=>{assert.equal(getProviderConnectionType("openai-agents").capabilities.runtimeSecurity,true);for(const adapter of ["openai-responses","anthropic-messages","work-iq-rest"])assert.notEqual(getProviderConnectionType(adapter).capabilities.runtimeSecurity,true)});
test("Security Profile API presentation distinguishes API-key rejection from endpoint-neutral access denial",()=>{assert.equal(securityProfileTestMessage("adrian_ws_authentication_failed","current",401),"Adrian authentication failed. The configured API key was rejected. (HTTP 401)");const forbidden=securityProfileTestMessage("adrian_ws_access_forbidden","current",403);assert.equal(forbidden,"Adrian WebSocket access was forbidden. (HTTP 403)");assert.doesNotMatch(forbidden,/key|hosted|SaaS/i);assert.equal(securityProfileTestMessage("adrian_ws_upgrade_rejected","current",404),"Adrian rejected the WebSocket endpoint. (HTTP 404)")});

test("run authority freezes no secret and resolves only its endpoint-bound generation",async()=>{const agent={schemaVersion:2,id:"agent",name:"Agent",description:"",status:"draft",connectionKey:"openai",securityProfileId:"production",prompt:{source:"custom",text:"prompt"},masterPrompt:"prompt"},repository={list:async()=>[{definition:securityProfileDefinitionSchema.parse(profile),fileSha:"sha"}]},vault={currentSecurityProfileCredentialBinding:async()=>({bindingId:`spb_${"a".repeat(43)}`,credentialConfigured:true}),resolveSecurityProfileCredential:async(repositoryId,bindingId,endpoint)=>{assert.equal(repositoryId,42);assert.equal(bindingId,`spb_${"a".repeat(43)}`);assert.equal(endpoint,"wss://security.example/events");return"rotated-key"}},snapshot=await freezeSecurityProfiles(42,[agent],repository,vault);assert.equal(JSON.stringify(snapshot).includes("rotated-key"),false);assert.equal(JSON.stringify(snapshot).includes("sec_"),false);assert.equal((await resolveFrozenSecurityProfile(42,agent,snapshot,vault)).credential,"rotated-key")});
test("Agent editor preserves and deliberately clears Security Profile assignment",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../components/WorkflowAgentEditor.tsx",import.meta.url),"utf8"));assert.match(source,/defaultValue=\{initial\?\.securityProfileId\?\?""\}/);assert.match(source,/const securityProfileId=String\(data\.get\("securityProfileId"\)/);assert.match(source,/\.\.\.\(securityProfileId\?\{securityProfileId\}:\{\}\)/)});

test("credential-unavailable profile recovery is one revision-safe compensated mutation",async t=>{
 const configured=securityProfileDefinitionSchema.parse(profile),changed={...configured,name:"Recovered metadata"};
 await t.test("success creates a fresh generation after the SHA-guarded Git update",async()=>{const repository=new InMemorySecurityProfileDefinitionRepository(),created=await repository.create(configured),calls=[],historical=`spb_${"h".repeat(43)}`,fresh=`spb_${"n".repeat(43)}`,vault={currentSecurityProfileCredentialBinding:async()=>{throw Error("missing")},recoverSecurityProfileCredentialBinding:async(...args)=>{calls.push(args);return fresh},rotateSecurityProfileCredential:async()=>assert.fail(),replaceSecurityProfileCredentialBinding:async()=>assert.fail()};const {updateSecurityProfileAuthority}=await import("../lib/security-profile-authority.ts"),saved=await updateSecurityProfileAuthority(42,changed,created.fileSha,"new-key",repository,vault);assert.equal(saved.definition.name,"Recovered metadata");assert.deepEqual(calls,[[42,"production","wss://security.example/events","new-key"]]);assert.notEqual(fresh,historical)});
 await t.test("stale SHA and Git failure perform zero credential mutations",async()=>{for(const mode of ["stale","git-failure"]){const repository=new InMemorySecurityProfileDefinitionRepository(),created=await repository.create(configured),mutations=[];if(mode==="git-failure")repository.update=async()=>{throw Error("git unavailable")};const vault={currentSecurityProfileCredentialBinding:async()=>{throw Error("missing")},recoverSecurityProfileCredentialBinding:async()=>mutations.push("create"),rotateSecurityProfileCredential:async()=>mutations.push("rotate"),replaceSecurityProfileCredentialBinding:async()=>mutations.push("replace")},{updateSecurityProfileAuthority}=await import("../lib/security-profile-authority.ts");await assert.rejects(updateSecurityProfileAuthority(42,changed,mode==="stale"?"stale":created.fileSha,"new-key",repository,vault));assert.deepEqual(mutations,[])}});
 await t.test("binding failure rolls Git back, and rollback failure stays credential-unavailable",async()=>{for(const rollbackFails of [false,true]){const repository=new InMemorySecurityProfileDefinitionRepository(),created=await repository.create(configured),ordinaryUpdate=repository.update.bind(repository);let updates=0;repository.update=async(...args)=>{updates++;if(rollbackFails&&updates===2)throw Error("rollback failed");return ordinaryUpdate(...args)};const vault={currentSecurityProfileCredentialBinding:async()=>{throw Error("missing")},recoverSecurityProfileCredentialBinding:async()=>{throw Error("binding failed")},rotateSecurityProfileCredential:async()=>assert.fail(),replaceSecurityProfileCredentialBinding:async()=>assert.fail()},{updateSecurityProfileAuthority}=await import("../lib/security-profile-authority.ts");await assert.rejects(updateSecurityProfileAuthority(42,changed,created.fileSha,"new-key",repository,vault));assert.equal((await repository.get("production")).definition.name,rollbackFails?"Recovered metadata":"Production")}});
 await t.test("recovery rejects endpoint change and missing key before Git or credential mutation",async()=>{const repository=new InMemorySecurityProfileDefinitionRepository(),created=await repository.create(configured),updates=[],ordinary=repository.update.bind(repository);repository.update=async(...args)=>{updates.push(args);return ordinary(...args)};const vault={currentSecurityProfileCredentialBinding:async()=>{throw Error("missing")},recoverSecurityProfileCredentialBinding:async()=>assert.fail(),rotateSecurityProfileCredential:async()=>assert.fail(),replaceSecurityProfileCredentialBinding:async()=>assert.fail()},{updateSecurityProfileAuthority}=await import("../lib/security-profile-authority.ts");for(const [definition,key] of [[changed,undefined],[{...changed,endpointUrl:"wss://other.example/events"},"key"]])await assert.rejects(updateSecurityProfileAuthority(42,definition,created.fileSha,key,repository,vault),/security_profile_credential_required/);assert.deepEqual(updates,[])})
});

test("Security Profile editor performs unavailable recovery as one revisioned save",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../components/SecurityProfileEditor.tsx",import.meta.url),"utf8"));assert.doesNotMatch(source,/\/credential`/);assert.match(source,/required=\{!initial\|\|!initial\.credentialConfigured\}/);assert.match(source,/\{definition,fileSha,\.\.\.\(apiKey\?\{apiKey\}:\{\}\)\}/)});
test('Security Profile editor uses shared identity drafting, permanent ID guidance, and the write-only draft control',async()=>{const source=await import('node:fs/promises').then(fs=>fs.readFile(new URL('../components/SecurityProfileEditor.tsx',import.meta.url),'utf8'));assert.match(source,/definitionIdDraftReducer/);assert.match(source,/DEFINITION_ID_MAX_LENGTH/);assert.ok(source.indexOf('Name *')<source.indexOf('ID *'));assert.match(source,/readOnly=\{Boolean\(initial\)\}/);assert.match(source,/Permanent identifier used by Agents/);assert.match(source,/<SecretDraftInput name="apiKey"/)});
test('Security routes share the protected application shell',async()=>{const source=await import('node:fs/promises').then(fs=>fs.readFile(new URL('../app/security/layout.tsx',import.meta.url),'utf8'));assert.match(source,/requireRepositoryAuthorization\("\/security"\)/);assert.match(source,/<AppHeader/);assert.equal((source.match(/<AppHeader/g)??[]).length,1)});
