import test from "node:test";
import assert from "node:assert/strict";
import {canonicalAdrianEndpoint,securityProfileDefinitionSchema,securityProfilePath} from "../lib/security-profile-definitions.ts";
import {InMemorySecurityProfileDefinitionRepository} from "../lib/security-profile-definition-repository.ts";
import {freezeSecurityProfiles,resolveFrozenSecurityProfile} from "../lib/security-profile-authority.ts";
import {getProviderConnectionType} from "../lib/provider-connection-types.ts";

const profile={schemaVersion:1,id:"production",name:"Production",description:"",provider:"adrian",endpointUrl:"wss://SECURITY.example:443/events#ignored",decisionTimeoutMs:1500};
test("security profiles canonicalise secure trust targets and reject insecure endpoints",()=>{assert.equal(canonicalAdrianEndpoint(profile.endpointUrl),"wss://security.example/events");assert.throws(()=>securityProfileDefinitionSchema.parse({...profile,endpointUrl:"ws://remote.example"}));assert.throws(()=>securityProfileDefinitionSchema.parse({...profile,endpointUrl:"wss://user:password@security.example/events"}));assert.throws(()=>securityProfileDefinitionSchema.parse({...profile,endpointUrl:"wss://security.example/events?api_key=secret"}));assert.equal(securityProfilePath("production"),"security-profiles/production.json")});
test("security profile repository enforces revisions and returns defensive values",async()=>{const repository=new InMemorySecurityProfileDefinitionRepository(),created=await repository.create(profile);assert.equal(created.definition.endpointUrl,"wss://security.example/events");created.definition.name="mutated";assert.equal((await repository.get("production")).definition.name,"Production");await assert.rejects(repository.update({...profile,name:"Updated"},"stale"));const updated=await repository.update({...profile,name:"Updated"},created.fileSha);assert.equal(updated.definition.name,"Updated");await repository.delete("production",updated.fileSha);assert.equal(await repository.get("production"),undefined)});
test("runtime security is an explicit provider capability",()=>{assert.equal(getProviderConnectionType("openai-agents").capabilities.runtimeSecurity,true);for(const adapter of ["openai-responses","anthropic-messages","work-iq-rest"])assert.notEqual(getProviderConnectionType(adapter).capabilities.runtimeSecurity,true)});

test("run authority freezes no secret and resolves only its endpoint-bound generation",async()=>{const agent={schemaVersion:2,id:"agent",name:"Agent",description:"",status:"draft",connectionKey:"openai",securityProfileId:"production",prompt:{source:"custom",text:"prompt"},masterPrompt:"prompt"},repository={list:async()=>[{definition:securityProfileDefinitionSchema.parse(profile),fileSha:"sha"}]},vault={currentSecurityProfileCredentialBinding:async()=>({bindingId:`spb_${"a".repeat(43)}`,credentialConfigured:true}),resolveSecurityProfileCredential:async(repositoryId,bindingId,endpoint)=>{assert.equal(repositoryId,42);assert.equal(bindingId,`spb_${"a".repeat(43)}`);assert.equal(endpoint,"wss://security.example/events");return"rotated-key"}},snapshot=await freezeSecurityProfiles(42,[agent],repository,vault);assert.equal(JSON.stringify(snapshot).includes("rotated-key"),false);assert.equal(JSON.stringify(snapshot).includes("sec_"),false);assert.equal((await resolveFrozenSecurityProfile(42,agent,snapshot,vault)).credential,"rotated-key")});
test("Agent editor preserves and deliberately clears Security Profile assignment",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../components/WorkflowAgentEditor.tsx",import.meta.url),"utf8"));assert.match(source,/defaultValue=\{initial\?\.securityProfileId\?\?""\}/);assert.match(source,/const securityProfileId=String\(data\.get\("securityProfileId"\)/);assert.match(source,/\.\.\.\(securityProfileId\?\{securityProfileId\}:\{\}\)/)});
