import test from 'node:test';import assert from 'node:assert/strict';import {installTsxHook} from './render-tsx.mjs';
const require=installTsxHook(),{validateWorkflowReferences}=require('../lib/workflow-definitions.ts'),{workflowError}=require('../lib/workflow-http.ts');
const agent=id=>({schemaVersion:2,id,name:id,description:'',status:'draft',connectionKey:'ready',prompt:{source:'custom',text:'prompt'},masterPrompt:'prompt'}),agents=['a','b','c'].map(agent);
const graph=edges=>({schemaVersion:2,id:'graph',name:'Graph',description:'',status:'draft',nodes:agents.map(({id})=>({id:`node-${id}`,blockType:'agent',blockVersion:1,config:{agentId:id}})),edges:edges.map(([source,target])=>({id:`edge-${source}-${target}`,source:`node-${source}`,target:`node-${target}`})),limits:{maxStepExecutions:32}});
test('unsupported v2 topology from Workflow validation maps to a stable safe 422 response',async()=>{try{await validateWorkflowReferences(graph([['a','b'],['a','c']]),agents,new Set(['ready']));assert.fail('branching graph should fail validation')}catch(error){const response=workflowError(error);assert.equal(response.status,422);assert.deepEqual(await response.json(),{code:'unsupported_workflow_topology',error:'Workflow graph topology is invalid or unsupported.'})}});
test('valid linear v2 validation continues and existing HTTP mappings stay unchanged',async()=>{await validateWorkflowReferences(graph([['a','b'],['b','c']]),agents,new Set(['ready']));const missing=workflowError(new Error('missing_agent:private-detail'));assert.equal(missing.status,422);assert.deepEqual(await missing.json(),{code:'missing_agent',error:'A referenced agent does not exist.'});const unknown=workflowError(new Error('unexpected_internal_detail'));assert.equal(unknown.status,500);assert.deepEqual(await unknown.json(),{code:'operation_failed',error:'The workflow operation could not be completed.'})});
test('ineligible Publish GitHub PR sources have bounded validation feedback',async()=>{const response=workflowError(new Error('publish_source_invalid'));assert.equal(response.status,422);assert.deepEqual(await response.json(),{code:'publish_source_invalid',error:'Publish GitHub PR requires a ready managed Codex Runner Agent source.'})});
test('incompatible reusable Workflow updates have bounded conflict feedback',async()=>{const response=workflowError(new Error('workflow_dependency_incompatible'));assert.equal(response.status,409);assert.deepEqual(await response.json(),{code:'workflow_dependency_incompatible',error:'This change would make a Workflow that reuses this Workflow invalid. Update the dependent Workflow first.'})});

test('Publish authoring and operational failures expose precise safe API errors',async()=>{for(const [code,message] of [['publish_source_not_codex_runner','must use a Codex Runner connection'],['publish_source_managed_git_required','managed Git enabled'],['publish_source_environment_required','managed environment identity'],['publish_source_operationally_unavailable','not currently ready and managed']]){const response=workflowError(new Error(code)),body=await response.json();assert.equal(response.status,422);assert.equal(body.code,code);assert.match(body.error,new RegExp(message))}});
test('layout revision observation conflict is explicit and retryable',async()=>{const response=workflowError(new Error('workflow_revision_not_observed'));assert.equal(response.status,409);assert.deepEqual(await response.json(),{code:'workflow_revision_not_observed',error:'The saved Workflow revision is not yet available for layout validation. Retry layout save.'})});
