import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {Miniflare} from 'miniflare';import {agentDefinitionSchema,buildSequentialWorkflow} from '../lib/workflow-definitions.ts';import {D1WorkflowRunStorage} from '../lib/workflow-d1-storage.ts';import {newWorkflowRun} from '../lib/workflow-storage.ts';import {DeterministicTestAdapter} from '../lib/workflow-adapter.ts';import {resolveConnection,safeConnectionSnapshot} from '../lib/workflow-connections.ts';import {executeDurableWorkflow} from '../lib/workflow-durable-driver.ts';
const env={NODE_ENV:'test'},connection=resolveConnection('deterministic-test',env);const agent=(id,name,options={mode:'immediate',pendingChecks:0,cancellation:'supported'})=>agentDefinitionSchema.parse({schemaVersion:1,id,name,description:'',status:'draft',masterPrompt:`Prompt ${name}`,connectionKey:'deterministic-test',adapterOptions:options});
async function database(){const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:{DB:'workflow-test'}}),db=await mf.getD1Database('DB'),sql=await readFile(new URL('../migrations/0003_create_workflow_runs.sql',import.meta.url),'utf8');await db.batch(sql.split(';').map(value=>value.trim()).filter(Boolean).map(value=>db.prepare(value)));return {mf,db};}
class FakeStep{names=[];sleeps=[];async do(name,operation){this.names.push(name);return operation();}async sleep(name,duration){this.names.push(name);this.sleeps.push(duration);}}
function fixture(id='durable',options){const agents=[agent('first','First',options),agent('second','Second')],workflow=buildSequentialWorkflow({id:'two-step',name:'Two step',agents});return {agents,workflow,run:newWorkflowRun({id,workflow,revision:'workflow-sha',agents,agentRevisions:{first:'first-sha',second:'second-sha'},connections:[safeConnectionSnapshot(connection)],initialInput:'  exact\r\ntext  ',clientIdempotencyKey:`client-${id}`})};}
test('D1 migration persists atomic run snapshots across storage instances',async()=>{const {mf,db}=await database(),{run}=fixture();const first=new D1WorkflowRunStorage(db),created=await first.createRun(run);assert.equal(created.attempts.length,2);const second=new D1WorkflowRunStorage(db),reloaded=await second.getRun(run.id);assert.equal(reloaded.run.workflowRevision,'workflow-sha');assert.deepEqual(reloaded.run.agentRevisions,{first:'first-sha',second:'second-sha'});const duplicate=await second.createRun({...run,id:'different'});assert.equal(duplicate.run.id,run.id);await mf.dispose();});
test('durable driver completes two D1 steps with exact persisted handoff',async()=>{const {mf,db}=await database(),{run}=fixture('two-step-d1'),storage=new D1WorkflowRunStorage(db);await storage.createRun(run);const adapter=new DeterministicTestAdapter(),step=new FakeStep();await executeDurableWorkflow({runId:run.id,storage,adapters:new Map([[adapter.kind,adapter]]),resolveConnection:()=>connection,step});const fresh=new D1WorkflowRunStorage(db),detail=await fresh.getRun(run.id),one=detail.attempts.find(a=>a.stepId==='step-1'),two=detail.attempts.find(a=>a.stepId==='step-2');assert.equal(detail.run.status,'succeeded');assert.equal(two.inputText,one.outputText);assert.equal(adapter.starts.get(`${run.id}:step-1:1:1`),1);assert.equal(adapter.starts.get(`${run.id}:step-2:1:1`),1);assert.ok(step.names.some(name=>name.endsWith(':claim')));await mf.dispose();});
test('pending provider uses durable sleep and persisted task is reused',async()=>{const {mf,db}=await database(),{run}=fixture('pending-d1',{mode:'pending',pendingChecks:0,cancellation:'supported'}),storage=new D1WorkflowRunStorage(db);await storage.createRun(run);const adapter=new DeterministicTestAdapter(),step=new FakeStep();await executeDurableWorkflow({runId:run.id,storage,adapters:new Map([[adapter.kind,adapter]]),resolveConnection:()=>connection,step});assert.equal((await storage.getRun(run.id)).run.status,'succeeded');assert.ok(step.sleeps.length>=1);assert.ok(step.sleeps.every(delay=>delay===10000));assert.equal(adapter.starts.get(`${run.id}:step-1:1:1`),1);assert.ok(step.names.some(name=>name.endsWith(':check')));await mf.dispose();});
test('D1 guarded mutations retain cancellation outcome and reject competing transitions',async()=>{const {mf,db}=await database(),{run}=fixture('cancel-d1'),a=new D1WorkflowRunStorage(db),b=new D1WorkflowRunStorage(db);await a.createRun(run);await a.requestCancellation(run.id);await a.recordCancellationResult(run.id,'unsupported');await a.cancelRun(run.id);assert.equal((await b.getRun(run.id)).run.cancellationResult,'unsupported');await assert.rejects(b.claimStep(run.id,'step-1','x'),/invalid_step_claim/);await mf.dispose();});
