import test from 'node:test'; import assert from 'node:assert/strict';
import { agentDefinitionSchema, buildSequentialWorkflow, canonicalJson, agentDefinitionPath, workflowDefinitionPath } from '../lib/workflow-definitions.ts';
import { InMemoryWorkflowRunStorage, newWorkflowRun } from '../lib/workflow-storage.ts';
import { DeterministicTestAdapter } from '../lib/workflow-adapter.ts'; import { WorkflowRunner } from '../lib/workflow-runner.ts'; import { resolveConnection, safeConnectionSnapshot } from '../lib/workflow-connections.ts';
const agent=(id,name)=>agentDefinitionSchema.parse({schemaVersion:1,id,name,description:'',status:'draft',masterPrompt:`Prompt ${name}`,connectionKey:'deterministic-test'});
const env={NODE_ENV:'test'};
test('schemas produce canonical paths and deterministic JSON',()=>{assert.equal(agentDefinitionPath('one'),'_adt/agents/one.agent.json');assert.equal(workflowDefinitionPath('one'),'_adt/workflows/one.workflow.json');assert.equal(canonicalJson({z:1,a:{z:2,a:1}}),'{\n  "a": {\n    "a": 1,\n    "z": 2\n  },\n  "z": 1\n}\n');assert.throws(()=>agentDefinitionSchema.parse({...agent('one','One'),adapterOptions:{apiKey:'unsafe'}}));});
test('durable two step run uses exact persisted output and survives reload',async()=>{const agents=[agent('first','First'),agent('second','Second')],workflow=buildSequentialWorkflow({id:'two-step',name:'Two step',agents});const connection=resolveConnection('deterministic-test',env);const store=new InMemoryWorkflowRunStorage();await store.createRun(newWorkflowRun({id:'run-1',workflow,revision:'abc',agents,connections:[safeConnectionSnapshot(connection)],initialInput:'  hello\nworld  '}));const adapter=new DeterministicTestAdapter();const runner=new WorkflowRunner(store,new Map([[adapter.kind,adapter]]),()=>connection);const detail=await runner.execute('run-1');assert.equal(detail.run.status,'succeeded');const first=detail.attempts.find(a=>a.stepId==='step-1'),second=detail.attempts.find(a=>a.stepId==='step-2');assert.equal(second.inputText,first.outputText);assert.equal(adapter.starts.get('run-1:step-1:1:1'),1);assert.equal(adapter.starts.get('run-1:step-2:1:1'),1);assert.deepEqual(await store.getRun('run-1'),detail);await runner.execute('run-1');assert.equal(adapter.starts.get('run-1:step-1:1:1'),1);});
test('run creation is idempotent and guarded transitions reject invalid advancement',async()=>{const agents=[agent('first','First')],workflow=buildSequentialWorkflow({id:'single',name:'Single',agents});const connection=safeConnectionSnapshot(resolveConnection('deterministic-test',env)),store=new InMemoryWorkflowRunStorage();const input={id:'one',workflow,revision:'r',agents,connections:[connection],initialInput:'x',clientIdempotencyKey:'client-1'};await store.createRun(newWorkflowRun(input));const duplicate=await store.createRun(newWorkflowRun({...input,id:'two'}));assert.equal(duplicate.run.id,'one');await assert.rejects(store.advance('one','step-1','missing'),/invalid_advancement/);});
