import test from 'node:test';import assert from 'node:assert/strict';
import {InMemoryToolDefinitionRepository} from '../lib/tool-definition-repository.ts';
import {createMcpServer,updateMcpServer,deleteMcpServer,discoverMcpServer} from '../lib/mcp-tool-service.ts';
import {freezeAuthorizedMcpTools,resolveFrozenMcpTools} from '../lib/mcp-tool-authority.ts';
import {newLangGraphWorkflowRun,InMemoryWorkflowRunStorage} from '../lib/workflow-storage.ts';

class Vault{values=new Map;bindings=new Map;generation=1;async create(value){const id=`sec_${String(this.values.size+1).padStart(43,'a')}`;this.values.set(id,value);return id}async resolve(id){if(!this.values.has(id))throw Error('vault_secret_unavailable');return this.values.get(id)}async delete(id){this.values.delete(id)}fresh(){return `mcpb_${String(this.generation++).padStart(43,'g')}`}async ensureMcpServerCredentialBinding(repositoryId,server,secret){const key=`${repositoryId}:${server}`,old=this.bindings.get(key);if(old){if(old.secret!==secret)throw Error('binding conflict');return old.id}const value={id:this.fresh(),secret};this.bindings.set(key,value);return value.id}async rotateMcpServerCredential(repositoryId,server,bindingId,secret,expected){const old=this.bindings.get(`${repositoryId}:${server}`);if(old?.id!==bindingId||old.secret!==expected)throw Error('binding conflict');old.secret=secret}async replaceMcpServerCredentialBinding(repositoryId,server,bindingId,secret){const old=this.bindings.get(`${repositoryId}:${server}`);if(old?.id!==bindingId)throw Error('binding conflict');old.id=this.fresh();old.secret=secret;return old.id}async restoreMcpServerCredentialBinding(repositoryId,server,bindingId,secret){this.bindings.set(`${repositoryId}:${server}`,{id:bindingId,secret})}async revokeMcpServerCredentialBinding(repositoryId,server,bindingId){const key=`${repositoryId}:${server}`,old=this.bindings.get(key);if(old?.id!==bindingId)throw Error('binding conflict');this.bindings.delete(key)}async resolveMcpServerCredential(repositoryId,bindingId){const old=[...this.bindings.entries()].find(([key,value])=>key.startsWith(`${repositoryId}:`)&&value.id===bindingId)?.[1];if(!old)throw Error('vault_secret_unavailable');return this.resolve(old.secret)}}
const agent={schemaVersion:2,id:'agent',name:'Agent',description:'',status:'draft',connectionKey:'openai',prompt:{source:'custom',text:'Act'},masterPrompt:'Act',tools:[{type:'mcp',serverId:'docs',toolName:'search'}]};
const workflow={schemaVersion:2,id:'flow',name:'Flow',description:'',status:'draft',nodes:[{id:'node',blockType:'agent',blockVersion:1,config:{agentId:'agent'}}],edges:[],limits:{maxStepExecutions:1}};
const plan={planVersion:2,nodes:workflow.nodes,edges:[],entryNodeId:'node',terminalNodeId:'node',maxStepExecutions:1};
const connection={key:'openai',name:'OpenAI',adapter:'openai-agents',enabled:true,capabilities:{asynchronous:false,cancellation:false,agentTools:true}};

async function setup(){const repo=new InMemoryToolDefinitionRepository(),vault=new Vault(),created=await createMcpServer(101,{id:'docs',name:'Docs',endpointUrl:'https://old.example/mcp',authenticationMode:'bearer',bearerToken:'credential-one'},repo,vault),discovered=await discoverMcpServer('docs',created.fileSha,repo,vault,{discoverMcp:async()=>[{name:'search',description:'old description',inputSchema:{type:'object',properties:{old:{type:'string'}}}},{name:'ungranted',inputSchema:{type:'object'}}]});return{repo,vault,discovered}}

test('run-owned MCP data freezes schema, description, alias, endpoint and only granted tools',async()=>{const {repo,vault,discovered}=await setup(),snapshot=await freezeAuthorizedMcpTools(101,[agent],repo,vault),run=newLangGraphWorkflowRun({id:'run',workflow,executionPlan:plan,revision:'sha',agents:[agent],connections:[connection],mcpToolSnapshots:snapshot,initialInput:'input'});assert.deepEqual(run.mcpToolSnapshots,snapshot);assert.equal(snapshot.agent.length,1);assert.equal(snapshot.agent[0].server.url,'https://old.example/mcp');assert.equal(snapshot.agent[0].tool.description,'old description');assert.equal(JSON.stringify(run).includes('credential-one'),false);assert.equal(JSON.stringify(run).includes('sec_'),false);
 await repo.update({...discovered.definition,endpointUrl:'https://new.example/mcp',catalogue:{...discovered.definition.catalogue,tools:[{name:'search',description:'new',inputSchema:{type:'object',required:['new']}},{name:'new-tool',inputSchema:{type:'object'}}]}},discovered.fileSha);
 const execution=await resolveFrozenMcpTools(101,agent,run.mcpToolSnapshots,vault);assert.equal(execution[0].server.url,'https://old.example/mcp');assert.equal(execution[0].tool.description,'old description');assert.deepEqual(execution[0].tool.inputSchema,{type:'object',properties:{old:{type:'string'}}});assert.equal(execution.length,1);
 const next=await freezeAuthorizedMcpTools(101,[agent],repo,vault);assert.equal(next.agent[0].server.url,'https://new.example/mcp');assert.deepEqual(next.agent[0].tool.inputSchema,{type:'object',required:['new']});
});

test('removing a catalogue tool preserves an existing snapshot and rejects a future run',async()=>{const {repo,vault,discovered}=await setup(),snapshot=await freezeAuthorizedMcpTools(101,[agent],repo,vault);await repo.update({...discovered.definition,catalogue:{...discovered.definition.catalogue,tools:[]}},discovered.fileSha);assert.equal((await resolveFrozenMcpTools(101,agent,snapshot,vault))[0].tool.name,'search');await assert.rejects(freezeAuthorizedMcpTools(101,[agent],repo,vault),/mcp_grant_unavailable/)});

test('credential rotation is live and does not mutate frozen state',async()=>{const {repo,vault}=await setup(),snapshot=await freezeAuthorizedMcpTools(101,[agent],repo,vault),before=structuredClone(snapshot),newId=await vault.create('credential-two');await vault.rotateMcpServerCredential(101,'docs',snapshot.agent[0].credentialBindingId,newId,vault.bindings.get('101:docs').secret);assert.equal((await resolveFrozenMcpTools(101,agent,snapshot,vault))[0].credential,'credential-two');assert.deepEqual(snapshot,before);vault.bindings.delete('101:docs');await assert.rejects(resolveFrozenMcpTools(101,agent,snapshot,vault),/vault_secret_unavailable/)});

test('retry storage retains the exact MCP snapshot',async()=>{const {repo,vault}=await setup(),snapshot=await freezeAuthorizedMcpTools(101,[agent],repo,vault),storage=new InMemoryWorkflowRunStorage(),run=newLangGraphWorkflowRun({id:'retry',workflow,executionPlan:plan,revision:'sha',agents:[agent],connections:[connection],mcpToolSnapshots:snapshot,initialInput:'input'});await storage.createRun(run);await storage.ensureGraphActivation(run.id,'node','activation');const claim=await storage.claimGraphNode(run.id,'node','input','activation');await storage.failStep(run.id,'node',claim.attempt.iteration,claim.attempt.attempt,{category:'provider_unavailable',safeMessage:'retry',retryable:true});await storage.createAutomaticRetryAttempt(run.id,'node','activation');assert.deepEqual((await storage.getRun(run.id)).run.mcpToolSnapshots,snapshot)});

test('historical MCP runs without frozen data fail closed while legacy Artifact Search is unchanged',async()=>{await assert.rejects(resolveFrozenMcpTools(101,agent,undefined,{resolveMcpServerCredential:async()=>{throw Error('must not resolve')}}),/mcp_run_snapshot_missing/);const legacy={...agent,tools:['artifact_search']};assert.deepEqual(await resolveFrozenMcpTools(101,legacy,undefined,{resolveMcpServerCredential:async()=>{throw Error('must not resolve')}}),[])});

test('same server ID credentials remain isolated by frozen run repository identity',async()=>{const vault=new Vault(),repoA=new InMemoryToolDefinitionRepository(),repoB=new InMemoryToolDefinitionRepository(),a=await createMcpServer(101,{id:'docs',name:'A docs',endpointUrl:'https://a.example/mcp',authenticationMode:'bearer',bearerToken:'credential-a'},repoA,vault),b=await createMcpServer(202,{id:'docs',name:'B docs',endpointUrl:'https://b.example/mcp',authenticationMode:'bearer',bearerToken:'credential-b'},repoB,vault),da=await discoverMcpServer('docs',a.fileSha,repoA,vault,{discoverMcp:async()=>[{name:'search',inputSchema:{type:'object'}}]}),db=await discoverMcpServer('docs',b.fileSha,repoB,vault,{discoverMcp:async()=>[{name:'search',inputSchema:{type:'object'}}]}),snapshotA=await freezeAuthorizedMcpTools(101,[agent],repoA,vault),snapshotB=await freezeAuthorizedMcpTools(202,[agent],repoB,vault);assert.equal((await resolveFrozenMcpTools(101,agent,snapshotA,vault))[0].credential,'credential-a');assert.equal((await resolveFrozenMcpTools(202,agent,snapshotB,vault))[0].credential,'credential-b');const rotated=await updateMcpServer(202,{id:'docs',name:'B docs',endpointUrl:'https://b.example/mcp',authenticationMode:'bearer',bearerToken:'credential-b2',fileSha:db.fileSha},repoB,vault);assert.equal((await resolveFrozenMcpTools(101,agent,snapshotA,vault))[0].credential,'credential-a');assert.equal((await resolveFrozenMcpTools(202,agent,snapshotB,vault))[0].credential,'credential-b2');await deleteMcpServer(202,'docs',rotated.fileSha,repoB,vault);const existingA=await resolveFrozenMcpTools(101,agent,snapshotA,vault);assert.equal(existingA[0].server.url,'https://a.example/mcp');assert.equal(existingA[0].credential,'credential-a');await assert.rejects(resolveFrozenMcpTools(202,agent,snapshotB,vault),/vault_secret_unavailable/);assert.equal((await repoA.get('docs')).fileSha,da.fileSha)});

test('endpoint generation change and later rotation never expose endpoint B credential to endpoint A run',async()=>{const{repo,vault,discovered}=await setup(),snapshotA=await freezeAuthorizedMcpTools(101,[agent],repo,vault),generationA=snapshotA.agent[0].credentialBindingId,changed=await updateMcpServer(101,{id:'docs',name:'Docs',endpointUrl:'https://new.example/mcp',authenticationMode:'bearer',bearerToken:'credential-b',fileSha:discovered.fileSha},repo,vault),snapshotB=await freezeAuthorizedMcpTools(101,[agent],repo,vault);assert.notEqual(snapshotB.agent[0].credentialBindingId,generationA);assert.equal(snapshotB.agent[0].server.url,'https://new.example/mcp');await assert.rejects(resolveFrozenMcpTools(101,agent,snapshotA,vault),/vault_secret_unavailable/);const rotated=await updateMcpServer(101,{id:'docs',name:'Docs',endpointUrl:'https://new.example/mcp',authenticationMode:'bearer',bearerToken:'credential-b-rotated',fileSha:changed.fileSha},repo,vault),snapshotAfterRotation=await freezeAuthorizedMcpTools(101,[agent],repo,vault);assert.equal(snapshotAfterRotation.agent[0].credentialBindingId,snapshotB.agent[0].credentialBindingId);assert.equal((await resolveFrozenMcpTools(101,agent,snapshotB,vault))[0].credential,'credential-b-rotated');await assert.rejects(resolveFrozenMcpTools(101,agent,snapshotA,vault),/vault_secret_unavailable/);assert.equal((await repo.get('docs')).fileSha,rotated.fileSha)});

test('delete and recreate same server ID and endpoint never resurrects an old run generation',async()=>{const{repo,vault,discovered}=await setup(),oldSnapshot=await freezeAuthorizedMcpTools(101,[agent],repo,vault);await deleteMcpServer(101,'docs',discovered.fileSha,repo,vault);const recreated=await createMcpServer(101,{id:'docs',name:'Docs again',endpointUrl:'https://old.example/mcp',authenticationMode:'bearer',bearerToken:'recreated-token'},repo,vault),catalogued=await discoverMcpServer('docs',recreated.fileSha,repo,vault,{discoverMcp:async()=>[{name:'search',inputSchema:{type:'object'}}]}),newSnapshot=await freezeAuthorizedMcpTools(101,[agent],repo,vault);assert.notEqual(newSnapshot.agent[0].credentialBindingId,oldSnapshot.agent[0].credentialBindingId);assert.equal(newSnapshot.agent[0].server.url,oldSnapshot.agent[0].server.url);await assert.rejects(resolveFrozenMcpTools(101,agent,oldSnapshot,vault),/vault_secret_unavailable/);assert.equal((await resolveFrozenMcpTools(101,agent,newSnapshot,vault))[0].credential,'recreated-token');assert.equal((await repo.get('docs')).fileSha,catalogued.fileSha)});

test('authentication changes revoke or establish generations and snapshots remain non-secret',async()=>{const{repo,vault,discovered}=await setup(),bearer=await freezeAuthorizedMcpTools(101,[agent],repo,vault),none=await updateMcpServer(101,{id:'docs',name:'Docs',endpointUrl:'https://old.example/mcp',authenticationMode:'none',fileSha:discovered.fileSha},repo,vault);await assert.rejects(resolveFrozenMcpTools(101,agent,bearer,vault),/vault_secret_unavailable/);const bearerAgain=await updateMcpServer(101,{id:'docs',name:'Docs',endpointUrl:'https://old.example/mcp',authenticationMode:'bearer',bearerToken:'new-bearer',fileSha:none.fileSha},repo,vault),snapshot=await freezeAuthorizedMcpTools(101,[agent],repo,vault);assert.ok(snapshot.agent[0].credentialBindingId.startsWith('mcpb_'));assert.notEqual(snapshot.agent[0].credentialBindingId,bearer.agent[0].credentialBindingId);assert.doesNotMatch(JSON.stringify(snapshot),/sec_|credential-one|new-bearer/);assert.equal((await resolveFrozenMcpTools(101,agent,snapshot,vault))[0].credential,'new-bearer');assert.equal((await repo.get('docs')).fileSha,bearerAgain.fileSha)});

test('legacy definitions initialise one stable generation and reject conflicting concurrent authority',async()=>{const{repo,vault}=await setup();vault.bindings.clear();const [first,second]=await Promise.all([freezeAuthorizedMcpTools(101,[agent],repo,vault),freezeAuthorizedMcpTools(101,[agent],repo,vault)]);assert.equal(first.agent[0].credentialBindingId,second.agent[0].credentialBindingId);const conflicting=await vault.create('conflict');vault.bindings.get('101:docs').secret=conflicting;await assert.rejects(freezeAuthorizedMcpTools(101,[agent],repo,vault),/binding conflict/)});
