import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Miniflare} from 'miniflare';
import {D1WorkflowProviderConnectionStore} from '../lib/workflow-provider-connection-store.ts';
import {testWorkflowConnection} from '../lib/workflow-connection-test.ts';

test('connection diagnostic resolves transiently without changing persistent application state',async t=>{const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:{DB:crypto.randomUUID()}}),db=await mf.getD1Database('DB');t.after(()=>mf.dispose());for(const migration of ['0003_create_workflow_runs.sql','0004_create_workflow_provider_connections.sql']){const sql=await readFile(new URL(`../migrations/${migration}`,import.meta.url),'utf8');await db.batch(sql.split(';').map(v=>v.trim()).filter(Boolean).map(statement=>db.prepare(statement)));}const secret='diagnostic-plaintext-secret',store=new D1WorkflowProviderConnectionStore(db,Buffer.alloc(32,44).toString('base64'));await store.upsertConnection({connectionKey:'openai-primary',adapter:'openai-responses',model:'configured-model',credential:secret});const before=await db.prepare('SELECT * FROM workflow_provider_connections').first(),counts=async()=>({runs:(await db.prepare('SELECT COUNT(*) count FROM workflow_runs').first()).count,attempts:(await db.prepare('SELECT COUNT(*) count FROM workflow_step_attempts').first()).count});const definitions={agents:0,workflows:0};let received;const adapter={kind:'openai-responses',validateConnection:async()=>({ok:true}),start:async()=>{throw new Error('unused')},check:async()=>{throw new Error('unused')},testConnection:async connection=>{received=connection;return{ok:true,outputText:'OK'}}};const result=await testWorkflowConnection('openai-primary',store,new Map([[adapter.kind,adapter]])),after=await db.prepare('SELECT * FROM workflow_provider_connections').first();assert.deepEqual(result,{ok:true,outputText:'OK'});assert.equal(received.credential,secret);assert.deepEqual(after,before);assert.deepEqual(await counts(),{runs:0,attempts:0});assert.deepEqual(definitions,{agents:0,workflows:0});assert.equal(JSON.stringify(result).includes(secret),false)});
test('unconfigured diagnostic does not call a provider',async()=>{let calls=0;const store={resolveCredential:async()=>{throw new Error('connection_unavailable')}};const adapter={testConnection:async()=>{calls++;return{ok:true,outputText:'bad'}}};assert.deepEqual(await testWorkflowConnection('openai-primary',store,new Map([['openai-responses',adapter]])),{ok:false,category:'connection_unavailable',safeMessage:'Connection is not configured.'});assert.equal(calls,0)});
test('test route is protected, same-origin, no-store, and ignores browser input',async()=>{const source=await readFile(new URL('../app/api/workflow-connections/[connectionKey]/test/route.ts',import.meta.url),'utf8');assert.match(source,/requireApiRepositoryAccess/);assert.match(source,/sameOrigin\(request\)/);assert.match(source,/noStoreHeaders/);assert.doesNotMatch(source,/request\.(json|text|formData)\(/);for(const prohibited of ['prompt','endpoint','model','credential','headers','providerOptions'])assert.doesNotMatch(source,new RegExp(`body\\.${prohibited}`))});
