import test from 'node:test';import assert from 'node:assert/strict';
import {workflowDefinitionSchema,compileWorkflowV2,validateWorkflowReferences,workflowAgentReferences} from '../lib/workflow-definitions.ts';
import {workflowBlockRegistry} from '../lib/workflow-block-registry.ts';import {InMemoryWorkflowDefinitionRepository} from '../lib/workflow-definition-repository.ts';
const agent=id=>({schemaVersion:2,id,name:id,description:'',status:'draft',connectionKey:'ready',prompt:{source:'custom',text:'prompt'},masterPrompt:'prompt'});const agents=['a','b','c'].map(agent);
const graph=(nodes=['a','b','c'],edges=[['a','b'],['b','c']])=>({schemaVersion:2,id:'graph',name:'Graph',description:'',status:'draft',nodes:nodes.map(id=>({id:`node-${id}`,blockType:'agent',blockVersion:1,config:{agentId:id}})),edges:edges.map(([source,target])=>({id:`edge-${source}-${target}`,source:`node-${source}`,target:`node-${target}`})),limits:{maxStepExecutions:32}});
test('Workflow v2 validates and round-trips through the definition repository',async()=>{const repo=new InMemoryWorkflowDefinitionRepository(),value=workflowDefinitionSchema.parse(graph()),created=await repo.createWorkflow(value);assert.deepEqual((await repo.getWorkflow('graph')).definition,value);await assert.rejects(repo.updateWorkflow({...value,name:'stale'},'wrong'),/changed/);assert.equal(created.definition.schemaVersion,2)});
test('Block Registry owns Agent config validation and fails closed for unknown type/version/config',()=>{assert.deepEqual(workflowBlockRegistry.validate('agent',1,{agentId:'a'}),{agentId:'a'});for(const node of [{blockType:'missing',blockVersion:1,config:{}},{blockType:'agent',blockVersion:2,config:{agentId:'a'}},{blockType:'agent',blockVersion:1,config:{agent:'a'}}])assert.throws(()=>workflowDefinitionSchema.parse({...graph(['a'],[]),nodes:[{id:'node-a',...node}]}))});
test('linear compilation derives deterministic order from edges, not node array order',()=>{const shuffled=graph(['c','a','b']);assert.deepEqual(compileWorkflowV2(shuffled,agents).steps.map(x=>x.id),['node-a','node-b','node-c']);assert.deepEqual(compileWorkflowV2({...shuffled,nodes:[...shuffled.nodes].reverse()},agents).steps.map(x=>x.agentId),['a','b','c'])});
test('Phase 9 rejects branching, joins, cycles, disconnected and ambiguous topology',()=>{const cases=[graph(['a','b','c'],[['a','b'],['a','c']]),graph(['a','b','c'],[['a','c'],['b','c']]),graph(['a','b','c'],[['a','b'],['b','a']]),graph(['a','b','c'],[['a','b']]),graph(['a','b'],[])];for(const value of cases)assert.throws(()=>compileWorkflowV2(value,agents),/unsupported_workflow_topology/)});
test('references and connections fail before execution and v2 Agent use is discoverable',async()=>{assert.deepEqual(workflowAgentReferences(graph()),['a','b','c']);await assert.rejects(validateWorkflowReferences(graph(),agents.slice(0,2),new Set(['ready'])),/missing_agent:c/);await assert.rejects(validateWorkflowReferences(graph(),agents,new Set()),/connection_unavailable:ready/)});
test('compiled v2 preserves stable node IDs and sequential handoff contract',()=>{const compiled=compileWorkflowV2(graph(),agents);assert.deepEqual(compiled.steps.map(({id,input,onSuccess})=>({id,input:input.source,onSuccess:onSuccess.type})),[{id:'node-a',input:'run_input',onSuccess:'next'},{id:'node-b',input:'previous_step',onSuccess:'next'},{id:'node-c',input:'previous_step',onSuccess:'complete'}]);assert.equal(compiled.result.stepId,'node-c')});

import {persistWorkflowLayout,persistWorkflowSemantics} from '../lib/workflow-editor-persistence.ts';
import {normalizeWorkflowLayout,projectSequentialWorkflow} from '../lib/workflow-layout.ts';
import {InMemoryWorkflowLayoutRepository} from '../lib/workflow-layout-repository.ts';
import {addV1Step,moveV1Step,removeV1Step,replaceV1StepAgent} from '../lib/workflow-v1-editor.ts';

test('existing v2 layout save never invokes the semantic Workflow endpoint',async()=>{const calls=[],value=graph(),layout=normalizeWorkflowLayout(value,{'node-a':{x:90,y:40}},{x:2,y:3,zoom:1.2}),fetcher=async(url,init)=>{calls.push({url,body:JSON.parse(init.body)});return Response.json({fileSha:'layout-next'})};assert.equal(await persistWorkflowLayout(fetcher,layout,'layout-old'),'layout-next');assert.deepEqual(calls.map(call=>call.url),['/api/workflow-definitions/graph/layout']);assert.equal(calls[0].body.fileSha,'layout-old')});
test('semantic edge save mutates only the revision-aware Workflow definition',async()=>{const calls=[],value={...graph(),edges:[{id:'edge-b-a',source:'node-b',target:'node-a'},{id:'edge-a-c',source:'node-a',target:'node-c'}]},fetcher=async(url,init)=>{calls.push({url,body:JSON.parse(init.body)});return Response.json({fileSha:'workflow-next'})};assert.equal(await persistWorkflowSemantics(fetcher,value,'workflow-old'),'workflow-next');assert.deepEqual(calls.map(call=>call.url),['/api/workflow-definitions/graph']);assert.equal(calls[0].body.fileSha,'workflow-old');assert.deepEqual(calls[0].body.definition.edges,value.edges)});
test('Workflow and layout revisions remain independently stale-safe',async()=>{const definitions=new InMemoryWorkflowDefinitionRepository(),layouts=new InMemoryWorkflowLayoutRepository(),createdWorkflow=await definitions.createWorkflow(graph()),createdLayout=await layouts.createLayout(normalizeWorkflowLayout(graph(),{}, {x:0,y:0,zoom:1}));await assert.rejects(definitions.updateWorkflow({...graph(),name:'changed'},'stale'),/changed/);await assert.rejects(layouts.updateLayout(normalizeWorkflowLayout(graph(),{}, {x:9,y:9,zoom:1}),'stale'),/changed/);assert.equal((await definitions.updateWorkflow({...graph(),name:'changed'},createdWorkflow.fileSha)).definition.name,'changed');assert.equal((await layouts.updateLayout(normalizeWorkflowLayout(graph(),{}, {x:9,y:9,zoom:1}),createdLayout.fileSha)).definition.viewport.x,9)});
test('v1 editor operations add, remove, reorder and replace Agents without removing the last step',()=>{assert.deepEqual(addV1Step(['a'],'b'),['a','b']);assert.deepEqual(moveV1Step(['a','b','c'],2,-1),['a','c','b']);assert.deepEqual(replaceV1StepAgent(['a','b'],0,'c'),['c','b']);assert.deepEqual(removeV1Step(['a','b'],0),['b']);assert.deepEqual(removeV1Step(['a'],0),['a'])});
test('shuffled v2 node arrays project Agent blocks without array-derived execution ordinals',()=>{const projected=projectSequentialWorkflow(graph(['c','a','b']));assert.deepEqual(projected.nodes.map(node=>({id:node.id,kind:node.data.kind,stepNumber:node.data.stepNumber})),[{id:'node-c',kind:'block',stepNumber:undefined},{id:'node-a',kind:'block',stepNumber:undefined},{id:'node-b',kind:'block',stepNumber:undefined}])});
