import test from 'node:test';import assert from 'node:assert/strict';
import {WorkflowProviderConnectionMigrationService} from '../lib/workflow-provider-connection-migration.ts';
import {createWorkflowProviderSecretResolver} from '../lib/workflow-provider-secret-resolver.ts';
const sentinel='provider-plaintext-sentinel',legacyRef='WORKFLOW_PROVIDER_CONNECTION_PRIMARY',vaultRef=`sec_${'v'.repeat(43)}`;
const definition=(runtime='openai-responses',credential={secretRef:legacyRef})=>({schemaVersion:1,id:'primary',name:'Primary',runtime,provider:'openai',model:'gpt-test',credential});
function fixture(options={}){const {git,d1,updateError,createError}=options,secret=Object.hasOwn(options,"secret")?options.secret:sentinel;const calls={created:[],deleted:[],updated:[],createdGit:[],d1:0};const repository={getConnection:async()=>{if(options.repositoryError)throw new Error("connection_repository_unavailable");return git},updateConnection:async(value,revision)=>{calls.updated.push({value,revision});if(updateError)throw new Error(updateError);return{definition:value,fileSha:'new-revision',sourcePath:'connections/primary.connection.json'}},createConnection:async value=>{calls.createdGit.push(value);if(createError)throw new Error(createError);return{definition:value,fileSha:'created-revision',sourcePath:'connections/primary.connection.json'}}};const store={getPersistedSafeDescriptor:async()=>options.persisted===false?undefined:d1?.descriptor,getLegacyMigrationSource:async()=>{calls.d1++;if(options.d1Error)throw new Error("connection_unavailable");return d1}};const secrets=createWorkflowProviderSecretResolver(ref=>ref===legacyRef?secret:undefined);const vault={create:async value=>{calls.created.push(value);return vaultRef},delete:async ref=>calls.deleted.push(ref)};return{service:new WorkflowProviderConnectionMigrationService(repository,store,secrets,vault),calls}}

test('inspection identifies D1, legacy Git binding, missing binding, and vault states without leaking credentials',async()=>{const d1={descriptor:{key:'primary',name:'Primary',adapter:'openai-responses',defaultModel:'gpt-test'},credential:sentinel,sourceVersion:'opaque-version'};for(const [options,state] of [[{d1},'d1_eligible'],[{git:{definition:definition(),fileSha:'r1'}},'git_binding_eligible'],[{git:{definition:definition(),fileSha:'r1'},secret:undefined},'git_binding_unavailable'],[{git:{definition:definition('openai-agents',{source:'adt-vault',secretRef:vaultRef}),fileSha:'r1'}},'already_vault']]){const result=await fixture(options).service.inspect('primary');assert.equal(result.state,state);assert.doesNotMatch(JSON.stringify(result),new RegExp(sentinel));}});

test('Cloudflare migration is source-exact, preserves both runtimes, and sends only a vault ref to Git',async()=>{for(const runtime of ['openai-responses','openai-agents']){const f=fixture({git:{definition:definition(runtime),fileSha:'r1'}});await f.service.migrate('primary',{expectedSource:'cloudflare-binding',repositoryRevision:'r1'});assert.deepEqual(f.calls.created,[sentinel]);assert.equal(f.calls.d1,0);assert.equal(f.calls.updated[0].value.runtime,runtime);assert.deepEqual(f.calls.updated[0].value.credential,{source:'adt-vault',secretRef:vaultRef});assert.doesNotMatch(JSON.stringify(f.calls.updated),new RegExp(sentinel));}});

test('stale Git state and missing binding fail before vault mutation without D1 fallback',async()=>{for(const input of [{git:{definition:definition(),fileSha:'r2'}},{git:{definition:definition(),fileSha:'r1'},secret:undefined}]){const f=fixture(input);await assert.rejects(f.service.migrate('primary',{expectedSource:'cloudflare-binding',repositoryRevision:'r1'}));assert.equal(f.calls.created.length,0);assert.equal(f.calls.d1,0)}});

test('definite Git conflict deletes the new vault value while ambiguous mutation retains it',async()=>{for(const [error,deleted] of [['connection_revision_conflict',1],['connection_repository_mutation_uncertain',0]]){const f=fixture({git:{definition:definition(),fileSha:'r1'},updateError:error});await assert.rejects(f.service.migrate('primary',{expectedSource:'cloudflare-binding',repositoryRevision:'r1'}),new RegExp(error));assert.equal(f.calls.deleted.length,deleted);assert.equal(f.calls.updated.length,1)}});

test('D1 migration preserves safe fields, re-encrypts via vault, and never alters the legacy source',async()=>{const source={descriptor:{key:'primary',name:'Primary',adapter:'openai-responses',defaultModel:'gpt-test'},credential:sentinel,sourceVersion:'opaque-version'},f=fixture({d1:source});await f.service.migrate('primary',{expectedSource:'legacy-d1',sourceVersion:'opaque-version'});assert.deepEqual(f.calls.created,[sentinel]);assert.equal(f.calls.createdGit[0].id,'primary');assert.equal(f.calls.createdGit[0].name,'Primary');assert.equal(f.calls.createdGit[0].model,'gpt-test');assert.deepEqual(f.calls.createdGit[0].credential,{source:'adt-vault',secretRef:vaultRef});assert.doesNotMatch(JSON.stringify(f.calls.createdGit),new RegExp(sentinel));assert.equal(source.credential,sentinel)});

test('stale D1 observation fails before mutation and D1 create conflict follows safe cleanup semantics',async()=>{let f=fixture({d1:{descriptor:{key:'primary',name:'Primary',adapter:'openai-responses',defaultModel:'gpt-test'},credential:sentinel,sourceVersion:'new'}});await assert.rejects(f.service.migrate('primary',{expectedSource:'legacy-d1',sourceVersion:'old'}),/migration_source_changed/);assert.equal(f.calls.created.length,0);for(const [error,deleted] of [['connection_exists',1],['connection_repository_mutation_uncertain',0]]){f=fixture({d1:{descriptor:{key:'primary',name:'Primary',adapter:'openai-responses',defaultModel:'gpt-test'},credential:sentinel,sourceVersion:'v'},createError:error});await assert.rejects(f.service.migrate('primary',{expectedSource:'legacy-d1',sourceVersion:'v'}));assert.equal(f.calls.deleted.length,deleted)}});

test('inspection reports unknown Git authority and existing unavailable D1 credentials honestly',async()=>{const unknown=await fixture({repositoryError:true}).service.inspect('primary');assert.equal(unknown.state,'temporarily_unavailable');assert.equal(unknown.currentSource,'unknown');assert.equal(unknown.canMigrate,false);const d1={descriptor:{key:'primary',name:'Primary',adapter:'openai-responses',defaultModel:'gpt-test'}};const unavailable=await fixture({d1,d1Error:true}).service.inspect('primary');assert.equal(unavailable.state,'d1_credential_unavailable');assert.equal(unavailable.currentSource,'legacy-d1');assert.equal(unavailable.canMigrate,false);assert.doesNotMatch(JSON.stringify(unavailable),/ciphertext|credential_iv|decryption|master.key/i);await assert.rejects(fixture({persisted:false}).service.inspect('primary'),/migration_source_not_found/) });
