import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {Miniflare} from 'miniflare';
import {D1WorkflowProviderConnectionStore} from '../lib/workflow-provider-connection-store.ts';
import {D1ProviderCredentialVault,isProviderCredentialVaultSecretId} from '../lib/provider-credential-vault.ts';
import {providerCredentialVaultV1KeyResolver} from '../lib/provider-credential-vault-crypto.ts';
import {WorkflowProviderConnectionMigrationService} from '../lib/workflow-provider-connection-migration.ts';
import {createWorkflowProviderSecretResolver} from '../lib/workflow-provider-secret-resolver.ts';
import {GitAuthoritativeWorkflowProviderConnectionStore} from '../lib/git-workflow-provider-connection-store.ts';

const key=Buffer.alloc(32,73).toString('base64'),credential='harmless-migration-sentinel-91f4',replacement='harmless-rotated-sentinel-28a7';
async function fixture(t){const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:{DB:crypto.randomUUID()}}),db=await mf.getD1Database('DB');t.after(()=>mf.dispose());for(const migration of ['0004_create_workflow_provider_connections.sql','0006_add_workflow_provider_connection_display_name.sql','0009_create_provider_credential_vault.sql']){const sql=await readFile(new URL(`../migrations/${migration}`,import.meta.url),'utf8');await db.batch(sql.split(';').map(x=>x.trim()).filter(Boolean).map(x=>db.prepare(x)))}const legacy=new D1WorkflowProviderConnectionStore(db,key),vault=new D1ProviderCredentialVault(db,providerCredentialVaultV1KeyResolver(key));let git;const repository={getConnection:async id=>git?.definition.id===id?git:undefined,createConnection:async definition=>(git={definition,fileSha:'created-revision',sourcePath:`connections/${definition.id}.connection.json`})};const service=new WorkflowProviderConnectionMigrationService(repository,legacy,createWorkflowProviderSecretResolver(()=>undefined),vault);return{db,legacy,vault,repository,service,get git(){return git}}}
const rawLegacy=(db,id)=>db.prepare('SELECT * FROM workflow_provider_connections WHERE connection_key=?').bind(id).first();

test('real D1 migration freshly encrypts into the vault, preserves Git-safe fields, and retains the exact legacy row',async t=>{const f=await fixture(t),id='legacy-real';await f.legacy.upsertConnection({connectionKey:id,displayName:'Legacy real',adapter:'openai-responses',model:'gpt-safe',credential});const before=await rawLegacy(f.db,id),beforeBytes=JSON.stringify(before);assert.doesNotMatch(beforeBytes,new RegExp(credential));assert.equal((await f.legacy.resolveCredential(id)).credential,credential);const inspected=await f.service.inspect(id),inspectionJson=JSON.stringify(inspected);assert.equal(inspected.state,'d1_eligible');assert.equal(inspected.currentSource,'legacy-d1');assert.match(inspected.sourceVersion,/^[A-Za-z0-9_-]{43}$/);for(const secret of [credential,before.encrypted_credential,before.credential_iv])assert.doesNotMatch(inspectionJson,new RegExp(secret.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));await f.service.migrate(id,{expectedSource:'legacy-d1',sourceVersion:inspected.sourceVersion});const definition=f.git.definition,gitJson=JSON.stringify(definition);assert.equal(definition.id,id);assert.equal(definition.name,'Legacy real');assert.equal(definition.runtime,'openai-responses');assert.equal(definition.model,'gpt-safe');assert.equal(definition.credential.source,'adt-vault');assert.ok(isProviderCredentialVaultSecretId(definition.credential.secretRef));assert.doesNotMatch(gitJson,/harmless-migration|encrypted_credential|credential_iv/);const vaultRow=await f.db.prepare('SELECT * FROM provider_credential_vault WHERE secret_id=?').bind(definition.credential.secretRef).first();assert.doesNotMatch(JSON.stringify(vaultRow),new RegExp(credential));assert.equal(JSON.stringify(await rawLegacy(f.db,id)),beforeBytes);const freshVault=new D1ProviderCredentialVault(f.db,providerCredentialVaultV1KeyResolver(key));assert.equal(await freshVault.resolve(definition.credential.secretRef),credential);assert.equal((await f.legacy.resolveCredential(id)).credential,credential);const current=new GitAuthoritativeWorkflowProviderConnectionStore(f.repository,f.legacy,createWorkflowProviderSecretResolver(()=>undefined),async()=>{},freshVault);const descriptor=await current.getSafeDescriptor(id);assert.equal(descriptor.credentialSource,'adt-vault');assert.equal((await current.resolveCredential(id,descriptor)).credential,credential);assert.doesNotMatch(JSON.stringify(descriptor),new RegExp(credential))});

test('real source fingerprint changes for credential envelopes and metadata, stays stable otherwise, and rejects stale migration',async t=>{const f=await fixture(t),id='legacy-race';await f.legacy.upsertConnection({connectionKey:id,displayName:'Race',adapter:'openai-responses',model:'gpt-one',credential});const first=await f.service.inspect(id),stable=await f.service.inspect(id);assert.equal(first.sourceVersion,stable.sourceVersion);const firstRow=await rawLegacy(f.db,id);for(const secret of [credential,firstRow.encrypted_credential,firstRow.credential_iv])assert.equal(first.sourceVersion.includes(secret),false);await f.legacy.upsertConnection({connectionKey:id,displayName:'Race',adapter:'openai-responses',model:'gpt-one',credential:replacement});const rotated=await f.service.inspect(id);assert.notEqual(rotated.sourceVersion,first.sourceVersion);await assert.rejects(f.service.migrate(id,{expectedSource:'legacy-d1',sourceVersion:first.sourceVersion}),/migration_source_changed/);assert.equal((await f.db.prepare('SELECT count(*) AS count FROM provider_credential_vault').first()).count,0);assert.equal(f.git,undefined);await f.legacy.upsertConnection({connectionKey:id,displayName:'Renamed',adapter:'openai-responses',model:'gpt-two'});const metadata=await f.service.inspect(id);assert.notEqual(metadata.sourceVersion,rotated.sourceVersion);await f.service.migrate(id,{expectedSource:'legacy-d1',sourceVersion:metadata.sourceVersion});assert.equal(await f.vault.resolve(f.git.definition.credential.secretRef),replacement)});

test('existing corrupt D1 credential is a safe unavailable state rather than not found',async t=>{const f=await fixture(t),id='legacy-broken';await f.legacy.upsertConnection({connectionKey:id,displayName:'Broken',adapter:'openai-responses',model:'gpt-safe',credential});await f.db.prepare("UPDATE workflow_provider_connections SET credential_iv='damaged-envelope'").run();const result=await f.service.inspect(id),serialized=JSON.stringify(result);assert.equal(result.state,'d1_credential_unavailable');assert.equal(result.currentSource,'legacy-d1');assert.equal(result.canMigrate,false);assert.equal(result.sourceVersion,undefined);assert.doesNotMatch(serialized,/damaged-envelope|decryption|ciphertext|credential_iv|harmless-migration/)});
