import test from 'node:test';import assert from 'node:assert/strict';
import {workflowDefinitionSchema,compileWorkflowV2,compileWorkflowV2ExecutionPlan,validateWorkflowReferences,workflowAgentReferences} from '../lib/workflow-definitions.ts';
import {workflowBlockRegistry} from '../lib/workflow-block-registry.ts';import {InMemoryWorkflowDefinitionRepository} from '../lib/workflow-definition-repository.ts';
const agent=id=>({schemaVersion:2,id,name:id,description:'',status:'draft',connectionKey:'ready',prompt:{source:'custom',text:'prompt'},masterPrompt:'prompt'});const agents=['a','b','c'].map(agent);
const graph=(nodes=['a','b','c'],edges=[['a','b'],['b','c']])=>({schemaVersion:2,id:'graph',name:'Graph',description:'',status:'draft',nodes:nodes.map(id=>({id:`node-${id}`,blockType:'agent',blockVersion:1,config:{agentId:id}})),edges:edges.map(([source,target])=>({id:`edge-${source}-${target}`,source:`node-${source}`,target:`node-${target}`})),limits:{maxStepExecutions:32}});
test('Workflow v2 validates and round-trips through the definition repository',async()=>{const repo=new InMemoryWorkflowDefinitionRepository(),value=workflowDefinitionSchema.parse(graph()),created=await repo.createWorkflow(value);assert.deepEqual((await repo.getWorkflow('graph')).definition,value);await assert.rejects(repo.updateWorkflow({...value,name:'stale'},'wrong'),/changed/);assert.equal(created.definition.schemaVersion,2)});
test('Block Registry owns Agent config validation and fails closed for unknown type/version/config',()=>{assert.deepEqual(workflowBlockRegistry.validate('agent',1,{agentId:'a'}),{agentId:'a'});for(const node of [{blockType:'missing',blockVersion:1,config:{}},{blockType:'agent',blockVersion:2,config:{agentId:'a'}},{blockType:'agent',blockVersion:1,config:{agent:'a'}}])assert.throws(()=>workflowDefinitionSchema.parse({...graph(['a'],[]),nodes:[{id:'node-a',...node}]}))});
test('linear compilation derives deterministic order from edges, not node array order',()=>{const shuffled=graph(['c','a','b']);assert.deepEqual(compileWorkflowV2(shuffled,agents).steps.map(x=>x.id),['node-a','node-b','node-c']);assert.deepEqual(compileWorkflowV2({...shuffled,nodes:[...shuffled.nodes].reverse()},agents).steps.map(x=>x.agentId),['a','b','c'])});
test('Phase 9 rejects branching, joins, cycles, disconnected and ambiguous topology',()=>{const cases=[graph(['a','b','c'],[['a','b'],['a','c']]),graph(['a','b','c'],[['a','c'],['b','c']]),graph(['a','b','c'],[['a','b'],['b','a']]),graph(['a','b','c'],[['a','b']]),graph(['a','b'],[])];for(const value of cases)assert.throws(()=>compileWorkflowV2(value,agents),/unsupported_workflow_topology/)});
test('references and connections fail before execution and v2 Agent use is discoverable',async()=>{assert.deepEqual(workflowAgentReferences(graph()),['a','b','c']);await assert.rejects(validateWorkflowReferences(graph(),agents.slice(0,2),new Set(['ready'])),/missing_agent:c/);await assert.rejects(validateWorkflowReferences(graph(),agents,new Set()),/connection_unavailable:ready/)});
test('compiled v2 preserves stable node IDs and sequential handoff contract',()=>{const compiled=compileWorkflowV2(graph(),agents);assert.deepEqual(compiled.steps.map(({id,input,onSuccess})=>({id,input:input.source,onSuccess:onSuccess.type})),[{id:'node-a',input:'run_input',onSuccess:'next'},{id:'node-b',input:'previous_step',onSuccess:'next'},{id:'node-c',input:'previous_step',onSuccess:'complete'}]);assert.equal(compiled.result.stepId,'node-c')});

import {persistWorkflowLayout,persistWorkflowSemantics} from '../lib/workflow-editor-persistence.ts';
import {normalizeWorkflowLayout,projectSequentialWorkflow} from '../lib/workflow-layout.ts';
import {InMemoryWorkflowLayoutRepository} from '../lib/workflow-layout-repository.ts';
import {addV1Step,moveV1Step,removeV1Step,replaceV1StepAgent} from '../lib/workflow-v1-editor.ts';

test('existing v2 layout save never invokes the semantic Workflow endpoint',async()=>{const calls=[],value=graph(),layout=normalizeWorkflowLayout(value,{'node-a':{x:90,y:40}},{x:2,y:3,zoom:1.2}),fetcher=async(url,init)=>{calls.push({url,body:JSON.parse(init.body)});return Response.json({fileSha:'layout-next'})};assert.equal(await persistWorkflowLayout(fetcher,layout,'layout-old'),'layout-next');assert.deepEqual(calls.map(call=>call.url),['/api/workflow-definitions/graph/layout']);assert.equal(calls[0].body.fileSha,'layout-old')});
test('semantic edge save mutates only the revision-aware Workflow definition',async()=>{const calls=[],value={...graph(),edges:[{id:'edge-b-a',source:'node-b',target:'node-a'},{id:'edge-a-c',source:'node-a',target:'node-c'}]},fetcher=async(url,init)=>{calls.push({url,body:JSON.parse(init.body)});return Response.json({fileSha:'workflow-next'})};assert.equal(await persistWorkflowSemantics(fetcher,value,'workflow-old'),'workflow-next');assert.deepEqual(calls.map(call=>call.url),['/api/workflow-definitions/graph']);assert.equal(calls[0].body.fileSha,'workflow-old');assert.deepEqual(calls[0].body.definition.edges,value.edges)});
test('Workflow and layout revisions remain independently stale-safe',async()=>{const definitions=new InMemoryWorkflowDefinitionRepository(),layouts=new InMemoryWorkflowLayoutRepository(),createdWorkflow=await definitions.createWorkflow(graph()),createdLayout=await layouts.createLayout(normalizeWorkflowLayout(graph(),{}, {x:0,y:0,zoom:1}));await assert.rejects(definitions.updateWorkflow({...graph(),name:'changed'},'stale'),/changed/);await assert.rejects(layouts.updateLayout(normalizeWorkflowLayout(graph(),{}, {x:9,y:9,zoom:1}),'stale'),/changed/);assert.equal((await definitions.updateWorkflow({...graph(),name:'changed'},createdWorkflow.fileSha)).definition.name,'changed');assert.equal((await layouts.updateLayout(normalizeWorkflowLayout(graph(),{}, {x:9,y:9,zoom:1}),createdLayout.fileSha)).definition.viewport.x,9)});
test('v1 editor operations add, remove, reorder and replace Agents without removing the last step',()=>{assert.deepEqual(addV1Step(['a'],'b'),['a','b']);assert.deepEqual(moveV1Step(['a','b','c'],2,-1),['a','c','b']);assert.deepEqual(replaceV1StepAgent(['a','b'],0,'c'),['c','b']);assert.deepEqual(removeV1Step(['a','b'],0),['b']);assert.deepEqual(removeV1Step(['a'],0),['a'])});
test('shuffled v2 node arrays project Agent blocks without array-derived execution ordinals',()=>{const projected=projectSequentialWorkflow(graph(['c','a','b']));assert.deepEqual(projected.nodes.map(node=>({id:node.id,kind:node.data.kind,stepNumber:node.data.stepNumber})),[{id:'node-c',kind:'block',stepNumber:undefined},{id:'node-a',kind:'block',stepNumber:undefined},{id:'node-b',kind:'block',stepNumber:undefined}])});

const conditionGraph=()=>({schemaVersion:2,id:'condition-graph',name:'Condition graph',description:'',status:'draft',nodes:[{id:'research',blockType:'agent',blockVersion:1,config:{agentId:'a'}},{id:'decision',blockType:'condition',blockVersion:1,config:{operator:'contains',value:'approved',caseSensitive:false}},{id:'accept',blockType:'agent',blockVersion:1,config:{agentId:'b'}},{id:'revise',blockType:'agent',blockVersion:1,config:{agentId:'c'}},{id:'finish',blockType:'agent',blockVersion:1,config:{agentId:'a'}}],edges:[{id:'research-decision',source:'research',target:'decision'},{id:'decision-true',source:'decision',sourcePort:'true',target:'accept',targetPort:'in'},{id:'decision-false',source:'decision',sourcePort:'false',target:'revise',targetPort:'in'},{id:'accept-finish',source:'accept',target:'finish'},{id:'revise-finish',source:'revise',target:'finish'}],limits:{maxStepExecutions:32}});
test('semantic ports, Agent and Condition contracts validate and persist',async()=>{const value=workflowDefinitionSchema.parse(conditionGraph()),repo=new InMemoryWorkflowDefinitionRepository();assert.equal(value.edges[1].sourcePort,'true');assert.deepEqual(workflowBlockRegistry.resolve('condition',1).interface.outputs.map(port=>port.id),['true','false']);await repo.createWorkflow(value);assert.deepEqual((await repo.getWorkflow(value.id)).definition,value)});
test('omitted default ports remain valid while invalid ports and incomplete Condition routes fail safely',()=>{assert.doesNotThrow(()=>workflowDefinitionSchema.parse(graph()));for(const mutate of [value=>({...value,edges:value.edges.map((edge,index)=>index===0?{...edge,sourcePort:'missing'}:edge)}),value=>({...value,edges:value.edges.filter(edge=>edge.sourcePort!=='false')})])assert.throws(()=>workflowDefinitionSchema.parse(mutate(conditionGraph())))});
test('generic execution plan freezes block configs and resolved semantic ports independent of array order',async()=>{const {compileWorkflowV2ExecutionPlan}=await import('../lib/workflow-definitions.ts'),value=conditionGraph(),a=compileWorkflowV2ExecutionPlan(value,agents),b=compileWorkflowV2ExecutionPlan({...value,nodes:[...value.nodes].reverse(),edges:[...value.edges].reverse()},agents);assert.equal(a.planVersion,2);assert.deepEqual(new Set(a.edges.map(edge=>`${edge.source}:${edge.sourcePort}->${edge.target}:${edge.targetPort}`)),new Set(b.edges.map(edge=>`${edge.source}:${edge.sourcePort}->${edge.target}:${edge.targetPort}`)));assert.deepEqual(a.nodes.find(node=>node.id==='decision').config,{operator:'contains',value:'approved',caseSensitive:false})});

test('Join ports, structured fan-out, and deterministic plan config are accepted',()=>{const value={schemaVersion:2,id:'parallel',name:'Parallel',description:'',status:'draft',nodes:[{id:'input',blockType:'agent',blockVersion:1,config:{agentId:'a'}},{id:'left',blockType:'agent',blockVersion:1,config:{agentId:'b'}},{id:'right',blockType:'agent',blockVersion:1,config:{agentId:'c'}},{id:'join',blockType:'join',blockVersion:1,config:{}},{id:'finish',blockType:'agent',blockVersion:1,config:{agentId:'a'}}],edges:[['input','left'],['input','right'],['left','join'],['right','join'],['join','finish']].map(([source,target])=>({id:`${source}-${target}`,source,target})),limits:{maxStepExecutions:4}},parsed=workflowDefinitionSchema.parse(value);assert.deepEqual(workflowBlockRegistry.resolve('join',1).interface.inputs,[{id:'in',dataType:'text',default:true,multiple:true}]);assert.equal(parsed.nodes.find(node=>node.id==='join').blockType,'join')});
test('controlled Condition cycle validates while unconditional and no-exit cycles fail',()=>{const controlled={schemaVersion:2,id:'loop',name:'Loop',description:'',status:'draft',nodes:[{id:'draft',blockType:'agent',blockVersion:1,config:{agentId:'a'}},{id:'review',blockType:'agent',blockVersion:1,config:{agentId:'b'}},{id:'condition',blockType:'condition',blockVersion:1,config:{operator:'contains',value:'approved',caseSensitive:false}},{id:'finish',blockType:'agent',blockVersion:1,config:{agentId:'c'}}],edges:[{id:'draft-review',source:'draft',target:'review'},{id:'review-condition',source:'review',target:'condition'},{id:'condition-true',source:'condition',sourcePort:'true',target:'finish'},{id:'condition-false',source:'condition',sourcePort:'false',target:'draft'}],limits:{maxStepExecutions:2}};assert.doesNotThrow(()=>workflowDefinitionSchema.parse(controlled));const unconditional={...controlled,nodes:controlled.nodes.filter(node=>node.id!=='condition'),edges:[{id:'draft-review',source:'draft',target:'review'},{id:'review-draft',source:'review',target:'draft'},{id:'review-finish',source:'review',target:'finish'}]};assert.throws(()=>workflowDefinitionSchema.parse(unconditional),/Every cycle must contain a Condition/);const noExit={...controlled,edges:controlled.edges.filter(edge=>edge.sourcePort!=='true')};assert.throws(()=>workflowDefinitionSchema.parse(noExit))});
test('plan nodes reject configuration belonging to a different block type',async()=>{const {genericWorkflowExecutionPlanSchema}=await import('../lib/workflow-definitions.ts'),base={planVersion:2,edges:[],entryNodeId:'a',terminalNodeId:'a',maxStepExecutions:1};assert.throws(()=>genericWorkflowExecutionPlanSchema.parse({...base,nodes:[{id:'a',blockType:'agent',blockVersion:1,config:{operator:'contains',value:'x',caseSensitive:false}}]}));assert.throws(()=>genericWorkflowExecutionPlanSchema.parse({...base,nodes:[{id:'a',blockType:'condition',blockVersion:1,config:{agentId:'a'}}]}))});

test('Join rejects conditional, bypassing, unrelated, and nested ambiguous predecessors',()=>{const agentNode=id=>({id,blockType:'agent',blockVersion:1,config:{agentId:'a'}}),join={id:'join',blockType:'join',blockVersion:1,config:{}},condition={id:'condition',blockType:'condition',blockVersion:1,config:{operator:'contains',value:'x',caseSensitive:false}},definition=(nodes,edges)=>({schemaVersion:2,id:'invalid-join',name:'Invalid',description:'',status:'draft',nodes,edges:edges.map((edge,i)=>({id:`e-${i}`,...edge})),limits:{maxStepExecutions:32}});const cases=[definition([agentNode('entry'),condition,agentNode('a'),agentNode('b'),join,agentNode('finish')],[{source:'entry',target:'condition'},{source:'condition',sourcePort:'true',target:'a'},{source:'condition',sourcePort:'false',target:'b'},{source:'a',target:'join'},{source:'b',target:'join'},{source:'join',target:'finish'}]),definition([agentNode('entry'),agentNode('a'),agentNode('b'),join,agentNode('bypass'),agentNode('finish')],[{source:'entry',target:'a'},{source:'entry',target:'b'},{source:'a',target:'join'},{source:'a',target:'bypass'},{source:'b',target:'join'},{source:'join',target:'finish'},{source:'bypass',target:'finish'}]),definition([agentNode('left-origin'),agentNode('right-origin'),agentNode('a'),agentNode('b'),join,agentNode('finish')],[{source:'left-origin',target:'a'},{source:'right-origin',target:'b'},{source:'a',target:'join'},{source:'b',target:'join'},{source:'join',target:'finish'}])];for(const value of cases)assert.throws(()=>workflowDefinitionSchema.parse(value))});
test('cyclic exit must be directly Condition-controlled',()=>{const value={schemaVersion:2,id:'bad-loop-exit',name:'Bad loop',description:'',status:'draft',nodes:[{id:'draft',blockType:'agent',blockVersion:1,config:{agentId:'a'}},{id:'condition',blockType:'condition',blockVersion:1,config:{operator:'contains',value:'x',caseSensitive:false}},{id:'branch',blockType:'agent',blockVersion:1,config:{agentId:'b'}},{id:'finish',blockType:'agent',blockVersion:1,config:{agentId:'c'}}],edges:[{id:'d-c',source:'draft',target:'condition'},{id:'c-t',source:'condition',sourcePort:'true',target:'branch'},{id:'c-f',source:'condition',sourcePort:'false',target:'draft'},{id:'b-d',source:'branch',target:'draft'},{id:'b-f',source:'branch',target:'finish'}],limits:{maxStepExecutions:10}};assert.throws(()=>workflowDefinitionSchema.parse(value),/Condition-controlled structural exit|cyclic region/)});

test('approval@1 round-trips strictly and compiles without an Agent reference',()=>{const workflow=workflowDefinitionSchema.parse({schemaVersion:2,id:'approval-flow',name:'Approval flow',description:'',status:'draft',nodes:[{id:'first',blockType:'agent',blockVersion:1,config:{agentId:'agent-a'}},{id:'review',blockType:'approval',blockVersion:1,config:{message:'Approve this result?'}},{id:'last',blockType:'agent',blockVersion:1,config:{agentId:'agent-b'}}],edges:[{id:'one',source:'first',target:'review'},{id:'two',source:'review',target:'last'}],limits:{maxStepExecutions:3}});const plan=compileWorkflowV2ExecutionPlan(workflow,[agent('agent-a'),agent('agent-b')]);assert.equal(plan.nodes[1].blockType,'approval');assert.deepEqual(workflowAgentReferences(workflow),['agent-a','agent-b']);assert.throws(()=>workflowDefinitionSchema.parse({...workflow,nodes:workflow.nodes.map(node=>node.id==='review'?{...node,config:{message:'ok',role:'admin'}}:node)}));});
