import test from 'node:test';
import assert from 'node:assert/strict';
import {compileWorkflowV2ExecutionPlan,composeVersionedWorkflowV2,workflowDefinitionSchema} from '../lib/workflow-definitions.ts';
const agent=id=>({schemaVersion:2,id,name:id,description:'',status:'draft',connectionKey:'ready',prompt:{source:'custom',text:'prompt'},masterPrompt:'prompt'});
const contextGraph=()=>({schemaVersion:2,id:'context',name:'Context',description:'',status:'draft',nodes:[
 {id:'producer',blockType:'agent',blockVersion:2,config:{agentId:'a',context:{publishOutput:true,includeRunInput:false,includeNodeOutputs:[]}}},
 {id:'consumer',blockType:'agent',blockVersion:2,config:{agentId:'b',context:{publishOutput:false,includeRunInput:true,includeNodeOutputs:['producer']}}},
],edges:[{id:'handoff',source:'producer',target:'consumer'}],limits:{maxStepExecutions:4}});
test('agent@2 freezes context while legacy agent@1 remains byte-compatible',()=>{const legacy={...contextGraph(),nodes:contextGraph().nodes.map(node=>({id:node.id,blockType:'agent',blockVersion:1,config:{agentId:node.config.agentId}}))},legacyPlan=compileWorkflowV2ExecutionPlan(legacy,[agent('a'),agent('b')]),plan=compileWorkflowV2ExecutionPlan(contextGraph(),[agent('a'),agent('b')]);assert.deepEqual(legacyPlan.nodes.map(node=>node.config),[{agentId:'a'},{agentId:'b'}]);assert.deepEqual(plan.nodes[1].config.context,{publishOutput:false,includeRunInput:true,includeNodeOutputs:['producer']})});
test('context references fail closed for self, missing, non-publishing, and structurally-later sources',()=>{for(const source of ['consumer','missing'])assert.throws(()=>workflowDefinitionSchema.parse({...contextGraph(),nodes:contextGraph().nodes.map(node=>node.id==='consumer'?{...node,config:{...node.config,context:{...node.config.context,includeNodeOutputs:[source]}}}:node)}));const notPublished=contextGraph();notPublished.nodes[0].config.context.publishOutput=false;assert.throws(()=>workflowDefinitionSchema.parse(notPublished));const later=contextGraph();later.nodes[0].config.context.includeNodeOutputs=['consumer'];assert.throws(()=>workflowDefinitionSchema.parse(later))});
test('context references do not create topology and child references remap to scoped execution IDs',()=>{const child=workflowDefinitionSchema.parse({...contextGraph(),id:'child-context',name:'Child',exposableAsBlock:true}),parent=workflowDefinitionSchema.parse({schemaVersion:2,id:'parent-context',name:'Parent',description:'',status:'draft',nodes:[{id:'child-call',blockType:'subworkflow',blockVersion:1,config:{workflowId:'child-context'}}],edges:[],limits:{maxStepExecutions:4}}),composed=composeVersionedWorkflowV2({definition:parent,fileSha:'parent'},[{definition:child,fileSha:'child'}]),producer=composed.composition.nodes.find(node=>node.semanticNodeId==='producer').executionNodeId,consumer=composed.workflow.nodes.find(node=>node.id!==producer);assert.equal(composed.workflow.edges.length,1);assert.deepEqual(consumer.config.context.includeNodeOutputs,[producer])});
