import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {Miniflare} from 'miniflare';import {D1ProviderCredentialVault} from '../lib/provider-credential-vault.ts';import {providerCredentialVaultV1KeyResolver} from '../lib/provider-credential-vault-crypto.ts';import {WORK_IQ_OAUTH_CLEANUP_LIMIT,WORK_IQ_OAUTH_TTL_MS,WorkIqOAuthStateStore} from '../lib/work-iq-oauth.ts';
const key=Buffer.alloc(32,71).toString('base64');
async function fixture(t){const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:{DB:crypto.randomUUID()}}),db=await mf.getD1Database('DB');t.after(()=>mf.dispose());for(const name of ['0009_create_provider_credential_vault.sql','0019_add_work_iq_oauth_state.sql']){const sql=await readFile(new URL(`../migrations/${name}`,import.meta.url),'utf8');await db.batch(sql.split(';').map(v=>v.trim()).filter(Boolean).map(v=>db.prepare(v)))}return{db,vault:new D1ProviderCredentialVault(db,providerCredentialVaultV1KeyResolver(key)),states:new WorkIqOAuthStateStore(db)}}
async function add(states,vault,state,expiresAt,now,consume=false){const ref=await vault.create(`verifier-${state}`);await states.create({state,connectionKey:'work',repositoryRevision:'sha',tenantId:'tenant',clientId:'client',sessionId:'session',verifierSecretRef:ref,expiresAt});if(consume)await states.consume(state,'session',now);return ref}
const count=db=>db.prepare('SELECT COUNT(*) AS count FROM work_iq_oauth_states').first().then(row=>Number(row.count));
const unavailable=error=>error?.code==='vault_secret_unavailable';
function failStateDeleteDatabase(db){let failures=1;return{prepare(sql){const statement=db.prepare(sql),wrap=current=>({bind(...values){return wrap(current.bind(...values))},first:(...args)=>current.first(...args),all:(...args)=>current.all(...args),run:async()=>{if(failures&&sql.startsWith('DELETE FROM work_iq_oauth_states')){failures--;throw new Error('transient d1 delete')}return current.run()}});return wrap(statement)}}}

test('expired cleanup removes verifier first and retains a retryable row when vault deletion fails',async t=>{const{db,vault,states}=await fixture(t),now=1000,ref=await add(states,vault,'expired',now,now);let failures=1;const flaky={delete:async id=>{if(failures-- >0)throw new Error('transient vault delete');return vault.delete(id)}};await assert.rejects(states.cleanup(flaky,now),/transient vault delete/);assert.equal(await count(db),1);assert.equal(await vault.resolve(ref),'verifier-expired');assert.equal(await states.cleanup(vault,now),1);assert.equal(await count(db),0);await assert.rejects(vault.resolve(ref),unavailable)});

test('denial consumes replay authority but retains cleanup reference until verifier deletion succeeds',async t=>{const{db,vault,states}=await fixture(t),now=Date.now(),ref=await add(states,vault,'denied',now+WORK_IQ_OAUTH_TTL_MS*3,now);await assert.rejects(states.discard('denied','session',{delete:async()=>{throw new Error('vault unavailable')}}),/vault unavailable/);await assert.rejects(states.lookup('denied','session',now+1),/oauth_state_invalid/);const row=await db.prepare('SELECT consumed_at FROM work_iq_oauth_states').first();assert.ok(row.consumed_at);assert.equal(await vault.resolve(ref),'verifier-denied');assert.equal(await states.cleanup(vault,now+WORK_IQ_OAUTH_TTL_MS+1000),1);assert.equal(await count(db),0);await assert.rejects(vault.resolve(ref),unavailable)});

test('state deletion failure after secret deletion leaks no secret and later cleanup is idempotent',async t=>{const{db,vault,states}=await fixture(t),now=1000,ref=await add(states,vault,'d1-failure',now,now),flakyStates=new WorkIqOAuthStateStore(failStateDeleteDatabase(db));await assert.rejects(flakyStates.cleanup(vault,now),/transient d1 delete/);assert.equal(await count(db),1);await assert.rejects(vault.resolve(ref),unavailable);assert.equal(await states.cleanup(vault,now),1);assert.equal(await count(db),0)});

test('concurrent cleanup is idempotent and each pass remains bounded',async t=>{const{db,vault,states}=await fixture(t),now=1000;for(let index=0;index<WORK_IQ_OAUTH_CLEANUP_LIMIT+2;index++)await add(states,vault,`state-${index}`,now,now);const cleaned=await Promise.all([states.cleanup(vault,now),states.cleanup(vault,now)]);assert.ok(cleaned.every(value=>value<=WORK_IQ_OAUTH_CLEANUP_LIMIT));assert.ok(cleaned.reduce((a,b)=>a+b,0)<=WORK_IQ_OAUTH_CLEANUP_LIMIT+2);assert.ok(await count(db)<=2);await states.cleanup(vault,now);assert.equal(await count(db),0)});
