import test from 'node:test';
import assert from 'node:assert/strict';
import {connectionDefinitionPath,connectionDefinitionSchema,SECRET_BINDING} from '../lib/workflow-connection-definitions.ts';
import {createConnectionMigrationExport,suggestedProviderSecretRef,WorkflowProviderConnectionMigrationService} from '../lib/workflow-provider-connection-migration.ts';
import {createWorkflowProviderSecretResolver} from '../lib/workflow-provider-secret-resolver.ts';

const d1={key:'openai-primary',name:'Primary',adapter:'openai-responses',defaultModel:'gpt-sentinel'};
const sensitive=['browser-plaintext-sentinel','encrypted-sentinel','iv-sentinel'];
function git(overrides={}){const definition={schemaVersion:1,id:d1.key,name:d1.name,runtime:'openai-responses',provider:'openai',model:d1.defaultModel,credential:{secretRef:suggestedProviderSecretRef(d1.key)},...overrides};return{definition,fileSha:'reviewed-revision',sourcePath:connectionDefinitionPath(d1.key)}}
function fixture({row=d1,version=undefined,secret='provider-unit-sentinel',validate=async()=>{}}={}){let reads=0;const repository={listConnections:async()=>version?[version]:[],getConnection:async id=>version?.definition.id===id?version:undefined},store={getPersistedSafeDescriptor:async id=>{reads++;return row?.key===id?row:undefined}},secrets=createWorkflowProviderSecretResolver(ref=>ref===suggestedProviderSecretRef(d1.key)?secret:undefined);return{service:new WorkflowProviderConnectionMigrationService(repository,store,secrets,validate),get reads(){return reads},row}}

test('persisted D1 export is exact canonical Phase 5A JSON without credential state',()=>{const value=createConnectionMigrationExport({...d1,credential:sensitive[0],encrypted_credential:sensitive[1],credential_iv:sensitive[2]});assert.equal(value.targetPath,connectionDefinitionPath(d1.key));assert.deepEqual(connectionDefinitionSchema.parse(JSON.parse(value.canonicalJson)),value.definition);assert.equal(value.secretRef,'WORKFLOW_PROVIDER_CONNECTION_OPENAI_PRIMARY');assert.match(value.secretRef,SECRET_BINDING);for(const item of sensitive)assert.doesNotMatch(JSON.stringify(value),new RegExp(item));assert.deepEqual(Object.keys(value.definition),['schemaVersion','id','name','runtime','provider','model','credential'])});

test('secret references cover the canonical ID domain and remain dedicated and reversible',()=>{for(const id of ['openai-primary','team-7-review','7-review','a'.repeat(80)]){const ref=suggestedProviderSecretRef(id);assert.match(ref,SECRET_BINDING);assert.equal(ref.replace('WORKFLOW_PROVIDER_CONNECTION_','').toLowerCase().replaceAll('_','-'),id)}assert.equal(suggestedProviderSecretRef('openai-primary'),'WORKFLOW_PROVIDER_CONNECTION_OPENAI_PRIMARY');for(const ref of ['WORKFLOW_PROVIDER_CONNECTION_lowercase','FOREIGN_CONNECTION_OPENAI','OPENAI_PRIMARY'])assert.equal(SECRET_BINDING.test(ref),false)});

test('D1-only migration is preparable while a missing real row and reserved placeholder are not exports',async()=>{assert.equal((await fixture().service.inspect(d1.key)).state,'d1_only');await assert.rejects(fixture({row:null}).service.inspect(d1.key),/migration_source_not_found/);await assert.rejects(fixture({row:{...d1,key:'codex-primary'}}).service.inspect('codex-primary'),/reserved_connection_key/)});

test('Git readiness states fail closed and migration inspection never writes D1',async()=>{for(const scenario of [{secret:null,state:'git_secret_missing'},{secret:'bad-sentinel',validate:async()=>{throw new Error('authentication_failed')},state:'git_validation_failed'},{secret:'valid-sentinel',validate:async()=>{throw new Error('model_unavailable')},state:'git_validation_failed'},{secret:'valid-sentinel',validate:async()=>{throw new Error('provider_unavailable')},state:'temporarily_unavailable'}]){const f=fixture({...scenario,version:git()}),status=await f.service.inspect(d1.key);assert.equal(status.state,scenario.state);assert.equal(f.reads,1);assert.equal(f.row,d1);assert.equal('canRetire' in status,false)}});

test('semantic mismatch remains reviewable and non-destructive',async()=>{const f=fixture({version:git({model:'other-model'})}),status=await f.service.inspect(d1.key);assert.equal(status.state,'git_d1_mismatch');assert.equal(f.row,d1);assert.equal(f.reads,1)});

test('Git-ready migration deliberately retains the shadowed D1 row',async()=>{const f=fixture({version:git()}),status=await f.service.inspect(d1.key);assert.equal(status.state,'git_ready_shadowing_d1');assert.match(status.message,/intentionally retained|pre-migration run compatibility/);assert.equal(f.row,d1);assert.equal(f.reads,1);assert.equal('canRetire' in status,false)});
