import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {searchWorkflowAgentPrompts} from '../lib/workflow-agent-prompts.ts';
import {getOpenAIModelAgentCapabilities,validateOpenAIModelAgentOptions} from '../lib/openai-model-agent-capabilities.ts';
const source=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
test('Overview and Runs use the same accessible sortable run table',async()=>{const [overview,runs,table]=await Promise.all([source('app/workflows/page.tsx'),source('app/workflows/runs/page.tsx'),source('components/WorkflowRunsTable.tsx')]);assert.equal((overview.match(/WorkflowRunsTable/g)||[]).length>=3,true);assert.match(runs,/WorkflowRunsTable/);for(const heading of ['Workflow','Status','Started','Completed','Current step'])assert.ok(table.includes(`label:"${heading}"`));assert.match(table,/aria-sort=\{direction\}/);assert.match(table,/<button type="button"/);assert.match(table,/key:"startedAt",direction:"descending"/);assert.match(table,/startedAt\?\?item\.createdAt/);assert.match(table,/href=\{`\/workflows\/runs\/\$\{run\.id\}`\}/)});
test('new Agent guidance and prompt combobox retain labels and reference semantics',async()=>{const [editor,prompt]=await Promise.all([source('components/WorkflowAgentEditor.tsx'),source('components/WorkflowAgentPromptSelector.tsx')]);for(const value of ['e.g. Todo list planner','e.g. todo-list-planner','What this Agent is responsible for'])assert.ok(editor.includes(value));for(const value of ['role="combobox"','role="listbox"','role="option"','aria-expanded','aria-controls','aria-activedescendant','aria-labelledby','ArrowDown','ArrowUp','Enter','Escape','Custom Prompt','No matching prompts.','Artifact Library temporarily unavailable.','Copy this prompt','Referenced from Artifact Library','Changes to this prompt will be used by future runs.','Master prompt'])assert.ok(prompt.includes(value),value);assert.match(prompt,/setPrompt\(\{source:"artifact",artifactId:prompts\[i\]\.id\}\)/);assert.doesNotMatch(prompt,/type="hidden" name="masterPrompt"/)});
test('prompt catalogue filters type/status, orders production, bounds, and returns metadata only',()=>{const artifact=(id,type,status,title)=>({id,type,status,title,description:'',tags:[],aliases:[],body:`body ${id}`,excerpt:`excerpt ${id}`,path:`artifacts/${id}.md`});const results=searchWorkflowAgentPrompts([artifact('draft','prompt','draft','Draft'),artifact('prod','prompt','production','Production'),artifact('old','prompt','archived','Old'),artifact('template','template','production','Template'),artifact('agent','agent','draft','Agent'),artifact('snippet','snippet','draft','Snippet')],'');assert.deepEqual(results.map(x=>x.id),['prod','draft']);assert.equal('body' in results[0],false)});
test('OpenAI capabilities are exact and unknown models are conservative',()=>{assert.deepEqual(getOpenAIModelAgentCapabilities('unknown-model'),{});const known=getOpenAIModelAgentCapabilities('gpt-5.2');assert.deepEqual(known.reasoningEfforts,['none','low','medium','high','xhigh']);assert.equal(known.reasoningEfforts.includes('max'),false);assert.throws(()=>validateOpenAIModelAgentOptions('gpt-5',{reasoningEffort:'xhigh'}));assert.deepEqual(validateOpenAIModelAgentOptions('unknown-model',{}),{});assert.throws(()=>validateOpenAIModelAgentOptions('unknown-model',{verbosity:'high'}))});


test('archived references remain editable while copy validation is fail-safe',async()=>{const [edit,selector]=await Promise.all([source('app/workflows/agents/[agentId]/edit/page.tsx'),source('components/WorkflowAgentPromptSelector.tsx')]);assert.match(edit,/artifact&&artifact\.type==="prompt"\?/);assert.doesNotMatch(edit,/status!=="archived"/);for(const value of ['artifact.type!=="prompt"','text.length>AGENT_MASTER_PROMPT_MAX_LENGTH','The live reference is unchanged.'])assert.ok(selector.includes(value),value)});
