import assert from 'node:assert/strict';import test from 'node:test';import {assertWorkIqConfigurationMutable,createWorkIqPrivateBundle,parseWorkIqPrivateBundle,resolveWorkIqConnection,serializeWorkIqPrivateBundle,WORK_IQ_TOKEN_TIMEOUT_MS} from '../lib/work-iq-auth.ts';
const configuration={tenantId:'11111111-1111-4111-8111-111111111111',clientId:'22222222-2222-4222-8222-222222222222'},context='ctx_abcdefghijklmnopqrstuvwxyzABCDEFG1234567890_-',other='ctx_0123456789abcdefghijklmnopqrstuvwxyzABCDEFG_-';
const bundle=(ctx=context,refresh='old')=>serializeWorkIqPrivateBundle({version:1,kind:'work-iq-rest',clientSecret:'s',refreshToken:refresh,authorizationContextId:ctx});
const snapshot={key:'work',name:'Work',adapter:'work-iq-rest',endpoint:'https://workiq.svc.cloud.microsoft',providerConfiguration:configuration,authorizationContextId:context,enabled:true,management:'git',credentialSource:'adt-vault',credentialSecretRef:`sec_${'a'.repeat(43)}`,capabilities:{asynchronous:false,cancellation:false}};
test('private bundle parser is versioned, strict, and requires paired delegated state',()=>{assert.deepEqual(parseWorkIqPrivateBundle(createWorkIqPrivateBundle('secret')),{version:1,kind:'work-iq-rest',clientSecret:'secret'});for(const value of [{version:2,kind:'work-iq-rest',clientSecret:'x'},{version:1,kind:'work-iq-rest',clientSecret:'x',unknown:true},{version:1,kind:'work-iq-rest',clientSecret:'x',refreshToken:'r'}])assert.throws(()=>parseWorkIqPrivateBundle(JSON.stringify(value)))});
function raceVault(after,{cas=true}={}){let reads=0,writes=0;return{get writes(){return writes},resolveWithRevision:async()=>({value:reads++===0?bundle():after,revision:1}),replaceIfRevision:async()=>{writes++;return cas}}}
const token=(replacement)=>async()=>Response.json({token_type:'Bearer',access_token:'access',...(replacement!==undefined?{refresh_token:replacement}:{})});
test('refresh rotation uses CAS, preserves context, and never persists access tokens',async()=>{let stored=bundle(),revision=4;const vault={resolveWithRevision:async()=>({value:stored,revision}),replaceIfRevision:async(_r,expected,value)=>{assert.equal(expected,4);stored=value;revision++;return true}},resolved=await resolveWorkIqConnection('work',snapshot,vault,token('new'));assert.equal(resolved.credential,'access');assert.equal(parseWorkIqPrivateBundle(stored).refreshToken,'new');assert.doesNotMatch(stored,/access/) });
test('disconnect and reconnect during every refresh outcome fail before execution',async()=>{for(const replacement of [undefined,'new'])for(const current of [createWorkIqPrivateBundle('s'),bundle(other,'newer')]){const vault=raceVault(current);await assert.rejects(resolveWorkIqConnection('work',snapshot,vault,token(replacement)),e=>e.category==='connection_unavailable')}});
test('unchanged context succeeds without replacement and after stale CAS loss without a second redemption',async()=>{let calls=0;const noReplacement=raceVault(bundle(context,'winner'));assert.equal((await resolveWorkIqConnection('work',snapshot,noReplacement,async()=>{calls++;return token(undefined)()})).credential,'access');const lost=raceVault(bundle(context,'winner'),{cas:false});assert.equal((await resolveWorkIqConnection('work',snapshot,lost,async()=>{calls++;return token('new')()})).credential,'access');assert.equal(calls,2);assert.equal(lost.writes,1)});
test('token errors retain bounded categories and timeout never becomes provider-start ambiguity',async()=>{for(const [status,category] of [[400,'authentication_failed'],[403,'permission_denied'],[429,'rate_limited'],[503,'provider_unavailable']])await assert.rejects(resolveWorkIqConnection('work',snapshot,raceVault(bundle()),async()=>new Response('',{status})),e=>e.category===category);await assert.rejects(resolveWorkIqConnection('work',snapshot,raceVault(bundle()),async()=>new Promise(()=>{}),5),e=>e.category==='provider_timeout'&&e.category!=='provider_start_ambiguous');assert.equal(WORK_IQ_TOKEN_TIMEOUT_MS,15000)});

test('app identity mutation allows confirmed disconnect but rejects connected and unreadable bundles',async()=>{await assert.doesNotReject(assertWorkIqConfigurationMutable(snapshot.credentialSecretRef,{resolveWithRevision:async()=>({value:createWorkIqPrivateBundle('s'),revision:1})}));await assert.rejects(assertWorkIqConfigurationMutable(snapshot.credentialSecretRef,{resolveWithRevision:async()=>({value:bundle(),revision:1})}),/delegated_account_disconnect_required/);await assert.rejects(assertWorkIqConfigurationMutable(snapshot.credentialSecretRef,{resolveWithRevision:async()=>{throw new Error('vault down')}}),e=>e.category==='connection_unavailable')});
