"use client";
import Link from "next/link";
import { useState } from "react";
import type { Artifact } from "@/lib/artifact-repository";
import { lifecycleErrorMessage, safeArtifactHref, safeGitHubUrl, unknownEditErrorMessage } from "@/lib/edit-ui";
export function ArtifactDeleteButton({ artifact }: { artifact: Artifact }) {
  const [confirming, setConfirming] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [result, setResult] = useState<{ commitUrl?: string; pullUrl?: string; deletedId?: string }>();
  async function confirm() { if (busy || !confirming) return; setBusy(true); setMessage(""); try { const detail = await fetch(`/api/artifacts/${encodeURIComponent(artifact.id)}`, { cache: "no-store" }); const loaded = await detail.json().catch(() => undefined) as { currentFileSha?: string; artifact?: { status?: string } } | undefined; if (!detail.ok || !loaded?.currentFileSha || !loaded.artifact) { setMessage(unknownEditErrorMessage); return; } const proposal = loaded.artifact.status === "production"; const response = await fetch(proposal ? `/api/artifacts/${encodeURIComponent(artifact.id)}/deletion-proposal` : `/api/artifacts/${encodeURIComponent(artifact.id)}`, { method: proposal ? "POST" : "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentFileSha: loaded.currentFileSha }) }); const data = await response.json().catch(() => undefined) as { code?: string; artifactId?: string; commitUrl?: string; pullRequestUrl?: string } | undefined; if (!response.ok) { setMessage(lifecycleErrorMessage(data?.code)); return; } const commitUrl = safeGitHubUrl(data?.commitUrl, "commit"); const pullUrl = safeGitHubUrl(data?.pullRequestUrl, "pull"); if (proposal ? !pullUrl : !commitUrl || !safeArtifactHref(data?.artifactId)) { setMessage(unknownEditErrorMessage); return; } setResult(proposal ? { pullUrl } : { commitUrl, deletedId: data?.artifactId }); } catch { setMessage(unknownEditErrorMessage); } finally { setBusy(false); setConfirming(false); } }
  return <div className="mt-4 border-t pt-3"><button onClick={() => setConfirming(true)} className="text-sm font-semibold text-red-700">Delete</button>{confirming ? <div role="alertdialog" aria-modal="true" aria-label={`Delete ${artifact.title}`} className="mt-3 rounded-xl border border-red-300 p-3"><p className="text-sm">Delete <strong>{artifact.title}</strong> ({artifact.id})? {artifact.status === "production" ? "A reviewable deletion proposal will be created." : "This will commit a direct deletion."}</p><div className="mt-2 flex gap-2"><button autoFocus disabled={busy} onClick={() => setConfirming(false)} className="rounded-lg border px-3 py-1">Cancel</button><button disabled={busy} onClick={confirm} className="rounded-lg bg-red-700 px-3 py-1 text-white">Confirm</button></div></div> : null}{message ? <p className="mt-2 text-sm">{message}</p> : null}{result?.deletedId ? <p className="mt-2 text-sm">Deleted <strong>{result.deletedId}</strong>. <a href={result.commitUrl} className="underline">View commit</a> · <Link href="/" className="underline">Library</Link></p> : null}{result?.pullUrl ? <p className="mt-2 text-sm">Deletion proposed; the artifact remains live until merged. <a href={result.pullUrl} className="underline">View pull request</a></p> : null}</div>;
}
