"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import type { Artifact } from "@/lib/artifact-repository";
import { safeGitHubUrl, unknownEditErrorMessage } from "@/lib/edit-ui";

export function normalizeEditorValues(values: string[]) { return Array.from(new Set(values.map((value) => value.trim()).filter(Boolean))); }

function ValueList({ label, values, onChange }: { label: string; values: string[]; onChange: (values: string[]) => void }) {
  const [next, setNext] = useState("");
  return <fieldset className="mt-4"><legend className="text-sm font-semibold">{label}</legend><div className="mt-2 flex flex-wrap gap-2">{values.map((value) => <button type="button" key={value} onClick={() => onChange(values.filter((item) => item !== value))} className="rounded-full bg-slate-100 px-3 py-1 text-sm dark:bg-slate-800" aria-label={`Remove ${value}`}>{value} ×</button>)}</div><div className="mt-2 flex gap-2"><input value={next} onChange={(event) => setNext(event.target.value)} className="rounded-xl border p-2 dark:bg-slate-950" /><button type="button" className="rounded-xl border px-3" onClick={() => { onChange(normalizeEditorValues([...values, next])); setNext(""); }}>Add</button></div></fieldset>;
}

export function ArtifactEditor({ artifact, currentFileSha }: { artifact?: Artifact; currentFileSha?: string }) {
  const router = useRouter(); const creating = !artifact;
  const [title, setTitle] = useState(artifact?.title ?? ""); const [id, setId] = useState(artifact?.id ?? "");
  const [type, setType] = useState<Artifact["type"]>(artifact?.type ?? "prompt"); const [body, setBody] = useState(artifact?.body ?? "");
  const [tags, setTags] = useState(artifact?.tags ?? []); const [aliases, setAliases] = useState(artifact?.aliases ?? []);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [confirming, setConfirming] = useState(false);
  const metadata = { id, title, type, status: artifact?.status ?? "draft" as const, tags, aliases, ...(artifact?.sourceId ? { sourceId: artifact.sourceId } : {}), ...(artifact?.createdAt ? { createdAt: artifact.createdAt } : {}) };
  async function save() { if (busy) return; setBusy(true); setMessage(""); try { const production = artifact?.status === "production"; const endpoint = production ? `/api/artifacts/${encodeURIComponent(id)}/proposal` : creating ? "/api/artifacts" : `/api/artifacts/${encodeURIComponent(id)}`; const response = await fetch(endpoint, { method: creating || production ? "POST" : "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ metadata, body, ...(currentFileSha ? { currentFileSha } : {}) }) }); const data = await response.json().catch(() => undefined) as { code?: string; commitUrl?: string; pullRequestUrl?: string } | undefined; if (!response.ok) { setMessage(data?.code ?? unknownEditErrorMessage); return; } const url = safeGitHubUrl(data?.pullRequestUrl, "pull") ?? safeGitHubUrl(data?.commitUrl, "commit"); setMessage(url ? "Saved successfully in GitHub." : "Saved successfully."); if (creating) router.push(`/artifacts/${encodeURIComponent(id)}`); else router.refresh(); } catch { setMessage(unknownEditErrorMessage); } finally { setBusy(false); } }
  async function remove() { if (!confirming || busy || !artifact || !currentFileSha) return; setBusy(true); try { const proposal = artifact.status === "production"; const response = await fetch(proposal ? `/api/artifacts/${encodeURIComponent(id)}/deletion-proposal` : `/api/artifacts/${encodeURIComponent(id)}`, { method: proposal ? "POST" : "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentFileSha }) }); const data = await response.json().catch(() => undefined) as { code?: string; pullRequestUrl?: string } | undefined; if (!response.ok) { setMessage(data?.code ?? unknownEditErrorMessage); return; } if (proposal) setMessage("Deletion proposal created. The live artifact is unchanged."); else router.push("/"); } finally { setBusy(false); setConfirming(false); } }
  return <section className="rounded-3xl border bg-white p-6 shadow-soft dark:border-slate-800 dark:bg-slate-900"><h1 className="text-3xl font-black">{creating ? "Create artifact" : `Edit ${artifact.title}`}</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{artifact?.status === "production" ? "Saving creates a reviewable pull request; the live artifact remains unchanged." : "Changes are committed directly using the revision you loaded."}</p>
    <label className="mt-4 block text-sm font-semibold">Title<input value={title} onChange={(e) => { setTitle(e.target.value); if (creating && !id) setId(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 80)); }} className="mt-1 w-full rounded-xl border p-2 dark:bg-slate-950" /></label>
    <label className="mt-4 block text-sm font-semibold">Stable ID<input value={id} disabled={!creating} onChange={(e) => setId(e.target.value)} className="mt-1 w-full rounded-xl border p-2 disabled:opacity-60 dark:bg-slate-950" /></label>
    <label className="mt-4 block text-sm font-semibold">Type<select value={type} disabled={!creating} onChange={(e) => setType(e.target.value as Artifact["type"])} className="mt-1 w-full rounded-xl border p-2 dark:bg-slate-950">{["prompt","agent","snippet","template","app-idea"].map((value) => <option key={value}>{value}</option>)}</select></label>
    <ValueList label="Tags" values={tags} onChange={setTags} /><ValueList label="Aliases" values={aliases} onChange={setAliases} />
    <label className="mt-4 block text-sm font-semibold">Markdown body<textarea rows={16} value={body} onChange={(e) => setBody(e.target.value)} className="mt-1 w-full rounded-xl border p-3 font-mono text-sm dark:bg-slate-950" /></label>
    <div className="mt-5 flex flex-wrap gap-3"><button disabled={busy} onClick={save} className="rounded-xl bg-sky-700 px-5 py-2 font-semibold text-white">{busy ? "Working…" : artifact?.status === "production" ? "Create pull request" : "Save artifact"}</button>{artifact ? <button disabled={busy} onClick={() => setConfirming(true)} className="rounded-xl border border-red-500 px-5 py-2 font-semibold text-red-700">Delete</button> : null}</div>{message ? <p className="mt-4">{message}</p> : null}
    {confirming && artifact ? <div role="alertdialog" aria-modal="true" aria-labelledby="delete-title" className="mt-5 rounded-2xl border border-red-300 p-4"><h2 id="delete-title" className="font-bold">Delete {artifact.title} ({artifact.id})?</h2><p className="mt-2 text-sm">{artifact.status === "production" ? "This creates a production deletion proposal and leaves the live artifact unchanged." : "This directly deletes the artifact from the repository."}</p><div className="mt-3 flex gap-3"><button autoFocus disabled={busy} onClick={() => setConfirming(false)} className="rounded-xl border px-4 py-2">Cancel</button><button disabled={busy} onClick={remove} className="rounded-xl bg-red-700 px-4 py-2 text-white">Confirm deletion</button></div></div> : null}
  </section>;
}
