"use client";
import Link from "next/link";
import { useState } from "react";
import type { Artifact } from "@/lib/artifact-repository";
import { hasPreview, lifecycleErrorMessage, safeArtifactHref, safeGitHubUrl, unknownEditErrorMessage } from "@/lib/edit-ui";
import { canonicalEditorSnapshot, directDeletionCompleted, directWriteCompleted, editorDeletionSnapshot, editorRequestAllowed, editorValuesAreDirty, initialEditorLifecycle, normalizeEditorValues, suggestedArtifactId, validatedCanonicalEditorSnapshot, type CanonicalEditorSnapshot } from "@/lib/artifact-editor-helpers";
import { deletionConfirmation } from "@/lib/deletion-ui";

function ValueList({ label, values, onChange }: { label: string; values: string[]; onChange: (values: string[]) => void }) { const [next, setNext] = useState(""); return <fieldset className="mt-4"><legend className="text-sm font-semibold">{label}</legend><div className="mt-2 flex flex-wrap gap-2">{values.map((value) => <button type="button" key={value} onClick={() => onChange(values.filter((item) => item !== value))} className="rounded-full bg-slate-100 px-3 py-1 text-sm dark:bg-slate-800" aria-label={`Remove ${value}`}>{value} ×</button>)}</div><div className="mt-2 flex gap-2"><input value={next} onChange={(e) => setNext(e.target.value)} className="rounded-xl border p-2 dark:bg-slate-950" /><button type="button" className="rounded-xl border px-3" onClick={() => { onChange(normalizeEditorValues([...values, next])); setNext(""); }}>Add</button></div></fieldset>; }

type Result = { localHref?: string; commitUrl?: string; pullUrl?: string; deletedId?: string; recoveryUrl?: string; deletionProposal?: boolean };
export function ArtifactEditor({ artifact, currentFileSha }: { artifact?: Artifact; currentFileSha?: string }) {
  const creating = !artifact; const [title, setTitle] = useState(artifact?.title ?? ""); const [id, setId] = useState(artifact?.id ?? ""); const [manualId, setManualId] = useState(false); const [type, setType] = useState<Artifact["type"]>(artifact?.type ?? "prompt"); const [body, setBody] = useState(artifact?.body ?? ""); const [tags, setTags] = useState(artifact?.tags ?? []); const [aliases, setAliases] = useState(artifact?.aliases ?? []); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [confirming, setConfirming] = useState(false); const [preview, setPreview] = useState<unknown>(); const [result, setResult] = useState<Result>(); const [lifecycle, setLifecycle] = useState(() => initialEditorLifecycle(currentFileSha, artifact?.title)); const [persistedEditor, setPersistedEditor] = useState<CanonicalEditorSnapshot | undefined>(() => artifact ? canonicalEditorSnapshot(artifact) : undefined);
  const metadata = { id, title, type, status: artifact?.status ?? "draft" as const, tags, aliases, ...(artifact?.sourceId ? { sourceId: artifact.sourceId } : {}), ...(artifact?.createdAt ? { createdAt: artifact.createdAt } : {}) };
  const deletionSnapshot = artifact ? editorDeletionSnapshot(lifecycle, artifact) : undefined;
  const deletionCopy = deletionSnapshot ? deletionConfirmation(deletionSnapshot) : undefined;
  const hasUnsavedChanges = persistedEditor ? editorValuesAreDirty(canonicalEditorSnapshot({ title, tags, aliases, body }), persistedEditor) : false;
  async function operation(kind: "preview" | "save") { if (busy || !editorRequestAllowed(lifecycle, kind)) return; setBusy(true); setMessage(""); setResult(undefined); try { const production = artifact?.status === "production"; const endpoint = kind === "preview" ? creating ? "/api/artifacts/preview" : `/api/artifacts/${encodeURIComponent(id)}/preview` : production ? `/api/artifacts/${encodeURIComponent(id)}/proposal` : creating ? "/api/artifacts" : `/api/artifacts/${encodeURIComponent(id)}`; const response = await fetch(endpoint, { method: kind === "preview" || creating || production ? "POST" : "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ metadata, body, ...(lifecycle.activeFileSha ? { currentFileSha: lifecycle.activeFileSha } : {}) }) }); const data = await response.json().catch(() => undefined) as { code?: string; artifactId?: string; commitUrl?: string; pullRequestUrl?: string; branchUrl?: string; fileSha?: string; canonicalTitle?: string; canonicalEditor?: CanonicalEditorSnapshot } | undefined; if (!response.ok) { setPreview(undefined); setMessage(lifecycleErrorMessage(data?.code)); const recoveryUrl = safeGitHubUrl(data?.branchUrl, "branch"); if (recoveryUrl) setResult({ recoveryUrl }); return; } if (kind === "preview") { if (hasPreview(data)) setPreview(data); else setMessage(unknownEditErrorMessage); return; } const localHref = safeArtifactHref(data?.artifactId); const commitUrl = safeGitHubUrl(data?.commitUrl, "commit"); const pullUrl = safeGitHubUrl(data?.pullRequestUrl, "pull"); if (production ? !pullUrl : !localHref || !commitUrl) { setMessage(unknownEditErrorMessage); return; } if (!production) { const nextLifecycle = directWriteCompleted(lifecycle, data?.fileSha, data?.canonicalTitle, creating); if (!nextLifecycle) { setMessage(unknownEditErrorMessage); return; } const canonicalEditor = validatedCanonicalEditorSnapshot(data?.canonicalEditor); if (!canonicalEditor) { setMessage(unknownEditErrorMessage); return; } setLifecycle(nextLifecycle); setTitle(canonicalEditor.title); setTags(canonicalEditor.tags); setAliases(canonicalEditor.aliases); setBody(canonicalEditor.body); setPersistedEditor(canonicalEditor); } setPreview(undefined); setResult({ localHref, commitUrl, pullUrl }); } catch { setMessage(unknownEditErrorMessage); } finally { setBusy(false); } }
  async function remove() { setResult(undefined); if (!confirming || busy || !artifact || !deletionSnapshot || !editorRequestAllowed(lifecycle, "delete")) return; setBusy(true); setMessage(""); try { const proposal = artifact.status === "production"; const response = await fetch(proposal ? `/api/artifacts/${encodeURIComponent(deletionSnapshot.id)}/deletion-proposal` : `/api/artifacts/${encodeURIComponent(deletionSnapshot.id)}`, { method: proposal ? "POST" : "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentFileSha: deletionSnapshot.currentFileSha }) }); const data = await response.json().catch(() => undefined) as { code?: string; artifactId?: string; commitUrl?: string; pullRequestUrl?: string; branchUrl?: string } | undefined; if (!response.ok) { setPreview(undefined); setMessage(lifecycleErrorMessage(data?.code)); const recoveryUrl = safeGitHubUrl(data?.branchUrl, "branch"); if (recoveryUrl) setResult({ recoveryUrl }); return; } const commitUrl = safeGitHubUrl(data?.commitUrl, "commit"); const pullUrl = safeGitHubUrl(data?.pullRequestUrl, "pull"); if (proposal ? !pullUrl : !commitUrl || !safeArtifactHref(data?.artifactId)) { setMessage(unknownEditErrorMessage); return; } setResult(proposal ? { pullUrl, deletionProposal: true } : { deletedId: data?.artifactId, commitUrl }); if (!proposal) setLifecycle((current) => directDeletionCompleted(current)); } catch { setMessage(unknownEditErrorMessage); } finally { setBusy(false); setConfirming(false); } }
  return <section className="rounded-3xl border bg-white p-6 shadow-soft dark:border-slate-800 dark:bg-slate-900"><h1 className="text-3xl font-black">{creating ? "Create artifact" : `Edit ${title || artifact.title}`}</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{artifact?.status === "production" ? "Saving creates a reviewable pull request; the live artifact remains unchanged." : "Changes use the exact revision you loaded."}</p>
    {!lifecycle.completedCreation && !lifecycle.deleted ? <><label className="mt-4 block text-sm font-semibold">Title<input value={title} onChange={(e) => { setTitle(e.target.value); setPreview(undefined); setResult(undefined); if (creating) setId(suggestedArtifactId(e.target.value, manualId, id)); }} className="mt-1 w-full rounded-xl border p-2 dark:bg-slate-950" /></label>
    {creating ? <><label className="mt-4 block text-sm font-semibold">Stable ID<input value={id} onChange={(e) => { setManualId(true); setId(e.target.value); setPreview(undefined); setResult(undefined); }} className="mt-1 w-full rounded-xl border p-2 dark:bg-slate-950" /></label><label className="mt-4 block text-sm font-semibold">Type<select value={type} onChange={(e) => { setType(e.target.value as Artifact["type"]); setPreview(undefined); setResult(undefined); }} className="mt-1 w-full rounded-xl border p-2 dark:bg-slate-950">{["prompt","agent","snippet","template","app-idea"].map((value) => <option key={value}>{value}</option>)}</select></label></> : <dl className="mt-4 grid gap-2 rounded-xl bg-slate-50 p-4 text-sm dark:bg-slate-950"><div><dt className="font-semibold">ID</dt><dd>{artifact.id}</dd></div><div><dt className="font-semibold">Type</dt><dd>{artifact.type}</dd></div><div><dt className="font-semibold">Status</dt><dd>{artifact.status}</dd></div>{artifact.sourceId ? <div><dt className="font-semibold">Source artifact</dt><dd>{artifact.sourceId}</dd></div> : null}{artifact.createdAt ? <div><dt className="font-semibold">Created</dt><dd>{String(artifact.createdAt)}</dd></div> : null}</dl>}
    <ValueList label="Tags" values={tags} onChange={(values) => { setTags(values); setPreview(undefined); setResult(undefined); }} /><ValueList label="Aliases" values={aliases} onChange={(values) => { setAliases(values); setPreview(undefined); setResult(undefined); }} /><label className="mt-4 block text-sm font-semibold">Markdown body<textarea rows={16} value={body} onChange={(e) => { setBody(e.target.value); setPreview(undefined); setResult(undefined); }} className="mt-1 w-full rounded-xl border p-3 font-mono text-sm dark:bg-slate-950" /></label>
    <div className="mt-5 flex flex-wrap gap-3"><button disabled={busy} onClick={() => operation("preview")} className="rounded-xl border px-5 py-2 font-semibold">Preview</button><button disabled={busy} onClick={() => operation("save")} className="rounded-xl bg-sky-700 px-5 py-2 font-semibold text-white">{busy ? "Working…" : artifact?.status === "production" ? "Create pull request" : "Save artifact"}</button>{artifact ? <button disabled={busy} onClick={() => setConfirming(true)} className="rounded-xl border border-red-500 px-5 py-2 font-semibold text-red-700">Delete</button> : null}</div></> : null}{message ? <p className="mt-4">{message}</p> : null}
    {result ? <div className="mt-4 rounded-xl bg-emerald-50 p-4 text-emerald-950">{result.deletedId ? <p>Deleted artifact <strong>{result.deletedId}</strong>. <a href={result.commitUrl} target="_blank" rel="noreferrer" className="underline">View commit</a> · <Link href="/" className="underline">Back to library</Link></p> : result.pullUrl ? <p>Proposal created. {result.deletionProposal ? "The artifact remains live until the proposal is merged." : "The live artifact remains unchanged."} <a href={result.pullUrl} target="_blank" rel="noreferrer" className="underline">View pull request</a></p> : result.localHref ? <p>Saved. <Link href={result.localHref} className="underline">View artifact</Link> · <a href={result.commitUrl} target="_blank" rel="noreferrer" className="underline">View commit</a></p> : null}{result.recoveryUrl ? <a href={result.recoveryUrl} className="underline">View recovery branch</a> : null}</div> : null}
    {hasPreview(preview) ? <article className="mt-5 rounded-xl border p-4"><h2 className="text-2xl font-bold">{preview.metadata.title}</h2><p>ID: {preview.metadata.id} · Type: {preview.metadata.type} · Status: {preview.metadata.status}</p><p>Tags: {preview.metadata.tags.join(", ") || "None"} · Aliases: {preview.metadata.aliases.join(", ") || "None"}</p>{artifact?.sourceId ? <p>Source: {artifact.sourceId}</p> : null}{artifact?.createdAt ? <p>Created: {String(artifact.createdAt)}</p> : null}<div className="mt-3" dangerouslySetInnerHTML={{ __html: preview.bodyHtml }} /></article> : null}
    {confirming && artifact && deletionCopy ? <div role="alertdialog" aria-modal="true" aria-labelledby="delete-title" className="mt-5 rounded-2xl border border-red-300 p-4"><h2 id="delete-title" className="font-bold">{deletionCopy.heading}</h2><p className="mt-2 text-sm">{deletionCopy.description}</p>{hasUnsavedChanges ? <p className="mt-2 text-sm font-semibold">Unsaved edits are not included. This action applies to the currently saved artifact.</p> : null}<div className="mt-3 flex gap-3"><button autoFocus disabled={busy} onClick={() => setConfirming(false)} className="rounded-xl border px-4 py-2">Cancel</button><button disabled={busy} onClick={remove} className="rounded-xl bg-red-700 px-4 py-2 text-white">Confirm deletion</button></div></div> : null}
  </section>;
}
