"use client";
import { useState } from "react";
import type { Artifact } from "@/lib/artifact-repository";

export function ArtifactDeleteButton({ artifact }: { artifact: Artifact }) {
  const [confirming, setConfirming] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function confirm() { if (busy) return; setBusy(true); try { const detail = await fetch(`/api/artifacts/${encodeURIComponent(artifact.id)}`, { cache: "no-store" }); const loaded = await detail.json() as { currentFileSha?: string }; if (!detail.ok || !loaded.currentFileSha) throw new Error(); const proposal = artifact.status === "production"; const response = await fetch(proposal ? `/api/artifacts/${encodeURIComponent(artifact.id)}/deletion-proposal` : `/api/artifacts/${encodeURIComponent(artifact.id)}`, { method: proposal ? "POST" : "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentFileSha: loaded.currentFileSha }) }); if (!response.ok) throw new Error(); if (proposal) setMessage("Deletion proposal created; the live artifact remains available."); else window.location.reload(); } catch { setMessage("The artifact could not be deleted. Reload and try again."); } finally { setBusy(false); setConfirming(false); } }
  return <div className="mt-4 border-t pt-3"><button onClick={() => setConfirming(true)} className="text-sm font-semibold text-red-700">Delete</button>{confirming ? <div role="alertdialog" aria-modal="true" aria-label={`Delete ${artifact.title}`} className="mt-3 rounded-xl border border-red-300 p-3"><p className="text-sm">Delete <strong>{artifact.title}</strong> ({artifact.id})? {artifact.status === "production" ? "A reviewable deletion proposal will be created." : "This will commit a direct deletion."}</p><div className="mt-2 flex gap-2"><button autoFocus disabled={busy} onClick={() => setConfirming(false)} className="rounded-lg border px-3 py-1">Cancel</button><button disabled={busy} onClick={confirm} className="rounded-lg bg-red-700 px-3 py-1 text-white">Confirm</button></div></div> : null}{message ? <p className="mt-2 text-sm">{message}</p> : null}</div>;
}
