"use client";
import { useState } from "react";
import type { Artifact } from "@/lib/artifact-repository";
import { deletionRequest, type DeletionResult, type DeletionSnapshot } from "@/lib/deletion-ui";
import { lifecycleErrorMessage, safeArtifactHref, safeGitHubUrl, unknownEditErrorMessage } from "@/lib/edit-ui";
export function ArtifactDeleteButton({ artifact, onResult, onStart }: { artifact: Artifact; onResult: (result: DeletionResult) => void; onStart: () => void }) {
  const [snapshot, setSnapshot] = useState<DeletionSnapshot>(); const [loading, setLoading] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function begin() { if (loading || busy) return; onStart(); setLoading(true); setMessage(""); try { const response = await fetch(`/api/artifacts/${encodeURIComponent(artifact.id)}`, { cache: "no-store" }); const data = await response.json().catch(() => undefined) as { currentFileSha?: string; artifact?: Artifact } | undefined; if (!response.ok || !data?.currentFileSha || !data.artifact || data.artifact.id !== artifact.id) { setMessage(unknownEditErrorMessage); return; } setSnapshot({ id: data.artifact.id, title: data.artifact.title, status: data.artifact.status, currentFileSha: data.currentFileSha }); } catch { setMessage(unknownEditErrorMessage); } finally { setLoading(false); } }
  async function confirm() { if (busy || !snapshot) return; setBusy(true); setMessage(""); try { const operation = deletionRequest(snapshot); const response = await fetch(operation.endpoint, { method: operation.method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(operation.body) }); const data = await response.json().catch(() => undefined) as { code?: string; artifactId?: string; commitUrl?: string; pullRequestUrl?: string } | undefined; if (!response.ok) { setMessage(lifecycleErrorMessage(data?.code)); return; } const commitUrl = safeGitHubUrl(data?.commitUrl, "commit"); const pullUrl = safeGitHubUrl(data?.pullRequestUrl, "pull"); if (snapshot.status === "production") { if (!pullUrl || data?.artifactId !== snapshot.id) { setMessage(unknownEditErrorMessage); return; } onResult({ kind: "proposal", artifactId: snapshot.id, pullUrl }); } else { if (!commitUrl || !safeArtifactHref(data?.artifactId) || data?.artifactId !== snapshot.id) { setMessage(unknownEditErrorMessage); return; } onResult({ kind: "deleted", artifactId: snapshot.id, commitUrl }); } setSnapshot(undefined); } catch { setMessage(unknownEditErrorMessage); } finally { setBusy(false); } }
  return <div className="mt-4 border-t pt-3"><button disabled={loading || busy} onClick={begin} className="text-sm font-semibold text-red-700">{loading ? "Loading deletion details…" : "Delete"}</button>{snapshot ? <div role="alertdialog" aria-modal="true" aria-label={`Delete ${snapshot.title}`} className="mt-3 rounded-xl border border-red-300 p-3"><p className="text-sm">Delete <strong>{snapshot.title}</strong> ({snapshot.id})? {snapshot.status === "production" ? "Confirmation creates a reviewable deletion pull request and leaves the artifact live." : "Confirmation directly deletes this artifact from the repository."}</p><div className="mt-2 flex gap-2"><button autoFocus disabled={busy} onClick={() => setSnapshot(undefined)} className="rounded-lg border px-3 py-1">Cancel</button><button disabled={busy} onClick={confirm} className="rounded-lg bg-red-700 px-3 py-1 text-white">Confirm</button></div></div> : null}{message ? <p className="mt-2 text-sm">{message}</p> : null}</div>;
}
