"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import {LocalizedTime} from "./LocalizedTime";
import {PendingButtonContent} from "./PendingButtonContent";
import {buttonStyles} from "./Ui";
import type {RunnerEnvironmentDescriptor,RunnerJobList,RunnerJobSummary,RunnerWorkspaceDiagnostics,RunnerSandboxDiagnostics,RunnerControlStatus,RunnerSqliteStorage} from "@/lib/codex-runner-client";
import type {SafeCodexConnectionStatus} from "@/lib/codex-runner-status";
import {EXPECTED_RUNNER_RELEASE} from "@/lib/codex-runner-release";
import {evaluateRunnerCompatibility,shortBuildRevision} from "@/lib/codex-runner-compatibility";

export type OperationalLoadState=
 | {status:"not-requested"}
 | {status:"loading"}
 | {status:"loaded";data:RunnerJobList;confirmedAt:string}
 | {status:"unavailable";previous?:RunnerJobList;confirmedAt?:string};
export function operationalRefreshScope(kind:"manual"|"poll"){return kind==="manual"?["jobs","diagnostics","control"] as const:["jobs"] as const}

const activeStates=new Set(["queued","running","cancelling"]);
const labels={queued:"Starting",running:"Running",cancelling:"Cancelling",completed:"Completed",failed:"Failed",cancelled:"Cancelled"} as const;

function JobCard({job,current=false,matching=false}:{job:RunnerJobSummary;current?:boolean;matching?:boolean}){
 return <article className={`adt-panel ${(current||matching)?"border-sky-600 bg-sky-50 dark:border-orange-400 dark:bg-slate-900":""}`}>
  <div className="flex flex-wrap items-center justify-between gap-2"><code className="break-all text-sm">{job.jobId}</code><span className="rounded-full border px-2 py-1 text-sm font-semibold">{labels[job.state]}</span></div>
  {matching&&<p className="mt-2 font-bold">Matches this Workflow attempt</p>}
  <dl className="mt-3 grid grid-cols-1 gap-1 text-sm sm:grid-cols-[auto_1fr] sm:gap-x-4"><dt>Environment</dt><dd><code>{job.environmentKey}</code></dd><dt>Created</dt><dd><LocalizedTime value={job.createdAt}/></dd><dt>Last updated</dt><dd><LocalizedTime value={job.updatedAt}/></dd>{job.reason&&<><dt>Safe failure reason</dt><dd>{job.reason.replaceAll("_"," ")}</dd></>}</dl>
 </article>
}

export function CodexRunnerOperationalView({state,expectedDigest}:{state:OperationalLoadState;expectedDigest?:string}){
 if(state.status==="not-requested")return <p className="mt-4 text-sm text-slate-600 dark:text-slate-300">Recent work has not been queried.</p>;
 if(state.status==="loading")return <p role="status" className="mt-6 adt-panel">Checking current Runner work…</p>;
 const data=state.status==="loaded"?state.data:state.previous;
 if(!data)return <p role="alert" className="mt-6 rounded border border-red-600 p-3">Runner operational status is unavailable. Current Runner job state is unknown. Do not infer that retry is safe.</p>;
 const stale=state.status==="unavailable",active=data.capacity.activeJobId?data.jobs.find(job=>job.jobId===data.capacity.activeJobId):undefined,recent=data.jobs.filter(job=>!activeStates.has(job.state)),match=expectedDigest?data.jobs.find(job=>job.idempotencyDigest===expectedDigest):undefined;
 return <>
  {stale&&<p role="alert" className="mt-6 rounded border border-amber-600 p-3"><strong>Current Runner state is unknown.</strong> The information below is stale and was last confirmed {state.confirmedAt?<LocalizedTime value={state.confirmedAt}/>:"at an unknown time"}. Do not infer that retry is safe.</p>}
  {expectedDigest&&!match&&<p className="mt-4 rounded border p-3">No matching Runner record was found in the available history. This does not establish that retry is safe.</p>}
  <div aria-label={stale?"Stale Runner operational information":"Current Runner operational information"}>
   <section className="mt-6"><h2 className="text-xl font-bold">Current work</h2><div className="mt-3">{active?<JobCard job={active} current matching={active===match}/>:<p className="adt-panel">{stale?"Last confirmed state had no admitted Workflow job.":"Runner is idle. There is no admitted Workflow job."}</p>}</div></section>
   <section className="mt-6"><h2 className="text-xl font-bold">Recent jobs</h2><div className="mt-3 grid gap-3">{recent.length?recent.map(job=><JobCard job={job} matching={job===match} key={job.jobId}/>):<p className="adt-panel">{stale?"No terminal jobs were present in the last confirmed history.":"No terminal jobs are available in the current Runner history."}</p>}</div></section>
  </div>
 </>
}


type SandboxDiagnosticState={state:"available";value:RunnerSandboxDiagnostics}|{state:"unsupported"}|{state:"unavailable"};
type WorkspaceItem={environment:RunnerEnvironmentDescriptor;diagnostics:RunnerWorkspaceDiagnostics|null;sandboxDiagnostic:SandboxDiagnosticState};
const sandboxReasonLabels:Record<RunnerSandboxDiagnostics["reason"],string>={ok:"OK",read_only_not_supported:"Read-only fails closed in container-boundary mode",execution_probe_failed:"Container execution probe failed",sandbox_helper_unavailable:"Sandbox helper unavailable",user_namespace_unavailable:"User namespace unavailable",uid_mapping_denied:"UID mapping denied",pid_namespace_unavailable:"PID namespace unavailable",network_namespace_unavailable:"Network namespace unavailable",loopback_configuration_denied:"Loopback configuration denied",proc_unavailable:"/proc prerequisite unavailable",permission_denied:"Permission denied",sandbox_initialization_failed:"Sandbox initialization failed",timeout:"Diagnostic timeout",unknown:"Unknown failure"};
export function WorkspaceSection({items}:{items:WorkspaceItem[]|null}){return <section className="mt-6 adt-panel"><h2 className="text-xl font-bold">Workspace</h2>{items===null?<p className="mt-3">Workspace diagnostics require a newer Runner.</p>:<div className="mt-3 grid gap-4">{items.map(({environment,diagnostics,sandboxDiagnostic})=><article key={environment.key}><h3 className="font-bold">{environment.name}</h3>{diagnostics?<><dl className="grid grid-cols-[auto_1fr] gap-x-4 text-sm"><dt>Filesystem</dt><dd>{diagnostics.filesystemReady?"Ready":"Unavailable"}</dd><dt>Git</dt><dd>{diagnostics.gitAvailable?"Available":"Unavailable"}</dd><dt>Repository</dt><dd>{diagnostics.gitRepository?"Yes":"Not a Git checkout"}</dd><dt>HEAD</dt><dd>{diagnostics.headCommit?<code>{diagnostics.headCommit.slice(0,8)}…</code>:"Unavailable"}</dd><dt>Working tree</dt><dd>{diagnostics.dirty===true?"Modified":diagnostics.dirty===false?"Clean":"State unavailable"}</dd></dl>{!diagnostics.gitAvailable?<p className="mt-2 text-sm">Git is unavailable in this Runner.</p>:!diagnostics.gitRepository?<p className="mt-2 text-sm">The workspace is available but is not currently a Git checkout. Codex can edit files, but repository-aware operations are unavailable.</p>:null}</>:<p className="mt-2 text-sm">Workspace diagnostics require a newer Runner.</p>}<div className="mt-3 border-t pt-3">{sandboxDiagnostic.state==="available"?<dl className="grid grid-cols-[auto_1fr] gap-x-4 text-sm"><dt>Local execution sandbox</dt><dd>{sandboxDiagnostic.value.status==="available"?"Available":sandboxDiagnostic.value.status==="unavailable"?"Unavailable":"Unknown"}</dd><dt>Backend</dt><dd>{sandboxDiagnostic.value.backend==="bubblewrap"?"Bubblewrap":sandboxDiagnostic.value.backend==="container"?"Docker container boundary":"Unknown"}</dd><dt>Reason</dt><dd>{sandboxReasonLabels[sandboxDiagnostic.value.reason]}</dd></dl>:<p className="text-sm">{sandboxDiagnostic.state==="unsupported"?"Local execution sandbox diagnostics require a newer Runner.":"Local execution sandbox diagnostics are currently unavailable."}</p>}</div></article>)}</div>}</section>}
export function CodexRunnerOperationalStatus({connection,expectedDigest,initialControl}:{connection:SafeCodexConnectionStatus;expectedDigest?:string;initialControl?:RunnerControlStatus}){
 const[state,setState]=useState<OperationalLoadState>({status:"not-requested"}),[workspaces,setWorkspaces]=useState<WorkspaceItem[]|undefined>(),[control,setControl]=useState<RunnerControlStatus|undefined>(initialControl),[controlError,setControlError]=useState(false),[detailsPending,setDetailsPending]=useState(false),[jobsPending,setJobsPending]=useState(false),[controlPending,setControlPending]=useState(false),jobsInFlight=useRef(false),[storage,setStorage]=useState<RunnerSqliteStorage>(),[storagePending,setStoragePending]=useState(false),[storageMessage,setStorageMessage]=useState<string>(),[selectedBackup,setSelectedBackup]=useState("");
 const refreshJobs=useCallback(async()=>{if(jobsInFlight.current)return;jobsInFlight.current=true;setJobsPending(true);setState(current=>current.status==="loaded"?current:{status:"loading"});try{const response=await fetch("/api/workflow-connections/codex-runner/jobs",{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json() as RunnerJobList;setState({status:"loaded",data,confirmedAt:new Date().toISOString()})}catch{setState(current=>({status:"unavailable",...(current.status==="loaded"?{previous:current.data,confirmedAt:current.confirmedAt}:current.status==="unavailable"&&current.previous?{previous:current.previous,confirmedAt:current.confirmedAt}:{})}))}finally{jobsInFlight.current=false;setJobsPending(false)}},[]);
 async function queryDetails(){setDetailsPending(true);setControlError(false);try{const [workspaceResponse,controlResponse]=await Promise.all([fetch("/api/workflow-connections/codex-runner/workspaces",{cache:"no-store"}),fetch("/api/workflow-connections/codex-runner/control",{cache:"no-store"})]);if(!workspaceResponse.ok||!controlResponse.ok)throw new Error();setWorkspaces((await workspaceResponse.json() as {workspaces:WorkspaceItem[]}).workspaces);setControl(await controlResponse.json())}catch{setControlError(true)}finally{setDetailsPending(false)}}
 async function queryStorage(){setStoragePending(true);setStorageMessage(undefined);try{const response=await fetch("/api/workflow-connections/codex-runner/sqlite-storage",{cache:"no-store"});if(!response.ok)throw new Error();const next=await response.json() as RunnerSqliteStorage;setStorage(next);setSelectedBackup(current=>next.backups.some(item=>item.backupId===current)?current:next.backups[0]?.backupId??"")}catch{setStorageMessage("Storage status is unavailable.")}finally{setStoragePending(false)}}
 const controlAction=async(action:"emergency-stop"|"resume")=>{if(action==="emergency-stop"&&!confirm("Emergency stop the Runner and request an executor restart?"))return;setControlPending(true);setControlError(false);try{const response=await fetch("/api/workflow-connections/codex-runner/control",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action})});if(!response.ok)throw new Error();setControl(await response.json());await refreshJobs()}catch{setControlError(true)}finally{setControlPending(false)}};
 const storageAction=async(action:"backup"|"restore")=>{const backupId=selectedBackup;if(action==="restore"&&(!backupId||!confirm("Restore this SQLite backup? Current SQLite state will be replaced and Runner execution will temporarily pause. Durable non-SQLite Codex home and session data will not be replaced. A pre-restore safety snapshot will be attempted.")))return;setStoragePending(true);setStorageMessage(undefined);try{const response=await fetch("/api/workflow-connections/codex-runner/sqlite-storage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(action==="backup"?{action}:{action,backupId})});if(!response.ok){const failure=await response.json().catch(()=>({})) as {error?:string};throw new Error(typeof failure.error==="string"?failure.error:"runner_storage_operation_failed")}setStorageMessage(action==="backup"?"Backup completed.":"Restore completed and App Server is ready.");await queryStorage()}catch(error){const code=error instanceof Error?error.message:"runner_storage_operation_failed",messages:Record<string,string>={runner_busy:"Runner work or maintenance is active. Wait for it to finish, then query storage again.",backup_not_found:"That completed backup is no longer available. Query storage again before another action.",invalid_backup:"The selected backup failed integrity validation and was not restored.",sqlite_backup_failed:"Backup failed safely; previous completed backups were preserved.",sqlite_backup_insufficient_space:"Local SQLite storage has insufficient free space for a consistent backup snapshot.",app_server_shutdown_unconfirmed:"SQLite was not modified, but App Server termination could not be confirmed. The Runner remains fail-closed; restart or redeploy the executor before resuming work.",restore_failed_rolled_back:"Restore failed readiness and the pre-restore SQLite state was restored. Query storage before retrying.",restore_rollback_failed:"Restore rollback could not be completed. The Runner remains in maintenance; preserve local recovery state and contact an operator.",storage_operation_result_unknown:"The operation result is unknown because its response was lost. Query storage status before taking another action.",sqlite_home_not_configured:"Configure a separate local CODEX_SQLITE_HOME before using recovery operations."};setStorageMessage(messages[code]??(action==="backup"?"Backup failed safely; completed backups were preserved.":"Restore failed safely; query storage before another action."))}finally{setStoragePending(false)}};
 const known=state.status==="loaded"?state.data:state.status==="unavailable"?state.previous:undefined,shouldPoll=Boolean(known?.capacity.activeJobId),compatibility=evaluateRunnerCompatibility(connection.capabilities),statusLabel=(value:string)=>value.replaceAll("_"," ").replace(/^./,c=>c.toUpperCase());
 useEffect(()=>{if(!shouldPoll)return;const timer=setInterval(()=>void refreshJobs(),4000);return()=>clearInterval(timer)},[shouldPoll,refreshJobs]);
 useEffect(()=>{if(!expectedDigest||state.status!=="not-requested")return;const timer=setTimeout(()=>void refreshJobs(),0);return()=>clearTimeout(timer)},[expectedDigest,state.status,refreshJobs]);
 return <div>
  <div className="mt-4 flex flex-wrap gap-2"><button className={buttonStyles.secondary} onClick={()=>void queryDetails()} disabled={detailsPending} aria-busy={detailsPending}><PendingButtonContent pending={detailsPending}>{detailsPending?"Querying…":"Query operational details"}</PendingButtonContent></button><button className={buttonStyles.secondary} onClick={()=>void refreshJobs()} disabled={jobsPending} aria-busy={jobsPending}><PendingButtonContent pending={jobsPending}>{jobsPending?"Loading…":"Load recent jobs"}</PendingButtonContent></button><button className={buttonStyles.secondary} onClick={()=>void queryStorage()} disabled={storagePending} aria-busy={storagePending}><PendingButtonContent pending={storagePending}>{storagePending?"Querying…":"Query storage & recovery"}</PendingButtonContent></button></div>
  {control&&<section className={`mt-4 rounded border p-4 ${control.emergencyStopped?"border-red-600 bg-red-50 dark:bg-slate-950":""}`}><h3 className="font-bold">Execution controls</h3><p className="mt-2"><b>Emergency stop:</b> {control.emergencyStopped?"ACTIVE":"Clear"} · <b>Executor:</b> {control.executor?(control.executor.healthy?"Healthy":"Unavailable"):"Integrated mode"}</p><div className="mt-3 flex flex-wrap gap-2"><button className={buttonStyles.danger} disabled={controlPending||control.emergencyStopped} aria-busy={controlPending} onClick={()=>void controlAction("emergency-stop")}><PendingButtonContent pending={controlPending}>{controlPending?"Stopping…":"Emergency Stop Runner"}</PendingButtonContent></button><button className={buttonStyles.secondary} disabled={controlPending||!control.emergencyStopped} aria-busy={controlPending} onClick={()=>void controlAction("resume")}><PendingButtonContent pending={controlPending}>{controlPending?"Resuming…":"Resume Runner"}</PendingButtonContent></button></div></section>}
  {controlError&&<p role="alert" className="mt-3 rounded border border-red-600 p-3">Optional Runner operational detail is unavailable. Previously observed essential status is unchanged.</p>}
  <details className="mt-4 adt-panel"><summary className="cursor-pointer font-bold">Compatibility & build details</summary>{connection.capabilities?<dl className="mt-3 grid grid-cols-1 gap-1 text-sm sm:grid-cols-[auto_1fr]"><dt>Protocol</dt><dd>{connection.capabilities.protocolVersion} · {statusLabel(compatibility.protocol)}</dd><dt>Runner release</dt><dd>{connection.capabilities.releaseMetadata==="legacy"?"Unknown (legacy evidence)":`${connection.capabilities.runnerRevision} · ${statusLabel(compatibility.runnerRevision)}`}</dd><dt>Expected release</dt><dd>{EXPECTED_RUNNER_RELEASE.runnerRevision}</dd><dt>Codex CLI</dt><dd>{connection.capabilities.releaseMetadata==="current"?connection.capabilities.codexVersion:"Unknown (legacy evidence)"} · {statusLabel(compatibility.codexVersion)}</dd><dt>Build identity</dt><dd><code className="break-all">{shortBuildRevision(connection.capabilities.runnerVersion)}</code></dd></dl>:<p className="mt-2">Compatibility/version status unknown.</p>}</details>
  {workspaces!==undefined&&<WorkspaceSection items={workspaces}/>}
  {storage&&<section className="mt-6 adt-panel"><h3 className="font-bold">Storage & recovery maintenance</h3><p className="mt-2 text-sm">Separate SQLite home: {storage.status.separateSqliteHomeConfigured?"Configured":"Not configured"} · Filesystem: {statusLabel(storage.status.sqliteFilesystemClass)} · Writable: {storage.status.sqliteHomeWritable?"Yes":"No"}</p><label className="mt-3 block text-sm font-bold">Completed backup<select className="adt-field mt-1 max-w-sm" value={selectedBackup} disabled={!storage.backups.length||storagePending} onChange={event=>setSelectedBackup(event.target.value)}>{storage.backups.length?storage.backups.map(backup=><option key={backup.backupId} value={backup.backupId}>{backup.createdAt}</option>):<option value="">No completed backups</option>}</select></label><div className="mt-3 flex flex-wrap gap-2"><button className={buttonStyles.secondary} disabled={storagePending||storage.status.operation!=="idle"} aria-busy={storagePending} onClick={()=>void storageAction("backup")}><PendingButtonContent pending={storagePending}>{storagePending?"Backing up…":"Back up now"}</PendingButtonContent></button><button className={buttonStyles.danger} disabled={storagePending||!storage.backups.length||storage.status.operation!=="idle"} aria-busy={storagePending} onClick={()=>void storageAction("restore")}><PendingButtonContent pending={storagePending}>{storagePending?"Restoring…":"Restore backup"}</PendingButtonContent></button></div></section>}
  {storageMessage&&<p role="status" className="mt-3">{storageMessage}</p>}
  <CodexRunnerOperationalView state={state} expectedDigest={expectedDigest}/>
 </div>
}
