"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {definitionIdFromName} from "@/lib/definition-id";

type Initial={key:string;name:string;model:string;runtime:"openai-responses"|"openai-agents";repositoryRevision:string};

export function ProviderConnectionEditor({initial}:{initial?:Initial}){
 const router=useRouter(),editing=!!initial,[name,setName]=useState(initial?.name??""),[key,setKey]=useState(initial?.key??""),[overridden,setOverridden]=useState(editing),[credential,setCredential]=useState(""),[runtime,setRuntime]=useState<Initial["runtime"]>(initial?.runtime??"openai-responses"),[model,setModel]=useState(initial?.model??""),[models,setModels]=useState<string[]>(initial?.model?[initial.model]:[]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError("");const url=editing?`/api/workflow-connections/${encodeURIComponent(initial.key)}/models`:"/api/workflow-connections/models",response=await fetch(url,{method:editing?"GET":"POST",...(editing?{}:{headers:{"content-type":"application/json"},body:JSON.stringify({credential})})}),value=await response.json() as {models?:string[];error?:string};if(response.ok){setModels(value.models??[]);if(!model&&value.models?.length)setModel(value.models[0]);}else setError(value.error??"Unable to retrieve models.");setBusy(false)}
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");const body=editing?{displayName:name,adapter:runtime,model,repositoryRevision:initial.repositoryRevision}:{connectionKey:key,displayName:name,adapter:runtime,model,credential},url=editing?`/api/workflow-connections/${encodeURIComponent(initial.key)}`:"/api/workflow-connections",response=await fetch(url,{method:editing?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),value=await response.json() as {error?:string};if(!response.ok){setError(value.error??"Unable to save connection.");setBusy(false);return}router.push("/workflows/connections");router.refresh()}
 return <form onSubmit={submit} className="mt-6 grid max-w-2xl gap-4"><p className="text-sm">* Required</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<label>Name *<input className="block w-full rounded border p-2" required maxLength={120} value={name} onChange={event=>{setName(event.target.value);if(!overridden)setKey(definitionIdFromName(event.target.value))}}/></label><label>Connection ID *<input className="block w-full rounded border p-2" required readOnly={editing} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={80} value={key} onChange={event=>{setOverridden(true);setKey(event.target.value)}}/></label><p className="text-sm">Permanent identifier used by Agents to reference this connection. Lowercase letters and numbers separated by hyphens.</p><label>Provider runtime *<select className="block w-full rounded border p-2" value={runtime} onChange={event=>setRuntime(event.target.value as Initial["runtime"])}><option value="openai-responses">OpenAI Responses</option><option value="openai-agents">OpenAI Agents (ADT Runtime)</option></select></label>{!editing&&<label>API key *<input autoComplete="off" className="block w-full rounded border p-2" type="password" required maxLength={8192} value={credential} onChange={event=>setCredential(event.target.value)}/></label>}<button type="button" className="w-fit rounded border p-2" disabled={busy||(!editing&&!credential)} onClick={load}>{editing?"Refresh available models":"Load available models"}</button><label>Model *<input className="block w-full rounded border p-2" required list="available-models" value={model} onChange={event=>setModel(event.target.value)}/><datalist id="available-models">{models.map(id=><option key={id} value={id}/>)}</datalist></label><p className="text-sm">Search the models available to this authenticated OpenAI project. Test connection validates the selected OpenAI provider and model. OpenAI Agents Runtime diagnostics remain independent.</p><button className="rounded bg-sky-700 px-4 py-2 font-bold text-white" disabled={busy||models.length===0}>{busy?"Working…":"Save connection"}</button></form>
}
