"use client";

import { useId, useMemo, useRef, useState } from "react";
import { addTagValue, comboboxEscaped, comboboxMoved, comboboxQueryChanged, comboboxSelected, removeTagValue, tagOptions, type ComboboxState, type TagSuggestion } from "@/lib/tag-suggestions";

export function TagCombobox({ label, selected, suggestions, onChange, disabled = false, unavailableMessage }: { label: string; selected: string[]; suggestions: TagSuggestion[]; onChange: (values: string[]) => void; disabled?: boolean; unavailableMessage?: string }) {
  const reactId = useId().replaceAll(":", "");
  const inputId = `${reactId}-tag-input`; const listboxId = `${reactId}-tag-listbox`; const helpId = `${reactId}-tag-help`; const labelId = `${reactId}-tag-label`;
  const inputRef = useRef<HTMLInputElement>(null);
  const [query, setQuery] = useState("");
  const [state, setState] = useState<ComboboxState>({ open: false, activeIndex: -1 });
  const options = useMemo(() => tagOptions(suggestions, query, selected), [suggestions, query, selected]);
  const activeId = state.open && state.activeIndex >= 0 && options[state.activeIndex] ? `${listboxId}-option-${state.activeIndex}` : undefined;
  function commit(value: string) { const next = addTagValue(selected, value, suggestions); if (next !== selected) onChange(next); setQuery(""); setState(comboboxSelected()); requestAnimationFrame(() => inputRef.current?.focus()); }
  return <fieldset className="mt-4"><legend id={labelId} className="text-sm font-semibold">{label}</legend>
    <div className="mt-2 flex flex-wrap gap-2">{selected.map((tag) => <span key={tag} className="inline-flex items-center gap-1 rounded-full bg-slate-100 py-1 pl-3 pr-1 text-sm dark:bg-slate-800"><span>{tag}</span><button type="button" disabled={disabled} onClick={() => onChange(removeTagValue(selected, tag))} aria-label={`Remove tag ${tag}`} className="rounded-full px-2 py-0.5 font-bold text-slate-700 hover:bg-slate-300 hover:text-slate-950 focus:bg-slate-300 focus:outline focus:outline-2 focus:outline-sky-700 dark:text-slate-100 dark:hover:bg-slate-700 dark:focus:bg-slate-700">×</button></span>)}</div>
    <p id={helpId} className="mt-2 text-xs text-slate-600 dark:text-slate-300">Type to search existing tags. Press Enter to add a new tag.</p>{unavailableMessage ? <p className="mt-1 text-xs text-amber-700 dark:text-amber-300">{unavailableMessage}</p> : null}
    <div className="relative mt-2"><input ref={inputRef} id={inputId} value={query} disabled={disabled} role="combobox" aria-autocomplete="list" aria-expanded={state.open && options.length > 0} aria-controls={listboxId} aria-activedescendant={activeId} aria-labelledby={labelId} aria-describedby={helpId} onChange={(event) => { const value = event.target.value; const nextOptions = tagOptions(suggestions, value, selected); setQuery(value); setState(comboboxQueryChanged(state, nextOptions.length)); }} onFocus={() => setState((current) => ({ ...current, open: options.length > 0 }))} onBlur={() => undefined} onKeyDown={(event) => { if (event.key === "ArrowDown") { event.preventDefault(); setState((current) => comboboxMoved(current, options.length, 1)); } else if (event.key === "ArrowUp") { event.preventDefault(); setState((current) => comboboxMoved(current, options.length, -1)); } else if (event.key === "Enter") { event.preventDefault(); const active = state.open && state.activeIndex >= 0 ? options[state.activeIndex] : undefined; commit(active?.value ?? query); } else if (event.key === "Escape") { setState((current) => comboboxEscaped(current)); } }} className="w-full rounded-xl border p-2 dark:bg-slate-950" />
      {state.open && options.length > 0 ? <ul id={listboxId} role="listbox" aria-labelledby={labelId} className="absolute z-10 mt-1 max-h-64 w-full overflow-auto rounded-xl border bg-white p-1 shadow-soft dark:border-slate-700 dark:bg-slate-900">{options.map((option, index) => <li id={`${listboxId}-option-${index}`} key={`${option.kind}-${option.value}`} role="option" aria-selected={index === state.activeIndex} onMouseDown={(event) => event.preventDefault()}><button type="button" onClick={() => commit(option.value)} className={`w-full rounded-lg px-3 py-2 text-left text-sm ${index === state.activeIndex ? "bg-sky-100 dark:bg-slate-800" : "hover:bg-slate-100 dark:hover:bg-slate-800"}`}>{option.kind === "create" ? <>Create tag “{option.value}”</> : option.value}</button></li>)}</ul> : null}</div>
  </fieldset>;
}
