"use client";
import {useReducer,useState} from "react";
import {useRouter} from "next/navigation";
import {definitionIdDraftReducer,DEFINITION_ID_MAX_LENGTH} from "@/lib/definition-id";
import type {ConnectionDescriptor} from "@/lib/workflow-connections";
import {getOpenAIModelAgentCapabilities} from "@/lib/openai-model-agent-capabilities";
import {WorkflowAgentPromptSelector} from "@/components/WorkflowAgentPromptSelector";
import type {WorkflowAgentPromptSummary} from "@/lib/workflow-agent-prompts";
import type {AgentPrompt} from "@/lib/workflow-definitions";
type Initial={id:string;name:string;description:string;prompt?:AgentPrompt;masterPrompt?:string;connectionKey:string;adapterOptions?:Record<string,unknown>};
const field="block w-full rounded border p-2";
export function WorkflowAgentEditor({initial,fileSha,connections,initialArtifact}:{initial?:Initial;fileSha?:string;connections:ConnectionDescriptor[];initialArtifact?:WorkflowAgentPromptSummary}){
 const router=useRouter(),[error,setError]=useState(""),[key,setKey]=useState(initial?.connectionKey??connections.find(c=>c.enabled)?.key??""),[prompt,setPrompt]=useState<AgentPrompt>(initial?.prompt??{source:"custom",text:initial?.masterPrompt??""});
 const [identity,updateIdentity]=useReducer(definitionIdDraftReducer,{name:initial?.name??"",id:initial?.id??"",idOverridden:Boolean(initial)}),selected=connections.find(c=>c.key===key),options=initial?.adapterOptions??{},capabilities=getOpenAIModelAgentCapabilities(selected?.defaultModel);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError("");const data=new FormData(event.currentTarget);let adapterOptions:Record<string,unknown>={};if(selected?.adapter==="deterministic-test")adapterOptions={mode:String(data.get("mode")),pendingChecks:Number(data.get("pendingChecks")),cancellation:String(data.get("cancellation"))};else if(selected?.adapter==="openai-responses"){const effort=String(data.get("reasoningEffort")??""),verbosity=String(data.get("verbosity")??""),maximum=String(data.get("maxOutputTokens")??"");adapterOptions={...(effort?{reasoningEffort:effort}:{}),...(verbosity?{verbosity}:{}),...(maximum?{maxOutputTokens:Number(maximum)}:{})}}else if(selected?.adapter==="codex-cloud")adapterOptions={environmentKey:String(data.get("environmentKey"))};const definition={schemaVersion:2,id:String(data.get("id")),name:String(data.get("name")),description:String(data.get("description")),status:"draft",prompt,connectionKey:key,adapterOptions};const response=await fetch(initial?`/api/workflow-agents/${initial.id}`:"/api/workflow-agents",{method:initial?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(initial?{definition,fileSha}:definition)});if(!response.ok){const body=await response.json() as {error?:string};setError(body.error??"Save failed.");return}router.push(`/workflows/agents/${definition.id}`);router.refresh()}
 const panelDescription=selected?`Optional controls for ${selected.name}${selected.defaultModel?` — ${selected.defaultModel}`:""}.`:"";
 const legacyEffort=typeof options.reasoningEffort==="string"&&!capabilities.reasoningEfforts?.includes(options.reasoningEffort as never)?options.reasoningEffort:undefined,legacyVerbosity=typeof options.verbosity==="string"&&!capabilities.verbosity?.includes(options.verbosity as never)?options.verbosity:undefined;
 return <form onSubmit={submit} className="mt-6 grid max-w-2xl gap-4"><p className="text-sm">* Required</p>{error&&<p role="alert" className="text-red-700">{error}</p>}
 <label>Name *<input name="name" required value={identity.name} placeholder={initial?undefined:"e.g. Todo list planner"} onChange={e=>updateIdentity({type:"name",value:e.target.value})} className={field}/></label>
 <label>ID *<input name="id" required readOnly={Boolean(initial)} value={identity.id} placeholder={initial?undefined:"e.g. todo-list-planner"} onChange={e=>updateIdentity({type:"id",value:e.target.value})} maxLength={DEFINITION_ID_MAX_LENGTH} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" aria-describedby="agent-id-help" className={field}/></label><p id="agent-id-help" className="text-sm">Permanent identifier used by Workflows. It cannot be changed after creation.</p>
 <label>Description (optional)<textarea name="description" defaultValue={initial?.description} placeholder={initial?undefined:"What this Agent is responsible for"} className={field}/></label>
 <WorkflowAgentPromptSelector prompt={prompt} setPrompt={setPrompt} initialArtifact={initialArtifact}/>
 <label>Connection *<select name="connectionKey" required value={key} onChange={e=>setKey(e.target.value)} aria-describedby="agent-connection-help" className={field}>{connections.map(c=><option key={c.key} value={c.key} disabled={!c.enabled&&c.key!==initial?.connectionKey}>{c.name}{c.defaultModel?` — ${c.defaultModel}`:""}{c.enabled?"":" (Not configured)"}</option>)}</select></label><p id="agent-connection-help" className="text-sm">Provider connection used when this Agent runs.</p>
 {selected&&<fieldset className="grid gap-4 rounded-lg border bg-slate-50 p-4 dark:bg-slate-900/50"><legend className="px-1 font-bold">Additional settings</legend><p className="text-sm text-slate-600 dark:text-slate-300">{panelDescription}</p>
 {selected.adapter==="deterministic-test"&&<div className="grid gap-3 sm:grid-cols-2"><label>Mode<select name="mode" defaultValue={String(options.mode??"immediate")} className={field}><option value="immediate">Immediate completion</option><option value="pending">Pending then completion</option><option value="transient_failure">Transient failure</option><option value="terminal_failure">Terminal failure</option><option value="oversized">Oversized output</option></select></label><label>Pending checks<input name="pendingChecks" type="number" min="0" max="20" defaultValue={Number(options.pendingChecks??0)} className={field}/></label><label>Cancellation<select name="cancellation" defaultValue={String(options.cancellation??"supported")} className={field}><option value="supported">Supported</option><option value="unsupported">Unsupported</option></select></label></div>}
 {selected.adapter==="openai-responses"&&<div className="grid gap-3 sm:grid-cols-2"><label>Reasoning effort<select name="reasoningEffort" defaultValue={String(options.reasoningEffort??"")} className={field}><option value="">Provider default</option>{legacyEffort&&<option value={legacyEffort}>{legacyEffort} (unsupported)</option>}{capabilities.reasoningEfforts?.map(v=><option key={v} value={v}>{v}</option>)}</select></label><label>Verbosity<select name="verbosity" defaultValue={String(options.verbosity??"")} className={field}><option value="">Provider default</option>{legacyVerbosity&&<option value={legacyVerbosity}>{legacyVerbosity} (unsupported)</option>}{capabilities.verbosity?.map(v=><option key={v} value={v}>{v}</option>)}</select></label>{(capabilities.maxOutputTokens||options.maxOutputTokens!==undefined)&&<label>Maximum output tokens<input name="maxOutputTokens" type="number" min="1" max={capabilities.maxOutputTokens??262144} defaultValue={options.maxOutputTokens===undefined?"":Number(options.maxOutputTokens)} className={field}/><span className="text-sm">Optional provider limit. Availability depends on the selected model.</span></label>}{legacyEffort||legacyVerbosity?<p role="alert" className="text-sm text-red-700">A saved option is unsupported by this model. Choose Provider default or a supported value before saving.</p>:null}</div>}
 {selected.adapter==="codex-cloud"&&<div><label>Codex environment key *<input name="environmentKey" required maxLength={80} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" defaultValue={String(options.environmentKey??"")} className={field}/></label><p className="mt-2 text-sm">Production transport is currently unavailable. Repository and GitHub configuration remain owned by Codex.</p></div>}</fieldset>}
 <button disabled={!selected?.enabled} className="rounded bg-sky-700 px-4 py-2 font-bold text-white disabled:opacity-50">Save Agent</button></form>
}
