"use client";
import {useCallback,useState} from "react";
import {Background,Controls,Handle,Position,ReactFlow,applyNodeChanges,type Node,type NodeChange,type Viewport} from "@xyflow/react";
import type {WorkflowDefinition} from "@/lib/workflow-definitions";
import {normalizeWorkflowLayout,projectSequentialWorkflow,type WorkflowLayoutV1} from "@/lib/workflow-layout";
type SavedLayout={definition:WorkflowLayoutV1;fileSha:string};
function GraphNode({data}:{data:{label:string;detail:string;kind:string}}){const join=data.kind==="join",condition=data.kind==="condition",approval=data.kind==="approval",subworkflow=data.kind==="subworkflow";return <div className={`min-w-44 rounded border-2 p-3 shadow ${join?"border-violet-600 bg-violet-50 text-violet-950":condition?"border-amber-600 bg-amber-50 text-amber-950":approval?"border-orange-600 bg-orange-50 text-orange-950":subworkflow?"border-teal-600 bg-teal-50 text-teal-950":"border-sky-600 bg-white text-slate-950"}`}><Handle id="in" type="target" position={Position.Left}/><strong>{data.label}</strong><span className="block text-xs">{data.detail}</span>{condition?<><Handle id="true" type="source" position={Position.Right} style={{top:"35%"}}/><span className="block text-right text-xs">true</span><Handle id="false" type="source" position={Position.Right} style={{top:"70%"}}/><span className="block text-right text-xs">false</span></>:<Handle id="out" type="source" position={Position.Right}/>}</div>}
const nodeTypes={graph:GraphNode};
export function WorkflowLayoutEditor({workflow,agents,initialLayout}:{workflow:WorkflowDefinition;agents:Record<string,string>;initialLayout?:SavedLayout}){
 const projected=projectSequentialWorkflow(workflow,initialLayout?.definition);
 const [nodes,setNodes]=useState<Node[]>(()=>projected.nodes.map(node=>{const semantic=workflow.nodes.find(item=>item.id===node.id)!,agentId=String((semantic.config as {agentId?:string}).agentId??"");return{...node,type:"graph",data:{label:semantic.blockType==="agent"?(agents[agentId]??agentId):semantic.blockType==="condition"?"Condition":semantic.blockType==="approval"?"Approval":semantic.blockType==="subworkflow"?"Reusable workflow":"Join",detail:semantic.blockType==="condition"?"contains predicate":semantic.blockType==="join"?"Wait for every branch":semantic.blockType==="approval"?String((semantic.config as {message:string}).message):semantic.blockType==="subworkflow"?String((semantic.config as {workflowId:string}).workflowId):"Agent",kind:semantic.blockType}}}));
 const edges=workflow.edges.map(edge=>({...edge,sourceHandle:edge.sourcePort??"out",targetHandle:edge.targetPort??"in",label:edge.sourcePort==="true"||edge.sourcePort==="false"?edge.sourcePort:undefined}));
 const [viewport,setViewport]=useState<Viewport>(projected.viewport),[fileSha,setFileSha]=useState(initialLayout?.fileSha),[status,setStatus]=useState("");
 const onNodesChange=useCallback((changes:NodeChange<Node>[])=>setNodes(current=>applyNodeChanges(changes,current)),[]);
 async function save(){setStatus("Saving layout…");const positions=Object.fromEntries(nodes.map(node=>[node.id,node.position])),layout=normalizeWorkflowLayout(workflow,positions,viewport);try{const response=await fetch(`/api/workflow-definitions/${workflow.id}/layout`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({layout,...(fileSha?{fileSha}:{})})}),body=await response.json() as {fileSha?:string;error?:string};if(!response.ok||!body.fileSha){setStatus(body.error??"Layout could not be saved.");return;}setFileSha(body.fileSha);setStatus("Layout saved.");}catch{setStatus("Layout could not be saved. Refresh before trying again.");}}
 return <section className="mt-6" aria-labelledby="workflow-layout-heading"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="workflow-layout-heading" className="text-xl font-bold">{"Workflow graph"}</h2><p className="text-sm text-slate-600 dark:text-slate-300">Drag nodes or move the viewport to arrange this view. Semantic edges determine {"routing"}; layout changes never change what runs.</p></div><button type="button" onClick={save} className="rounded bg-sky-700 px-4 py-2 font-bold text-white">Save layout</button></div><div className="mt-3 h-[28rem] min-h-80 w-full overflow-hidden rounded-lg border bg-slate-50 touch-none dark:bg-slate-950" data-workflow-visual-editor><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onMoveEnd={(_,next)=>setViewport(next)} defaultViewport={projected.viewport} fitView={!initialLayout} fitViewOptions={{padding:0.2}} nodesConnectable={false} elementsSelectable zoomOnPinch panOnScroll minZoom={0.2} maxZoom={2}><Background/><Controls showInteractive={false}/></ReactFlow></div><p className="mt-2 min-h-6 text-sm" role="status">{status}</p></section>;
}
