"use client";
import {useId,useRef,useState} from "react";
import type {WorkflowAgentPromptSummary} from "@/lib/workflow-agent-prompts";
export const AGENT_MASTER_PROMPT_MAX_LENGTH=65536;
type Selected=WorkflowAgentPromptSummary&{body:string};
export function WorkflowAgentPromptSelector({masterPrompt,setMasterPrompt}:{masterPrompt:string;setMasterPrompt:(value:string)=>void}){
 const id=useId(),timer=useRef<ReturnType<typeof setTimeout>>(undefined),[query,setQuery]=useState(""),[open,setOpen]=useState(false),[prompts,setPrompts]=useState<WorkflowAgentPromptSummary[]>([]),[loading,setLoading]=useState(false),[warning,setWarning]=useState(""),[active,setActive]=useState(0),[selected,setSelected]=useState<Selected>();
 function search(value:string){setQuery(value);setOpen(true);setLoading(true);clearTimeout(timer.current);timer.current=setTimeout(async()=>{try{const response=await fetch(`/api/workflow-agent-prompts?q=${encodeURIComponent(value)}`);if(!response.ok)throw new Error();const body=await response.json() as {prompts:WorkflowAgentPromptSummary[]};setPrompts(body.prompts);setWarning("");}catch{setPrompts([]);setWarning("Artifact Library temporarily unavailable.");}finally{setLoading(false);setActive(0)}},150)}
 const count=prompts.length+1;
 async function choose(index:number){if(index===prompts.length){setSelected(undefined);setMasterPrompt("");setQuery("Custom Prompt");setOpen(false);return}const summary=prompts[index];setLoading(true);try{const response=await fetch(`/api/artifacts/${encodeURIComponent(summary.id)}`);if(!response.ok)throw new Error("Prompt is no longer available.");const detail=await response.json() as {artifact?:{id:string;title:string;type:string;status:string;body:string;excerpt:string;tags:string[]}};const artifact=detail.artifact;if(!artifact||artifact.type!=="prompt"||artifact.status==="archived")throw new Error("This Artifact is no longer an available prompt.");if(artifact.body.length>AGENT_MASTER_PROMPT_MAX_LENGTH)throw new Error("This prompt is too large for an Agent master prompt.");setSelected({...summary,title:artifact.title,status:artifact.status as "production"|"draft",body:artifact.body});setMasterPrompt(artifact.body);setQuery(artifact.title);setWarning("");setOpen(false);}catch(error){setWarning(error instanceof Error?error.message:"Prompt could not be loaded.");setSelected(undefined);setMasterPrompt("");}finally{setLoading(false)}}
 if(selected)return <section aria-labelledby={`${id}-label`} className="grid gap-2"><h2 id={`${id}-label`} className="font-medium">Prompt *</h2><div className="rounded border bg-slate-50 p-4 dark:bg-slate-900"><div className="flex items-center justify-between gap-3"><strong>{selected.title}</strong><span className="rounded-full border px-2 py-0.5 text-xs capitalize">{selected.status}</span></div><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{selected.excerpt}</p><button type="button" className="mt-3 underline" onClick={()=>{setSelected(undefined);setMasterPrompt("");setQuery("");setOpen(true)}}>Change prompt</button></div><input type="hidden" name="masterPrompt" value={masterPrompt}/></section>;
 return <div className="grid gap-2"><label id={`${id}-label`} htmlFor={`${id}-input`}>Prompt *</label><div className="relative"><input id={`${id}-input`} role="combobox" aria-expanded={open} aria-controls={`${id}-listbox`} aria-activedescendant={open?`${id}-option-${active}`:undefined} aria-autocomplete="list" value={query} placeholder="Search prompts..." onFocus={()=>{setOpen(true);if(prompts.length===0&&!loading)search(query)}} onChange={event=>search(event.target.value)} onKeyDown={event=>{if(event.key==="ArrowDown"){event.preventDefault();setOpen(true);setActive(value=>Math.min(value+1,count-1))}else if(event.key==="ArrowUp"){event.preventDefault();setActive(value=>Math.max(value-1,0))}else if(event.key==="Enter"&&open){event.preventDefault();void choose(active)}else if(event.key==="Escape")setOpen(false)}} className="block w-full rounded border p-2"/>{open&&<ul id={`${id}-listbox`} role="listbox" aria-labelledby={`${id}-label`} className="absolute z-10 mt-1 max-h-72 w-full overflow-auto rounded border bg-white p-1 shadow-lg dark:bg-slate-950">{loading&&<li className="p-2" role="status">Loading prompts…</li>}{!loading&&prompts.length===0&&<li className="p-2 text-sm">No matching prompts.</li>}{prompts.map((prompt,index)=><li key={prompt.id} id={`${id}-option-${index}`} role="option" aria-selected={active===index} onMouseDown={event=>{event.preventDefault();void choose(index)}} className={`cursor-pointer rounded p-2 ${active===index?"bg-sky-100 dark:bg-sky-950":""}`}><span className="flex justify-between gap-2"><strong>{prompt.title}</strong><span className="capitalize">{prompt.status}</span></span><span className="block text-sm text-slate-600 dark:text-slate-300">{prompt.excerpt}</span></li>)}<li className="my-1 border-t"/><li id={`${id}-option-${prompts.length}`} role="option" aria-selected={active===prompts.length} onMouseDown={event=>{event.preventDefault();void choose(prompts.length)}} className={`cursor-pointer rounded p-2 font-semibold ${active===prompts.length?"bg-sky-100 dark:bg-sky-950":""}`}>Custom Prompt</li></ul>}</div>{warning&&<p role="status" className="text-amber-700 dark:text-amber-300">{warning} Custom Prompt is still available.</p>}<label>Master prompt *<textarea name="masterPrompt" required maxLength={AGENT_MASTER_PROMPT_MAX_LENGTH} value={masterPrompt} onChange={event=>setMasterPrompt(event.target.value)} placeholder="Give this Agent persistent instructions..." className="block min-h-32 w-full rounded border p-2"/></label></div>;
}
