"use client";
import {useReducer,useState} from "react";
import {useRouter} from "next/navigation";
import {definitionIdDraftReducer,DEFINITION_ID_MAX_LENGTH} from "@/lib/definition-id";
import {agentConnectionOptions,type ConnectionDescriptor} from "@/lib/workflow-connections";
import {getOpenAIModelAgentCapabilities} from "@/lib/openai-model-agent-capabilities";
import {WorkflowAgentPromptSelector} from "@/components/WorkflowAgentPromptSelector";
import type {WorkflowAgentPromptDescriptor} from "@/lib/workflow-agent-prompts";
import type {CodexRunnerSnapshot} from "@/lib/workflow-services";
import type {AgentPrompt} from "@/lib/workflow-definitions";
type Initial={id:string;name:string;description:string;prompt?:AgentPrompt;masterPrompt?:string;connectionKey:string;tools?:"artifact_search"[];adapterOptions?:Record<string,unknown>};
const field="adt-field";
export function buildCodexRunnerAgentOptions(environmentKey:string,model:string,reasoningEffort:string){return{environmentKey,...(model?{model}:{}),...(reasoningEffort?{reasoningEffort}:{})}}
export function WorkflowAgentEditor({initial,fileSha,connections,initialArtifact,codexSnapshot}:{initial?:Initial;fileSha?:string;connections:ConnectionDescriptor[];initialArtifact?:WorkflowAgentPromptDescriptor;codexSnapshot?:CodexRunnerSnapshot}){
 connections=agentConnectionOptions(connections,initial?.connectionKey);
 const router=useRouter(),[error,setError]=useState(""),[codexEnvironment,setCodexEnvironment]=useState(String(initial?.adapterOptions?.environmentKey??"")),[codexModel,setCodexModel]=useState(String(initial?.adapterOptions?.model??"")),[codexEffort,setCodexEffort]=useState(String(initial?.adapterOptions?.reasoningEffort??"")),[key,setKey]=useState(initial?.connectionKey??connections.find(c=>c.enabled)?.key??""),[prompt,setPrompt]=useState<AgentPrompt>(initial?.prompt??{source:"custom",text:initial?.masterPrompt??""});
 const [identity,updateIdentity]=useReducer(definitionIdDraftReducer,{name:initial?.name??"",id:initial?.id??"",idOverridden:Boolean(initial)}),selected=connections.find(c=>c.key===key),options=initial?.adapterOptions??{},capabilities=getOpenAIModelAgentCapabilities(selected?.defaultModel);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError("");const data=new FormData(event.currentTarget);let adapterOptions:Record<string,unknown>={};if(selected?.adapter==="deterministic-test")adapterOptions={mode:String(data.get("mode")),pendingChecks:Number(data.get("pendingChecks")),cancellation:String(data.get("cancellation"))};else if(selected&&["openai-responses","openai-agents"].includes(selected.adapter)){const effort=String(data.get("reasoningEffort")??""),verbosity=String(data.get("verbosity")??""),maximum=String(data.get("maxOutputTokens")??"");adapterOptions={...(effort?{reasoningEffort:effort}:{}),...(verbosity?{verbosity}:{}),...(maximum?{maxOutputTokens:Number(maximum)}:{})}}else if(selected?.adapter==="codex-runner")adapterOptions=buildCodexRunnerAgentOptions(String(data.get("environmentKey")),String(data.get("model")??""),String(data.get("reasoningEffort")??""));else if(selected?.adapter==="codex-cloud")adapterOptions={environmentKey:String(data.get("environmentKey"))};const tools=selected?.adapter==="openai-agents"&&data.get("artifactSearch")==="enabled"?["artifact_search" as const]:undefined;const definition={schemaVersion:2,id:String(data.get("id")),name:String(data.get("name")),description:String(data.get("description")),status:"draft",prompt,connectionKey:key,...(tools?{tools}:{}),adapterOptions};const response=await fetch(initial?`/api/workflow-agents/${initial.id}`:"/api/workflow-agents",{method:initial?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(initial?{definition,fileSha}:definition)});if(!response.ok){const body=await response.json() as {error?:string};setError(body.error??"Save failed.");return}router.push(`/workflows/agents/${definition.id}`);router.refresh()}
 const panelDescription=selected?`Optional controls for ${selected.name}${selected.defaultModel?` — ${selected.defaultModel}`:""}.`:"";
 const codexSelectedModel=codexSnapshot?.models.find(model=>codexModel?model.id===codexModel:model.isDefault),savedCodexModelUnavailable=Boolean(codexSnapshot?.modelCatalogAvailable&&codexModel&&!codexSelectedModel),savedCodexEffortUnsupported=Boolean(codexSnapshot?.modelCatalogAvailable&&codexEffort&&!codexSelectedModel?.supportedReasoningEfforts.some(item=>item.reasoningEffort===codexEffort)),selectedCodexEnvironment=codexSnapshot?.environments.find(item=>item.key===codexEnvironment),readyCodexEnvironments=codexSnapshot?.environments.filter(item=>item.enabled&&item.ready)??[];
 const codexBlockers=selected?.adapter!=="codex-runner"?[]:[...(!codexSnapshot?.configured?["Codex Runner is not configured."]:[]),...(codexSnapshot?.configured&&!codexSnapshot.reachable?["Codex Runner is unavailable."]:[]),...(codexSnapshot?.reachable&&!codexSnapshot.capabilitiesAvailable?["Codex Runner capabilities are unavailable."]:[]),...(codexSnapshot?.capabilitiesAvailable&&!codexSnapshot.codexAvailable?["Codex is unavailable on this Runner."]:[]),...(codexSnapshot?.capabilitiesAvailable&&codexSnapshot.codexAvailable&&!codexSnapshot.jobExecution?["This Codex Runner does not support Workflow job execution."]:[]),...(codexSnapshot?.reachable&&!codexSnapshot.environmentCatalogAvailable?["The Codex Runner environment catalogue is unavailable."]:[]),...(codexSnapshot?.environmentCatalogAvailable&&!readyCodexEnvironments.length?["No ready Codex Runner environments are available. Configure an environment on the Runner before saving this Agent."]:[]),...(codexEnvironment&&(!selectedCodexEnvironment?.enabled||!selectedCodexEnvironment.ready)?["The selected Codex Runner environment is unavailable."]:[]),...(!codexEnvironment?["Select a ready Codex Runner environment."]:[]),...(codexSnapshot?.reachable&&!codexSnapshot.authStatusAvailable?["ChatGPT connection status is unavailable."]:[]),...(codexSnapshot?.authStatusAvailable&&!codexSnapshot.authenticated?["ChatGPT is not connected on the Codex Runner."]:[]),...(!codexSnapshot?.modelCatalogAvailable?["The Codex model catalogue is unavailable."]:[]),...(savedCodexModelUnavailable?["The selected Codex model is unavailable."]:[]),...(savedCodexEffortUnsupported?["The selected reasoning effort is unavailable for this Codex model."]:[])];
 const legacyEffort=typeof options.reasoningEffort==="string"&&!capabilities.reasoningEfforts?.includes(options.reasoningEffort as never)?options.reasoningEffort:undefined,legacyVerbosity=typeof options.verbosity==="string"&&!capabilities.verbosity?.includes(options.verbosity as never)?options.verbosity:undefined;
 return <form onSubmit={submit} className="mt-6 grid max-w-2xl gap-4"><p className="text-sm">* Required</p>{error&&<p role="alert" className="text-red-700">{error}</p>}
 <label>Name *<input name="name" required value={identity.name} placeholder={initial?undefined:"e.g. Todo list planner"} onChange={e=>updateIdentity({type:"name",value:e.target.value})} className={field}/></label>
 <label>ID *<input name="id" required readOnly={Boolean(initial)} value={identity.id} placeholder={initial?undefined:"e.g. todo-list-planner"} onChange={e=>updateIdentity({type:"id",value:e.target.value})} maxLength={DEFINITION_ID_MAX_LENGTH} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" aria-describedby="agent-id-help" className={field}/></label><p id="agent-id-help" className="text-sm">Permanent identifier used by Workflows. It cannot be changed after creation.</p>
 <label>Description (optional)<textarea name="description" defaultValue={initial?.description} placeholder={initial?undefined:"What this Agent is responsible for"} className={field}/></label>
 <WorkflowAgentPromptSelector prompt={prompt} setPrompt={setPrompt} initialArtifact={initialArtifact}/>
 <label>Connection *<select name="connectionKey" required value={key} onChange={e=>setKey(e.target.value)} aria-describedby="agent-connection-help" className={field}>{connections.map(c=>{const retired=c.adapter==="codex-cloud";return <option key={c.key} value={c.key} disabled={retired||!c.enabled}>{c.name}{c.defaultModel?` — ${c.defaultModel}`:""}{retired?" (Saved legacy connection — unavailable)":c.enabled?"":c.adapter==="codex-runner"?" (Currently unavailable)":" (Not configured)"}</option>})}</select></label><p id="agent-connection-help" className="text-sm">Provider connection used when this Agent runs.</p>
 {selected&&<fieldset className="grid gap-4 rounded-lg border bg-slate-50 p-4 dark:bg-slate-900/50"><legend className="px-1 font-bold">Additional settings</legend><p className="text-sm text-slate-600 dark:text-slate-300">{panelDescription}</p>
 {selected.adapter==="deterministic-test"&&<div className="grid gap-3 sm:grid-cols-2"><label>Mode<select name="mode" defaultValue={String(options.mode??"immediate")} className={field}><option value="immediate">Immediate completion</option><option value="pending">Pending then completion</option><option value="transient_failure">Transient failure</option><option value="terminal_failure">Terminal failure</option><option value="oversized">Oversized output</option></select></label><label>Pending checks<input name="pendingChecks" type="number" min="0" max="20" defaultValue={Number(options.pendingChecks??0)} className={field}/></label><label>Cancellation<select name="cancellation" defaultValue={String(options.cancellation??"supported")} className={field}><option value="supported">Supported</option><option value="unsupported">Unsupported</option></select></label></div>}
 {["openai-responses","openai-agents"].includes(selected.adapter)&&<div className="grid gap-3 sm:grid-cols-2">{selected.adapter==="openai-agents"&&<label className="sm:col-span-2 flex items-start gap-2"><input name="artifactSearch" type="checkbox" value="enabled" defaultChecked={initial?.tools?.includes("artifact_search")}/><span><strong>Artifact search</strong><span className="block text-sm">Allow this Agent to search the authorised Artifact Library.</span></span></label>}<label>Reasoning effort<select name="reasoningEffort" defaultValue={String(options.reasoningEffort??"")} className={field}><option value="">Provider default</option>{legacyEffort&&<option value={legacyEffort}>{legacyEffort} (unsupported)</option>}{capabilities.reasoningEfforts?.map(v=><option key={v} value={v}>{v}</option>)}</select></label><label>Verbosity<select name="verbosity" defaultValue={String(options.verbosity??"")} className={field}><option value="">Provider default</option>{legacyVerbosity&&<option value={legacyVerbosity}>{legacyVerbosity} (unsupported)</option>}{capabilities.verbosity?.map(v=><option key={v} value={v}>{v}</option>)}</select></label>{(capabilities.maxOutputTokens||options.maxOutputTokens!==undefined)&&<label>Maximum output tokens<input name="maxOutputTokens" type="number" min="1" max={capabilities.maxOutputTokens??262144} defaultValue={options.maxOutputTokens===undefined?"":Number(options.maxOutputTokens)} className={field}/><span className="text-sm">Optional provider limit. Availability depends on the selected model.</span></label>}{legacyEffort||legacyVerbosity?<p role="alert" className="text-sm text-red-700">A saved option is unsupported by this model. Choose Provider default or a supported value before saving.</p>:null}</div>}
 {selected.adapter==="codex-runner"&&<div className="grid gap-3 sm:grid-cols-2"><label>Environment *<select name="environmentKey" required value={codexEnvironment} onChange={event=>setCodexEnvironment(event.target.value)} className={field}>{typeof options.environmentKey==="string"&&!codexSnapshot?.environments.some(item=>item.key===options.environmentKey)&&<option value={options.environmentKey}>{options.environmentKey} (saved; live validation unavailable)</option>}<option value="" disabled>Select environment</option>{codexSnapshot?.environments.map(item=><option key={item.key} value={item.key} disabled={!item.enabled||!item.ready}>{item.name} / {item.key}{item.enabled&&item.ready?"":" (Unavailable)"}</option>)}</select></label><label>Model<select name="model" value={codexModel} onChange={event=>{const model=event.target.value;setCodexModel(model);const advertised=codexSnapshot?.models.find(item=>model?item.id===model:item.isDefault)?.supportedReasoningEfforts.some(item=>item.reasoningEffort===codexEffort);if(codexEffort&&!advertised)setCodexEffort("")}} className={field} disabled={!codexSnapshot?.modelCatalogAvailable}><option value="">Codex default</option>{typeof options.model==="string"&&!codexSnapshot?.models.some(item=>item.id===options.model)&&<option value={options.model}>{options.model} (saved; live validation unavailable)</option>}{codexSnapshot?.models.map(model=><option key={model.id} value={model.id}>{model.displayName}{model.isDefault?" (current default)":""}</option>)}</select></label><label>Reasoning effort<select name="reasoningEffort" value={codexEffort} onChange={event=>setCodexEffort(event.target.value)} className={field} disabled={!codexSnapshot?.modelCatalogAvailable}><option value="">Model default</option>{savedCodexEffortUnsupported&&<option value={codexEffort}>{codexEffort} (saved; unsupported)</option>}{codexSelectedModel?.supportedReasoningEfforts.map(effort=><option key={effort.reasoningEffort} value={effort.reasoningEffort}>{effort.reasoningEffort}{effort.description?` — ${effort.description}`:""}</option>)}</select></label>{!codexSnapshot?.modelCatalogAvailable&&<p role="alert" className="text-sm text-red-700">Codex model discovery is currently unavailable. Runner environments remain available; saved model values are unchanged.</p>}{codexBlockers.length>0&&<div role="alert" className="sm:col-span-2 rounded border border-red-300 p-3 text-sm text-red-700"><p className="font-semibold">This Agent cannot currently be saved:</p><ul className="list-disc pl-5">{codexBlockers.map(reason=><li key={reason}>{reason}</li>)}</ul></div>}</div>}
 {selected.adapter==="codex-cloud"&&<p role="alert" className="text-sm text-red-700">This saved legacy connection is unavailable and cannot be selected or saved.</p>}</fieldset>}
 <button disabled={!selected?.enabled||codexBlockers.length>0} className="rounded bg-sky-700 px-4 py-2 font-bold text-white disabled:opacity-50">Save Agent</button></form>
}
