"use client";
import {useCallback,useReducer,useState} from "react";
import {useRouter} from "next/navigation";
import {addEdge,applyEdgeChanges,applyNodeChanges,Background,Controls,Handle,Position,ReactFlow,type Connection,type Edge,type EdgeChange,type Node,type NodeChange,type Viewport} from "@xyflow/react";
import {definitionIdDraftReducer,DEFINITION_ID_MAX_LENGTH} from "@/lib/definition-id";
import type {WorkflowDefinitionV1,WorkflowDefinitionV2} from "@/lib/workflow-definitions";
import {normalizeWorkflowLayout,type WorkflowLayoutV1} from "@/lib/workflow-layout";
import {persistWorkflowLayout,persistWorkflowSemantics} from "@/lib/workflow-editor-persistence";
import {addV1Step,moveV1Step,removeV1Step,replaceV1StepAgent} from "@/lib/workflow-v1-editor";

type Agent={id:string;name:string};type SavedLayout={definition:WorkflowLayoutV1;fileSha:string};
function AgentNode({data}:{data:{label:string}}){return <div className="min-w-44 rounded border bg-white p-3 text-slate-950 shadow"><Handle type="target" position={Position.Left}/><strong>{data.label}</strong><Handle type="source" position={Position.Right}/></div>}
const nodeTypes={agent:AgentNode};
export function WorkflowDefinitionEditor(props:{agents:Agent[];initial?:WorkflowDefinitionV1|WorkflowDefinitionV2;fileSha?:string;initialLayout?:SavedLayout}){return props.initial?.schemaVersion===1?<V1Editor agents={props.agents} initial={props.initial} fileSha={props.fileSha}/>:<V2Editor {...props} initial={props.initial?.schemaVersion===2?props.initial:undefined}/>;}
function V2Editor({agents,initial,fileSha,initialLayout}:{agents:Agent[];initial?:WorkflowDefinitionV2;fileSha?:string;initialLayout?:SavedLayout}){
 const router=useRouter(),workflow=initial,saved=initialLayout?.definition.positions??{};
 const [nodes,setNodes]=useState<Node[]>(()=>workflow?.nodes.map((node,index)=>{const config=node.config as {agentId:string};return{id:node.id,type:"agent",position:saved[node.id]??{x:index*240,y:80},data:{label:agents.find(a=>a.id===config.agentId)?.name??config.agentId,agentId:config.agentId}}})??[]);
 const [edges,setEdges]=useState<Edge[]>(()=>workflow?.edges.map(edge=>({...edge}))??[]),[viewport,setViewport]=useState<Viewport>(initialLayout?.definition.viewport??{x:0,y:0,zoom:1}),[layoutSha,setLayoutSha]=useState(initialLayout?.fileSha),[description,setDescription]=useState(workflow?.description??""),[createdId,setCreatedId]=useState<string>(),[error,setError]=useState(""),[status,setStatus]=useState("");
 const [identity,updateIdentity]=useReducer(definitionIdDraftReducer,{name:workflow?.name??"",id:workflow?.id??"",idOverridden:Boolean(workflow)});
 const onNodesChange=useCallback((changes:NodeChange<Node>[])=>setNodes(current=>applyNodeChanges(changes,current)),[]),onEdgesChange=useCallback((changes:EdgeChange<Edge>[])=>setEdges(current=>applyEdgeChanges(changes,current)),[]),onConnect=useCallback((connection:Connection)=>setEdges(current=>addEdge({...connection,id:`edge-${connection.source}-${connection.target}`},current)),[]);
 function addAgent(){const agent=agents[0];if(!agent)return;const id=`node-${crypto.randomUUID().slice(0,8)}`;setNodes(old=>[...old,{id,type:"agent",position:{x:old.length*220,y:80},data:{label:agent.name,agentId:agent.id}}]);}
 const definition=()=>({schemaVersion:2 as const,id:identity.id,name:identity.name,description,status:"draft" as const,nodes:nodes.map(node=>({id:node.id,blockType:"agent",blockVersion:1,config:{agentId:String(node.data.agentId)}})),edges:edges.map(edge=>({id:edge.id,source:edge.source,target:edge.target})),limits:{maxStepExecutions:Math.max(nodes.length,32)}});
 async function saveLayout(){if(!workflow)return;setError("");setStatus("Saving layout…");try{const saved=await persistWorkflowLayout(fetch,normalizeWorkflowLayout(workflow,Object.fromEntries(nodes.map(node=>[node.id,node.position])),viewport),layoutSha);setLayoutSha(saved);setStatus("Layout saved without changing the Workflow definition.");}catch(cause){setStatus("");setError(cause instanceof Error?cause.message:"Layout could not be saved. Refresh before trying again.");}}
 async function submit(event:React.FormEvent<HTMLFormElement>){
  event.preventDefault();setError("");setStatus("Saving Workflow…");const value=definition();
  try{
   await persistWorkflowSemantics(fetch,value,fileSha);
   if(workflow){setStatus("Workflow definition saved. Layout was not changed.");router.refresh();return;}
   try{await persistWorkflowLayout(fetch,normalizeWorkflowLayout(value,Object.fromEntries(nodes.map(node=>[node.id,node.position])),viewport));}
   catch{setStatus("");setCreatedId(value.id);setError("Workflow was created, but its optional layout was not saved. Open the created Workflow and save layout there; do not create it again.");return;}
   router.push(`/workflows/definitions/${value.id}`);router.refresh();
  }catch(cause){setStatus("");setError(cause instanceof Error?cause.message:"Workflow could not be saved.");}
 }
 return <form onSubmit={submit} className="mt-6 grid gap-4"><p className="text-sm">Workflow graph changes (blocks and connections) are semantic. Dragging changes presentation layout only.</p>{error&&<p role="alert">{error}</p>}<label>Name *<input name="name" required value={identity.name} onChange={e=>updateIdentity({type:"name",value:e.target.value})} className="block w-full rounded border p-2"/></label><label>ID *<input name="id" required readOnly={Boolean(workflow)} value={identity.id} onChange={e=>updateIdentity({type:"id",value:e.target.value})} maxLength={DEFINITION_ID_MAX_LENGTH} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" className="block w-full rounded border p-2"/></label><label>Description<textarea name="description" value={description} onChange={event=>setDescription(event.target.value)} className="block w-full rounded border p-2"/></label><div><button type="button" onClick={addAgent} className="rounded border px-3 py-2">Add Agent block</button></div><div className="h-[32rem] rounded border bg-slate-50 dark:bg-slate-950"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={onConnect} onMoveEnd={(_,next)=>setViewport(next)} defaultViewport={viewport} deleteKeyCode={null} fitView={!initialLayout}><Background/><Controls/></ReactFlow></div>{nodes.map(node=><label key={node.id}>{node.id} Agent<select value={String(node.data.agentId)} onChange={e=>setNodes(old=>old.map(item=>item.id===node.id?{...item,data:{agentId:e.target.value,label:agents.find(a=>a.id===e.target.value)?.name??e.target.value}}:item))} className="ml-2 rounded border p-2">{agents.map(agent=><option key={agent.id} value={agent.id}>{agent.name}</option>)}</select><button type="button" className="ml-2" onClick={()=>{setNodes(old=>old.filter(item=>item.id!==node.id));setEdges(old=>old.filter(edge=>edge.source!==node.id&&edge.target!==node.id))}}>Remove block</button></label>)}<p className="text-sm">Select a connection and use “Remove connection” to make an intentional semantic edit.</p>{edges.map(edge=><button type="button" key={edge.id} onClick={()=>setEdges(old=>old.filter(item=>item.id!==edge.id))}>Remove connection {edge.source} → {edge.target}</button>)}<div className="flex gap-3">{workflow&&<button type="button" onClick={saveLayout} className="rounded border px-4 py-2 font-bold">Save layout only</button>}<button disabled={Boolean(createdId)} className="rounded bg-sky-700 px-4 py-2 font-bold text-white disabled:opacity-50">{workflow?"Save Workflow changes":"Create Workflow"}</button></div>{createdId&&<a className="underline" href={`/workflows/definitions/${createdId}`}>Open created Workflow</a>}<p role="status">{status}</p></form>;
}
function V1Editor({agents,initial,fileSha}:{agents:Agent[];initial:WorkflowDefinitionV1;fileSha?:string}){
 const router=useRouter(),[steps,setSteps]=useState(initial.steps.map(s=>s.agentId)),[error,setError]=useState("");const [identity,updateIdentity]=useReducer(definitionIdDraftReducer,{name:initial.name,id:initial.id,idOverridden:true});
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),definition={...initial,name:String(data.get("name")),description:String(data.get("description")),steps:steps.map((agentId,index)=>({id:`step-${index+1}`,name:agents.find(a=>a.id===agentId)?.name??`Step ${index+1}`,agentId,input:{source:index?"previous_step":"run_input"},onSuccess:{type:index===steps.length-1?"complete":"next"},onFailure:{type:"fail"}})),result:{source:"step_output",stepId:`step-${steps.length}`},limits:{maxStepExecutions:Math.max(initial.limits.maxStepExecutions,steps.length)}};const response=await fetch(`/api/workflow-definitions/${initial.id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({definition,fileSha})});if(!response.ok){setError(((await response.json()) as {error?:string}).error??"Save failed.");return;}router.push(`/workflows/definitions/${initial.id}`);router.refresh()}
 return <form onSubmit={submit} className="mt-6 grid max-w-2xl gap-4">{error&&<p role="alert">{error}</p>}<p>This existing Workflow uses v1 ordered-step editing and is not automatically converted.</p><label>Name *<input name="name" required value={identity.name} onChange={e=>updateIdentity({type:"name",value:e.target.value})} className="block w-full rounded border p-2"/></label><input type="hidden" name="id" value={identity.id}/><label>Description<textarea name="description" defaultValue={initial.description} className="block w-full rounded border p-2"/></label><fieldset><legend className="font-bold">Ordered Agents *</legend>{steps.map((value,index)=><div className="mt-3 rounded border p-3" key={index}><strong>Step {index+1}</strong><select aria-label={`Step ${index+1} Agent`} value={value} onChange={e=>setSteps(old=>replaceV1StepAgent(old,index,e.target.value))} className="ml-2 rounded border p-2">{agents.map(agent=><option key={agent.id} value={agent.id}>{agent.name}</option>)}</select><div className="mt-2 flex gap-2"><button type="button" disabled={index===0} onClick={()=>setSteps(old=>moveV1Step(old,index,-1))}>Move up</button><button type="button" disabled={index===steps.length-1} onClick={()=>setSteps(old=>moveV1Step(old,index,1))}>Move down</button><button type="button" disabled={steps.length===1} onClick={()=>setSteps(old=>removeV1Step(old,index))}>Remove</button></div></div>)}<button type="button" className="mt-3" disabled={!agents.length} onClick={()=>setSteps(old=>addV1Step(old,agents[0].id))}>Add step</button></fieldset><button className="rounded bg-sky-700 px-4 py-2 font-bold text-white">Save Workflow</button></form>
}
