import {z} from "zod";
import {PROTOCOL_VERSION} from "./protocol.js";

export const EXECUTION_PATH_DIAGNOSTIC_PATH="/v1/diagnostics/execution-path",EXECUTION_PATH_DIAGNOSTIC_CAPABILITY="diagnostic:execution-path";
const targetSchema=z.object({url:z.string().min(1).max(2048),authority:z.string().min(1).max(4096)}).strict();
export const executionPathDiagnosticSchema=z.object({protocolVersion:z.literal(PROTOCOL_VERSION),capability:z.literal(EXECUTION_PATH_DIAGNOSTIC_CAPABILITY),requestId:z.string().regex(/^[A-Za-z0-9:_-]{1,256}$/),targets:z.object({checkpoint:targetSchema.optional(),"graph-node":targetSchema.optional(),"artifact-search":targetSchema.optional()}).strict()}).strict();
export type ExecutionPathTarget="checkpoint"|"graph-node"|"artifact-search";
export type ExecutionPathResult={target:ExecutionPathTarget;configured:boolean;endpoint?:string;responseReceived:boolean;authorityAccepted:boolean|null;backendAvailable:boolean|null;httpStatus?:number;elapsedMs:number;failureCode?:"timeout"|"network_error"|"http_401"|"http_403"|"http_409"|"http_503"|"malformed_response"|"authority_rejected"|"backend_unavailable"};
function endpoint(value:string){const url=new URL(value);if(url.username||url.password||url.search||url.hash||value.length>2048||url.protocol!=="https:"&&!['localhost','127.0.0.1','::1'].includes(url.hostname))throw new Error("invalid_url");return `${url.host}${url.pathname}`}
function validWire(value:unknown):value is {ok:boolean;authorityAccepted?:boolean;backendAvailable?:boolean;code?:string}{if(!value||typeof value!=="object"||Array.isArray(value))return false;const v=value as Record<string,unknown>;return typeof v.ok==="boolean"&&(v.authorityAccepted===undefined||typeof v.authorityAccepted==="boolean")&&(v.backendAvailable===undefined||typeof v.backendAvailable==="boolean")&&(v.code===undefined||typeof v.code==="string")}
export async function diagnoseExecutionPathTarget(target:ExecutionPathTarget,value:{url:string;authority:string},fetcher:typeof fetch=fetch):Promise<ExecutionPathResult>{const started=Date.now();let display:string;try{display=endpoint(value.url)}catch{return{target,configured:true,responseReceived:false,authorityAccepted:null,backendAvailable:null,elapsedMs:Date.now()-started,failureCode:"network_error"}}let response:Response;try{response=await fetcher(value.url,{method:"POST",redirect:"error",headers:{"content-type":"application/json","authorization":`Bearer ${value.authority}`},body:JSON.stringify({operation:"execution-path-diagnostic",target}),signal:AbortSignal.timeout(5_000)})}catch(error){return{target,configured:true,endpoint:display,responseReceived:false,authorityAccepted:null,backendAvailable:null,elapsedMs:Date.now()-started,failureCode:error instanceof DOMException&&["AbortError","TimeoutError"].includes(error.name)?"timeout":"network_error"}}let wire:unknown;try{const body=await response.text();if(Buffer.byteLength(body)>2048)throw new Error();wire=JSON.parse(body)}catch{return{target,configured:true,endpoint:display,responseReceived:true,authorityAccepted:null,backendAvailable:null,httpStatus:response.status,elapsedMs:Date.now()-started,failureCode:"malformed_response"}}if(!validWire(wire))return{target,configured:true,endpoint:display,responseReceived:true,authorityAccepted:null,backendAvailable:null,httpStatus:response.status,elapsedMs:Date.now()-started,failureCode:"malformed_response"};const code=response.status===401?"authority_rejected":response.status===403?"http_403":response.status===409?"http_409":response.status===503?(wire.code==="backend_unavailable"?"backend_unavailable":"http_503"):undefined;return{target,configured:true,endpoint:display,responseReceived:true,authorityAccepted:wire.authorityAccepted??(response.ok?true:response.status===401?false:null),backendAvailable:wire.backendAvailable??null,httpStatus:response.status,elapsedMs:Date.now()-started,...(code?{failureCode:code}:{})}}
export async function diagnoseExecutionPath(request:z.infer<typeof executionPathDiagnosticSchema>,fetcher:typeof fetch=fetch){const entries=Object.entries(request.targets) as Array<[ExecutionPathTarget,{url:string;authority:string}]>;return Promise.all(entries.map(([target,value])=>diagnoseExecutionPathTarget(target,value,fetcher)))}
