import {lookup} from "node:dns/promises";
import {isIP} from "node:net";
import {Client} from "@modelcontextprotocol/sdk/client/index.js";
import {StreamableHTTPClientTransport} from "@modelcontextprotocol/sdk/client/streamableHttp.js";

export const MCP_DISCOVERY_CAPABILITY="mcp:streamable-http:discover",MCP_CALL_CAPABILITY="mcp:streamable-http:call";
export const MCP_LIMITS={tools:64,nameBytes:128,descriptionBytes:2048,schemaBytes:32_768,argumentsBytes:65_536,resultBytes:128_000,durationMs:10_000,redirects:2} as const;
export type McpServerConfig={url:string;transport:"streamable-http";allowLocalhost?:boolean};
export type McpTool={name:string;description?:string;inputSchema:Record<string,unknown>};
export class McpFailure extends Error{readonly retryable=false;constructor(readonly category:string,readonly safeMessage:string,readonly ambiguous=false){super(category)}}
const bytes=(value:string)=>Buffer.byteLength(value,"utf8");
function forbidden(address:string){if(address==="::1"||address==="::"||address.startsWith("fe80:")||address.startsWith("fc")||address.startsWith("fd"))return true;if(isIP(address)===4){const p=address.split(".").map(Number);return p[0]===10||p[0]===127||p[0]===0||p[0]===169&&p[1]===254||p[0]===172&&p[1]>=16&&p[1]<=31||p[0]===192&&p[1]===168||p[0]>=224}return false}
export async function validateMcpUrl(value:string,allowLocalhost=false){let url:URL;try{url=new URL(value)}catch{throw new McpFailure("configuration_invalid","MCP server configuration is invalid.")}if(url.username||url.password||url.hash||url.protocol!=="https:"){if(!(allowLocalhost&&url.protocol==="http:"&&(url.hostname==="localhost"||url.hostname==="127.0.0.1"||url.hostname==="[::1]")))throw new McpFailure("configuration_invalid","MCP server destination is not permitted.")}if(allowLocalhost&&(url.hostname==="localhost"||url.hostname==="127.0.0.1"||url.hostname==="[::1]"))return url;let addresses;try{addresses=await lookup(url.hostname,{all:true,verbatim:true})}catch{throw new McpFailure("connection_unavailable","MCP server is unavailable.")}if(!addresses.length||addresses.some(item=>forbidden(item.address)))throw new McpFailure("configuration_invalid","MCP server destination is not permitted.");return url}
function safeFetch(config:McpServerConfig,credential?:string,fetcher:typeof fetch=fetch){return async(input:string|URL|Request,init?:RequestInit)=>{let url=await validateMcpUrl(input instanceof Request?input.url:String(input),config.allowLocalhost),redirects=0;for(;;){const headers=new Headers(init?.headers);if(credential)headers.set("authorization",`Bearer ${credential}`);let response:Response;try{response=await fetcher(url,{...init,headers,redirect:"manual",signal:AbortSignal.timeout(MCP_LIMITS.durationMs)})}catch{throw new McpFailure("connection_unavailable","MCP server request failed safely.")}if(response.status<300||response.status>=400)return response;const location=response.headers.get("location");if(!location||redirects++>=MCP_LIMITS.redirects)throw new McpFailure("connection_unavailable","MCP server redirect was rejected.");url=await validateMcpUrl(new URL(location,url).href,config.allowLocalhost)}}}
async function connected<T>(config:McpServerConfig,credential:string|undefined,operation:(client:Client)=>Promise<T>,fetcher?:typeof fetch,ambiguous=false,operationFailure="connection_unavailable"){if(config.transport!=="streamable-http")throw new McpFailure("configuration_invalid","MCP transport is unsupported.");const client=new Client({name:"adt-runtime",version:"1"}),transport=new StreamableHTTPClientTransport(await validateMcpUrl(config.url,config.allowLocalhost),{fetch:safeFetch(config,credential,fetcher),reconnectionOptions:{maxReconnectionDelay:1,initialReconnectionDelay:1,reconnectionDelayGrowFactor:1,maxRetries:0}});let connected=false;try{await client.connect(transport,{timeout:MCP_LIMITS.durationMs});connected=true;return await operation(client)}catch(error){if(error instanceof McpFailure&&!connected)throw error;if(error instanceof McpFailure&&!ambiguous)throw error;throw new McpFailure(connected?operationFailure:"connection_unavailable",ambiguous&&connected?"MCP tool outcome is unknown.":connected?"MCP server returned an invalid response.":"MCP server request failed safely.",ambiguous&&connected)}finally{await transport.close().catch(()=>undefined)}}
function catalogueTool(value:unknown):McpTool{if(!value||typeof value!=="object"||Array.isArray(value))throw new McpFailure("malformed_response","MCP server returned an invalid tool catalogue.");const v=value as Record<string,unknown>,name=v.name,description=v.description,inputSchema=v.inputSchema;if(typeof name!=="string"||!name||bytes(name)>MCP_LIMITS.nameBytes||(description!==undefined&&(typeof description!=="string"||bytes(description)>MCP_LIMITS.descriptionBytes))||!inputSchema||typeof inputSchema!=="object"||Array.isArray(inputSchema)||bytes(JSON.stringify(inputSchema))>MCP_LIMITS.schemaBytes)throw new McpFailure("malformed_response","MCP server returned an invalid tool catalogue.");return{name,...(description?{description}:{}),inputSchema:inputSchema as Record<string,unknown>}}
export async function discoverMcpTools(config:McpServerConfig,credential?:string,fetcher?:typeof fetch){return connected(config,credential,async client=>{const result=await client.listTools(undefined,{timeout:MCP_LIMITS.durationMs});if(result.tools.length>MCP_LIMITS.tools)throw new McpFailure("response_too_large","MCP tool catalogue exceeds the permitted size.");return result.tools.map(catalogueTool)},fetcher,false,"malformed_response")}
export async function callMcpTool(config:McpServerConfig,tool:McpTool,arguments_:Record<string,unknown>,credential?:string,fetcher?:typeof fetch){catalogueTool(tool);if(bytes(JSON.stringify(arguments_))>MCP_LIMITS.argumentsBytes)throw new McpFailure("configuration_invalid","MCP tool arguments exceed the permitted size.");return connected(config,credential,async client=>{const result=await client.callTool({name:tool.name,arguments:arguments_},undefined,{timeout:MCP_LIMITS.durationMs});const serialized=JSON.stringify(result);if(bytes(serialized)>MCP_LIMITS.resultBytes)throw new McpFailure("response_too_large","MCP tool result exceeds the permitted size.");return result},fetcher,true)}
