import {createServer,type IncomingMessage,type ServerResponse} from "node:http";
import {readFileSync} from "node:fs";
import {secretValue,authenticate,ReplayCache,MAX_BODY_BYTES,PROTOCOL_VERSION,READINESS_PATH,EXECUTE_PATH,executionSchema,decryptCredential,loadWrappingKey,MCP_DISCOVER_PATH,MCP_CALL_PATH,mcpDiscoverySchema,mcpCallSchema,SECURITY_TEST_PATH,ADRIAN_SECURITY_CAPABILITY,ADRIAN_SECURITY_TEST_CAPABILITY,securityTestSchema} from "./protocol.js";
import {executeOpenAIAgents,RuntimeFailure,type Factories} from "./openai-agents.js";
import {advanceGenericGraph,graphExecutionSchema,GraphNodeGatewayFailure,CheckpointGatewayFailure,LANGGRAPH_EXECUTE_PATH,LANGGRAPH_APPROVAL_CAPABILITY,LANGGRAPH_CONTEXT_SELECTION_CAPABILITY,LANGGRAPH_GRAPH_CAPABILITY} from "./langgraph.js";
import {diagnoseExecutionPath,executionPathDiagnosticSchema,EXECUTION_PATH_DIAGNOSTIC_CAPABILITY,EXECUTION_PATH_DIAGNOSTIC_PATH} from "./execution-path-diagnostic.js";
import {callMcpTool,discoverMcpTools,MCP_CALL_CAPABILITY,MCP_DISCOVERY_CAPABILITY,McpFailure,type McpTool,type NetworkFetch} from "./mcp.js";
import {adrian} from "@secureagentics/adrian";
import {acquireAdrianExecutionLease,AdrianExecutionLeaseUnavailableError,ProductionAdrianSecurityGate,SecurityDecisionError} from "./adrian.js";
import {ADRIAN_TEST_LOGIN_TIMEOUT_MS,ADRIAN_TEST_TOTAL_TIMEOUT_MS,probeAdrianControlChannel,type AdrianCommissioningResult} from "./adrian-commissioning.js";
import {RUNTIME_RELEASE} from "./release.js";
import {AdrianLocalLifecycleError,withAdrianLocalLog} from "./adrian-local-log.js";
import {REDEPLOY_CAPABILITY,REDEPLOY_PATH,redeployAvailable,requestRedeploy,type RedeployConfiguration} from "./redeploy.js";

export const RUNTIME_INBOUND_REQUEST_TIMEOUT_MS=60_000,RUNTIME_HEADERS_TIMEOUT_MS=10_000,RUNTIME_EXECUTION_RESPONSE_TIMEOUT_MS=150_000;
type Logger=(event:Record<string,unknown>)=>void;
export type AdrianRuntimeLifecycle=Pick<typeof adrian,"init"|"shutdown"|"getHandler"|"getWebSocketClient">;
type Options={host:string;port:number;authSecret:string;privateKeyPem:string;revision:string;factories?:Partial<Factories>;mcpFetcher?:NetworkFetch;redeployFetcher?:typeof fetch;redeploy?:RedeployConfiguration;now?:()=>number;logger?:Logger;adrianRuntime?:AdrianRuntimeLifecycle;adrianProbe?:typeof probeAdrianControlChannel};
type ErrorCode="runtime_authentication_failed"|"invalid_request"|"credential_invalid"|"unsupported_operation"|"protocol_incompatible"|"capability_unavailable"|"runtime_unavailable"|"execution_failed"|"adrian_initialization_failed"|"adrian_policy_unavailable";
const safe=(res:ServerResponse,status:number,value:unknown)=>{const body=JSON.stringify(value);res.writeHead(status,{"content-type":"application/json","content-length":Buffer.byteLength(body),"cache-control":"no-store"});res.end(body)};
const error=(res:ServerResponse,status:number,code:ErrorCode,category:string,message:string,providerExecutionEntered=false,orchestration?:unknown)=>safe(res,status,{protocolVersion:PROTOCOL_VERSION,ok:false,error:{code,category,safeMessage:message,retryable:false,providerExecutionEntered,...(orchestration?{orchestration}:{})}});
async function body(req:IncomingMessage){const chunks:Buffer[]=[];let size=0;for await(const value of req){size+=value.length;if(size>MAX_BODY_BYTES)throw new Error("body_too_large");chunks.push(value)}return Buffer.concat(chunks)}
const boundedId=(value:unknown)=>typeof value==="string"&&/^[A-Za-z0-9:_-]{1,256}$/.test(value)?value:undefined;
export function runtimeBuildRevision(environment:NodeJS.ProcessEnv=process.env,readRevision:()=>string=()=>readFileSync("/runtime/REVISION","utf8")){try{const revision=readRevision().trim();if(revision)return revision.slice(0,128)}catch{/* Local source execution has no image-owned revision file. */}return (environment.ADT_RUNTIME_REVISION??"development").slice(0,128)}
export async function createRuntimeServer(options:Options){
 const {privateKey,keyId}=await loadWrappingKey(options.privateKeyPem),replays=new ReplayCache(),securityRuntime=options.adrianRuntime??adrian,log=options.logger??(event=>process.stdout.write(`${JSON.stringify(event)}\n`));let shuttingDown=false;
 const emit=(event:string,fields:Record<string,unknown>)=>log({event,protocolVersion:PROTOCOL_VERSION,runtimeRevision:options.revision,...fields});
 const server=createServer(async(req,res)=>{const started=Date.now();res.setHeader("x-content-type-options","nosniff");const path=new URL(req.url??"/","http://runtime.invalid").pathname,operation=path===READINESS_PATH?"readiness":path===EXECUTE_PATH?"execute":path===SECURITY_TEST_PATH?"security_test":path===MCP_DISCOVER_PATH?"mcp_discover":path===MCP_CALL_PATH?"mcp_call":path===LANGGRAPH_EXECUTE_PATH?"langgraph_advance":path===EXECUTION_PATH_DIAGNOSTIC_PATH?"execution_path_diagnostic":path===REDEPLOY_PATH?"infrastructure_redeploy":"unsupported";
  if(req.method==="GET"&&path==="/healthz")return safe(res,shuttingDown?503:200,{ok:!shuttingDown});
  if(shuttingDown){emit("runtime_request_rejected",{operation,result:"runtime_unavailable",httpStatus:503,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,503,"runtime_unavailable","connection_unavailable","Runtime is shutting down.")}
  let raw:Buffer;try{raw=await body(req)}catch{emit("runtime_request_rejected",{operation,result:"request_too_large",httpStatus:413,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,413,"invalid_request","configuration_invalid","Request body exceeds the permitted size.")}
  if(!authenticate(req.headers,req.method??"",path,raw,options.authSecret,replays,options.now?.())){emit("runtime_request_rejected",{operation,result:"authentication_failed",httpStatus:401,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,401,"runtime_authentication_failed","authentication_failed","Runtime request authentication failed.")}
  if(req.headers["x-adt-protocol"]!==PROTOCOL_VERSION){emit("runtime_request_rejected",{operation,result:"protocol_incompatible",httpStatus:409,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,409,"protocol_incompatible","configuration_invalid","Runtime protocol is incompatible.")}
  if(req.method==="GET"&&path===READINESS_PATH){const redeployTargets=(['runtime','runner'] as const).filter(target=>redeployAvailable(target,options.redeploy??{}));emit("runtime_readiness_succeeded",{operation,httpStatus:200,elapsedMs:Date.now()-started,providerExecutionEntered:false});return safe(res,200,{protocolVersion:PROTOCOL_VERSION,runtimeRevision:options.revision,runtimeReleaseRevision:RUNTIME_RELEASE.releaseRevision,capabilities:["openai-agents","tool:artifact-search",MCP_DISCOVERY_CAPABILITY,MCP_CALL_CAPABILITY,LANGGRAPH_GRAPH_CAPABILITY,LANGGRAPH_APPROVAL_CAPABILITY,LANGGRAPH_CONTEXT_SELECTION_CAPABILITY,EXECUTION_PATH_DIAGNOSTIC_CAPABILITY,"execution-timeout",ADRIAN_SECURITY_CAPABILITY,ADRIAN_SECURITY_TEST_CAPABILITY,REDEPLOY_CAPABILITY],redeployTargets,credentialWrappingKeyId:keyId})}
  if(req.method==="POST"&&path===REDEPLOY_PATH){
   let request:{target:"runtime"|"runner";requestId:string};try{const value=JSON.parse(raw.toString("utf8"));if(!value||typeof value!=="object"||Array.isArray(value)||!(["runtime","runner"] as unknown[]).includes(value.target)||!boundedId(value.requestId)||Object.keys(value).some(key=>!["target","requestId"].includes(key)))throw Error();request=value}catch{return error(res,400,"invalid_request","configuration_invalid","Redeploy request is invalid.")}
   if(!redeployAvailable(request.target,options.redeploy??{}))return error(res,503,"capability_unavailable","configuration_invalid","Runtime-mediated redeploy is not configured.");
   const result=await requestRedeploy(request.target,options.redeploy??{},options.redeployFetcher,options.now);for(const outcome of result.outcomes)emit("runtime_redeploy_role_completed",{operation,requestId:request.requestId,target:request.target,role:outcome.role,result:outcome.outcome,httpStatus:outcome.httpStatus,elapsedMs:outcome.elapsedMs,providerExecutionEntered:false});
   return safe(res,result.accepted?202:502,{protocolVersion:PROTOCOL_VERSION,ok:result.accepted,...(result.accepted?{result:{state:"accepted",target:request.target,outcomes:result.outcomes}}:{error:{code:"execution_failed",category:result.ambiguous?"provider_start_ambiguous":"provider_rejected",safeMessage:result.ambiguous?"Redeploy request outcome is uncertain. Check freshness before trying again.":"Redeploy request was not accepted.",retryable:false,providerExecutionEntered:false,ambiguous:result.ambiguous,outcomes:result.outcomes}})});
  }
  if(req.method==="POST"&&path===SECURITY_TEST_PATH){
   let request;try{request=securityTestSchema.parse(JSON.parse(raw.toString("utf8")))}catch{return error(res,400,"invalid_request","configuration_invalid","Security Profile test request is invalid.")}
   let credential="",release:(()=>void)|undefined;const requestId=boundedId(request.requestId),testStarted=Date.now();
   const respond=(result:AdrianCommissioningResult)=>{const diagnostic={stage:result.stage,safeCode:result.safeCode,elapsedMs:Math.min(60_000,Math.max(0,Date.now()-testStarted)),...(result.httpStatus===undefined?{}:{httpStatus:result.httpStatus}),...(result.websocketCloseCode===undefined?{}:{websocketCloseCode:result.websocketCloseCode}),...(result.policyMode===undefined?{}:{policyMode:result.policyMode})};emit(result.ok?"runtime_security_test_sdk_ready":"runtime_security_test_failed",{operation,requestId,...diagnostic});return safe(res,result.ok?200:503,{protocolVersion:PROTOCOL_VERSION,ok:result.ok,...(result.ok?{result:{state:"ready",provider:"adrian",profileId:request.profileId,...diagnostic}}:{error:{code:result.safeCode,category:"security_unavailable",safeMessage:"Adrian commissioning failed safely.",retryable:false,providerExecutionEntered:false,diagnostic}})})};
   emit("runtime_security_test_started",{operation,requestId,stage:"runtime",elapsedMs:0});
   try{
    credential=await decryptCredential(request.credential,privateKey,keyId,`${PROTOCOL_VERSION}:${request.capability}:${request.requestId}`);
    let totalTimer:NodeJS.Timeout|undefined;const probe=await Promise.race([(options.adrianProbe??probeAdrianControlChannel)({endpointUrl:request.endpointUrl,apiKey:credential,sessionId:`adt:test:${request.requestId}`}),new Promise<AdrianCommissioningResult>(resolve=>{totalTimer=setTimeout(()=>resolve({ok:false,stage:"transport",safeCode:"adrian_ws_unreachable",elapsedMs:ADRIAN_TEST_TOTAL_TIMEOUT_MS}),ADRIAN_TEST_TOTAL_TIMEOUT_MS)})]).finally(()=>clearTimeout(totalTimer));
    if(!probe.ok)return respond(probe);
    emit("runtime_security_test_ws_upgrade_succeeded",{operation,requestId,stage:"upgrade",elapsedMs:Date.now()-testStarted});emit("runtime_security_test_login_ack_received",{operation,requestId,stage:"login",elapsedMs:Date.now()-testStarted});emit("runtime_security_test_policy_observed",{operation,requestId,stage:"policy",policyMode:probe.policyMode,elapsedMs:Date.now()-testStarted});
    try{release=acquireAdrianExecutionLease()}catch{return respond({...probe,ok:false,stage:"sdk",safeCode:"adrian_sdk_readiness_failed"})}
    let result:AdrianCommissioningResult;try{result=await withAdrianLocalLog(securityRuntime,{apiKey:credential,wsUrl:request.endpointUrl,sessionId:`adt:test:sdk:${request.requestId}`,blockTimeout:request.decisionTimeoutMs/1000},async()=>{const handler=securityRuntime.getHandler(),client=securityRuntime.getWebSocketClient();let ready=false;try{ready=Boolean(handler&&client&&await client.waitForPolicyReady(ADRIAN_TEST_LOGIN_TIMEOUT_MS/1000)&&client.loginAcked()&&client.policyActive()&&client.blockTimeout(request.decisionTimeoutMs/1000)===request.decisionTimeoutMs/1000)}catch{}return ready?{...probe,stage:"ready",safeCode:"ready",ok:true}:{...probe,ok:false,stage:"sdk",safeCode:"adrian_sdk_readiness_failed"}})}catch(value){if(value instanceof AdrianLocalLifecycleError)emit("runtime_security_test_local_initialization_failed",{operation,requestId,stage:"sdk",reason:value.reason});result={...probe,ok:false,stage:"sdk",safeCode:"adrian_sdk_readiness_failed"}}
    return respond(result)
   }catch(value){const failure=value instanceof AdrianExecutionLeaseUnavailableError?value:new AdrianExecutionLeaseUnavailableError();return error(res,503,"execution_failed",failure.category,failure.safeMessage,false)}finally{credential="";if(release)release()}
  }
  if(req.method==="POST"&&(path===MCP_DISCOVER_PATH||path===MCP_CALL_PATH)){let request;try{request=(path===MCP_DISCOVER_PATH?mcpDiscoverySchema:mcpCallSchema).parse(JSON.parse(raw.toString("utf8")))}catch{return error(res,400,"invalid_request","configuration_invalid","MCP request is invalid.")}let credential:string|undefined;if(request.credential)try{credential=await decryptCredential(request.credential,privateKey,keyId,`${PROTOCOL_VERSION}:${request.capability}:${request.requestId}`)}catch{return error(res,400,"credential_invalid","configuration_invalid","Credential envelope is invalid.")}try{const call=request as typeof request&{tool:McpTool;arguments:Record<string,unknown>},dependencies=options.mcpFetcher?{fetch:options.mcpFetcher}:undefined,result=path===MCP_DISCOVER_PATH?await discoverMcpTools(request.server,credential,dependencies):await callMcpTool(request.server,call.tool,call.arguments,credential,dependencies);emit("runtime_mcp_completed",{operation,requestId:boundedId(request.requestId),result:"completed",httpStatus:200,elapsedMs:Date.now()-started,providerExecutionEntered:false});return safe(res,200,{protocolVersion:PROTOCOL_VERSION,ok:true,result})}catch(value){const failure=value instanceof McpFailure?value:new McpFailure("internal_error","MCP operation failed safely.");emit("runtime_mcp_failed",{operation,requestId:boundedId(request.requestId),result:failure.category,httpStatus:502,elapsedMs:Date.now()-started,providerExecutionEntered:false,ambiguous:failure.ambiguous});return safe(res,502,{protocolVersion:PROTOCOL_VERSION,ok:false,error:{code:"execution_failed",category:failure.category,safeMessage:failure.safeMessage,retryable:false,ambiguous:failure.ambiguous}})}}
  if(req.method==="POST"&&path===EXECUTION_PATH_DIAGNOSTIC_PATH){let request;try{request=executionPathDiagnosticSchema.parse(JSON.parse(raw.toString("utf8")))}catch{emit("runtime_request_rejected",{operation,result:"schema_invalid",httpStatus:400,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,400,"invalid_request","configuration_invalid","Execution-path diagnostic request is invalid.")}emit("runtime_execution_path_diagnostic_started",{operation,requestId:boundedId(request.requestId),providerExecutionEntered:false});const results=await diagnoseExecutionPath(request);for(const result of results)emit("runtime_execution_path_target_completed",{operation,requestId:boundedId(request.requestId),target:result.target,result:result.failureCode??"available",httpStatus:result.httpStatus,elapsedMs:result.elapsedMs,providerExecutionEntered:false});emit("runtime_execution_path_diagnostic_completed",{operation,requestId:boundedId(request.requestId),result:"completed",httpStatus:200,elapsedMs:Date.now()-started,providerExecutionEntered:false});return safe(res,200,{protocolVersion:PROTOCOL_VERSION,ok:true,results})}
  if(req.method==="POST"&&path===LANGGRAPH_EXECUTE_PATH){let request;try{request=graphExecutionSchema.parse(JSON.parse(raw.toString("utf8")))}catch{emit("runtime_request_rejected",{operation,result:"schema_invalid",httpStatus:400,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,400,"invalid_request","configuration_invalid","LangGraph request is invalid.")}try{const result=await advanceGenericGraph(request);emit("runtime_langgraph_advance_completed",{operation,requestId:boundedId(request.requestId),result:result.state,httpStatus:200,elapsedMs:Date.now()-started,providerExecutionEntered:false});return safe(res,200,{protocolVersion:PROTOCOL_VERSION,ok:true,result})}catch(value){const known=value instanceof GraphNodeGatewayFailure||value instanceof CheckpointGatewayFailure,invalid=value instanceof GraphNodeGatewayFailure&&!value.retryable,status=invalid?409:503,category=invalid?"configuration_invalid":"provider_unavailable",message=invalid?"Graph node authority or admission is invalid.":"LangGraph execution is temporarily unavailable.",orchestration=known?value.orchestration:undefined;emit("runtime_langgraph_advance_failed",{operation,requestId:boundedId(request.requestId),result:orchestration?.code??"execution_failed",stage:orchestration?.stage,httpStatus:orchestration?.httpStatus??status,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,status,"execution_failed",category,message,false,orchestration)}}
  if(req.method!=="POST"||path!==EXECUTE_PATH){emit("runtime_request_rejected",{operation,result:"unsupported_operation",httpStatus:404,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,404,"unsupported_operation","configuration_invalid","Runtime operation is unsupported.")}
  let request;try{request=executionSchema.parse(JSON.parse(raw.toString("utf8")))}catch{emit("runtime_request_rejected",{operation,result:"schema_invalid",httpStatus:400,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,400,"invalid_request","configuration_invalid","Runtime request is invalid.")}
  const requestId=boundedId(request.requestId),aad=`${PROTOCOL_VERSION}:${request.capability}:${request.idempotencyKey}`;let credential:string;try{credential=await decryptCredential(request.credential,privateKey,keyId,aad)}catch{emit("runtime_request_rejected",{operation,requestId,result:"credential_invalid",httpStatus:400,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,400,"credential_invalid","configuration_invalid","Credential envelope is invalid.")}
  let releaseSecurity:(()=>void)|undefined,securityCredential="",security:ProductionAdrianSecurityGate|undefined,providerEntered=false;
  try{
   const execute=async()=>{if(request.runtimeSecurity){const handler=securityRuntime.getHandler(),client=securityRuntime.getWebSocketClient();let policyReady=false;try{policyReady=Boolean(client&&await client.waitForPolicyReady(request.runtimeSecurity.decisionTimeoutMs/1000)&&client.blockTimeout(request.runtimeSecurity.decisionTimeoutMs/1000)===request.runtimeSecurity.decisionTimeoutMs/1000)}catch{}if(!handler||!client||!policyReady)throw new AdrianExecutionLeaseUnavailableError();security=new ProductionAdrianSecurityGate(handler,client,request.runtimeSecurity.decisionTimeoutMs,decision=>emit("runtime_security_decision",{operation,requestId,provider:"adrian",profileId:request.runtimeSecurity!.profileId,outcome:decision.outcome,elapsedMs:decision.elapsedMs,providerExecutionEntered:true}))}
    emit("runtime_provider_execution_started",{operation,requestId,providerExecutionEntered:true});providerEntered=true;const mcpCredentials=new Map<string,string>();for(const grant of request.mcpTools)if(grant.credential)mcpCredentials.set(grant.alias,await decryptCredential(grant.credential,privateKey,keyId,`${PROTOCOL_VERSION}:${request.capability}:${request.idempotencyKey}:mcp:${grant.alias}`));const outputText=await executeOpenAIAgents(request,credential,{...options.factories,mcpCredentials,...(security?{securityGate:security,modelInstrumentation:security}:{})});emit("runtime_provider_execution_completed",{operation,requestId,result:"completed",httpStatus:200,elapsedMs:Date.now()-started,providerExecutionEntered:true});return outputText};
   let outputText:string;if(request.runtimeSecurity){try{releaseSecurity=acquireAdrianExecutionLease()}catch(value){if(value instanceof AdrianExecutionLeaseUnavailableError)return error(res,503,"execution_failed",value.category,value.safeMessage,false);throw value}securityCredential=await decryptCredential(request.runtimeSecurity.credential,privateKey,keyId,`${PROTOCOL_VERSION}:${request.capability}:${request.idempotencyKey}:security:adrian`);try{outputText=await withAdrianLocalLog(securityRuntime,{apiKey:securityCredential,wsUrl:request.runtimeSecurity.endpointUrl,sessionId:`adt:${request.idempotencyKey}`,blockTimeout:request.runtimeSecurity.decisionTimeoutMs/1000},execute)}catch(value){if(value instanceof AdrianLocalLifecycleError)throw new AdrianExecutionLeaseUnavailableError();throw value}}else outputText=await execute();
   return safe(res,200,{protocolVersion:PROTOCOL_VERSION,ok:true,result:{state:"completed",outputText}})
  }catch(value){const failure=value instanceof RuntimeFailure||value instanceof SecurityDecisionError||value instanceof AdrianExecutionLeaseUnavailableError?value:new RuntimeFailure("internal_error","The Agents runtime failed unexpectedly.");emit("runtime_provider_execution_failed",{operation,requestId,result:"execution_failed",failureCategory:failure.category,httpStatus:422,elapsedMs:Date.now()-started,providerExecutionEntered:providerEntered});return error(res,422,"execution_failed",failure.category,failure.safeMessage.length>512?"Runtime execution failed.":failure.safeMessage,providerEntered)}finally{credential="";securityCredential="";if(releaseSecurity)releaseSecurity()}

 });server.requestTimeout=RUNTIME_INBOUND_REQUEST_TIMEOUT_MS;server.headersTimeout=RUNTIME_HEADERS_TIMEOUT_MS;server.timeout=RUNTIME_EXECUTION_RESPONSE_TIMEOUT_MS;
 return{server,keyId,replays,listen:()=>new Promise<void>((resolve,reject)=>server.listen(options.port,options.host,resolve).once("error",reject)),close:()=>new Promise<void>((resolve,reject)=>server.close(value=>value?reject(value):resolve())),shutdown(){shuttingDown=true;server.closeIdleConnections()}};
}
function startup(event:string,stage:string){process.stderr.write(`${JSON.stringify({event,protocolVersion:PROTOCOL_VERSION,stage})}\n`)}
async function main(){let authSecret:string,privateKeyPem:string;try{authSecret=secretValue("ADT_RUNTIME_AUTH_SECRET")}catch{startup("runtime_startup_failed","auth_secret_missing");return process.exit(1)}if(authSecret.length<32){startup("runtime_startup_failed","auth_secret_invalid");return process.exit(1)}try{privateKeyPem=secretValue("ADT_RUNTIME_PRIVATE_KEY")}catch{startup("runtime_startup_failed","private_key_missing");return process.exit(1)}const optional=(name:string)=>{try{return secretValue(name)}catch{return undefined}},redeploy:RedeployConfiguration={runtime:optional("ADT_RUNTIME_REDEPLOY_WEBHOOK"),controller:optional("CODEX_RUNNER_CONTROLLER_REDEPLOY_WEBHOOK"),executor:optional("CODEX_RUNNER_EXECUTOR_REDEPLOY_WEBHOOK"),"repository-manager":optional("CODEX_RUNNER_REPOSITORY_MANAGER_REDEPLOY_WEBHOOK")},host=process.env.ADT_RUNTIME_HOST??"0.0.0.0",port=Number(process.env.ADT_RUNTIME_PORT??8080),revision=runtimeBuildRevision();if(!Number.isInteger(port)||port<1||port>65535||host.length>255){startup("runtime_startup_failed","listen_configuration_invalid");return process.exit(1)}let runtime;try{runtime=await createRuntimeServer({host,port,authSecret,privateKeyPem,revision,redeploy})}catch(value){const stage=value instanceof Error&&["private_key_invalid","wrapping_key_derivation_failed","wrapping_key_import_failed"].includes(value.message)?value.message:"wrapping_key_import_failed";startup("runtime_startup_failed",stage);return process.exit(1)}try{await runtime.listen()}catch{startup("runtime_startup_failed","listen_failed");return process.exit(1)}process.stdout.write(`${JSON.stringify({event:"runtime_started",protocolVersion:PROTOCOL_VERSION,runtimeRevision:revision,port})}\n`);const stop=()=>{runtime.shutdown();setTimeout(()=>process.exit(0),30_000).unref();runtime.close().then(()=>process.exit(0),()=>process.exit(1))};process.once("SIGTERM",stop);process.once("SIGINT",stop)}
if(process.argv[1]===new URL(import.meta.url).pathname)void main();
