import {createServer,type IncomingMessage,type ServerResponse} from "node:http";
import {secretValue,authenticate,ReplayCache,MAX_BODY_BYTES,PROTOCOL_VERSION,READINESS_PATH,EXECUTE_PATH,executionSchema,decryptCredential,loadWrappingKey} from "./protocol.js";
import {executeOpenAIAgents,RuntimeFailure,type Factories} from "./openai-agents.js";
import {advanceLinearGraph,LANGGRAPH_EXECUTE_PATH,LANGGRAPH_LINEAR_CAPABILITY,langGraphExecutionSchema} from "./langgraph.js";

type Logger=(event:Record<string,unknown>)=>void;
type Options={host:string;port:number;authSecret:string;privateKeyPem:string;revision:string;factories?:Partial<Factories>;now?:()=>number;logger?:Logger};
type ErrorCode="runtime_authentication_failed"|"invalid_request"|"credential_invalid"|"unsupported_operation"|"protocol_incompatible"|"capability_unavailable"|"runtime_unavailable"|"execution_failed";
const safe=(res:ServerResponse,status:number,value:unknown)=>{const body=JSON.stringify(value);res.writeHead(status,{"content-type":"application/json","content-length":Buffer.byteLength(body),"cache-control":"no-store"});res.end(body)};
const error=(res:ServerResponse,status:number,code:ErrorCode,category:string,message:string,providerExecutionEntered=false)=>safe(res,status,{protocolVersion:PROTOCOL_VERSION,ok:false,error:{code,category,safeMessage:message,retryable:false,providerExecutionEntered}});
async function body(req:IncomingMessage){const chunks:Buffer[]=[];let size=0;for await(const value of req){size+=value.length;if(size>MAX_BODY_BYTES)throw new Error("body_too_large");chunks.push(value)}return Buffer.concat(chunks)}
const boundedId=(value:unknown)=>typeof value==="string"&&/^[A-Za-z0-9:_-]{1,256}$/.test(value)?value:undefined;
export async function createRuntimeServer(options:Options){
 const {privateKey,keyId}=await loadWrappingKey(options.privateKeyPem),replays=new ReplayCache(),log=options.logger??(event=>process.stdout.write(`${JSON.stringify(event)}\n`));let shuttingDown=false;
 const emit=(event:string,fields:Record<string,unknown>)=>log({event,protocolVersion:PROTOCOL_VERSION,runtimeRevision:options.revision,...fields});
 const server=createServer(async(req,res)=>{const started=Date.now();res.setHeader("x-content-type-options","nosniff");const path=new URL(req.url??"/","http://runtime.invalid").pathname,operation=path===READINESS_PATH?"readiness":path===EXECUTE_PATH?"execute":path===LANGGRAPH_EXECUTE_PATH?"langgraph_advance":"unsupported";
  if(req.method==="GET"&&path==="/healthz")return safe(res,shuttingDown?503:200,{ok:!shuttingDown});
  if(shuttingDown){emit("runtime_request_rejected",{operation,result:"runtime_unavailable",httpStatus:503,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,503,"runtime_unavailable","connection_unavailable","Runtime is shutting down.")}
  let raw:Buffer;try{raw=await body(req)}catch{emit("runtime_request_rejected",{operation,result:"request_too_large",httpStatus:413,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,413,"invalid_request","configuration_invalid","Request body exceeds the permitted size.")}
  if(!authenticate(req.headers,req.method??"",path,raw,options.authSecret,replays,options.now?.())){emit("runtime_request_rejected",{operation,result:"authentication_failed",httpStatus:401,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,401,"runtime_authentication_failed","authentication_failed","Runtime request authentication failed.")}
  if(req.headers["x-adt-protocol"]!==PROTOCOL_VERSION){emit("runtime_request_rejected",{operation,result:"protocol_incompatible",httpStatus:409,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,409,"protocol_incompatible","configuration_invalid","Runtime protocol is incompatible.")}
  if(req.method==="GET"&&path===READINESS_PATH){emit("runtime_readiness_succeeded",{operation,httpStatus:200,elapsedMs:Date.now()-started,providerExecutionEntered:false});return safe(res,200,{protocolVersion:PROTOCOL_VERSION,runtimeRevision:options.revision,capabilities:["openai-agents","tool:artifact-search",LANGGRAPH_LINEAR_CAPABILITY],credentialWrappingKeyId:keyId})}
  if(req.method==="POST"&&path===LANGGRAPH_EXECUTE_PATH){let request;try{request=langGraphExecutionSchema.parse(JSON.parse(raw.toString("utf8")))}catch{emit("runtime_request_rejected",{operation,result:"schema_invalid",httpStatus:400,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,400,"invalid_request","configuration_invalid","LangGraph request is invalid.")}try{const result=await advanceLinearGraph(request);emit("runtime_langgraph_advance_completed",{operation,requestId:boundedId(request.requestId),result:result.state,httpStatus:200,elapsedMs:Date.now()-started,providerExecutionEntered:false});return safe(res,200,{protocolVersion:PROTOCOL_VERSION,ok:true,result})}catch{emit("runtime_langgraph_advance_failed",{operation,requestId:boundedId(request.requestId),result:"execution_failed",httpStatus:503,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,503,"execution_failed","provider_unavailable","LangGraph execution is temporarily unavailable.")}}
  if(req.method!=="POST"||path!==EXECUTE_PATH){emit("runtime_request_rejected",{operation,result:"unsupported_operation",httpStatus:404,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,404,"unsupported_operation","configuration_invalid","Runtime operation is unsupported.")}
  let request;try{request=executionSchema.parse(JSON.parse(raw.toString("utf8")))}catch{emit("runtime_request_rejected",{operation,result:"schema_invalid",httpStatus:400,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,400,"invalid_request","configuration_invalid","Runtime request is invalid.")}
  const requestId=boundedId(request.requestId),aad=`${PROTOCOL_VERSION}:${request.capability}:${request.idempotencyKey}`;let credential:string;try{credential=await decryptCredential(request.credential,privateKey,keyId,aad)}catch{emit("runtime_request_rejected",{operation,requestId,result:"credential_invalid",httpStatus:400,elapsedMs:Date.now()-started,providerExecutionEntered:false});return error(res,400,"credential_invalid","configuration_invalid","Credential envelope is invalid.")}
  emit("runtime_provider_execution_started",{operation,requestId,providerExecutionEntered:true});
  try{const outputText=await executeOpenAIAgents(request,credential,options.factories);emit("runtime_provider_execution_completed",{operation,requestId,result:"completed",httpStatus:200,elapsedMs:Date.now()-started,providerExecutionEntered:true});return safe(res,200,{protocolVersion:PROTOCOL_VERSION,ok:true,result:{state:"completed",outputText}})}
  catch(value){const failure=value instanceof RuntimeFailure?value:new RuntimeFailure("internal_error","The Agents runtime failed unexpectedly.");emit("runtime_provider_execution_failed",{operation,requestId,result:"execution_failed",failureCategory:failure.category,httpStatus:422,elapsedMs:Date.now()-started,providerExecutionEntered:true});return error(res,422,"execution_failed",failure.category,failure.safeMessage.length>512?"Runtime execution failed.":failure.safeMessage,true)}finally{credential=""}
 });server.requestTimeout=35_000;server.headersTimeout=10_000;
 return{server,keyId,replays,listen:()=>new Promise<void>((resolve,reject)=>server.listen(options.port,options.host,resolve).once("error",reject)),close:()=>new Promise<void>((resolve,reject)=>server.close(value=>value?reject(value):resolve())),shutdown(){shuttingDown=true;server.closeIdleConnections()}};
}
function startup(event:string,stage:string){process.stderr.write(`${JSON.stringify({event,protocolVersion:PROTOCOL_VERSION,stage})}\n`)}
async function main(){let authSecret:string,privateKeyPem:string;try{authSecret=secretValue("ADT_RUNTIME_AUTH_SECRET")}catch{startup("runtime_startup_failed","auth_secret_missing");return process.exit(1)}if(authSecret.length<32){startup("runtime_startup_failed","auth_secret_invalid");return process.exit(1)}try{privateKeyPem=secretValue("ADT_RUNTIME_PRIVATE_KEY")}catch{startup("runtime_startup_failed","private_key_missing");return process.exit(1)}const host=process.env.ADT_RUNTIME_HOST??"0.0.0.0",port=Number(process.env.ADT_RUNTIME_PORT??8080),revision=process.env.ADT_RUNTIME_REVISION??"development";if(!Number.isInteger(port)||port<1||port>65535||host.length>255){startup("runtime_startup_failed","listen_configuration_invalid");return process.exit(1)}let runtime;try{runtime=await createRuntimeServer({host,port,authSecret,privateKeyPem,revision})}catch(value){const stage=value instanceof Error&&["private_key_invalid","wrapping_key_derivation_failed","wrapping_key_import_failed"].includes(value.message)?value.message:"wrapping_key_import_failed";startup("runtime_startup_failed",stage);return process.exit(1)}try{await runtime.listen()}catch{startup("runtime_startup_failed","listen_failed");return process.exit(1)}process.stdout.write(`${JSON.stringify({event:"runtime_started",protocolVersion:PROTOCOL_VERSION,runtimeRevision:revision,port})}\n`);const stop=()=>{runtime.shutdown();setTimeout(()=>process.exit(0),30_000).unref();runtime.close().then(()=>process.exit(0),()=>process.exit(1))};process.once("SIGTERM",stop);process.once("SIGINT",stop)}
if(process.argv[1]===new URL(import.meta.url).pathname)void main();
