import type { AgentRuntime } from "./agent-runtime.ts";
import type { AdapterInvocation, AdapterResult, FailureCategory } from "./workflow-adapter.ts";
import { openAIResponsesOptionsSchema } from "./workflow-adapter.ts";

export const ADT_RUNTIME_PROTOCOL="adt-runtime-v1", ADT_RUNTIME_EXECUTE_PATH="/v1/executions/openai-agents", ADT_RUNTIME_READINESS_PATH="/v1/readiness";
const encoder=new TextEncoder(),MAX_RESPONSE_BYTES=300_000;
type RuntimeConfig={baseUrl?:string;authSecret?:string;wrappingPublicKey?:string};type RuntimeFetcher=(input:string,init:RequestInit)=>Promise<Response>;
export class RemoteRuntimeFailure extends Error{readonly retryable=false;readonly category:FailureCategory;readonly safeMessage:string;constructor(category:FailureCategory,safeMessage:string){super(category);this.category=category;this.safeMessage=safeMessage}}const failure=(category:FailureCategory,message:string)=>new RemoteRuntimeFailure(category,message);
const b64=(value:ArrayBuffer|Uint8Array)=>{const bytes=value instanceof Uint8Array?value:new Uint8Array(value);let s="";for(const byte of bytes)s+=String.fromCharCode(byte);return btoa(s).replaceAll("+","-").replaceAll("/","_").replace(/=+$/g,"")};
const pem=(value:string)=>Uint8Array.from(atob(value.replace(/-----[^-]+-----|\s/g,"")),c=>c.charCodeAt(0));
async function digest(value:Uint8Array|string){return b64(await crypto.subtle.digest("SHA-256",typeof value==="string"?encoder.encode(value):new Uint8Array(value).buffer))}async function hmac(secret:string,value:string){const key=await crypto.subtle.importKey("raw",encoder.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64(await crypto.subtle.sign("HMAC",key,encoder.encode(value)))}
function nonce(){return b64(crypto.getRandomValues(new Uint8Array(24)))}async function signedHeaders(secret:string,method:string,path:string,body:string){const timestamp=String(Date.now()),requestNonce=nonce(),bodyDigest=await digest(body),canonical=[ADT_RUNTIME_PROTOCOL,method,path,timestamp,requestNonce,bodyDigest].join("\n");return {"content-type":"application/json","x-adt-protocol":ADT_RUNTIME_PROTOCOL,"x-adt-timestamp":timestamp,"x-adt-nonce":requestNonce,"x-adt-content-sha256":bodyDigest,"x-adt-signature":await hmac(secret,canonical)}}
async function publicKey(config:string){const der=pem(config),key=await crypto.subtle.importKey("spki",der,{name:"RSA-OAEP",hash:"SHA-256"},false,["encrypt"]);return {key,keyId:await digest(der)}}
async function envelope(credential:string,key:CryptoKey,keyId:string,aad:string){const contentKey=await crypto.subtle.generateKey({name:"AES-GCM",length:256},true,["encrypt"]),raw=await crypto.subtle.exportKey("raw",contentKey),iv=crypto.getRandomValues(new Uint8Array(12));const ciphertext=await crypto.subtle.encrypt({name:"AES-GCM",iv,additionalData:encoder.encode(aad),tagLength:128},contentKey,encoder.encode(credential)),wrapped=await crypto.subtle.encrypt({name:"RSA-OAEP"},key,raw);return{version:1,keyId,algorithm:"RSA-OAEP-256+A256GCM",wrappedKey:b64(wrapped),nonce:b64(iv),ciphertext:b64(ciphertext)}}
async function boundedJson(response:Response){const declared=Number(response.headers.get("content-length")??0);if(declared>MAX_RESPONSE_BYTES)throw new Error();const body=await response.text();if(body.length>MAX_RESPONSE_BYTES)throw new Error();return JSON.parse(body) as any}
function configured(config:RuntimeConfig):config is Required<RuntimeConfig>{return Boolean(config.baseUrl?.trim()&&config.authSecret?.trim()&&config.wrappingPublicKey?.trim())}

/** A no-retry synchronous transport. Any uncertain execution POST outcome is terminal and ambiguous. */
export class RemoteOpenAIAgentsRuntime implements AgentRuntime{
 readonly kind="openai-agents";private readonly config:RuntimeConfig;private readonly fetcher:RuntimeFetcher;constructor(config:RuntimeConfig,fetcher:RuntimeFetcher=fetch){this.config=config;this.fetcher=fetcher}
 private base(){if(!configured(this.config))throw failure("connection_unavailable","ADT Runtime is not configured.");let url:URL;try{url=new URL(this.config.baseUrl)}catch{throw failure("configuration_invalid","ADT Runtime URL is invalid.")}if(url.protocol!=="https:"&&!(["localhost","127.0.0.1","::1"].includes(url.hostname)))throw failure("configuration_invalid","ADT Runtime requires HTTPS.");return url.toString().replace(/\/$/,"")}
 private async readiness(expectedKeyId:string){const body="",headers=await signedHeaders(this.config.authSecret!,"GET",ADT_RUNTIME_READINESS_PATH,body);let response;try{response=await this.fetcher(this.base()+ADT_RUNTIME_READINESS_PATH,{method:"GET",headers,signal:AbortSignal.timeout(5_000)})}catch{throw failure("connection_unavailable","ADT Runtime is unreachable.")}let value;try{value=await boundedJson(response)}catch{throw failure("malformed_response","ADT Runtime readiness response is malformed.")}if(!response.ok||value.protocolVersion!==ADT_RUNTIME_PROTOCOL)throw failure("configuration_invalid","ADT Runtime protocol is incompatible.");if(!Array.isArray(value.capabilities)||!value.capabilities.includes(this.kind))throw failure("connection_unavailable","ADT Runtime capability is unavailable.");if(value.credentialWrappingKeyId!==expectedKeyId)throw failure("configuration_invalid","ADT Runtime credential wrapping key does not match.")}
 async start(invocation:AdapterInvocation):Promise<AdapterResult>{if(invocation.connection.adapter!==this.kind||!invocation.connection.enabled||!invocation.connection.defaultModel?.trim())throw failure("configuration_invalid","The Agents runtime connection is invalid.");const credential=invocation.connection.credential;if(typeof credential!=="string"||!credential.trim())throw failure("connection_unavailable","Connection is not configured.");let options;try{options=openAIResponsesOptionsSchema.parse(invocation.providerOptions??{})}catch{throw failure("configuration_invalid","The Agents runtime options are invalid.")}let wrapping;try{wrapping=await publicKey(this.config.wrappingPublicKey??"")}catch{throw failure("configuration_invalid","ADT Runtime wrapping key is invalid.")}await this.readiness(wrapping.keyId);const requestId=nonce(),aad=`${ADT_RUNTIME_PROTOCOL}:${this.kind}:${invocation.idempotencyKey}`,wrapped=await envelope(credential,wrapping.key,wrapping.keyId,aad),body=JSON.stringify({protocolVersion:ADT_RUNTIME_PROTOCOL,capability:this.kind,requestId,idempotencyKey:invocation.idempotencyKey,agentName:invocation.agentName,instructions:invocation.masterPrompt,input:invocation.inputText,model:invocation.connection.defaultModel,options,credential:wrapped}),headers=await signedHeaders(this.config.authSecret!,"POST",ADT_RUNTIME_EXECUTE_PATH,body);let response;try{response=await this.fetcher(this.base()+ADT_RUNTIME_EXECUTE_PATH,{method:"POST",headers,body,signal:AbortSignal.timeout(36_000)})}catch{throw failure("provider_start_ambiguous","ADT Runtime execution outcome is unknown.")}let value;try{value=await boundedJson(response)}catch{throw failure("provider_start_ambiguous","ADT Runtime returned an ambiguous malformed response.")}if(value?.protocolVersion!==ADT_RUNTIME_PROTOCOL)throw failure("provider_start_ambiguous","ADT Runtime returned an incompatible execution response.");if(response.ok&&value?.ok===true&&value?.result?.state==="completed"&&typeof value.result.outputText==="string"&&value.result.outputText.length<=262_144)return value.result;const safe=value?.error;if(value?.ok===false&&typeof safe?.category==="string"&&typeof safe?.safeMessage==="string"&&safe?.retryable===false&&["configuration_invalid","connection_unavailable","authentication_failed","permission_denied","provider_rejected","rate_limited","provider_unavailable","provider_timeout","malformed_response","output_too_large","internal_error"].includes(safe.category))throw failure(safe.category,safe.safeMessage.slice(0,512));throw failure("provider_start_ambiguous","ADT Runtime execution response is ambiguous.")}
 async check():Promise<never>{throw failure("configuration_invalid","The Agents runtime does not expose asynchronous tasks.")}async cancel(){return "unsupported" as const}
}
