import {ANTHROPIC_API_VERSION,ANTHROPIC_ENDPOINT} from "./anthropic-models.ts";
import {anthropicMessagesOptionsSchema,ANTHROPIC_MAX_OUTPUT_TOKENS_DEFAULT,type AdapterInvocation,type AdapterResult,type AgentProviderAdapter,type ConnectionTestResult,type FailureCategory,type ProviderTransportDiagnostics} from "./workflow-adapter.ts";
import type {ConnectionDescriptor,ResolvedConnection} from "./workflow-connections.ts";
import {classifyTransportException,isLocalRuntimeTransportRejection} from "./safe-transport-exception.ts";
import {normalizeProviderSafeConfiguration,requireProviderConnectionType} from "./provider-connection-types.ts";

export const ANTHROPIC_CONNECTION_TEST_TIMEOUT_MS=10_000;
const MIN_EXECUTION_TIMEOUT_MS=600_000,MAX_EXECUTION_TIMEOUT_MS=900_000,TEST_MAX_TOKENS=8;
export function anthropicMessagesTimeoutMs(maxOutputTokens:number){const bounded=Math.max(1,Math.min(32768,maxOutputTokens));return Math.min(MAX_EXECUTION_TIMEOUT_MS,MIN_EXECUTION_TIMEOUT_MS+bounded*10)}
type Fetcher=(input:string|URL,init?:RequestInit)=>Promise<Response>;
type ProviderFailure=Error&{category:FailureCategory;transportDiagnostics?:ProviderTransportDiagnostics};
const failure=(category:FailureCategory,transportDiagnostics?:ProviderTransportDiagnostics):ProviderFailure=>Object.assign(new Error(category),{category,transportDiagnostics});
const object=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
const safeMessages:Partial<Record<FailureCategory,string>>={connection_unavailable:"Connection is not configured.",authentication_failed:"Authentication failed.",permission_denied:"Permission denied.",provider_rejected:"Configured model was rejected.",rate_limited:"Provider rate limited.",provider_unavailable:"Provider temporarily unavailable.",provider_timeout:"Connection test timed out.",malformed_response:"Provider returned an invalid response.",internal_error:"Connection test could not be completed."};
const workspaceHeaders=(configuration:ResolvedConnection["providerConfiguration"]):Record<string,string>=>{const value=normalizeProviderSafeConfiguration(requireProviderConnectionType("anthropic-messages"),configuration)?.workspaceId;return value?{"anthropic-workspace-id":value}:{}};
const safeRequestId=(value:string|null)=>value&&value.length<=255&&/^[A-Za-z0-9._:-]+$/.test(value)?value:undefined;
async function clientRequestId(invocation:AdapterInvocation){const identity=`${invocation.runId}\0${invocation.stepId}\0${invocation.iteration}\0${invocation.attempt}\0start`,digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(identity));return `adt-${[...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,"0")).join("").slice(0,40)}`}

export function extractAnthropicMessageText(response:unknown){if(!object(response)||response.type!=="message"||!Array.isArray(response.content))return undefined;const parts:string[]=[];for(const block of response.content)if(object(block)&&block.type==="text"&&typeof block.text==="string")parts.push(block.text);return parts.length?parts.join(""):undefined}

export class AnthropicMessagesAdapter implements AgentProviderAdapter{
 readonly kind="anthropic-messages";private readonly fetcher?:Fetcher;private readonly timeoutOverrideMs?:number;
 constructor(fetcher?:Fetcher,timeoutOverrideMs?:number){this.fetcher=fetcher;this.timeoutOverrideMs=timeoutOverrideMs}
 async validateConnection(descriptor:ConnectionDescriptor){return descriptor.adapter===this.kind&&descriptor.enabled&&descriptor.endpoint===ANTHROPIC_ENDPOINT&&Boolean(descriptor.defaultModel)?{ok:true as const}:{ok:false as const,safeMessage:"The Anthropic connection is not configured."}}
 private validate(invocation:AdapterInvocation){const c=invocation.connection;if(c.adapter!==this.kind||c.endpoint!==ANTHROPIC_ENDPOINT||!c.enabled||!c.defaultModel||typeof c.credential!=="string"||!c.credential.trim())throw failure("connection_unavailable");return anthropicMessagesOptionsSchema.parse(invocation.providerOptions??{})}
 private httpFailure(status:number,start=false){if(status===401)return failure("authentication_failed");if(status===403)return failure("permission_denied");if(status===429)return failure("rate_limited");if(start&&status>=500)return failure("provider_start_ambiguous");if(status>=500)return failure("provider_unavailable");return failure("provider_rejected")}
 private async request(init:RequestInit,start:boolean,diagnosticId:string,timeoutMs:number){const controller=new AbortController(),started=Date.now();let timer:ReturnType<typeof setTimeout>|undefined,timedOut=false;const diagnostic=(outcome:ProviderTransportDiagnostics["outcome"],response?:Response,exception?:ReturnType<typeof classifyTransportException>):ProviderTransportDiagnostics=>({clientRequestId:diagnosticId,requestId:response?safeRequestId(response.headers.get("request-id")):undefined,httpStatus:response?.status,elapsedMs:Math.max(0,Date.now()-started),outcome,...exception});const timeout=new Promise<never>((_,reject)=>{timer=setTimeout(()=>{timedOut=true;controller.abort();reject(failure(start?"provider_start_ambiguous":"provider_timeout",diagnostic("timeout")))},timeoutMs)});try{const response=await Promise.race([(this.fetcher??globalThis.fetch)(`${ANTHROPIC_ENDPOINT}/v1/messages`,{...init,signal:controller.signal}),timeout]);return{response,diagnostics:diagnostic("response_received",response)}}catch(error){if(object(error)&&"category" in error)throw error;const exception=classifyTransportException(error),local=isLocalRuntimeTransportRejection(exception.reason);throw failure(start?(local?"internal_error":"provider_start_ambiguous"):timedOut?"provider_timeout":"provider_unavailable",diagnostic(timedOut?"timeout":"network_error",undefined,timedOut?undefined:exception))}finally{if(timer)clearTimeout(timer)}}
 private async json(response:Response){try{const value:unknown=await response.json();if(!object(value))throw new Error();return value}catch{throw failure("malformed_response")}}
 async start(invocation:AdapterInvocation):Promise<AdapterResult>{const options=this.validate(invocation),id=await clientRequestId(invocation),body={model:invocation.connection.defaultModel,system:invocation.masterPrompt,messages:[{role:"user",content:invocation.inputText}],max_tokens:options.maxOutputTokens??ANTHROPIC_MAX_OUTPUT_TOKENS_DEFAULT};const {response,diagnostics}=await this.request({method:"POST",headers:{authorization:`Bearer ${invocation.connection.credential}`,"anthropic-version":ANTHROPIC_API_VERSION,"content-type":"application/json",...workspaceHeaders(invocation.connection.providerConfiguration)},body:JSON.stringify(body)},true,id,this.timeoutOverrideMs??anthropicMessagesTimeoutMs(body.max_tokens));if(!response.ok)throw Object.assign(this.httpFailure(response.status,true),{transportDiagnostics:diagnostics});const text=extractAnthropicMessageText(await this.json(response));if(text===undefined)throw failure("malformed_response",diagnostics);return{state:"completed",outputText:text,transportDiagnostics:diagnostics}}
 async check():Promise<never>{throw failure("configuration_invalid")}
 async cancel(){return "unsupported" as const}
 async testConnection(connection:ResolvedConnection):Promise<ConnectionTestResult>{if(connection.adapter!==this.kind||connection.endpoint!==ANTHROPIC_ENDPOINT||!connection.enabled||!connection.defaultModel||typeof connection.credential!=="string"||!connection.credential.trim())return{ok:false,category:"connection_unavailable",safeMessage:safeMessages.connection_unavailable!};try{const {response}=await this.request({method:"POST",headers:{authorization:`Bearer ${connection.credential}`,"anthropic-version":ANTHROPIC_API_VERSION,"content-type":"application/json",...workspaceHeaders(connection.providerConfiguration)},body:JSON.stringify({model:connection.defaultModel,messages:[{role:"user",content:"Reply exactly with OK."}],max_tokens:TEST_MAX_TOKENS})},false,"adt-connection-test",this.timeoutOverrideMs??ANTHROPIC_CONNECTION_TEST_TIMEOUT_MS);if(!response.ok)throw this.httpFailure(response.status);const text=extractAnthropicMessageText(await this.json(response))?.trim();if(!text)throw failure("malformed_response");return{ok:true,outputText:text.slice(0,100)}}catch(error){const category=object(error)&&typeof error.category==="string"?error.category as FailureCategory:"internal_error";return{ok:false,category,safeMessage:safeMessages[category]??safeMessages.internal_error!}}}
}
