export const ANTHROPIC_ENDPOINT="https://api.anthropic.com";
export const ANTHROPIC_API_VERSION="2023-06-01";
export const ANTHROPIC_MODELS_URL=`${ANTHROPIC_ENDPOINT}/v1/models`;
const PAGE_SIZE=100,MAX_PAGES=10,MAX_MODELS=1000;
export type AnthropicModelFailure="authentication_failed"|"permission_denied"|"rate_limited"|"provider_unavailable"|"provider_timeout"|"provider_rejected"|"malformed_response"|"model_unavailable";
export class AnthropicModelError extends Error{code:AnthropicModelFailure;constructor(code:AnthropicModelFailure){super(code);this.code=code}}
type Fetcher=typeof fetch;
const object=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
function failure(status:number,lookup=false){if(status===401)return new AnthropicModelError("authentication_failed");if(status===403)return new AnthropicModelError("permission_denied");if(status===429)return new AnthropicModelError("rate_limited");if(status>=500)return new AnthropicModelError("provider_unavailable");if(lookup&&status===404)return new AnthropicModelError("model_unavailable");return new AnthropicModelError("provider_rejected")}
async function request(url:string,credential:string,fetcher:Fetcher,timeoutMs:number){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetcher(url,{method:"GET",headers:{authorization:`Bearer ${credential}`,"anthropic-version":ANTHROPIC_API_VERSION,accept:"application/json"},signal:controller.signal})}catch(error){throw new AnthropicModelError(error instanceof DOMException&&error.name==="AbortError"?"provider_timeout":"provider_unavailable")}finally{clearTimeout(timer)}}
async function json(response:Response){try{const body:unknown=await response.json();if(!object(body))throw new Error();return body}catch{throw new AnthropicModelError("malformed_response")}}
const validId=(value:unknown):value is string=>typeof value==="string"&&value.length>0&&value.length<=120&&!/[\u0000-\u001f\u007f]/.test(value);
export async function listAnthropicModels(credential:string,fetcher:Fetcher=fetch,timeoutMs=10000){const ids:string[]=[],seen=new Set<string>();let after:string|undefined;for(let page=0;page<MAX_PAGES;page++){const url=new URL(ANTHROPIC_MODELS_URL);url.searchParams.set("limit",String(PAGE_SIZE));if(after)url.searchParams.set("after_id",after);const response=await request(url.toString(),credential,fetcher,timeoutMs);if(!response.ok)throw failure(response.status);const body=await json(response);if(!Array.isArray(body.data))throw new AnthropicModelError("malformed_response");for(const item of body.data){if(!object(item)||!validId(item.id))throw new AnthropicModelError("malformed_response");if(!seen.has(item.id)){seen.add(item.id);ids.push(item.id);if(ids.length>=MAX_MODELS)return ids}}if(body.has_more===false)return ids;if(body.has_more!==true||!validId(body.last_id)||body.last_id===after)throw new AnthropicModelError("malformed_response");after=body.last_id}throw new AnthropicModelError("malformed_response")}
export async function validateAnthropicModel(credential:string,model:string,fetcher:Fetcher=fetch,timeoutMs=10000){const response=await request(`${ANTHROPIC_MODELS_URL}/${encodeURIComponent(model)}`,credential,fetcher,timeoutMs);if(!response.ok)throw failure(response.status,true);const body=await json(response);if(body.id!==model)throw new AnthropicModelError("malformed_response")}
