import { createHmac, timingSafeEqual } from "node:crypto";
import { z } from "zod";
import type { Artifact } from "./artifact-repository.ts";
import { searchArtifacts } from "./search.ts";

export const ARTIFACT_SEARCH_LIMITS={queryCharacters:500,maxResults:10,bodyBytes:32_000,totalBytes:128_000,maxCalls:4} as const;
export const artifactSearchArgumentsSchema=z.object({query:z.string().trim().min(1).max(ARTIFACT_SEARCH_LIMITS.queryCharacters),limit:z.number().int().min(1).max(ARTIFACT_SEARCH_LIMITS.maxResults).optional()}).strict();
export type ArtifactSearchAuthority={version:1;runId:string;repositoryId:number;owner:string;repository:string;branch:string;root:string;expiresAt:number;nonce:string};
const authoritySchema=z.object({version:z.literal(1),runId:z.string().uuid(),repositoryId:z.number().int().positive(),owner:z.string().min(1).max(100),repository:z.string().min(1).max(100),branch:z.string().min(1).max(255),root:z.string().min(1).max(255),expiresAt:z.number().int(),nonce:z.string().uuid()}).strict();
const encode=(value:unknown)=>Buffer.from(JSON.stringify(value)).toString("base64url");
export function issueArtifactSearchAuthority(value:ArtifactSearchAuthority,secret:string){if(secret.length<32)throw new Error("tool_authority_secret_invalid");const payload=encode(authoritySchema.parse(value)),signature=createHmac("sha256",secret).update(payload).digest("base64url");return `${payload}.${signature}`;}
export function verifyArtifactSearchAuthority(token:string,secret:string,expectedRunId:string,now=Date.now()):ArtifactSearchAuthority{const [payload,provided,...extra]=token.split(".");if(!payload||!provided||extra.length)throw new Error("tool_authority_invalid");const expected=createHmac("sha256",secret).update(payload).digest(),actual=Buffer.from(provided,"base64url");if(expected.length!==actual.length||!timingSafeEqual(expected,actual))throw new Error("tool_authority_invalid");let value;try{value=authoritySchema.parse(JSON.parse(Buffer.from(payload,"base64url").toString("utf8")))}catch{throw new Error("tool_authority_invalid")}if(value.runId!==expectedRunId||value.expiresAt<=now)throw new Error("tool_authority_invalid");return value;}
function truncateUtf8(value:string,max:number){const bytes=Buffer.from(value,"utf8");if(bytes.length<=max)return {value,truncated:false};let end=max;while(end&&((bytes[end]&0xc0)===0x80))end--;return {value:bytes.subarray(0,end).toString("utf8"),truncated:true};}
export function boundedArtifactSearch(artifacts:readonly Artifact[],input:unknown){const {query,limit=ARTIFACT_SEARCH_LIMITS.maxResults}=artifactSearchArgumentsSchema.parse(input),matches=searchArtifacts([...artifacts],query).slice(0,limit),results:unknown[]=[];let used=Buffer.byteLength(JSON.stringify({results:[]}));for(const artifact of matches){const body=truncateUtf8(artifact.body,ARTIFACT_SEARCH_LIMITS.bodyBytes),safe={id:artifact.id,title:artifact.title,description:artifact.description,type:artifact.type,tags:artifact.tags,aliases:artifact.aliases,body:body.value,truncated:body.truncated};const size=Buffer.byteLength(JSON.stringify(safe));if(used+size>ARTIFACT_SEARCH_LIMITS.totalBytes)break;results.push(safe);used+=size;}return {results,truncated:results.length<matches.length};}

/** Process-local replay/call budget. A durable deployment may replace this with an equivalent atomic store. */
export class ArtifactSearchAuthorityBudget{private uses=new Map<string,{expiresAt:number;count:number}>();accept(authority:ArtifactSearchAuthority,now=Date.now()){for(const [nonce,value] of this.uses)if(value.expiresAt<=now)this.uses.delete(nonce);const current=this.uses.get(authority.nonce)??{expiresAt:authority.expiresAt,count:0};if(current.count>=ARTIFACT_SEARCH_LIMITS.maxCalls)throw new Error("tool_authority_replayed");current.count++;this.uses.set(authority.nonce,current);}}
