import {createCipheriv,createDecipheriv,createHash,randomBytes} from "node:crypto";
import { z } from "zod";
import type { Artifact } from "./artifact-repository.ts";
import { searchArtifacts } from "./search.ts";

export const ARTIFACT_SEARCH_LIMITS={queryCharacters:500,maxResults:10,bodyBytes:32_000,totalBytes:128_000,maxCalls:4} as const;
export const artifactSearchArgumentsSchema=z.object({query:z.string().trim().min(1).max(ARTIFACT_SEARCH_LIMITS.queryCharacters),limit:z.number().int().min(1).max(ARTIFACT_SEARCH_LIMITS.maxResults).optional()}).strict();
export type ArtifactSearchAuthority={version:1;runId:string;stepId:string;iteration:number;attempt:number;repositoryId:number;installationId:number;owner:string;repository:string;branch:string;root:string;expiresAt:number;nonce:string};
const authoritySchema=z.object({version:z.literal(1),runId:z.string().uuid(),stepId:z.string().min(1).max(80),iteration:z.number().int().positive(),attempt:z.number().int().positive(),repositoryId:z.number().int().positive(),installationId:z.number().int().positive(),owner:z.string().min(1).max(100),repository:z.string().min(1).max(100),branch:z.string().min(1).max(255),root:z.string().min(1).max(255),expiresAt:z.number().int(),nonce:z.string().uuid()}).strict();
const authorityKey=(secret:string)=>{if(secret.length<32)throw new Error("tool_authority_secret_invalid");return createHash("sha256").update(`artifact-search-authority\0${secret}`).digest();};
export function issueArtifactSearchAuthority(value:ArtifactSearchAuthority,secret:string){const nonce=randomBytes(12),cipher=createCipheriv("aes-256-gcm",authorityKey(secret),nonce);const ciphertext=Buffer.concat([cipher.update(JSON.stringify(authoritySchema.parse(value)),"utf8"),cipher.final()]);return `${nonce.toString("base64url")}.${ciphertext.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}`;}
export function verifyArtifactSearchAuthority(token:string,secret:string,expectedRunId:string,now=Date.now()):ArtifactSearchAuthority{const [nonce,ciphertext,tag,...extra]=token.split(".");if(!nonce||!ciphertext||!tag||extra.length)throw new Error("tool_authority_invalid");let value;try{const decipher=createDecipheriv("aes-256-gcm",authorityKey(secret),Buffer.from(nonce,"base64url"));decipher.setAuthTag(Buffer.from(tag,"base64url"));value=authoritySchema.parse(JSON.parse(Buffer.concat([decipher.update(Buffer.from(ciphertext,"base64url")),decipher.final()]).toString("utf8")));}catch{throw new Error("tool_authority_invalid")}if(value.runId!==expectedRunId||value.expiresAt<=now)throw new Error("tool_authority_invalid");return value;}
function truncateUtf8(value:string,max:number){const bytes=Buffer.from(value,"utf8");if(bytes.length<=max)return {value,truncated:false};let end=max;while(end&&((bytes[end]&0xc0)===0x80))end--;return {value:bytes.subarray(0,end).toString("utf8"),truncated:true};}
export function boundedArtifactSearch(artifacts:readonly Artifact[],input:unknown){const {query,limit=ARTIFACT_SEARCH_LIMITS.maxResults}=artifactSearchArgumentsSchema.parse(input),allMatches=searchArtifacts([...artifacts],query),matches=allMatches.slice(0,limit),results:unknown[]=[];let used=Buffer.byteLength(JSON.stringify({results:[]}));for(const artifact of matches){const body=truncateUtf8(artifact.body,ARTIFACT_SEARCH_LIMITS.bodyBytes),safe={id:artifact.id,title:artifact.title,description:artifact.description,type:artifact.type,tags:artifact.tags,aliases:artifact.aliases,body:body.value,truncated:body.truncated};const size=Buffer.byteLength(JSON.stringify(safe));if(used+size>ARTIFACT_SEARCH_LIMITS.totalBytes)break;results.push(safe);used+=size;}return {results,truncated:allMatches.length>matches.length||results.length<matches.length};}

/** Process-local replay/call budget. A durable deployment may replace this with an equivalent atomic store. */
export class ArtifactSearchAuthorityBudget{private uses=new Map<string,{expiresAt:number;calls:Set<string>}>();accept(authority:ArtifactSearchAuthority,callId:string,now=Date.now()){if(!/^[A-Za-z0-9_-]{1,128}$/.test(callId))throw new Error("tool_call_invalid");for(const [nonce,value] of this.uses)if(value.expiresAt<=now)this.uses.delete(nonce);const current=this.uses.get(authority.nonce)??{expiresAt:authority.expiresAt,calls:new Set<string>()};if(current.calls.has(callId)||current.calls.size>=ARTIFACT_SEARCH_LIMITS.maxCalls)throw new Error("tool_authority_replayed");current.calls.add(callId);this.uses.set(authority.nonce,current);}}
