import { z } from "zod";
import { noStoreHeaders } from "./auth-core.ts";
import { ArtifactSearchAuthorityBudget, boundedArtifactSearch, verifyArtifactSearchAuthority } from "./artifact-search-tool.ts";
import type { Artifact } from "./artifact-repository.ts";
import type { RunRepositoryContext, WorkflowRunStorage } from "./workflow-storage.ts";
import {isLegacyRunReadOnly} from "./workflow-run-legacy.ts";

const requestSchema=z.object({runId:z.string().uuid(),tool:z.literal("artifact_search"),callId:z.string().regex(/^[A-Za-z0-9_-]{1,128}$/),arguments:z.unknown()}).strict();
const sameContext=(a:RunRepositoryContext,b:RunRepositoryContext)=>a.repositoryId===b.repositoryId&&a.installationId===b.installationId&&a.owner.toLowerCase()===b.owner.toLowerCase()&&a.repository.toLowerCase()===b.repository.toLowerCase()&&a.branch===b.branch&&a.root===b.root;
const denied=()=>Response.json({error:"Artifact search authority is invalid."},{status:401,headers:noStoreHeaders});

export function createArtifactSearchGateway(dependencies:{storage:WorkflowRunStorage;secret:string;loadArtifacts:(context:RunRepositoryContext)=>Promise<readonly Artifact[]>;budget?:ArtifactSearchAuthorityBudget;now?:()=>number}){
 const budget=dependencies.budget??new ArtifactSearchAuthorityBudget();
 return async(request:Request)=>{let input:z.infer<typeof requestSchema>;try{const raw=await request.text();if(Buffer.byteLength(raw,"utf8")>2048)throw new Error();input=requestSchema.parse(JSON.parse(raw));}catch{return Response.json({error:"Artifact search request is invalid."},{status:400,headers:noStoreHeaders})}const header=request.headers.get("authorization")??"",token=header.startsWith("Bearer ")?header.slice(7):"";let authority;try{authority=verifyArtifactSearchAuthority(token,dependencies.secret,input.runId,dependencies.now?.());}catch{return denied()}const detail=await dependencies.storage.getRun(input.runId),context=detail?.run.repositoryContext,step=detail?.run.executionPlan&&"planVersion" in detail.run.executionPlan?detail.run.executionPlan.nodes.find(item=>item.id===authority.stepId&&item.blockType==="agent"):undefined,snapshot=step&&step.blockType==="agent"?detail?.run.agentSnapshots[step.config.agentId]:undefined,attempts=detail?.attempts.filter(item=>item.stepId===authority.stepId).sort((a,b)=>a.iteration-b.iteration||a.attempt-b.attempt)??[],active=attempts.at(-1),connection=active?detail?.run.connectionSnapshots[active.connectionKey]:undefined;if(!detail||detail.run.status!=="running"||detail.run.currentStepId!==authority.stepId||!context||!step||!snapshot?.tools?.includes("artifact_search")||!active||active.iteration!==authority.iteration||active.attempt!==authority.attempt||active.agentId!==(step.blockType==="agent"?step.config.agentId:"")||active.status!=="starting"||connection?.adapter!=="openai-agents"||isLegacyRunReadOnly(detail.run)||!sameContext(authority,context))return denied();try{budget.accept(authority,input.callId,dependencies.now?.());const artifacts=await dependencies.loadArtifacts(context);return Response.json(boundedArtifactSearch(artifacts,input.arguments),{headers:noStoreHeaders});}catch{return Response.json({error:"Artifact search failed safely."},{status:422,headers:noStoreHeaders})}};
}
