import type {AdapterInvocation,AgentProviderAdapter,FailureCategory} from "./workflow-adapter.ts";
import {codexRunnerOptionsSchema} from "./workflow-adapter.ts";
import type {ConnectionDescriptor} from "./workflow-connections.ts";
import {gatewayFromConnection,RunnerGatewayError,type RunnerJob} from "./codex-runner-workflow-gateway.ts";
const failure=(category:FailureCategory)=>Object.assign(new Error(category),{category});
export class CodexRunnerAdapter implements AgentProviderAdapter{
 readonly kind="codex-runner";
 async validateConnection(value:ConnectionDescriptor){return value.adapter===this.kind&&value.enabled?{ok:true as const}:{ok:false as const,safeMessage:"The Codex Runner connection is unavailable."}}
 private gateway(invocation:AdapterInvocation){if(!invocation.connection.enabled||invocation.connection.adapter!==this.kind)throw failure("connection_unavailable");return gatewayFromConnection(invocation.connection)}
 private result(job:RunnerJob):Awaited<ReturnType<AgentProviderAdapter["check"]>>{if(job.state==="queued"||job.state==="running")return{state:"pending" as const,pollAfterMs:3000};if(job.state==="completed")return{state:"completed" as const,outputText:job.outputText};return{state:"failed" as const,category:job.state==="cancelled"?"cancelled" as const:job.state==="failed"&&job.reason==="authentication_failed"?"authentication_failed" as const:"provider_rejected" as const,retryable:false,safeMessage:job.state==="cancelled"?"The Codex job was cancelled.":"The Codex job did not complete."}}
 async start(invocation:AdapterInvocation){const options=codexRunnerOptionsSchema.parse(invocation.providerOptions),prompt=`${invocation.masterPrompt}\n\nTask:\n\n${invocation.inputText}`;try{const job=await this.gateway(invocation).start({idempotencyKey:invocation.idempotencyKey,prompt,...options});if(job.state==="queued"||job.state==="running")return{state:"pending" as const,taskId:job.jobId,pollAfterMs:3000};if(job.state==="completed")return{state:"completed" as const,outputText:job.outputText};throw failure(job.state==="cancelled"?"cancelled":job.state==="failed"&&job.reason==="authentication_failed"?"authentication_failed":"provider_rejected")}catch(error){throw this.map(error)}}
 async check(taskId:string,invocation:AdapterInvocation){try{return this.result(await this.gateway(invocation).get(taskId))}catch(error){if(error instanceof RunnerGatewayError&&["runner_unavailable","invalid_response"].includes(error.code))return{state:"pending" as const,pollAfterMs:5000,providerState:"runner_status_temporarily_unavailable"};throw this.map(error)}}
 async cancel(taskId:string,invocation:AdapterInvocation){const value=await this.gateway(invocation).cancel(taskId);if(value.state==="cancellation_pending")return "cancellation_pending" as const;if(value.state==="cancelled")return "cancelled" as const;if(value.state==="completed"||value.state==="failed")return "already_terminal" as const;throw failure("malformed_response")}
 private map(error:unknown){if(error instanceof RunnerGatewayError){if(error.code==="authentication_failed")return failure("authentication_failed");if(error.code==="provider_start_ambiguous")return failure("provider_start_ambiguous");if(["runner_busy","runner_unavailable"].includes(error.code))return failure("provider_unavailable");if(["unknown_environment","environment_disabled","environment_not_ready","unknown_model","unsupported_reasoning_effort"].includes(error.code))return failure("configuration_invalid")}return failure("internal_error")}
}
