import type {ResolvedConnection} from "./workflow-connections.ts";
export type RunnerJob={jobId:string;state:"queued"|"running"}|{jobId:string;state:"completed";outputText:string}|{jobId:string;state:"failed";reason:string}|{jobId:string;state:"cancelled"};
export type RunnerEnvironmentDescriptor={key:string;name:string;enabled:boolean;ready:boolean;sandbox:"read-only"|"workspace-write"};
export type RunnerModelDescriptor={id:string;displayName:string;isDefault:boolean;defaultReasoningEffort:string;supportedReasoningEfforts:{reasoningEffort:string;description:string}[]};
export type CodexRunnerCatalog={environments:RunnerEnvironmentDescriptor[];models:RunnerModelDescriptor[]};
const digest=async(value:string)=>[...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))].map(v=>v.toString(16).padStart(2,"0")).join("");
export class RunnerGatewayError extends Error{readonly code:string;readonly ambiguous:boolean;constructor(code:string,ambiguous=false){super(code);this.code=code;this.ambiguous=ambiguous}}
export class CodexRunnerWorkflowGateway{
 private readonly configuration:{baseUrl:string;accessClientId:string;accessClientSecret:string;sharedSecret:string};private readonly fetcher:typeof fetch;constructor(configuration:{baseUrl:string;accessClientId:string;accessClientSecret:string;sharedSecret:string},fetcher:typeof fetch=fetch){this.configuration=configuration;this.fetcher=fetcher}
 private headers(){return{accept:"application/json","content-type":"application/json","CF-Access-Client-Id":this.configuration.accessClientId,"CF-Access-Client-Secret":this.configuration.accessClientSecret,"X-Codex-Runner-Secret":this.configuration.sharedSecret}}
 private async request(path:string,init:RequestInit={},ambiguous=false){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15_000);let response:Response;try{response=await this.fetcher(new URL(path,this.configuration.baseUrl),{...init,headers:{...this.headers(),...init.headers},signal:controller.signal,redirect:"manual"})}catch{throw new RunnerGatewayError("runner_unavailable",ambiguous)}finally{clearTimeout(timer)}let value:unknown;try{const text=await response.text();if(new TextEncoder().encode(text).length>300_000)throw new Error();value=JSON.parse(text)}catch{throw new RunnerGatewayError("invalid_response",ambiguous&&response.status>=500)}if(!response.ok)throw new RunnerGatewayError(response.status===401?"authentication_failed":typeof value==="object"&&value&&typeof (value as Record<string,unknown>).error==="string"?String((value as Record<string,unknown>).error):"runner_unavailable",ambiguous&&response.status>=500);return value}
 async start(input:{idempotencyKey:string;environmentKey:string;prompt:string;model?:string;reasoningEffort?:string}){try{return this.job(await this.request("/v1/jobs",{method:"POST",body:JSON.stringify(input)},true))}catch(error){if(!(error instanceof RunnerGatewayError)||!error.ambiguous)throw error;const found=await this.lookup(input.idempotencyKey).catch(()=>undefined);if(found)return found;throw new RunnerGatewayError("provider_start_ambiguous")}}
 async lookup(key:string){try{return this.job(await this.request(`/v1/jobs/by-idempotency/${await digest(key)}`))}catch(error){if(error instanceof RunnerGatewayError&&error.code==="not_found")return undefined;throw error}}
 async get(id:string){return this.job(await this.request(`/v1/jobs/${encodeURIComponent(id)}`))}
 async cancel(id:string){return this.job(await this.request(`/v1/jobs/${encodeURIComponent(id)}/cancel`,{method:"POST"}))}
 private job(value:unknown):RunnerJob{if(!value||typeof value!=="object"||Array.isArray(value))throw new RunnerGatewayError("invalid_response");const v=value as Record<string,unknown>;if(typeof v.jobId!=="string"||!/[a-f0-9]{48}/.test(v.jobId)||!['queued','running','completed','failed','cancelled'].includes(String(v.state)))throw new RunnerGatewayError("invalid_response");if(v.state==="completed"&&typeof v.outputText!=="string")throw new RunnerGatewayError("invalid_response");if(v.state==="failed"&&typeof v.reason!=="string")throw new RunnerGatewayError("invalid_response");return v as RunnerJob}
}
export function gatewayFromConnection(connection:ResolvedConnection){const value=connection.serverConfiguration as Record<string,unknown>|undefined;if(!value||typeof value.baseUrl!=="string"||typeof value.accessClientId!=="string"||typeof value.accessClientSecret!=="string"||typeof value.sharedSecret!=="string")throw new RunnerGatewayError("connection_unavailable");return new CodexRunnerWorkflowGateway(value as {baseUrl:string;accessClientId:string;accessClientSecret:string;sharedSecret:string})}
