import "server-only";

export type RunnerErrorCategory="configuration_missing"|"runner_unavailable"|"access_denied"|"runner_unauthorized"|"runner_update_required"|"invalid_response";
export type RunnerTransportReason="timeout"|"fetch_error";
export type RunnerOperationError="device_auth_start_failed"|"codex_logout_failed"|"codex_auth_unavailable";
export type DeviceAuthFailureReason="chatgpt_login_disabled"|"device_auth_not_enabled"|"device_auth_upstream_forbidden"|"device_auth_rate_limited"|"device_auth_upstream_unavailable"|"device_auth_upstream_rejected"|"device_auth_transport_error"|"device_auth_ca_configuration"|"device_auth_http_client_configuration"|"device_auth_internal"|"device_auth_unknown";
export interface RunnerFailureDetails{deviceAuthReason?:DeviceAuthFailureReason;upstreamHttpStatus?:number;jsonRpcCode?:number}
export class CodexRunnerError extends Error{constructor(public readonly category:RunnerErrorCategory,public readonly transport?:RunnerTransportReason,public readonly runnerCode?:RunnerOperationError,public readonly details:RunnerFailureDetails={}){super(category)}}
export interface CodexRunnerConfiguration{baseUrl:string;accessClientId:string;accessClientSecret:string;sharedSecret:string;production:boolean;timeoutMs?:number}
export interface RunnerCapabilities{protocolVersion:number;runnerVersion:string;codexAvailable:boolean;deviceAuth:boolean;jobExecution:boolean}
export interface RunnerAuthStatus{connected:boolean;authMode?:string;planType?:string}
export interface RunnerDeviceCeremony{loginId:string;verificationUrl:string;userCode:string}
export interface RunnerAuthEnvironmentDiagnostics{runnerReachable:true;codexAppServerReady:boolean;customCaSource:"none"|"codex_ca_certificate"|"ssl_cert_file";customCaFileReadable?:boolean;httpProxyConfigured:boolean;httpsProxyConfigured:boolean;allProxyConfigured:boolean;noProxyConfigured:boolean;dnsResolution:"ok"|"failed";ipv4Available:boolean;ipv6Available:boolean;ipv4TcpConnectivity:"ok"|"timeout"|"failed"|"unavailable";ipv6TcpConnectivity:"ok"|"timeout"|"failed"|"unavailable";ipv4TlsConnectivity:"ok"|"timeout"|"failed"|"unavailable";ipv6TlsConnectivity:"ok"|"timeout"|"failed"|"unavailable";httpsResponseReceived:boolean;httpsStatus?:number;httpsMitigationChallenge:boolean;tcpConnectivity:"ok"|"timeout"|"failed";codexHomeReadable:boolean;codexHomeWritable:boolean}
const MAX_RESPONSE_BYTES=32_768;
const SAFE_RUNNER_ERRORS=new Set<RunnerOperationError>(["device_auth_start_failed","codex_logout_failed","codex_auth_unavailable"]);
const SAFE_DEVICE_AUTH_REASONS=new Set<DeviceAuthFailureReason>(["chatgpt_login_disabled","device_auth_not_enabled","device_auth_upstream_forbidden","device_auth_rate_limited","device_auth_upstream_unavailable","device_auth_upstream_rejected","device_auth_transport_error","device_auth_ca_configuration","device_auth_http_client_configuration","device_auth_internal","device_auth_unknown"]);

export function readCodexRunnerConfiguration(environment:Record<string,string|undefined>=process.env):CodexRunnerConfiguration{
 const values=[environment.CODEX_RUNNER_BASE_URL,environment.CODEX_RUNNER_ACCESS_CLIENT_ID,environment.CODEX_RUNNER_ACCESS_CLIENT_SECRET,environment.CODEX_RUNNER_SHARED_SECRET];
 if(values.every(v=>!v))throw new CodexRunnerError("configuration_missing");if(values.some(v=>!v))throw new CodexRunnerError("configuration_missing");
 return{baseUrl:values[0]!,accessClientId:values[1]!,accessClientSecret:values[2]!,sharedSecret:values[3]!,production:environment.NODE_ENV==="production"};
}
function requiredString(value:unknown){return typeof value==="string"&&value.length>0?value:undefined}
export class CodexRunnerClient{
 private readonly baseUrl:URL;
 constructor(private readonly configuration:CodexRunnerConfiguration,private readonly fetcher:typeof fetch=fetch){this.baseUrl=new URL(configuration.baseUrl);if(configuration.production&&this.baseUrl.protocol!=="https:")throw new CodexRunnerError("configuration_missing");}
 private async request(path:string,method="GET"){const controller=new AbortController();let timedOut=false;const timer=setTimeout(()=>{timedOut=true;controller.abort()},this.configuration.timeoutMs??8_000);let response:Response;try{response=await this.fetcher(new URL(path,this.baseUrl),{method,headers:{accept:"application/json","content-type":"application/json","CF-Access-Client-Id":this.configuration.accessClientId,"CF-Access-Client-Secret":this.configuration.accessClientSecret,"X-Codex-Runner-Secret":this.configuration.sharedSecret},signal:controller.signal,redirect:"manual"});}catch{throw new CodexRunnerError("runner_unavailable",timedOut?"timeout":"fetch_error")}finally{clearTimeout(timer)}
  const accessMetadata=response.headers.has("cf-ray")||response.headers.has("cf-access-domain");if(response.status>=300&&response.status<400)throw new CodexRunnerError(accessMetadata?"access_denied":"invalid_response");if(response.status===401||response.status===403)throw new CodexRunnerError(accessMetadata?"access_denied":"runner_unauthorized");const length=Number(response.headers.get("content-length")??0);if(length>MAX_RESPONSE_BYTES)throw new CodexRunnerError(response.ok?"invalid_response":"runner_unavailable");const text=await response.text();if(Buffer.byteLength(text)>MAX_RESPONSE_BYTES)throw new CodexRunnerError(response.ok?"invalid_response":"runner_unavailable");if(!response.ok){let runnerCode:RunnerOperationError|undefined,details:RunnerFailureDetails={};try{const value=JSON.parse(text) as Record<string,unknown>,code=value.error;if(typeof code==="string"&&SAFE_RUNNER_ERRORS.has(code as RunnerOperationError))runnerCode=code as RunnerOperationError;if(runnerCode==="device_auth_start_failed"&&typeof value.deviceAuthReason==="string"&&SAFE_DEVICE_AUTH_REASONS.has(value.deviceAuthReason as DeviceAuthFailureReason)){details={deviceAuthReason:value.deviceAuthReason as DeviceAuthFailureReason,...(Number.isInteger(value.upstreamHttpStatus)&&Number(value.upstreamHttpStatus)>=100&&Number(value.upstreamHttpStatus)<=599?{upstreamHttpStatus:Number(value.upstreamHttpStatus)}:{}),...(Number.isInteger(value.jsonRpcCode)&&Number.isFinite(value.jsonRpcCode)?{jsonRpcCode:Number(value.jsonRpcCode)}:{})}}}catch{/* Malformed remote errors remain generic. */}throw new CodexRunnerError("runner_unavailable",undefined,runnerCode,details)}try{return JSON.parse(text) as unknown}catch{throw new CodexRunnerError("invalid_response")}}
 async capabilities():Promise<RunnerCapabilities>{const value=await this.request("/v1/capabilities") as Partial<RunnerCapabilities>;if(value.protocolVersion!==1)throw new CodexRunnerError("runner_update_required");if(!requiredString(value.runnerVersion)||typeof value.codexAvailable!=="boolean"||typeof value.deviceAuth!=="boolean"||typeof value.jobExecution!=="boolean")throw new CodexRunnerError("invalid_response");return value as RunnerCapabilities}
 async authStatus():Promise<RunnerAuthStatus>{const value=await this.request("/v1/auth/status") as Partial<RunnerAuthStatus>;if(typeof value.connected!=="boolean")throw new CodexRunnerError("invalid_response");return{connected:value.connected,...(requiredString(value.authMode)?{authMode:value.authMode}:{}),...(requiredString(value.planType)?{planType:value.planType}:{})}}
 async authEnvironmentDiagnostics():Promise<RunnerAuthEnvironmentDiagnostics>{const value=await this.request("/v1/diagnostics/auth-environment") as Partial<RunnerAuthEnvironmentDiagnostics>;const ca=value.customCaSource,tcp=value.tcpConnectivity,dns=value.dnsResolution,connectivity=[value.ipv4TcpConnectivity,value.ipv6TcpConnectivity,value.ipv4TlsConnectivity,value.ipv6TlsConnectivity],booleans=[value.codexAppServerReady,value.httpProxyConfigured,value.httpsProxyConfigured,value.allProxyConfigured,value.noProxyConfigured,value.ipv4Available,value.ipv6Available,value.httpsResponseReceived,value.httpsMitigationChallenge,value.codexHomeReadable,value.codexHomeWritable];if(value.runnerReachable!==true||!(ca==="none"||ca==="codex_ca_certificate"||ca==="ssl_cert_file")||!(dns==="ok"||dns==="failed")||!(tcp==="ok"||tcp==="timeout"||tcp==="failed")||connectivity.some(item=>!(item==="ok"||item==="timeout"||item==="failed"||item==="unavailable"))||booleans.some(item=>typeof item!=="boolean")||(value.httpsStatus!==undefined&&(!Number.isInteger(value.httpsStatus)||value.httpsStatus<100||value.httpsStatus>599))||(value.httpsResponseReceived?value.httpsStatus===undefined:value.httpsStatus!==undefined)||(ca==="none"?value.customCaFileReadable!==undefined:typeof value.customCaFileReadable!=="boolean"))throw new CodexRunnerError("invalid_response");return{runnerReachable:true,codexAppServerReady:value.codexAppServerReady!,customCaSource:ca,...(ca!=="none"?{customCaFileReadable:value.customCaFileReadable}:{}),httpProxyConfigured:value.httpProxyConfigured!,httpsProxyConfigured:value.httpsProxyConfigured!,allProxyConfigured:value.allProxyConfigured!,noProxyConfigured:value.noProxyConfigured!,dnsResolution:dns,ipv4Available:value.ipv4Available!,ipv6Available:value.ipv6Available!,ipv4TcpConnectivity:value.ipv4TcpConnectivity!,ipv6TcpConnectivity:value.ipv6TcpConnectivity!,ipv4TlsConnectivity:value.ipv4TlsConnectivity!,ipv6TlsConnectivity:value.ipv6TlsConnectivity!,httpsResponseReceived:value.httpsResponseReceived!,...(value.httpsStatus!==undefined?{httpsStatus:value.httpsStatus}:{}),httpsMitigationChallenge:value.httpsMitigationChallenge!,tcpConnectivity:tcp,codexHomeReadable:value.codexHomeReadable!,codexHomeWritable:value.codexHomeWritable!}}
 async startDeviceAuth():Promise<RunnerDeviceCeremony>{const value=await this.request("/v1/auth/device/start","POST") as Partial<RunnerDeviceCeremony>;if(!requiredString(value.loginId)||!requiredString(value.verificationUrl)||!requiredString(value.userCode))throw new CodexRunnerError("invalid_response");try{const url=new URL(value.verificationUrl!);if(url.protocol!=="https:"||!(url.hostname==="openai.com"||url.hostname.endsWith(".openai.com")))throw new Error()}catch{throw new CodexRunnerError("invalid_response")}return value as RunnerDeviceCeremony}
 async logout(){await this.request("/v1/auth/logout","POST");return{connected:false as const}}
}
export function getCodexRunnerClient(environment:Record<string,string|undefined>=process.env){return new CodexRunnerClient(readCodexRunnerConfiguration(environment))}
