import {type ConnectionDescriptor,type ResolvedConnection} from "./workflow-connections.ts";
import type {WorkflowConnectionDefinitionRepository} from "./workflow-connection-definition-repository.ts";
import type {WorkflowProviderConnectionStore} from "./workflow-provider-connection-store.ts";
import type {D1ProviderCredentialVault} from "./provider-credential-vault.ts";
import {requireProviderConnectionType,isExecutableGitProviderAdapter,type ProviderConnectionTypePolicy} from "./provider-connection-types.ts";
import {resolveAuthenticationForExecution,resolveAuthenticationForReadiness} from "./provider-authentication-lifecycle.ts";
import {parseWorkIqPrivateBundle,resolveWorkIqConnection} from "./work-iq-auth.ts";

type VersionedConnection=Awaited<ReturnType<WorkflowConnectionDefinitionRepository["listConnections"]>>[number];
export async function validateProviderConnectionReadiness(policy:ProviderConnectionTypePolicy,credential:string,model:string|undefined,configuration:ConnectionDescriptor["providerConfiguration"],validateModel:(credential:string,model:string,connectionType?:string,configuration?:ConnectionDescriptor["providerConfiguration"])=>Promise<void>){if(policy.model.required){if(!model)throw new Error("model_required");await validateModel(credential,model,policy.id,configuration)}}
export async function resolveApiKeySnapshotCredential(key:string,snapshot:ConnectionDescriptor,vault?:Pick<D1ProviderCredentialVault,"resolve">,policy?:ProviderConnectionTypePolicy):Promise<ResolvedConnection>{const type=policy??requireProviderConnectionType(snapshot.adapter);if(type.id!==snapshot.adapter||type.authentication!=="api-key")throw new Error("authentication_lifecycle_unsupported");if(snapshot.management!=="git"||snapshot.key!==key||snapshot.credentialSource!=="adt-vault"||!snapshot.credentialSecretRef||!vault||!isExecutableGitProviderAdapter(snapshot.adapter))throw new Error("connection_unavailable");try{return{...snapshot,enabled:true,credential:await vault.resolve(snapshot.credentialSecretRef)}}catch{throw new Error("connection_unavailable")}}
export class GitAuthoritativeWorkflowProviderConnectionStore implements WorkflowProviderConnectionStore{
 private git:WorkflowConnectionDefinitionRepository;private validateModel:(credential:string,model:string,connectionType?:string,configuration?:ConnectionDescriptor["providerConfiguration"])=>Promise<void>;private vault:Pick<D1ProviderCredentialVault,"resolve"|"resolveWithRevision"|"replaceIfRevision">;
 constructor(git:WorkflowConnectionDefinitionRepository,validateModel:(credential:string,model:string,connectionType?:string,configuration?:ConnectionDescriptor["providerConfiguration"])=>Promise<void>,vault:Pick<D1ProviderCredentialVault,"resolve"|"resolveWithRevision"|"replaceIfRevision">){this.git=git;this.validateModel=validateModel;this.vault=vault;}
 private descriptor(value:VersionedConnection,ready:boolean,configured=ready):ConnectionDescriptor{const type=requireProviderConnectionType(value.definition.runtime);return{key:value.definition.id,name:value.definition.name,adapter:type.id,endpoint:type.endpoint,...(value.definition.model?{defaultModel:value.definition.model}:{}),...(type.safeConfiguration.forExecution&&value.definition.configuration?{providerConfiguration:value.definition.configuration}:{}),enabled:ready,configured,management:"git",credentialSource:"adt-vault",credentialSecretRef:value.definition.credential.secretRef,repositoryRevision:value.fileSha,capabilities:type.capabilities}}
 private async safe(value:VersionedConnection){const type=requireProviderConnectionType(value.definition.runtime);if(type.id==="work-iq-rest"){let configured=false,authorizationContextId:string|undefined;try{const bundle=parseWorkIqPrivateBundle(await this.vault.resolve(value.definition.credential.secretRef));configured=Boolean(bundle.clientSecret);authorizationContextId=bundle.authorizationContextId}catch{}return{...this.descriptor(value,Boolean(configured&&authorizationContextId),configured),...(authorizationContextId?{authorizationContextId}:{})}}let ready=false,configured=false;try{const descriptor=this.descriptor(value,false),resolved=await resolveAuthenticationForReadiness(type,()=>resolveApiKeySnapshotCredential(value.definition.id,descriptor,this.vault));configured=true;await validateProviderConnectionReadiness(type,resolved.credential!,value.definition.model,descriptor.providerConfiguration,this.validateModel);ready=true}catch{ready=false}return this.descriptor(value,ready,configured)}
 async listSafeDescriptors(){return Promise.all((await this.git.listConnections()).map(item=>this.safe(item)))}
 async getSafeDescriptor(key:string){const value=await this.git.getConnection(key);return value?this.safe(value):undefined}
 async resolveForExecution(key:string,snapshot?:ConnectionDescriptor){if(snapshot){const type=requireProviderConnectionType(snapshot.adapter);if(type.id==="work-iq-rest")return resolveWorkIqConnection(key,snapshot,this.vault);return resolveAuthenticationForExecution(type,()=>resolveApiKeySnapshotCredential(key,snapshot,this.vault))}const value=await this.git.getConnection(key);if(!value)throw new Error("connection_unavailable");if(value.definition.runtime==="work-iq-rest"){const safe=await this.safe(value);if(!safe.enabled)throw new Error("connection_unavailable");return resolveWorkIqConnection(key,safe,this.vault)}const descriptor=this.descriptor(value,true);return resolveAuthenticationForExecution(requireProviderConnectionType(value.definition.runtime),()=>resolveApiKeySnapshotCredential(key,descriptor,this.vault))}
}
