import {type ConnectionDescriptor,type ResolvedConnection} from "./workflow-connections.ts";
import type {WorkflowConnectionDefinitionRepository} from "./workflow-connection-definition-repository.ts";
import type {WorkflowProviderConnectionStore} from "./workflow-provider-connection-store.ts";
import type {D1ProviderCredentialVault} from "./provider-credential-vault.ts";
import {requireProviderConnectionType,isExecutableGitProviderAdapter,type ProviderConnectionTypePolicy} from "./provider-connection-types.ts";
import {resolveAuthenticationForExecution,resolveAuthenticationForReadiness} from "./provider-authentication-lifecycle.ts";

type VersionedConnection=Awaited<ReturnType<WorkflowConnectionDefinitionRepository["listConnections"]>>[number];
export async function validateProviderConnectionReadiness(policy:ProviderConnectionTypePolicy,credential:string,model:string|undefined,validateModel:(credential:string,model:string,connectionType?:string)=>Promise<void>){if(policy.model.required){if(!model)throw new Error("model_required");await validateModel(credential,model,policy.id)}}
export async function resolveApiKeySnapshotCredential(key:string,snapshot:ConnectionDescriptor,vault?:Pick<D1ProviderCredentialVault,"resolve">,policy?:ProviderConnectionTypePolicy):Promise<ResolvedConnection>{const type=policy??requireProviderConnectionType(snapshot.adapter);if(type.id!==snapshot.adapter||type.authentication!=="api-key")throw new Error("authentication_lifecycle_unsupported");if(snapshot.management!=="git"||snapshot.key!==key||snapshot.credentialSource!=="adt-vault"||!snapshot.credentialSecretRef||!vault||!isExecutableGitProviderAdapter(snapshot.adapter))throw new Error("connection_unavailable");try{return{...snapshot,enabled:true,credential:await vault.resolve(snapshot.credentialSecretRef)}}catch{throw new Error("connection_unavailable")}}
export class GitAuthoritativeWorkflowProviderConnectionStore implements WorkflowProviderConnectionStore{
 private git:WorkflowConnectionDefinitionRepository;private validateModel:(credential:string,model:string,connectionType?:string)=>Promise<void>;private vault:Pick<D1ProviderCredentialVault,"resolve">;
 constructor(git:WorkflowConnectionDefinitionRepository,validateModel:(credential:string,model:string,connectionType?:string)=>Promise<void>,vault:Pick<D1ProviderCredentialVault,"resolve">){this.git=git;this.validateModel=validateModel;this.vault=vault;}
 private descriptor(value:VersionedConnection,ready:boolean,configured=ready):ConnectionDescriptor{const type=requireProviderConnectionType(value.definition.runtime);return{key:value.definition.id,name:value.definition.name,adapter:type.id,endpoint:type.endpoint,...(value.definition.model?{defaultModel:value.definition.model}:{}),...(type.safeConfiguration.forExecution&&value.definition.configuration?{providerConfiguration:value.definition.configuration}:{}),enabled:ready,configured,management:"git",credentialSource:"adt-vault",credentialSecretRef:value.definition.credential.secretRef,repositoryRevision:value.fileSha,capabilities:type.capabilities}}
 private async safe(value:VersionedConnection){let ready=false,configured=false;try{const type=requireProviderConnectionType(value.definition.runtime),resolved=await resolveAuthenticationForReadiness(type,()=>resolveApiKeySnapshotCredential(value.definition.id,this.descriptor(value,false),this.vault));configured=true;await validateProviderConnectionReadiness(type,resolved.credential!,value.definition.model,this.validateModel);ready=true}catch{ready=false}return this.descriptor(value,ready,configured)}
 async listSafeDescriptors(){return Promise.all((await this.git.listConnections()).map(item=>this.safe(item)))}
 async getSafeDescriptor(key:string){const value=await this.git.getConnection(key);return value?this.safe(value):undefined}
 async resolveForExecution(key:string,snapshot?:ConnectionDescriptor){if(snapshot)return resolveAuthenticationForExecution(requireProviderConnectionType(snapshot.adapter),()=>resolveApiKeySnapshotCredential(key,snapshot,this.vault));const value=await this.git.getConnection(key);if(!value)throw new Error("connection_unavailable");const descriptor=this.descriptor(value,true);return resolveAuthenticationForExecution(requireProviderConnectionType(value.definition.runtime),()=>resolveApiKeySnapshotCredential(key,descriptor,this.vault))}
}
