import {githubHeaders} from "./github-app.ts";

const OWNER=/^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})$/,REPO=/^[A-Za-z0-9._-]{1,100}$/,BRANCH=/^adt\/codex\/[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/;
export type ManagedPullRequest={number:number;url:string;branch:string;baseBranch:string;draft:boolean;state:"open"|"closed"};
export class GitHubPullRequestError extends Error{constructor(readonly category:"permission_denied"|"not_found"|"conflict"|"rate_limited"|"temporarily_unavailable"|"malformed_response"){super(`github_pull_request_${category}`)}}
function target(owner:string,repo:string,branch:string){if(!OWNER.test(owner)||!REPO.test(repo)||repo==="."||repo===".."||!BRANCH.test(branch))throw new GitHubPullRequestError("not_found");return{owner,repo,branch}}
function parse(value:unknown,expected:{branch:string;baseBranch:string}):ManagedPullRequest{const v=value as Record<string,unknown>,head=v?.head as Record<string,unknown>,base=v?.base as Record<string,unknown>;if(!Number.isSafeInteger(v?.number)||Number(v.number)<1||typeof v.html_url!=="string"||typeof v.draft!=="boolean"||(v.state!=="open"&&v.state!=="closed")||head?.ref!==expected.branch||base?.ref!==expected.baseBranch)throw new GitHubPullRequestError("malformed_response");let url:URL;try{url=new URL(v.html_url)}catch{throw new GitHubPullRequestError("malformed_response")}if(url.protocol!=="https:"||url.hostname!=="github.com")throw new GitHubPullRequestError("malformed_response");return{number:Number(v.number),url:url.toString(),branch:expected.branch,baseBranch:expected.baseBranch,draft:v.draft,state:v.state}}
async function request(fetcher:typeof fetch,url:string,token:string,init:RequestInit={}){let response:Response;try{response=await fetcher(url,{...init,headers:{...githubHeaders(token),"content-type":"application/json",...init.headers}})}catch{throw new GitHubPullRequestError("temporarily_unavailable")}if(!response.ok){const category=response.status===401||response.status===403?"permission_denied":response.status===404?"not_found":response.status===409||response.status===422?"conflict":response.status===429?"rate_limited":response.status>=500?"temporarily_unavailable":"malformed_response";throw new GitHubPullRequestError(category)}try{return await response.json()}catch{throw new GitHubPullRequestError("malformed_response")}}
export class GitHubPullRequestClient{constructor(private fetcher:typeof fetch=fetch){}async find(input:{owner:string;repo:string;branch:string;baseBranch:string;token:string}){const t=target(input.owner,input.repo,input.branch),url=new URL(`https://api.github.com/repos/${encodeURIComponent(t.owner)}/${encodeURIComponent(t.repo)}/pulls`);url.searchParams.set("state","open");url.searchParams.set("head",`${t.owner}:${t.branch}`);url.searchParams.set("base",input.baseBranch);const value=await request(this.fetcher,url.toString(),input.token);if(!Array.isArray(value)||value.length>100)throw new GitHubPullRequestError("malformed_response");return value.length?parse(value[0],input):undefined}async create(input:{owner:string;repo:string;branch:string;baseBranch:string;title:string;body:string;draft:boolean;token:string}){const t=target(input.owner,input.repo,input.branch);if(!input.title.trim()||input.title.length>256||input.body.length>65536)throw new GitHubPullRequestError("malformed_response");return parse(await request(this.fetcher,`https://api.github.com/repos/${encodeURIComponent(t.owner)}/${encodeURIComponent(t.repo)}/pulls`,input.token,{method:"POST",body:JSON.stringify({title:input.title.trim(),body:input.body,head:t.branch,base:input.baseBranch,draft:input.draft})}),input)}async update(input:{owner:string;repo:string;branch:string;baseBranch:string;number:number;title:string;body:string;draft:boolean;token:string}){const t=target(input.owner,input.repo,input.branch);if(!Number.isSafeInteger(input.number)||input.number<1||!input.title.trim()||input.title.length>256||input.body.length>65536)throw new GitHubPullRequestError("malformed_response");const current=parse(await request(this.fetcher,`https://api.github.com/repos/${encodeURIComponent(t.owner)}/${encodeURIComponent(t.repo)}/pulls/${input.number}`,input.token),input);if(current.branch!==t.branch||current.baseBranch!==input.baseBranch)throw new GitHubPullRequestError("conflict");return parse(await request(this.fetcher,`https://api.github.com/repos/${encodeURIComponent(t.owner)}/${encodeURIComponent(t.repo)}/pulls/${input.number}`,input.token,{method:"PATCH",body:JSON.stringify({title:input.title.trim(),body:input.body,...(current.draft&&!input.draft?{draft:false}:{})})}),input)}async createOrUpdate(input:{owner:string;repo:string;branch:string;baseBranch:string;title:string;body:string;draft:boolean;token:string}){const existing=await this.find(input);return existing?{pullRequest:await this.update({...input,number:existing.number}),created:false}:{pullRequest:await this.create(input),created:true}}}
