import {githubHeaders} from "./github-app.ts";

const OWNER=/^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})$/;
const REPO=/^[A-Za-z0-9._-]{1,100}$/;
const BRANCH=/^adt\/codex\/[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/;
const NODE_ID=/^[A-Za-z0-9_=-]{8,200}$/;
export type ManagedPullRequest={number:number;url:string;branch:string;baseBranch:string;draft:boolean;state:"open"|"closed"};
type InternalPullRequest=ManagedPullRequest&{nodeId:string};
type Failure="permission_denied"|"not_found"|"conflict"|"rate_limited"|"temporarily_unavailable"|"malformed_response";
export class GitHubPullRequestError extends Error{
 readonly category:Failure;
 constructor(category:Failure){super(`github_pull_request_${category}`);this.category=category}
}
function target(owner:string,repo:string,branch:string){if(!OWNER.test(owner)||!REPO.test(repo)||repo==="."||repo===".."||!BRANCH.test(branch))throw new GitHubPullRequestError("not_found");return{owner,repo,branch}}
function parse(value:unknown,expected:{branch:string;baseBranch:string}):InternalPullRequest{const v=value as Record<string,unknown>,head=v?.head as Record<string,unknown>,base=v?.base as Record<string,unknown>;if(!Number.isSafeInteger(v?.number)||Number(v.number)<1||typeof v.html_url!=="string"||typeof v.draft!=="boolean"||(v.state!=="open"&&v.state!=="closed")||head?.ref!==expected.branch||base?.ref!==expected.baseBranch||typeof v.node_id!=="string"||!NODE_ID.test(v.node_id))throw new GitHubPullRequestError("malformed_response");let url:URL;try{url=new URL(v.html_url)}catch{throw new GitHubPullRequestError("malformed_response")}if(url.protocol!=="https:"||url.hostname!=="github.com")throw new GitHubPullRequestError("malformed_response");return{number:Number(v.number),url:url.toString(),branch:expected.branch,baseBranch:expected.baseBranch,draft:v.draft,state:v.state,nodeId:v.node_id}}
function category(status:number):Failure{return status===401||status===403?"permission_denied":status===404?"not_found":status===409||status===422?"conflict":status===429?"rate_limited":status>=500?"temporarily_unavailable":"malformed_response"}
async function request(fetcher:typeof fetch,url:string,token:string,init:RequestInit={}){let response:Response;try{response=await fetcher(url,{...init,headers:{...githubHeaders(token),"content-type":"application/json",...init.headers}})}catch{throw new GitHubPullRequestError("temporarily_unavailable")}if(!response.ok)throw new GitHubPullRequestError(category(response.status));try{return await response.json()}catch{throw new GitHubPullRequestError("malformed_response")}}
function safe(value:InternalPullRequest):ManagedPullRequest{return{number:value.number,url:value.url,branch:value.branch,baseBranch:value.baseBranch,draft:value.draft,state:value.state}}
export class GitHubPullRequestClient{
 private fetcher:typeof fetch;
 constructor(fetcher:typeof fetch=fetch){this.fetcher=fetcher}
 private async transition(current:InternalPullRequest,draft:boolean,token:string){if(current.draft===draft)return current;const mutation=draft?"convertPullRequestToDraft":"markPullRequestReadyForReview",field=draft?"convertPullRequestToDraft":"markPullRequestReadyForReview",query=`mutation($id:ID!){${mutation}(input:{pullRequestId:$id}){pullRequest{id isDraft}}}`;const raw=await request(this.fetcher,"https://api.github.com/graphql",token,{method:"POST",body:JSON.stringify({query,variables:{id:current.nodeId}})}) as Record<string,unknown>,errors=raw?.errors;if(Array.isArray(errors)&&errors.length){const codes=errors.map(value=>String((value as {extensions?:{type?:unknown;code?:unknown}})?.extensions?.type??(value as {extensions?:{code?:unknown}})?.extensions?.code??""));if(codes.some(value=>value==="RATE_LIMITED"||value==="RATE_LIMIT"))throw new GitHubPullRequestError("rate_limited");if(codes.some(value=>value==="FORBIDDEN"||value==="UNAUTHORIZED"))throw new GitHubPullRequestError("permission_denied");throw new GitHubPullRequestError("malformed_response")}const data=raw?.data as Record<string,unknown>,payload=data?.[field] as Record<string,unknown>,pullRequest=payload?.pullRequest as Record<string,unknown>;if(!pullRequest||pullRequest.id!==current.nodeId||pullRequest.isDraft!==draft)throw new GitHubPullRequestError("malformed_response");return{...current,draft}}
 async find(input:{owner:string;repo:string;branch:string;baseBranch:string;token:string}){const t=target(input.owner,input.repo,input.branch),url=new URL(`https://api.github.com/repos/${encodeURIComponent(t.owner)}/${encodeURIComponent(t.repo)}/pulls`);url.searchParams.set("state","open");url.searchParams.set("head",`${t.owner}:${t.branch}`);url.searchParams.set("base",input.baseBranch);const value=await request(this.fetcher,url.toString(),input.token);if(!Array.isArray(value)||value.length>100)throw new GitHubPullRequestError("malformed_response");return value.length?parse(value[0],input):undefined}
 async create(input:{owner:string;repo:string;branch:string;baseBranch:string;title:string;body:string;draft:boolean;token:string}){const t=target(input.owner,input.repo,input.branch);if(!input.title.trim()||input.title.length>256||input.body.length>65536)throw new GitHubPullRequestError("malformed_response");return safe(parse(await request(this.fetcher,`https://api.github.com/repos/${encodeURIComponent(t.owner)}/${encodeURIComponent(t.repo)}/pulls`,input.token,{method:"POST",body:JSON.stringify({title:input.title.trim(),body:input.body,head:t.branch,base:input.baseBranch,draft:input.draft})}),input))}
 async update(input:{owner:string;repo:string;branch:string;baseBranch:string;number:number;title:string;body:string;draft:boolean;token:string}){const t=target(input.owner,input.repo,input.branch);if(!Number.isSafeInteger(input.number)||input.number<1||!input.title.trim()||input.title.length>256||input.body.length>65536)throw new GitHubPullRequestError("malformed_response");const current=parse(await request(this.fetcher,`https://api.github.com/repos/${encodeURIComponent(t.owner)}/${encodeURIComponent(t.repo)}/pulls/${input.number}`,input.token),input);const updated=parse(await request(this.fetcher,`https://api.github.com/repos/${encodeURIComponent(t.owner)}/${encodeURIComponent(t.repo)}/pulls/${input.number}`,input.token,{method:"PATCH",body:JSON.stringify({title:input.title.trim(),body:input.body})}),input);if(updated.nodeId!==current.nodeId)throw new GitHubPullRequestError("malformed_response");return safe(await this.transition(updated,input.draft,input.token))}
 async createOrUpdate(input:{owner:string;repo:string;branch:string;baseBranch:string;title:string;body:string;draft:boolean;token:string}){const existing=await this.find(input);return existing?{pullRequest:await this.update({...input,number:existing.number}),created:false}:{pullRequest:await this.create(input),created:true}}
}
