export type InfrastructureComponent="worker"|"runtime"|"runner";
export type InfrastructureComponentFreshnessState="current"|"superseded"|"unknown";
export type InfrastructureFreshnessState=InfrastructureComponentFreshnessState;
export const infrastructureFreshnessUnknownReasons=["revision_unavailable","release_revision_unavailable","release_revision_newer","observation_timeout","observation_unavailable"] as const;
export type InfrastructureFreshnessUnknownReason=typeof infrastructureFreshnessUnknownReasons[number];
export type InfrastructureComponentFreshness={state:InfrastructureComponentFreshnessState;deployedRevision?:string;deployedReleaseRevision?:number;expectedReleaseRevision?:number;unknownReason?:InfrastructureFreshnessUnknownReason};
export type InfrastructureFreshnessSnapshot={state:InfrastructureFreshnessState;checkedAt:string;components:Record<InfrastructureComponent,InfrastructureComponentFreshness>};
const componentKeys:InfrastructureComponent[]=["worker","runtime","runner"],componentStates=new Set<InfrastructureComponentFreshnessState>(["current","superseded","unknown"]),fullSha=/^[0-9a-f]{40}$/i,unknownReasons=new Set<string>(infrastructureFreshnessUnknownReasons),integer=(value:unknown)=>Number.isInteger(value)&&Number(value)>=1&&Number(value)<=1_000_000;
export const INFRASTRUCTURE_FRESHNESS_SERVER_TIMEOUT_MS=3_500,INFRASTRUCTURE_FRESHNESS_CLIENT_TIMEOUT_MS=5_000,INFRASTRUCTURE_FRESHNESS_CLIENT_TTL_MS=2*60_000,INFRASTRUCTURE_FRESHNESS_UNKNOWN_CLIENT_TTL_MS=15_000,INFRASTRUCTURE_FRESHNESS_SERVER_CACHE_MS=60_000,INFRASTRUCTURE_FRESHNESS_UNKNOWN_SERVER_CACHE_MS=15_000;
export const infrastructureFreshnessHasUnknownComponent=(snapshot:InfrastructureFreshnessSnapshot)=>componentKeys.some(component=>snapshot.components[component].state==="unknown");
export const infrastructureFreshnessClientTtl=(snapshot:InfrastructureFreshnessSnapshot)=>infrastructureFreshnessHasUnknownComponent(snapshot)?INFRASTRUCTURE_FRESHNESS_UNKNOWN_CLIENT_TTL_MS:INFRASTRUCTURE_FRESHNESS_CLIENT_TTL_MS;
export const infrastructureFreshnessServerTtl=(snapshot:InfrastructureFreshnessSnapshot)=>infrastructureFreshnessHasUnknownComponent(snapshot)?INFRASTRUCTURE_FRESHNESS_UNKNOWN_SERVER_CACHE_MS:INFRASTRUCTURE_FRESHNESS_SERVER_CACHE_MS;
export function aggregateInfrastructureFreshness(components:InfrastructureFreshnessSnapshot["components"]):InfrastructureFreshnessState{const states=componentKeys.map(key=>components[key].state);return states.includes("superseded")?"superseded":states.includes("unknown")?"unknown":"current"}
function parseComponent(value:unknown):InfrastructureComponentFreshness|undefined{if(!value||typeof value!=="object"||Array.isArray(value))return;const item=value as Record<string,unknown>;if(!componentStates.has(item.state as InfrastructureComponentFreshnessState)||item.deployedRevision!==undefined&&(typeof item.deployedRevision!=="string"||!fullSha.test(item.deployedRevision))||item.deployedReleaseRevision!==undefined&&!integer(item.deployedReleaseRevision)||item.expectedReleaseRevision!==undefined&&!integer(item.expectedReleaseRevision)||item.unknownReason!==undefined&&(item.state!=="unknown"||typeof item.unknownReason!=="string"||!unknownReasons.has(item.unknownReason))||Object.keys(item).some(key=>!["state","deployedRevision","deployedReleaseRevision","expectedReleaseRevision","unknownReason"].includes(key)))return;return{state:item.state as InfrastructureComponentFreshnessState,...(typeof item.deployedRevision==="string"?{deployedRevision:item.deployedRevision.toLowerCase()}:{}),...(integer(item.deployedReleaseRevision)?{deployedReleaseRevision:Number(item.deployedReleaseRevision)}:{}),...(integer(item.expectedReleaseRevision)?{expectedReleaseRevision:Number(item.expectedReleaseRevision)}:{}),...(typeof item.unknownReason==="string"?{unknownReason:item.unknownReason as InfrastructureFreshnessUnknownReason}:{})}}
export function parseInfrastructureFreshnessSnapshot(value:unknown):InfrastructureFreshnessSnapshot|undefined{if(!value||typeof value!=="object"||Array.isArray(value))return;const item=value as Record<string,unknown>;if(!componentStates.has(item.state as InfrastructureFreshnessState)||typeof item.checkedAt!=="string"||!Number.isFinite(Date.parse(item.checkedAt))||!item.components||typeof item.components!=="object"||Array.isArray(item.components)||Object.keys(item).some(key=>!["state","checkedAt","components"].includes(key)))return;const source=item.components as Record<string,unknown>;if(Object.keys(source).some(key=>!componentKeys.includes(key as InfrastructureComponent)))return;const worker=parseComponent(source.worker),runtime=parseComponent(source.runtime),runner=parseComponent(source.runner);if(!worker||!runtime||!runner)return;const components={worker,runtime,runner};if(aggregateInfrastructureFreshness(components)!==item.state)return;return{state:item.state as InfrastructureFreshnessState,checkedAt:new Date(item.checkedAt).toISOString(),components}}
export function infrastructureFreshnessLabel(snapshot:InfrastructureFreshnessSnapshot){if(snapshot.state==="current")return"Infra current";const labels:Record<InfrastructureComponent,string>={worker:"App",runtime:"Runtime",runner:"Runner"},stale=componentKeys.filter(key=>snapshot.components[key].state==="superseded").map(key=>labels[key]);if(stale.length===1)return`${stale[0]} update available`;if(stale.length>1)return`Updates available · ${stale.join(" + ")}`;const unknown=componentKeys.filter(key=>snapshot.components[key].state==="unknown").map(key=>labels[key]);return unknown.length===1?`${unknown[0]} freshness unavailable`:`Infrastructure freshness unavailable${unknown.length?` · ${unknown.join(" + ")}`:""}`}
export function infrastructureRevisionLabel(snapshot:InfrastructureFreshnessSnapshot){return(["runtime","runner"] as const).flatMap(component=>snapshot.components[component].deployedRevision?[`${component==="runtime"?"Runtime":"Runner"} ${snapshot.components[component].deployedRevision!.slice(0,7)}`]:[]).join(" · ")}
