import type {WorkflowD1Database} from "./workflow-d1-storage.ts";

const MAX_OPERATION_BYTES=1_000_000,MAX_LIST=100,encoder=new TextEncoder(),specialWriteIndexes:Record<string,number>={__error__:-1,__scheduled__:-2,__interrupt__:-3,__resume__:-4};
type Config={configurable?:{thread_id?:string;checkpoint_ns?:string;checkpoint_id?:string}};
// The gateway validates every field before use; this internal wire envelope must represent heterogeneous official saver operations.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Operation={operation:"get"|"list"|"put"|"putWrites"|"deleteThread";threadId:string;payload?:any};
const b64=(bytes:ArrayBuffer)=>{let value="";for(const byte of new Uint8Array(bytes))value+=String.fromCharCode(byte);return btoa(value).replaceAll("+","-").replaceAll("/","_").replace(/=+$/,"")};
const decode=(value:string)=>Uint8Array.from(atob(value.replaceAll("-","+").replaceAll("_","/").padEnd(Math.ceil(value.length/4)*4,"=")),c=>c.charCodeAt(0));
async function hmac(secret:string,value:string){const key=await crypto.subtle.importKey("raw",encoder.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64(await crypto.subtle.sign("HMAC",key,encoder.encode(value)))}
async function digest(value:string){return b64(await crypto.subtle.digest("SHA-256",encoder.encode(value)))}
async function issueAuthority(aud:"checkpoint"|"graph-node",runId:string,secret:string,expiresAt:number,scope?:Record<string,unknown>){if(secret.length<32)throw new Error(`${aud}_authority_unavailable`);const payload=b64(encoder.encode(JSON.stringify({v:1,aud,runId,expiresAt,nonce:crypto.randomUUID(),...scope})).buffer);return`${payload}.${await hmac(secret,payload)}`}
async function authorityPayload(aud:"checkpoint"|"graph-node",token:string,runId:string,secret:string){const [payload,signature,...rest]=token.split(".");if(rest.length||!payload||!signature||secret.length<32)return undefined;const expected=await hmac(secret,payload);if(expected.length!==signature.length)return undefined;let mismatch=0;for(let i=0;i<expected.length;i++)mismatch|=expected.charCodeAt(i)^signature.charCodeAt(i);if(mismatch)return undefined;try{const value=JSON.parse(new TextDecoder().decode(decode(payload)));return value.v===1&&value.aud===aud&&value.runId===runId&&Number.isInteger(value.expiresAt)&&value.expiresAt>=Date.now()&&typeof value.nonce==="string"?value as Record<string,unknown>:undefined}catch{return undefined}}
export const issueCheckpointAuthority=(runId:string,secret:string,expiresAt=Date.now()+5*60_000)=>issueAuthority("checkpoint",runId,secret,expiresAt);
export const verifyCheckpointAuthority=async(token:string,runId:string,secret:string)=>Boolean(await authorityPayload("checkpoint",token,runId,secret));
export type GraphNodeAuthorityScope={runId:string;nodeId:string;activationId?:string;workflowGeneration:number;iteration:number;attempt:number};
export const issueGraphNodeAuthority=(scope:GraphNodeAuthorityScope,secret:string,expiresAt=Date.now()+5*60_000)=>issueAuthority("graph-node",scope.runId,secret,expiresAt,{nodeId:scope.nodeId,...(scope.activationId?{activationId:scope.activationId}:{}),workflowGeneration:scope.workflowGeneration,iteration:scope.iteration,attempt:scope.attempt});
export const verifyGraphNodeAuthority=async(token:string,scope:GraphNodeAuthorityScope,secret:string)=>{const value=await authorityPayload("graph-node",token,scope.runId,secret);return Boolean(value&&value.nodeId===scope.nodeId&&value.activationId===scope.activationId&&value.workflowGeneration===scope.workflowGeneration&&value.iteration===scope.iteration&&value.attempt===scope.attempt)};
const configValues=(config:Config,runId:string)=>{const value=config?.configurable;if(value?.thread_id!==runId)throw new Error("checkpoint_authority_invalid");const ns=value.checkpoint_ns??"",id=value.checkpoint_id;return{ns,id}};
const json=(value:unknown)=>{const raw=JSON.stringify(value);if(encoder.encode(raw).byteLength>MAX_OPERATION_BYTES)throw new Error("checkpoint_operation_too_large");return raw};

export class D1LangGraphCheckpointStore{
 private db:WorkflowD1Database;private now:()=>string;
 constructor(db:WorkflowD1Database,now=()=>new Date().toISOString()){this.db=db;this.now=now}
 private async tuple(runId:string,row:Record<string,unknown>){const writes=(await this.db.prepare("SELECT task_id,channel,value_json FROM langgraph_checkpoint_writes WHERE run_id=? AND checkpoint_namespace=? AND checkpoint_id=? ORDER BY task_id,write_index").bind(runId,row.checkpoint_namespace,row.checkpoint_id).all<Record<string,unknown>>()).results??[];const config=JSON.parse(String(row.config_json));return{config,checkpoint:JSON.parse(String(row.checkpoint_json)),metadata:JSON.parse(String(row.metadata_json)),...(row.parent_checkpoint_id?{parentConfig:{configurable:{...config.configurable,checkpoint_id:String(row.parent_checkpoint_id)}}}:{}),pendingWrites:writes.map(write=>[String(write.task_id),String(write.channel),JSON.parse(String(write.value_json))])}}
 async execute(runId:string,request:Operation){if(request.threadId!==runId)throw new Error("checkpoint_authority_invalid");const payload=request.payload??{};if(request.operation==="deleteThread"){await this.db.batch([this.db.prepare("DELETE FROM langgraph_checkpoint_writes WHERE run_id=?").bind(runId),this.db.prepare("DELETE FROM langgraph_checkpoints WHERE run_id=?").bind(runId)]);return null}const {ns,id}=configValues(payload.config,runId);
  if(request.operation==="get"){const row=id?await this.db.prepare("SELECT * FROM langgraph_checkpoints WHERE run_id=? AND checkpoint_namespace=? AND checkpoint_id=?").bind(runId,ns,id).first<Record<string,unknown>>():await this.db.prepare("SELECT * FROM langgraph_checkpoints WHERE run_id=? AND checkpoint_namespace=? ORDER BY created_at DESC,checkpoint_id DESC LIMIT 1").bind(runId,ns).first<Record<string,unknown>>();return row?this.tuple(runId,row):null}
  if(request.operation==="list"){const limit=Math.min(MAX_LIST,Math.max(1,Number(payload.options?.limit??MAX_LIST)));const rows=(await this.db.prepare("SELECT * FROM langgraph_checkpoints WHERE run_id=? AND checkpoint_namespace=? ORDER BY created_at DESC,checkpoint_id DESC LIMIT ?").bind(runId,ns,limit).all<Record<string,unknown>>()).results??[];return Promise.all(rows.map(row=>this.tuple(runId,row)))}
  if(request.operation==="put"){const checkpoint=payload.checkpoint;if(!checkpoint||typeof checkpoint.id!=="string"||checkpoint.id.length>128)throw new Error("checkpoint_state_invalid");const checkpointJson=json(checkpoint),metadataJson=json(payload.metadata),configJson=json({configurable:{...payload.config.configurable,thread_id:runId,checkpoint_ns:ns,checkpoint_id:checkpoint.id}}),hash=await digest(`${checkpointJson}\n${metadataJson}\n${configJson}`),parent=id??null,existing=await this.db.prepare("SELECT content_sha256 FROM langgraph_checkpoints WHERE run_id=? AND checkpoint_namespace=? AND checkpoint_id=?").bind(runId,ns,checkpoint.id).first<{content_sha256:string}>();if(existing){if(existing.content_sha256!==hash)throw new Error("checkpoint_state_conflicting")}else await this.db.prepare("INSERT INTO langgraph_checkpoints VALUES (?,?,?,?,?,?,?,?,?)").bind(runId,ns,checkpoint.id,parent,checkpointJson,metadataJson,configJson,hash,this.now()).run();return JSON.parse(configJson)}
  if(request.operation==="putWrites"){if(!id||typeof payload.taskId!=="string"||!Array.isArray(payload.writes)||payload.writes.length>256)throw new Error("checkpoint_state_invalid");for(const [position,write] of payload.writes.entries()){if(!Array.isArray(write)||write.length!==2||typeof write[0]!=="string")throw new Error("checkpoint_state_invalid");const index=specialWriteIndexes[write[0]]??position,valueJson=json(write[1]),hash=await digest(`${write[0]}\n${valueJson}`),existing=await this.db.prepare("SELECT content_sha256 FROM langgraph_checkpoint_writes WHERE run_id=? AND checkpoint_namespace=? AND checkpoint_id=? AND task_id=? AND write_index=?").bind(runId,ns,id,payload.taskId,index).first<{content_sha256:string}>();if(existing&&existing.content_sha256!==hash)throw new Error("checkpoint_state_conflicting");if(!existing)await this.db.prepare("INSERT INTO langgraph_checkpoint_writes VALUES (?,?,?,?,?,?,?,?,?)").bind(runId,ns,id,payload.taskId,index,write[0],valueJson,hash,this.now()).run()}return null}
  throw new Error("checkpoint_operation_invalid");
 }
}

export function parseCheckpointOperation(value:unknown):Operation{const raw=json(value);const item=JSON.parse(raw);if(!item||typeof item!=="object"||!(["get","list","put","putWrites","deleteThread"] as string[]).includes(item.operation)||typeof item.threadId!=="string"||item.threadId.length>128)throw new Error("checkpoint_operation_invalid");return item}
const gatewaySafeCodes=new Set(["checkpoint_authority_invalid","checkpoint_operation_invalid","checkpoint_operation_too_large","checkpoint_state_invalid","checkpoint_state_conflicting","checkpoint_persistence_unavailable"]);
export function checkpointGatewayFailureCode(error:unknown){const raw=error instanceof Error?error.message:"";return raw==="body_too_large"?"checkpoint_operation_too_large":raw==="invalid_json"?"checkpoint_operation_invalid":gatewaySafeCodes.has(raw)?raw:"checkpoint_persistence_unavailable"}
