import type {RepositoryAccessContext} from "./repository-authorization.ts";
import type {WorkflowD1Database} from "./workflow-d1-storage.ts";
import type {RunDetail} from "./workflow-storage.ts";
import {createGitHubAppJwt,mintInstallationToken} from "./github-app.ts";
import {getRepositoryAuthorizationConfig} from "./repository-authorization.ts";
import {CodexRunnerWorkflowGateway} from "./codex-runner-workflow-gateway.ts";
import {GitHubPullRequestClient} from "./github-pull-requests.ts";

const SHA=/^[a-f0-9]{40}$/;
const taskId=async(runId:string,stepId:string,iteration:number)=>{const bytes=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(`${runId}:${stepId}:${iteration}`)));return[...bytes].slice(0,16).map(v=>v.toString(16).padStart(2,"0")).join("")};
export function validateManagedPublishResult(published:Record<string,unknown>,expected:{owner:string;repo:string;baseBranch:string;branch:string}){const repository=published.repository as Record<string,unknown>,branch=String(published.branch??""),baseBranch=String(published.baseBranch??""),commit=String(published.commitSha??published.pushedCommitSha??"");if(published.changed!==true&&published.changed!==false||repository?.owner!==expected.owner||repository?.repo!==expected.repo||baseBranch!==expected.baseBranch||branch!==expected.branch||!/^adt\/codex\/[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/.test(branch)||!SHA.test(commit))throw new Error("malformed_response");return{changed:published.changed,branch,baseBranch,commit}}
export async function publishManagedPullRequest(input:{detail:RunDetail;stepId:string;associationStepId?:string;title:string;body:string;draft:boolean;access:RepositoryAccessContext;database:WorkflowD1Database;runner:{baseUrl:string;accessClientId:string;accessClientSecret:string;sharedSecret:string};fetcher?:typeof fetch;credentialProvider?:(capability:"write"|"pull_requests")=>Promise<{token:string}>;runnerGateway?:Pick<CodexRunnerWorkflowGateway,"publish">;pullRequestClient?:Pick<GitHubPullRequestClient,"createOrUpdate"|"update">}){
 const {detail}=input,associationStepId=input.associationStepId??input.stepId,context=detail.run.repositoryContext;
 if(!context||context.repositoryId!==input.access.repositoryId||context.installationId!==input.access.installationId||context.owner.toLowerCase()!==input.access.owner.toLowerCase()||context.repository.toLowerCase()!==input.access.repo.toLowerCase())throw new Error("permission_denied");
 const attempt=detail.attempts.filter(v=>v.stepId===input.stepId&&v.status==="succeeded").at(-1),agent=attempt&&detail.run.agentSnapshots[attempt.agentId],connection=attempt&&detail.run.connectionSnapshots[attempt.connectionKey];
 if(!attempt?.providerTaskId||!agent||connection?.adapter!=="codex-runner"||(agent.adapterOptions as {managedGit?:boolean}|undefined)?.managedGit!==true)throw new Error("managed_codex_result_required");
 const id=await taskId(detail.run.id,input.stepId,attempt.iteration),continuation=(agent.adapterOptions as {continueFrom?:{runId:string;publishNodeId:string}}).continueFrom;
 const prior=continuation?await input.database.prepare("SELECT repository_id,installation_id,owner,repository,base_branch,head_branch,commit_sha,pull_request_number,pull_request_url,draft,publication_created,state FROM workflow_managed_pull_requests WHERE run_id=? AND step_id=?").bind(continuation.runId,continuation.publishNodeId).first<{repository_id:number;installation_id:number;owner:string;repository:string;base_branch:string;head_branch:string;commit_sha:string;pull_request_number:number;pull_request_url:string;draft:number;publication_created:number;state:string}>():undefined;
 if(continuation&&(!prior||prior.repository_id!==context.repositoryId||prior.installation_id!==context.installationId||prior.owner!==context.owner||prior.repository!==context.repository||prior.base_branch!==context.branch||!/^adt\/codex\/[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/.test(prior.head_branch)||!SHA.test(prior.commit_sha)||!Number.isSafeInteger(prior.pull_request_number)||prior.pull_request_number<1||prior.pull_request_url!==`https://github.com/${context.owner}/${context.repository}/pull/${prior.pull_request_number}`||![0,1].includes(prior.draft)||![0,1].includes(prior.publication_created)||!["open","closed"].includes(prior.state)))throw new Error("malformed_response");
 const config=input.credentialProvider?undefined:getRepositoryAuthorizationConfig(),fetcher=input.fetcher??fetch;let appJwt:Promise<string>|undefined;
 const credential=input.credentialProvider??(async(capability:"write"|"pull_requests")=>{appJwt??=createGitHubAppJwt(config!.appId,config!.privateKey);return mintInstallationToken(context.installationId,context.repositoryId,await appJwt,capability,fetcher)});
 const write=await credential("write"),runner=input.runnerGateway??new CodexRunnerWorkflowGateway(input.runner,input.fetcher),published=await runner.publish({environmentKey:(agent.adapterOptions as {environmentKey:string}).environmentKey,taskId:id,credential:write.token,message:`ADT: ${input.title.trim().slice(0,180)}`}) as Record<string,unknown>,expectedBranch=prior?.head_branch??`adt/codex/${id}`;
 const {changed,branch,baseBranch,commit}=validateManagedPublishResult(published,{owner:context.owner,repo:context.repository,baseBranch:context.branch,branch:expectedBranch});
 if(changed===false&&!prior)throw new Error("managed_task_has_no_changes");
 const prCredential=await credential("pull_requests"),client=input.pullRequestClient??new GitHubPullRequestClient(input.fetcher),result=prior?{pullRequest:await client.update({owner:context.owner,repo:context.repository,branch,baseBranch,number:prior.pull_request_number,title:input.title,body:input.body,draft:input.draft,token:prCredential.token}),created:false}:await client.createOrUpdate({owner:context.owner,repo:context.repository,branch,baseBranch,title:input.title,body:input.body,draft:input.draft,token:prCredential.token}),now=new Date().toISOString();
 await input.database.prepare("INSERT INTO workflow_managed_pull_requests (run_id,step_id,runner_job_id,repository_task_id,repository_id,installation_id,owner,repository,base_branch,head_branch,commit_sha,pull_request_number,pull_request_url,draft,publication_created,state,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(run_id,step_id) DO UPDATE SET commit_sha=excluded.commit_sha,pull_request_number=excluded.pull_request_number,pull_request_url=excluded.pull_request_url,draft=excluded.draft,state=excluded.state,updated_at=excluded.updated_at").bind(detail.run.id,associationStepId,attempt.providerTaskId,id,context.repositoryId,context.installationId,context.owner,context.repository,baseBranch,branch,commit,result.pullRequest.number,result.pullRequest.url,result.pullRequest.draft?1:0,result.created?1:0,result.pullRequest.state,now,now).run();
 return{number:result.pullRequest.number,url:result.pullRequest.url,branch,commitSha:commit,draft:result.pullRequest.draft,created:result.created};
}
