import type {RepositoryAccessContext} from "./repository-authorization.ts";
import type {WorkflowD1Database} from "./workflow-d1-storage.ts";
import type {RunDetail} from "./workflow-storage.ts";
import {createGitHubAppJwt,mintInstallationToken} from "./github-app.ts";
import {getRepositoryAuthorizationConfig} from "./repository-authorization.ts";
import {CodexRunnerWorkflowGateway} from "./codex-runner-workflow-gateway.ts";
import {GitHubPullRequestClient} from "./github-pull-requests.ts";

const SHA=/^[a-f0-9]{40}$/;
const taskId=async(runId:string,stepId:string,iteration:number)=>{const bytes=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(`${runId}:${stepId}:${iteration}`)));return[...bytes].slice(0,16).map(v=>v.toString(16).padStart(2,"0")).join("")};
export async function publishManagedPullRequest(input:{detail:RunDetail;stepId:string;title:string;body:string;draft:boolean;access:RepositoryAccessContext;database:WorkflowD1Database;runner:{baseUrl:string;accessClientId:string;accessClientSecret:string;sharedSecret:string};fetcher?:typeof fetch}){const {detail}=input,context=detail.run.repositoryContext;if(!context||context.repositoryId!==input.access.repositoryId||context.installationId!==input.access.installationId||context.owner.toLowerCase()!==input.access.owner.toLowerCase()||context.repository.toLowerCase()!==input.access.repo.toLowerCase())throw new Error("permission_denied");const attempt=detail.attempts.filter(v=>v.stepId===input.stepId&&v.status==="succeeded").at(-1),agent=attempt&&detail.run.agentSnapshots[attempt.agentId],connection=attempt&&detail.run.connectionSnapshots[attempt.connectionKey];if(!attempt?.providerTaskId||!agent||connection?.adapter!=="codex-runner"||(agent.adapterOptions as {managedGit?:boolean}|undefined)?.managedGit!==true)throw new Error("managed_codex_result_required");const id=await taskId(detail.run.id,input.stepId,attempt.iteration),config=getRepositoryAuthorizationConfig();const appJwt=await createGitHubAppJwt(config.appId,config.privateKey),write=await mintInstallationToken(context.installationId,context.repositoryId,appJwt,"write"),runner=new CodexRunnerWorkflowGateway(input.runner,input.fetcher),published=await runner.publish({environmentKey:(agent.adapterOptions as {environmentKey:string}).environmentKey,taskId:id,credential:write.token,message:`ADT: ${input.title.trim().slice(0,180)}`}) as Record<string,unknown>;if(published.changed!==true&&published.changed!==false)throw new Error("malformed_response");const branch=String(published.branch??""),commit=String(published.commitSha??published.pushedCommitSha??"");if(!/^adt\/codex\/[a-z0-9-]+$/.test(branch)||published.changed===true&&!SHA.test(commit))throw new Error("malformed_response");if(published.changed===false&&!SHA.test(commit)){const previous=await input.database.prepare("SELECT commit_sha FROM workflow_managed_pull_requests WHERE run_id=? AND step_id=?").bind(detail.run.id,input.stepId).first<{commit_sha:string}>();if(!previous?.commit_sha)throw new Error("managed_task_has_no_changes");}
 const prCredential=await mintInstallationToken(context.installationId,context.repositoryId,appJwt,"pull_requests"),client=new GitHubPullRequestClient(input.fetcher),result=await client.createOrUpdate({owner:context.owner,repo:context.repository,branch,baseBranch:context.branch,title:input.title,body:input.body,draft:input.draft,token:prCredential.token}),now=new Date().toISOString(),sha=SHA.test(commit)?commit:String((await input.database.prepare("SELECT commit_sha FROM workflow_managed_pull_requests WHERE run_id=? AND step_id=?").bind(detail.run.id,input.stepId).first<{commit_sha:string}>())?.commit_sha??"");await input.database.prepare("INSERT INTO workflow_managed_pull_requests (run_id,step_id,runner_job_id,repository_task_id,repository_id,installation_id,owner,repository,base_branch,head_branch,commit_sha,pull_request_number,pull_request_url,draft,state,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(run_id,step_id) DO UPDATE SET commit_sha=excluded.commit_sha,pull_request_number=excluded.pull_request_number,pull_request_url=excluded.pull_request_url,draft=excluded.draft,state=excluded.state,updated_at=excluded.updated_at").bind(detail.run.id,input.stepId,attempt.providerTaskId,id,context.repositoryId,context.installationId,context.owner,context.repository,context.branch,branch,sha,result.pullRequest.number,result.pullRequest.url,result.pullRequest.draft?1:0,result.pullRequest.state,now,now).run();return{number:result.pullRequest.number,url:result.pullRequest.url,branch,commitSha:sha,draft:result.pullRequest.draft,created:result.created}}
