import {mcpCatalogueToolSchema,mcpServerDefinitionSchema,safeMcpServer,type McpServerDefinition} from "./tool-definitions.ts";
import type {ToolDefinitionRepository} from "./tool-definition-repository.ts";
import type {D1ProviderCredentialVault} from "./provider-credential-vault.ts";
import type {RemoteOpenAIAgentsRuntime} from "./adt-runtime-client.ts";
import {z} from "zod";

type Vault=Pick<D1ProviderCredentialVault,"create"|"resolve"|"delete"|"ensureMcpServerCredentialBinding"|"rotateMcpServerCredential"|"replaceMcpServerCredentialBinding"|"restoreMcpServerCredentialBinding"|"revokeMcpServerCredentialBinding">;
export const mcpServerInputSchema=z.object({id:z.string(),name:z.string(),endpointUrl:z.string(),authenticationMode:z.enum(["none","bearer"]),bearerToken:z.string().max(8192).optional()}).strict();
const cleanupSecret=async(vault:Vault,secretId:string|undefined)=>{if(secretId)await vault.delete(secretId).catch(()=>undefined)};

export async function createMcpServer(repositoryId:number,input:z.infer<typeof mcpServerInputSchema>,repo:ToolDefinitionRepository,vault:Vault){
 const value=mcpServerInputSchema.parse(input);let ref:string|undefined;if(value.authenticationMode==="bearer"){if(!value.bearerToken?.trim())throw new Error("credential_required");ref=await vault.create(value.bearerToken)}
 const definition=mcpServerDefinitionSchema.parse({schemaVersion:1,id:value.id,name:value.name,type:"mcp",transport:"streamable-http",endpointUrl:value.endpointUrl,authentication:value.authenticationMode==="bearer"?{mode:"bearer",credentialSecretRef:ref}:{mode:"none"}});let created:Awaited<ReturnType<ToolDefinitionRepository["create"]>>;
 try{created=await repo.create(definition)}catch(error){await cleanupSecret(vault,ref);throw error}if(!ref)return created;
 let bindingId:string|undefined;try{bindingId=await vault.ensureMcpServerCredentialBinding(repositoryId,value.id,ref);return created}catch(error){if(bindingId)await vault.revokeMcpServerCredentialBinding(repositoryId,value.id,bindingId).catch(()=>undefined);await repo.delete(value.id,created.fileSha).catch(()=>undefined);await cleanupSecret(vault,ref);throw error}
}

export async function updateMcpServer(repositoryId:number,input:z.infer<typeof mcpServerInputSchema>&{fileSha:string},repo:ToolDefinitionRepository,vault:Vault){
 const old=await repo.get(input.id);if(!old)throw new Error("tool_not_found");const oldAuth=old.definition.authentication,oldBindingId=oldAuth.mode==="bearer"?await vault.ensureMcpServerCredentialBinding(repositoryId,input.id,oldAuth.credentialSecretRef):undefined,endpointChanged=old.definition.endpointUrl!==input.endpointUrl;
 let authentication:McpServerDefinition["authentication"],candidate:string|undefined,obsolete:string|undefined;if(input.authenticationMode==="none")authentication={mode:"none"};else if(oldAuth.mode==="bearer"){authentication=oldAuth;if(input.bearerToken?.trim()){candidate=await vault.create(input.bearerToken);obsolete=oldAuth.credentialSecretRef;authentication={mode:"bearer",credentialSecretRef:candidate}}}else{if(!input.bearerToken?.trim())throw new Error("credential_required");candidate=await vault.create(input.bearerToken);authentication={mode:"bearer",credentialSecretRef:candidate}}
 if(input.authenticationMode==="none"&&oldAuth.mode==="bearer")obsolete=oldAuth.credentialSecretRef;let saved:Awaited<ReturnType<ToolDefinitionRepository["update"]>>;try{saved=await repo.update({...old.definition,name:input.name,endpointUrl:input.endpointUrl,authentication},input.fileSha)}catch(error){await cleanupSecret(vault,candidate);throw error}
 let newBindingId:string|undefined;try{
  if(oldAuth.mode==="bearer"&&authentication.mode==="bearer"){if(endpointChanged)newBindingId=await vault.replaceMcpServerCredentialBinding(repositoryId,input.id,oldBindingId!,authentication.credentialSecretRef);else{newBindingId=oldBindingId;if(authentication.credentialSecretRef!==oldAuth.credentialSecretRef)await vault.rotateMcpServerCredential(repositoryId,input.id,oldBindingId!,authentication.credentialSecretRef,oldAuth.credentialSecretRef)}}
  else if(oldAuth.mode==="bearer")await vault.revokeMcpServerCredentialBinding(repositoryId,input.id,oldBindingId!);
  else if(authentication.mode==="bearer")newBindingId=await vault.ensureMcpServerCredentialBinding(repositoryId,input.id,authentication.credentialSecretRef);
 }catch(error){
  let authorityRestored=false;try{if(oldAuth.mode==="bearer")await vault.restoreMcpServerCredentialBinding(repositoryId,input.id,oldBindingId!,oldAuth.credentialSecretRef);else if(newBindingId)await vault.revokeMcpServerCredentialBinding(repositoryId,input.id,newBindingId);authorityRestored=true}catch{/* Secret retirement below makes incomplete compensation fail closed. */}
  let gitRestored=false;try{await repo.update(old.definition,saved.fileSha);gitRestored=true}catch{/* Incomplete Git compensation is disabled below. */}
  if(!authorityRestored||!gitRestored){await cleanupSecret(vault,candidate);if(oldAuth.mode==="bearer"&&!gitRestored)await cleanupSecret(vault,oldAuth.credentialSecretRef)}else await cleanupSecret(vault,candidate);throw error
 }
 if(obsolete&&!(authentication.mode==="bearer"&&obsolete===authentication.credentialSecretRef))await cleanupSecret(vault,obsolete);return saved;
}

export async function deleteMcpServer(repositoryId:number,id:string,fileSha:string,repo:ToolDefinitionRepository,vault:Vault){const old=await repo.get(id);if(!old)throw new Error("tool_not_found");const auth=old.definition.authentication,bindingId=auth.mode==="bearer"?await vault.ensureMcpServerCredentialBinding(repositoryId,id,auth.credentialSecretRef):undefined;await repo.delete(id,fileSha);if(auth.mode!=="bearer")return;try{await vault.revokeMcpServerCredentialBinding(repositoryId,id,bindingId!)}catch(error){let authorityRestored=false;try{await vault.restoreMcpServerCredentialBinding(repositoryId,id,bindingId!,auth.credentialSecretRef);authorityRestored=true}catch{}let gitRestored=false;try{await repo.create(old.definition);gitRestored=true}catch{}if(!authorityRestored||!gitRestored)await cleanupSecret(vault,auth.credentialSecretRef);throw error}await cleanupSecret(vault,auth.credentialSecretRef)}
export async function discoverMcpServer(id:string,fileSha:string,repo:ToolDefinitionRepository,vault:Vault,runtime:Pick<RemoteOpenAIAgentsRuntime,"discoverMcp">,now=()=>new Date()){const old=await repo.get(id);if(!old)throw new Error("tool_not_found");if(old.fileSha!==fileSha)throw new Error("definition_conflict");const credential=old.definition.authentication.mode==="bearer"?await vault.resolve(old.definition.authentication.credentialSecretRef):undefined;const tools=z.array(mcpCatalogueToolSchema).max(128).parse(await runtime.discoverMcp({url:old.definition.endpointUrl,transport:"streamable-http"},credential));return repo.update({...old.definition,catalogue:{tools,refreshedAt:now().toISOString()}},fileSha)}
export const safeVersionedMcp=(value:{definition:McpServerDefinition;fileSha:string})=>({definition:safeMcpServer(value.definition),fileSha:value.fileSha});

export async function validateAgentMcpGrants(agent:import("./workflow-definitions.ts").AgentDefinitionV1,repo:Pick<ToolDefinitionRepository,"list">){const {mcpToolGrants}=await import("./workflow-definitions.ts"),grants=mcpToolGrants(agent.tools);if(!grants.length)return agent;const servers=new Map((await repo.list()).map(item=>[item.definition.id,item.definition]));for(const grant of grants){const server=servers.get(grant.serverId);if(!server?.catalogue?.tools.some(tool=>tool.name===grant.toolName))throw new Error("mcp_grant_unavailable")}return agent}
