import type {AgentDefinitionV1} from "./workflow-definitions.ts";import {mcpToolGrants} from "./workflow-definitions.ts";import type {ToolDefinitionRepository} from "./tool-definition-repository.ts";import type {D1ProviderCredentialVault} from "./provider-credential-vault.ts";import type {AuthorizedMcpTool} from "./workflow-adapter.ts";import {z} from "zod";
export type FrozenMcpTool={alias:string;serverId:string;authenticationMode:"none"|"bearer";server:{url:string;transport:"streamable-http"};tool:{name:string;description?:string;inputSchema:Record<string,unknown>}};
export type FrozenMcpRunTools=Record<string,FrozenMcpTool[]>;
const frozenMcpToolSchema=z.object({alias:z.string().min(1).max(64),serverId:z.string().min(1).max(80),authenticationMode:z.enum(["none","bearer"]),server:z.object({url:z.string().url().refine(value=>new URL(value).protocol==="https:"),transport:z.literal("streamable-http")}).strict(),tool:z.object({name:z.string().min(1).max(128),description:z.string().max(2048).optional(),inputSchema:z.record(z.string(),z.unknown())}).strict()}).strict();
export const frozenMcpRunToolsSchema=z.record(z.string(),z.array(frozenMcpToolSchema).max(128));
const b64=(bytes:Uint8Array)=>Buffer.from(bytes).toString("base64url");const safe=(value:string)=>value.replace(/[^A-Za-z0-9_-]/g,"_").replace(/^[^A-Za-z_]/,"_").slice(0,30)||"tool";
/** Collision-safe model alias: mcp_<remote prefix>_<SHA-256(server ID NUL remote name)[0..22]>. */
export async function mcpToolAlias(serverId:string,toolName:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(`${serverId}\0${toolName}`));return `mcp_${safe(toolName)}_${b64(new Uint8Array(bytes)).slice(0,22)}`}
export async function freezeAuthorizedMcpTools(agents:readonly AgentDefinitionV1[],repo:Pick<ToolDefinitionRepository,"list">,credentialBindings?:Pick<D1ProviderCredentialVault,"bindMcpServerCredential">):Promise<FrozenMcpRunTools>{const servers=new Map((await repo.list()).map(item=>[item.definition.id,item.definition])),snapshot:FrozenMcpRunTools={};for(const agent of agents){const result:FrozenMcpTool[]=[];for(const grant of mcpToolGrants(agent.tools)){const server=servers.get(grant.serverId),tool=server?.catalogue?.tools.find(item=>item.name===grant.toolName);if(!server)throw new Error("mcp_server_missing");if(!tool)throw new Error("mcp_grant_unavailable");if(server.authentication.mode==="bearer")await credentialBindings?.bindMcpServerCredential(server.id,server.authentication.credentialSecretRef);result.push({alias:await mcpToolAlias(server.id,tool.name),serverId:server.id,authenticationMode:server.authentication.mode,server:{url:server.endpointUrl,transport:"streamable-http"},tool:structuredClone(tool)})}if(new Set(result.map(item=>item.alias)).size!==result.length)throw new Error("mcp_alias_collision");if(result.length)snapshot[agent.id]=result}return snapshot}
export async function resolveFrozenMcpTools(agent:AgentDefinitionV1,snapshot:FrozenMcpRunTools|undefined,vault:Pick<D1ProviderCredentialVault,"resolveMcpServerCredential">):Promise<AuthorizedMcpTool[]>{const grants=mcpToolGrants(agent.tools);if(!grants.length)return[];const frozen=snapshot?.[agent.id];if(!frozen)throw new Error("mcp_run_snapshot_missing");if(frozen.length!==grants.length||grants.some(grant=>!frozen.some(item=>item.serverId===grant.serverId&&item.tool.name===grant.toolName)))throw new Error("mcp_run_snapshot_invalid");return Promise.all(frozen.map(async item=>{const credential=item.authenticationMode==="bearer"?await vault.resolveMcpServerCredential(item.serverId):undefined;return{alias:item.alias,serverId:item.serverId,server:structuredClone(item.server),tool:structuredClone(item.tool),...(credential?{credential}:{})}}))}
/** Current-definition resolution remains available for grant validation and non-run callers only. */
export async function resolveAuthorizedMcpTools(agent:AgentDefinitionV1,repo:Pick<ToolDefinitionRepository,"list">,vault:Pick<D1ProviderCredentialVault,"resolve">):Promise<AuthorizedMcpTool[]>{const servers=new Map((await repo.list()).map(item=>[item.definition.id,item.definition])),result:AuthorizedMcpTool[]=[];for(const grant of mcpToolGrants(agent.tools)){const server=servers.get(grant.serverId),tool=server?.catalogue?.tools.find(item=>item.name===grant.toolName);if(!server)throw new Error("mcp_server_missing");if(!tool)throw new Error("mcp_grant_unavailable");const credential=server.authentication.mode==="bearer"?await vault.resolve(server.authentication.credentialSecretRef):undefined;result.push({alias:await mcpToolAlias(server.id,tool.name),serverId:server.id,server:{url:server.endpointUrl,transport:"streamable-http"},tool,...(credential?{credential}:{})})}return result}
