import { agentDefinitionPath, agentDefinitionSchema, canonicalJson, workflowDefinitionPath, workflowDefinitionSchema, type AgentDefinitionV1, type WorkflowDefinitionV1 } from "./workflow-definitions.ts";
import { definitionReadRoots } from "./repository-layout.ts";

export class DefinitionConflictError extends Error { constructor(){super("The definition changed since it was loaded.");} }
export class DefinitionNotFoundError extends Error { constructor(){super("Definition not found.");} }
export class AgentInUseError extends Error { constructor(){super("agent_in_use");} }
export class DefinitionLayoutCollisionError extends Error { readonly identity:string; readonly paths:string[]; constructor(identity:string,paths:string[]){super(`Definition ID "${identity}" is duplicated across ${paths.join(" and ")}.`);this.identity=identity;this.paths=paths;} }
export class DefinitionCompatibilityReadOnlyError extends Error { constructor(){super("Future-layout definitions are read-only during repository migration compatibility.");} }
export type Versioned<T>={definition:T;fileSha:string;sourcePath?:string};
export interface WorkflowDefinitionRepository { listAgents():Promise<Versioned<AgentDefinitionV1>[]>; getAgent(id:string):Promise<Versioned<AgentDefinitionV1>|undefined>; createAgent(value:AgentDefinitionV1):Promise<Versioned<AgentDefinitionV1>>; updateAgent(value:AgentDefinitionV1,fileSha:string):Promise<Versioned<AgentDefinitionV1>>; deleteAgent(id:string,fileSha:string):Promise<void>; listWorkflows():Promise<Versioned<WorkflowDefinitionV1>[]>; getWorkflow(id:string):Promise<Versioned<WorkflowDefinitionV1>|undefined>; createWorkflow(value:WorkflowDefinitionV1):Promise<Versioned<WorkflowDefinitionV1>>; updateWorkflow(value:WorkflowDefinitionV1,fileSha:string):Promise<Versioned<WorkflowDefinitionV1>>; deleteWorkflow(id:string,fileSha:string):Promise<void>; }

export class InMemoryWorkflowDefinitionRepository implements WorkflowDefinitionRepository {
 private agents=new Map<string,Versioned<AgentDefinitionV1>>(); private workflows=new Map<string,Versioned<WorkflowDefinitionV1>>(); private revision=0;
 private version<T>(definition:T):Versioned<T>{return {definition:structuredClone(definition),fileSha:`sha-${++this.revision}`};}
 async listAgents(){return structuredClone([...this.agents.values()]);} async getAgent(id:string){return structuredClone(this.agents.get(id));}
 async createAgent(value:AgentDefinitionV1){const parsed=agentDefinitionSchema.parse(value);if(this.agents.has(parsed.id))throw new DefinitionConflictError();const stored=this.version(parsed);this.agents.set(parsed.id,stored);return structuredClone(stored);}
 async updateAgent(value:AgentDefinitionV1,sha:string){const parsed=agentDefinitionSchema.parse(value),old=this.agents.get(parsed.id);if(!old)throw new DefinitionNotFoundError();if(old.fileSha!==sha)throw new DefinitionConflictError();const stored=this.version(parsed);this.agents.set(parsed.id,stored);return structuredClone(stored);}
 async deleteAgent(id:string,sha:string){agentDefinitionPath(id);const old=this.agents.get(id);if(!old)throw new DefinitionNotFoundError();if(old.fileSha!==sha)throw new DefinitionConflictError();if([...this.workflows.values()].some(({definition})=>definition.steps.some(step=>step.agentId===id)))throw new AgentInUseError();this.agents.delete(id);}
 async listWorkflows(){return structuredClone([...this.workflows.values()]);} async getWorkflow(id:string){return structuredClone(this.workflows.get(id));}
 async createWorkflow(value:WorkflowDefinitionV1){const parsed=workflowDefinitionSchema.parse(value);if(this.workflows.has(parsed.id))throw new DefinitionConflictError();const stored=this.version(parsed);this.workflows.set(parsed.id,stored);return structuredClone(stored);}
 async updateWorkflow(value:WorkflowDefinitionV1,sha:string){const parsed=workflowDefinitionSchema.parse(value),old=this.workflows.get(parsed.id);if(!old)throw new DefinitionNotFoundError();if(old.fileSha!==sha)throw new DefinitionConflictError();const stored=this.version(parsed);this.workflows.set(parsed.id,stored);return structuredClone(stored);}
 async deleteWorkflow(id:string,sha:string){workflowDefinitionPath(id);const old=this.workflows.get(id);if(!old)throw new DefinitionNotFoundError();if(old.fileSha!==sha)throw new DefinitionConflictError();this.workflows.delete(id);}
}

/** Minimal Git contents adapter. Credentials stay in the injected server-only request function. */
export class GitHubWorkflowDefinitionRepository implements WorkflowDefinitionRepository {
 private request:(path:string,init?:RequestInit)=>Promise<Response>; private agentRoot:string; private workflowRoot:string; private agentRoots:string[]; private workflowRoots:string[];
 constructor(request:(path:string,init?:RequestInit)=>Promise<Response>,agentRoot="_adt/agents",workflowRoot="_adt/workflows"){this.request=request;this.agentRoot=agentRoot;this.workflowRoot=workflowRoot;this.agentRoots=definitionReadRoots(agentRoot,"agents");this.workflowRoots=definitionReadRoots(workflowRoot,"workflows");}
 private async get<T>(path:string,schema:{parse(value:unknown):T}):Promise<Versioned<T>|undefined>{const response=await this.request(`/contents/${path}`);if(response.status===404)return undefined;if(!response.ok)throw new Error("definition_repository_unavailable");const body=await response.json() as {content:string;sha:string};return {definition:schema.parse(JSON.parse(Buffer.from(body.content.replace(/\s/g,""),"base64").toString("utf8"))),fileSha:body.sha,sourcePath:path};}
 private async list<T>(root:string,suffix:string,schema:{parse(value:unknown):T}){const response=await this.request(`/contents/${root}`);if(response.status===404)return [];if(!response.ok)throw new Error("definition_repository_unavailable");const entries=await response.json() as {path:string;name:string}[];const values=await Promise.all(entries.filter(e=>e.name.endsWith(suffix)).map(e=>this.get(e.path,schema)));return values.filter((x):x is Versioned<T>=>x!==undefined);}
 private async put<T>(path:string,value:T,schema:{parse(value:unknown):T},sha?:string){const parsed=schema.parse(value);const response=await this.request(`/contents/${path}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({message:`Update ${path}`,content:Buffer.from(canonicalJson(parsed)).toString("base64"),...(sha?{sha}:{})})});if(response.status===409||response.status===422)throw new DefinitionConflictError();if(!response.ok)throw new Error("definition_repository_unavailable");const body=await response.json() as {content?:{sha?:string}};return {definition:parsed,fileSha:body.content?.sha??"",sourcePath:path};}
 private async delete(path:string,sha:string){const response=await this.request(`/contents/${path}`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({message:`Delete ${path}`,sha})});if(response.status===404)throw new DefinitionNotFoundError();if(response.status===409||response.status===422)throw new DefinitionConflictError();if(!response.ok)throw new Error("definition_repository_unavailable");}
 private async listRoots<T>(roots:string[],suffix:string,schema:{parse(value:unknown):T},idOf:(value:T)=>string){const values=(await Promise.all(roots.map(root=>this.list(root,suffix,schema)))).flat();const seen=new Map<string,Versioned<T>>();for(const value of values){const id=idOf(value.definition);const previous=seen.get(id);if(previous)throw new DefinitionLayoutCollisionError(id,[previous.sourcePath??"[unknown path]",value.sourcePath??"[unknown path]"]);seen.set(id,value);}return values;}

 private assertLegacy<T>(value:Versioned<T>|undefined,legacyRoot:string){if(!value)throw new DefinitionNotFoundError();if(!value.sourcePath?.startsWith(`${legacyRoot}/`))throw new DefinitionCompatibilityReadOnlyError();return value;}
 private agentParser={parse:(value:unknown)=>agentDefinitionSchema.parse(value)};
 listAgents(){return this.listRoots(this.agentRoots,".agent.json",this.agentParser,value=>value.id);} async getAgent(id:string){agentDefinitionPath(id);return (await this.listAgents()).find(value=>value.definition.id===id);} async createAgent(v:AgentDefinitionV1){if(await this.getAgent(v.id))throw new DefinitionConflictError();return this.put(agentDefinitionPath(v.id,this.agentRoot),v,this.agentParser);} async updateAgent(v:AgentDefinitionV1,s:string){this.assertLegacy(await this.getAgent(v.id),this.agentRoot);return this.put(agentDefinitionPath(v.id,this.agentRoot),v,this.agentParser,s);} async deleteAgent(id:string,s:string){this.assertLegacy(await this.getAgent(id),this.agentRoot);if((await this.listWorkflows()).some(({definition})=>definition.steps.some(step=>step.agentId===id)))throw new AgentInUseError();return this.delete(agentDefinitionPath(id,this.agentRoot),s);}
 listWorkflows(){return this.listRoots(this.workflowRoots,".workflow.json",workflowDefinitionSchema,value=>value.id);} async getWorkflow(id:string){workflowDefinitionPath(id);return (await this.listWorkflows()).find(value=>value.definition.id===id);} async createWorkflow(v:WorkflowDefinitionV1){if(await this.getWorkflow(v.id))throw new DefinitionConflictError();return this.put(workflowDefinitionPath(v.id,this.workflowRoot),v,workflowDefinitionSchema);} async updateWorkflow(v:WorkflowDefinitionV1,s:string){this.assertLegacy(await this.getWorkflow(v.id),this.workflowRoot);return this.put(workflowDefinitionPath(v.id,this.workflowRoot),v,workflowDefinitionSchema,s);} async deleteWorkflow(id:string,s:string){this.assertLegacy(await this.getWorkflow(id),this.workflowRoot);return this.delete(workflowDefinitionPath(id,this.workflowRoot),s);}
}
