import {decryptProviderCredential,encryptProviderCredential,providerSecretStorageAvailable} from "./workflow-provider-secret-crypto.ts";
import type {ConnectionDescriptor,ResolvedConnection} from "./workflow-connections.ts";
import {assertProviderConnectionKey,RESERVED_CONNECTION_KEYS} from "./workflow-connections.ts";
export interface ProviderConnectionDatabase{prepare(sql:string):{bind(...values:unknown[]):{first<T>():Promise<T|null>;run():Promise<unknown>;all<T>():Promise<{results:T[]}>}}}
type Row={connection_key:string;display_name?:string|null;adapter:string;default_model:string;encrypted_credential:string;credential_iv:string;encryption_version:number};
export type ProviderConnectionInput={connectionKey:string;displayName?:string;adapter:string;model:string;credential?:string};
export interface WorkflowProviderConnectionStore{listSafeDescriptors():Promise<ConnectionDescriptor[]>;getSafeDescriptor(key:string):Promise<ConnectionDescriptor|undefined>;resolveCredential(key:string,snapshot?:ConnectionDescriptor):Promise<ResolvedConnection>;assertMutable(key:string):Promise<void>;upsertConnection(input:ProviderConnectionInput):Promise<ConnectionDescriptor>;duplicateConnection(sourceKey:string,input:Omit<ProviderConnectionInput,"credential">):Promise<ConnectionDescriptor>;deleteConnection(key:string):Promise<void>}
const descriptor=(row:Row,ready:boolean):ConnectionDescriptor=>({key:row.connection_key,name:row.display_name?.trim()||"OpenAI Responses",adapter:row.adapter,endpoint:"https://api.openai.com/v1",defaultModel:row.default_model,enabled:ready,management:"d1",capabilities:{asynchronous:true,cancellation:true}});
const legacyUnavailable:ConnectionDescriptor={key:"openai-primary",name:"OpenAI Responses",adapter:"openai-responses",endpoint:"https://api.openai.com/v1",enabled:false,capabilities:{asynchronous:true,cancellation:true}};
export class D1WorkflowProviderConnectionStore implements WorkflowProviderConnectionStore{
 private db:ProviderConnectionDatabase;private root:string|undefined;constructor(db:ProviderConnectionDatabase,root:string|undefined){this.db=db;this.root=root;}
 async row(key:string){return this.db.prepare("SELECT * FROM workflow_provider_connections WHERE connection_key = ?").bind(key).first<Row>();}
 private assertProviderRow(row:Row|null){if(row&&RESERVED_CONNECTION_KEYS.has(row.connection_key))throw new Error("connection_identity_collision");return row}
 private async safeDescriptor(row:Row|null){this.assertProviderRow(row);if(!row||row.adapter!=="openai-responses")return undefined;let ready=false;if(providerSecretStorageAvailable(this.root)){try{await decryptProviderCredential({version:row.encryption_version,ciphertext:row.encrypted_credential,iv:row.credential_iv},this.root,row.connection_key,row.adapter);ready=true;}catch{ready=false;}}return descriptor(row,ready);}
 async listSafeDescriptors(){const {results}=await this.db.prepare("SELECT * FROM workflow_provider_connections WHERE adapter = ? ORDER BY display_name, connection_key").bind("openai-responses").all<Row>().catch(async()=>this.db.prepare("SELECT * FROM workflow_provider_connections WHERE adapter = ? ORDER BY connection_key").bind("openai-responses").all<Row>());results.forEach(row=>this.assertProviderRow(row));const safe=(await Promise.all(results.map(row=>this.safeDescriptor(row)))).filter((item):item is ConnectionDescriptor=>!!item);return safe.length?safe:[legacyUnavailable];}
 async getSafeDescriptor(key:string){return (await this.safeDescriptor(await this.row(key)))??(key==="openai-primary"?legacyUnavailable:undefined);}
 async getPersistedSafeDescriptor(key:string){const row=this.assertProviderRow(await this.row(key));return row?.adapter==="openai-responses"?descriptor(row,false):undefined;}
 async resolveCredential(key:string){const row=this.assertProviderRow(await this.row(key));if(!row||row.adapter!=="openai-responses"||!providerSecretStorageAvailable(this.root))throw new Error("connection_unavailable");const credential=await decryptProviderCredential({version:row.encryption_version,ciphertext:row.encrypted_credential,iv:row.credential_iv},this.root,key,row.adapter).catch(()=>{throw new Error("connection_unavailable")});return{...descriptor(row,true),credential};}
 async assertMutable(key:string){assertProviderConnectionKey(key)}
 async upsertConnection(input:ProviderConnectionInput){await this.assertMutable(input.connectionKey);if(input.adapter!=="openai-responses")throw new Error("unsupported_adapter");const old=await this.row(input.connectionKey),name=(input.displayName??old?.display_name??"OpenAI Responses").trim();if(!name)throw new Error("display_name_required");if(!input.credential&&!old)throw new Error("credential_required");const now=new Date().toISOString();if(input.credential){const encrypted=await encryptProviderCredential(input.credential,this.root,input.connectionKey,input.adapter);try{await this.db.prepare("INSERT INTO workflow_provider_connections(connection_key,display_name,adapter,default_model,encrypted_credential,credential_iv,encryption_version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(connection_key) DO UPDATE SET display_name=excluded.display_name,adapter=excluded.adapter,default_model=excluded.default_model,encrypted_credential=excluded.encrypted_credential,credential_iv=excluded.credential_iv,encryption_version=excluded.encryption_version,updated_at=excluded.updated_at").bind(input.connectionKey,name,input.adapter,input.model,encrypted.ciphertext,encrypted.iv,encrypted.version,now,now).run();}catch{await this.db.prepare("INSERT INTO workflow_provider_connections(connection_key,adapter,default_model,encrypted_credential,credential_iv,encryption_version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(connection_key) DO UPDATE SET adapter=excluded.adapter,default_model=excluded.default_model,encrypted_credential=excluded.encrypted_credential,credential_iv=excluded.credential_iv,encryption_version=excluded.encryption_version,updated_at=excluded.updated_at").bind(input.connectionKey,input.adapter,input.model,encrypted.ciphertext,encrypted.iv,encrypted.version,now,now).run();}}else await this.db.prepare("UPDATE workflow_provider_connections SET display_name = ?, default_model = ?, updated_at = ? WHERE connection_key = ?").bind(name,input.model,now,input.connectionKey).run().catch(()=>this.db.prepare("UPDATE workflow_provider_connections SET default_model = ?, updated_at = ? WHERE connection_key = ?").bind(input.model,now,input.connectionKey).run());return (await this.getSafeDescriptor(input.connectionKey))!;}
 async duplicateConnection(sourceKey:string,input:Omit<ProviderConnectionInput,"credential">){await this.assertMutable(input.connectionKey);if(await this.row(input.connectionKey))throw new Error("connection_exists");const source=await this.resolveCredential(sourceKey);return this.upsertConnection({...input,credential:source.credential});}
 async deleteConnection(key:string){await this.db.prepare("DELETE FROM workflow_provider_connections WHERE connection_key = ?").bind(key).run();}
 async retirePersistedConnection(expected:{key:string;name:string;adapter:string;defaultModel?:string}){const row=this.assertProviderRow(await this.row(expected.key));if(!row||row.adapter!=="openai-responses")throw new Error("migration_fallback_not_found");if(row.adapter!==expected.adapter||row.default_model!==expected.defaultModel||(row.display_name?.trim()||"OpenAI Responses")!==expected.name.trim())throw new Error("migration_configuration_mismatch");const result=await this.db.prepare("DELETE FROM workflow_provider_connections WHERE connection_key = ? AND adapter = ? AND default_model = ? AND COALESCE(NULLIF(TRIM(display_name), ''), 'OpenAI Responses') = ?").bind(expected.key,expected.adapter,expected.defaultModel,expected.name.trim()).run() as {meta?:{changes?:number}};if(result.meta?.changes!==1)throw new Error("migration_configuration_mismatch");}
}
