import type { AgentDefinitionV1, WorkflowDefinitionV1 } from "./workflow-definitions.ts";
import type { ConnectionDescriptor } from "./workflow-connections.ts";
import type { FailureCategory } from "./workflow-adapter.ts";

export type RunStatus = "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled";
export type StepStatus = "pending" | "starting" | "waiting_provider" | "succeeded" | "failed" | "cancelled";
export type CancellationResult = "cancelled" | "already_terminal" | "unsupported" | "safe_failure";
export type WorkflowLaunchState="unclaimed"|"launching"|"attached"|"launch_failed";
export type StepAttempt = { runId: string; stepId: string; iteration: number; attempt: number; agentId: string; connectionKey: string; status: StepStatus; inputText?: string; outputText?: string; outputExternalUrl?:string; providerTaskId?: string; providerState?: string; providerPollCount: number; nextPollDelayMs?:number; startedAt?: string; completedAt?: string; failureCategory?: FailureCategory; safeFailureMessage?: string; retryable?: boolean };
export type WorkflowRun = { id: string; engineVersion: "1"; workflowId: string; workflowRevision: string; workflowSnapshot: WorkflowDefinitionV1; agentSnapshots: Record<string, AgentDefinitionV1>; agentRevisions: Record<string,string>; connectionSnapshots: Record<string, ConnectionDescriptor>; initialInput: string; status: RunStatus; currentStepId?: string; transitionCount: number; stateVersion:number; workflowInstanceId?: string; reservedWorkflowInstanceId?:string; workflowGeneration: number; workflowLaunchState:WorkflowLaunchState; workflowLaunchFailure?:string; workflowLaunchAttemptedAt?:string; finalOutput?: string; finalExternalUrl?: string; cancelRequestedAt?: string; cancellationResult?: CancellationResult; createdAt: string; updatedAt: string; startedAt?: string; completedAt?: string; failureCode?: FailureCategory; failureMessage?: string; clientIdempotencyKey?: string };
export type RunDetail = { run: WorkflowRun; attempts: StepAttempt[] };
/** A two-minute lease avoids stealing a live request while bounding abandoned launch recovery. */
export const WORKFLOW_LAUNCH_STALE_MS=2*60*1000;
const terminalRuns = new Set<RunStatus>(["succeeded", "failed", "cancelled"]);

export interface WorkflowRunStorage {
  createRun(run: WorkflowRun): Promise<RunDetail>; findRunByIdempotencyKey(key:string):Promise<RunDetail|undefined>; getRun(id: string): Promise<RunDetail | undefined>; listRuns(limit?: number): Promise<WorkflowRun[]>;
  claimWorkflowLaunch(runId:string,generation:number,instanceId:string):Promise<{result:"claimed"|"stale_launch_claimed"|"launch_in_progress"|"already_attached"|"terminal";instanceId:string}>; attachWorkflowInstance(id: string,generation:number,instanceId: string): Promise<void>; recordWorkflowLaunchFailure(id:string,generation:number,instanceId:string,message:string):Promise<void>; claimStep(runId: string, stepId: string, inputText: string): Promise<StepAttempt>;
  persistProviderTask(runId: string, stepId: string, iteration: number, attempt: number, taskId: string,pollDelayMs:number): Promise<void>; incrementPollCount(runId: string, stepId: string, iteration: number, attempt: number,nextDelayMs:number): Promise<number>; completeStep(runId: string, stepId: string, iteration: number, attempt: number, output: string,externalUrl?:string): Promise<void>;
  failStep(runId: string, stepId: string, iteration: number, attempt: number, failure: { category: FailureCategory; safeMessage: string; retryable: boolean }): Promise<void>;
  advance(runId: string, expectedStepId: string, nextStepId: string): Promise<void>; completeRun(runId: string, expectedStepId: string, output: string, externalUrl?: string): Promise<void>;
  failRun(runId: string, code: FailureCategory, message: string): Promise<void>; requestCancellation(runId: string): Promise<RunStatus>; recordCancellationResult(runId: string, result: CancellationResult): Promise<void>; cancelRun(runId: string): Promise<void>; createAutomaticRetryAttempt(runId:string,stepId:string):Promise<StepAttempt>;prepareManualRetry(runId:string,stepId:string):Promise<RunDetail>;
}

export class InMemoryWorkflowRunStorage implements WorkflowRunStorage {
  private clock:()=>Date;
  constructor(clock:()=>Date=()=>new Date()){this.clock=clock;}
  private runs = new Map<string, WorkflowRun>(); private attempts = new Map<string, StepAttempt[]>(); private idempotency = new Map<string, string>();
  private now() { return this.clock().toISOString(); }
  async createRun(run: WorkflowRun) {
    if (run.clientIdempotencyKey && this.idempotency.has(run.clientIdempotencyKey)) return (await this.getRun(this.idempotency.get(run.clientIdempotencyKey)!))!;
    if (this.runs.has(run.id)) throw new Error("run_conflict");
    const first = run.workflowSnapshot.steps[0]; const stored = structuredClone(run); this.runs.set(run.id, stored);
    this.attempts.set(run.id, run.workflowSnapshot.steps.map((step) => ({ runId: run.id, stepId: step.id, iteration: 1, attempt: 1, agentId: step.agentId, connectionKey: run.agentSnapshots[step.agentId].connectionKey, status: "pending", providerPollCount: 0 })));
    if (run.clientIdempotencyKey) this.idempotency.set(run.clientIdempotencyKey, run.id); stored.currentStepId = first.id;
    return (await this.getRun(run.id))!;
  }
  async getRun(id: string) { const run = this.runs.get(id); return run ? structuredClone({ run, attempts: this.attempts.get(id) ?? [] }) : undefined; }
  async findRunByIdempotencyKey(key:string){const id=this.idempotency.get(key);return id?this.getRun(id):undefined;}
  async listRuns(limit = 25) { return [...this.runs.values()].sort((a,b) => b.createdAt.localeCompare(a.createdAt)).slice(0, limit).map((run) => structuredClone(run)); }
  private require(id: string) { const run = this.runs.get(id); if (!run) throw new Error("run_not_found"); return run; }
  private attempt(runId: string, stepId: string, iteration: number, attempt: number) { const value = this.attempts.get(runId)?.find((item) => item.stepId === stepId && item.iteration === iteration && item.attempt === attempt); if (!value) throw new Error("attempt_not_found"); return value; }
  async claimWorkflowLaunch(id:string,generation:number,instanceId:string){const run=this.require(id);if(terminalRuns.has(run.status)&&run.workflowLaunchState!=="launch_failed")return {result:"terminal" as const,instanceId};if(run.workflowGeneration!==generation)throw new Error("workflow_generation_conflict");if(run.workflowLaunchState==="attached")return {result:"already_attached" as const,instanceId:run.workflowInstanceId!};if(run.workflowLaunchState==="launching"){const reserved=run.reservedWorkflowInstanceId!;if(Date.parse(this.now())-Date.parse(run.workflowLaunchAttemptedAt!)<WORKFLOW_LAUNCH_STALE_MS)return {result:"launch_in_progress" as const,instanceId:reserved};run.workflowLaunchAttemptedAt=this.now();return {result:"stale_launch_claimed" as const,instanceId:reserved};}run.workflowLaunchState="launching";run.reservedWorkflowInstanceId=instanceId;run.workflowLaunchAttemptedAt=this.now();return {result:"claimed" as const,instanceId};}
  async attachWorkflowInstance(id: string,generation:number,instanceId: string) { const run=this.require(id); if(run.workflowGeneration!==generation||run.reservedWorkflowInstanceId!==instanceId)throw new Error("workflow_instance_conflict");if(run.workflowLaunchState==="attached"&&run.workflowInstanceId===instanceId)return;run.workflowInstanceId=instanceId;run.workflowLaunchState="attached";run.workflowLaunchFailure=undefined; }
  async recordWorkflowLaunchFailure(id:string,generation:number,instanceId:string,message:string){const run=this.require(id);if(run.workflowGeneration===generation&&run.workflowLaunchState==="launching"&&run.reservedWorkflowInstanceId===instanceId){run.workflowLaunchState="launch_failed";run.workflowLaunchFailure=message;run.status="failed";run.failureCode="internal_error";run.failureMessage=message;}}
  async claimStep(runId: string, stepId: string, inputText: string) { const run=this.require(runId); if (terminalRuns.has(run.status) || run.currentStepId !== stepId) throw new Error("invalid_step_claim"); const values=this.attempts.get(runId)!.filter(a=>a.stepId===stepId); const item=values.at(-1)!; if (item.status === "starting" || item.status === "waiting_provider" || item.status === "succeeded") return structuredClone(item); if (item.status !== "pending") throw new Error("invalid_step_claim"); item.status="starting"; item.inputText=inputText; item.startedAt=this.now(); run.status="running"; run.startedAt??=this.now(); return structuredClone(item); }
  async persistProviderTask(r:string,s:string,i:number,a:number,taskId:string,pollDelayMs:number) { const item=this.attempt(r,s,i,a); if (item.providerTaskId && item.providerTaskId!==taskId) throw new Error("provider_task_conflict"); if (!item.providerTaskId && item.status!=="starting") throw new Error("invalid_attempt_state"); item.providerTaskId=taskId; item.providerState="pending";item.nextPollDelayMs=pollDelayMs; item.status="waiting_provider"; }
  async incrementPollCount(r:string,s:string,i:number,a:number,nextDelayMs:number) { const item=this.attempt(r,s,i,a); if(item.status!=="waiting_provider") throw new Error("invalid_attempt_state");item.nextPollDelayMs=nextDelayMs; return ++item.providerPollCount; }
  async completeStep(r:string,s:string,i:number,a:number,output:string,externalUrl?:string) { const item=this.attempt(r,s,i,a); if (item.status==="succeeded") { if(item.outputText!==output) throw new Error("completion_conflict"); return; } if(!["starting","waiting_provider"].includes(item.status)) throw new Error("invalid_attempt_state"); item.status="succeeded"; item.outputText=output;item.outputExternalUrl=externalUrl; item.providerState="completed"; item.completedAt=this.now(); }
  async failStep(r:string,s:string,i:number,a:number,f:{category:FailureCategory;safeMessage:string;retryable:boolean}) { const item=this.attempt(r,s,i,a); if(item.status==="failed") return; if(!["starting","waiting_provider"].includes(item.status)) throw new Error("invalid_attempt_state"); Object.assign(item,{status:"failed",failureCategory:f.category,safeFailureMessage:f.safeMessage,retryable:f.retryable,completedAt:this.now()}); }
  async advance(id:string,expected:string,next:string) { const run=this.require(id); if(run.status!=="running"||run.currentStepId!==expected) throw new Error("invalid_advancement"); const current=this.attempts.get(id)!.filter(a=>a.stepId===expected).at(-1)!; if(current.status!=="succeeded"||!run.workflowSnapshot.steps.some(s=>s.id===next)) throw new Error("invalid_advancement"); run.currentStepId=next; run.transitionCount++; }
  async completeRun(id:string,expected:string,output:string,externalUrl?:string) { const run=this.require(id); if(run.status==="succeeded") return; if(run.status!=="running"||run.currentStepId!==expected||this.attempts.get(id)!.filter(a=>a.stepId===expected).at(-1)?.status!=="succeeded") throw new Error("invalid_completion"); Object.assign(run,{status:"succeeded",finalOutput:output,finalExternalUrl:externalUrl,completedAt:this.now(),currentStepId:undefined}); }
  async failRun(id:string,code:FailureCategory,message:string) { const run=this.require(id); if(terminalRuns.has(run.status)) return; Object.assign(run,{status:"failed",failureCode:code,failureMessage:message,completedAt:this.now()}); }
  async requestCancellation(id:string) { const run=this.require(id); if(terminalRuns.has(run.status)) return run.status; run.status="cancelling"; run.cancelRequestedAt??=this.now();return run.status; }
  async recordCancellationResult(id:string,result:CancellationResult) { const run=this.require(id); if(run.status!=="cancelling") throw new Error("invalid_cancellation"); run.cancellationResult??=result; }
  async cancelRun(id:string) { const run=this.require(id); if(run.status!=="cancelling") throw new Error("invalid_cancellation"); run.status="cancelled"; run.completedAt=this.now(); for(const item of this.attempts.get(id)!) if(["pending","starting","waiting_provider"].includes(item.status)) item.status="cancelled"; }
  private retry(id:string,stepId:string,automatic:boolean){const run=this.require(id),prior=this.attempts.get(id)!.filter(a=>a.stepId===stepId).at(-1);if(run.status!=="failed"||!prior||prior.status!=="failed"||prior.attempt>=(automatic?3:10))throw new Error("invalid_retry");const item={...prior,attempt:prior.attempt+1,status:"pending" as const,inputText:undefined,outputText:undefined,outputExternalUrl:undefined,providerTaskId:undefined,providerState:undefined,providerPollCount:0,nextPollDelayMs:undefined,startedAt:undefined,completedAt:undefined,failureCategory:undefined,safeFailureMessage:undefined,retryable:undefined};this.attempts.get(id)!.push(item);Object.assign(run,{status:"queued",currentStepId:stepId,completedAt:undefined,failureCode:undefined,failureMessage:undefined,...(!automatic?{workflowGeneration:run.workflowGeneration+1,workflowInstanceId:undefined,reservedWorkflowInstanceId:undefined,workflowLaunchState:"unclaimed" as const}:{})});return item;}
  async createAutomaticRetryAttempt(id:string,stepId:string){return structuredClone(this.retry(id,stepId,true));}async prepareManualRetry(id:string,stepId:string){this.retry(id,stepId,false);return (await this.getRun(id))!;}
}

export function newWorkflowRun(input: { id: string; workflow: WorkflowDefinitionV1; revision: string; agents: AgentDefinitionV1[]; agentRevisions?:Record<string,string>; connections: ConnectionDescriptor[]; initialInput: string; clientIdempotencyKey?: string }): WorkflowRun {
  if (Buffer.byteLength(input.initialInput,"utf8") > 65536) throw new Error("initial_input_too_large");
  const now=new Date().toISOString(); return { id:input.id,engineVersion:"1",workflowId:input.workflow.id,workflowRevision:input.revision,workflowSnapshot:structuredClone(input.workflow),agentSnapshots:Object.fromEntries(input.agents.map(a=>[a.id,structuredClone(a)])),agentRevisions:input.agentRevisions??{},connectionSnapshots:Object.fromEntries(input.connections.map(c=>[c.key,structuredClone(c)])),initialInput:input.initialInput,status:"queued",currentStepId:input.workflow.steps[0].id,transitionCount:0,stateVersion:0,workflowGeneration:1,workflowLaunchState:"unclaimed",createdAt:now,updatedAt:now,clientIdempotencyKey:input.clientIdempotencyKey };
}

export function manualRetryEligibility(detail:RunDetail|undefined){if(!detail||detail.run.status!=="failed")return {eligible:false as const,reason:"The run is not failed."};const attempt=detail.attempts.filter(item=>item.status==="failed").at(-1);if(!attempt)return {eligible:false as const,reason:"No failed step is available."};if(attempt.attempt>=10)return {eligible:false as const,reason:"The total attempt limit was reached."};return {eligible:true as const,stepId:attempt.stepId,reason:"The failed step can be retried."};}
