import type { AgentProviderAdapter, AdapterInvocation, FailureCategory } from "./workflow-adapter.ts";
import type { ResolvedConnection } from "./workflow-connections.ts";
import type { RunDetail, StepAttempt, WorkflowRunStorage } from "./workflow-storage.ts";

export type DurableStep={do<T>(name:string,callback:()=>Promise<T>):Promise<T>;sleep(name:string,duration:number|string):Promise<void>};
const terminal=new Set(["succeeded","failed","cancelled"]), transient=new Set<FailureCategory>(["rate_limited","provider_unavailable","provider_timeout"]);
const MAX_OUTPUT=262144,MAX_POLL=900_000,DEFAULT_POLL=10_000,MIN_POLL=1_000;
const safeFailure=(error:unknown):{category:FailureCategory;safeMessage:string;retryable:boolean}=>{
 const category=error&&typeof error==="object"&&"category" in error&&typeof error.category==="string"?error.category:"internal_error";
 const allowed:FailureCategory[]=["configuration_invalid","connection_unavailable","authentication_failed","permission_denied","provider_rejected","rate_limited","provider_unavailable","provider_timeout","malformed_response","output_too_large","cancelled","internal_error"];
 const safe=allowed.includes(category as FailureCategory)?category as FailureCategory:"internal_error";
 return {category:safe,safeMessage:safe==="internal_error"?"The provider operation failed unexpectedly.":`The provider operation failed (${safe.replaceAll("_"," ")}).`,retryable:transient.has(safe)};
};
function coordinates(runId:string,attempt:StepAttempt,operation:string,poll=attempt.providerPollCount){return `${runId}:${attempt.stepId}:${attempt.iteration}:${attempt.attempt}:${poll}:${operation}`;}
function invocation(detail:RunDetail,attempt:StepAttempt,resolve:(key:string)=>ResolvedConnection):AdapterInvocation{
 const agent=detail.run.agentSnapshots[attempt.agentId],snapshot=detail.run.connectionSnapshots[attempt.connectionKey],live=resolve(attempt.connectionKey);
 if(!snapshot||!live.enabled||snapshot.adapter!==live.adapter)throw Object.assign(new Error("connection unavailable"),{category:"connection_unavailable"});
 return {runId:detail.run.id,stepId:attempt.stepId,iteration:attempt.iteration,attempt:attempt.attempt,providerPollCount:attempt.providerPollCount,idempotencyKey:`${detail.run.id}:${attempt.stepId}:${attempt.iteration}:${attempt.attempt}`,agentName:agent.name,masterPrompt:agent.masterPrompt,inputText:attempt.inputText??"",connection:{...snapshot,credential:live.credential,serverConfiguration:live.serverConfiguration,privateOptions:live.privateOptions},providerOptions:agent.adapterOptions};
}
export async function executeDurableWorkflow(input:{runId:string;storage:WorkflowRunStorage;adapters:Map<string,AgentProviderAdapter>;resolveConnection:(key:string)=>ResolvedConnection;step:DurableStep}){
 const {runId,storage,adapters,resolveConnection,step}=input;
 for(;;){let detail=await storage.getRun(runId);if(!detail)throw new Error("run_not_found");if(terminal.has(detail.run.status))return {runId,status:detail.run.status};
  const currentRun=detail.run,stepDefinition=currentRun.workflowSnapshot.steps.find(item=>item.id===currentRun.currentStepId);if(!stepDefinition){await step.do(`${runId}:cursor:0:0:0:fail`,async()=>{await storage.failRun(runId,"internal_error","The workflow cursor is invalid.");return {status:"failed"};});continue;}
  let attempt=detail.attempts.filter(item=>item.stepId===stepDefinition.id).at(-1)!;
  if(detail.run.status==="cancelling"||detail.run.cancelRequestedAt){await step.do(coordinates(runId,attempt,"cancel"),async()=>{let outcome:"cancelled"|"already_terminal"|"unsupported"|"safe_failure"="already_terminal";try{if(attempt.providerTaskId){const call=invocation(detail!,attempt,resolveConnection),adapter=adapters.get(call.connection.adapter);outcome=adapter?.cancel?await adapter.cancel(attempt.providerTaskId,call):"unsupported";}}catch{outcome="safe_failure";}await storage.recordCancellationResult(runId,outcome);await storage.cancelRun(runId);return {status:"cancelled",outcome};});continue;}
  if(attempt.status==="pending"){const index=detail.run.workflowSnapshot.steps.indexOf(stepDefinition),previous=index?detail.attempts.filter(item=>item.stepId===detail!.run.workflowSnapshot.steps[index-1].id&&item.status==="succeeded").at(-1):undefined,inputText=index?previous?.outputText:detail.run.initialInput;if(inputText===undefined){await storage.failRun(runId,"internal_error","The previous step output is unavailable.");continue;}await step.do(coordinates(runId,attempt,"claim"),async()=>{await storage.claimStep(runId,stepDefinition.id,inputText);return {status:"claimed"};});continue;}
  detail=await storage.getRun(runId);attempt=detail!.attempts.filter(item=>item.stepId===stepDefinition.id).at(-1)!;
  if(attempt.status==="starting"){await step.do(coordinates(runId,attempt,"start"),async()=>{try{const call=invocation(detail!,attempt,resolveConnection),adapter=adapters.get(call.connection.adapter);if(!adapter)throw Object.assign(new Error("adapter unavailable"),{category:"configuration_invalid"});const result=await adapter.start(call);if(result.state==="pending")await storage.persistProviderTask(runId,attempt.stepId,attempt.iteration,attempt.attempt,result.taskId);else if(Buffer.byteLength(result.outputText,"utf8")>MAX_OUTPUT)throw Object.assign(new Error("large"),{category:"output_too_large"});else await storage.completeStep(runId,attempt.stepId,attempt.iteration,attempt.attempt,result.outputText);return {state:result.state};}catch(error){const failure=safeFailure(error);await storage.failStep(runId,attempt.stepId,attempt.iteration,attempt.attempt,failure);return {state:"failed"};}});continue;}
  if(attempt.status==="waiting_provider"){const count=await step.do(coordinates(runId,attempt,"poll"),()=>storage.incrementPollCount(runId,attempt.stepId,attempt.iteration,attempt.attempt));const delay=Math.max(MIN_POLL,Math.min(MAX_POLL,DEFAULT_POLL));await step.sleep(coordinates(runId,{...attempt,providerPollCount:count},"sleep",count),delay);detail=await storage.getRun(runId);if(detail?.run.status==="cancelling"||detail?.run.cancelRequestedAt)continue;await step.do(coordinates(runId,{...attempt,providerPollCount:count},"check",count),async()=>{try{const current=(await storage.getRun(runId))!,latest=current.attempts.filter(item=>item.stepId===attempt.stepId).at(-1)!,call=invocation(current,latest,resolveConnection),adapter=adapters.get(call.connection.adapter);if(!adapter||!latest.providerTaskId)throw Object.assign(new Error("invalid provider state"),{category:"configuration_invalid"});const result=await adapter.check(latest.providerTaskId,call);if(result.state==="completed"){if(Buffer.byteLength(result.outputText,"utf8")>MAX_OUTPUT)throw Object.assign(new Error("large"),{category:"output_too_large"});await storage.completeStep(runId,latest.stepId,latest.iteration,latest.attempt,result.outputText);}else if(result.state==="failed")await storage.failStep(runId,latest.stepId,latest.iteration,latest.attempt,{category:result.category,safeMessage:result.safeMessage,retryable:result.retryable});return {state:result.state};}catch(error){const failure=safeFailure(error);await storage.failStep(runId,attempt.stepId,attempt.iteration,attempt.attempt,failure);return {state:"failed"};}});continue;}
  if(attempt.status==="failed"){if(attempt.retryable&&transient.has(attempt.failureCategory!)&&attempt.attempt<3){await step.do(coordinates(runId,attempt,"retry"),async()=>{await storage.failRun(runId,attempt.failureCategory!,attempt.safeFailureMessage??"Provider temporarily unavailable.");await storage.createRetryAttempt(runId,attempt.stepId);return {status:"retrying"};});continue;}await step.do(coordinates(runId,attempt,"fail"),async()=>{await storage.failRun(runId,attempt.failureCategory??"internal_error",attempt.safeFailureMessage??"The workflow step failed.");return {status:"failed"};});continue;}
  if(attempt.status==="succeeded"){const index=detail!.run.workflowSnapshot.steps.findIndex(item=>item.id===stepDefinition.id);if(stepDefinition.onSuccess.type==="complete")await step.do(coordinates(runId,attempt,"complete"),async()=>{await storage.completeRun(runId,attempt.stepId,attempt.outputText??"");return {status:"succeeded"};});else await step.do(coordinates(runId,attempt,"advance"),async()=>{await storage.advance(runId,attempt.stepId,detail!.run.workflowSnapshot.steps[index+1].id);return {status:"advanced"};});continue;}
  if(attempt.status==="cancelled")continue;
 }
}
