import type { AdapterInvocation, FailureCategory } from "./workflow-adapter.ts";
import type { AgentRuntimeResolver } from "./agent-runtime.ts";
import type { ResolvedConnection } from "./workflow-connections.ts";
import type { RunDetail, StepAttempt, WorkflowRunStorage } from "./workflow-storage.ts";

export type DurableStepConfig={retries:{limit:number;delay:number|string}};
export type DurableStep={do<T>(name:string,callback:()=>Promise<T>):Promise<T>;do<T>(name:string,config:DurableStepConfig,callback:()=>Promise<T>):Promise<T>;sleep(name:string,duration:number|string):Promise<void>};
/** Side-effecting external creation/publication must explicitly opt out of platform replay. */
export const NO_PLATFORM_RETRY={retries:{limit:0,delay:0}} as const;
const terminal=new Set(["succeeded","failed","cancelled"]), transient=new Set<FailureCategory>(["rate_limited","provider_unavailable","provider_timeout"]);
const MAX_TEXT=262144,MAX_POLL_DELAY=900_000,DEFAULT_POLL=10_000,MIN_POLL=1_000,MAX_POLLS=720,MAX_RUN_MS=86_400_000,MAX_STEP_MS=7_200_000,MAX_TOTAL_ATTEMPTS=10;
export function clampPollDelay(value:unknown){return typeof value==="number"&&Number.isFinite(value)?Math.max(MIN_POLL,Math.min(MAX_POLL_DELAY,Math.round(value))):DEFAULT_POLL;}
export function safeExternalUrl(value:string|undefined){if(!value)return undefined;try{const url=new URL(value);return url.protocol==="https:"&&!url.username&&!url.password?url.toString():undefined;}catch{return undefined;}}
const safeFailure=(error:unknown):{category:FailureCategory;safeMessage:string;retryable:boolean}=>{
 const category=error&&typeof error==="object"&&"category" in error&&typeof error.category==="string"?error.category:"internal_error";
 const allowed:FailureCategory[]=["configuration_invalid","connection_unavailable","authentication_failed","permission_denied","provider_rejected","provider_start_ambiguous","provider_publish_ambiguous","rate_limited","provider_unavailable","provider_timeout","malformed_response","output_too_large","cancelled","internal_error"];
 const safe=allowed.includes(category as FailureCategory)?category as FailureCategory:"internal_error",diagnostics=error&&typeof error==="object"&&"transportDiagnostics" in error?error.transportDiagnostics:undefined,outcome=diagnostics&&typeof diagnostics==="object"&&"outcome" in diagnostics?diagnostics.outcome:undefined,reason=diagnostics&&typeof diagnostics==="object"&&"reason" in diagnostics?diagnostics.reason:undefined,elapsed=diagnostics&&typeof diagnostics==="object"&&"elapsedMs" in diagnostics&&typeof diagnostics.elapsedMs==="number"?diagnostics.elapsedMs:undefined,explicitRetryable=error&&typeof error==="object"&&"retryable" in error&&typeof error.retryable==="boolean"?error.retryable:undefined;
 const ambiguous=outcome==="timeout"?`The provider request timed out${elapsed!==undefined?` after ${Math.round(elapsed/1000)} seconds`:""} before ADT received a provider task ID. The provider may still have accepted the request, so ADT did not automatically submit another request.`:outcome==="network_error"?"The connection ended before ADT received a provider task ID. The provider may still have accepted the request, so ADT did not automatically submit another request.":"The provider may have accepted the request, so ADT did not automatically start a duplicate. Inspect provider activity before manually retrying if necessary.";
 const localRuntime=reason==="cross_request_io"||reason==="invalid_request_context";
 return {category:safe,safeMessage:localRuntime?"ADT could not start the provider request because the Worker runtime rejected the network operation. No provider response was received.":error&&typeof error==="object"&&"safeMessage" in error&&typeof error.safeMessage==="string"?error.safeMessage:safe==="internal_error"?"The provider operation failed unexpectedly.":safe==="provider_start_ambiguous"?ambiguous:safe==="provider_publish_ambiguous"?"The provider may have opened the pull request. ADT will not blindly request another publication.":`The provider operation failed (${safe.replaceAll("_"," ")}).`,retryable:localRuntime?false:explicitRetryable??transient.has(safe)};
};
function coordinates(runId:string,attempt:StepAttempt,operation:string,poll=attempt.providerPollCount){return `${runId}:${attempt.stepId}:${attempt.iteration}:${attempt.attempt}:${poll}:${operation}`;}
async function invocation(detail:RunDetail,attempt:StepAttempt,resolve:(key:string,snapshot?:import("./workflow-connections.ts").ConnectionDescriptor)=>Promise<ResolvedConnection>):Promise<AdapterInvocation>{
 const agent=detail.run.agentSnapshots[attempt.agentId],snapshot=detail.run.connectionSnapshots[attempt.connectionKey],live=await resolve(attempt.connectionKey,snapshot);
 if(!snapshot||!live.enabled||snapshot.adapter!==live.adapter)throw Object.assign(new Error("connection unavailable"),{category:"connection_unavailable"});
 return {runId:detail.run.id,stepId:attempt.stepId,iteration:attempt.iteration,attempt:attempt.attempt,providerPollCount:attempt.providerPollCount,idempotencyKey:`${detail.run.id}:${attempt.stepId}:${attempt.iteration}:${attempt.attempt}`,agentName:agent.name,masterPrompt:agent.masterPrompt,inputText:attempt.inputText??"",tools:agent.tools,connection:{...snapshot,credential:live.credential,serverConfiguration:live.serverConfiguration,privateOptions:{...(live.privateOptions&&typeof live.privateOptions==="object"?live.privateOptions:{}),providerState:attempt.providerState,outputText:attempt.outputText}},providerOptions:agent.adapterOptions};
}
export async function executeDurableWorkflow(input:{runId:string;storage:WorkflowRunStorage;runtimes:AgentRuntimeResolver;resolveConnection:(key:string,snapshot?:import("./workflow-connections.ts").ConnectionDescriptor)=>Promise<ResolvedConnection>;step:DurableStep}){
 const {runId,storage,runtimes,resolveConnection,step}=input;
 for(;;){let detail=await storage.getRun(runId);if(!detail)throw new Error("run_not_found");if(terminal.has(detail.run.status))return {runId,status:detail.run.status};
  if(detail.run.status!=="cancelling"){if(Date.now()-Date.parse(detail.run.createdAt)>MAX_RUN_MS){await storage.failRun(runId,"provider_timeout","The workflow run exceeded its time limit.");continue;}if(detail.run.workflowSnapshot.steps.length>32||detail.run.transitionCount>=detail.run.workflowSnapshot.limits.maxStepExecutions){await storage.failRun(runId,"internal_error","The workflow execution limit was reached.");continue;}}
  const currentRun=detail.run,stepDefinition=currentRun.workflowSnapshot.steps.find(item=>item.id===currentRun.currentStepId);if(!stepDefinition){await step.do(`${runId}:cursor:0:0:0:fail`,async()=>{await storage.failRun(runId,"internal_error","The workflow cursor is invalid.");return {status:"failed"};});continue;}
  let attempt=detail.attempts.filter(item=>item.stepId===stepDefinition.id).at(-1)!;
  if(detail.run.status==="cancelling"||detail.run.cancelRequestedAt){const result=await step.do(coordinates(runId,attempt,"cancel"),async()=>{let outcome:"cancelled"|"cancellation_pending"|"already_terminal"|"unsupported"|"safe_failure"="already_terminal";try{if(attempt.providerTaskId){const call=await invocation(detail!,attempt,resolveConnection),runtime=runtimes.resolve(call.connection.adapter);outcome=runtime?await runtime.cancel(attempt.providerTaskId,call):"unsupported";}}catch{outcome="safe_failure";}await storage.recordCancellationResult(runId,outcome);if(outcome!=="cancellation_pending")await storage.cancelRun(runId);return {status:outcome==="cancellation_pending"?"cancelling" as const:"cancelled" as const,outcome};});if(result.outcome==="cancellation_pending"){if(attempt.status!=="waiting_provider"||!attempt.providerTaskId)throw new Error("invalid_cancellation_pending");if(attempt.providerPollCount>=MAX_POLLS){await step.do(coordinates(runId,attempt,"cancel-exhausted"),async()=>{await storage.recordCancellationResult(runId,"safe_failure");await storage.cancelRun(runId);return {status:"cancelled" as const,outcome:"safe_failure" as const}});continue}const delay=Math.min(5000,clampPollDelay(attempt.nextPollDelayMs)),count=await step.do(coordinates(runId,attempt,"cancel-poll"),()=>storage.incrementPollCount(runId,attempt.stepId,attempt.iteration,attempt.attempt,delay));await step.sleep(coordinates(runId,{...attempt,providerPollCount:count},"cancel-sleep",count),delay)}continue;}
  if(attempt.status==="pending"){const index=detail.run.workflowSnapshot.steps.indexOf(stepDefinition),previous=index?detail.attempts.filter(item=>item.stepId===detail!.run.workflowSnapshot.steps[index-1].id&&item.status==="succeeded").at(-1):undefined,inputText=index?previous?.outputText:detail.run.initialInput;if(inputText===undefined){await storage.failRun(runId,"internal_error","The previous step output is unavailable.");continue;}if(Buffer.byteLength(inputText,"utf8")>MAX_TEXT){await storage.failRun(runId,"output_too_large","The step input exceeds the allowed size.");continue;}await step.do(coordinates(runId,attempt,"claim"),async()=>{await storage.claimStep(runId,stepDefinition.id,inputText);return {status:"claimed"};});continue;}
  detail=await storage.getRun(runId);attempt=detail!.attempts.filter(item=>item.stepId===stepDefinition.id).at(-1)!;
  if(attempt.status==="starting"){await step.do(coordinates(runId,attempt,"start"),NO_PLATFORM_RETRY,async()=>{const current=await storage.getRun(runId);if(current?.run.status==="cancelling"||current?.run.cancelRequestedAt)return {state:"cancelled"};try{const call=await invocation(current!,attempt,resolveConnection),runtime=runtimes.resolve(call.connection.adapter);if(!runtime)throw Object.assign(new Error("runtime unavailable"),{category:"configuration_invalid"});const result=await runtime.start(call);if(result.transportDiagnostics)await storage.recordProviderDiagnostics(runId,attempt.stepId,attempt.iteration,attempt.attempt,result.transportDiagnostics);if(result.state==="pending"){await storage.persistProviderTask(runId,attempt.stepId,attempt.iteration,attempt.attempt,result.taskId,clampPollDelay(result.pollAfterMs));if(result.providerState||result.outputText||result.taskUrl)await storage.persistProviderProgress(runId,attempt.stepId,attempt.iteration,attempt.attempt,result.providerState??"pending",clampPollDelay(result.pollAfterMs),result.outputText,safeExternalUrl(result.taskUrl));}else if(Buffer.byteLength(result.outputText,"utf8")>MAX_TEXT)throw Object.assign(new Error("large"),{category:"output_too_large"});else await storage.completeStep(runId,attempt.stepId,attempt.iteration,attempt.attempt,result.outputText,safeExternalUrl(result.externalUrl));return {state:result.state};}catch(error){if(error&&typeof error==="object"&&"transportDiagnostics" in error&&error.transportDiagnostics)await storage.recordProviderDiagnostics(runId,attempt.stepId,attempt.iteration,attempt.attempt,error.transportDiagnostics as import("./workflow-adapter.ts").ProviderTransportDiagnostics);const failure=safeFailure(error);await storage.failStep(runId,attempt.stepId,attempt.iteration,attempt.attempt,failure);return {state:"failed"};}});continue;}
  if(attempt.status==="waiting_provider"){if(attempt.providerPollCount>=MAX_POLLS||!attempt.startedAt||Date.now()-Date.parse(attempt.startedAt)>MAX_STEP_MS){await storage.failStep(runId,attempt.stepId,attempt.iteration,attempt.attempt,{category:"provider_timeout",safeMessage:"The provider step exceeded its polling limit.",retryable:false});continue;}const delay=clampPollDelay(attempt.nextPollDelayMs),count=await step.do(coordinates(runId,attempt,"poll"),()=>storage.incrementPollCount(runId,attempt.stepId,attempt.iteration,attempt.attempt,delay));await step.sleep(coordinates(runId,{...attempt,providerPollCount:count},"sleep",count),delay);detail=await storage.getRun(runId);if(detail?.run.status==="cancelling"||detail?.run.cancelRequestedAt)continue;await step.do(coordinates(runId,{...attempt,providerPollCount:count},"check",count),async()=>{try{const current=(await storage.getRun(runId))!,latest=current.attempts.filter(item=>item.stepId===attempt.stepId).at(-1)!,call=await invocation(current,latest,resolveConnection),runtime=runtimes.resolve(call.connection.adapter);if(!runtime||!latest.providerTaskId)throw Object.assign(new Error("invalid provider state"),{category:"configuration_invalid"});const result=await runtime.check(latest.providerTaskId,call);if(result.state==="completed"){if(Buffer.byteLength(result.outputText,"utf8")>MAX_TEXT)throw Object.assign(new Error("large"),{category:"output_too_large"});await storage.completeStep(runId,latest.stepId,latest.iteration,latest.attempt,result.outputText,safeExternalUrl(result.externalUrl));}else if(result.state==="pending"){if(result.providerState||result.outputText||result.taskUrl)await storage.persistProviderProgress(runId,latest.stepId,latest.iteration,latest.attempt,result.providerState??latest.providerState??"pending",clampPollDelay(result.pollAfterMs),result.outputText,safeExternalUrl(result.taskUrl));else await storage.persistProviderTask(runId,latest.stepId,latest.iteration,latest.attempt,latest.providerTaskId,clampPollDelay(result.pollAfterMs));}else await storage.failStep(runId,latest.stepId,latest.iteration,latest.attempt,{category:result.category,safeMessage:result.safeMessage,retryable:result.retryable});return {state:result.state};}catch(error){const failure=safeFailure(error);await storage.failStep(runId,attempt.stepId,attempt.iteration,attempt.attempt,failure);return {state:"failed"};}});continue;}
  if(attempt.status==="failed"){const total=detail!.attempts.filter(item=>item.stepId===attempt.stepId).length;if(attempt.retryable&&transient.has(attempt.failureCategory!)&&attempt.attempt<3&&total<MAX_TOTAL_ATTEMPTS){const delay=attempt.attempt===1?10_000:30_000;await step.sleep(coordinates(runId,attempt,"retry-backoff"),delay);await step.do(coordinates(runId,attempt,"automatic-retry"),async()=>{await storage.createAutomaticRetryAttempt(runId,attempt.stepId);return {status:"retrying"};});continue;}await step.do(coordinates(runId,attempt,"fail"),async()=>{await storage.failRun(runId,attempt.failureCategory??"internal_error",attempt.safeFailureMessage??"The workflow step failed.");return {status:"failed"};});continue;}
  if(attempt.status==="succeeded"){const index=detail!.run.workflowSnapshot.steps.findIndex(item=>item.id===stepDefinition.id);if(stepDefinition.onSuccess.type==="complete")await step.do(coordinates(runId,attempt,"complete"),async()=>{await storage.completeRun(runId,attempt.stepId,attempt.outputText??"",safeExternalUrl(attempt.outputExternalUrl));return {status:"succeeded"};});else await step.do(coordinates(runId,attempt,"advance"),async()=>{await storage.advance(runId,attempt.stepId,detail!.run.workflowSnapshot.steps[index+1].id);return {status:"advanced"};});continue;}
  if(attempt.status==="cancelled")continue;
 }
}
