import type {CancellationResult,RunStatus,WorkflowRun} from "./workflow-storage.ts";
import {workflowBlockRegistry} from "./workflow-block-registry.ts";
const terminalRunStatuses=new Set<RunStatus>(["succeeded","failed","cancelled"]);
export function workflowRunPresentation(status:RunStatus,cancellationResult?:CancellationResult){const cancellationPending=status==="cancelling"&&cancellationResult==="cancellation_pending";const cancellationMessage=cancellationPending?"Cancellation requested. External Codex work is still stopping.":cancellationResult==="safe_failure"?"Provider cancellation could not be confirmed safely.":cancellationResult==="unsupported"?"External cancellation was unsupported; external work may continue, but local workflow progression stopped.":undefined;return {terminal:terminalRunStatuses.has(status),cancellationPending,cancellationMessage};}
export function workflowRunNodeLabel(run:WorkflowRun,nodeId:string){const provenance=run.compositionSnapshot?.nodes.find(item=>item.executionNodeId===nodeId),planNode=run.executionPlan&&"planVersion" in run.executionPlan?run.executionPlan.nodes.find(item=>item.id===nodeId):undefined,agentId=planNode?.blockType==="agent"?planNode.config.agentId:undefined,blockLabel=planNode&&planNode.blockType!=="agent"?workflowBlockRegistry.metadata().find(item=>item.type===planNode.blockType&&item.version===planNode.blockVersion)?.ui.label:undefined,leaf=agentId?run.agentSnapshots[agentId]?.name:blockLabel??provenance?.semanticNodeId;if(!provenance)return leaf??nodeId;return[run.semanticWorkflowSnapshot?.name,...provenance.invocationPath.map(item=>`${item.workflowName} (${item.invocationNodeId})`),leaf??provenance.semanticNodeId].filter(Boolean).join(" / ")}

export function workflowRunName(run:WorkflowRun){return run.semanticWorkflowSnapshot?.name??run.workflowSnapshot?.name??run.workflowId;}

import type {WorkflowOrchestrationStage} from "./workflow-orchestration-diagnostics.ts";
const orchestrationStagePresentation:Record<WorkflowOrchestrationStage,{label:string;guidance:string}>={runtime_readiness:{label:"ADT Runtime readiness",guidance:"Open Diagnostics and check ADT Runtime readiness."},runtime_transport:{label:"ADT Runtime transport",guidance:"Open Diagnostics and test ADT Runtime reachability."},checkpoint_gateway:{label:"Checkpoint gateway",guidance:"Open Diagnostics and run Test execution path; inspect the Checkpoint gateway result."},graph_node_gateway:{label:"Graph-node gateway",guidance:"Open Diagnostics and run Test execution path; inspect the Graph-node gateway result."},runtime_response:{label:"ADT Runtime response",guidance:"Open Diagnostics and test the ADT Runtime execution path. Use the request ID for safe log correlation if further investigation is required."},runtime_langgraph:{label:"LangGraph orchestration",guidance:"Open Diagnostics and test the ADT Runtime execution path. Use the request ID for safe log correlation if further investigation is required."}};
export function workflowOrchestrationDiagnosticPresentation(stage:WorkflowOrchestrationStage){return orchestrationStagePresentation[stage]}
