import {z} from "zod";
import type {WorkflowD1Database} from "./workflow-d1-storage.ts";

export const approvalRequestIdSchema=z.string().uuid();
export const approvalEventType=(requestId:string)=>`approval-${approvalRequestIdSchema.parse(requestId)}`;
export type WorkflowApproval={requestId:string;runId:string;workflowGeneration:number;nodeId:string;activationId:string;interruptId:string;message:string;reviewText:string;status:"pending"|"approved";requestedAt:string;approvedAt?:string;consumedAt?:string};
const row=(value:Record<string,unknown>):WorkflowApproval=>({requestId:String(value.request_id),runId:String(value.run_id),workflowGeneration:Number(value.workflow_generation),nodeId:String(value.node_id),activationId:String(value.activation_id),interruptId:String(value.interrupt_id),message:String(value.message),reviewText:String(value.review_text),status:value.status as "pending"|"approved",requestedAt:String(value.requested_at),approvedAt:value.approved_at?String(value.approved_at):undefined,consumedAt:value.consumed_at?String(value.consumed_at):undefined});
const exact=(approval:WorkflowApproval,input:{nodeId:string;interruptId:string;message:string;reviewText:string})=>approval.nodeId===input.nodeId&&approval.interruptId===input.interruptId&&approval.message===input.message&&approval.reviewText===input.reviewText;
export class D1WorkflowApprovalStore{
 private db:WorkflowD1Database;private clock:()=>string;constructor(db:WorkflowD1Database,clock:()=>string=()=>new Date().toISOString()){this.db=db;this.clock=clock}
 async active(runId:string){const value=await this.db.prepare("SELECT * FROM workflow_approvals WHERE run_id=? AND consumed_at IS NULL ORDER BY requested_at DESC LIMIT 1").bind(runId).first<Record<string,unknown>>();return value?row(value):undefined}
 async pending(runId:string){return this.active(runId)}
 async get(requestId:string){const value=await this.db.prepare("SELECT * FROM workflow_approvals WHERE request_id=?").bind(approvalRequestIdSchema.parse(requestId)).first<Record<string,unknown>>();return value?row(value):undefined}
 async require(input:{runId:string;workflowGeneration:number;nodeId:string;activationId:string;interruptId:string;message:string;reviewText:string}){if(Buffer.byteLength(input.reviewText,"utf8")>262144||input.message.length>2000||input.activationId.length>256||input.interruptId.length>256)throw new Error("approval_invalid");const find=()=>this.db.prepare("SELECT * FROM workflow_approvals WHERE run_id=? AND workflow_generation=? AND activation_id=?").bind(input.runId,input.workflowGeneration,input.activationId).first<Record<string,unknown>>();let existing=await find();if(existing){const parsed=row(existing);if(!exact(parsed,input))throw new Error("approval_conflict");return parsed}const requestId=crypto.randomUUID(),now=this.clock();try{await this.db.prepare("INSERT INTO workflow_approvals(request_id,run_id,workflow_generation,node_id,activation_id,interrupt_id,message,review_text,status,requested_at) SELECT ?,?,?,?,?,?,?,?,'pending',? WHERE EXISTS(SELECT 1 FROM workflow_runs WHERE id=? AND workflow_generation=? AND status IN ('queued','running','waiting_approval') AND cancel_requested_at IS NULL)").bind(requestId,input.runId,input.workflowGeneration,input.nodeId,input.activationId,input.interruptId,input.message,input.reviewText,now,input.runId,input.workflowGeneration).run()}catch{existing=await find();if(existing){const parsed=row(existing);if(!exact(parsed,input))throw new Error("approval_conflict");return parsed}throw new Error("approval_not_pending")}const created=await this.get(requestId);if(!created){existing=await find();if(existing){const parsed=row(existing);if(!exact(parsed,input))throw new Error("approval_conflict");return parsed}throw new Error("approval_not_pending")}const changed=await this.db.prepare("UPDATE workflow_runs SET status='waiting_approval',current_step_id=?,updated_at=?,state_version=state_version+1 WHERE id=? AND workflow_generation=? AND status IN ('queued','running','waiting_approval') AND cancel_requested_at IS NULL").bind(input.nodeId,now,input.runId,input.workflowGeneration).run();if(changed.meta?.changes!==1){const run=await this.db.prepare("SELECT status,cancel_requested_at FROM workflow_runs WHERE id=?").bind(input.runId).first<{status:string;cancel_requested_at:string|null}>();if(run?.status!=="cancelling"&&run?.status!=="cancelled"&&!run?.cancel_requested_at)throw new Error("approval_not_pending")}return created}
 async approve(runId:string,requestId:string){approvalRequestIdSchema.parse(requestId);const now=this.clock(),result=await this.db.prepare("UPDATE workflow_approvals SET status='approved',approved_at=COALESCE(approved_at,?) WHERE request_id=? AND run_id=? AND status='pending' AND consumed_at IS NULL AND EXISTS(SELECT 1 FROM workflow_runs WHERE id=? AND workflow_generation=workflow_approvals.workflow_generation AND status='waiting_approval' AND cancel_requested_at IS NULL)").bind(now,requestId,runId,runId).run(),approval=await this.get(requestId);if(result.meta?.changes===1)return{approval:approval!,idempotent:false as const,wakeRequired:true as const};if(approval?.runId===runId&&approval.status==='approved'){const run=await this.db.prepare("SELECT status,cancel_requested_at FROM workflow_runs WHERE id=?").bind(runId).first<{status:string;cancel_requested_at:string|null}>();if(run&&!run.cancel_requested_at&&!['cancelling','cancelled','failed'].includes(run.status))return{approval,idempotent:true as const,wakeRequired:!approval.consumedAt}}throw new Error(approval&&approval.runId!==runId?"approval_wrong_run":"approval_not_pending")}
 async consume(runId:string,requestId:string){const now=this.clock(),[resumed,consumed]=await this.db.batch([this.db.prepare("UPDATE workflow_runs SET status='running',updated_at=?,state_version=state_version+1 WHERE id=? AND status='waiting_approval' AND cancel_requested_at IS NULL AND EXISTS(SELECT 1 FROM workflow_approvals WHERE request_id=? AND run_id=? AND status='approved' AND consumed_at IS NULL)").bind(now,runId,requestId,runId),this.db.prepare("UPDATE workflow_approvals SET consumed_at=? WHERE request_id=? AND run_id=? AND status='approved' AND consumed_at IS NULL AND EXISTS(SELECT 1 FROM workflow_runs WHERE id=? AND status='running' AND cancel_requested_at IS NULL)").bind(now,requestId,runId,runId)]);if(resumed.meta?.changes!==1){if(consumed.meta?.changes)throw new Error("approval_consume_conflict");return false}if(consumed.meta?.changes!==1)throw new Error("approval_consume_conflict");return true}
 async suspendedMs(runId:string){const value=await this.db.prepare("SELECT COALESCE(SUM((julianday(COALESCE(consumed_at,?))-julianday(requested_at))*86400000),0) AS value FROM workflow_approvals WHERE run_id=?").bind(this.clock(),runId).first<{value:number}>();return Math.max(0,Number(value?.value??0))}
}
