import {workIqRestOptionsSchema,type AdapterInvocation,type AdapterResult,type AgentProviderAdapter,type ConnectionTestResult,type FailureCategory} from "./workflow-adapter.ts";import type {ConnectionDescriptor,ResolvedConnection} from "./workflow-connections.ts";import {classifyTransportException,isLocalRuntimeTransportRejection} from "./safe-transport-exception.ts";
export const WORK_IQ_ENDPOINT="https://workiq.svc.cloud.microsoft",WORK_IQ_EXECUTION_TIMEOUT_MS=120_000,WORK_IQ_TEST_TIMEOUT_MS=30_000;
const MAX_OUTPUT=262144,object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v),failure=(category:FailureCategory)=>Object.assign(new Error(category),{category});type Fetcher=(input:string|URL,init?:RequestInit)=>Promise<Response>;
export function frameWorkIqMessage(instructions:string,input:string){return `Instructions:\n${instructions}\n\nWorkflow input:\n${input}`}
export function extractWorkIqResponse(value:unknown,submitted:string){if(!object(value))throw failure("malformed_response");if(value.state==="disengagedForRai")throw failure("provider_rejected");if(!Array.isArray(value.messages))throw failure("malformed_response");const texts=value.messages.flatMap(message=>object(message)&&typeof message.text==="string"?[message.text]:[]);const answer=[...texts].reverse().find(text=>text!==submitted);if(!answer)throw failure("malformed_response");if(answer.length>MAX_OUTPUT)throw failure("output_too_large");return answer}
export class WorkIqRestAdapter implements AgentProviderAdapter{readonly kind="work-iq-rest";private fetcher:Fetcher;private executionTimeoutMs:number;private testTimeoutMs:number;constructor(fetcher:Fetcher=fetch,executionTimeoutMs=WORK_IQ_EXECUTION_TIMEOUT_MS,testTimeoutMs=WORK_IQ_TEST_TIMEOUT_MS){this.fetcher=fetcher;this.executionTimeoutMs=executionTimeoutMs;this.testTimeoutMs=testTimeoutMs}
 async validateConnection(d:ConnectionDescriptor){return d.adapter===this.kind&&d.endpoint===WORK_IQ_ENDPOINT&&d.enabled?{ok:true as const}:{ok:false as const,safeMessage:"The Microsoft 365 account is not connected."}}
 private http(status:number){if(status===401)return failure("authentication_failed");if(status===403)return failure("permission_denied");if(status===429)return failure("rate_limited");if(status>=500)return failure("provider_start_ambiguous");return failure("provider_rejected")}
 private async post(path:string,credential:string,body:unknown,timeoutMs:number,expectedStatus:number){const controller=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;try{const timeout=new Promise<never>((_,reject)=>{timer=setTimeout(()=>{controller.abort();reject(failure("provider_start_ambiguous"))},timeoutMs)});let response:Response;try{response=await Promise.race([this.fetcher(`${WORK_IQ_ENDPOINT}${path}`,{method:"POST",headers:{authorization:`Bearer ${credential}`,"content-type":"application/json"},body:JSON.stringify(body),signal:controller.signal}),timeout])}catch(error){if(object(error)&&"category" in error)throw error;const reason=classifyTransportException(error);throw failure(isLocalRuntimeTransportRejection(reason.reason)?"internal_error":"provider_start_ambiguous")}if(!response.ok)throw this.http(response.status);if(response.status!==expectedStatus)throw failure("malformed_response");try{return await response.json()}catch{throw failure("malformed_response")}}finally{if(timer)clearTimeout(timer)}}
 private validate(c:ResolvedConnection){if(c.adapter!==this.kind||c.endpoint!==WORK_IQ_ENDPOINT||!c.enabled||typeof c.credential!=="string"||!c.credential)throw failure("connection_unavailable")}
 private async invoke(connection:ResolvedConnection,message:string,timeZone:string,webGroundingEnabled:boolean,timeout:number){this.validate(connection);const created=await this.post("/rest/conversations",connection.credential!,{},timeout,201);if(!object(created)||typeof created.id!=="string"||!created.id||created.id.length>256||!/^[A-Za-z0-9._-]+$/.test(created.id))throw failure("malformed_response");const body:Record<string,unknown>={message:{text:message},locationHint:{timeZone}};if(!webGroundingEnabled)body.contextualResources={webContext:{isWebEnabled:false}};return extractWorkIqResponse(await this.post(`/rest/conversations/${encodeURIComponent(created.id)}/chat`,connection.credential!,body,timeout,200),message)}
 async start(i:AdapterInvocation):Promise<AdapterResult>{const options=workIqRestOptionsSchema.parse(i.providerOptions??{}),message=frameWorkIqMessage(i.masterPrompt,i.inputText);return{state:"completed",outputText:await this.invoke(i.connection,message,options.timeZone,options.webGroundingEnabled!==false,this.executionTimeoutMs)}}
 async check():Promise<never>{throw failure("configuration_invalid")}async cancel(){return"unsupported" as const}
 async testConnection(connection:ResolvedConnection):Promise<ConnectionTestResult>{try{return{ok:true,outputText:(await this.invoke(connection,"Reply with OK.","Etc/UTC",true,this.testTimeoutMs)).slice(0,100)}}catch(error){const category=object(error)&&typeof error.category==="string"?error.category as FailureCategory:"internal_error";return{ok:false,category,safeMessage:category==="authentication_failed"?"Microsoft authentication failed; reconnect the account.":category==="permission_denied"?"Microsoft denied permission. Check tenant enablement and administrator consent.":"The Work IQ connection test could not be completed."}}}}
