import type {FailureCategory,ProviderTransportDiagnostics} from "./workflow-adapter.ts";
export const MAX_WORKFLOW_ORCHESTRATION_DIAGNOSTIC_BYTES=4096;
export const workflowOrchestrationStages=["runtime_readiness","runtime_transport","checkpoint_gateway","graph_node_gateway","runtime_response","runtime_langgraph"] as const;
export const workflowOrchestrationCodes=["capability_unavailable","authentication_failed","protocol_incompatible","runtime_unavailable","timeout","network_error","checkpoint_unavailable","checkpoint_authority_invalid","checkpoint_backend_unavailable","checkpoint_state_conflicting","checkpoint_state_invalid","graph_node_unavailable","graph_node_authority_invalid","graph_node_backend_unavailable","malformed_response","execution_failed"] as const;
export type WorkflowOrchestrationStage=typeof workflowOrchestrationStages[number];export type WorkflowOrchestrationCode=typeof workflowOrchestrationCodes[number];
export type RuntimeOrchestrationEvidence={stage:"checkpoint_gateway"|"graph_node_gateway";code:WorkflowOrchestrationCode;httpStatus?:number;transportOutcome?:"response_received"|"timeout"|"network_error"};
export type WorkflowOrchestrationDiagnostic={version:1;stage:WorkflowOrchestrationStage;category:FailureCategory;runtimeCode?:string;orchestrationCode:WorkflowOrchestrationCode;transport?:Pick<ProviderTransportDiagnostics,"outcome"|"reason"|"runtimeErrorName"|"httpStatus"|"elapsedMs"|"clientRequestId">;consecutiveFailures:number;recoveryRetriesAllowed:number;observedAt:string};
const stages=new Set<string>(workflowOrchestrationStages),codes=new Set<string>(workflowOrchestrationCodes),categories=new Set<string>(["authentication_failed","configuration_invalid","connection_unavailable","provider_unavailable","provider_rejected","provider_timeout","provider_start_ambiguous","malformed_response","output_too_large","internal_error"]),outcomes=new Set(["response_received","timeout","network_error"]),reasons=new Set(["cross_request_io","invalid_request_context","network_connection_lost","aborted","fetch_type_error","unknown"]),errorNames=new Set(["AbortError","TypeError","Error"]);
const integer=(value:unknown,min:number,max:number)=>Number.isInteger(value)&&Number(value)>=min&&Number(value)<=max,identifier=(value:unknown,max=256)=>typeof value==="string"&&value.length>0&&value.length<=max&&/^[A-Za-z0-9:_-]+$/.test(value);
export function parseWorkflowOrchestrationDiagnostic(value:unknown):WorkflowOrchestrationDiagnostic|undefined{if(!value||Array.isArray(value)||typeof value!=="object")return;const v=value as Record<string,unknown>;if(Object.keys(v).some(key=>!["version","stage","category","runtimeCode","orchestrationCode","transport","consecutiveFailures","recoveryRetriesAllowed","observedAt"].includes(key))||v.version!==1||!stages.has(String(v.stage))||!categories.has(String(v.category))||!codes.has(String(v.orchestrationCode))||!integer(v.consecutiveFailures,1,32769)||!integer(v.recoveryRetriesAllowed,0,32768)||typeof v.observedAt!=="string"||!Number.isFinite(Date.parse(v.observedAt))||v.runtimeCode!==undefined&&!identifier(v.runtimeCode,64))return;let transport:WorkflowOrchestrationDiagnostic["transport"];if(v.transport!==undefined){if(!v.transport||Array.isArray(v.transport)||typeof v.transport!=="object")return;const t=v.transport as Record<string,unknown>;if(Object.keys(t).some(key=>!["outcome","reason","runtimeErrorName","httpStatus","elapsedMs","clientRequestId"].includes(key))||!outcomes.has(String(t.outcome))||t.reason!==undefined&&!reasons.has(String(t.reason))||t.runtimeErrorName!==undefined&&!errorNames.has(String(t.runtimeErrorName))||t.httpStatus!==undefined&&!integer(t.httpStatus,100,599)||!integer(t.elapsedMs,0,3_600_000)||!identifier(t.clientRequestId))return;transport=t as WorkflowOrchestrationDiagnostic["transport"]}const parsed={version:1,stage:v.stage,category:v.category,...(v.runtimeCode===undefined?{}:{runtimeCode:v.runtimeCode}),orchestrationCode:v.orchestrationCode,...(transport?{transport}:{}),consecutiveFailures:v.consecutiveFailures,recoveryRetriesAllowed:v.recoveryRetriesAllowed,observedAt:v.observedAt} as WorkflowOrchestrationDiagnostic;return new TextEncoder().encode(JSON.stringify(parsed)).byteLength<=MAX_WORKFLOW_ORCHESTRATION_DIAGNOSTIC_BYTES?parsed:undefined}
export function serializeWorkflowOrchestrationDiagnostic(value:WorkflowOrchestrationDiagnostic){const parsed=parseWorkflowOrchestrationDiagnostic(value);if(!parsed)throw new Error("invalid_orchestration_diagnostic");return JSON.stringify(parsed)}
export function parseRuntimeOrchestrationEvidence(value:unknown):RuntimeOrchestrationEvidence|undefined{if(!value||Array.isArray(value)||typeof value!=="object")return;const v=value as Record<string,unknown>;if(Object.keys(v).some(key=>!["stage","code","httpStatus","transportOutcome"].includes(key))||!["checkpoint_gateway","graph_node_gateway"].includes(String(v.stage))||!codes.has(String(v.code))||v.httpStatus!==undefined&&!integer(v.httpStatus,100,599)||v.transportOutcome!==undefined&&!outcomes.has(String(v.transportOutcome)))return;return v as RuntimeOrchestrationEvidence}
