import type { AdapterInvocation, FailureCategory } from "./workflow-adapter.ts";
import type { AgentRuntimeResolver } from "./agent-runtime.ts";
import type { ResolvedConnection } from "./workflow-connections.ts";
import type { RunDetail, StepAttempt, WorkflowRunStorage } from "./workflow-storage.ts";

export type DurableStepConfig={retries:{limit:number;delay:number|string}};
export type DurableStep={do<T>(name:string,callback:()=>Promise<T>):Promise<T>;do<T>(name:string,config:DurableStepConfig,callback:()=>Promise<T>):Promise<T>;sleep(name:string,duration:number|string):Promise<void>};
/** Side-effecting external creation/publication must explicitly opt out of platform replay. */
export const NO_PLATFORM_RETRY={retries:{limit:0,delay:0}} as const;
const transient=new Set<FailureCategory>(["rate_limited","provider_unavailable","provider_timeout"]);
const MAX_TEXT=262144,MAX_POLL_DELAY=900_000,DEFAULT_POLL=10_000,MIN_POLL=1_000,MAX_TOTAL_ATTEMPTS=10;
export const MAX_PROVIDER_POLLS=720,MAX_WORKFLOW_RUN_MS=86_400_000,MAX_PROVIDER_STEP_MS=7_200_000,GRAPH_START_UNCERTAINTY_MS=2*60_000;
export function clampPollDelay(value:unknown){return typeof value==="number"&&Number.isFinite(value)?Math.max(MIN_POLL,Math.min(MAX_POLL_DELAY,Math.round(value))):DEFAULT_POLL;}
export function safeExternalUrl(value:string|undefined){if(!value)return undefined;try{const url=new URL(value);return url.protocol==="https:"&&!url.username&&!url.password?url.toString():undefined;}catch{return undefined;}}
export const durableSafeFailure=(error:unknown):{category:FailureCategory;safeMessage:string;retryable:boolean}=>{
 const category=error&&typeof error==="object"&&"category" in error&&typeof error.category==="string"?error.category:"internal_error";
 const allowed:FailureCategory[]=["configuration_invalid","connection_unavailable","authentication_failed","permission_denied","provider_rejected","provider_start_ambiguous","provider_publish_ambiguous","rate_limited","provider_unavailable","provider_timeout","malformed_response","output_too_large","cancelled","internal_error"];
 const safe=allowed.includes(category as FailureCategory)?category as FailureCategory:"internal_error",diagnostics=error&&typeof error==="object"&&"transportDiagnostics" in error?error.transportDiagnostics:undefined,outcome=diagnostics&&typeof diagnostics==="object"&&"outcome" in diagnostics?diagnostics.outcome:undefined,reason=diagnostics&&typeof diagnostics==="object"&&"reason" in diagnostics?diagnostics.reason:undefined,elapsed=diagnostics&&typeof diagnostics==="object"&&"elapsedMs" in diagnostics&&typeof diagnostics.elapsedMs==="number"?diagnostics.elapsedMs:undefined,explicitRetryable=error&&typeof error==="object"&&"retryable" in error&&typeof error.retryable==="boolean"?error.retryable:undefined;
 const ambiguous=outcome==="timeout"?`The provider request timed out${elapsed!==undefined?` after ${Math.round(elapsed/1000)} seconds`:""} before ADT received a provider task ID. The provider may still have accepted the request, so ADT did not automatically submit another request.`:outcome==="network_error"?"The connection ended before ADT received a provider task ID. The provider may still have accepted the request, so ADT did not automatically submit another request.":"The provider may have accepted the request, so ADT did not automatically start a duplicate. Inspect provider activity before manually retrying if necessary.";
 const localRuntime=reason==="cross_request_io"||reason==="invalid_request_context";
 return {category:safe,safeMessage:localRuntime?"ADT could not start the provider request because the Worker runtime rejected the network operation. No provider response was received.":error&&typeof error==="object"&&"safeMessage" in error&&typeof error.safeMessage==="string"?error.safeMessage:safe==="internal_error"?"The provider operation failed unexpectedly.":safe==="provider_start_ambiguous"?ambiguous:safe==="provider_publish_ambiguous"?"The provider may have opened the pull request. ADT will not blindly request another publication.":`The provider operation failed (${safe.replaceAll("_"," ")}).`,retryable:localRuntime?false:explicitRetryable??transient.has(safe)};
};
export async function durableInvocation(detail:RunDetail,attempt:StepAttempt,resolve:(key:string,snapshot?:import("./workflow-connections.ts").ConnectionDescriptor)=>Promise<ResolvedConnection>):Promise<AdapterInvocation>{
 const agent=detail.run.agentSnapshots[attempt.agentId],snapshot=detail.run.connectionSnapshots[attempt.connectionKey],live=await resolve(attempt.connectionKey,snapshot);
 if(!snapshot||!live.enabled||snapshot.adapter!==live.adapter)throw Object.assign(new Error("connection unavailable"),{category:"connection_unavailable"});
 return {runId:detail.run.id,stepId:attempt.stepId,iteration:attempt.iteration,attempt:attempt.attempt,providerPollCount:attempt.providerPollCount,idempotencyKey:`${detail.run.id}:${attempt.stepId}:${attempt.iteration}:${attempt.attempt}`,agentName:agent.name,masterPrompt:agent.masterPrompt,inputText:attempt.inputText??"",tools:agent.tools,repositoryContext:detail.run.repositoryContext,connection:{...snapshot,credential:live.credential,serverConfiguration:live.serverConfiguration,privateOptions:{...(live.privateOptions&&typeof live.privateOptions==="object"?live.privateOptions:{}),providerState:attempt.providerState,outputText:attempt.outputText}},providerOptions:agent.adapterOptions};
}
export type GraphNodeTurnResult={state:"completed"|"pending"|"failed"|"cancelled";outputText?:string;safeMessage?:string;retryAfterMs?:number};
const graphRetryDelay=(attempt:number)=>attempt===1?10_000:30_000;
async function reconcileFailedGraphRun(input:{runId:string;attempt:StepAttempt;detail:RunDetail;storage:WorkflowRunStorage;runtimes:AgentRuntimeResolver;resolveConnection:(key:string,snapshot?:import("./workflow-connections.ts").ConnectionDescriptor)=>Promise<ResolvedConnection>;now:()=>number}):Promise<GraphNodeTurnResult>{
 const {runId,storage,runtimes,resolveConnection,now}=input;let {attempt,detail}=input;const original={category:detail.run.failureCode!,safeMessage:detail.run.failureMessage!};
 const finish=async()=>{const current=(await storage.getRun(runId))!,outstanding=current.attempts.some(item=>item.providerTaskId&&["starting","waiting_provider"].includes(item.status)||item.status==="starting"&&!item.providerTaskId);if(outstanding)return{state:"pending" as const,retryAfterMs:MIN_POLL};await storage.failRun(runId,original.category,original.safeMessage);return{state:"failed" as const,safeMessage:original.safeMessage}};
 if(attempt.status==="starting"&&!attempt.providerTaskId){if(attempt.startedAt&&now()-Date.parse(attempt.startedAt)<GRAPH_START_UNCERTAINTY_MS)return{state:"pending",retryAfterMs:MIN_POLL};await storage.failStep(runId,attempt.stepId,attempt.iteration,attempt.attempt,{category:"provider_start_ambiguous",safeMessage:"ADT did not receive a durable provider task identity or result. The provider may have accepted the request, so ADT did not automatically submit another request.",retryable:false});return finish()}
 if(attempt.status!=="waiting_provider"||!attempt.providerTaskId)return finish();
 let cancellation:"cancelled"|"cancellation_pending"|"already_terminal"|"unsupported"|"safe_failure"="unsupported";try{const call=await durableInvocation(detail,attempt,resolveConnection),runtime=runtimes.resolve(call.connection.adapter);cancellation=runtime?await runtime.cancel(attempt.providerTaskId,call):"unsupported"}catch{cancellation="safe_failure"}
 if(cancellation==="cancelled"){await storage.failStep(runId,attempt.stepId,attempt.iteration,attempt.attempt,{category:"cancelled",safeMessage:"The admitted sibling provider task was cancelled after another graph branch failed.",retryable:false});return finish()}
 if(attempt.providerPollCount>=MAX_PROVIDER_POLLS||!attempt.startedAt||now()-Date.parse(attempt.startedAt)>MAX_PROVIDER_STEP_MS){await storage.failStep(runId,attempt.stepId,attempt.iteration,attempt.attempt,{category:"provider_timeout",safeMessage:"The admitted sibling provider task could not be reconciled within its polling limit.",retryable:false});return finish()}
 try{const delay=clampPollDelay(attempt.nextPollDelayMs);await storage.incrementPollCount(runId,attempt.stepId,attempt.iteration,attempt.attempt,delay);detail=(await storage.getRun(runId))!;attempt=detail.attempts.find(item=>item.stepId===attempt.stepId&&item.iteration===attempt.iteration&&item.attempt===attempt.attempt)!;const call=await durableInvocation(detail,attempt,resolveConnection),runtime=runtimes.resolve(call.connection.adapter);if(!runtime)throw Object.assign(new Error("runtime unavailable"),{category:"configuration_invalid"});const result=await runtime.check(attempt.providerTaskId!,call);if(result.state==="completed"){if(Buffer.byteLength(result.outputText,"utf8")>MAX_TEXT)throw Object.assign(new Error("large"),{category:"output_too_large"});await storage.completeStep(runId,attempt.stepId,attempt.iteration,attempt.attempt,result.outputText,safeExternalUrl(result.externalUrl));return finish()}if(result.state==="pending"){const next=clampPollDelay(result.pollAfterMs);await storage.persistProviderProgress(runId,attempt.stepId,attempt.iteration,attempt.attempt,result.providerState??attempt.providerState??"pending",next,result.outputText,safeExternalUrl(result.taskUrl));return{state:"pending",retryAfterMs:next}}await storage.failStep(runId,attempt.stepId,attempt.iteration,attempt.attempt,{category:result.category,safeMessage:result.safeMessage,retryable:false});return finish()}catch(error){const failure=durableSafeFailure(error);await storage.failStep(runId,attempt.stepId,attempt.iteration,attempt.attempt,{...failure,retryable:false});return finish()}
}
/** Executes at most one persisted provider lifecycle transition for an exact engine-v2 node. */
export async function executeDurableGraphNodeTurn(input:{runId:string;nodeId:string;activationId?:string;inputText:string;storage:WorkflowRunStorage;runtimes:AgentRuntimeResolver;resolveConnection:(key:string,snapshot?:import("./workflow-connections.ts").ConnectionDescriptor)=>Promise<ResolvedConnection>;now?:()=>number}):Promise<GraphNodeTurnResult>{
 const {runId,nodeId,storage,runtimes,resolveConnection}=input,now=input.now??Date.now;let detail=await storage.getRun(runId);
 if(!detail||detail.run.engineVersion!=="2"||!detail.run.executionPlan||!("planVersion" in detail.run.executionPlan)||!detail.run.executionPlan.nodes.some(node=>node.id===nodeId))throw new Error("invalid_graph_node");
 if(detail.run.status==="succeeded")return{state:"completed",outputText:(input.activationId?detail.attempts.filter(item=>item.stepId===nodeId&&item.graphActivationId===input.activationId&&item.status==="succeeded").at(-1):detail.attempts.filter(item=>item.stepId===nodeId&&item.status==="succeeded").at(-1))?.outputText??detail.run.finalOutput??""};
 if(detail.run.status==="cancelled")return{state:"cancelled"};
 if(now()-Date.parse(detail.run.createdAt)>MAX_WORKFLOW_RUN_MS){await storage.failRun(runId,"provider_timeout","The workflow run exceeded its time limit.");return{state:"failed",safeMessage:"The workflow run exceeded its time limit."}}
 let attempt=input.activationId?detail.attempts.filter(item=>item.stepId===nodeId&&item.graphActivationId===input.activationId).at(-1):detail.attempts.filter(item=>item.stepId===nodeId).at(-1);if(!attempt)throw new Error("invalid_graph_node");

 if(detail.run.status==="cancelling"||detail.run.cancelRequestedAt){const admitted=detail.attempts.filter(item=>item.providerTaskId&&["starting","waiting_provider"].includes(item.status)),outcomes=await Promise.all(admitted.map(async item=>{try{const call=await durableInvocation(detail!,item,resolveConnection),runtime=runtimes.resolve(call.connection.adapter);return runtime?await runtime.cancel(item.providerTaskId!,call):"unsupported" as const}catch{return "safe_failure" as const}})),outcome=outcomes.includes("cancellation_pending")?"cancellation_pending":outcomes.includes("safe_failure")?"safe_failure":outcomes.includes("unsupported")?"unsupported":outcomes.includes("cancelled")?"cancelled":"already_terminal";await storage.recordCancellationResult(runId,outcome);if(outcome!=="cancellation_pending")await storage.cancelRun(runId);return{state:outcome==="cancellation_pending"?"pending":"cancelled",retryAfterMs:outcome==="cancellation_pending"?Math.min(5000,clampPollDelay(attempt.nextPollDelayMs)):undefined}}
 if(detail.run.failureCode)return reconcileFailedGraphRun({runId,attempt,detail,storage,runtimes,resolveConnection,now});
 const deferFailure=async(category:FailureCategory,safeMessage:string)=>{await storage.recordGraphFailure(runId,category,safeMessage);return executeDurableGraphNodeTurn(input)};
 if(attempt.status==="succeeded")return{state:"completed",outputText:attempt.outputText??""};
 let ownsStart=false;
 if(attempt.status==="pending"){if(Buffer.byteLength(input.inputText,"utf8")>MAX_TEXT)throw new Error("output_too_large");const claim=await storage.claimGraphNode(runId,nodeId,input.inputText,input.activationId);attempt=claim.attempt;ownsStart=claim.claimed;if(attempt.status==="cancelled")return{state:"cancelled"};if(!ownsStart&&attempt.status==="pending"){detail=(await storage.getRun(runId))!;if(detail.run.failureCode)return reconcileFailedGraphRun({runId,attempt,detail,storage,runtimes,resolveConnection,now});throw new Error("invalid_step_claim")}}
 if(attempt.status==="starting"&&!ownsStart){if(!attempt.startedAt||now()-Date.parse(attempt.startedAt)<GRAPH_START_UNCERTAINTY_MS)return{state:"pending",retryAfterMs:MIN_POLL};const failure={category:"provider_start_ambiguous" as const,safeMessage:"ADT did not receive a durable provider task identity or result. The provider may have accepted the request, so ADT did not automatically submit another request.",retryable:false};await storage.failStep(runId,nodeId,attempt.iteration,attempt.attempt,failure);return deferFailure(failure.category,failure.safeMessage)}
 if(attempt.status==="starting"&&ownsStart){try{detail=(await storage.getRun(runId))!;if(detail.run.status==="cancelled")return{state:"cancelled"};if(detail.run.status==="cancelling"||detail.run.cancelRequestedAt)return{state:"pending",retryAfterMs:MIN_POLL};const call=await durableInvocation(detail,attempt,resolveConnection),runtime=runtimes.resolve(call.connection.adapter);if(!runtime)throw Object.assign(new Error("runtime unavailable"),{category:"configuration_invalid"});const result=await runtime.start(call);if(result.transportDiagnostics)await storage.recordProviderDiagnostics(runId,nodeId,attempt.iteration,attempt.attempt,result.transportDiagnostics);if(result.state==="pending"){const delay=clampPollDelay(result.pollAfterMs);await storage.persistProviderTask(runId,nodeId,attempt.iteration,attempt.attempt,result.taskId,delay);if(result.providerState||result.outputText||result.taskUrl)await storage.persistProviderProgress(runId,nodeId,attempt.iteration,attempt.attempt,result.providerState??"pending",delay,result.outputText,safeExternalUrl(result.taskUrl));return{state:"pending",retryAfterMs:delay}}if(Buffer.byteLength(result.outputText,"utf8")>MAX_TEXT)throw Object.assign(new Error("large"),{category:"output_too_large"});await storage.completeStep(runId,nodeId,attempt.iteration,attempt.attempt,result.outputText,safeExternalUrl(result.externalUrl));return{state:"completed",outputText:result.outputText}}catch(error){if(error&&typeof error==="object"&&"transportDiagnostics" in error&&error.transportDiagnostics)await storage.recordProviderDiagnostics(runId,nodeId,attempt.iteration,attempt.attempt,error.transportDiagnostics as import("./workflow-adapter.ts").ProviderTransportDiagnostics);const failure=durableSafeFailure(error);await storage.failStep(runId,nodeId,attempt.iteration,attempt.attempt,failure);if(failure.retryable&&transient.has(failure.category))return{state:"pending",retryAfterMs:MIN_POLL};return deferFailure(failure.category,failure.safeMessage)}}
 if(attempt.status==="waiting_provider"){if(!attempt.providerTaskId)throw new Error("invalid_attempt_state");if(attempt.providerPollCount>=MAX_PROVIDER_POLLS||!attempt.startedAt||now()-Date.parse(attempt.startedAt)>MAX_PROVIDER_STEP_MS){const failure={category:"provider_timeout" as const,safeMessage:"The provider step exceeded its polling limit.",retryable:false};await storage.failStep(runId,nodeId,attempt.iteration,attempt.attempt,failure);return deferFailure(failure.category,failure.safeMessage)}try{const delay=clampPollDelay(attempt.nextPollDelayMs);await storage.incrementPollCount(runId,nodeId,attempt.iteration,attempt.attempt,delay);detail=(await storage.getRun(runId))!;attempt=input.activationId?detail.attempts.filter(item=>item.stepId===nodeId&&item.graphActivationId===input.activationId).at(-1)!:detail.attempts.filter(item=>item.stepId===nodeId).at(-1)!;const call=await durableInvocation(detail,attempt,resolveConnection),runtime=runtimes.resolve(call.connection.adapter);if(!runtime)throw Object.assign(new Error("runtime unavailable"),{category:"configuration_invalid"});const result=await runtime.check(attempt.providerTaskId!,call);if(result.state==="completed"){if(Buffer.byteLength(result.outputText,"utf8")>MAX_TEXT)throw Object.assign(new Error("large"),{category:"output_too_large"});await storage.completeStep(runId,nodeId,attempt.iteration,attempt.attempt,result.outputText,safeExternalUrl(result.externalUrl));return{state:"completed",outputText:result.outputText}}if(result.state==="pending"){const next=clampPollDelay(result.pollAfterMs);await storage.persistProviderProgress(runId,nodeId,attempt.iteration,attempt.attempt,result.providerState??attempt.providerState??"pending",next,result.outputText,safeExternalUrl(result.taskUrl));return{state:"pending",retryAfterMs:next}}await storage.failStep(runId,nodeId,attempt.iteration,attempt.attempt,{category:result.category,safeMessage:result.safeMessage,retryable:result.retryable});if(result.retryable&&transient.has(result.category))return{state:"pending",retryAfterMs:MIN_POLL};return deferFailure(result.category,result.safeMessage)}catch(error){const failure=durableSafeFailure(error);await storage.failStep(runId,nodeId,attempt.iteration,attempt.attempt,failure);if(failure.retryable&&transient.has(failure.category))return{state:"pending",retryAfterMs:MIN_POLL};return deferFailure(failure.category,failure.safeMessage)}}
 if(attempt.status==="failed"){const total=detail.attempts.filter(item=>item.stepId===nodeId&&(!input.activationId||item.graphActivationId===input.activationId)).length;if(attempt.retryable&&transient.has(attempt.failureCategory!)&&attempt.attempt<3&&total<MAX_TOTAL_ATTEMPTS){await storage.createAutomaticRetryAttempt(runId,nodeId,input.activationId);return{state:"pending",retryAfterMs:graphRetryDelay(attempt.attempt)}}return deferFailure(attempt.failureCategory??"internal_error",attempt.safeFailureMessage??"The workflow step failed.")}
 return{state:"pending",retryAfterMs:MIN_POLL};
}
