import {z} from "zod";
import type {WorkflowD1Database} from "./workflow-d1-storage.ts";

export const approvalRequestIdSchema=z.string().uuid();
export type WorkflowApproval={requestId:string;runId:string;workflowGeneration:number;nodeId:string;activationId:string;interruptId:string;message:string;reviewText:string;status:"pending"|"approved";requestedAt:string;approvedAt?:string};
const row=(value:Record<string,unknown>):WorkflowApproval=>({requestId:String(value.request_id),runId:String(value.run_id),workflowGeneration:Number(value.workflow_generation),nodeId:String(value.node_id),activationId:String(value.activation_id),interruptId:String(value.interrupt_id),message:String(value.message),reviewText:String(value.review_text),status:value.status as "pending"|"approved",requestedAt:String(value.requested_at),approvedAt:value.approved_at?String(value.approved_at):undefined});
export class D1WorkflowApprovalStore{
 private db:WorkflowD1Database;private clock:()=>string;constructor(db:WorkflowD1Database,clock:()=>string=()=>new Date().toISOString()){this.db=db;this.clock=clock}
 async pending(runId:string){const value=await this.db.prepare("SELECT * FROM workflow_approvals WHERE run_id=? AND status='pending' ORDER BY requested_at DESC LIMIT 1").bind(runId).first<Record<string,unknown>>();return value?row(value):undefined}
 async get(requestId:string){const value=await this.db.prepare("SELECT * FROM workflow_approvals WHERE request_id=?").bind(approvalRequestIdSchema.parse(requestId)).first<Record<string,unknown>>();return value?row(value):undefined}
 async require(input:{runId:string;workflowGeneration:number;nodeId:string;activationId:string;interruptId:string;message:string;reviewText:string}){if(Buffer.byteLength(input.reviewText,"utf8")>262144||input.message.length>2000||input.activationId.length>256||input.interruptId.length>256)throw new Error("approval_invalid");const existing=await this.db.prepare("SELECT * FROM workflow_approvals WHERE run_id=? AND workflow_generation=? AND activation_id=?").bind(input.runId,input.workflowGeneration,input.activationId).first<Record<string,unknown>>();if(existing){const parsed=row(existing);if(parsed.nodeId!==input.nodeId||parsed.interruptId!==input.interruptId||parsed.message!==input.message||parsed.reviewText!==input.reviewText)throw new Error("approval_conflict");return parsed}const requestId=crypto.randomUUID(),now=this.clock();await this.db.prepare("INSERT INTO workflow_approvals(request_id,run_id,workflow_generation,node_id,activation_id,interrupt_id,message,review_text,status,requested_at) SELECT ?,?,?,?,?,?,?,?,'pending',? WHERE EXISTS(SELECT 1 FROM workflow_runs WHERE id=? AND workflow_generation=? AND status IN ('queued','running','waiting_approval'))").bind(requestId,input.runId,input.workflowGeneration,input.nodeId,input.activationId,input.interruptId,input.message,input.reviewText,now,input.runId,input.workflowGeneration).run();await this.db.prepare("UPDATE workflow_runs SET status='waiting_approval',current_step_id=?,updated_at=?,state_version=state_version+1 WHERE id=? AND workflow_generation=? AND status IN ('queued','running','waiting_approval')").bind(input.nodeId,now,input.runId,input.workflowGeneration).run();return (await this.get(requestId))!}
 async approve(runId:string,requestId:string){approvalRequestIdSchema.parse(requestId);const now=this.clock(),result=await this.db.prepare("UPDATE workflow_approvals SET status='approved',approved_at=COALESCE(approved_at,?) WHERE request_id=? AND run_id=? AND status='pending' AND EXISTS(SELECT 1 FROM workflow_runs WHERE id=? AND workflow_generation=workflow_approvals.workflow_generation AND status='waiting_approval' AND cancel_requested_at IS NULL)").bind(now,requestId,runId,runId).run();const approval=await this.get(requestId);if(result.meta?.changes===1){await this.db.prepare("UPDATE workflow_runs SET status='running',updated_at=?,state_version=state_version+1 WHERE id=? AND status='waiting_approval' AND cancel_requested_at IS NULL").bind(now,runId).run();return{approval,idempotent:false as const};}if(approval?.runId===runId&&approval.status==='approved')return{approval,idempotent:true as const};throw new Error("approval_not_pending")}
 async suspendedMs(runId:string){const value=await this.db.prepare("SELECT COALESCE(SUM((julianday(approved_at)-julianday(requested_at))*86400000),0) AS value FROM workflow_approvals WHERE run_id=? AND status='approved'").bind(runId).first<{value:number}>();return Math.max(0,Number(value?.value??0))}
}
