import {decryptProviderCredential,encryptProviderCredential,providerSecretStorageAvailable} from "./workflow-provider-secret-crypto.ts";
import type {ConnectionDescriptor,ResolvedConnection} from "./workflow-connections.ts";
export interface ProviderConnectionDatabase{prepare(sql:string):{bind(...values:unknown[]):{first<T>():Promise<T|null>;run():Promise<unknown>;all<T>():Promise<{results:T[]}>}}}
type Row={connection_key:string;adapter:string;default_model:string;encrypted_credential:string;credential_iv:string;encryption_version:number};
export interface WorkflowProviderConnectionStore{listSafeDescriptors():Promise<ConnectionDescriptor[]>;getSafeDescriptor(key:string):Promise<ConnectionDescriptor|undefined>;resolveCredential(key:string):Promise<ResolvedConnection>;upsertConnection(input:{connectionKey:string;adapter:string;model:string;credential?:string}):Promise<ConnectionDescriptor>;deleteConnection(key:string):Promise<void>}
const descriptor=(row:Row,ready:boolean):ConnectionDescriptor=>({key:row.connection_key,name:"OpenAI Responses",adapter:row.adapter,endpoint:"https://api.openai.com/v1",defaultModel:row.default_model,enabled:ready,capabilities:{asynchronous:true,cancellation:true}});
const openAIUnavailable:ConnectionDescriptor={key:"openai-primary",name:"OpenAI Responses",adapter:"openai-responses",endpoint:"https://api.openai.com/v1",enabled:false,capabilities:{asynchronous:true,cancellation:true}};
export class D1WorkflowProviderConnectionStore implements WorkflowProviderConnectionStore{
 private db:ProviderConnectionDatabase;private root:string|undefined;constructor(db:ProviderConnectionDatabase,root:string|undefined){this.db=db;this.root=root;}
 async row(key:string){return this.db.prepare("SELECT * FROM workflow_provider_connections WHERE connection_key = ?").bind(key).first<Row>();}
 private async safeDescriptor(row:Row|null){if(!row||row.connection_key!=="openai-primary"||row.adapter!=="openai-responses")return openAIUnavailable;let ready=false;if(providerSecretStorageAvailable(this.root)){try{await decryptProviderCredential({version:row.encryption_version,ciphertext:row.encrypted_credential,iv:row.credential_iv},this.root,row.connection_key,row.adapter);ready=true;}catch{ready=false;}}return descriptor(row,ready);}
 async listSafeDescriptors(){return[await this.safeDescriptor(await this.row("openai-primary"))];}
 async getSafeDescriptor(key:string){if(key!=="openai-primary")return undefined;return this.safeDescriptor(await this.row(key));}
 async resolveCredential(key:string){const row=key==="openai-primary"?await this.row(key):null;if(!row||row.adapter!=="openai-responses"||!providerSecretStorageAvailable(this.root))throw new Error("connection_unavailable");const credential=await decryptProviderCredential({version:row.encryption_version,ciphertext:row.encrypted_credential,iv:row.credential_iv},this.root,key,row.adapter).catch(()=>{throw new Error("connection_unavailable")});return{...descriptor(row,true),credential};}
 async upsertConnection(input:{connectionKey:string;adapter:string;model:string;credential?:string}){const old=await this.row(input.connectionKey);if(!input.credential&&!old)throw new Error("credential_required");const now=new Date().toISOString();if(input.credential){const encrypted=await encryptProviderCredential(input.credential,this.root,input.connectionKey,input.adapter);await this.db.prepare("INSERT INTO workflow_provider_connections(connection_key,adapter,default_model,encrypted_credential,credential_iv,encryption_version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(connection_key) DO UPDATE SET adapter=excluded.adapter,default_model=excluded.default_model,encrypted_credential=excluded.encrypted_credential,credential_iv=excluded.credential_iv,encryption_version=excluded.encryption_version,updated_at=excluded.updated_at").bind(input.connectionKey,input.adapter,input.model,encrypted.ciphertext,encrypted.iv,encrypted.version,old?now:now,now).run();}else await this.db.prepare("UPDATE workflow_provider_connections SET default_model = ?, updated_at = ? WHERE connection_key = ?").bind(input.model,now,input.connectionKey).run();return (await this.getSafeDescriptor(input.connectionKey))!;}
 async deleteConnection(key:string){await this.db.prepare("DELETE FROM workflow_provider_connections WHERE connection_key = ?").bind(key).run();}
}
