use std::{error::Error, io, net::{SocketAddr, ToSocketAddrs}, time::Duration};
use reqwest::{header, ClientBuilder, Version};
use serde::Serialize;
const HOST:&str="auth.openai.com";const URL:&str="https://auth.openai.com/api/accounts/deviceauth/usercode";const BODY:&str="{";const TIMEOUT:Duration=Duration::from_secs(4);
#[derive(Clone,Copy)]enum Variant{Baseline,NamedUserAgent,Http1Only,NoProxy,ForcedIpv4}impl Variant{fn name(self)->&'static str{match self{Self::Baseline=>"baseline",Self::NamedUserAgent=>"namedUserAgent",Self::Http1Only=>"http1Only",Self::NoProxy=>"noProxy",Self::ForcedIpv4=>"forcedIpv4"}}}
#[derive(Serialize)]#[serde(rename_all="camelCase",tag="outcome")]enum ResultSummary{#[serde(rename="http_response")]Http{status:u16,protocol:&'static str,cloudflare_edge:bool,mitigation_challenge:bool,content_kind:&'static str},#[serde(rename="transport_error")]Transport{is_timeout:bool,is_connect:bool,is_request:bool,io_error_kind:&'static str,tls_source_present:bool,source_class:&'static str}}
#[derive(Serialize)]struct Entry{variant:&'static str,result:ResultSummary}#[derive(Serialize)]struct Output{attempts:Vec<Entry>}
fn builder(variant:Variant,ipv4:&[SocketAddr])->ClientBuilder{let mut b=ClientBuilder::new().timeout(TIMEOUT);match variant{Variant::Baseline=>{},Variant::NamedUserAgent=>b=b.user_agent(format!("ADT-Codex-Auth-Probe/{}",env!("CARGO_PKG_VERSION"))),Variant::Http1Only=>b=b.http1_only(),Variant::NoProxy=>b=b.no_proxy(),Variant::ForcedIpv4=>b=b.resolve_to_addrs(HOST,ipv4)}b}
fn io_kind(kind:io::ErrorKind)->&'static str{match kind{io::ErrorKind::NetworkUnreachable=>"network_unreachable",io::ErrorKind::HostUnreachable=>"host_unreachable",io::ErrorKind::ConnectionRefused=>"connection_refused",io::ErrorKind::ConnectionReset=>"connection_reset",io::ErrorKind::TimedOut=>"timed_out",io::ErrorKind::AddrNotAvailable=>"address_not_available",_=>"other"}}
fn classify(error:&reqwest::Error)->ResultSummary{let mut source=error.source();let mut kind="none";let mut class="unknown";let mut tls=false;while let Some(current)=source{if let Some(e)=current.downcast_ref::<io::Error>(){kind=io_kind(e.kind());class="io"}else if current.downcast_ref::<native_tls::Error>().is_some(){tls=true;class="tls"}source=current.source()}ResultSummary::Transport{is_timeout:error.is_timeout(),is_connect:error.is_connect(),is_request:error.is_request(),io_error_kind:kind,tls_source_present:tls,source_class:class}}
async fn attempt(variant:Variant,ipv4:&[SocketAddr])->Entry{let result=match builder(variant,ipv4).build(){Ok(client)=>match client.post(URL).header(header::CONTENT_TYPE,"application/json").body(BODY).send().await{Ok(response)=>{let h=response.headers();let content=h.get(header::CONTENT_TYPE).and_then(|v|v.to_str().ok()).map(|v|v.split(';').next().unwrap_or("").trim());ResultSummary::Http{status:response.status().as_u16(),protocol:match response.version(){Version::HTTP_11|Version::HTTP_10=>"http1",Version::HTTP_2=>"http2",_=>"unknown"},cloudflare_edge:h.get(header::SERVER).and_then(|v|v.to_str().ok()).is_some_and(|v|v.eq_ignore_ascii_case("cloudflare")),mitigation_challenge:h.get("cf-mitigated").and_then(|v|v.to_str().ok())==Some("challenge"),content_kind:match content{Some("application/json")=>"json",Some("text/html")=>"html",Some(_)=>"other",None=>"unknown"}}},Err(e)=>classify(&e)},Err(e)=>classify(&e)};Entry{variant:variant.name(),result}}
#[tokio::main]async fn main(){let ipv4:Vec<_>=(HOST,443).to_socket_addrs().map(|v|v.filter(SocketAddr::is_ipv4).collect()).unwrap_or_default();let mut attempts=vec![attempt(Variant::Baseline,&ipv4).await];if matches!(attempts[0].result,ResultSummary::Transport{..}){for v in[Variant::NamedUserAgent,Variant::Http1Only,Variant::NoProxy,Variant::ForcedIpv4]{attempts.push(attempt(v,&ipv4).await)}}println!("{}",serde_json::to_string(&Output{attempts}).expect("bounded output serializes"))}
