import {access,constants,readFile} from "node:fs/promises";
import {homedir} from "node:os";
import {join} from "node:path";
import {lookup} from "node:dns/promises";
import {connect,type Socket} from "node:net";
import {connect as tlsConnect,type TLSSocket} from "node:tls";
import {request as httpsRequest} from "node:https";
import {connect as http2Connect,constants as h2} from "node:http2";
import {execFile} from "node:child_process";

const AUTH_HOST="auth.openai.com",AUTH_PORT=443,DEVICE_PATH="/api/accounts/deviceauth/usercode",PROBE_TIMEOUT_MS=2_000;
export const EXPECTED_CODEX_VERSION="0.118.0";
type Connectivity="ok"|"timeout"|"failed"|"unavailable";
export type FailureReason="network_unreachable"|"address_unavailable"|"connection_refused"|"connection_reset"|"certificate"|"tls_protocol"|"timeout"|"other";
export type HttpProbe={protocol:"http1"|"http2";responseReceived:boolean;status?:number;mitigationChallenge:boolean;cloudflareEdge:boolean;redirectPresent:boolean;contentKind?:"html"|"json"|"other";cloudflareColo?:string};
type ProbeResult={connectivity:Connectivity;failureReason?:FailureReason};
export type AuthEnvironmentDiagnostics={runnerReachable:true;codexAppServerReady:boolean;codexVersion?:string;codexVersionMatchesExpected:boolean;customCaSource:"none"|"codex_ca_certificate"|"ssl_cert_file";customCaFileReadable?:boolean;httpProxyConfigured:boolean;httpsProxyConfigured:boolean;allProxyConfigured:boolean;noProxyConfigured:boolean;dnsResolution:"ok"|"failed";ipv4Available:boolean;ipv6Available:boolean;systemResolverFirstFamily:"ipv4"|"ipv6"|"none";runnerAddressPolicy:"system_default"|"ipv4_preferred";runnerAddressPolicyEffective:boolean|null;kernelIpv6Disabled:boolean;ipv4TcpConnectivity:Connectivity;ipv6TcpConnectivity:Connectivity;ipv4TlsConnectivity:Connectivity;ipv6TlsConnectivity:Connectivity;ipv4TcpFailureReason?:FailureReason;ipv6TcpFailureReason?:FailureReason;ipv4TlsFailureReason?:FailureReason;ipv6TlsFailureReason?:FailureReason;authOriginHttp1:HttpProbe;deviceAuthHttp1:HttpProbe;deviceAuthHttp2:HttpProbe;deviceAuthNamedClientHttp1:HttpProbe;clientIdentificationChangesOutcome:boolean;httpsResponseReceived:boolean;httpsStatus?:number;httpsMitigationChallenge:boolean;tcpConnectivity:"ok"|"timeout"|"failed";codexHomeReadable:boolean;codexHomeWritable:boolean;summary:string[]};
type LookupAddress={address:string;family:number};
type Dependencies={environment?:NodeJS.ProcessEnv;codexCommand?:string;lookupHost?:(hostname:string)=>Promise<LookupAddress[]>;connectHost?:(host:string,port:number,family:4|6,timeoutMs:number)=>Promise<ProbeResult|Exclude<Connectivity,"unavailable">>;tlsHost?:(host:string,port:number,family:4|6,timeoutMs:number)=>Promise<ProbeResult|Exclude<Connectivity,"unavailable">>;http1Head?:(path:"/"|typeof DEVICE_PATH,userAgent?:string)=>Promise<HttpProbe>;http2Head?:()=>Promise<HttpProbe>;accessPath?:(path:string,mode:number)=>Promise<void>;readSystemFile?:(path:string)=>Promise<string>;codexVersion?:(command:string)=>Promise<string|undefined>;codexAppServerReady?:()=>Promise<boolean>};
const emptyProbe=(protocol:"http1"|"http2"):HttpProbe=>({protocol,responseReceived:false,mitigationChallenge:false,cloudflareEdge:false,redirectPresent:false});
const present=(environment:NodeJS.ProcessEnv,upper:string,lower:string)=>Boolean(environment[upper]||environment[lower]);
const bounded=<T>(operation:Promise<T>,timeoutMs:number,fallback:T)=>new Promise<T>(resolve=>{const timer=setTimeout(()=>resolve(fallback),timeoutMs);operation.then(value=>{clearTimeout(timer);resolve(value)},()=>{clearTimeout(timer);resolve(fallback)})});
const errorCode=(error:unknown)=>typeof error==="object"&&error!==null&&"code" in error?String((error as {code:unknown}).code):"";
export function classifyNetworkFailure(error:unknown,tls=false):FailureReason{const code=errorCode(error);if(code==="ENETUNREACH"||code==="EHOSTUNREACH")return"network_unreachable";if(code==="EADDRNOTAVAIL"||code==="EAFNOSUPPORT")return"address_unavailable";if(code==="ECONNREFUSED")return"connection_refused";if(code==="ECONNRESET"||code==="EPIPE")return"connection_reset";if(code==="ETIMEDOUT")return"timeout";if(["CERT_HAS_EXPIRED","DEPTH_ZERO_SELF_SIGNED_CERT","SELF_SIGNED_CERT_IN_CHAIN","UNABLE_TO_VERIFY_LEAF_SIGNATURE","ERR_TLS_CERT_ALTNAME_INVALID"].includes(code))return"certificate";if(tls&&code.startsWith("ERR_SSL_"))return"tls_protocol";return"other"}
async function socketProbe(host:string,port:number,family:4|6,timeoutMs:number,tls:boolean){return new Promise<ProbeResult>(resolve=>{let done=false,tlsSocket:TLSSocket|undefined;const socket:Socket=connect({host,port,family});const finish=(result:ProbeResult)=>{if(done)return;done=true;tlsSocket?.destroy();socket.destroy();resolve(result)};socket.setTimeout(timeoutMs,()=>finish({connectivity:"timeout",failureReason:"timeout"}));socket.once("error",e=>finish({connectivity:"failed",failureReason:classifyNetworkFailure(e,tls)}));socket.once("connect",()=>{if(!tls)return finish({connectivity:"ok"});tlsSocket=tlsConnect({socket,servername:AUTH_HOST,rejectUnauthorized:true});tlsSocket.setTimeout(timeoutMs,()=>finish({connectivity:"timeout",failureReason:"timeout"}));tlsSocket.once("secureConnect",()=>finish({connectivity:"ok"}));tlsSocket.once("error",e=>finish({connectivity:"failed",failureReason:classifyNetworkFailure(e,true)}))})})}
export function safeHttpResult(protocol:"http1"|"http2",status:number|undefined,headers:Record<string,string|string[]|undefined>):HttpProbe{const one=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]:v;const rawContent=one(headers["content-type"]),content=rawContent?.split(";",1)[0]?.trim().toLowerCase(),ray=one(headers["cf-ray"]),colo=ray?.match(/^[A-Za-z0-9]+-([A-Z]{3})$/)?.[1];return{protocol,responseReceived:true,...(status!==undefined?{status}:{}),mitigationChallenge:one(headers["cf-mitigated"])==="challenge",cloudflareEdge:one(headers.server)?.trim().toLowerCase()==="cloudflare",redirectPresent:status!==undefined&&status>=300&&status<400&&headers.location!==undefined,...(content?{contentKind:content==="text/html"?"html":content==="application/json"?"json":"other" as const}:{}),...(colo?{cloudflareColo:colo}:{})}}
async function defaultHttp1(path:"/"|typeof DEVICE_PATH,userAgent?:string){return new Promise<HttpProbe>(resolve=>{let done=false;const request=httpsRequest({host:AUTH_HOST,port:AUTH_PORT,family:4,servername:AUTH_HOST,path,method:"HEAD",headers:userAgent?{"user-agent":userAgent}:{},rejectUnauthorized:true,timeout:PROBE_TIMEOUT_MS},response=>{response.destroy();finish(safeHttpResult("http1",response.statusCode,response.headers))});const finish=(result:HttpProbe)=>{if(done)return;done=true;request.destroy();resolve(result)};request.once("timeout",()=>finish(emptyProbe("http1")));request.once("error",()=>finish(emptyProbe("http1")));request.end()})}
async function defaultHttp2(){return new Promise<HttpProbe>(resolve=>{let done=false;const session=http2Connect(`https://${AUTH_HOST}`,{rejectUnauthorized:true,servername:AUTH_HOST,createConnection:()=>tlsConnect({host:AUTH_HOST,port:AUTH_PORT,family:4,servername:AUTH_HOST,rejectUnauthorized:true,ALPNProtocols:["h2"]} as unknown as number)});const finish=(v:HttpProbe)=>{if(done)return;done=true;session.destroy();resolve(v)},timer=setTimeout(()=>finish(emptyProbe("http2")),PROBE_TIMEOUT_MS);session.once("error",()=>finish(emptyProbe("http2")));const request=session.request({[h2.HTTP2_HEADER_METHOD]:"HEAD",[h2.HTTP2_HEADER_PATH]:DEVICE_PATH,[h2.HTTP2_HEADER_AUTHORITY]:AUTH_HOST});request.once("response",headers=>{clearTimeout(timer);const record=Object.fromEntries(Object.entries(headers).map(([k,v])=>[k,v as string|string[]|undefined]));request.close();finish(safeHttpResult("http2",Number.isInteger(headers[h2.HTTP2_HEADER_STATUS])?Number(headers[h2.HTTP2_HEADER_STATUS]):undefined,record))});request.once("error",()=>finish(emptyProbe("http2")));request.end()})}
async function defaultCodexVersion(command:string){return new Promise<string|undefined>(resolve=>execFile(command,["--version"],{timeout:PROBE_TIMEOUT_MS,maxBuffer:1024},(error,stdout)=>{if(error)return resolve(undefined);const match=stdout.trim().match(/^(?:codex-cli |codex )?(\d+\.\d+\.\d+)$/);resolve(match?.[1])}))}
const sameOutcome=(a:HttpProbe,b:HttpProbe)=>a.responseReceived===b.responseReceived&&a.status===b.status&&a.mitigationChallenge===b.mitigationChallenge&&a.cloudflareEdge===b.cloudflareEdge&&a.redirectPresent===b.redirectPresent&&a.contentKind===b.contentKind;
export async function diagnoseAuthEnvironment(dependencies:Dependencies={}):Promise<AuthEnvironmentDiagnostics>{
 const env=dependencies.environment??process.env,caPath=env.CODEX_CA_CERTIFICATE||env.SSL_CERT_FILE,customCaSource=env.CODEX_CA_CERTIFICATE?"codex_ca_certificate":env.SSL_CERT_FILE?"ssl_cert_file":"none",accessPath=dependencies.accessPath??access,home=env.CODEX_HOME??join(homedir(),".codex"),read=dependencies.readSystemFile??(p=>readFile(p,"utf8"));
 const canAccess=async(path:string,mode:number)=>{try{await bounded(accessPath(path,mode).then(()=>true),PROBE_TIMEOUT_MS,false).then(ok=>{if(!ok)throw new Error()});return true}catch{return false}};
 const [addresses,codexAppServerReady,codexHomeReadable,codexHomeWritable,customCaFileReadable,kernelState,codexVersion]=await Promise.all([bounded((dependencies.lookupHost??(hostname=>lookup(hostname,{all:true,verbatim:true})))(AUTH_HOST),PROBE_TIMEOUT_MS,[]),bounded(dependencies.codexAppServerReady?.()??Promise.resolve(false),PROBE_TIMEOUT_MS,false),canAccess(home,constants.R_OK),canAccess(home,constants.W_OK),caPath?canAccess(caPath,constants.R_OK):undefined,bounded(read("/proc/sys/net/ipv6/conf/all/disable_ipv6"),PROBE_TIMEOUT_MS,"0"),bounded((dependencies.codexVersion??defaultCodexVersion)(dependencies.codexCommand??env.CODEX_COMMAND??"codex"),PROBE_TIMEOUT_MS+100,undefined)]);
 const ipv4Available=addresses.some(v=>v.family===4),ipv6Available=addresses.some(v=>v.family===6),first=addresses.find(v=>v.family===4||v.family===6),systemResolverFirstFamily=first?.family===4?"ipv4":first?.family===6?"ipv6":"none",runnerAddressPolicy=env.CODEX_RUNNER_ADDRESS_POLICY==="ipv4_preferred"?"ipv4_preferred":"system_default",runnerAddressPolicyEffective=runnerAddressPolicy==="system_default"?null:ipv4Available&&ipv6Available&&systemResolverFirstFamily==="ipv4";
 const familyProbe=async(available:boolean,operation:()=>Promise<ProbeResult|string>):Promise<ProbeResult>=>{if(!available)return{connectivity:"unavailable"};const value=await bounded(operation(),PROBE_TIMEOUT_MS+100,{connectivity:"timeout",failureReason:"timeout"} as ProbeResult);return typeof value==="string"?{connectivity:value as Connectivity,...(value==="timeout"?{failureReason:"timeout" as const}:{})}:value};const connectHost=dependencies.connectHost??((h,p,f,t)=>socketProbe(h,p,f,t,false)),tlsHost=dependencies.tlsHost??((h,p,f,t)=>socketProbe(h,p,f,t,true));
 const [v4tcp,v6tcp,v4tls,v6tls]=await Promise.all([familyProbe(ipv4Available,()=>connectHost(AUTH_HOST,AUTH_PORT,4,PROBE_TIMEOUT_MS)),familyProbe(ipv6Available,()=>connectHost(AUTH_HOST,AUTH_PORT,6,PROBE_TIMEOUT_MS)),familyProbe(ipv4Available,()=>tlsHost(AUTH_HOST,AUTH_PORT,4,PROBE_TIMEOUT_MS)),familyProbe(ipv6Available,()=>tlsHost(AUTH_HOST,AUTH_PORT,6,PROBE_TIMEOUT_MS))]);
 const http1=dependencies.http1Head??defaultHttp1,http2=dependencies.http2Head??defaultHttp2,namedUa=`ADT-Codex-Runner-Diagnostic/${env.CODEX_RUNNER_VERSION??"development"}`;const [origin,device,h2probe,named]=ipv4Available?await Promise.all([bounded(http1("/"),PROBE_TIMEOUT_MS+100,emptyProbe("http1")),bounded(http1(DEVICE_PATH),PROBE_TIMEOUT_MS+100,emptyProbe("http1")),bounded(http2(),PROBE_TIMEOUT_MS+100,emptyProbe("http2")),bounded(http1(DEVICE_PATH,namedUa),PROBE_TIMEOUT_MS+100,emptyProbe("http1"))]):[emptyProbe("http1"),emptyProbe("http1"),emptyProbe("http2"),emptyProbe("http1")];
 const summary:string[]=[];if(ipv6Available&&v6tcp.connectivity!=="ok"&&v4tcp.connectivity==="ok"&&v4tls.connectivity==="ok")summary.push("IPv6 is advertised but its network path is unavailable. IPv4 is healthy.");if(runnerAddressPolicyEffective===true)summary.push("Runner IPv4 preference is active in the system resolver.");if(runnerAddressPolicyEffective===false)summary.push("Runner IPv4 preference is configured but the system resolver still prefers IPv6.");if(device.responseReceived&&device.mitigationChallenge)summary.push("OpenAI authentication is reachable, but Cloudflare mitigation is challenging the device-auth route.");if(v4tcp.connectivity==="ok"&&v4tls.connectivity==="ok"&&device.responseReceived&&!device.mitigationChallenge)summary.push("The Runner network path is healthy. A continuing device-auth transport failure is specific to the Codex HTTP client or its request handling.");
 const result:AuthEnvironmentDiagnostics={runnerReachable:true,codexAppServerReady,...(codexVersion?{codexVersion}:{}),codexVersionMatchesExpected:codexVersion===EXPECTED_CODEX_VERSION,customCaSource,...(customCaFileReadable!==undefined?{customCaFileReadable}:{}),httpProxyConfigured:present(env,"HTTP_PROXY","http_proxy"),httpsProxyConfigured:present(env,"HTTPS_PROXY","https_proxy"),allProxyConfigured:present(env,"ALL_PROXY","all_proxy"),noProxyConfigured:present(env,"NO_PROXY","no_proxy"),dnsResolution:addresses.length?"ok":"failed",ipv4Available,ipv6Available,systemResolverFirstFamily,runnerAddressPolicy,runnerAddressPolicyEffective,kernelIpv6Disabled:kernelState.trim()==="1",ipv4TcpConnectivity:v4tcp.connectivity,ipv6TcpConnectivity:v6tcp.connectivity,ipv4TlsConnectivity:v4tls.connectivity,ipv6TlsConnectivity:v6tls.connectivity,...(v4tcp.failureReason?{ipv4TcpFailureReason:v4tcp.failureReason}:{}),...(v6tcp.failureReason?{ipv6TcpFailureReason:v6tcp.failureReason}:{}),...(v4tls.failureReason?{ipv4TlsFailureReason:v4tls.failureReason}:{}),...(v6tls.failureReason?{ipv6TlsFailureReason:v6tls.failureReason}:{}),authOriginHttp1:origin,deviceAuthHttp1:device,deviceAuthHttp2:h2probe,deviceAuthNamedClientHttp1:named,clientIdentificationChangesOutcome:!sameOutcome(device,named),httpsResponseReceived:origin.responseReceived,...(origin.status!==undefined?{httpsStatus:origin.status}:{}),httpsMitigationChallenge:origin.mitigationChallenge,tcpConnectivity:[v4tcp.connectivity,v6tcp.connectivity].includes("ok")?"ok":[v4tcp.connectivity,v6tcp.connectivity].includes("timeout")?"timeout":"failed",codexHomeReadable,codexHomeWritable,summary};return result;
}
