import {access,constants,readFile,stat} from "node:fs/promises";
import {homedir} from "node:os";
import {join} from "node:path";
import {lookup} from "node:dns/promises";
import {connect,type Socket} from "node:net";
import {connect as tlsConnect,type TLSSocket} from "node:tls";
import {request as httpsRequest} from "node:https";
import {request as httpRequest} from "node:http";
import {execFile} from "node:child_process";
import {RUNNER_RELEASE} from "./release.js";

const AUTH_HOST="auth.openai.com",AUTH_PORT=443,DEVICE_PATH="/api/accounts/deviceauth/usercode",SYSTEM_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt",PROBE_TIMEOUT_MS=2_000;
export const EXPECTED_CODEX_VERSION=RUNNER_RELEASE.codexVersion;
type Connectivity="ok"|"timeout"|"failed"|"unavailable";
export type FailureReason="network_unreachable"|"address_unavailable"|"connection_refused"|"connection_reset"|"certificate"|"tls_protocol"|"timeout"|"other";
export type HttpProbe={responseReceived:boolean;status?:number};
type ProbeResult={connectivity:Connectivity;failureReason?:FailureReason};
export type AuthEnvironmentDiagnostics={runnerReachable:true;codexAppServerReady:boolean;codexVersion?:string;codexVersionMatchesExpected:boolean;codexNativeLibc:"glibc"|"musl"|"unknown";codexAddressPolicyApplies:boolean|null;customCaSource:"none"|"codex_ca_certificate"|"ssl_cert_file";customCaFileReadable?:boolean;systemCaBundlePresent:boolean;systemCaBundleReadable:boolean;systemCaBundleNonEmpty:boolean;httpProxyConfigured:boolean;httpsProxyConfigured:boolean;allProxyConfigured:boolean;noProxyConfigured:boolean;dnsResolution:"ok"|"failed";ipv4Available:boolean;ipv6Available:boolean;systemResolverFirstFamily:"ipv4"|"ipv6"|"none";runnerAddressPolicy:"system_default"|"ipv4_preferred";runnerAddressPolicyEffective:boolean|null;kernelIpv6Disabled:boolean;ipv4TcpConnectivity:Connectivity;ipv6TcpConnectivity:Connectivity;ipv4TlsConnectivity:Connectivity;ipv6TlsConnectivity:Connectivity;ipv4TcpFailureReason?:FailureReason;ipv6TcpFailureReason?:FailureReason;ipv4TlsFailureReason?:FailureReason;ipv6TlsFailureReason?:FailureReason;deviceAuthRoute:HttpProbe;codexHomeReadable:boolean;codexHomeWritable:boolean;summary:string[]};
type LookupAddress={address:string;family:number};
type Dependencies={environment?:NodeJS.ProcessEnv;codexCommand?:string;lookupHost?:(hostname:string)=>Promise<LookupAddress[]>;connectHost?:(host:string,port:number,family:4|6,timeoutMs:number)=>Promise<ProbeResult|Exclude<Connectivity,"unavailable">>;tlsHost?:(host:string,port:number,family:4|6,timeoutMs:number)=>Promise<ProbeResult|Exclude<Connectivity,"unavailable">>;deviceAuthHead?:()=>Promise<HttpProbe>;accessPath?:(path:string,mode:number)=>Promise<void>;statPath?:(path:string)=>Promise<{isFile():boolean;size:number}>;readSystemFile?:(path:string)=>Promise<string>;codexVersion?:(command:string)=>Promise<string|undefined>;codexAppServerReady?:()=>Promise<boolean>;readCodexLibcMarker?:()=>Promise<string>};
const present=(e:NodeJS.ProcessEnv,u:string,l:string)=>Boolean(e[u]||e[l]);
const bounded=<T>(p:Promise<T>,ms:number,f:T)=>new Promise<T>(resolve=>{const timer=setTimeout(()=>resolve(f),ms);p.then(v=>{clearTimeout(timer);resolve(v)},()=>{clearTimeout(timer);resolve(f)})});
const errorCode=(e:unknown)=>typeof e==="object"&&e!==null&&"code" in e?String((e as {code:unknown}).code):"";
export function classifyNetworkFailure(error:unknown,tls=false):FailureReason{const c=errorCode(error);if(c==="ENETUNREACH"||c==="EHOSTUNREACH")return"network_unreachable";if(c==="EADDRNOTAVAIL"||c==="EAFNOSUPPORT")return"address_unavailable";if(c==="ECONNREFUSED")return"connection_refused";if(c==="ECONNRESET"||c==="EPIPE")return"connection_reset";if(c==="ETIMEDOUT")return"timeout";if(["CERT_HAS_EXPIRED","DEPTH_ZERO_SELF_SIGNED_CERT","SELF_SIGNED_CERT_IN_CHAIN","UNABLE_TO_VERIFY_LEAF_SIGNATURE","ERR_TLS_CERT_ALTNAME_INVALID"].includes(c))return"certificate";if(tls&&c.startsWith("ERR_SSL_"))return"tls_protocol";return"other"}
async function socketProbe(host:string,port:number,family:4|6,timeoutMs:number,tls:boolean){return new Promise<ProbeResult>(resolve=>{let done=false,tlsSocket:TLSSocket|undefined;const socket:Socket=connect({host,port,family});const finish=(r:ProbeResult)=>{if(done)return;done=true;tlsSocket?.destroy();socket.destroy();resolve(r)};socket.setTimeout(timeoutMs,()=>finish({connectivity:"timeout",failureReason:"timeout"}));socket.once("error",e=>finish({connectivity:"failed",failureReason:classifyNetworkFailure(e,tls)}));socket.once("connect",()=>{if(!tls)return finish({connectivity:"ok"});tlsSocket=tlsConnect({socket,servername:AUTH_HOST,rejectUnauthorized:true});tlsSocket.setTimeout(timeoutMs,()=>finish({connectivity:"timeout",failureReason:"timeout"}));tlsSocket.once("secureConnect",()=>finish({connectivity:"ok"}));tlsSocket.once("error",e=>finish({connectivity:"failed",failureReason:classifyNetworkFailure(e,true)}))})})}
async function defaultHead(){return new Promise<HttpProbe>(resolve=>{const request=httpsRequest({host:AUTH_HOST,port:AUTH_PORT,path:DEVICE_PATH,method:"HEAD",rejectUnauthorized:true,timeout:PROBE_TIMEOUT_MS},response=>{const status=response.statusCode;response.destroy();resolve({responseReceived:true,...(status?{status}:{})})});request.once("timeout",()=>{request.destroy();resolve({responseReceived:false})});request.once("error",()=>resolve({responseReceived:false}));request.end()})}
async function defaultVersion(command:string){return new Promise<string|undefined>(resolve=>execFile(command,["--version"],{timeout:PROBE_TIMEOUT_MS,maxBuffer:1024},(e,out)=>resolve(e?undefined:out.trim().match(/(?:codex-cli |codex )?(\d+\.\d+\.\d+)/)?.[1])))}
export async function diagnoseAuthEnvironment(d:Dependencies={}):Promise<AuthEnvironmentDiagnostics>{
 const env=d.environment??process.env,caPath=env.CODEX_CA_CERTIFICATE||env.SSL_CERT_FILE,customCaSource=env.CODEX_CA_CERTIFICATE?"codex_ca_certificate":env.SSL_CERT_FILE?"ssl_cert_file":"none",accessPath=d.accessPath??access,read=d.readSystemFile??(p=>readFile(p,"utf8")),home=env.CODEX_HOME??join(homedir(),".codex");
 const can=async(p:string,m:number)=>bounded(accessPath(p,m).then(()=>true),PROBE_TIMEOUT_MS,false);const ca=await bounded((d.statPath??stat)(SYSTEM_CA_BUNDLE).then(v=>({present:v.isFile(),nonEmpty:v.isFile()&&v.size>0})),PROBE_TIMEOUT_MS,{present:false,nonEmpty:false});
 const [addresses,ready,homeR,homeW,customR,kernel,version,marker]=await Promise.all([bounded((d.lookupHost??(h=>lookup(h,{all:true,verbatim:true})))(AUTH_HOST),PROBE_TIMEOUT_MS,[]),bounded(d.codexAppServerReady?.()??Promise.resolve(false),PROBE_TIMEOUT_MS,false),can(home,constants.R_OK),can(home,constants.W_OK),caPath?can(caPath,constants.R_OK):undefined,bounded(read("/proc/sys/net/ipv6/conf/all/disable_ipv6"),PROBE_TIMEOUT_MS,"0"),bounded((d.codexVersion??defaultVersion)(d.codexCommand??env.CODEX_COMMAND??"codex"),PROBE_TIMEOUT_MS+100,undefined),bounded(d.readCodexLibcMarker?.()??read("/etc/codex-runner/codex-native-libc"),PROBE_TIMEOUT_MS,"unknown")]);
 const v4=addresses.some(a=>a.family===4),v6=addresses.some(a=>a.family===6),first=addresses.find(a=>a.family===4||a.family===6),family=first?.family===4?"ipv4":first?.family===6?"ipv6":"none",policy=env.CODEX_RUNNER_ADDRESS_POLICY==="ipv4_preferred"?"ipv4_preferred":"system_default",libc=marker.trim()==="glibc"?"glibc":marker.trim()==="musl"?"musl":"unknown";
 const familyProbe=async(available:boolean,op:()=>Promise<ProbeResult|string>):Promise<ProbeResult>=>available?bounded(op().then(v=>typeof v==="string"?{connectivity:v as Connectivity}:v),PROBE_TIMEOUT_MS+100,{connectivity:"timeout",failureReason:"timeout"}):{connectivity:"unavailable"};const cp=d.connectHost??((h,p,f,t)=>socketProbe(h,p,f,t,false)),tp=d.tlsHost??((h,p,f,t)=>socketProbe(h,p,f,t,true));const [v4tcp,v6tcp,v4tls,v6tls,route]=await Promise.all([familyProbe(v4,()=>cp(AUTH_HOST,AUTH_PORT,4,PROBE_TIMEOUT_MS)),familyProbe(v6,()=>cp(AUTH_HOST,AUTH_PORT,6,PROBE_TIMEOUT_MS)),familyProbe(v4,()=>tp(AUTH_HOST,AUTH_PORT,4,PROBE_TIMEOUT_MS)),familyProbe(v6,()=>tp(AUTH_HOST,AUTH_PORT,6,PROBE_TIMEOUT_MS)),v4?bounded((d.deviceAuthHead??defaultHead)(),PROBE_TIMEOUT_MS+100,{responseReceived:false}):Promise.resolve({responseReceived:false})]);
 const summary:string[]=[];if(v6&&v6tls.connectivity!=="ok"&&v4tls.connectivity==="ok")summary.push("IPv6 is advertised but unavailable; the verified IPv4 TLS path is healthy.");if(route.responseReceived)summary.push("The OpenAI device-auth route returned an HTTP response to a non-mutating HEAD request.");
 return{runnerReachable:true,codexAppServerReady:ready,...(version?{codexVersion:version}:{}),codexVersionMatchesExpected:version===EXPECTED_CODEX_VERSION,codexNativeLibc:libc,codexAddressPolicyApplies:libc==="unknown"?null:libc==="glibc"&&policy==="ipv4_preferred",customCaSource,...(customR===undefined?{}:{customCaFileReadable:customR}),systemCaBundlePresent:ca.present,systemCaBundleReadable:await can(SYSTEM_CA_BUNDLE,constants.R_OK),systemCaBundleNonEmpty:ca.nonEmpty,httpProxyConfigured:present(env,"HTTP_PROXY","http_proxy"),httpsProxyConfigured:present(env,"HTTPS_PROXY","https_proxy"),allProxyConfigured:present(env,"ALL_PROXY","all_proxy"),noProxyConfigured:present(env,"NO_PROXY","no_proxy"),dnsResolution:addresses.length?"ok":"failed",ipv4Available:v4,ipv6Available:v6,systemResolverFirstFamily:family,runnerAddressPolicy:policy,runnerAddressPolicyEffective:policy==="system_default"?null:v4&&v6&&family==="ipv4",kernelIpv6Disabled:kernel.trim()==="1",ipv4TcpConnectivity:v4tcp.connectivity,ipv6TcpConnectivity:v6tcp.connectivity,ipv4TlsConnectivity:v4tls.connectivity,ipv6TlsConnectivity:v6tls.connectivity,...(v4tcp.failureReason?{ipv4TcpFailureReason:v4tcp.failureReason}:{}),...(v6tcp.failureReason?{ipv6TcpFailureReason:v6tcp.failureReason}:{}),...(v4tls.failureReason?{ipv4TlsFailureReason:v4tls.failureReason}:{}),...(v6tls.failureReason?{ipv6TlsFailureReason:v6tls.failureReason}:{}),deviceAuthRoute:route,codexHomeReadable:homeR,codexHomeWritable:homeW,summary};
}

export async function diagnoseProxyAuthEnvironment(d:Dependencies={}):Promise<AuthEnvironmentDiagnostics>{
 const env=d.environment??process.env,raw=env.HTTPS_PROXY??env.https_proxy;if(!raw)return diagnoseAuthEnvironment({...d,lookupHost:async()=>[],connectHost:async()=>({connectivity:"unavailable"}),tlsHost:async()=>({connectivity:"unavailable"}),deviceAuthHead:async()=>({responseReceived:false})});let proxy:URL;try{proxy=new URL(raw);if(proxy.protocol!=="http:"||proxy.username||proxy.password||proxy.pathname!=="/"||proxy.search||proxy.hash)throw new Error()}catch{return diagnoseAuthEnvironment({...d,lookupHost:async()=>[],connectHost:async()=>({connectivity:"failed",failureReason:"other"}),tlsHost:async()=>({connectivity:"failed",failureReason:"other"}),deviceAuthHead:async()=>({responseReceived:false})})}
 const probe=bounded(new Promise<HttpProbe>(resolve=>{const request=httpRequest({host:proxy.hostname,port:Number(proxy.port||80),method:"CONNECT",path:`${AUTH_HOST}:${AUTH_PORT}`,headers:{host:`${AUTH_HOST}:${AUTH_PORT}`},timeout:PROBE_TIMEOUT_MS},response=>{const status=response.statusCode;response.destroy();resolve({responseReceived:true,...(status?{status}:{})})});request.once("connect",response=>{const status=response.statusCode;response.socket.destroy();resolve({responseReceived:true,...(status?{status}:{})})});request.once("timeout",()=>{request.destroy();resolve({responseReceived:false})});request.once("error",()=>resolve({responseReceived:false}));request.end()}),PROBE_TIMEOUT_MS+100,{responseReceived:false}),asResult=async():Promise<ProbeResult>=>{const result=await probe;if(!result.responseReceived)return{connectivity:"failed",failureReason:"network_unreachable"};return result.status===200?{connectivity:"ok"}:{connectivity:"failed",failureReason:"connection_refused"}};
 const result=await diagnoseAuthEnvironment({...d,environment:env,lookupHost:async()=>[{address:"0.0.0.0",family:4}],connectHost:async()=>asResult(),tlsHost:async()=>asResult(),deviceAuthHead:async()=>probe});result.summary.push(result.deviceAuthRoute.status===200?"The provider route is reachable through the configured egress proxy.":result.deviceAuthRoute.responseReceived?"The configured egress proxy denied the provider route.":"The configured egress proxy is unavailable.");return result
}
