import {access,constants} from "node:fs/promises";
import {homedir} from "node:os";
import {join} from "node:path";
import {lookup} from "node:dns/promises";
import {connect,type Socket} from "node:net";
import {connect as tlsConnect,type TLSSocket} from "node:tls";
import {request as httpsRequest} from "node:https";

const AUTH_HOST="auth.openai.com",AUTH_PORT=443,PROBE_TIMEOUT_MS=2_000;
type Connectivity="ok"|"timeout"|"failed"|"unavailable";
type HttpProbe={responseReceived:boolean;status?:number;mitigationChallenge:boolean};
export type AuthEnvironmentDiagnostics={runnerReachable:true;codexAppServerReady:boolean;customCaSource:"none"|"codex_ca_certificate"|"ssl_cert_file";customCaFileReadable?:boolean;httpProxyConfigured:boolean;httpsProxyConfigured:boolean;allProxyConfigured:boolean;noProxyConfigured:boolean;dnsResolution:"ok"|"failed";ipv4Available:boolean;ipv6Available:boolean;ipv4TcpConnectivity:Connectivity;ipv6TcpConnectivity:Connectivity;ipv4TlsConnectivity:Connectivity;ipv6TlsConnectivity:Connectivity;httpsResponseReceived:boolean;httpsStatus?:number;httpsMitigationChallenge:boolean;tcpConnectivity:"ok"|"timeout"|"failed";codexHomeReadable:boolean;codexHomeWritable:boolean};
type LookupAddress={address:string;family:number};
type Dependencies={environment?:NodeJS.ProcessEnv;lookupHost?:(hostname:string)=>Promise<LookupAddress[]>;connectHost?:(host:string,port:number,family:4|6,timeoutMs:number)=>Promise<Exclude<Connectivity,"unavailable">>;tlsHost?:(host:string,port:number,family:4|6,timeoutMs:number)=>Promise<Exclude<Connectivity,"unavailable">>;httpsHead?:(host:string,port:number,family:4|6,timeoutMs:number)=>Promise<HttpProbe>;accessPath?:(path:string,mode:number)=>Promise<void>;codexAppServerReady?:()=>Promise<boolean>};
const present=(environment:NodeJS.ProcessEnv,upper:string,lower:string)=>Boolean(environment[upper]||environment[lower]);
const bounded=<T>(operation:Promise<T>,timeoutMs:number,fallback:T)=>new Promise<T>(resolve=>{const timer=setTimeout(()=>resolve(fallback),timeoutMs);operation.then(value=>{clearTimeout(timer);resolve(value)},()=>{clearTimeout(timer);resolve(fallback)})});
const boundedAccess=(operation:Promise<void>,timeoutMs:number)=>new Promise<void>((resolve,reject)=>{const timer=setTimeout(reject,timeoutMs);operation.then(()=>{clearTimeout(timer);resolve()},()=>{clearTimeout(timer);reject()})});
async function defaultConnect(host:string,port:number,family:4|6,timeoutMs:number){return new Promise<"ok"|"timeout"|"failed">(resolve=>{let done=false;const socket:Socket=connect({host,port,family});const finish=(result:"ok"|"timeout"|"failed")=>{if(done)return;done=true;socket.destroy();resolve(result)};socket.setTimeout(timeoutMs,()=>finish("timeout"));socket.once("connect",()=>finish("ok"));socket.once("error",()=>finish("failed"))})}
async function defaultTls(host:string,port:number,family:4|6,timeoutMs:number){return new Promise<"ok"|"timeout"|"failed">(resolve=>{let done=false,tlsSocket:TLSSocket|undefined;const socket:Socket=connect({host,port,family});const finish=(result:"ok"|"timeout"|"failed")=>{if(done)return;done=true;tlsSocket?.destroy();socket.destroy();resolve(result)};socket.setTimeout(timeoutMs,()=>finish("timeout"));socket.once("error",()=>finish("failed"));socket.once("connect",()=>{tlsSocket=tlsConnect({socket,servername:AUTH_HOST,rejectUnauthorized:true});tlsSocket.setTimeout(timeoutMs,()=>finish("timeout"));tlsSocket.once("secureConnect",()=>finish("ok"));tlsSocket.once("error",()=>finish("failed"))})})}
async function defaultHttpsHead(host:string,port:number,family:4|6,timeoutMs:number){return new Promise<HttpProbe>(resolve=>{let done=false;const finish=(result:HttpProbe)=>{if(done)return;done=true;request.destroy();resolve(result)};const request=httpsRequest({host,port,family,servername:AUTH_HOST,path:"/",method:"HEAD",rejectUnauthorized:true,timeout:timeoutMs},response=>{const status=response.statusCode;response.resume();finish({responseReceived:true,...(status!==undefined?{status}:{}),mitigationChallenge:response.headers["cf-mitigated"]==="challenge"})});request.once("timeout",()=>finish({responseReceived:false,mitigationChallenge:false}));request.once("error",()=>finish({responseReceived:false,mitigationChallenge:false}));request.end()})}
export async function diagnoseAuthEnvironment(dependencies:Dependencies={}):Promise<AuthEnvironmentDiagnostics>{
 const environment=dependencies.environment??process.env,caPath=environment.CODEX_CA_CERTIFICATE||environment.SSL_CERT_FILE,customCaSource=environment.CODEX_CA_CERTIFICATE?"codex_ca_certificate":environment.SSL_CERT_FILE?"ssl_cert_file":"none",accessPath=dependencies.accessPath??access,home=environment.CODEX_HOME??join(homedir(),".codex");
 const canAccess=async(mode:number)=>{try{await boundedAccess(accessPath(home,mode),PROBE_TIMEOUT_MS);return true}catch{return false}};const caReadable=async()=>{if(!caPath)return undefined;try{await boundedAccess(accessPath(caPath,constants.R_OK),PROBE_TIMEOUT_MS);return true}catch{return false}};
 const [addresses,codexAppServerReady,codexHomeReadable,codexHomeWritable,customCaFileReadable]=await Promise.all([bounded((dependencies.lookupHost??(hostname=>lookup(hostname,{all:true})))(AUTH_HOST),PROBE_TIMEOUT_MS,[]),bounded(dependencies.codexAppServerReady?.()??Promise.resolve(false),PROBE_TIMEOUT_MS,false),canAccess(constants.R_OK),canAccess(constants.W_OK),caReadable()]);
 const ipv4Available=addresses.some(value=>value.family===4),ipv6Available=addresses.some(value=>value.family===6),connectHost=dependencies.connectHost??defaultConnect,tlsHost=dependencies.tlsHost??defaultTls;
 const familyProbe=<T>(available:boolean,operation:()=>Promise<T>,fallback:T)=>available?bounded(operation(),PROBE_TIMEOUT_MS+100,fallback):Promise.resolve("unavailable" as const);
 const [ipv4TcpConnectivity,ipv6TcpConnectivity,ipv4TlsConnectivity,ipv6TlsConnectivity]=await Promise.all([familyProbe(ipv4Available,()=>connectHost(AUTH_HOST,AUTH_PORT,4,PROBE_TIMEOUT_MS),"timeout" as const),familyProbe(ipv6Available,()=>connectHost(AUTH_HOST,AUTH_PORT,6,PROBE_TIMEOUT_MS),"timeout" as const),familyProbe(ipv4Available,()=>tlsHost(AUTH_HOST,AUTH_PORT,4,PROBE_TIMEOUT_MS),"timeout" as const),familyProbe(ipv6Available,()=>tlsHost(AUTH_HOST,AUTH_PORT,6,PROBE_TIMEOUT_MS),"timeout" as const)]);
 const httpsFamily:4|6|undefined=ipv4Available?4:ipv6Available?6:undefined,httpsProbe=httpsFamily?await bounded((dependencies.httpsHead??defaultHttpsHead)(AUTH_HOST,AUTH_PORT,httpsFamily,PROBE_TIMEOUT_MS),PROBE_TIMEOUT_MS+100,{responseReceived:false,mitigationChallenge:false}):{responseReceived:false,mitigationChallenge:false};
 const tcpValues=[ipv4TcpConnectivity,ipv6TcpConnectivity],tcpConnectivity=tcpValues.includes("ok")?"ok":tcpValues.includes("timeout")?"timeout":"failed";
 const result:AuthEnvironmentDiagnostics={runnerReachable:true,codexAppServerReady,customCaSource,httpProxyConfigured:present(environment,"HTTP_PROXY","http_proxy"),httpsProxyConfigured:present(environment,"HTTPS_PROXY","https_proxy"),allProxyConfigured:present(environment,"ALL_PROXY","all_proxy"),noProxyConfigured:present(environment,"NO_PROXY","no_proxy"),dnsResolution:addresses.length?"ok":"failed",ipv4Available,ipv6Available,ipv4TcpConnectivity,ipv6TcpConnectivity,ipv4TlsConnectivity,ipv6TlsConnectivity,httpsResponseReceived:httpsProbe.responseReceived,...(httpsProbe.status!==undefined?{httpsStatus:httpsProbe.status}:{}),httpsMitigationChallenge:httpsProbe.mitigationChallenge,tcpConnectivity,codexHomeReadable,codexHomeWritable};
 if(customCaFileReadable!==undefined)result.customCaFileReadable=customCaFileReadable;return result;
}
