import {mkdir,readFile,rename,writeFile} from "node:fs/promises";
import {join} from "node:path";
import {randomBytes} from "node:crypto";

export interface EmergencyState{emergencyStopped:boolean;stoppedGeneration?:string;updatedAt:string;hardRestart:{attempted:boolean;succeeded:boolean;reason?:"not_configured"|"request_failed"}}
function parseState(value:unknown):EmergencyState{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("control_state_untrusted");const v=value as Record<string,unknown>,keys=Object.keys(v);if(keys.some(key=>!["emergencyStopped","stoppedGeneration","updatedAt","hardRestart"].includes(key))||!Object.hasOwn(v,"emergencyStopped")||!Object.hasOwn(v,"updatedAt")||!Object.hasOwn(v,"hardRestart")||typeof v.emergencyStopped!=="boolean"||typeof v.updatedAt!=="string"||v.updatedAt.length>40||!Number.isFinite(Date.parse(v.updatedAt)))throw new Error("control_state_untrusted");if(v.stoppedGeneration!==undefined&&(typeof v.stoppedGeneration!=="string"||v.stoppedGeneration.length<1||v.stoppedGeneration.length>256||!/^[A-Za-z0-9._:-]+$/.test(v.stoppedGeneration)))throw new Error("control_state_untrusted");if(!v.emergencyStopped&&v.stoppedGeneration!==undefined)throw new Error("control_state_untrusted");if(!v.hardRestart||typeof v.hardRestart!=="object"||Array.isArray(v.hardRestart))throw new Error("control_state_untrusted");const h=v.hardRestart as Record<string,unknown>;if(Object.keys(h).some(key=>!["attempted","succeeded","reason"].includes(key))||typeof h.attempted!=="boolean"||typeof h.succeeded!=="boolean"||(h.reason!==undefined&&h.reason!=="not_configured"&&h.reason!=="request_failed"))throw new Error("control_state_untrusted");const valid=(!h.attempted&&!h.succeeded&&(h.reason===undefined||h.reason==="not_configured"))||(h.attempted&&h.succeeded&&h.reason===undefined)||(h.attempted&&!h.succeeded&&h.reason==="request_failed");if(!valid)throw new Error("control_state_untrusted");return v as unknown as EmergencyState}
export class EmergencyStopController{
 private state:EmergencyState={emergencyStopped:false,updatedAt:new Date(0).toISOString(),hardRestart:{attempted:false,succeeded:false}};
 private transition=Promise.resolve();
 private constructor(private directory:string,private webhook?:string){}
 static async create(directory:string,webhook?:string){const value=new EmergencyStopController(directory,webhook);await mkdir(directory,{recursive:true,mode:0o700});try{const raw=await readFile(join(directory,"control.json"),"utf8");if(Buffer.byteLength(raw)>4096)throw new Error("control_state_untrusted");value.state=parseState(JSON.parse(raw))}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw new Error("control_state_untrusted")}return value}
 snapshot(){return structuredClone(this.state)}
 restartPhaseComplete(){return this.state.hardRestart.attempted||this.state.hardRestart.reason==="not_configured"}
 private serialize<T>(operation:()=>Promise<T>){const result=this.transition.then(operation,operation);this.transition=result.then(()=>{},()=>{});return result}
 private async persist(next:EmergencyState){const target=join(this.directory,"control.json"),temp=`${target}.${randomBytes(8).toString("hex")}.tmp`;await writeFile(temp,JSON.stringify(next),{mode:0o600,flag:"wx"});await rename(temp,target);this.state=next}
 async latch(generation?:string){return this.serialize(async()=>{const stoppedGeneration=generation??this.state.stoppedGeneration;await this.persist({emergencyStopped:true,...(stoppedGeneration?{stoppedGeneration}:{}),updatedAt:new Date().toISOString(),hardRestart:{attempted:false,succeeded:false}});return this.snapshot()})}
 async recordStoppedGeneration(generation:string){return this.serialize(async()=>{if(!this.state.emergencyStopped||this.state.stoppedGeneration)return this.snapshot();await this.persist({...this.state,stoppedGeneration:generation,updatedAt:new Date().toISOString()});return this.snapshot()})}
 async triggerHardRestart(){return this.serialize(async()=>{if(!this.state.emergencyStopped)return this.snapshot();let hardRestart:EmergencyState["hardRestart"]={attempted:false,succeeded:false,reason:"not_configured"};if(this.webhook){try{const response=await fetch(new URL(this.webhook),{method:"POST",redirect:"manual",signal:AbortSignal.timeout(10_000)});hardRestart={attempted:true,succeeded:response.status>=200&&response.status<300};if(!hardRestart.succeeded)hardRestart.reason="request_failed"}catch{hardRestart={attempted:true,succeeded:false,reason:"request_failed"}}}await this.persist({...this.state,hardRestart,updatedAt:new Date().toISOString()});return this.snapshot()})}
 async stop(generation:string|undefined,interrupt:()=>Promise<void>){await this.latch(generation);await interrupt().catch(()=>{});return this.triggerHardRestart()}
 async resume(currentGeneration:string|undefined,idle:boolean){const observed=this.snapshot();if(observed.emergencyStopped&&!this.restartPhaseComplete())throw new Error("unsafe_resume");return this.serialize(async()=>{if(!this.state.emergencyStopped)return this.snapshot();if(!this.restartPhaseComplete()||!currentGeneration||!idle||(this.state.stoppedGeneration&&currentGeneration===this.state.stoppedGeneration))throw new Error("unsafe_resume");await this.persist({emergencyStopped:false,updatedAt:new Date().toISOString(),hardRestart:this.state.hardRestart});return this.snapshot()})}
}
