import {createServer,type IncomingMessage,type ServerResponse} from "node:http";
import {createHash,createPrivateKey,createPublicKey,randomBytes,randomUUID,sign,verify,type KeyObject} from "node:crypto";
import {realpath} from "node:fs/promises";
import {isAbsolute,relative,sep} from "node:path";
import type {AppServerClient,WorkflowTurnResult} from "./app-server-client.js";
import {SafeError,safeError} from "./errors.js";
import {diagnoseWorkspace,workspaceReadiness} from "./environments.js";
import {diagnoseProxyAuthEnvironment,type AuthEnvironmentDiagnostics} from "./auth-environment-diagnostics.js";
import type {RunnerConfiguration} from "./configuration.js";

const MAX_BODY=1_100_000,ID=/^[a-f0-9-]{36}$/,NONCE=/^[a-f0-9]{48}$/,AUTH_WINDOW_MS=30_000,json=(r:ServerResponse,s:number,v:unknown)=>{r.writeHead(s,{"content-type":"application/json","cache-control":"no-store","x-content-type-options":"nosniff"});r.end(JSON.stringify(v))};
const canonicalRequest=(method:string,path:string,timestamp:string,nonce:string,raw:Buffer)=>Buffer.from(`adt-executor-v1\n${method}\n${path}\n${timestamp}\n${nonce}\n${createHash("sha256").update(raw).digest("hex")}`,"utf8");
export function executorRequestHeaders(privateKey:string,method:string,path:string,raw:Buffer,now=Date.now(),nonce=randomBytes(24).toString("hex")){let key:KeyObject;try{key=createPrivateKey(privateKey)}catch{throw new Error("invalid_executor_signing_key")}if(key.asymmetricKeyType!=="ed25519")throw new Error("invalid_executor_signing_key");const timestamp=String(now),signature=sign(null,canonicalRequest(method,path,timestamp,nonce,raw),key).toString("base64url");return{"x-codex-executor-timestamp":timestamp,"x-codex-executor-nonce":nonce,"x-codex-executor-signature":signature}}
async function rawBody(req:IncomingMessage){let n=0;const chunks:Buffer[]=[];for await(const chunk of req){const b=Buffer.from(chunk);n+=b.length;if(n>MAX_BODY)throw new SafeError("request_too_large",413);chunks.push(b)}return Buffer.concat(chunks)}
function parsedBody(req:IncomingMessage,raw:Buffer){if(raw.length&&!req.headers["content-type"]?.startsWith("application/json"))throw new SafeError("json_content_type_required",415);try{return raw.length?JSON.parse(raw.toString("utf8")):undefined}catch{throw new SafeError("invalid_request",400)}}
function object(value:unknown,allowed:string[]){if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value).some(k=>!allowed.includes(k)))throw new SafeError("invalid_request",400);return value as Record<string,unknown>}
export async function safeCwd(candidate:string,root:string){const canonicalRoot=await realpath(root),canonical=await realpath(candidate),rel=relative(canonicalRoot,canonical);if(rel===""||(!isAbsolute(rel)&&rel!==".."&&!rel.startsWith(`..${sep}`)))return canonical;throw new SafeError("workspace_outside_root",400)}
type Execution={state:"running"|"completed"|"failed"|"cancelled";result?:WorkflowTurnResult;threadId?:string;turnId?:string;startedAt:string;updatedAt:string;activityCount:number};
export function createExecutorServer(configuration:RunnerConfiguration,app:AppServerClient,authDiagnostics=()=>diagnoseProxyAuthEnvironment({codexCommand:configuration.codexCommand,codexAppServerReady:()=>app.readiness()})){
 const generation=randomUUID(),executions=new Map<string,Execution>(),seenNonces=new Map<string,number>();let active:string|undefined;
 let verifyingKey:KeyObject;try{verifyingKey=createPublicKey(configuration.executorVerifyingPublicKey!);if(verifyingKey.asymmetricKeyType!=="ed25519")throw new Error()}catch{throw new Error("invalid_executor_verifying_key")}
 return createServer({requestTimeout:65_000,headersTimeout:10_000},async(req,res)=>{const path=new URL(req.url??"/","http://executor.invalid").pathname;try{
  if(req.method==="GET"&&path==="/health")return json(res,200,{ok:true,role:"executor",generation});const raw=await rawBody(req),timestamp=req.headers["x-codex-executor-timestamp"],nonce=req.headers["x-codex-executor-nonce"],signature=req.headers["x-codex-executor-signature"],now=Date.now();for(const [key,expiry] of seenNonces)if(expiry<now)seenNonces.delete(key);if(typeof timestamp!=="string"||!/^[0-9]{13}$/.test(timestamp)||Math.abs(now-Number(timestamp))>AUTH_WINDOW_MS||typeof nonce!=="string"||!NONCE.test(nonce)||seenNonces.has(nonce)||typeof signature!=="string"||signature.length>128)throw new SafeError("unauthorized",401);let signatureBytes:Buffer;try{signatureBytes=Buffer.from(signature,"base64url")}catch{throw new SafeError("unauthorized",401)}if(signatureBytes.length!==64||!verify(null,canonicalRequest(req.method??"",path,timestamp,nonce,raw),verifyingKey,signatureBytes))throw new SafeError("unauthorized",401);seenNonces.set(nonce,now+AUTH_WINDOW_MS);const value=parsedBody(req,raw);
  if(req.method==="GET"&&path==="/internal/v1/status")return json(res,200,{generation,healthy:await app.readiness(),activeExecutionId:active??null,boundary:"container",release:{runnerVersion:configuration.runnerVersion}});
  if(req.method==="GET"&&path==="/internal/v1/account"){const raw=await app.status() as {account?:Record<string,unknown>|null},account=raw?.account;if(!account)return json(res,200,{account:null});const string=(v:unknown)=>typeof v==="string"&&v.length>0&&v.length<=80?v:undefined,type=string(account.type),authMode=string(account.authMode),planType=string(account.planType);return json(res,200,{account:{...(type?{type}:{}),...(authMode?{authMode}:{}),...(planType?{planType}:{})}})}
  if(req.method==="POST"&&path==="/internal/v1/auth/device/start"){if(value!==undefined)throw new SafeError("invalid_request",400);const raw=await app.startDeviceLogin() as Record<string,unknown>;if(typeof raw.loginId!=="string"||raw.loginId.length>256||typeof raw.verificationUrl!=="string"||raw.verificationUrl.length>2048||typeof raw.userCode!=="string"||raw.userCode.length>128)throw new SafeError("app_server_unavailable",503);return json(res,200,{loginId:raw.loginId,verificationUrl:raw.verificationUrl,userCode:raw.userCode})}
  if(req.method==="POST"&&path==="/internal/v1/auth/logout"){if(value!==undefined)throw new SafeError("invalid_request",400);await app.logout();return json(res,200,{connected:false})}
  if(req.method==="GET"&&path==="/internal/v1/models")return json(res,200,{models:await app.listModels?.()??[]});
  if(req.method==="POST"&&path==="/internal/v1/test"){if(value!==undefined)throw new SafeError("invalid_request",400);if(active)return json(res,200,{ok:false,reason:"test_in_progress"});return json(res,200,await app.testCodex?.("danger-full-access")??{ok:false,reason:"app_server_unavailable"})}
  if(req.method==="GET"&&path==="/internal/v1/diagnostics/auth-environment")return json(res,200,{generation,diagnostics:await authDiagnostics()});
  if(req.method==="POST"&&path==="/internal/v1/diagnostics/execution-boundary"){const v=object(value,["environmentKey","sandbox"]);if(typeof v.environmentKey!=="string"||v.environmentKey.length>80||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v.environmentKey)||(v.sandbox!=="read-only"&&v.sandbox!=="workspace-write"))throw new SafeError("invalid_request",400);if(v.sandbox==="read-only")return json(res,200,{generation,diagnostics:{environmentKey:v.environmentKey,status:"unavailable",backend:"container",reason:"read_only_not_supported"}});if(active)return json(res,200,{generation,diagnostics:{environmentKey:v.environmentKey,status:"unavailable",backend:"container",reason:"execution_in_progress"}});const result=await app.testCodex?.("danger-full-access");return json(res,200,{generation,diagnostics:{environmentKey:v.environmentKey,status:result?.ok?"available":"unavailable",backend:"container",reason:result?.ok?"ok":"execution_probe_failed"}})}
  if(req.method==="POST"&&path==="/internal/v1/workspace/diagnostics"){const v=object(value,["environmentKey","cwd","sandbox"]);if(typeof v.environmentKey!=="string"||v.environmentKey.length>80||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v.environmentKey)||typeof v.cwd!=="string"||v.cwd.length>4096||(v.sandbox!=="read-only"&&v.sandbox!=="workspace-write"))throw new SafeError("invalid_request",400);const cwd=await safeCwd(v.cwd,configuration.workspaceRoot??"/workspaces"),ready=v.sandbox==="workspace-write"&&await workspaceReadiness(cwd,"workspace-write");return json(res,200,{generation,diagnostics:await diagnoseWorkspace({key:v.environmentKey,name:"Executor workspace",cwd,enabled:true,ready,sandbox:v.sandbox})})}
  if(req.method==="POST"&&path==="/internal/v1/executions"){if(active)throw new SafeError("runner_busy",409);const v=object(value,["cwd","sandbox","prompt","model","reasoningEffort"]);if(typeof v.cwd!=="string"||typeof v.prompt!=="string"||Buffer.byteLength(v.prompt)>524_320||v.sandbox!=="workspace-write"||(v.model!==undefined&&(typeof v.model!=="string"||v.model.length>120))||(v.reasoningEffort!==undefined&&(typeof v.reasoningEffort!=="string"||v.reasoningEffort.length>40)))throw new SafeError(v.sandbox==="read-only"?"read_only_not_supported": "invalid_request",v.sandbox==="read-only"?409:400);const cwd=await safeCwd(v.cwd,configuration.workspaceRoot??"/workspaces");if(!await workspaceReadiness(cwd,"workspace-write"))throw new SafeError("environment_not_ready",409);const id=randomUUID(),now=new Date().toISOString(),record:Execution={state:"running",startedAt:now,updatedAt:now,activityCount:0};executions.set(id,record);active=id;void app.runWorkflowTurn!({cwd,sandbox:"danger-full-access",prompt:v.prompt as string,...(v.model?{model:v.model as string}:{}),...(v.reasoningEffort?{reasoningEffort:v.reasoningEffort as string}:{}),onStarted:(threadId,turnId)=>{record.threadId=threadId;record.turnId=turnId;record.activityCount++;record.updatedAt=new Date().toISOString()}}).then(result=>{record.result=result;record.state=result.ok?"completed":record.state==="cancelled"?"cancelled":"failed";record.updatedAt=new Date().toISOString()}).catch(()=>{record.result={ok:false,reason:"turn_failed"};record.state="failed";record.updatedAt=new Date().toISOString()}).finally(()=>{if(active===id)active=undefined});return json(res,202,{executionId:id,generation})}
  const match=/^\/internal\/v1\/executions\/([a-f0-9-]{36})(\/cancel)?$/.exec(path);if(match&&!ID.test(match[1]!))throw new SafeError("not_found",404);if(match&&req.method==="GET"&&!match[2]){const execution=executions.get(match[1]!);if(!execution)throw new SafeError("not_found",404);return json(res,200,{executionId:match[1],generation,...execution})}if(match&&req.method==="POST"&&match[2]){if(value!==undefined)throw new SafeError("invalid_request",400);const execution=executions.get(match[1]!);if(!execution)throw new SafeError("not_found",404);if(execution.state==="running"&&execution.threadId&&execution.turnId){execution.state="cancelled";await app.interruptWorkflowTurn?.(execution.threadId,execution.turnId)}return json(res,200,{executionId:match[1],generation,state:execution.state})}
  throw new SafeError("not_found",404);
 }catch(error){const safe=safeError(error);json(res,safe.status,{error:safe.code})}}).on("close",()=>void app.close());
}

export class ExecutorTransportError extends Error{constructor(){super("executor_transport")}}
export class ExecutorGenerationError extends Error{constructor(){super("executor_generation")}}
export class ExecutorProtocolError extends Error{constructor(){super("executor_protocol")}}
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,MAX_RESPONSE=300_000;
function exact(value:unknown,required:string[],optional:string[]=[]){if(!value||typeof value!=="object"||Array.isArray(value)||required.some(k=>!Object.hasOwn(value,k))||Object.keys(value).some(k=>![...required,...optional].includes(k)))throw new ExecutorProtocolError();return value as Record<string,unknown>}
function id(value:unknown){if(typeof value!=="string"||!UUID.test(value))throw new ExecutorProtocolError();return value}
function safeString(value:unknown,max:number,empty=false){if(typeof value!=="string"||value.length>max||(!empty&&!value))throw new ExecutorProtocolError();return value}
function status(value:unknown){const v=exact(value,["generation","healthy","activeExecutionId","boundary","release"]),release=exact(v.release,["runnerVersion"]);if(typeof v.healthy!=="boolean"||(v.activeExecutionId!==null&&(typeof v.activeExecutionId!=="string"||!UUID.test(v.activeExecutionId)))||v.boundary!=="container")throw new ExecutorProtocolError();return{generation:id(v.generation),healthy:v.healthy,activeExecutionId:v.activeExecutionId as string|null,boundary:"container" as const,release:{runnerVersion:safeString(release.runnerVersion,64)}}}
function workspace(value:unknown){const v=exact(value,["environmentKey","filesystemReady","gitAvailable","gitRepository","headCommit","dirty"]);safeString(v.environmentKey,80);if(typeof v.filesystemReady!=="boolean"||typeof v.gitAvailable!=="boolean"||typeof v.gitRepository!=="boolean"||(v.headCommit!==null&&(typeof v.headCommit!=="string"||!/^[a-f0-9]{40}$/.test(v.headCommit)))||(v.dirty!==null&&typeof v.dirty!=="boolean"))throw new ExecutorProtocolError();return v as unknown as import("./environments.js").WorkspaceDiagnostics}
export type ExecutionBoundaryDiagnostics={environmentKey:string;status:"available"|"unavailable";backend:"container";reason:"ok"|"read_only_not_supported"|"execution_probe_failed"|"execution_in_progress"};
function boundary(value:unknown){const v=exact(value,["environmentKey","status","backend","reason"]);safeString(v.environmentKey,80);if(!["available","unavailable"].includes(String(v.status))||v.backend!=="container"||!["ok","read_only_not_supported","execution_probe_failed","execution_in_progress"].includes(String(v.reason))||(v.status==="available")!==(v.reason==="ok"))throw new ExecutorProtocolError();return v as unknown as ExecutionBoundaryDiagnostics}
function authEnvironment(value:unknown){const v=value as Record<string,unknown>,required=["runnerReachable","codexAppServerReady","codexVersionMatchesExpected","codexNativeLibc","codexAddressPolicyApplies","customCaSource","systemCaBundlePresent","systemCaBundleReadable","systemCaBundleNonEmpty","httpProxyConfigured","httpsProxyConfigured","allProxyConfigured","noProxyConfigured","dnsResolution","ipv4Available","ipv6Available","systemResolverFirstFamily","runnerAddressPolicy","runnerAddressPolicyEffective","kernelIpv6Disabled","ipv4TcpConnectivity","ipv6TcpConnectivity","ipv4TlsConnectivity","ipv6TlsConnectivity","deviceAuthRoute","codexHomeReadable","codexHomeWritable","summary"],optional=["codexVersion","customCaFileReadable","ipv4TcpFailureReason","ipv6TcpFailureReason","ipv4TlsFailureReason","ipv6TlsFailureReason"];exact(value,required,optional);const booleans=["codexAppServerReady","codexVersionMatchesExpected","systemCaBundlePresent","systemCaBundleReadable","systemCaBundleNonEmpty","httpProxyConfigured","httpsProxyConfigured","allProxyConfigured","noProxyConfigured","ipv4Available","ipv6Available","kernelIpv6Disabled","codexHomeReadable","codexHomeWritable"],connectivity=new Set(["ok","timeout","failed","unavailable"]),reasons=new Set(["network_unreachable","address_unavailable","connection_refused","connection_reset","certificate","tls_protocol","timeout","other"]),route=exact(v.deviceAuthRoute,["responseReceived"],["status"]);if(v.runnerReachable!==true||booleans.some(k=>typeof v[k]!=="boolean")||(v.codexVersion!==undefined&&(typeof v.codexVersion!=="string"||!/^[0-9]+\.[0-9]+\.[0-9]+$/.test(v.codexVersion)))||!["glibc","musl","unknown"].includes(String(v.codexNativeLibc))||(v.codexAddressPolicyApplies!==null&&typeof v.codexAddressPolicyApplies!=="boolean")||!["none","codex_ca_certificate","ssl_cert_file"].includes(String(v.customCaSource))||!["ok","failed"].includes(String(v.dnsResolution))||!["ipv4","ipv6","none"].includes(String(v.systemResolverFirstFamily))||!["system_default","ipv4_preferred"].includes(String(v.runnerAddressPolicy))||(v.runnerAddressPolicyEffective!==null&&typeof v.runnerAddressPolicyEffective!=="boolean")||![v.ipv4TcpConnectivity,v.ipv6TcpConnectivity,v.ipv4TlsConnectivity,v.ipv6TlsConnectivity].every(x=>connectivity.has(String(x)))||![v.ipv4TcpFailureReason,v.ipv6TcpFailureReason,v.ipv4TlsFailureReason,v.ipv6TlsFailureReason].every(x=>x===undefined||reasons.has(String(x)))||typeof route.responseReceived!=="boolean"||(route.status!==undefined&&(!Number.isInteger(route.status)||Number(route.status)<100||Number(route.status)>599))||!Array.isArray(v.summary)||v.summary.length>20||v.summary.some(x=>typeof x!=="string"||x.length>240))throw new ExecutorProtocolError();return v as unknown as AuthEnvironmentDiagnostics}
export class RemoteExecutorClient implements AppServerClient{
 private uncertain?:()=>Promise<void>;private readonly reconcileAfterMs=10_000;
 constructor(private readonly base:string,private readonly signingPrivateKey:string,private generation?:string){}
 setUncertainExecutionHandler(handler:()=>Promise<void>){this.uncertain=handler}
 private async request(path:string,method="GET",payload?:unknown){const bodyText=payload===undefined?undefined:JSON.stringify(payload),raw=Buffer.from(bodyText??"","utf8"),auth=executorRequestHeaders(this.signingPrivateKey,method,path,raw);let response:Response;try{response=await fetch(new URL(path,this.base),{method,headers:{accept:"application/json",...auth,...(payload===undefined?{}:{"content-type":"application/json"})},body:bodyText,redirect:"manual",signal:AbortSignal.timeout(10_000)})}catch{throw new ExecutorTransportError()}if(response.status>=300&&response.status<400)throw new ExecutorProtocolError();if(Number(response.headers.get("content-length")??0)>MAX_RESPONSE||!response.headers.get("content-type")?.toLowerCase().startsWith("application/json"))throw new ExecutorProtocolError();let text:string;try{text=await response.text()}catch{throw new ExecutorTransportError()}if(Buffer.byteLength(text)>MAX_RESPONSE)throw new ExecutorProtocolError();let value:unknown;try{value=JSON.parse(text)}catch{throw new ExecutorProtocolError()}if(!response.ok){const error=exact(value,["error"]);if(response.status===404&&error.error==="not_found")throw new ExecutorGenerationError();throw new ExecutorTransportError()}return value}
 private observe(value:string){if(this.generation&&this.generation!==value)throw new ExecutorGenerationError();this.generation=value}
 async readiness(){try{const s=status(await this.request("/internal/v1/status"));this.observe(s.generation);return s.healthy}catch{return false}}
 async status(){const v=exact(await this.request("/internal/v1/account"),["account"]);if(v.account!==null){const account=exact(v.account,[],["type","authMode","planType"]);for(const value of Object.values(account))safeString(value,80)}return v}
 async startDeviceLogin(){const v=exact(await this.request("/internal/v1/auth/device/start","POST"),["loginId","verificationUrl","userCode"]);return{loginId:safeString(v.loginId,256),verificationUrl:safeString(v.verificationUrl,2048),userCode:safeString(v.userCode,128)}}
 async logout(){const v=exact(await this.request("/internal/v1/auth/logout","POST"),["connected"]);if(v.connected!==false)throw new ExecutorProtocolError();return{connected:false}}
 async listModels(){const wrapper=exact(await this.request("/internal/v1/models"),["models"]);if(!Array.isArray(wrapper.models)||wrapper.models.length>25)throw new ExecutorProtocolError();return wrapper.models.map(raw=>{const v=exact(raw,["id","threadModel","displayName","isDefault","defaultReasoningEffort","supportedReasoningEfforts"]);if(typeof v.isDefault!=="boolean"||!Array.isArray(v.supportedReasoningEfforts)||v.supportedReasoningEfforts.length>12)throw new ExecutorProtocolError();return{id:safeString(v.id,120),threadModel:safeString(v.threadModel,120),displayName:safeString(v.displayName,120),isDefault:v.isDefault,defaultReasoningEffort:safeString(v.defaultReasoningEffort,40),supportedReasoningEfforts:v.supportedReasoningEfforts.map(raw=>{const e=exact(raw,["reasoningEffort","description"]);return{reasoningEffort:safeString(e.reasoningEffort,40),description:safeString(e.description,240,true)}})}})}
 async testCodex(){const value=await this.request("/internal/v1/test","POST"),ok=value&&typeof value==="object"&&!Array.isArray(value)&&(value as Record<string,unknown>).ok===true,v=exact(value,["ok",ok?"durationMs":"reason"]),reasons=new Set(["codex_not_connected","app_server_unavailable","thread_start_failed","turn_start_failed","turn_failed","timeout","unexpected_output","unexpected_tool_activity","test_in_progress"]);if(v.ok===true&&Number.isInteger(v.durationMs)&&Number(v.durationMs)>=0&&Number(v.durationMs)<=60_000)return{ok:true as const,durationMs:Number(v.durationMs)};if(v.ok===false&&reasons.has(String(v.reason)))return{ok:false as const,reason:v.reason as import("./app-server-client.js").CodexTestFailureReason};throw new ExecutorProtocolError()}
 async workspaceDiagnostics(environmentKey:string,cwd:string,sandbox:"read-only"|"workspace-write"){const current=await this.executorStatus(),wrapper=exact(await this.request("/internal/v1/workspace/diagnostics","POST",{environmentKey,cwd,sandbox}),["generation","diagnostics"]);if(id(wrapper.generation)!==current.generation)throw new ExecutorGenerationError();return workspace(wrapper.diagnostics)}
 async executionBoundaryDiagnostics(environmentKey:string,sandbox:"read-only"|"workspace-write"){const current=await this.executorStatus(),wrapper=exact(await this.request("/internal/v1/diagnostics/execution-boundary","POST",{environmentKey,sandbox}),["generation","diagnostics"]);if(id(wrapper.generation)!==current.generation)throw new ExecutorGenerationError();return boundary(wrapper.diagnostics)}
 async authEnvironmentDiagnostics(){const current=await this.executorStatus(),wrapper=exact(await this.request("/internal/v1/diagnostics/auth-environment"),["generation","diagnostics"]);if(id(wrapper.generation)!==current.generation)throw new ExecutorGenerationError();return authEnvironment(wrapper.diagnostics)}
 async executorStatus(){const value=status(await this.request("/internal/v1/status"));this.generation=value.generation;return value}
 async observeWorkflowTurn(generation:string,executionId:string):Promise<WorkflowTurnResult>{let lostAt:number|undefined,escalated=false;for(;;){await new Promise(r=>setTimeout(r,250));let value:unknown;try{value=await this.request(`/internal/v1/executions/${executionId}`);lostAt=undefined}catch(error){if(error instanceof ExecutorGenerationError)return{ok:false,reason:"runner_restarted"};if(error instanceof ExecutorTransportError||error instanceof ExecutorProtocolError){lostAt??=Date.now();try{const current=status(await this.request("/internal/v1/status"));if(current.generation!==generation)return{ok:false,reason:"runner_restarted"}}catch(statusError){if(!(statusError instanceof ExecutorTransportError)&&!(statusError instanceof ExecutorProtocolError))throw statusError}if(!escalated&&Date.now()-lostAt>=this.reconcileAfterMs){escalated=true;await this.uncertain?.().catch(()=>{})}continue}throw error}const v=exact(value,["executionId","generation","state","startedAt","updatedAt","activityCount"],["result","threadId","turnId"]);if(id(v.executionId)!==executionId||id(v.generation)!==generation)return{ok:false,reason:"runner_restarted"};if(!["running","completed","failed","cancelled"].includes(String(v.state))||!Number.isInteger(v.activityCount)||Number(v.activityCount)<0||Number(v.activityCount)>1_000_000||typeof v.startedAt!=="string"||typeof v.updatedAt!=="string"||!Number.isFinite(Date.parse(v.startedAt))||!Number.isFinite(Date.parse(v.updatedAt)))throw new ExecutorProtocolError();if(v.state==="running")continue;if(!v.result||typeof v.result!=="object")return{ok:false,reason:"turn_failed"};const raw=v.result as Record<string,unknown>,success=raw.ok===true,result=exact(raw,success?["ok","outputText","threadId","turnId"]:["ok","reason"],success?[]:["threadId","turnId"]) as unknown as WorkflowTurnResult;if(result.ok){if(typeof result.outputText!=="string"||Buffer.byteLength(result.outputText)>262_144||!safeString(result.threadId,256)||!safeString(result.turnId,256))throw new ExecutorProtocolError()}else if(!["thread_start_failed","turn_start_failed","turn_failed","interaction_required","output_too_large"].includes(result.reason)||(result.threadId!==undefined&&!safeString(result.threadId,256))||(result.turnId!==undefined&&!safeString(result.turnId,256)))throw new ExecutorProtocolError();return result}}
 private async reconcileAmbiguousStart(generation:string):Promise<WorkflowTurnResult>{const lostAt=Date.now();let escalated=false;for(;;){await new Promise(resolve=>setTimeout(resolve,250));try{const current=status(await this.request("/internal/v1/status"));if(current.generation!==generation)return{ok:false,reason:"runner_restarted"};if(current.activeExecutionId===null)return{ok:false,reason:"turn_start_failed"}}catch(error){if(error instanceof ExecutorGenerationError)return{ok:false,reason:"runner_restarted"};if(!(error instanceof ExecutorTransportError)&&!(error instanceof ExecutorProtocolError))throw error}if(!escalated&&Date.now()-lostAt>=this.reconcileAfterMs){escalated=true;await this.uncertain?.().catch(()=>{})}}}
 async reconcileUnknownExecution():Promise<WorkflowTurnResult>{let observedGeneration:string|undefined,escalated=false;const started=Date.now();for(;;){try{const current=status(await this.request("/internal/v1/status"));observedGeneration??=current.generation;if(current.generation!==observedGeneration||current.activeExecutionId===null)return{ok:false,reason:"runner_restarted"}}catch(error){if(!(error instanceof ExecutorTransportError)&&!(error instanceof ExecutorProtocolError)&&!(error instanceof ExecutorGenerationError))throw error}if(!escalated&&Date.now()-started>=this.reconcileAfterMs){escalated=true;await this.uncertain?.().catch(()=>{})}await new Promise(resolve=>setTimeout(resolve,250))}}
 async runWorkflowTurn(input:Parameters<NonNullable<AppServerClient["runWorkflowTurn"]>>[0]){const current=await this.executorStatus();try{const start=exact(await this.request("/internal/v1/executions","POST",input),["executionId","generation"]),executionId=id(start.executionId),generation=id(start.generation);if(generation!==current.generation)return{ok:false,reason:"runner_restarted"} as WorkflowTurnResult;this.observe(generation);input.onStarted?.(generation,executionId);return await this.observeWorkflowTurn(generation,executionId)}catch(error){if(error instanceof ExecutorGenerationError)return{ok:false,reason:"runner_restarted"} as WorkflowTurnResult;if(error instanceof ExecutorTransportError||error instanceof ExecutorProtocolError)return this.reconcileAmbiguousStart(current.generation);throw error}}

 async interruptWorkflowTurn(generation:string,executionId:string){try{const v=exact(await this.request(`/internal/v1/executions/${executionId}/cancel`,"POST"),["executionId","generation","state"]);if(id(v.executionId)!==executionId||id(v.generation)!==generation||!["running","completed","failed","cancelled"].includes(String(v.state)))throw new ExecutorProtocolError()}catch(error){if(error instanceof ExecutorTransportError||error instanceof ExecutorGenerationError)return;throw error}}
 async close(){}
}
