import {createHash,randomBytes} from "node:crypto";
import {readFile,readdir,rename,stat,writeFile} from "node:fs/promises";
import {join} from "node:path";
import type {AppServerClient,WorkflowTurnResult} from "./app-server-client.js";
import type {RunnerEnvironment} from "./environments.js";
import {ensureStateDirectory} from "./environments.js";
import {SafeError} from "./errors.js";

export type JobFailureReason="authentication_failed"|"runner_restarted"|"thread_start_failed"|"turn_start_failed"|"turn_failed"|"interaction_required"|"output_too_large"|"timeout"|"internal_error";
export interface CodexJobStartInput{idempotencyKey:string;environmentKey:string;prompt:string;model?:string;reasoningEffort?:string}
export type CodexJobStatus={jobId:string;state:"queued"|"running"}|{jobId:string;state:"completed";outputText:string}|{jobId:string;state:"failed";reason:JobFailureReason}|{jobId:string;state:"cancelled"};
export type CodexJobCancellation=CodexJobStatus|{jobId:string;state:"cancellation_pending"};
type RecordState="queued"|"running"|"cancelling"|"completed"|"failed"|"cancelled";
export type CodexJobOperationalSummary={jobId:string;idempotencyDigest:string;environmentKey:string;state:RecordState;reason?:JobFailureReason;createdAt:string;updatedAt:string};
export type CodexJobOperationalList={capacity:{maxActive:1;activeJobId:string|null};jobs:CodexJobOperationalSummary[]};
type JobRecord={schemaVersion:1;revision:number;jobId:string;idempotencyDigest:string;fingerprint:string;environmentKey:string;state:RecordState;outputText?:string;reason?:JobFailureReason;threadId?:string;turnId?:string;createdAt:string;updatedAt:string};
type RuntimeControl={interruptIntent:boolean;interruptSent:boolean;forcedTerminal:boolean;terminalPending?:boolean;escalationTimer?:NodeJS.Timeout;startedWrite?:Promise<void>;persistenceError?:unknown};
type PersistenceHook=(snapshot:Readonly<JobRecord>)=>Promise<void>;
const JOB_ID=/^[a-f0-9]{48}$/,DIGEST=/^[a-f0-9]{64}$/;
const digest=(value:string)=>createHash("sha256").update(value,"utf8").digest("hex");
const fingerprint=(input:CodexJobStartInput)=>digest(JSON.stringify({environmentKey:input.environmentKey,prompt:input.prompt,model:input.model??null,reasoningEffort:input.reasoningEffort??null}));
export const idempotencyDigest=digest;
export class PersistentCodexJobRunner{
 private readonly app:AppServerClient;private readonly environments:RunnerEnvironment[];private readonly stateDirectory:string;private readonly durationMs:number;private readonly cleanupMs:number;private readonly persistenceHook?:PersistenceHook;private readonly environmentsConfigured:boolean;private readonly boundedExecutionPlane:boolean;private readonly hardStop?:()=>Promise<void>;
 private records=new Map<string,JobRecord>();private byDigest=new Map<string,string>();private writes=new Map<string,Promise<void>>();private controls=new Map<string,RuntimeControl>();private activeJob?:string;private admission=Promise.resolve();private storageHealthy=true;
 private constructor(app:AppServerClient,environments:RunnerEnvironment[],stateDirectory:string,durationMs:number,cleanupMs:number,persistenceHook:PersistenceHook|undefined,environmentsConfigured:boolean,boundedExecutionPlane:boolean,hardStop?:()=>Promise<void>){this.app=app;this.environments=environments;this.stateDirectory=stateDirectory;this.durationMs=durationMs;this.cleanupMs=cleanupMs;this.persistenceHook=persistenceHook;this.environmentsConfigured=environmentsConfigured;this.boundedExecutionPlane=boundedExecutionPlane;this.hardStop=hardStop}
 static async create(app:AppServerClient,environments:RunnerEnvironment[],stateDirectory:string,durationMs=7_000_000,cleanupMs=30_000,persistenceHook?:PersistenceHook,environmentsConfigured=true,boundedExecutionPlane=false,hardStop?:()=>Promise<void>){const value=new PersistentCodexJobRunner(app,environments,stateDirectory,durationMs,cleanupMs,persistenceHook,environmentsConfigured,boundedExecutionPlane,hardStop);await ensureStateDirectory(stateDirectory);await value.load();return value}
 private path(id:string){return join(this.stateDirectory,`${id}.json`)}
 private persist(record:JobRecord){record.revision++;record.updatedAt=new Date().toISOString();const immutable={...record},snapshot=JSON.stringify(immutable),previous=this.writes.get(record.jobId)??Promise.resolve();const write=previous.then(async()=>{await this.persistenceHook?.(immutable);const path=this.path(record.jobId),temp=`${path}.${immutable.revision}.${randomBytes(8).toString("hex")}.tmp`;if(Buffer.byteLength(snapshot)>300_000)throw new Error("job_state_too_large");await writeFile(temp,snapshot,{mode:0o600,flag:"wx"});await rename(temp,path)});this.writes.set(record.jobId,write);return write}
 private parsePersisted(raw:string,file:string):JobRecord{if(Buffer.byteLength(raw)>300_000)throw new Error("job_state_untrusted");let value:unknown;try{value=JSON.parse(raw)}catch{throw new Error("job_state_untrusted")}if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("job_state_untrusted");const v=value as Record<string,unknown>,allowed=new Set(["schemaVersion","revision","jobId","idempotencyDigest","fingerprint","environmentKey","state","outputText","reason","threadId","turnId","createdAt","updatedAt"]),states=new Set<RecordState>(["queued","running","cancelling","completed","failed","cancelled"]),reasons=new Set<JobFailureReason>(["authentication_failed","runner_restarted","thread_start_failed","turn_start_failed","turn_failed","interaction_required","output_too_large","timeout","internal_error"]);if(Object.keys(v).some(key=>!allowed.has(key))||v.schemaVersion!==1||!Number.isSafeInteger(v.revision)||(v.revision as number)<0||typeof v.jobId!=="string"||`${v.jobId}.json`!==file||!JOB_ID.test(v.jobId)||typeof v.idempotencyDigest!=="string"||!DIGEST.test(v.idempotencyDigest)||typeof v.fingerprint!=="string"||!DIGEST.test(v.fingerprint)||typeof v.environmentKey!=="string"||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v.environmentKey)||v.environmentKey.length>80||typeof v.state!=="string"||!states.has(v.state as RecordState)||typeof v.createdAt!=="string"||!Number.isFinite(Date.parse(v.createdAt))||typeof v.updatedAt!=="string"||!Number.isFinite(Date.parse(v.updatedAt)))throw new Error("job_state_untrusted");if((v.threadId!==undefined&&(typeof v.threadId!=="string"||v.threadId.length<1||v.threadId.length>256))||(v.turnId!==undefined&&(typeof v.turnId!=="string"||v.turnId.length<1||v.turnId.length>256)))throw new Error("job_state_untrusted");if(v.state==="completed"?(typeof v.outputText!=="string"||Buffer.byteLength(v.outputText)>262_144||v.reason!==undefined):(v.outputText!==undefined))throw new Error("job_state_untrusted");if(v.state==="failed"?(typeof v.reason!=="string"||!reasons.has(v.reason as JobFailureReason)):(v.reason!==undefined))throw new Error("job_state_untrusted");return v as JobRecord}
 private async load(){const resume:JobRecord[]=[];for(const file of await readdir(this.stateDirectory)){if(!/^[a-f0-9]{48}\.json$/.test(file))continue;const value=this.parsePersisted(await readFile(join(this.stateDirectory,file),"utf8"),file);if(this.records.has(value.jobId)||this.byDigest.has(value.idempotencyDigest))throw new Error("job_state_untrusted");if(["queued","running","cancelling"].includes(value.state)){if(this.boundedExecutionPlane&&((value.threadId&&value.turnId&&this.app.observeWorkflowTurn)||this.app.reconcileUnknownExecution)){if(this.activeJob)throw new Error("job_state_untrusted");this.activeJob=value.jobId;this.controls.set(value.jobId,{interruptIntent:value.state==="cancelling",interruptSent:false,forcedTerminal:false});resume.push(value)}else{value.state="failed";value.reason="runner_restarted";delete value.threadId;delete value.turnId;await this.persist(value)}}this.records.set(value.jobId,value);this.byDigest.set(value.idempotencyDigest,value.jobId)}for(const value of resume)void this.resumePersisted(value)}
 private async resumePersisted(record:JobRecord){const control=this.controls.get(record.jobId)!;try{if(record.state==="cancelling")await this.requestInterrupt(record,control).catch(()=>{});const result=record.threadId&&record.turnId&&this.app.observeWorkflowTurn?await this.app.observeWorkflowTurn(record.threadId,record.turnId):await this.app.reconcileUnknownExecution!();if(record.state==="cancelling")record.state="cancelled";else if(result.ok){record.state="completed";record.outputText=result.outputText}else{record.state="failed";record.reason=result.reason}await this.persistTerminal(record)}catch{record.state="failed";record.reason="internal_error";await this.persistTerminal(record)}finally{if(this.storageHealthy&&this.activeJob===record.jobId)this.activeJob=undefined}}
 private public(value:JobRecord):CodexJobStatus{if(this.controls.get(value.jobId)?.terminalPending)return{jobId:value.jobId,state:"running"};if(value.state==="completed")return{jobId:value.jobId,state:"completed",outputText:value.outputText??""};if(value.state==="failed")return{jobId:value.jobId,state:"failed",reason:value.reason??"internal_error"};if(value.state==="cancelled")return{jobId:value.jobId,state:"cancelled"};return{jobId:value.jobId,state:value.state==="queued"?"queued":"running"}}
 private exclusive<T>(operation:()=>Promise<T>):Promise<T>{const result=this.admission.then(operation,operation);this.admission=result.then(()=>{},()=>{});return result}
 lookup(token:string){if(!DIGEST.test(token))throw new SafeError("invalid_request",400);const id=this.byDigest.get(token);return id?this.public(this.records.get(id)!):undefined}
 list(limit:number):CodexJobOperationalList{const jobs=[...this.records.values()].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)||b.createdAt.localeCompare(a.createdAt)||b.jobId.localeCompare(a.jobId)).slice(0,limit).map(record=>{const pending=this.controls.get(record.jobId)?.terminalPending,state=pending?"running":record.state;return{jobId:record.jobId,idempotencyDigest:record.idempotencyDigest,environmentKey:record.environmentKey,state,...(state==="failed"?{reason:record.reason??"internal_error"}:{}),createdAt:record.createdAt,updatedAt:record.updatedAt}});return{capacity:{maxActive:1,activeJobId:this.activeJob??null},jobs}}
 get(jobId:string){if(!JOB_ID.test(jobId)||!this.records.has(jobId))throw new SafeError("not_found",404);return this.public(this.records.get(jobId)!)}
 start(input:CodexJobStartInput){return this.exclusive(()=>this.admit(input))}
 private async admit(input:CodexJobStartInput){
  if(!this.storageHealthy)throw new SafeError("workflow_storage_unavailable",503);const idem=digest(input.idempotencyKey),requestFingerprint=fingerprint(input),existingId=this.byDigest.get(idem);if(existingId){const existing=this.records.get(existingId)!;if(existing.fingerprint!==requestFingerprint)throw new SafeError("idempotency_conflict",409);return this.public(existing)}if(!this.environmentsConfigured)throw new SafeError("configuration_unavailable",503);const environment=this.environments.find(item=>item.key===input.environmentKey);if(!environment)throw new SafeError("unknown_environment",400);if(!environment.enabled)throw new SafeError("environment_disabled",409);if(!environment.ready)throw new SafeError("environment_not_ready",409);if(this.activeJob)throw new SafeError("runner_busy",409);
  const now=new Date().toISOString(),record:JobRecord={schemaVersion:1,revision:0,jobId:randomBytes(24).toString("hex"),idempotencyDigest:idem,fingerprint:requestFingerprint,environmentKey:input.environmentKey,state:"queued",createdAt:now,updatedAt:now},control:RuntimeControl={interruptIntent:false,interruptSent:false,forcedTerminal:false};this.activeJob=record.jobId;this.records.set(record.jobId,record);this.byDigest.set(idem,record.jobId);this.controls.set(record.jobId,control);
  try{await this.persist(record)}catch(error){this.activeJob=undefined;this.records.delete(record.jobId);this.byDigest.delete(idem);this.controls.delete(record.jobId);throw error}
  this.execute(record,control,environment,input).catch(()=>{this.storageHealthy=false});return this.public(record)
 }
 private cancellationRequested(record:JobRecord){return record.state==="cancelling"}
 private async requestInterrupt(record:JobRecord,control:RuntimeControl){control.interruptIntent=true;if(control.interruptSent||!record.threadId||!record.turnId)return;control.interruptSent=true;await this.app.interruptWorkflowTurn?.(record.threadId,record.turnId)}
 private async persistTerminal(record:JobRecord){const control=this.controls.get(record.jobId);if(control)control.terminalPending=true;try{await this.persist(record);return true}catch{this.storageHealthy=false;record.state="failed";record.reason="internal_error";return false}finally{if(control)control.terminalPending=false}}
 private validationReason(error:unknown):JobFailureReason{return error instanceof SafeError&&error.code==="authentication_failed"?"authentication_failed":"internal_error"}
 private async execute(record:JobRecord,control:RuntimeControl,environment:RunnerEnvironment,input:CodexJobStartInput){let timer:NodeJS.Timeout|undefined;try{
   if(this.cancellationRequested(record)){record.state="cancelled";await this.persistTerminal(record);return}
   let threadModel:string|undefined;try{const status=await this.app.status() as {account?:unknown};if(!status?.account)throw new SafeError("authentication_failed",401);if(!this.app.listModels||!this.app.runWorkflowTurn)throw new SafeError("configuration_unavailable",503);const models=await this.app.listModels(),selected=input.model?models.find(item=>item.id===input.model):models.find(item=>item.isDefault);if(input.model&&!selected)throw new SafeError("unknown_model",400);if(input.reasoningEffort&&(!selected||!selected.supportedReasoningEfforts.some(item=>item.reasoningEffort===input.reasoningEffort)))throw new SafeError("unsupported_reasoning_effort",400);threadModel=input.model?selected?.threadModel:undefined}catch(error){record.state="failed";record.reason=this.validationReason(error);await this.persistTerminal(record);return}
   if(this.cancellationRequested(record)){record.state="cancelled";await this.persistTerminal(record);return}
   record.state="running";try{await this.persist(record)}catch{this.storageHealthy=false;record.state="failed";record.reason="internal_error";return}
   if(this.cancellationRequested(record)){record.state="cancelled";await this.persistTerminal(record);return}
   const execution=this.app.runWorkflowTurn!({cwd:environment.cwd,sandbox:environment.sandbox,prompt:input.prompt,...(threadModel?{model:threadModel}:{}),...(input.reasoningEffort?{reasoningEffort:input.reasoningEffort}:{}),onStarted:(threadId,turnId)=>{record.threadId=threadId;record.turnId=turnId;control.startedWrite=this.persist(record).catch(error=>{control.persistenceError=error;this.storageHealthy=false;return this.requestInterrupt(record,control).catch(()=>{})});if(control.interruptIntent||this.cancellationRequested(record))void this.requestInterrupt(record,control).catch(()=>{})}});
   const timeout=new Promise<"timeout">(resolve=>{timer=setTimeout(()=>resolve("timeout"),this.durationMs);timer.unref()}),first=await Promise.race([execution,timeout]);
   if(first==="timeout"){record.state="failed";record.reason="timeout";await this.persistTerminal(record);await this.requestInterrupt(record,control);let cleanupTimer:NodeJS.Timeout|undefined;const cleanup=new Promise<false>(resolve=>{cleanupTimer=setTimeout(()=>resolve(false),this.cleanupMs);cleanupTimer.unref()}),quiesced=await Promise.race([execution.then(()=>true,()=>true),cleanup]);if(cleanupTimer)clearTimeout(cleanupTimer);if(!quiesced){if(this.boundedExecutionPlane){control.forcedTerminal=true;await this.hardStop?.().catch(()=>{});await execution.catch(()=>undefined)}else{this.storageHealthy=false;await execution.catch(()=>undefined)}}return}
   const result=first as WorkflowTurnResult;await control.startedWrite;if(control.persistenceError){record.state="failed";record.reason="internal_error";return}if(control.forcedTerminal)return;if(this.cancellationRequested(record)){record.state="cancelled"}else if(result.ok){record.state="completed";record.outputText=result.outputText}else{record.state="failed";record.reason=result.reason}await this.persistTerminal(record)
  }catch{record.state="failed";record.reason="internal_error";await this.requestInterrupt(record,control).catch(()=>{});await this.persistTerminal(record)}finally{if(timer)clearTimeout(timer);if(control.escalationTimer)clearTimeout(control.escalationTimer);if(this.activeJob===record.jobId)this.activeJob=undefined}}
 async reconcileActive(reason:JobFailureReason="runner_restarted"){return this.exclusive(async()=>{const id=this.activeJob;if(!id)return undefined;const record=this.records.get(id)!,control=this.controls.get(id);if(control)control.forcedTerminal=true;record.state="failed";record.reason=reason;delete record.outputText;await this.persistTerminal(record);if(this.storageHealthy&&this.activeJob===id)this.activeJob=undefined;return this.public(record)})}
 async cancel(jobId:string):Promise<CodexJobCancellation>{if(!JOB_ID.test(jobId)||!this.records.has(jobId))throw new SafeError("not_found",404);const record=this.records.get(jobId)!,control=this.controls.get(jobId);if(["completed","failed","cancelled"].includes(record.state))return this.public(record);if(record.state!=="cancelling"){record.state="cancelling";if(!await this.persistTerminal(record))return this.public(record)}if(control){await this.requestInterrupt(record,control);if(this.boundedExecutionPlane&&!control.escalationTimer){control.escalationTimer=setTimeout(()=>{if(this.activeJob!==record.jobId||record.state!=="cancelling")return;void this.hardStop?.().catch(()=>{})},this.cleanupMs);control.escalationTimer.unref()}}return{jobId:record.jobId,state:"cancellation_pending"}}
 async stateFileMode(jobId:string){return(await stat(this.path(jobId))).mode&0o777}
}
