import {createHash,randomBytes} from "node:crypto";
import {readFile,readdir,rename,stat,writeFile} from "node:fs/promises";
import {join} from "node:path";
import type {AppServerClient,WorkflowTurnResult} from "./app-server-client.js";
import type {RunnerEnvironment} from "./environments.js";
import {ensureStateDirectory} from "./environments.js";
import {SafeError} from "./errors.js";

export type JobFailureReason="authentication_failed"|"runner_restarted"|"thread_start_failed"|"turn_start_failed"|"turn_failed"|"interaction_required"|"output_too_large"|"timeout"|"internal_error";
export interface CodexJobStartInput{idempotencyKey:string;environmentKey:string;prompt:string;model?:string;reasoningEffort?:string}
export type CodexJobStatus={jobId:string;state:"queued"|"running"}|{jobId:string;state:"completed";outputText:string}|{jobId:string;state:"failed";reason:JobFailureReason}|{jobId:string;state:"cancelled"};
type RecordState="queued"|"running"|"cancelling"|"completed"|"failed"|"cancelled";
type JobRecord={schemaVersion:1;revision:number;jobId:string;idempotencyDigest:string;fingerprint:string;environmentKey:string;state:RecordState;outputText?:string;reason?:JobFailureReason;threadId?:string;turnId?:string;createdAt:string;updatedAt:string};
type RuntimeControl={interruptIntent:boolean;interruptSent:boolean;startedWrite?:Promise<void>;persistenceError?:unknown};
type PersistenceHook=(snapshot:Readonly<JobRecord>)=>Promise<void>;
const JOB_ID=/^[a-f0-9]{48}$/,DIGEST=/^[a-f0-9]{64}$/;
const digest=(value:string)=>createHash("sha256").update(value,"utf8").digest("hex");
const fingerprint=(input:CodexJobStartInput)=>digest(JSON.stringify({environmentKey:input.environmentKey,prompt:input.prompt,model:input.model??null,reasoningEffort:input.reasoningEffort??null}));
export const idempotencyDigest=digest;
export class PersistentCodexJobRunner{
 private readonly app:AppServerClient;private readonly environments:RunnerEnvironment[];private readonly stateDirectory:string;private readonly durationMs:number;private readonly cleanupMs:number;private readonly persistenceHook?:PersistenceHook;
 private records=new Map<string,JobRecord>();private byDigest=new Map<string,string>();private writes=new Map<string,Promise<void>>();private controls=new Map<string,RuntimeControl>();private activeJob?:string;private admission=Promise.resolve();private storageHealthy=true;
 private constructor(app:AppServerClient,environments:RunnerEnvironment[],stateDirectory:string,durationMs:number,cleanupMs:number,persistenceHook?:PersistenceHook){this.app=app;this.environments=environments;this.stateDirectory=stateDirectory;this.durationMs=durationMs;this.cleanupMs=cleanupMs;this.persistenceHook=persistenceHook}
 static async create(app:AppServerClient,environments:RunnerEnvironment[],stateDirectory:string,durationMs=7_000_000,cleanupMs=30_000,persistenceHook?:PersistenceHook){const value=new PersistentCodexJobRunner(app,environments,stateDirectory,durationMs,cleanupMs,persistenceHook);await ensureStateDirectory(stateDirectory);await value.load();return value}
 private path(id:string){return join(this.stateDirectory,`${id}.json`)}
 private persist(record:JobRecord){record.revision++;record.updatedAt=new Date().toISOString();const immutable={...record},snapshot=JSON.stringify(immutable),previous=this.writes.get(record.jobId)??Promise.resolve();const write=previous.then(async()=>{await this.persistenceHook?.(immutable);const path=this.path(record.jobId),temp=`${path}.${immutable.revision}.${randomBytes(8).toString("hex")}.tmp`;if(Buffer.byteLength(snapshot)>300_000)throw new Error("job_state_too_large");await writeFile(temp,snapshot,{mode:0o600,flag:"wx"});await rename(temp,path)});this.writes.set(record.jobId,write);return write}
 private async load(){for(const file of await readdir(this.stateDirectory)){if(!/^[a-f0-9]{48}\.json$/.test(file))continue;try{const raw=await readFile(join(this.stateDirectory,file),"utf8");if(Buffer.byteLength(raw)>300_000)continue;const value=JSON.parse(raw) as JobRecord;if(value.schemaVersion!==1||!Number.isSafeInteger(value.revision)||!JOB_ID.test(value.jobId)||!DIGEST.test(value.idempotencyDigest)||!DIGEST.test(value.fingerprint))continue;if(["queued","running","cancelling"].includes(value.state)){value.state="failed";value.reason="runner_restarted";delete value.threadId;delete value.turnId;await this.persist(value)}this.records.set(value.jobId,value);this.byDigest.set(value.idempotencyDigest,value.jobId)}catch{/* Invalid state is ignored without exposing content. */}}}
 private public(value:JobRecord):CodexJobStatus{if(value.state==="completed")return{jobId:value.jobId,state:"completed",outputText:value.outputText??""};if(value.state==="failed")return{jobId:value.jobId,state:"failed",reason:value.reason??"internal_error"};if(value.state==="cancelled")return{jobId:value.jobId,state:"cancelled"};return{jobId:value.jobId,state:value.state==="queued"?"queued":"running"}}
 private exclusive<T>(operation:()=>Promise<T>):Promise<T>{const result=this.admission.then(operation,operation);this.admission=result.then(()=>{},()=>{});return result}
 lookup(token:string){if(!DIGEST.test(token))throw new SafeError("invalid_request",400);const id=this.byDigest.get(token);return id?this.public(this.records.get(id)!):undefined}
 get(jobId:string){if(!JOB_ID.test(jobId)||!this.records.has(jobId))throw new SafeError("not_found",404);return this.public(this.records.get(jobId)!)}
 start(input:CodexJobStartInput){return this.exclusive(()=>this.admit(input))}
 private async admit(input:CodexJobStartInput){
  if(!this.storageHealthy)throw new SafeError("workflow_storage_unavailable",503);const environment=this.environments.find(item=>item.key===input.environmentKey);if(!environment)throw new SafeError("unknown_environment",400);if(!environment.enabled)throw new SafeError("environment_disabled",409);if(!environment.ready)throw new SafeError("environment_not_ready",409);
  const idem=digest(input.idempotencyKey),requestFingerprint=fingerprint(input),existingId=this.byDigest.get(idem);if(existingId){const existing=this.records.get(existingId)!;if(existing.fingerprint!==requestFingerprint)throw new SafeError("idempotency_conflict",409);return this.public(existing)}if(this.activeJob)throw new SafeError("runner_busy",409);
  const now=new Date().toISOString(),record:JobRecord={schemaVersion:1,revision:0,jobId:randomBytes(24).toString("hex"),idempotencyDigest:idem,fingerprint:requestFingerprint,environmentKey:input.environmentKey,state:"queued",createdAt:now,updatedAt:now},control:RuntimeControl={interruptIntent:false,interruptSent:false};this.activeJob=record.jobId;this.records.set(record.jobId,record);this.byDigest.set(idem,record.jobId);this.controls.set(record.jobId,control);
  try{await this.persist(record)}catch(error){this.activeJob=undefined;this.records.delete(record.jobId);this.byDigest.delete(idem);this.controls.delete(record.jobId);throw error}
  this.execute(record,control,environment,input).catch(()=>{this.storageHealthy=false});return this.public(record)
 }
 private cancellationRequested(record:JobRecord){return record.state==="cancelling"}
 private async requestInterrupt(record:JobRecord,control:RuntimeControl){control.interruptIntent=true;if(control.interruptSent||!record.threadId||!record.turnId)return;control.interruptSent=true;await this.app.interruptWorkflowTurn?.(record.threadId,record.turnId)}
 private async persistTerminal(record:JobRecord){try{await this.persist(record);return true}catch{this.storageHealthy=false;record.state="failed";record.reason="internal_error";return false}}
 private validationReason(error:unknown):JobFailureReason{return error instanceof SafeError&&error.code==="authentication_failed"?"authentication_failed":"internal_error"}
 private async execute(record:JobRecord,control:RuntimeControl,environment:RunnerEnvironment,input:CodexJobStartInput){let timer:NodeJS.Timeout|undefined;try{
   if(this.cancellationRequested(record)){record.state="cancelled";await this.persistTerminal(record);return}
   let threadModel:string|undefined;try{const status=await this.app.status() as {account?:unknown};if(!status?.account)throw new SafeError("authentication_failed",401);if(!this.app.listModels||!this.app.runWorkflowTurn)throw new SafeError("configuration_unavailable",503);const models=await this.app.listModels(),selected=input.model?models.find(item=>item.id===input.model):models.find(item=>item.isDefault);if(input.model&&!selected)throw new SafeError("unknown_model",400);if(input.reasoningEffort&&(!selected||!selected.supportedReasoningEfforts.some(item=>item.reasoningEffort===input.reasoningEffort)))throw new SafeError("unsupported_reasoning_effort",400);threadModel=input.model?selected?.threadModel:undefined}catch(error){record.state="failed";record.reason=this.validationReason(error);await this.persistTerminal(record);return}
   if(this.cancellationRequested(record)){record.state="cancelled";await this.persistTerminal(record);return}
   record.state="running";try{await this.persist(record)}catch{this.storageHealthy=false;record.state="failed";record.reason="internal_error";return}
   if(this.cancellationRequested(record)){record.state="cancelled";await this.persistTerminal(record);return}
   const execution=this.app.runWorkflowTurn!({cwd:environment.cwd,sandbox:environment.sandbox,prompt:input.prompt,...(threadModel?{model:threadModel}:{}),...(input.reasoningEffort?{reasoningEffort:input.reasoningEffort}:{}),onStarted:(threadId,turnId)=>{record.threadId=threadId;record.turnId=turnId;control.startedWrite=this.persist(record).catch(error=>{control.persistenceError=error;this.storageHealthy=false;return this.requestInterrupt(record,control).catch(()=>{})});if(control.interruptIntent||this.cancellationRequested(record))void this.requestInterrupt(record,control).catch(()=>{})}});
   const timeout=new Promise<"timeout">(resolve=>{timer=setTimeout(()=>resolve("timeout"),this.durationMs);timer.unref()}),first=await Promise.race([execution,timeout]);
   if(first==="timeout"){record.state="failed";record.reason="timeout";await this.persistTerminal(record);await this.requestInterrupt(record,control);let cleanupTimer:NodeJS.Timeout|undefined;const cleanup=new Promise<false>(resolve=>{cleanupTimer=setTimeout(()=>resolve(false),this.cleanupMs);cleanupTimer.unref()}),quiesced=await Promise.race([execution.then(()=>true,()=>true),cleanup]);if(cleanupTimer)clearTimeout(cleanupTimer);if(!quiesced){this.storageHealthy=false;await execution.catch(()=>undefined)}return}
   const result=first as WorkflowTurnResult;await control.startedWrite;if(control.persistenceError){record.state="failed";record.reason="internal_error";return}if(this.cancellationRequested(record)){record.state="cancelled"}else if(result.ok){record.state="completed";record.outputText=result.outputText}else{record.state="failed";record.reason=result.reason}await this.persistTerminal(record)
  }catch{this.storageHealthy=false;record.state="failed";record.reason="internal_error";await this.requestInterrupt(record,control).catch(()=>{})}finally{if(timer)clearTimeout(timer);if(this.activeJob===record.jobId)this.activeJob=undefined}}
 async cancel(jobId:string){if(!JOB_ID.test(jobId)||!this.records.has(jobId))throw new SafeError("not_found",404);const record=this.records.get(jobId)!,control=this.controls.get(jobId);if(["completed","failed","cancelled"].includes(record.state))return this.public(record);if(record.state!=="cancelling"){record.state="cancelling";if(!await this.persistTerminal(record))return this.public(record)}if(control)await this.requestInterrupt(record,control);return this.public(record)}
 async stateFileMode(jobId:string){return(await stat(this.path(jobId))).mode&0o777}
}
