import {createServer,type IncomingMessage,type ServerResponse} from "node:http";
import {execFile} from "node:child_process";
import {createHash,createPublicKey,verify,type KeyObject} from "node:crypto";
import {access,chmod,lstat,mkdir,readFile,readdir,realpath,rename,rm,stat,writeFile} from "node:fs/promises";
import {constants} from "node:fs";
import {dirname,isAbsolute,join,relative,resolve,sep} from "node:path";
import {SafeError,safeError} from "./errors.js";
import {executorRequestHeaders} from "./executor.js";
import {loadRunnerEnvironments,type ManagedRepositoryConfiguration,type RunnerEnvironment} from "./environments.js";
import type {RunnerConfiguration} from "./configuration.js";

const SHA=/^[a-f0-9]{40}$/,TASK=/^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/,BRANCH=/^adt\/codex\/[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/,MAX_BODY=16_384,MAX_OUTPUT=64*1024,GIT_TIMEOUT=120_000;
const canonical=(method:string,path:string,timestamp:string,nonce:string,body:Buffer)=>Buffer.from(`adt-executor-v1\n${method}\n${path}\n${timestamp}\n${nonce}\n${createHash("sha256").update(body).digest("hex")}`);
const json=(res:ServerResponse,status:number,value:unknown)=>{res.writeHead(status,{"content-type":"application/json","cache-control":"no-store","x-content-type-options":"nosniff"});res.end(JSON.stringify(value))};
const exact=(value:unknown,keys:string[])=>{if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value).some(k=>!keys.includes(k))||keys.some(k=>!Object.hasOwn(value,k)))throw new SafeError("invalid_request",400);return value as Record<string,unknown>};
const taskId=(value:unknown)=>{if(typeof value!=="string"||!TASK.test(value))throw new SafeError("invalid_request",400);return value};
const token=(value:unknown)=>{if(typeof value!=="string"||value.length<1||value.length>2048||/[\r\n\0]/.test(value))throw new SafeError("invalid_request",400);return value};

export type ManagedTaskMetadata={schemaVersion:2;environmentKey:string;repository:{owner:string;repo:string};taskId:string;baseBranch:string;baseSha:string;branch:string;worktreeAvailable:boolean;state:"prepared"|"sealed"|"push-uncertain"|"published";sealedCommitSha?:string;sealedChanged?:boolean;pushedCommitSha?:string;dirty?:boolean};
type GitResult={stdout:string};
type ExecGit=(cwd:string,args:string[],credential?:string,trustedLocalMirror?:boolean)=>Promise<GitResult>;
export type GitPushFailureClass="timeout"|"authorization"|"network"|"remote_rejected"|"unknown";
export type GitPushFailure={failureClass:GitPushFailureClass;upstreamHttpStatus?:number};

class GitCommandError extends SafeError{constructor(code:string,status:number,public readonly failure:GitPushFailure){super(code,status,failure.upstreamHttpStatus?{upstreamHttpStatus:failure.upstreamHttpStatus}:{})}}

export function classifyGitPushFailure(error:unknown,stderr?:unknown):GitPushFailure{
 const value=error as NodeJS.ErrnoException&{killed?:boolean;signal?:string;failure?:GitPushFailure;stderr?:unknown};
 if(value?.failure)return value.failure;
 if(value?.killed||value?.signal==="SIGTERM"||value?.signal==="SIGKILL"||value?.code==="ETIMEDOUT"||(error instanceof SafeError&&error.code==="repository_operation_timeout"))return{failureClass:"timeout"};
 const text=typeof stderr==="string"?stderr.slice(0,MAX_OUTPUT):typeof value?.stderr==="string"?value.stderr.slice(0,MAX_OUTPUT):"";
 const http=/(?:requested URL returned error:|HTTP(?:\/\d(?:\.\d)?)?)\s*(401|403)\b/i.exec(text);
 if(http||/(?:authentication failed|write access(?: to repository)? not granted|permission to [^\r\n]{1,256} denied|could not read Username)/i.test(text))return{failureClass:"authorization",...(http?{upstreamHttpStatus:Number(http[1])}:{})};
 if(/(?:could not resolve (?:host|proxy)|failed to connect|connection (?:refused|reset)|SSL certificate problem|TLS connection|proxy CONNECT|network is unreachable)/i.test(text))return{failureClass:"network"};
 if(/(?:non-fast-forward|\[remote rejected\]|remote rejected|failed to push some refs)/i.test(text))return{failureClass:"remote_rejected"};
 return{failureClass:"unknown"};
}

function safeGitError(error:unknown,stderr:unknown){const failure=classifyGitPushFailure(error,stderr);return new GitCommandError(failure.failureClass==="timeout"?"repository_operation_timeout":"repository_operation_failed",failure.failureClass==="timeout"?503:409,failure)}

export class ManagedRepositoryService{
 private environments:RunnerEnvironment[];private workspaceRoot:string;private stateRoot:string;private runGit:ExecGit;private remote:(r:ManagedRepositoryConfiguration)=>string;private prepareBoundary?:(name:string)=>void;private operations=Promise.resolve();
 constructor(environments:RunnerEnvironment[],workspaceRoot:string,options:{stateRoot?:string;execGit?:ExecGit;remote?:(r:ManagedRepositoryConfiguration)=>string;prepareBoundary?:(name:string)=>void}={}){this.environments=environments;this.workspaceRoot=workspaceRoot;this.stateRoot=options.stateRoot??"/data/repositories";this.remote=options.remote??(r=>`https://github.com/${encodeURIComponent(r.owner)}/${encodeURIComponent(r.repo)}.git`);this.prepareBoundary=options.prepareBoundary;this.runGit=options.execGit??this.git.bind(this)}
 private serialize<T>(operation:()=>Promise<T>){const result=this.operations.then(operation,operation);this.operations=result.then(()=>{},()=>{});return result}
 private environment(key:unknown):RunnerEnvironment&{repository:ManagedRepositoryConfiguration}{if(typeof key!=="string"||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(key))throw new SafeError("invalid_request",400);const environment=this.environments.find(v=>v.key===key);if(!environment?.enabled||!environment.repository)throw new SafeError("managed_environment_unavailable",409);return environment as RunnerEnvironment&{repository:ManagedRepositoryConfiguration}}
 private async contained(path:string,rootPath:string,allowMissing=false){const root=await realpath(rootPath);let candidate:string;try{candidate=await realpath(path)}catch{if(!allowMissing)throw new SafeError("repository_state_invalid",409);const parent=await realpath(dirname(path));candidate=join(parent,path.slice(dirname(path).length+1))}const rel=relative(root,candidate);if(rel===""||(!isAbsolute(rel)&&rel!==".."&&!rel.startsWith(`..${sep}`)))return candidate;throw new SafeError("workspace_outside_root",400)}
 private paths(environment:RunnerEnvironment,id:string){const control=join(this.stateRoot,environment.key),task=join(control,"tasks",id),staging=join(control,"tasks",`.preparing-${id}`);return{workspaceRoot:environment.cwd,worktree:join(environment.cwd,"tasks",id),control,mirror:join(control,"mirror.git"),tasks:join(control,"tasks"),task,gitDir:join(task,"git"),record:join(task,"record.json"),staging,stagingGitDir:join(staging,"git"),stagingRecord:join(staging,"record.json")}}
 private async provisionManagedRoot(environment:RunnerEnvironment){
  if(environment.cwd.split(sep).some(part=>part===".."||part==="."))throw new SafeError("workspace_outside_root",400);
  const workspaceRoot=await realpath(this.workspaceRoot),candidate=resolve(environment.cwd),rel=relative(workspaceRoot,candidate);
  if(rel===""||isAbsolute(rel)||rel===".."||rel.startsWith(`..${sep}`))throw new SafeError("workspace_outside_root",400);
  let current=workspaceRoot;
  for(const part of rel.split(sep)){
   current=join(current,part);
   try{const info=await lstat(current);if(info.isSymbolicLink()||!info.isDirectory())throw new SafeError("repository_state_invalid",409)}catch(error){if(error instanceof SafeError)throw error;if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;await mkdir(current,{mode:0o700});const info=await lstat(current);if(info.isSymbolicLink()||!info.isDirectory())throw new SafeError("repository_state_invalid",409)}
  }
  await this.contained(environment.cwd,this.workspaceRoot);
  const entries=await readdir(environment.cwd);if(entries.some(v=>v!=="tasks"))throw new SafeError("managed_root_not_empty",409);
  const tasks=join(environment.cwd,"tasks");
  if(entries.includes("tasks")){const info=await lstat(tasks);if(!info.isDirectory()||info.isSymbolicLink())throw new SafeError("repository_state_invalid",409)}else await mkdir(tasks,{mode:0o700});
  await chmod(environment.cwd,0o700);await chmod(tasks,0o700);
 }
 async initialize(){return this.serialize(async()=>{await mkdir(this.stateRoot,{recursive:true,mode:0o700});await access(this.stateRoot,constants.R_OK|constants.W_OK|constants.X_OK);for(const environment of this.environments)if(environment.enabled&&environment.repository)await this.provisionManagedRoot(environment)})}
 private async validateRoots(environment:RunnerEnvironment){await this.contained(environment.cwd,this.workspaceRoot);await this.contained(join(this.stateRoot,environment.key),this.stateRoot,true);const entries=await readdir(environment.cwd);if(entries.some(v=>v!=="tasks"))throw new SafeError("managed_root_not_empty",409);if(entries.includes("tasks")){const info=await lstat(join(environment.cwd,"tasks"));if(!info.isDirectory()||info.isSymbolicLink())throw new SafeError("repository_state_invalid",409)}await access(environment.cwd,constants.R_OK|constants.W_OK|constants.X_OK);await access(this.stateRoot,constants.R_OK|constants.W_OK|constants.X_OK)}
 private async askpass(){const path="/tmp/adt-git-askpass.sh";try{await access(path,constants.X_OK)}catch{await writeFile(path,"#!/bin/sh\ncase \"$1\" in *Username*) printf '%s\\n' x-access-token;; *) printf '%s\\n' \"$ADT_GIT_TOKEN\";; esac\n",{mode:0o700,flag:"wx"}).catch(()=>{});await chmod(path,0o700)}return path}
 private async git(cwd:string,args:string[],credential?:string,trustedLocalMirror=false):Promise<GitResult>{const askpass=credential?await this.askpass():undefined;const safeArgs=["-c","core.hooksPath=/dev/null","-c","credential.helper=","-c","include.path=/dev/null","-c",`protocol.file.allow=${trustedLocalMirror?"always":"never"}`,"-c","protocol.ext.allow=never",...args],proxy:Record<string,string>={};for(const name of ["HTTP_PROXY","HTTPS_PROXY","ALL_PROXY"]){const value=process.env[name];if(value)try{const url=new URL(value);if(url.protocol==="http:"&&!url.username&&!url.password)proxy[name]=value}catch{}}if(process.env.NO_PROXY&&process.env.NO_PROXY.length<=2048)proxy.NO_PROXY=process.env.NO_PROXY;const env={PATH:process.env.PATH??"/usr/bin:/bin",HOME:"/nonexistent",LANG:"C",LC_ALL:"C",GIT_CONFIG_NOSYSTEM:"1",GIT_TERMINAL_PROMPT:"0",...proxy,...(credential?{GIT_ASKPASS:askpass!,GIT_ASKPASS_REQUIRE:"force",ADT_GIT_TOKEN:credential}:{})} as unknown as NodeJS.ProcessEnv;return new Promise((resolve,reject)=>execFile("git",safeArgs,{cwd,timeout:GIT_TIMEOUT,maxBuffer:MAX_OUTPUT,encoding:"utf8",env},(error:Error|null,stdout:string|Buffer,stderr:string|Buffer)=>error?reject(safeGitError(error,String(stderr))):resolve({stdout:String(stdout).slice(0,MAX_OUTPUT)})))}
 private gitArgs(paths:ReturnType<ManagedRepositoryService["paths"]>,...args:string[]){return[`--git-dir=${paths.gitDir}`,`--work-tree=${paths.worktree}`,...args]}
 private async readRecord(path:string):Promise<ManagedTaskMetadata|undefined>{try{const raw=await readFile(path,"utf8");if(Buffer.byteLength(raw)>8192)throw new Error();const v=JSON.parse(raw) as ManagedTaskMetadata;if(!v||v.schemaVersion!==2||!TASK.test(v.taskId)||!BRANCH.test(v.branch)||!SHA.test(v.baseSha)||!["prepared","sealed","push-uncertain","published"].includes(v.state)||(v.sealedCommitSha!==undefined&&!SHA.test(v.sealedCommitSha))||(v.sealedChanged!==undefined&&typeof v.sealedChanged!=="boolean")||(v.pushedCommitSha!==undefined&&!SHA.test(v.pushedCommitSha)))throw new Error();return v}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw new SafeError("repository_state_invalid",409)}}
 private async persist(paths:ReturnType<ManagedRepositoryService["paths"]>,record:ManagedTaskMetadata){const temp=join(paths.task,`.record-${process.pid}-${Date.now()}`);await writeFile(temp,JSON.stringify(record),{mode:0o600,flag:"wx"});await import("node:fs/promises").then(fs=>fs.rename(temp,paths.record))}
 private async remoteHead(environment:RunnerEnvironment&{repository:ManagedRepositoryConfiguration},paths:ReturnType<ManagedRepositoryService["paths"]>,branch:string,credential:string){const ref=`refs/adt/remote/${branch.replaceAll("/","-")}`;await this.runGit(paths.control,[`--git-dir=${paths.mirror}`,"fetch","--no-tags",this.remote(environment.repository),`+refs/heads/${branch}:${ref}`],credential);const sha=(await this.runGit(paths.control,[`--git-dir=${paths.mirror}`,"rev-parse","--verify",`${ref}^{commit}`])).stdout.trim();if(!SHA.test(sha))throw new SafeError("repository_state_invalid",409);return sha}
 private async ensureMirror(paths:ReturnType<ManagedRepositoryService["paths"]>){await mkdir(paths.mirror,{recursive:true,mode:0o700});const entries=await readdir(paths.mirror),allowed=new Set(["FETCH_HEAD","HEAD","branches","config","description","hooks","info","objects","refs","shallow","packed-refs"]);if(entries.some(name=>!allowed.has(name)))throw new SafeError("repository_state_invalid",409);this.prepareBoundary?.("mirror-directory");await this.runGit(paths.control,[`--git-dir=${paths.mirror}`,"init","--bare"]);this.prepareBoundary?.("mirror-initialized");const bare=(await this.runGit(paths.control,[`--git-dir=${paths.mirror}`,"rev-parse","--is-bare-repository"])).stdout.trim();if(bare!=="true")throw new SafeError("repository_state_invalid",409)}
 private async seal(environment:RunnerEnvironment,id:string,record:ManagedTaskMetadata){if(!record.worktreeAvailable)return record;const paths=this.paths(environment,id);await this.contained(paths.worktree,this.workspaceRoot);const status=(await this.runGit(paths.worktree,this.gitArgs(paths,"status","--porcelain=v1","--untracked-files=normal"))).stdout;if(status.length>0){await this.runGit(paths.worktree,this.gitArgs(paths,"add","--all"));await this.runGit(paths.worktree,this.gitArgs(paths,"-c","user.name=ADT Codex Runner","-c","user.email=codex-runner@adt.invalid","commit","--no-gpg-sign","-m","ADT: seal managed task"))}const commit=(await this.runGit(paths.task,this.gitArgs(paths,"rev-parse","--verify","HEAD^{commit}"))).stdout.trim();if(!SHA.test(commit))throw new SafeError("repository_state_invalid",409);const sealed={...record,state:"sealed" as const,worktreeAvailable:false,sealedCommitSha:commit,sealedChanged:commit!==record.baseSha,dirty:false};await this.persist(paths,sealed);await rm(paths.worktree,{recursive:true,force:true});return sealed}
 private async sealOthers(environment:RunnerEnvironment,currentId:string){for(const candidate of this.environments){if(!candidate.enabled||!candidate.repository)continue;const root=this.paths(candidate,currentId).tasks;for(const name of await readdir(root).catch(error=>{if((error as NodeJS.ErrnoException).code==="ENOENT")return[];throw error})){if((candidate.key===environment.key&&name===currentId)||name.startsWith(".preparing-")||!TASK.test(name))continue;const paths=this.paths(candidate,name),record=await this.readRecord(paths.record);if(record?.worktreeAvailable)await this.seal(candidate,name,record);else if(record)await rm(paths.worktree,{recursive:true,force:true})}}}
 async prepare(input:{environmentKey:string;taskId:string;credential:string;sourceBranch?:string}){return this.serialize(()=>this.prepareOperation(input))}
 private async prepareOperation(input:{environmentKey:string;taskId:string;credential:string;sourceBranch?:string}):Promise<ManagedTaskMetadata&{cwd:string}>{const environment=this.environment(input.environmentKey),id=taskId(input.taskId),credential=token(input.credential),paths=this.paths(environment,id),expectedBranch=input.sourceBranch??`adt/codex/${id}`;if(input.sourceBranch!==undefined&&!BRANCH.test(input.sourceBranch))throw new SafeError("invalid_request",400);await mkdir(this.stateRoot,{recursive:true,mode:0o700});await this.validateRoots(environment);await mkdir(paths.control,{recursive:true,mode:0o700});await mkdir(paths.tasks,{recursive:true,mode:0o700});await mkdir(join(paths.workspaceRoot,"tasks"),{recursive:true,mode:0o700});await this.contained(paths.worktree,this.workspaceRoot,true);await this.contained(paths.task,this.stateRoot,true);await this.contained(paths.staging,this.stateRoot,true);const existing=await this.readRecord(paths.record);if(existing?.branch!==undefined&&existing.branch!==expectedBranch)throw new SafeError("idempotency_conflict",409);await this.sealOthers(environment,id);if(existing){if(!existing.worktreeAvailable)throw new SafeError("managed_task_sealed",409);await access(paths.worktree,constants.R_OK|constants.W_OK|constants.X_OK);return{...existing,cwd:paths.worktree}}
  // A durable record is the only completed-prepare authority. Anything else is
  // an incomplete staging attempt and is safe to rebuild deterministically.
  await rm(paths.staging,{recursive:true,force:true});await rm(paths.task,{recursive:true,force:true});await rm(paths.worktree,{recursive:true,force:true});
  await this.ensureMirror(paths);const source=input.sourceBranch??environment.repository.baseBranch,baseSha=await this.remoteHead(environment,paths,source,credential),branch=expectedBranch,building={...paths,task:paths.staging,gitDir:paths.stagingGitDir,record:paths.stagingRecord};try{await mkdir(paths.staging,{mode:0o700});this.prepareBoundary?.("task-staged");await mkdir(paths.worktree,{mode:0o700});await mkdir(paths.stagingGitDir,{mode:0o700});await this.runGit(paths.staging,[`--git-dir=${paths.stagingGitDir}`,"init"]);this.prepareBoundary?.("git-initialized");await this.runGit(paths.staging,[`--git-dir=${paths.stagingGitDir}`,"config","core.bare","false"]);await this.runGit(paths.staging,[`--git-dir=${paths.stagingGitDir}`,"config","core.worktree",paths.worktree]);this.prepareBoundary?.("git-configured");await this.runGit(paths.staging,[`--git-dir=${paths.stagingGitDir}`,"fetch","--no-tags",paths.mirror,`${baseSha}:refs/heads/${branch}`],undefined,true);this.prepareBoundary?.("task-fetched");await this.runGit(paths.staging,[`--git-dir=${paths.stagingGitDir}`,"symbolic-ref","HEAD",`refs/heads/${branch}`]);await this.runGit(paths.worktree,this.gitArgs(building,"reset","--hard",branch));this.prepareBoundary?.("worktree-reset");const metadata:ManagedTaskMetadata={schemaVersion:2,environmentKey:environment.key,repository:{owner:environment.repository.owner,repo:environment.repository.repo},taskId:id,baseBranch:environment.repository.baseBranch,baseSha,branch,worktreeAvailable:true,state:"prepared"};this.prepareBoundary?.("before-record");await this.persist(building,metadata);await rename(paths.staging,paths.task);return{...metadata,cwd:paths.worktree}}catch(error){await rm(paths.staging,{recursive:true,force:true});await rm(paths.worktree,{recursive:true,force:true});throw error}}
 async inspect(environmentKey:string,idValue:string){return this.serialize(()=>this.inspectOperation(environmentKey,idValue))}
 private async inspectOperation(environmentKey:string,idValue:string){const environment=this.environment(environmentKey),id=taskId(idValue),paths=this.paths(environment,id),record=await this.readRecord(paths.record);if(!record)return{found:false as const};if(!record.worktreeAvailable)return{found:true as const,...record,dirty:false};const status=(await this.runGit(paths.worktree,this.gitArgs(paths,"status","--porcelain=v1","--untracked-files=normal"))).stdout;return{found:true as const,...record,dirty:status.length>0}}
 private async reconcilePush(environment:RunnerEnvironment&{repository:ManagedRepositoryConfiguration},paths:ReturnType<ManagedRepositoryService["paths"]>,record:ManagedTaskMetadata,commit:string,credential:string){try{return await this.remoteHead(environment,paths,record.branch,credential)===commit}catch{return false}}
 async publish(input:{environmentKey:string;taskId:string;credential:string;message:string}){return this.serialize(()=>this.publishOperation(input))}
 private async publishOperation(input:{environmentKey:string;taskId:string;credential:string;message:string}){const environment=this.environment(input.environmentKey),id=taskId(input.taskId),credential=token(input.credential);if(typeof input.message!=="string"||!input.message.trim()||input.message.length>200||/[\r\n\0]/.test(input.message))throw new SafeError("invalid_request",400);const paths=this.paths(environment,id),record=await this.readRecord(paths.record);if(!record)throw new SafeError("managed_task_not_found",404);await this.contained(paths.task,this.stateRoot);if(!record.worktreeAvailable)await rm(paths.worktree,{recursive:true,force:true});if(record.state==="push-uncertain"&&record.pushedCommitSha){if(!await this.reconcilePush(environment,paths,record,record.pushedCommitSha,credential))throw new SafeError("repository_publish_result_unknown",503);const reconciled={...record,state:"published" as const};await this.persist(paths,reconciled);return{...reconciled,changed:true as const,commitSha:record.pushedCommitSha,reconciled:true}}
  const sealed=record.state==="prepared"?await this.seal(environment,id,record):record;if(sealed.state==="published")return{...sealed,changed:sealed.sealedChanged??true,commitSha:sealed.pushedCommitSha};if(sealed.state!=="sealed"||!sealed.sealedCommitSha)throw new SafeError("repository_state_invalid",409);if(!sealed.sealedChanged)return{...sealed,changed:false as const,commitSha:sealed.sealedCommitSha};const commit=sealed.sealedCommitSha,pending={...sealed,state:"push-uncertain" as const,pushedCommitSha:commit};await this.persist(paths,pending);try{await this.runGit(paths.task,[`--git-dir=${paths.gitDir}`,"push","--porcelain",this.remote(environment.repository),`refs/heads/${record.branch}:refs/heads/${record.branch}`],credential)}catch(error){const failure=classifyGitPushFailure(error);console.error(JSON.stringify({level:"error",event:"repository_git_push_failed",...failure}));if(!await this.reconcilePush(environment,paths,record,commit,credential))throw new SafeError("repository_publish_result_unknown",503)}const updated={...pending,state:"published" as const,dirty:false};await this.persist(paths,updated);return{...updated,changed:true as const,commitSha:commit}}
 async cleanup(environmentKey:string,idValue:string){return this.serialize(()=>this.cleanupOperation(environmentKey,idValue))}
 private async cleanupOperation(environmentKey:string,idValue:string){const environment=this.environment(environmentKey),id=taskId(idValue),paths=this.paths(environment,id),record=await this.readRecord(paths.record);if(!record)return{cleaned:false};await this.contained(paths.task,this.stateRoot);if(record.worktreeAvailable)await this.contained(paths.worktree,this.workspaceRoot);await rm(paths.task,{recursive:true,force:true});await rm(paths.worktree,{recursive:true,force:true});return{cleaned:true}}
 async status(environmentKey:string){const environment=this.environment(environmentKey),paths=this.paths(environment,"probe");try{await this.validateRoots(environment);const gitAvailable=await this.runGit(environment.cwd,["--version"]).then(()=>true,()=>false),initialized=await stat(paths.mirror).then(v=>v.isDirectory(),()=>false),ref=`refs/adt/remote/${environment.repository.baseBranch.replaceAll("/","-")}`,lastFetchedBaseSha=initialized?await this.runGit(paths.control,[`--git-dir=${paths.mirror}`,"rev-parse","--verify",`${ref}^{commit}`]).then(result=>SHA.test(result.stdout.trim())?result.stdout.trim():null,()=>null):null;return{environmentKey:environment.key,repositoryManagementConfigured:true,gitAvailable,repositoryInitialized:initialized,baseRepositoryAvailable:initialized,managedRootReady:true,taskStorageReady:true,lastFetchedBaseSha,baseBranch:environment.repository.baseBranch,ready:gitAvailable}}catch{return{environmentKey:environment.key,repositoryManagementConfigured:true,gitAvailable:false,repositoryInitialized:false,baseRepositoryAvailable:false,managedRootReady:false,taskStorageReady:false,lastFetchedBaseSha:null,baseBranch:environment.repository.baseBranch,ready:false}}}
}
async function body(req:IncomingMessage){let size=0;const chunks:Buffer[]=[];for await(const chunk of req){const value=Buffer.from(chunk);size+=value.length;if(size>MAX_BODY)throw new SafeError("request_too_large",413);chunks.push(value)}return Buffer.concat(chunks)}
export function createRepositoryManagerServer(configuration:RunnerConfiguration,service:ManagedRepositoryService){let key:KeyObject;try{key=createPublicKey(configuration.executorVerifyingPublicKey!);if(key.asymmetricKeyType!=="ed25519")throw new Error()}catch{throw new Error("invalid_executor_verifying_key")}const seen=new Map<string,number>();return createServer({requestTimeout:130_000,headersTimeout:10_000},async(req,res)=>{const path=new URL(req.url??"/","http://repository-manager.invalid").pathname;try{if(req.method==="GET"&&path==="/health")return json(res,200,{ok:true,role:"repository-manager"});const raw=await body(req),timestamp=req.headers["x-codex-executor-timestamp"],nonce=req.headers["x-codex-executor-nonce"],signature=req.headers["x-codex-executor-signature"],now=Date.now();for(const [n,expiry] of seen)if(expiry<now)seen.delete(n);if(typeof timestamp!=="string"||!/^[0-9]{13}$/.test(timestamp)||Math.abs(now-Number(timestamp))>30_000||typeof nonce!=="string"||!/^[a-f0-9]{48}$/.test(nonce)||seen.has(nonce)||typeof signature!=="string")throw new SafeError("unauthorized",401);const bytes=Buffer.from(signature,"base64url");if(bytes.length!==64||!verify(null,canonical(req.method??"",path,timestamp,nonce,raw),key,bytes))throw new SafeError("unauthorized",401);seen.set(nonce,now+30_000);let value:unknown;try{value=raw.length?JSON.parse(raw.toString("utf8")):undefined}catch{throw new SafeError("invalid_request",400)}
 if(req.method==="POST"&&path==="/internal/v1/repositories/prepare"){const v=exact(value,["environmentKey","taskId","credential",...(Object.hasOwn(value as object,"sourceBranch")?["sourceBranch"]:[])]);return json(res,200,await service.prepare(v as never))}
 if(req.method==="POST"&&path==="/internal/v1/repositories/publish"){const v=exact(value,["environmentKey","taskId","credential","message"]);return json(res,200,await service.publish(v as never))}
 if(req.method==="POST"&&path==="/internal/v1/repositories/inspect"){const v=exact(value,["environmentKey","taskId"]);return json(res,200,await service.inspect(String(v.environmentKey),String(v.taskId)))}
 if(req.method==="POST"&&path==="/internal/v1/repositories/cleanup"){const v=exact(value,["environmentKey","taskId"]);return json(res,200,await service.cleanup(String(v.environmentKey),String(v.taskId)))}
 if(req.method==="POST"&&path==="/internal/v1/repositories/status"){const v=exact(value,["environmentKey"]);return json(res,200,await service.status(String(v.environmentKey)))}throw new SafeError("not_found",404)}catch(error){const safe=safeError(error);json(res,safe.status,{error:safe.code})}})}

export class RepositoryManagerClient{private baseUrl:string;private privateKey:string;constructor(baseUrl:string,privateKey:string){this.baseUrl=baseUrl;this.privateKey=privateKey}private async request(path:string,value:unknown,timeout=125_000):Promise<unknown>{const raw=Buffer.from(JSON.stringify(value)),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(new URL(path,this.baseUrl),{method:"POST",headers:{"content-type":"application/json",...executorRequestHeaders(this.privateKey,"POST",path,raw)},body:raw,signal:controller.signal});const text=await response.text();if(Buffer.byteLength(text)>MAX_OUTPUT)throw new SafeError("repository_manager_invalid_response",503);const parsed:unknown=JSON.parse(text);if(!response.ok)throw new SafeError(typeof (parsed as {error?:unknown})?.error==="string"?String((parsed as {error:string}).error):"repository_manager_unavailable",response.status);return parsed}catch(error){if(error instanceof SafeError)throw error;throw new SafeError("repository_manager_unavailable",503)}finally{clearTimeout(timer)}}prepare(value:unknown){return this.request("/internal/v1/repositories/prepare",value)}publish(value:unknown){return this.request("/internal/v1/repositories/publish",value)}inspect(value:unknown){return this.request("/internal/v1/repositories/inspect",value)}cleanup(value:unknown){return this.request("/internal/v1/repositories/cleanup",value)}status(value:unknown){return this.request("/internal/v1/repositories/status",value,10_000)}}

export async function repositoryManagerFromConfiguration(configuration:RunnerConfiguration){const environments=await loadRunnerEnvironments(configuration.environmentsFile,false),service=new ManagedRepositoryService(environments,configuration.workspaceRoot??"/workspaces",{stateRoot:configuration.repositoryStateRoot});await service.initialize();return service}
