import {createServer,type IncomingMessage,type ServerResponse} from "node:http";
import {execFile} from "node:child_process";
import {createHash,createPublicKey,verify,type KeyObject} from "node:crypto";
import {access,chmod,lstat,mkdir,readFile,readdir,realpath,rm,stat,writeFile} from "node:fs/promises";
import {constants} from "node:fs";
import {dirname,isAbsolute,join,relative,sep} from "node:path";
import {SafeError,safeError} from "./errors.js";
import {executorRequestHeaders} from "./executor.js";
import {loadRunnerEnvironments,type ManagedRepositoryConfiguration,type RunnerEnvironment} from "./environments.js";
import type {RunnerConfiguration} from "./configuration.js";

const SHA=/^[a-f0-9]{40}$/,TASK=/^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/,BRANCH=/^adt\/codex\/[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/,MAX_BODY=16_384,MAX_OUTPUT=64*1024,GIT_TIMEOUT=120_000;
const canonical=(method:string,path:string,timestamp:string,nonce:string,body:Buffer)=>Buffer.from(`adt-executor-v1\n${method}\n${path}\n${timestamp}\n${nonce}\n${createHash("sha256").update(body).digest("hex")}`);
const json=(res:ServerResponse,status:number,value:unknown)=>{res.writeHead(status,{"content-type":"application/json","cache-control":"no-store","x-content-type-options":"nosniff"});res.end(JSON.stringify(value))};
const exact=(value:unknown,keys:string[])=>{if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value).some(k=>!keys.includes(k))||keys.some(k=>!Object.hasOwn(value,k)))throw new SafeError("invalid_request",400);return value as Record<string,unknown>};
const taskId=(value:unknown)=>{if(typeof value!=="string"||!TASK.test(value))throw new SafeError("invalid_request",400);return value};
const token=(value:unknown)=>{if(typeof value!=="string"||value.length<1||value.length>2048||/[\r\n\0]/.test(value))throw new SafeError("invalid_request",400);return value};

export type ManagedTaskMetadata={environmentKey:string;repository:{owner:string;repo:string};taskId:string;baseBranch:string;baseSha:string;branch:string;worktreeAvailable:boolean;pushedCommitSha?:string;dirty?:boolean};
type GitResult={stdout:string};
type ExecGit=(cwd:string,args:string[],credential?:string)=>Promise<GitResult>;

function safeGitError(error:unknown){const value=error as NodeJS.ErrnoException&{killed?:boolean;signal?:string};if(value.killed||value.signal==="SIGTERM")return new SafeError("repository_operation_timeout",503);return new SafeError("repository_operation_failed",409)}

export class ManagedRepositoryService{
 private readonly environments:RunnerEnvironment[];private readonly workspaceRoot:string;private readonly runGit:ExecGit;private readonly remote:(r:ManagedRepositoryConfiguration)=>string;private readonly allowFileProtocol:boolean;
 constructor(environments:RunnerEnvironment[],workspaceRoot:string,options:{execGit?:ExecGit;remote?:(r:ManagedRepositoryConfiguration)=>string;allowFileProtocol?:boolean}={}){this.environments=environments;this.workspaceRoot=workspaceRoot;this.remote=options.remote??(r=>`https://github.com/${encodeURIComponent(r.owner)}/${encodeURIComponent(r.repo)}.git`);this.allowFileProtocol=options.allowFileProtocol===true;this.runGit=options.execGit??this.git.bind(this)}
 private environment(key:unknown):RunnerEnvironment&{repository:ManagedRepositoryConfiguration}{if(typeof key!=="string"||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(key))throw new SafeError("invalid_request",400);const environment=this.environments.find(v=>v.key===key);if(!environment?.enabled||!environment.repository)throw new SafeError("managed_environment_unavailable",409);return environment as RunnerEnvironment&{repository:ManagedRepositoryConfiguration}}
 private async contained(path:string,allowMissing=false){const root=await realpath(this.workspaceRoot);let candidate:string;try{candidate=await realpath(path)}catch{if(!allowMissing)throw new SafeError("repository_state_invalid",409);const parent=await realpath(dirname(path));candidate=join(parent,path.slice(dirname(path).length+1))}const rel=relative(root,candidate);if(rel===""||(!isAbsolute(rel)&&rel!==".."&&!rel.startsWith(`..${sep}`)))return candidate;throw new SafeError("workspace_outside_root",400)}
 private paths(environment:RunnerEnvironment,id:string){return{root:environment.cwd,repository:join(environment.cwd,".adt","repository"),tasks:join(environment.cwd,"tasks"),worktree:join(environment.cwd,"tasks",id),record:join(environment.cwd,".adt","tasks",`${id}.json`)}}
 private async validateRoot(environment:RunnerEnvironment){await this.contained(environment.cwd);const entries=await readdir(environment.cwd);if(entries.some(v=>v!==".adt"&&v!=="tasks"))throw new SafeError("managed_root_not_empty",409);for(const item of entries){const info=await lstat(join(environment.cwd,item));if(!info.isDirectory()||info.isSymbolicLink())throw new SafeError("repository_state_invalid",409)}}
 private async askpass(){const path="/tmp/adt-git-askpass.sh";try{await access(path,constants.X_OK)}catch{await writeFile(path,"#!/bin/sh\ncase \"$1\" in *Username*) printf '%s\\n' x-access-token;; *) printf '%s\\n' \"$ADT_GIT_TOKEN\";; esac\n",{mode:0o700,flag:"wx"}).catch(()=>{});await chmod(path,0o700)}return path}
 private async git(cwd:string,args:string[],credential?:string):Promise<GitResult>{const askpass=credential?await this.askpass():undefined;const safeArgs=["-c","core.hooksPath=/dev/null","-c","credential.helper=","-c",`protocol.file.allow=${this.allowFileProtocol?"always":"never"}`,"-c","protocol.ext.allow=never",...args],proxy:Record<string,string>={};for(const name of ["HTTP_PROXY","HTTPS_PROXY","ALL_PROXY"]){const value=process.env[name];if(value)try{const url=new URL(value);if(url.protocol==="http:"&&!url.username&&!url.password)proxy[name]=value}catch{}}if(process.env.NO_PROXY&&process.env.NO_PROXY.length<=2048)proxy.NO_PROXY=process.env.NO_PROXY;const env={PATH:process.env.PATH??"/usr/bin:/bin",HOME:"/nonexistent",LANG:"C",LC_ALL:"C",GIT_CONFIG_NOSYSTEM:"1",GIT_TERMINAL_PROMPT:"0",...proxy,...(credential?{GIT_ASKPASS:askpass!,GIT_ASKPASS_REQUIRE:"force",ADT_GIT_TOKEN:credential}:{})} as unknown as NodeJS.ProcessEnv;return new Promise((resolve,reject)=>execFile("git",safeArgs,{cwd,timeout:GIT_TIMEOUT,maxBuffer:MAX_OUTPUT,encoding:"utf8",env},(error:Error|null,stdout:string|Buffer)=>error?reject(safeGitError(error)):resolve({stdout:String(stdout).slice(0,MAX_OUTPUT)})))}
 private async readRecord(path:string):Promise<ManagedTaskMetadata|undefined>{try{const raw=await readFile(path,"utf8");if(Buffer.byteLength(raw)>8192)throw new Error();const v=JSON.parse(raw) as ManagedTaskMetadata;if(!v||!TASK.test(v.taskId)||!BRANCH.test(v.branch)||!SHA.test(v.baseSha))throw new Error();return v}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw new SafeError("repository_state_invalid",409)}}
 async prepare(input:{environmentKey:string;taskId:string;credential:string;sourceBranch?:string}):Promise<ManagedTaskMetadata&{cwd:string}>{const environment=this.environment(input.environmentKey),id=taskId(input.taskId),credential=token(input.credential),paths=this.paths(environment,id);await this.validateRoot(environment);await mkdir(join(paths.root,".adt","tasks"),{recursive:true,mode:0o700});await mkdir(paths.tasks,{recursive:true,mode:0o700});await this.contained(paths.repository,true);await this.contained(paths.worktree,true);const existing=await this.readRecord(paths.record);if(existing){await access(paths.worktree,constants.R_OK|constants.W_OK|constants.X_OK).catch(()=>{throw new SafeError("repository_state_invalid",409)});return{...existing,cwd:paths.worktree}}
  const repositoryExists=await stat(paths.repository).then(v=>v.isDirectory(),()=>false);if(!repositoryExists){const adt=join(paths.root,".adt");const adtEntries=(await readdir(adt)).filter(v=>v!=="tasks");if(adtEntries.length)throw new SafeError("repository_state_invalid",409);await this.runGit(paths.root,["clone","--bare","--origin","origin",this.remote(environment.repository),paths.repository],credential)}await this.runGit(paths.repository,["fetch","--no-tags","--prune","origin",`+refs/heads/${environment.repository.baseBranch}:refs/remotes/origin/${environment.repository.baseBranch}`],credential);
  const source=input.sourceBranch;if(source!==undefined&&!BRANCH.test(source))throw new SafeError("invalid_request",400);if(source)await this.runGit(paths.repository,["fetch","--no-tags","origin",`refs/heads/${source}:refs/remotes/origin/${source}`],credential);const ref=source?`refs/remotes/origin/${source}`:`refs/remotes/origin/${environment.repository.baseBranch}`,resolved=(await this.runGit(paths.repository,["rev-parse","--verify",`${ref}^{commit}`])).stdout.trim();if(!SHA.test(resolved))throw new SafeError("repository_state_invalid",409);const branch=source??`adt/codex/${id}`;if(!BRANCH.test(branch))throw new SafeError("invalid_request",400);if(source){await this.runGit(paths.repository,["branch","-f",branch,resolved]);await this.runGit(paths.repository,["worktree","add",paths.worktree,branch])}else await this.runGit(paths.repository,["worktree","add","-b",branch,paths.worktree,resolved]);const metadata:ManagedTaskMetadata={environmentKey:environment.key,repository:{owner:environment.repository.owner,repo:environment.repository.repo},taskId:id,baseBranch:environment.repository.baseBranch,baseSha:resolved,branch,worktreeAvailable:true};await writeFile(paths.record,JSON.stringify(metadata),{mode:0o600,flag:"wx"});return{...metadata,cwd:paths.worktree}}
 async inspect(environmentKey:string,idValue:string){const environment=this.environment(environmentKey),id=taskId(idValue),paths=this.paths(environment,id),record=await this.readRecord(paths.record);if(!record)return{found:false as const};const status=(await this.runGit(paths.worktree,["status","--porcelain=v1","--untracked-files=normal"])).stdout;return{found:true as const,...record,dirty:status.length>0}}
 async publish(input:{environmentKey:string;taskId:string;credential:string;message:string}){const environment=this.environment(input.environmentKey),id=taskId(input.taskId),credential=token(input.credential);if(typeof input.message!=="string"||!input.message.trim()||input.message.length>200||/[\r\n\0]/.test(input.message))throw new SafeError("invalid_request",400);const paths=this.paths(environment,id),record=await this.readRecord(paths.record);if(!record)throw new SafeError("managed_task_not_found",404);await this.contained(paths.worktree);const status=(await this.runGit(paths.worktree,["status","--porcelain=v1","--untracked-files=normal"])).stdout;if(!status)return{...record,changed:false as const};await this.runGit(paths.worktree,["add","--all"]);await this.runGit(paths.worktree,["-c","user.name=ADT Codex Runner","-c","user.email=codex-runner@adt.invalid","commit","--no-gpg-sign","-m",input.message.trim()]);const commit=(await this.runGit(paths.worktree,["rev-parse","--verify","HEAD^{commit}"])).stdout.trim();if(!SHA.test(commit))throw new SafeError("repository_state_invalid",409);await this.runGit(paths.worktree,["push","--porcelain","origin",`refs/heads/${record.branch}:refs/heads/${record.branch}`],credential);const updated={...record,pushedCommitSha:commit,dirty:false};await writeFile(paths.record,JSON.stringify(updated),{mode:0o600});return{...updated,changed:true as const,commitSha:commit}}
 async cleanup(environmentKey:string,idValue:string){const environment=this.environment(environmentKey),id=taskId(idValue),paths=this.paths(environment,id),record=await this.readRecord(paths.record);if(!record)return{cleaned:false};await this.runGit(paths.repository,["worktree","remove","--force",paths.worktree]);await this.runGit(paths.repository,["worktree","prune"]);await rm(paths.record,{force:true});return{cleaned:true}}
 async status(environmentKey:string){const environment=this.environment(environmentKey),paths=this.paths(environment,"probe"),initialized=await stat(paths.repository).then(v=>v.isDirectory(),()=>false);const gitAvailable=await this.runGit(environment.cwd,["--version"]).then(()=>true,()=>false);let baseSha:string|undefined;if(initialized)baseSha=(await this.runGit(paths.repository,["rev-parse","--verify",`refs/remotes/origin/${environment.repository!.baseBranch}^{commit}`]).catch(()=>({stdout:""}))).stdout.trim();return{environmentKey:environment.key,repositoryManagementConfigured:true,gitAvailable,repositoryInitialized:initialized,baseRepositoryAvailable:initialized,lastFetchedBaseSha:baseSha&&SHA.test(baseSha)?baseSha:null,baseBranch:environment.repository.baseBranch}}
}

async function body(req:IncomingMessage){let size=0;const chunks:Buffer[]=[];for await(const chunk of req){const value=Buffer.from(chunk);size+=value.length;if(size>MAX_BODY)throw new SafeError("request_too_large",413);chunks.push(value)}return Buffer.concat(chunks)}
export function createRepositoryManagerServer(configuration:RunnerConfiguration,service:ManagedRepositoryService){let key:KeyObject;try{key=createPublicKey(configuration.executorVerifyingPublicKey!);if(key.asymmetricKeyType!=="ed25519")throw new Error()}catch{throw new Error("invalid_executor_verifying_key")}const seen=new Map<string,number>();return createServer({requestTimeout:130_000,headersTimeout:10_000},async(req,res)=>{const path=new URL(req.url??"/","http://repository-manager.invalid").pathname;try{if(req.method==="GET"&&path==="/health")return json(res,200,{ok:true,role:"repository-manager"});const raw=await body(req),timestamp=req.headers["x-codex-executor-timestamp"],nonce=req.headers["x-codex-executor-nonce"],signature=req.headers["x-codex-executor-signature"],now=Date.now();for(const [n,expiry] of seen)if(expiry<now)seen.delete(n);if(typeof timestamp!=="string"||!/^[0-9]{13}$/.test(timestamp)||Math.abs(now-Number(timestamp))>30_000||typeof nonce!=="string"||!/^[a-f0-9]{48}$/.test(nonce)||seen.has(nonce)||typeof signature!=="string")throw new SafeError("unauthorized",401);const bytes=Buffer.from(signature,"base64url");if(bytes.length!==64||!verify(null,canonical(req.method??"",path,timestamp,nonce,raw),key,bytes))throw new SafeError("unauthorized",401);seen.set(nonce,now+30_000);let value:unknown;try{value=raw.length?JSON.parse(raw.toString("utf8")):undefined}catch{throw new SafeError("invalid_request",400)}
 if(req.method==="POST"&&path==="/internal/v1/repositories/prepare"){const v=exact(value,["environmentKey","taskId","credential",...(Object.hasOwn(value as object,"sourceBranch")?["sourceBranch"]:[])]);return json(res,200,await service.prepare(v as never))}
 if(req.method==="POST"&&path==="/internal/v1/repositories/publish"){const v=exact(value,["environmentKey","taskId","credential","message"]);return json(res,200,await service.publish(v as never))}
 if(req.method==="POST"&&path==="/internal/v1/repositories/inspect"){const v=exact(value,["environmentKey","taskId"]);return json(res,200,await service.inspect(String(v.environmentKey),String(v.taskId)))}
 if(req.method==="POST"&&path==="/internal/v1/repositories/cleanup"){const v=exact(value,["environmentKey","taskId"]);return json(res,200,await service.cleanup(String(v.environmentKey),String(v.taskId)))}
 if(req.method==="POST"&&path==="/internal/v1/repositories/status"){const v=exact(value,["environmentKey"]);return json(res,200,await service.status(String(v.environmentKey)))}throw new SafeError("not_found",404)}catch(error){const safe=safeError(error);json(res,safe.status,{error:safe.code})}})}

export class RepositoryManagerClient{constructor(private baseUrl:string,private privateKey:string){}private async request(path:string,value:unknown,timeout=125_000):Promise<unknown>{const raw=Buffer.from(JSON.stringify(value)),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(new URL(path,this.baseUrl),{method:"POST",headers:{"content-type":"application/json",...executorRequestHeaders(this.privateKey,"POST",path,raw)},body:raw,signal:controller.signal});const text=await response.text();if(Buffer.byteLength(text)>MAX_OUTPUT)throw new SafeError("repository_manager_invalid_response",503);const parsed:unknown=JSON.parse(text);if(!response.ok)throw new SafeError(typeof (parsed as {error?:unknown})?.error==="string"?String((parsed as {error:string}).error):"repository_manager_unavailable",response.status);return parsed}catch(error){if(error instanceof SafeError)throw error;throw new SafeError("repository_manager_unavailable",503)}finally{clearTimeout(timer)}}prepare(value:unknown){return this.request("/internal/v1/repositories/prepare",value)}publish(value:unknown){return this.request("/internal/v1/repositories/publish",value)}inspect(value:unknown){return this.request("/internal/v1/repositories/inspect",value)}cleanup(value:unknown){return this.request("/internal/v1/repositories/cleanup",value)}status(value:unknown){return this.request("/internal/v1/repositories/status",value,10_000)}}

export async function repositoryManagerFromConfiguration(configuration:RunnerConfiguration){const environments=await loadRunnerEnvironments(configuration.environmentsFile,true);return new ManagedRepositoryService(environments,configuration.workspaceRoot??"/workspaces")}
