import {createServer,type IncomingMessage,type ServerResponse} from "node:http";
import {spawn} from "node:child_process";
import {timingSafeEqual} from "node:crypto";
import {AuthenticationService} from "./authentication.js";
import {executorCodexConfigOverrides,StdioAppServerClient,type AppServerClient} from "./app-server-client.js";
import {capabilities} from "./capabilities.js";
import {JOB_PROMPT_UTF8_LIMIT,JOB_REQUEST_BODY_LIMIT,loadConfiguration,type RunnerConfiguration} from "./configuration.js";
import {SafeError,safeError} from "./errors.js";
import {diagnoseAuthEnvironment,type AuthEnvironmentDiagnostics} from "./auth-environment-diagnostics.js";
import {diagnoseWorkspace,loadRunnerEnvironments,publicEnvironment} from "./environments.js";
import {PersistentCodexJobRunner,type CodexJobStartInput} from "./job-runner.js";
import {diagnoseSandbox,type SandboxDiagnostics} from "./sandbox-diagnostics.js";
import {createExecutorServer,RemoteExecutorClient} from "./executor.js";
import {EmergencyStopController} from "./emergency-stop.js";


export function safeAuthDiagnosticsLog(value:AuthEnvironmentDiagnostics){return{level:"info",event:"auth_environment_diagnostics",codexReady:value.codexAppServerReady,systemCaAvailable:value.systemCaBundlePresent&&value.systemCaBundleReadable&&value.systemCaBundleNonEmpty,ipv4Tls:value.ipv4TlsConnectivity,ipv6Tls:value.ipv6TlsConnectivity,proxyConfigured:value.httpProxyConfigured||value.httpsProxyConfigured||value.allProxyConfigured}}
function jobListLimit(url:URL){for(const key of url.searchParams.keys())if(key!=="limit")throw new SafeError("invalid_request",400);const values=url.searchParams.getAll("limit");if(values.length>1)throw new SafeError("invalid_request",400);if(!values.length)return 25;if(!/^[1-9][0-9]*$/.test(values[0]!)||Number(values[0])>100)throw new SafeError("invalid_request",400);return Number(values[0])}

const json=(response:ServerResponse,status:number,value:unknown)=>{response.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"});response.end(JSON.stringify(value));};
function authorized(request:IncomingMessage,secret:string){const supplied=request.headers["x-codex-runner-secret"];if(typeof supplied!=="string")return false;const a=Buffer.from(supplied),b=Buffer.from(secret);return a.length===b.length&&timingSafeEqual(a,b)}
const requestId=(request:IncomingMessage)=>{const value=request.headers["x-adt-request-id"];return typeof value==="string"&&/^adt-[a-f0-9-]{32,64}$/.test(value)&&value.length<=68?value:undefined};
async function boundedBody(request:IncomingMessage,limit:number){let size=0;const chunks:Buffer[]=[];for await(const chunk of request){const value=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);size+=value.length;if(size>limit)throw new SafeError("request_too_large",413);chunks.push(value)}if(size>0&&!request.headers["content-type"]?.startsWith("application/json"))throw new SafeError("json_content_type_required",415);return{size,text:Buffer.concat(chunks).toString("utf8")}}
function parseJob(text:string):CodexJobStartInput{let value:unknown;try{value=JSON.parse(text)}catch{throw new SafeError("invalid_request",400)}if(!value||typeof value!=="object"||Array.isArray(value))throw new SafeError("invalid_request",400);const item=value as Record<string,unknown>,allowed=["idempotencyKey","environmentKey","prompt","model","reasoningEffort"];if(Object.keys(item).some(key=>!allowed.includes(key))||typeof item.idempotencyKey!=="string"||item.idempotencyKey.length<1||item.idempotencyKey.length>300||typeof item.environmentKey!=="string"||item.environmentKey.length>80||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(item.environmentKey)||typeof item.prompt!=="string"||Buffer.byteLength(item.prompt)>JOB_PROMPT_UTF8_LIMIT||(item.model!==undefined&&(typeof item.model!=="string"||item.model.length<1||item.model.length>120))||(item.reasoningEffort!==undefined&&(typeof item.reasoningEffort!=="string"||item.reasoningEffort.length<1||item.reasoningEffort.length>40)))throw new SafeError("invalid_request",400);return item as unknown as CodexJobStartInput}
export function createRunnerServer(configuration:RunnerConfiguration,appServer:AppServerClient=configuration.role==="controller"?new RemoteExecutorClient(configuration.executorBaseUrl!,configuration.executorSigningPrivateKey!):new StdioAppServerClient(configuration.codexCommand,configuration.runnerVersion),diagnostics:()=>Promise<AuthEnvironmentDiagnostics>=()=>diagnoseAuthEnvironment({codexCommand:configuration.codexCommand,codexAppServerReady:()=>appServer.readiness()}),sandboxDiagnostics:(environment:import("./environments.js").RunnerEnvironment)=>Promise<SandboxDiagnostics>=environment=>diagnoseSandbox(environment,configuration.codexCommand)){
 const stateDirectory=configuration.stateDirectory??`/tmp/adt-codex-runner-${process.pid}`,auth=new AuthenticationService(appServer),emergency=EmergencyStopController.create(stateDirectory,configuration.redeployWebhook);if(configuration.role==="controller"&&appServer instanceof RemoteExecutorClient)appServer.setUncertainExecutionHandler(async()=>{await (await emergency).triggerHardRestart()});const resources=loadRunnerEnvironments(configuration.environmentsFile,configuration.role!=="controller").then(async environments=>({environments,jobs:await PersistentCodexJobRunner.create(appServer,environments,stateDirectory,configuration.jobDurationMs??7_000_000,30_000,undefined,configuration.environmentsFile!==undefined,configuration.role==="controller",configuration.role==="controller"?async()=>{await (await emergency).triggerHardRestart()}:undefined)})).catch(()=>undefined),workflowResources=async()=>{const value=await resources;if(!value)throw new SafeError("workflow_resources_unavailable",503);return value},refreshEnvironment=async(environment:import("./environments.js").RunnerEnvironment)=>{if(configuration.role!=="controller")return environment;try{const result=await (appServer as RemoteExecutorClient).workspaceDiagnostics(environment.key,environment.cwd,environment.sandbox);environment.ready=environment.enabled&&environment.sandbox==="workspace-write"&&result.filesystemReady}catch{environment.ready=false}return environment},controlStatus=async()=>{const executor=configuration.role==="controller"?await (appServer as RemoteExecutorClient).executorStatus().catch(()=>null):null;return{...(await emergency).snapshot(),role:configuration.role??"integrated",executor:executor?{healthy:executor.healthy,generation:executor.generation,activeExecutionId:executor.activeExecutionId,boundary:executor.boundary}:null}};
 return createServer({requestTimeout:65_000,headersTimeout:10_000},async(request,response)=>{const url=new URL(request.url??"/","http://runner.invalid"),path=url.pathname;try{
  if(request.method==="GET"&&path==="/health")return json(response,200,{ok:true});if(!path.startsWith("/v1/")||!authorized(request,configuration.sharedSecret!))throw new SafeError("unauthorized",401);
  const limit=request.method==="POST"&&path==="/v1/jobs"?(configuration.jobRequestBodyLimit??JOB_REQUEST_BODY_LIMIT):configuration.requestBodyLimit,body=await boundedBody(request,limit);
  if(request.method==="GET"&&path==="/v1/capabilities")return json(response,200,capabilities(configuration.runnerVersion,await appServer.readiness(),configuration.deviceAuthCompatible));
  if(request.method==="GET"&&path==="/v1/environments"){const value=await workflowResources();for(const environment of value.environments)await refreshEnvironment(environment);return json(response,200,{environments:value.environments.map(publicEnvironment)})}
  const environmentDiagnostics=/^\/v1\/environments\/([a-z0-9]+(?:-[a-z0-9]+)*)\/diagnostics$/.exec(path);if(request.method==="GET"&&environmentDiagnostics){const value=await workflowResources(),environment=value.environments.find(item=>item.key===environmentDiagnostics[1]);if(!environment)throw new SafeError("unknown_environment",404);return json(response,200,configuration.role==="controller"?await (appServer as RemoteExecutorClient).workspaceDiagnostics(environment.key,environment.cwd,environment.sandbox):await diagnoseWorkspace(environment))}
  const sandboxRoute=/^\/v1\/environments\/([a-z0-9]+(?:-[a-z0-9]+)*)\/sandbox-diagnostics$/.exec(path);if(request.method==="GET"&&sandboxRoute){const value=await workflowResources(),environment=value.environments.find(item=>item.key===sandboxRoute[1]);if(!environment)throw new SafeError("unknown_environment",404);const result=configuration.role==="controller"?await (appServer as RemoteExecutorClient).executionBoundaryDiagnostics(environment.key,environment.sandbox):await sandboxDiagnostics(environment);if(result.status!=="available")console.log(JSON.stringify({level:"info",event:"runner_sandbox_diagnostic",...(requestId(request)?{clientRequestId:requestId(request)}:{}),environmentKey:environment.key,status:result.status,backend:result.backend,reason:result.reason}));return json(response,200,result)}
  if(request.method==="GET"&&path==="/v1/models"){const status=await appServer.status() as {account?:unknown};if(!status?.account)throw new SafeError("authentication_failed",401);if(!appServer.listModels)throw new SafeError("app_server_unavailable",503);return json(response,200,{models:(await appServer.listModels()).map(model=>({id:model.id,displayName:model.displayName,isDefault:model.isDefault,defaultReasoningEffort:model.defaultReasoningEffort,supportedReasoningEfforts:model.supportedReasoningEfforts}))})}
  if(request.method==="POST"&&path==="/v1/jobs"){if((await emergency).snapshot().emergencyStopped)throw new SafeError("emergency_stopped",503);const value=await workflowResources(),input=parseJob(body.text),environment=value.environments.find(item=>item.key===input.environmentKey);if(environment)await refreshEnvironment(environment);const job=await value.jobs.start(input);console.log(JSON.stringify({level:"info",event:"runner_job_admitted",...(requestId(request)?{clientRequestId:requestId(request)}:{}),jobId:job.jobId,environmentKey:input.environmentKey}));return json(response,202,job)}
  if(request.method==="GET"&&path==="/v1/jobs"){if(body.size)throw new SafeError("invalid_request",400);return json(response,200,(await workflowResources()).jobs.list(jobListLimit(url)))}
  const lookup=/^\/v1\/jobs\/by-idempotency\/([a-f0-9]{64})$/.exec(path);if(request.method==="GET"&&lookup){const value=await workflowResources();const found=value.jobs.lookup(lookup[1]!);return found?json(response,200,found):json(response,404,{error:"not_found"})}
  const job=/^\/v1\/jobs\/([a-f0-9]{48})(\/cancel)?$/.exec(path);if(job&&request.method==="GET"&&!job[2])return json(response,200,(await workflowResources()).jobs.get(job[1]!));if(job&&request.method==="POST"&&job[2]){if(body.size)throw new SafeError("invalid_request",400);return json(response,200,await (await workflowResources()).jobs.cancel(job[1]!))}
  if(request.method==="GET"&&path==="/v1/diagnostics/auth-environment"){const result=configuration.role==="controller"?await (appServer as RemoteExecutorClient).authEnvironmentDiagnostics():await diagnostics();console.log(JSON.stringify(safeAuthDiagnosticsLog(result)));return json(response,200,result)}
  if(request.method==="GET"&&path==="/v1/control/status")return json(response,200,await controlStatus())
  if(request.method==="POST"&&path==="/v1/control/emergency-stop"){if(body.size)throw new SafeError("invalid_request",400);const executor=configuration.role==="controller"?await (appServer as RemoteExecutorClient).executorStatus().catch(()=>null):null,value=await workflowResources(),current=value.jobs.list(1).capacity.activeJobId,stop=await emergency;await stop.latch(executor?.generation);if(current){await value.jobs.cancel(current);const deadline=Date.now()+2_000;while(value.jobs.list(1).capacity.activeJobId&&Date.now()<deadline)await new Promise(resolve=>setTimeout(resolve,50))}if(configuration.role==="controller")await stop.triggerHardRestart();return json(response,200,await controlStatus())}
  if(request.method==="POST"&&path==="/v1/control/resume"){if(body.size)throw new SafeError("invalid_request",400);const executor=configuration.role==="controller"?await (appServer as RemoteExecutorClient).executorStatus().catch(()=>null):null,jobs=(await workflowResources()).jobs.list(1);try{await (await emergency).resume(configuration.role==="controller"&&executor?.healthy?executor.generation:configuration.role==="controller"?undefined:"integrated",configuration.role==="controller"?executor?.healthy===true&&executor.activeExecutionId===null:jobs.capacity.activeJobId===null);return json(response,200,await controlStatus())}catch{throw new SafeError("unsafe_resume",409)}}
  if(request.method==="GET"&&path==="/v1/auth/status")return json(response,200,await auth.status());if(request.method==="POST"&&path==="/v1/auth/device/start")return json(response,200,await auth.startDevice());if(request.method==="POST"&&path==="/v1/auth/logout")return json(response,200,await auth.logout());if(request.method==="POST"&&path==="/v1/codex/test"){if(body.size!==0)throw new SafeError("invalid_request",400);if(!appServer.testCodex)return json(response,503,{ok:false,reason:"app_server_unavailable"});return json(response,200,await appServer.testCodex())}throw new SafeError("not_found",404);
 }catch(error){const safe=safeError(error),details=safe.details;console.error(JSON.stringify({level:"error",event:"runner_operation_failed",operation:`${request.method??"UNKNOWN"} ${path}`,category:safe.code,...(requestId(request)?{clientRequestId:requestId(request)}:{}),...details}));json(response,safe.status,{error:safe.code,...details});}}).on("close",()=>void appServer.close());
}
if(process.argv[1]===new URL(import.meta.url).pathname){const config=await loadConfiguration(),app=config.role==="controller"?new RemoteExecutorClient(config.executorBaseUrl!,config.executorSigningPrivateKey!):new StdioAppServerClient(config.codexCommand,config.runnerVersion,8_000,spawn,52_000,2_000,config.role==="executor"?executorCodexConfigOverrides(process.env):[]),server=config.role==="executor"?createExecutorServer(config,app):createRunnerServer(config,app);server.listen(config.port,config.host,()=>console.log(JSON.stringify({level:"info",event:"runner_started",role:config.role,port:config.port,externalSecretLoaded:config.role!=="executor"})));const stop=()=>server.close(()=>process.exit(0));process.on("SIGTERM",stop);process.on("SIGINT",stop);}
