import {createHash,randomBytes} from "node:crypto";
import {spawn} from "node:child_process";
import {access,constants,copyFile,lstat,mkdir,mkdtemp,open,readFile,readdir,rename,rm,stat,writeFile} from "node:fs/promises";
import {dirname,join} from "node:path";
import {tmpdir} from "node:os";
import type {RunnerConfiguration} from "./configuration.js";
import {SafeError} from "./errors.js";

const BACKUP_ID=/^b-[0-9]{8}T[0-9]{6}Z-[a-f0-9]{12}$/,DB=/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}\.(?:sqlite|db)$/i,MANIFEST="manifest.json",SCHEMA=1;
export type FilesystemClass="local"|"network"|"unknown";
export interface BackupMetadata{backupId:string;createdAt:string;runnerVersion:string;codexVersion:string;databases:{filename:string;size:number;sha256:string}[]}
export interface SqliteStorageStatus{separateSqliteHomeConfigured:boolean;sqliteFilesystemClass:FilesystemClass;sqliteHomeReadable:boolean;sqliteHomeWritable:boolean;codexHomeFilesystemClass:FilesystemClass;backupDirectoryAvailable:boolean;backupDirectoryWritable:boolean;lastSuccessfulBackupAt?:string;lastBackupFailureCategory?:string;latestBackupId?:string;retainedBackupCount:number;retention:number;operation:"idle"|"backup"|"restore";warning?:"network_filesystem_unsupported_for_sqlite"|"sqlite_home_not_separated"}
type Mount={mountPoint:string;filesystemType:string};
export function parseMountInfo(text:string):Mount[]{
 return text.split("\n").flatMap(line=>{
  const fields=line.split(" "),separator=fields.indexOf("-");
  if(separator<0||!fields[4]||!fields[separator+1])return[];
  return[{mountPoint:fields[4].replace(/\\040/g," "),filesystemType:fields[separator+1]!}];
 });
}
export function classifyFilesystem(path:string,mounts:Mount[]):FilesystemClass{const mount=mounts.filter(item=>path===item.mountPoint||path.startsWith(item.mountPoint.replace(/\/$/,"")+"/")).sort((a,b)=>b.mountPoint.length-a.mountPoint.length)[0];if(!mount)return"unknown";if(/^(nfs|nfs4|cifs|smb|smbfs|9p|ceph|glusterfs|fuse\.sshfs)$/i.test(mount.filesystemType))return"network";return"local"}
async function usable(path:string,mode:number){try{await access(path,mode);return true}catch{return false}}
async function databases(path:string){try{return(await readdir(path,{withFileTypes:true})).filter(item=>item.isFile()&&DB.test(item.name)&&!item.name.endsWith("-wal")&&!item.name.endsWith("-shm")).map(item=>item.name).sort()}catch{return[]}}
async function checksum(path:string){const handle=await open(path,"r"),hash=createHash("sha256");try{for await(const chunk of handle.readableWebStream())hash.update(Buffer.from(chunk))}finally{await handle.close()}return hash.digest("hex")}
async function sqliteBackup(source:string,destination:string){await new Promise<void>((resolve,reject)=>{const child=spawn("sqlite3",[source,`.backup ${JSON.stringify(destination)}`],{stdio:["ignore","ignore","ignore"]});child.once("error",reject);child.once("exit",code=>code===0?resolve():reject(new Error("sqlite_backup_failed")))})}
async function safeBackupDirectory(root:string,id:string){if(!BACKUP_ID.test(id))throw new SafeError("invalid_backup_id",400);const rootReal=await import("node:fs/promises").then(fs=>fs.realpath(root));const candidate=join(root,id),entry=await lstat(candidate).catch(()=>undefined);if(!entry?.isDirectory()||entry.isSymbolicLink())throw new SafeError("backup_not_found",404);const real=await import("node:fs/promises").then(fs=>fs.realpath(candidate));if(dirname(real)!==rootReal)throw new SafeError("invalid_backup_id",400);return real}
function validManifest(value:unknown,id:string):value is BackupMetadata&{schemaVersion:number}{if(!value||typeof value!=="object"||Array.isArray(value))return false;const v=value as Record<string,unknown>;return v.schemaVersion===SCHEMA&&v.backupId===id&&typeof v.createdAt==="string"&&Number.isFinite(Date.parse(v.createdAt))&&typeof v.runnerVersion==="string"&&typeof v.codexVersion==="string"&&Array.isArray(v.databases)&&v.databases.length>0&&v.databases.every(raw=>{const d=raw as Record<string,unknown>;return d&&DB.test(String(d.filename))&&Number.isSafeInteger(d.size)&&Number(d.size)>=0&&typeof d.sha256==="string"&&/^[a-f0-9]{64}$/.test(d.sha256)})}

export class SqliteStorageManager{
 private operation:SqliteStorageStatus["operation"]="idle";private lastFailure?:string;private timer?:NodeJS.Timeout;
 constructor(private readonly config:RunnerConfiguration,private readonly codexVersion:string){ }
 async initialize(){if(!this.config.sqliteHome)return;await mkdir(this.config.sqliteHome,{recursive:true,mode:0o700});const existing=await databases(this.config.sqliteHome),marker=join(this.config.sqliteHome,".adt-bootstrap-v1");if(existing.length||await usable(marker,constants.F_OK))return;const legacy=await databases(this.config.codexHome);if(!legacy.length){await writeFile(marker,"empty\n",{mode:0o600,flag:"wx"});return}const stage=await mkdtemp(join(dirname(this.config.sqliteHome),".adt-sqlite-bootstrap-"));try{for(const name of legacy){for(const suffix of ["","-wal","-shm"]){const source=join(this.config.codexHome,name+suffix);if(await usable(source,constants.R_OK))await copyFile(source,join(stage,name+suffix),constants.COPYFILE_EXCL)}}for(const name of await readdir(stage))await rename(join(stage,name),join(this.config.sqliteHome,name));await writeFile(marker,"legacy-copy-complete\n",{mode:0o600,flag:"wx"})}catch{for(const name of await readdir(stage).catch(()=>[]))await rm(join(this.config.sqliteHome,name),{force:true}).catch(()=>{});throw new Error("sqlite_bootstrap_failed")}finally{await rm(stage,{recursive:true,force:true})}}
 startScheduler(){if(!this.config.sqliteHome)return;this.timer=setInterval(()=>void this.createBackup().catch(()=>{}),this.config.sqliteBackupIntervalMs);this.timer.unref()}
 stopScheduler(){if(this.timer)clearInterval(this.timer)}
 async list():Promise<BackupMetadata[]>{await mkdir(this.config.sqliteBackupRoot,{recursive:true,mode:0o700});const entries=await readdir(this.config.sqliteBackupRoot,{withFileTypes:true});const result:BackupMetadata[]=[];for(const entry of entries){if(!entry.isDirectory()||!BACKUP_ID.test(entry.name))continue;try{const directory=await safeBackupDirectory(this.config.sqliteBackupRoot,entry.name),value=JSON.parse(await readFile(join(directory,MANIFEST),"utf8"));if(validManifest(value,entry.name))result.push({backupId:value.backupId,createdAt:value.createdAt,runnerVersion:value.runnerVersion,codexVersion:value.codexVersion,databases:value.databases})}catch{/* Ignore incomplete or invalid sets. */}}return result.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
 async status():Promise<SqliteStorageStatus>{const mounts=parseMountInfo(await readFile("/proc/self/mountinfo","utf8").catch(()=>"")),sqlitePath=this.config.sqliteHome??this.config.codexHome,sqliteFilesystemClass=classifyFilesystem(sqlitePath,mounts),backups=await this.list().catch(()=>[]),backupAvailable=await usable(this.config.sqliteBackupRoot,constants.R_OK),backupWritable=await usable(this.config.sqliteBackupRoot,constants.W_OK);return{separateSqliteHomeConfigured:Boolean(this.config.sqliteHome),sqliteFilesystemClass,sqliteHomeReadable:await usable(sqlitePath,constants.R_OK),sqliteHomeWritable:await usable(sqlitePath,constants.W_OK),codexHomeFilesystemClass:classifyFilesystem(this.config.codexHome,mounts),backupDirectoryAvailable:backupAvailable,backupDirectoryWritable:backupWritable,...(backups[0]?{lastSuccessfulBackupAt:backups[0].createdAt,latestBackupId:backups[0].backupId}:{}),...(this.lastFailure?{lastBackupFailureCategory:this.lastFailure}:{}),retainedBackupCount:backups.length,retention:this.config.sqliteBackupRetention,operation:this.operation,...(sqliteFilesystemClass==="network"?{warning:"network_filesystem_unsupported_for_sqlite" as const}:!this.config.sqliteHome?{warning:"sqlite_home_not_separated" as const}:{})}}
 async createBackup():Promise<BackupMetadata>{if(!this.config.sqliteHome)throw new SafeError("sqlite_home_not_configured",409);if(this.operation!=="idle")throw new SafeError("runner_busy",409);this.operation="backup";let local:string|undefined,nfs:string|undefined;try{const names=await databases(this.config.sqliteHome);if(!names.length)throw new Error("no_sqlite_databases");local=await mkdtemp(join(tmpdir(),"adt-sqlite-backup-"));const createdAt=new Date().toISOString(),backupId=`b-${createdAt.replace(/[-:]/g,"").replace(/\.\d{3}/,"")}-${randomBytes(6).toString("hex")}`;for(const name of names)await sqliteBackup(join(this.config.sqliteHome,name),join(local,name));const records=[];for(const name of names){const s=await stat(join(local,name));records.push({filename:name,size:s.size,sha256:await checksum(join(local,name))})}const manifest={schemaVersion:SCHEMA,backupId,createdAt,runnerVersion:this.config.runnerVersion,codexVersion:this.codexVersion,databases:records};await mkdir(this.config.sqliteBackupRoot,{recursive:true,mode:0o700});nfs=join(this.config.sqliteBackupRoot,`.staging-${backupId}`);await mkdir(nfs,{mode:0o700});for(const record of records){await copyFile(join(local,record.filename),join(nfs,record.filename),constants.COPYFILE_EXCL);if(await checksum(join(nfs,record.filename))!==record.sha256)throw new Error("backup_verification_failed")}await writeFile(join(nfs,MANIFEST),JSON.stringify(manifest)+"\n",{mode:0o600,flag:"wx"});await rename(nfs,join(this.config.sqliteBackupRoot,backupId));nfs=undefined;this.lastFailure=undefined;await this.prune();return manifest}catch(error){this.lastFailure=error instanceof Error&&/^[a-z_]+$/.test(error.message)?error.message:"backup_failed";throw new SafeError("sqlite_backup_failed",503)}finally{if(local)await rm(local,{recursive:true,force:true});if(nfs)await rm(nfs,{recursive:true,force:true});this.operation="idle"}}
 private async prune(){const complete=await this.list();for(const backup of complete.slice(this.config.sqliteBackupRetention))await rm(await safeBackupDirectory(this.config.sqliteBackupRoot,backup.backupId),{recursive:true})}
 async restore(id:string|"latest",hooks:{busy:()=>boolean;close:()=>Promise<void>;ready:()=>Promise<boolean>}):Promise<{backupId:string;rollbackOccurred:boolean}>{
  if(!this.config.sqliteHome)throw new SafeError("sqlite_home_not_configured",409);
  if(this.operation!=="idle"||hooks.busy())throw new SafeError("runner_busy",409);
  this.operation="restore";let safety:string|undefined,stage:string|undefined,movedCurrent=false,selected="";
  try{
   selected=id==="latest"?(await this.list())[0]?.backupId??"":id;if(!selected)throw new SafeError("backup_not_found",404);
   const directory=await safeBackupDirectory(this.config.sqliteBackupRoot,selected),manifest=JSON.parse(await readFile(join(directory,MANIFEST),"utf8"));
   if(!validManifest(manifest,selected))throw new SafeError("invalid_backup",409);
   for(const database of manifest.databases)if(await checksum(join(directory,database.filename))!==database.sha256||(await stat(join(directory,database.filename))).size!==database.size)throw new SafeError("invalid_backup",409);
   stage=await mkdtemp(join(dirname(this.config.sqliteHome),".adt-restore-"));for(const database of manifest.databases)await copyFile(join(directory,database.filename),join(stage,database.filename),constants.COPYFILE_EXCL);
   await hooks.close();safety=await mkdtemp(join(dirname(this.config.sqliteHome),".adt-pre-restore-"));
   for(const name of await readdir(this.config.sqliteHome))if(DB.test(name)||name.endsWith("-wal")||name.endsWith("-shm"))await rename(join(this.config.sqliteHome,name),join(safety,name));movedCurrent=true;
   for(const database of manifest.databases)await rename(join(stage,database.filename),join(this.config.sqliteHome,database.filename));
   if(!await hooks.ready())throw new Error("restore_readiness_failed");
   return{backupId:selected,rollbackOccurred:false};
  }catch(error){
   if(movedCurrent&&safety){await hooks.close().catch(()=>{});for(const name of await readdir(this.config.sqliteHome).catch(()=>[]))if(DB.test(name)||name.endsWith("-wal")||name.endsWith("-shm"))await rm(join(this.config.sqliteHome,name),{force:true});for(const name of await readdir(safety).catch(()=>[]))await rename(join(safety,name),join(this.config.sqliteHome,name));await hooks.ready().catch(()=>false);throw new SafeError("restore_failed_rolled_back",503)}
   throw error;
  }finally{if(stage)await rm(stage,{recursive:true,force:true});if(safety)await rm(safety,{recursive:true,force:true});this.operation="idle"}
 }
}
