import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {WebSocketServer} from 'ws';
import {decodeClientFrame} from './support/decode-client-frame.mjs';
import {probeAdrianControlChannel} from '../dist/adrian-commissioning.js';

const loginAck=mode=>Buffer.from([0x0a,0x04,0x0a,0x02,0x08,mode]);
async function fixture({reject,reply,close}={}){let authorization,login;const server=createServer();const wss=new WebSocketServer({noServer:true});server.on('upgrade',(req,socket,head)=>{authorization=req.headers.authorization;if(reject){socket.write(`HTTP/1.1 ${reject} Rejected\r\nConnection: close\r\n\r\n`);socket.destroy();return}wss.handleUpgrade(req,socket,head,ws=>wss.emit('connection',ws,req))});wss.on('connection',ws=>ws.once('message',data=>{login=decodeClientFrame(data);if(close)ws.close(close);else if(reply)ws.send(reply)}));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();return{url:`ws://127.0.0.1:${address.port}`,get authorization(){return authorization},get login(){return login},close:()=>new Promise(resolve=>{wss.close();server.close(resolve)})}}
for(const status of [401,403,404])test(`upgrade rejection ${status} is bounded`,async()=>{const f=await fixture({reject:status});try{const result=await probeAdrianControlChannel({endpointUrl:f.url,apiKey:'top-secret',sessionId:'adt:test:one'});assert.equal(result.safeCode,status===404?'adrian_ws_upgrade_rejected':'adrian_ws_authentication_failed');assert.equal(result.httpStatus,status);assert.doesNotMatch(JSON.stringify(result),/top-secret|Rejected/)}finally{await f.close()}});
test('valid login sends bearer SessionLogin and accepts only Block',async()=>{const f=await fixture({reply:loginAck(3)});try{const result=await probeAdrianControlChannel({endpointUrl:f.url,apiKey:'key-value',sessionId:'adt:test:bounded'});assert.equal(result.ok,true);assert.equal(result.policyMode,'block');assert.equal(f.authorization,'Bearer key-value');assert.deepEqual(f.login,{sessionId:'adt:test:bounded',provider:'adt-diagnostic',model:'none',schemaVersion:2})}finally{await f.close()}});
for(const [mode,code,name] of [[1,'adrian_policy_alert_mode','alert'],[2,'adrian_policy_hitl_unsupported','hitl'],[0,'adrian_policy_unspecified','unspecified']])test(`${name} policy is not enforcement-ready`,async()=>{const f=await fixture({reply:loginAck(mode)});try{const result=await probeAdrianControlChannel({endpointUrl:f.url,apiKey:'key',sessionId:'adt:test:x'});assert.equal(result.safeCode,code);assert.equal(result.policyMode,name)}finally{await f.close()}});
test('close, timeout, malformed and non-login frames remain distinct safe outcomes',async t=>{for(const [name,settings,code] of [['close',{close:1008},'adrian_ws_closed_before_login'],['timeout',{},'adrian_login_timeout'],['malformed',{reply:Buffer.from([255])},'adrian_protocol_invalid'],['other frame',{reply:Buffer.from([0x12,0])},'adrian_protocol_invalid']])await t.test(name,async()=>{const f=await fixture(settings);try{const result=await probeAdrianControlChannel({endpointUrl:f.url,apiKey:'key',sessionId:'adt:test:x',loginTimeoutMs:20});assert.equal(result.safeCode,code);if(name==='close')assert.equal(result.websocketCloseCode,1008)}finally{await f.close()}})});
test('connection failure is unreachable without leaking raw errors',async()=>{const result=await probeAdrianControlChannel({endpointUrl:'ws://127.0.0.1:1',apiKey:'never-log-this',sessionId:'adt:test:x',connectTimeoutMs:50});assert.equal(result.safeCode,'adrian_ws_unreachable');assert.doesNotMatch(JSON.stringify(result),/never-log-this|ECONNREFUSED/)});
