import test from 'node:test';
import assert from 'node:assert/strict';
import {MemorySaver} from '@langchain/langgraph';
import {advanceGenericGraph,compileGenericStateGraph,evaluateCondition,RemoteCheckpointSaver} from '../dist/langgraph.js';
test('remote saver rejects cross-thread access before a request',async()=>{let calls=0;const saver=new RemoteCheckpointSaver('https://adt.example/checkpoints','authority','run-a',async()=>{calls++;return Response.json({ok:true,result:null})});await assert.rejects(saver.getTuple({configurable:{thread_id:'run-b'}}),/checkpoint_authority_invalid/);assert.equal(calls,0)});

test('checkpoint callback distinguishes timeout, network, and received HTTP evidence',async()=>{for(const [error,outcome] of [[new DOMException('timed out','TimeoutError'),'timeout'],[new TypeError('offline'),'network_error']]){const saver=new RemoteCheckpointSaver('https://adt.example/checkpoints','authority','run-a',async()=>{throw error});await assert.rejects(saver.getTuple({configurable:{thread_id:'run-a'}}),value=>{assert.equal(value.orchestration.stage,'checkpoint_gateway');assert.equal(value.orchestration.transportOutcome,outcome);assert.equal(value.orchestration.httpStatus,undefined);return true})}const saver=new RemoteCheckpointSaver('https://adt.example/checkpoints','authority','run-a',async()=>Response.json({ok:false},{status:401}));await assert.rejects(saver.getTuple({configurable:{thread_id:'run-a'}}),value=>{assert.deepEqual(value.orchestration,{stage:'checkpoint_gateway',code:'checkpoint_authority_invalid',httpStatus:401,transportOutcome:'response_received'});return true})});
function gatewayFixture({failAfterA=false,pendingFirst=false,loseNodeResponseAfterSuccess=false}={}){const pendingSeen=new Set(),lostNodeResponses=new Set(),checkpoints=new Map(),writes=new Map(),attempts=new Map(),providerCalls=new Map();let failed=false;const tuple=id=>{const value=checkpoints.get(id);if(!value)return null;return{...value,pendingWrites:writes.get(id)??[]}},fetcher=async(url,init)=>{const body=JSON.parse(init.body);if(String(url).includes('nodes')){if(pendingFirst&&!pendingSeen.has(body.nodeId)){pendingSeen.add(body.nodeId);return Response.json({state:'pending'})}const prior=attempts.get(body.nodeId);if(prior)return Response.json({state:'completed',outputText:prior});providerCalls.set(body.nodeId,(providerCalls.get(body.nodeId)??0)+1);const output=`${body.inputText}|${body.nodeId}`;attempts.set(body.nodeId,output);if(loseNodeResponseAfterSuccess&&!lostNodeResponses.has(body.nodeId)){lostNodeResponses.add(body.nodeId);throw new TypeError('lost')}return Response.json({state:'completed',outputText:output})}const {operation,payload}=body;if(operation==='get'){const id=payload.config.configurable.checkpoint_id;const value=id?tuple(id):tuple([...checkpoints.keys()].at(-1));return Response.json({ok:true,result:value})}if(operation==='list')return Response.json({ok:true,result:[...checkpoints.keys()].reverse().map(tuple)});if(operation==='putWrites'){const id=payload.config.configurable.checkpoint_id,current=writes.get(id)??[];payload.writes.forEach(([channel,value])=>current.push([payload.taskId,channel,value]));writes.set(id,current);return Response.json({ok:true,result:null})}if(operation==='put'){const cp=payload.checkpoint;if(failAfterA&&!failed&&cp.channel_values?.outputs?.some?.(value=>value.output?.endsWith('|a'))){failed=true;return Response.json({ok:false,error:'checkpoint_persistence_unavailable'},{status:503})}const config={configurable:{...payload.config.configurable,checkpoint_id:cp.id}},parentId=payload.config.configurable.checkpoint_id;checkpoints.set(cp.id,{config,checkpoint:cp,metadata:payload.metadata,...(parentId?{parentConfig:{configurable:{...config.configurable,checkpoint_id:parentId}}}:{})});return Response.json({ok:true,result:config})}return Response.json({ok:true,result:null})};return{fetcher,providerCalls,attempts,checkpoints,writes}}
const genericPlan={planVersion:2,nodes:[{id:'research',blockType:'agent',blockVersion:1,config:{agentId:'researcher'}},{id:'condition',blockType:'condition',blockVersion:1,config:{operator:'contains',value:'approved',caseSensitive:false}},{id:'accept',blockType:'agent',blockVersion:1,config:{agentId:'accept'}},{id:'revise',blockType:'agent',blockVersion:1,config:{agentId:'revise'}},{id:'finish',blockType:'agent',blockVersion:1,config:{agentId:'finish'}}],edges:[{source:'research',sourcePort:'out',target:'condition',targetPort:'in'},{source:'condition',sourcePort:'true',target:'accept',targetPort:'in'},{source:'condition',sourcePort:'false',target:'revise',targetPort:'in'},{source:'accept',sourcePort:'out',target:'finish',targetPort:'in'},{source:'revise',sourcePort:'out',target:'finish',targetPort:'in'}],entryNodeId:'research',terminalNodeId:'finish',maxStepExecutions:32};
test('bounded contains predicate is deterministic',()=>{assert.equal(evaluateCondition({operator:'contains',value:'approved',caseSensitive:false},'APPROVED\n'),true);assert.equal(evaluateCondition({operator:'contains',value:'approved',caseSensitive:true},'APPROVED\n'),false)});
test('generic graph selects true route only and preserves Condition text',async()=>{const calls=[],graph=compileGenericStateGraph(genericPlan,async(node,input)=>{calls.push([node.id,input]);return node.id==='research'?'APPROVED\n':`${input}|${node.id}`},new MemorySaver()),config={configurable:{thread_id:'generic-true'}};for(let i=0;i<4;i++)await graph.invoke(i?null:{input:'start',activeText:'start',outputs:{},executions:0},config);assert.deepEqual(calls.map(call=>call[0]),['research','accept','finish']);assert.equal(calls[1][1],'APPROVED\n');const snapshot=await graph.getState(config);assert.equal(snapshot.values.executions,4)});
test('generic graph selects false route independent of plan order',async()=>{const calls=[],plan={...genericPlan,nodes:[...genericPlan.nodes].reverse(),edges:[...genericPlan.edges].reverse()},graph=compileGenericStateGraph(plan,async(node,input)=>{calls.push(node.id);return node.id==='research'?'needs revision':input},new MemorySaver()),config={configurable:{thread_id:'generic-false'}};for(let i=0;i<4;i++)await graph.invoke(i?null:{input:'start',activeText:'start',outputs:{},executions:0},config);assert.deepEqual(calls,['research','revise','finish'])});

test('structured fan-out runs one bounded parallel frontier and Join aggregates by semantic source',async()=>{const plan={planVersion:2,nodes:[{id:'input',blockType:'agent',blockVersion:1,config:{agentId:'input'}},{id:'reviewer-a',blockType:'agent',blockVersion:1,config:{agentId:'a'}},{id:'reviewer-b',blockType:'agent',blockVersion:1,config:{agentId:'b'}},{id:'join',blockType:'join',blockVersion:1,config:{}},{id:'synthesis',blockType:'agent',blockVersion:1,config:{agentId:'s'}}],edges:[{source:'input',sourcePort:'out',target:'reviewer-a',targetPort:'in'},{source:'input',sourcePort:'out',target:'reviewer-b',targetPort:'in'},{source:'reviewer-a',sourcePort:'out',target:'join',targetPort:'in'},{source:'reviewer-b',sourcePort:'out',target:'join',targetPort:'in'},{source:'join',sourcePort:'out',target:'synthesis',targetPort:'in'}],entryNodeId:'input',terminalNodeId:'synthesis',maxStepExecutions:8},calls=[],active=new Set();let parallel=false;const graph=compileGenericStateGraph(plan,async(node,input,activationId)=>{calls.push({node:node.id,input,activationId});if(node.id.startsWith('reviewer')){active.add(node.id);await new Promise(resolve=>setTimeout(resolve,5));parallel ||= active.size===2;active.delete(node.id)}return node.id==='input'?'seed':node.id==='synthesis'?input:`${node.id}-output`},new MemorySaver()),config={configurable:{thread_id:'parallel'}};for(let turn=0;turn<4;turn++)await graph.invoke(turn?null:{initialInput:'start',outputs:[],executions:0},config);assert.equal(parallel,true);const synthesis=calls.find(value=>value.node==='synthesis');assert.equal(synthesis.input,JSON.stringify({inputs:[{sourceNodeId:'reviewer-a',output:'reviewer-a-output'},{sourceNodeId:'reviewer-b',output:'reviewer-b-output'}]}));assert.equal(calls.filter(value=>value.node.startsWith('reviewer')).length,2)});

test('controlled loop creates distinct LangGraph Agent activations and preserves prior outputs',async()=>{const plan={planVersion:2,nodes:[{id:'draft',blockType:'agent',blockVersion:1,config:{agentId:'draft'}},{id:'review',blockType:'agent',blockVersion:1,config:{agentId:'review'}},{id:'condition',blockType:'condition',blockVersion:1,config:{operator:'contains',value:'approved',caseSensitive:false}},{id:'finish',blockType:'agent',blockVersion:1,config:{agentId:'finish'}}],edges:[{source:'draft',sourcePort:'out',target:'review',targetPort:'in'},{source:'review',sourcePort:'out',target:'condition',targetPort:'in'},{source:'condition',sourcePort:'true',target:'finish',targetPort:'in'},{source:'condition',sourcePort:'false',target:'draft',targetPort:'in'}],entryNodeId:'draft',terminalNodeId:'finish',maxStepExecutions:12},draftActivations=[],reviews=[],graph=compileGenericStateGraph(plan,async(node,input,activationId)=>{if(node.id==='draft'){draftActivations.push(activationId);return `draft-${draftActivations.length}`}if(node.id==='review'){reviews.push(input);return reviews.length===1?'revise':'approved'}return input},new MemorySaver()),config={configurable:{thread_id:'loop'},recursionLimit:20};for(let turn=0;turn<8;turn++){await graph.invoke(turn?null:{initialInput:'start',outputs:[],executions:0},config);const state=await graph.getState(config);if(!state.next.length)break}assert.equal(draftActivations.length,2);assert.notEqual(draftActivations[0],draftActivations[1]);assert.deepEqual(reviews,['draft-1','draft-2'])});

test('generic advance binds inspected task IDs and resumes only incomplete parallel siblings',async()=>{const plan={planVersion:2,nodes:[{id:'input',blockType:'agent',blockVersion:1,config:{agentId:'input'}},{id:'a',blockType:'agent',blockVersion:1,config:{agentId:'a'}},{id:'b',blockType:'agent',blockVersion:1,config:{agentId:'b'}},{id:'join',blockType:'join',blockVersion:1,config:{}},{id:'finish',blockType:'agent',blockVersion:1,config:{agentId:'finish'}}],edges:[{source:'input',sourcePort:'out',target:'a',targetPort:'in'},{source:'input',sourcePort:'out',target:'b',targetPort:'in'},{source:'a',sourcePort:'out',target:'join',targetPort:'in'},{source:'b',sourcePort:'out',target:'join',targetPort:'in'},{source:'join',sourcePort:'out',target:'finish',targetPort:'in'}],entryNodeId:'input',terminalNodeId:'finish',maxStepExecutions:8},runId=crypto.randomUUID(),fixture=gatewayFixture(),base={protocolVersion:'adt-runtime-v1',capability:'langgraph:graph',requestId:'generic-request',runId,initialInput:'initial',plan,checkpointGateway:{url:'https://adt.example/checkpoints',authority:'c'.repeat(32)}},inspect=()=>advanceGenericGraph({...base,nodeGateway:{url:'https://adt.example/nodes'}},fetcher),admit=frontier=>advanceGenericGraph({...base,nodeGateway:{url:'https://adt.example/nodes',authorities:frontier.map((item,index)=>({ ...item,authority:`${index}`.padEnd(32,'n'),workflowGeneration:1,iteration:1,attempt:1}))}},fetcher);let pendingB=true;const seen=[];async function fetcher(url,init){if(String(url).includes('nodes')){const body=JSON.parse(init.body);seen.push([body.nodeId,body.activationId]);if(body.nodeId==='b'&&pendingB)return Response.json({state:'pending',retryAfterMs:1000})}return fixture.fetcher(url,init)}let state=await inspect();assert.equal(state.frontier.length,1);const entryActivation=state.frontier[0].activationId;await assert.rejects(advanceGenericGraph({...base,nodeGateway:{url:'https://adt.example/nodes',authorities:[{nodeId:'input',activationId:'wrong-task',authority:'n'.repeat(32),workflowGeneration:1,iteration:1,attempt:1}]}},fetcher),/graph_node_gateway_invalid/);await admit(state.frontier);state=await inspect();assert.deepEqual(state.frontier.map(value=>value.nodeId),['a','b']);const siblingIds=Object.fromEntries(state.frontier.map(value=>[value.nodeId,value.activationId]));const pending=await admit(state.frontier);assert.equal(pending.state,'pending');state=await inspect();assert.deepEqual(state.frontier,[{nodeId:'b',activationId:siblingIds.b}]);assert.equal(seen.filter(([node])=>node==='a').length,1);assert.equal(seen.find(([node])=>node==='input')[1],entryActivation);assert.equal(siblingIds.a===siblingIds.b,false)});

test('checkpoint live outputs remain bounded across near-limit loop iterations',async()=>{const large='x'.repeat(240_000),plan={planVersion:2,nodes:[{id:'draft',blockType:'agent',blockVersion:1,config:{agentId:'draft'}},{id:'condition',blockType:'condition',blockVersion:1,config:{operator:'contains',value:'approved',caseSensitive:false}},{id:'finish',blockType:'agent',blockVersion:1,config:{agentId:'finish'}}],edges:[{source:'draft',sourcePort:'out',target:'condition',targetPort:'in'},{source:'condition',sourcePort:'false',target:'draft',targetPort:'in'},{source:'condition',sourcePort:'true',target:'finish',targetPort:'in'}],entryNodeId:'draft',terminalNodeId:'finish',maxStepExecutions:12},visits=[],graph=compileGenericStateGraph(plan,async(node,input)=>{if(node.id==='draft'){visits.push(input);return visits.length<4?large:`${large}approved`}return input},new MemorySaver()),config={configurable:{thread_id:'bounded-loop'},recursionLimit:20};for(let turn=0;turn<8;turn++){await graph.invoke(turn?null:{initialInput:'start',outputs:[],executions:0},config);const state=await graph.getState(config);assert.ok(Buffer.byteLength(JSON.stringify(state.values))<1_000_000);if(!state.next.length)break}assert.equal(visits.length,4)});

test('consecutive large parallel regions compact completed inputs and restart with exact region-local Join data',async()=>{const largeA='a'.repeat(120_000),largeB='b'.repeat(120_000),plan={planVersion:2,nodes:[{id:'seed',blockType:'agent',blockVersion:1,config:{agentId:'seed'}},{id:'one-a',blockType:'agent',blockVersion:1,config:{agentId:'one-a'}},{id:'one-b',blockType:'agent',blockVersion:1,config:{agentId:'one-b'}},{id:'join-one',blockType:'join',blockVersion:1,config:{}},{id:'two-a',blockType:'agent',blockVersion:1,config:{agentId:'two-a'}},{id:'two-b',blockType:'agent',blockVersion:1,config:{agentId:'two-b'}},{id:'join-two',blockType:'join',blockVersion:1,config:{}},{id:'finish',blockType:'agent',blockVersion:1,config:{agentId:'finish'}}],edges:[{source:'seed',sourcePort:'out',target:'one-a',targetPort:'in'},{source:'seed',sourcePort:'out',target:'one-b',targetPort:'in'},{source:'one-a',sourcePort:'out',target:'join-one',targetPort:'in'},{source:'one-b',sourcePort:'out',target:'join-one',targetPort:'in'},{source:'join-one',sourcePort:'out',target:'two-a',targetPort:'in'},{source:'join-one',sourcePort:'out',target:'two-b',targetPort:'in'},{source:'two-a',sourcePort:'out',target:'join-two',targetPort:'in'},{source:'two-b',sourcePort:'out',target:'join-two',targetPort:'in'},{source:'join-two',sourcePort:'out',target:'finish',targetPort:'in'}],entryNodeId:'seed',terminalNodeId:'finish',maxStepExecutions:12},saver=new MemorySaver(),inputs=new Map(),execute=async(node,input)=>{inputs.set(node.id,input);if(node.id==='seed')return'seed';if(node.id==='one-a')return largeA;if(node.id==='one-b')return largeB;if(node.id==='two-a')return`${largeA.slice(0,-1)}2`;if(node.id==='two-b')return`${largeB.slice(0,-1)}2`;return input},config={configurable:{thread_id:'bounded-parallel'},recursionLimit:20};let graph=compileGenericStateGraph(plan,execute,saver),maxBytes=0;for(let turn=0;turn<8;turn++){await graph.invoke(turn?null:{initialInput:'start',outputs:[],executions:0},config);const state=await graph.getState(config);maxBytes=Math.max(maxBytes,Buffer.byteLength(JSON.stringify(state.values)));if(turn===2)graph=compileGenericStateGraph(plan,execute,saver);if(!state.next.length)break}const expectedOne=JSON.stringify({inputs:[{sourceNodeId:'one-a',output:largeA},{sourceNodeId:'one-b',output:largeB}]}),expectedTwo=JSON.stringify({inputs:[{sourceNodeId:'two-a',output:`${largeA.slice(0,-1)}2`},{sourceNodeId:'two-b',output:`${largeB.slice(0,-1)}2`} ]});assert.equal(inputs.get('two-a'),expectedOne);assert.equal(inputs.get('two-b'),expectedOne);assert.equal(inputs.get('finish'),expectedTwo);assert.doesNotMatch(inputs.get('finish'),/one-a|one-b/);assert.ok(maxBytes<1_000_000);const final=await graph.getState(config);assert.deepEqual(final.values.outputs.map(value=>value.nodeId),['finish'])});

test('Approval interrupts durably, performs no node call, and resumes exact text once after Runtime replacement',async()=>{const plan={planVersion:2,nodes:[{id:'a',blockType:'agent',blockVersion:1,config:{agentId:'a'}},{id:'review',blockType:'approval',blockVersion:1,config:{message:'Approve exact output?' }},{id:'b',blockType:'agent',blockVersion:1,config:{agentId:'b'}}],edges:[{source:'a',sourcePort:'out',target:'review',targetPort:'in'},{source:'review',sourcePort:'out',target:'b',targetPort:'in'}],entryNodeId:'a',terminalNodeId:'b',maxStepExecutions:3},runId=crypto.randomUUID(),fixture=gatewayFixture(),base={protocolVersion:'adt-runtime-v1',capability:'langgraph:graph',requestId:'approval-request',runId,initialInput:'byte-for-byte\n',plan,checkpointGateway:{url:'https://adt.example/checkpoints',authority:'c'.repeat(32)}},inspect=()=>advanceGenericGraph({...base,nodeGateway:{url:'https://adt.example/nodes'}},fixture.fetcher);let state=await inspect();assert.deepEqual(state.frontier.map(x=>x.nodeId),['a']);state=await advanceGenericGraph({...base,nodeGateway:{url:'https://adt.example/nodes',authorities:state.frontier.map(x=>({...x,authority:'n'.repeat(32),workflowGeneration:1,iteration:1,attempt:1}))}},fixture.fetcher);assert.equal(state.state,'approval_required');assert.deepEqual({nodeId:state.nodeId,message:state.message,text:state.text},{nodeId:'review',message:'Approve exact output?',text:'byte-for-byte\n|a'});assert.ok(state.activationId&&state.interruptId&&state.activationId.length<=256&&state.interruptId.length<=256);assert.deepEqual([...fixture.providerCalls],[['a',1]]);const stale=await advanceGenericGraph({...base,approvalResume:{requestId:crypto.randomUUID(),interruptId:'stale-interrupt',approved:true},nodeGateway:{url:'https://adt.example/nodes'}},fixture.fetcher);assert.deepEqual(stale,state);assert.deepEqual([...fixture.providerCalls],[['a',1]]);state=await advanceGenericGraph({...base,approvalResume:{requestId:crypto.randomUUID(),interruptId:state.interruptId,approved:true},nodeGateway:{url:'https://adt.example/nodes'}},fixture.fetcher);assert.equal(state.state,'admission_required');assert.deepEqual(state.frontier.map(x=>x.nodeId),['b']);state=await advanceGenericGraph({...base,nodeGateway:{url:'https://adt.example/nodes',authorities:state.frontier.map(x=>({...x,authority:'n'.repeat(32),workflowGeneration:1,iteration:1,attempt:1}))}},fixture.fetcher);assert.equal(state.state,'completed');assert.equal(state.outputText,'byte-for-byte\n|a|b');assert.deepEqual([...fixture.providerCalls],[['a',1],['b',1]]);const latest=[...fixture.checkpoints.values()].at(-1).checkpoint.channel_values;assert.equal(latest.executions,3)});

const sequentialPlan={planVersion:2,nodes:[{id:'c',blockType:'agent',blockVersion:1,config:{agentId:'c'}},{id:'a',blockType:'agent',blockVersion:1,config:{agentId:'a'}},{id:'b',blockType:'agent',blockVersion:1,config:{agentId:'b'}}],edges:[{source:'a',sourcePort:'out',target:'b',targetPort:'in'},{source:'b',sourcePort:'out',target:'c',targetPort:'in'}],entryNodeId:'a',terminalNodeId:'c',maxStepExecutions:3};

test('semantic edges drive exact sequential handoff in a linear-shaped generic graph',async()=>{
 const calls=[],graph=compileGenericStateGraph(sequentialPlan,async(node,input)=>{calls.push([node.id,input]);return `${input}\u0000${node.id}`},new MemorySaver()),config={configurable:{thread_id:'generic-sequential'}};
 for(let turn=0;turn<4;turn++)await graph.invoke(turn?null:{initialInput:'exact input\n',outputs:[],executions:0},config);
 assert.deepEqual(calls,[['a','exact input\n'],['b','exact input\n\u0000a'],['c','exact input\n\u0000a\u0000b']]);
 const snapshot=await graph.getState(config);assert.equal(snapshot.values.outputs[0].output,'exact input\n\u0000a\u0000b\u0000c');
});

function genericRequest(runId,nodeGateway={url:'https://adt.example/nodes'}){return{protocolVersion:'adt-runtime-v1',capability:'langgraph:graph',requestId:'generic-request',runId,initialInput:'initial',plan:sequentialPlan,checkpointGateway:{url:'https://adt.example/checkpoints',authority:'c'.repeat(32)},nodeGateway}}
async function admittedGenericAdvance(runId,fetcher,authorities){const inspection=await advanceGenericGraph(genericRequest(runId),fetcher);if(inspection.state!=='admission_required')return inspection;const exact=authorities??inspection.frontier.map(item=>({...item,authority:'n'.repeat(32),workflowGeneration:1,iteration:1,attempt:1}));return advanceGenericGraph(genericRequest(runId,{url:'https://adt.example/nodes',authorities:exact}),fetcher)}

test('Runtime replacement recovers checkpoints without replaying durable node success',async()=>{
 const runId=crypto.randomUUID(),fixture=gatewayFixture({loseNodeResponseAfterSuccess:true});
 await assert.rejects(admittedGenericAdvance(runId,fixture.fetcher),/graph_node_gateway_unavailable/);
 let result;for(let replacement=0;replacement<9;replacement++){try{result=await admittedGenericAdvance(runId,fixture.fetcher)}catch(error){assert.match(error.message,/graph_node_gateway_unavailable/);continue}if(result.state==='completed')break}
 assert.equal(result.state,'completed');assert.equal(result.outputText,'initial|a|b|c');assert.deepEqual([...fixture.providerCalls],[['a',1],['b',1],['c',1]]);
});

test('generic node gateway network and HTTP 503 failures escape as orchestration failures',async()=>{
 for(const failure of ['network','timeout','503']){const runId=crypto.randomUUID(),fixture=gatewayFixture(),inspection=await advanceGenericGraph(genericRequest(runId),fixture.fetcher),fetcher=async(url,init)=>{if(String(url).includes('nodes')){if(failure==='network')throw new TypeError('offline');if(failure==='timeout')throw new DOMException('timed out','TimeoutError');return Response.json({state:'failed',safeMessage:'temporary'},{status:503})}return fixture.fetcher(url,init)};await assert.rejects(admittedGenericAdvance(runId,fetcher,inspection.frontier.map(item=>({...item,authority:'n'.repeat(32),workflowGeneration:1,iteration:1,attempt:1}))),value=>{assert.equal(value.message,'graph_node_gateway_unavailable');assert.equal(value.orchestration.transportOutcome,failure==='503'?'response_received':failure==='network'?'network_error':'timeout');assert.equal(value.orchestration.httpStatus,failure==='503'?503:undefined);return true})}
});

test('generic durable node failure remains a lifecycle failure',async()=>{
 const runId=crypto.randomUUID(),fixture=gatewayFixture(),inspection=await advanceGenericGraph(genericRequest(runId),fixture.fetcher),failed=await admittedGenericAdvance(runId,async(url,init)=>String(url).includes('nodes')?Response.json({state:'failed',safeMessage:'Persisted provider failure.'},{status:422}):fixture.fetcher(url,init),inspection.frontier.map(item=>({...item,authority:'n'.repeat(32),workflowGeneration:1,iteration:1,attempt:1})));
 assert.deepEqual(failed,{state:'failed',safeMessage:'Persisted provider failure.',retryAfterMs:undefined});
});

test('generic admission rejects wrong and stale activation-scoped authority',async()=>{
 const runId=crypto.randomUUID(),fixture=gatewayFixture(),first=await advanceGenericGraph(genericRequest(runId),fixture.fetcher),wrong=first.frontier.map(item=>({...item,activationId:'wrong-activation',authority:'n'.repeat(32),workflowGeneration:1,iteration:1,attempt:1}));
 await assert.rejects(admittedGenericAdvance(runId,fixture.fetcher,wrong),/graph_node_gateway_invalid/);assert.equal(fixture.providerCalls.size,0);
 await admittedGenericAdvance(runId,fixture.fetcher);const second=await advanceGenericGraph(genericRequest(runId),fixture.fetcher),stale=first.frontier.map(item=>({...item,authority:'n'.repeat(32),workflowGeneration:1,iteration:1,attempt:1}));
 await assert.rejects(admittedGenericAdvance(runId,fixture.fetcher,stale),/graph_node_gateway_invalid/);assert.deepEqual(second.frontier.map(item=>item.nodeId),['b']);assert.deepEqual([...fixture.providerCalls],[['a',1]]);
});
