import test from 'node:test';
import assert from 'node:assert/strict';
import {MemorySaver} from '@langchain/langgraph';
import {advanceLinearGraph,compileLinearStateGraph,orderedLinearNodes,RemoteCheckpointSaver} from '../dist/langgraph.js';
const plan={nodes:[{id:'c',agentId:'c'},{id:'a',agentId:'a'},{id:'b',agentId:'b'}],edges:[{source:'a',target:'b'},{source:'b',target:'c'}],entryNodeId:'a',terminalNodeId:'c',maxStepExecutions:3};
test('semantic edges determine stable node order and exact handoff',async()=>{assert.deepEqual(orderedLinearNodes(plan).map(v=>v.id),['a','b','c']);const calls=[],graph=compileLinearStateGraph(plan,async(node,input)=>{calls.push([node.id,input]);return `${input}\u0000${node.id}`},new MemorySaver()),result=await graph.invoke({input:'exact input\n',output:'',executions:0},{configurable:{thread_id:'run-a'}});assert.deepEqual(calls,[['a','exact input\n'],['b','exact input\n\u0000a'],['c','exact input\n\u0000a\u0000b']]);assert.equal(result.output,'exact input\n\u0000a\u0000b\u0000c')});
test('remote saver rejects cross-thread access before a request',async()=>{let calls=0;const saver=new RemoteCheckpointSaver('https://adt.example/checkpoints','authority','run-a',async()=>{calls++;return Response.json({ok:true,result:null})});await assert.rejects(saver.getTuple({configurable:{thread_id:'run-b'}}),/checkpoint_authority_invalid/);assert.equal(calls,0)});
function gatewayFixture({failAfterA=false,pendingFirst=false,loseNodeResponseAfterSuccess=false}={}){const pendingSeen=new Set(),lostNodeResponses=new Set(),checkpoints=new Map(),writes=new Map(),attempts=new Map(),providerCalls=new Map();let failed=false;const tuple=id=>{const value=checkpoints.get(id);if(!value)return null;return{...value,pendingWrites:writes.get(id)??[]}},fetcher=async(url,init)=>{const body=JSON.parse(init.body);if(String(url).includes('nodes')){if(pendingFirst&&!pendingSeen.has(body.nodeId)){pendingSeen.add(body.nodeId);return Response.json({state:'pending'})}const prior=attempts.get(body.nodeId);if(prior)return Response.json({state:'completed',outputText:prior});providerCalls.set(body.nodeId,(providerCalls.get(body.nodeId)??0)+1);const output=`${body.inputText}|${body.nodeId}`;attempts.set(body.nodeId,output);if(loseNodeResponseAfterSuccess&&!lostNodeResponses.has(body.nodeId)){lostNodeResponses.add(body.nodeId);throw new TypeError('lost')}return Response.json({state:'completed',outputText:output})}const {operation,payload}=body;if(operation==='get'){const id=payload.config.configurable.checkpoint_id;const value=id?tuple(id):tuple([...checkpoints.keys()].at(-1));return Response.json({ok:true,result:value})}if(operation==='list')return Response.json({ok:true,result:[...checkpoints.keys()].reverse().map(tuple)});if(operation==='putWrites'){const id=payload.config.configurable.checkpoint_id,current=writes.get(id)??[];payload.writes.forEach(([channel,value])=>current.push([payload.taskId,channel,value]));writes.set(id,current);return Response.json({ok:true,result:null})}if(operation==='put'){const cp=payload.checkpoint;if(failAfterA&&!failed&&cp.channel_values?.output?.endsWith('|a')){failed=true;return Response.json({ok:false,error:'checkpoint_persistence_unavailable'},{status:503})}const config={configurable:{...payload.config.configurable,checkpoint_id:cp.id}},parentId=payload.config.configurable.checkpoint_id;checkpoints.set(cp.id,{config,checkpoint:cp,metadata:payload.metadata,...(parentId?{parentConfig:{configurable:{...config.configurable,checkpoint_id:parentId}}}:{})});return Response.json({ok:true,result:config})}return Response.json({ok:true,result:null})};return{fetcher,providerCalls,attempts,checkpoints,writes}}
const request=(runId,nodeGateway={url:'https://adt.example/nodes'})=>({protocolVersion:'adt-runtime-v1',capability:'langgraph:linear',requestId:'request-identifier',runId,initialInput:'initial',plan,checkpointGateway:{url:'https://adt.example/checkpoints',authority:'c'.repeat(32)},nodeGateway});
async function admittedAdvance(runId,fetcher,override={}){const inspection=await advanceLinearGraph(request(runId),fetcher);if(inspection.state!=='admission_required')return inspection;return advanceLinearGraph(request(runId,{url:'https://adt.example/nodes',authority:'n'.repeat(32),nodeId:inspection.nextNodeId,workflowGeneration:1,iteration:1,attempt:1,...override}),fetcher)}
test('fresh Runtime instances resume one bounded node at a time through the remote saver',async()=>{const runId=crypto.randomUUID(),fixture=gatewayFixture();let result;for(let replacement=0;replacement<5;replacement++){result=await admittedAdvance(runId,fixture.fetcher);if(result.state==='completed')break}assert.equal(result.state,'completed');assert.equal(result.outputText,'initial|a|b|c');assert.deepEqual([...fixture.providerCalls],[['a',1],['b',1],['c',1]]);assert.ok(fixture.checkpoints.size>=4);assert.ok(fixture.writes.size>=1)});
test('durable Agent success is reused when checkpoint advancement fails',async()=>{const runId=crypto.randomUUID(),fixture=gatewayFixture({failAfterA:true});await assert.rejects(admittedAdvance(runId,fixture.fetcher),/checkpoint_persistence_unavailable/);let result;for(let replacement=0;replacement<6;replacement++){result=await admittedAdvance(runId,fixture.fetcher);if(result.state==='completed')break}assert.equal(result.state,'completed');assert.equal(fixture.providerCalls.get('a'),1);assert.equal(fixture.attempts.get('a'),'initial|a')});

test('pending node work remains at the same checkpoint until ADT reports durable success',async()=>{const runId=crypto.randomUUID(),fixture=gatewayFixture({pendingFirst:true});let result;for(let turn=0;turn<9;turn++){result=await admittedAdvance(runId,fixture.fetcher);if(result.state==='completed')break}assert.equal(result.state,'completed');assert.deepEqual([...fixture.providerCalls],[['a',1],['b',1],['c',1]])});

test('node retry delay is bounded and returned to the durable outer orchestrator',async()=>{const runId=crypto.randomUUID(),fixture=gatewayFixture({pendingFirst:true}),result=await admittedAdvance(runId,async(url,init)=>{const response=await fixture.fetcher(url,init);if(String(url).includes('nodes')){const value=await response.json();if(value.state==='pending')return Response.json({state:'pending',retryAfterMs:12345})}return response});assert.deepEqual(result,{state:'pending',safeMessage:undefined,retryAfterMs:12345})});


test('graph-node network and HTTP 503 failures escape as orchestration failures',async()=>{for(const failure of ['network','503']){const runId=crypto.randomUUID(),fixture=gatewayFixture(),fetcher=async(url,init)=>{if(String(url).includes('nodes')){if(failure==='network')throw new TypeError('offline');return Response.json({state:'failed',safeMessage:'temporary'},{status:503})}return fixture.fetcher(url,init)};await assert.rejects(admittedAdvance(runId,fetcher),/graph_node_gateway_unavailable/)}});
test('graph-node response loss re-enters and reuses its durable success',async()=>{const runId=crypto.randomUUID(),fixture=gatewayFixture({loseNodeResponseAfterSuccess:true});let result;for(let turn=0;turn<10;turn++){try{result=await admittedAdvance(runId,fixture.fetcher)}catch(error){assert.match(error.message,/graph_node_gateway_unavailable/);continue}if(result.state==='completed')break}assert.equal(result.state,'completed');assert.deepEqual([...fixture.providerCalls],[['a',1],['b',1],['c',1]])});
test('durable node failure remains lifecycle failure while admission failure is non-retryable',async()=>{const failedRun=crypto.randomUUID(),failedFixture=gatewayFixture(),failed=await admittedAdvance(failedRun,async(url,init)=>String(url).includes('nodes')?Response.json({state:'failed',safeMessage:'Persisted provider failure.'},{status:422}):failedFixture.fetcher(url,init));assert.deepEqual(failed,{state:'failed',safeMessage:'Persisted provider failure.',retryAfterMs:undefined});const invalidRun=crypto.randomUUID(),invalidFixture=gatewayFixture();await assert.rejects(admittedAdvance(invalidRun,async(url,init)=>String(url).includes('nodes')?Response.json({state:'failed',safeMessage:'invalid'},{status:401}):invalidFixture.fetcher(url,init)),/graph_node_gateway_invalid/)});

test('exact node admission cannot execute a different checkpoint position',async()=>{const runId=crypto.randomUUID(),fixture=gatewayFixture(),first=await advanceLinearGraph(request(runId),fixture.fetcher);assert.equal(first.nextNodeId,'a');await assert.rejects(advanceLinearGraph(request(runId,{url:'https://adt.example/nodes',authority:'n'.repeat(32),nodeId:'b',workflowGeneration:1,iteration:1,attempt:1}),fixture.fetcher),/graph_node_gateway_invalid/);assert.equal(fixture.providerCalls.size,0);await admittedAdvance(runId,fixture.fetcher);const second=await advanceLinearGraph(request(runId),fixture.fetcher);assert.equal(second.nextNodeId,'b');await assert.rejects(advanceLinearGraph(request(runId,{url:'https://adt.example/nodes',authority:'n'.repeat(32),nodeId:'a',workflowGeneration:1,iteration:1,attempt:1}),fixture.fetcher),/graph_node_gateway_invalid/);assert.deepEqual([...fixture.providerCalls],[['a',1]])});

import {compileGenericStateGraph,evaluateCondition} from '../dist/langgraph.js';
const genericPlan={planVersion:2,nodes:[{id:'research',blockType:'agent',blockVersion:1,config:{agentId:'researcher'}},{id:'condition',blockType:'condition',blockVersion:1,config:{operator:'contains',value:'approved',caseSensitive:false}},{id:'accept',blockType:'agent',blockVersion:1,config:{agentId:'accept'}},{id:'revise',blockType:'agent',blockVersion:1,config:{agentId:'revise'}},{id:'finish',blockType:'agent',blockVersion:1,config:{agentId:'finish'}}],edges:[{source:'research',sourcePort:'out',target:'condition',targetPort:'in'},{source:'condition',sourcePort:'true',target:'accept',targetPort:'in'},{source:'condition',sourcePort:'false',target:'revise',targetPort:'in'},{source:'accept',sourcePort:'out',target:'finish',targetPort:'in'},{source:'revise',sourcePort:'out',target:'finish',targetPort:'in'}],entryNodeId:'research',terminalNodeId:'finish',maxStepExecutions:32};
test('bounded contains predicate is deterministic',()=>{assert.equal(evaluateCondition({operator:'contains',value:'approved',caseSensitive:false},'APPROVED\n'),true);assert.equal(evaluateCondition({operator:'contains',value:'approved',caseSensitive:true},'APPROVED\n'),false)});
test('generic graph selects true route only and preserves Condition text',async()=>{const calls=[],graph=compileGenericStateGraph(genericPlan,async(node,input)=>{calls.push([node.id,input]);return node.id==='research'?'APPROVED\n':`${input}|${node.id}`},new MemorySaver()),config={configurable:{thread_id:'generic-true'}};for(let i=0;i<4;i++)await graph.invoke(i?null:{input:'start',activeText:'start',outputs:{},executions:0},config);assert.deepEqual(calls.map(call=>call[0]),['research','accept','finish']);assert.equal(calls[1][1],'APPROVED\n');const snapshot=await graph.getState(config);assert.equal(snapshot.values.executions,4)});
test('generic graph selects false route independent of plan order',async()=>{const calls=[],plan={...genericPlan,nodes:[...genericPlan.nodes].reverse(),edges:[...genericPlan.edges].reverse()},graph=compileGenericStateGraph(plan,async(node,input)=>{calls.push(node.id);return node.id==='research'?'needs revision':input},new MemorySaver()),config={configurable:{thread_id:'generic-false'}};for(let i=0;i<4;i++)await graph.invoke(i?null:{input:'start',activeText:'start',outputs:{},executions:0},config);assert.deepEqual(calls,['research','revise','finish'])});

test('structured fan-out runs one bounded parallel frontier and Join aggregates by semantic source',async()=>{const plan={planVersion:2,nodes:[{id:'input',blockType:'agent',blockVersion:1,config:{agentId:'input'}},{id:'reviewer-a',blockType:'agent',blockVersion:1,config:{agentId:'a'}},{id:'reviewer-b',blockType:'agent',blockVersion:1,config:{agentId:'b'}},{id:'join',blockType:'join',blockVersion:1,config:{}},{id:'synthesis',blockType:'agent',blockVersion:1,config:{agentId:'s'}}],edges:[{source:'input',sourcePort:'out',target:'reviewer-a',targetPort:'in'},{source:'input',sourcePort:'out',target:'reviewer-b',targetPort:'in'},{source:'reviewer-a',sourcePort:'out',target:'join',targetPort:'in'},{source:'reviewer-b',sourcePort:'out',target:'join',targetPort:'in'},{source:'join',sourcePort:'out',target:'synthesis',targetPort:'in'}],entryNodeId:'input',terminalNodeId:'synthesis',maxStepExecutions:8},calls=[],active=new Set();let parallel=false;const graph=compileGenericStateGraph(plan,async(node,input,activationId)=>{calls.push({node:node.id,input,activationId});if(node.id.startsWith('reviewer')){active.add(node.id);await new Promise(resolve=>setTimeout(resolve,5));parallel ||= active.size===2;active.delete(node.id)}return node.id==='input'?'seed':node.id==='synthesis'?input:`${node.id}-output`},new MemorySaver()),config={configurable:{thread_id:'parallel'}};for(let turn=0;turn<4;turn++)await graph.invoke(turn?null:{initialInput:'start',outputs:[],executions:0},config);assert.equal(parallel,true);const synthesis=calls.find(value=>value.node==='synthesis');assert.equal(synthesis.input,JSON.stringify({inputs:[{sourceNodeId:'reviewer-a',output:'reviewer-a-output'},{sourceNodeId:'reviewer-b',output:'reviewer-b-output'}]}));assert.equal(calls.filter(value=>value.node.startsWith('reviewer')).length,2)});

test('controlled loop creates distinct LangGraph Agent activations and preserves prior outputs',async()=>{const plan={planVersion:2,nodes:[{id:'draft',blockType:'agent',blockVersion:1,config:{agentId:'draft'}},{id:'review',blockType:'agent',blockVersion:1,config:{agentId:'review'}},{id:'condition',blockType:'condition',blockVersion:1,config:{operator:'contains',value:'approved',caseSensitive:false}},{id:'finish',blockType:'agent',blockVersion:1,config:{agentId:'finish'}}],edges:[{source:'draft',sourcePort:'out',target:'review',targetPort:'in'},{source:'review',sourcePort:'out',target:'condition',targetPort:'in'},{source:'condition',sourcePort:'true',target:'finish',targetPort:'in'},{source:'condition',sourcePort:'false',target:'draft',targetPort:'in'}],entryNodeId:'draft',terminalNodeId:'finish',maxStepExecutions:12},draftActivations=[],reviews=[],graph=compileGenericStateGraph(plan,async(node,input,activationId)=>{if(node.id==='draft'){draftActivations.push(activationId);return `draft-${draftActivations.length}`}if(node.id==='review'){reviews.push(input);return reviews.length===1?'revise':'approved'}return input},new MemorySaver()),config={configurable:{thread_id:'loop'},recursionLimit:20};for(let turn=0;turn<8;turn++){await graph.invoke(turn?null:{initialInput:'start',outputs:[],executions:0},config);const state=await graph.getState(config);if(!state.next.length)break}assert.equal(draftActivations.length,2);assert.notEqual(draftActivations[0],draftActivations[1]);assert.deepEqual(reviews,['draft-1','draft-2'])});
