import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {callMcpTool,discoverMcpTools,MCP_LIMITS,McpFailure,validateMcpUrl} from '../dist/mcp.js';

async function fake(handler){return new Promise(resolve=>{const server=createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;const message=raw?JSON.parse(raw):{};const result=handler(message,req);res.writeHead(result.status??200,{'content-type':'application/json',...(result.headers??{})});res.end(JSON.stringify(result.body))}).listen(0,'127.0.0.1',()=>resolve({server,url:`http://127.0.0.1:${server.address().port}/mcp`}))})}
const config=url=>({url,transport:'streamable-http',allowLocalhost:true});
function protocol(message,req,{token}={}){if(token&&req.headers.authorization!==`Bearer ${token}`)return{status:401,body:{private:'do not leak'}};if(message.method==='initialize')return{body:{jsonrpc:'2.0',id:message.id,result:{protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'fake',version:'1'}}}};if(message.method==='notifications/initialized')return{status:202,body:{}};if(message.method==='tools/list')return{body:{jsonrpc:'2.0',id:message.id,result:{tools:[{name:'echo',description:'Echo input',inputSchema:{type:'object',properties:{text:{type:'string'}}}}]}}};if(message.method==='tools/call')return{body:{jsonrpc:'2.0',id:message.id,result:{content:[{type:'text',text:message.params.arguments.text}]}}};return{status:400,body:{}}}

test('Streamable HTTP initializes, discovers and calls a frozen tool with no authentication',async t=>{const f=await fake((m,r)=>protocol(m,r));t.after(()=>new Promise(resolve=>f.server.close(resolve)));const tools=await discoverMcpTools(config(f.url));assert.deepEqual(tools,[{name:'echo',description:'Echo input',inputSchema:{type:'object',properties:{text:{type:'string'}}}}]);const result=await callMcpTool(config(f.url),tools[0],{text:'hello'});assert.equal(result.content[0].text,'hello')});
test('bearer authentication is invocation-only and failures are safe',async t=>{const secret='mcp-private-token',f=await fake((m,r)=>protocol(m,r,{token:secret}));t.after(()=>new Promise(resolve=>f.server.close(resolve)));assert.equal((await discoverMcpTools(config(f.url),secret))[0].name,'echo');await assert.rejects(discoverMcpTools(config(f.url),'wrong'),error=>error instanceof McpFailure&&!JSON.stringify(error).includes(secret)&&!JSON.stringify(error).includes('do not leak'))});
test('MCP bounds and destination policy fail closed',async()=>{await assert.rejects(validateMcpUrl('http://127.0.0.1/mcp'),/configuration_invalid/);await assert.rejects(validateMcpUrl('https://127.0.0.1/mcp'),/configuration_invalid/);await assert.rejects(discoverMcpTools({url:'https://example.com',transport:'stdio'}),/configuration_invalid/);const huge={name:'x',inputSchema:{value:'x'.repeat(MCP_LIMITS.schemaBytes)}};await assert.rejects(callMcpTool({url:'https://example.com',transport:'streamable-http'},huge,{}),/malformed_response/)});
test('catalogue count, schema, result and redirect bounds return safe errors',async t=>{const excessive=await fake((m,r)=>{const base=protocol(m,r);if(m.method==='tools/list')base.body.result.tools=Array.from({length:MCP_LIMITS.tools+1},(_,i)=>({name:`t${i}`,inputSchema:{type:'object'}}));return base});t.after(()=>new Promise(resolve=>excessive.server.close(resolve)));await assert.rejects(discoverMcpTools(config(excessive.url)),error=>error.category==='response_too_large');const malformed=await fake((m,r)=>{const base=protocol(m,r);if(m.method==='tools/list')base.body.result.tools=[{name:'bad',inputSchema:'not-schema'}];return base});t.after(()=>new Promise(resolve=>malformed.server.close(resolve)));await assert.rejects(discoverMcpTools(config(malformed.url)),error=>error.category==='malformed_response');const oversized=await fake((m,r)=>{const base=protocol(m,r);if(m.method==='tools/call')base.body.result={content:[{type:'text',text:'x'.repeat(MCP_LIMITS.resultBytes)}]};return base});t.after(()=>new Promise(resolve=>oversized.server.close(resolve)));await assert.rejects(callMcpTool(config(oversized.url),{name:'echo',inputSchema:{type:'object'}},{}),error=>error.category==='connection_unavailable'&&error.ambiguous);let requests=0;const redirectFetch=async(_url,init)=>{const message=JSON.parse(init.body);if(message.method==='initialize'){requests++;return new Response(null,{status:302,headers:{location:'http://169.254.169.254/latest'}})}throw new Error('must not follow')};await assert.rejects(discoverMcpTools({url:'http://localhost/mcp',transport:'streamable-http',allowLocalhost:true},undefined,redirectFetch),error=>error.category==='configuration_invalid');assert.equal(requests,1)});
test('a tools/call transport failure is reported ambiguous and is not retried',async()=>{let calls=0;const fetcher=async(_url,init)=>{const message=JSON.parse(init.body);if(message.method==='initialize')return Response.json({jsonrpc:'2.0',id:message.id,result:{protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'fake',version:'1'}}});if(message.method==='notifications/initialized')return new Response(null,{status:202});calls++;throw new Error('private remote failure')};await assert.rejects(callMcpTool({url:'http://localhost/mcp',transport:'streamable-http',allowLocalhost:true},{name:'echo',inputSchema:{type:'object'}},{},undefined,fetcher),error=>error.ambiguous===true&&!error.safeMessage.includes('private'));assert.equal(calls,1)});
