import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {callMcpTool,createPinnedLookup,discoverMcpTools,isForbiddenMcpAddress,MCP_LIMITS,McpFailure,validateMcpUrl} from '../dist/mcp.js';

async function fake(handler){return new Promise(resolve=>{const server=createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;const message=raw?JSON.parse(raw):{};const result=handler(message,req);res.writeHead(result.status??200,{'content-type':'application/json',...(result.headers??{})});res.end(result.raw??JSON.stringify(result.body))}).listen(0,'127.0.0.1',()=>resolve({server,url:`http://127.0.0.1:${server.address().port}/mcp`}))})}
const config=url=>({url,transport:'streamable-http',allowLocalhost:true});
function protocol(message,req,{token}={}){if(token&&req.headers.authorization!==`Bearer ${token}`)return{status:401,body:{private:'do not leak'}};if(message.method==='initialize')return{body:{jsonrpc:'2.0',id:message.id,result:{protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'fake',version:'1'}}}};if(message.method==='notifications/initialized')return{status:202,body:{}};if(message.method==='tools/list')return{body:{jsonrpc:'2.0',id:message.id,result:{tools:[{name:'echo',description:'Echo input',inputSchema:{type:'object',properties:{text:{type:'string'}}}}]}}};if(message.method==='tools/call')return{body:{jsonrpc:'2.0',id:message.id,result:{content:[{type:'text',text:message.params.arguments.text}]}}};return{status:400,body:{}}}

test('Streamable HTTP initializes, discovers and calls a frozen tool with no authentication',async t=>{const f=await fake((m,r)=>protocol(m,r));t.after(()=>new Promise(resolve=>f.server.close(resolve)));const tools=await discoverMcpTools(config(f.url));assert.deepEqual(tools,[{name:'echo',description:'Echo input',inputSchema:{type:'object',properties:{text:{type:'string'}}}}]);const result=await callMcpTool(config(f.url),tools[0],{text:'hello'});assert.equal(result.content[0].text,'hello')});

test('bearer authentication is invocation-only and failures are safe',async t=>{const secret='mcp-private-token',f=await fake((m,r)=>protocol(m,r,{token:secret}));t.after(()=>new Promise(resolve=>f.server.close(resolve)));assert.equal((await discoverMcpTools(config(f.url),secret))[0].name,'echo');await assert.rejects(discoverMcpTools(config(f.url),'wrong'),error=>error instanceof McpFailure&&!JSON.stringify(error).includes(secret)&&!JSON.stringify(error).includes('do not leak'))});

test('same-origin redirects retain bearer auth and redirect chains are bounded',async()=>{const token='redirect-secret';let requests=0;const fetcher=async(url,init)=>{requests++;assert.equal(new URL(url).origin,'http://localhost');assert.equal(new Headers(init.headers).get('authorization'),`Bearer ${token}`);const message=JSON.parse(init.body);if(requests<=2)return new Response(null,{status:307,headers:{location:`/hop-${requests}`}});if(message.method==='initialize')return Response.json({jsonrpc:'2.0',id:message.id,result:{protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'fake',version:'1'}}});if(message.method==='notifications/initialized')return new Response(null,{status:202});return Response.json({jsonrpc:'2.0',id:message.id,result:{tools:[]}})};assert.deepEqual(await discoverMcpTools(config('http://localhost/mcp'),token,{fetch:fetcher}),[]);assert.ok(requests>=4);requests=0;const endless=async(_url,init)=>{requests++;assert.equal(new Headers(init.headers).get('authorization'),`Bearer ${token}`);return new Response(null,{status:307,headers:{location:`/hop-${requests}`}})};await assert.rejects(discoverMcpTools(config('http://localhost/mcp'),token,{fetch:endless}),error=>error.category==='connection_unavailable');assert.equal(requests,MCP_LIMITS.redirects+1)});

test('cross-origin redirects are rejected before credentials or requests reach the target',async()=>{const token='must-not-cross-origin';let sourceRequests=0,targetRequests=0,targetToken;const target=await fake((_m,req)=>{targetRequests++;targetToken=req.headers.authorization;return{status:500,body:{}}});const source=await fake(()=>{sourceRequests++;return{status:307,headers:{location:target.url},body:{}}});try{await assert.rejects(discoverMcpTools(config(source.url),token),error=>error.category==='configuration_invalid'&&!JSON.stringify(error).includes(token));assert.equal(sourceRequests,1);assert.equal(targetRequests,0);assert.equal(targetToken,undefined)}finally{await new Promise(resolve=>source.server.close(resolve));await new Promise(resolve=>target.server.close(resolve))}});

test('destination policy covers representative IPv4 and IPv6 non-public ranges',async()=>{for(const address of ['0.0.0.0','10.1.2.3','100.64.1.2','127.0.0.1','169.254.169.254','172.16.0.1','192.168.1.1','224.0.0.1','240.0.0.1','::','::1','::ffff:127.0.0.1','fc00::1','fe80::1','ff02::1','2001:db8::1'])assert.equal(isForbiddenMcpAddress(address),true,address);for(const address of ['8.8.8.8','1.1.1.1','2606:4700:4700::1111','2001:4860:4860::8888'])assert.equal(isForbiddenMcpAddress(address),false,address);await assert.rejects(validateMcpUrl('https://private.test/mcp',false,async()=>[{address:'10.0.0.1',family:4}]),/configuration_invalid/)});

test('validated DNS answers are pinned for connection lookup rather than resolved again',async()=>{let resolutions=0;const resolver=async()=>{resolutions++;return[{address:resolutions===1?'8.8.8.8':'127.0.0.1',family:4}]},validated=await resolver(),lookup=createPinnedLookup('rebind.test',validated),connected=await new Promise((resolve,reject)=>lookup('rebind.test',{family:0},(error,address,family)=>error?reject(error):resolve({address,family})));assert.deepEqual(connected,{address:'8.8.8.8',family:4});assert.equal(resolutions,1);await assert.rejects(new Promise((resolve,reject)=>lookup('different.test',{family:0},(error,address)=>error?reject(error):resolve(address))),error=>error.code==='EPERM')});

test('MCP bounds and destination policy fail closed',async()=>{await assert.rejects(validateMcpUrl('http://127.0.0.1/mcp'),/configuration_invalid/);await assert.rejects(validateMcpUrl('https://127.0.0.1/mcp'),/configuration_invalid/);await assert.rejects(discoverMcpTools({url:'https://example.com',transport:'stdio'}),/configuration_invalid/);const huge={name:'x',inputSchema:{value:'x'.repeat(MCP_LIMITS.schemaBytes)}};await assert.rejects(callMcpTool({url:'https://example.com',transport:'streamable-http'},huge,{}),error=>error.category==='malformed_response'&&!error.ambiguous)});

test('catalogue and result limits retain precise non-ambiguous failures',async t=>{const excessive=await fake((m,r)=>{const base=protocol(m,r);if(m.method==='tools/list')base.body.result.tools=Array.from({length:MCP_LIMITS.tools+1},(_,i)=>({name:`t${i}`,inputSchema:{type:'object'}}));return base});t.after(()=>new Promise(resolve=>excessive.server.close(resolve)));await assert.rejects(discoverMcpTools(config(excessive.url)),error=>error.category==='response_too_large'&&!error.ambiguous);const malformed=await fake((m,r)=>{const base=protocol(m,r);if(m.method==='tools/list')base.body.result.tools=[{name:'bad',inputSchema:'not-schema'}];return base});t.after(()=>new Promise(resolve=>malformed.server.close(resolve)));await assert.rejects(discoverMcpTools(config(malformed.url)),error=>error.category==='malformed_response'&&!error.ambiguous);const oversized=await fake((m,r)=>{const base=protocol(m,r);if(m.method==='tools/call')base.body.result={content:[{type:'text',text:'x'.repeat(MCP_LIMITS.resultBytes)}]};return base});t.after(()=>new Promise(resolve=>oversized.server.close(resolve)));await assert.rejects(callMcpTool(config(oversized.url),{name:'echo',inputSchema:{type:'object'}},{}),error=>error.category==='response_too_large'&&error.ambiguous===false)});

test('a tools/call transport failure after dispatch is ambiguous and is not retried',async()=>{let calls=0;const fetcher=async(_url,init)=>{const message=JSON.parse(init.body);if(message.method==='initialize')return Response.json({jsonrpc:'2.0',id:message.id,result:{protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'fake',version:'1'}}});if(message.method==='notifications/initialized')return new Response(null,{status:202});calls++;throw new Error('private remote failure')};await assert.rejects(callMcpTool(config('http://localhost/mcp'),{name:'echo',inputSchema:{type:'object'}},{},undefined,{fetch:fetcher}),error=>error.category==='connection_unavailable'&&error.ambiguous===true&&!error.safeMessage.includes('private'));assert.equal(calls,1)});
