import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Miniflare} from 'miniflare';
import {AgentRuntimeRegistry} from '../../lib/agent-runtime.ts';
import {D1LangGraphCheckpointStore,issueCheckpointAuthority,issueGraphNodeAuthority,parseCheckpointOperation,verifyGraphNodeAuthority} from '../../lib/langgraph-checkpoints.ts';
import {D1WorkflowRunStorage} from '../../lib/workflow-d1-storage.ts';
import {executeDurableGraphNodeTurn} from '../../lib/workflow-durable-driver.ts';
import {agentDefinitionSchema,compileWorkflowV2ExecutionPlan,executableWorkflow,workflowDefinitionV2Schema} from '../../lib/workflow-definitions.ts';
import {executeLangGraphWorkflow,waitForApprovalWake} from '../../lib/workflow-worker-runtime.ts';
import {D1WorkflowApprovalStore} from '../../lib/workflow-approvals.ts';
import {MAX_WORKFLOW_RUN_MS} from '../../lib/workflow-durable-driver.ts';
import {newLangGraphWorkflowRun} from '../../lib/workflow-storage.ts';
import {advanceGenericGraph} from '../dist/langgraph.js';

const secret='pass-c-integrated-authority-secret-000000000',connection={key:'deterministic-test',name:'Integrated test',adapter:'deterministic-test',enabled:true,capabilities:{asynchronous:false,cancellation:false}};
const agent=id=>agentDefinitionSchema.parse({schemaVersion:1,id:`agent-${id}`,name:id,description:'',status:'draft',masterPrompt:id,connectionKey:connection.key});
const edge=(source,target,sourcePort)=>({id:`${source}-${sourcePort??'out'}-${target}`,source,...(sourcePort?{sourcePort}:{}),target});

async function database(t){const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:{DB:crypto.randomUUID()}}),db=await mf.getD1Database('DB');t.after(()=>mf.dispose());for(const name of ['0003_create_workflow_runs.sql','0005_create_workflow_codex_environments.sql','0007_add_provider_transport_diagnostics.sql','0008_add_provider_transport_reason.sql','0010_add_workflow_run_repository_context.sql','0011_add_langgraph_workflow_runs.sql','0012_add_graph_activation_identity.sql','0013_add_workflow_approvals.sql']){const sql=await readFile(new URL(`../../migrations/${name}`,import.meta.url),'utf8');await db.batch(sql.split(';').map(value=>value.trim()).filter(Boolean).map(value=>db.prepare(value)))}return db}

async function harness(t,{definition,agents,initialInput,provider}){
 const db=await database(t),storage=new D1WorkflowRunStorage(db),plan=compileWorkflowV2ExecutionPlan(definition,agents),run=newLangGraphWorkflowRun({id:crypto.randomUUID(),workflow:definition,compatibilityWorkflow:executableWorkflow(definition,agents),executionPlan:plan,revision:'immutable-sha',agents,connections:[connection],initialInput});await storage.createRun(run);
 const checkpoints=new D1LangGraphCheckpointStore(db),runtimes=new AgentRuntimeRegistry([{kind:'deterministic-test',start:provider.start,check:provider.check??(async()=>{throw Error('unused')}),cancel:async()=> 'unsupported'}]),scopes=[],checkpointRequestBytes=[],sleeps=[];
 const checkpointAuthority=()=>issueCheckpointAuthority(run.id,secret),nodeAuthority=async scope=>{const authority=await issueGraphNodeAuthority(scope,secret);scopes.push({...scope,authority});return authority};
 async function fetcher(url,init){const raw=String(init.body),body=JSON.parse(raw);if(String(url).includes('checkpoints')){checkpointRequestBytes.push(Buffer.byteLength(raw));try{return Response.json({ok:true,result:await checkpoints.execute(run.id,parseCheckpointOperation(body))})}catch(error){return Response.json({ok:false,error:error.message},{status:422})}}const authority=String(init.headers.authorization??'').replace(/^Bearer /,'');const scope={runId:body.runId,nodeId:body.nodeId,activationId:body.activationId,workflowGeneration:body.workflowGeneration,iteration:body.iteration,attempt:body.attempt};if(!await verifyGraphNodeAuthority(authority,scope,secret))return Response.json({state:'failed',safeMessage:'invalid'},{status:401});const result=await executeDurableGraphNodeTurn({runId:run.id,nodeId:body.nodeId,activationId:body.activationId,inputText:body.inputText,storage,runtimes,resolveConnection:async()=>({...connection,credential:'secret'})});return Response.json(result,{status:result.state==='failed'?422:200})}
 let runtimeConstructions=0;const remote={advanceLangGraph:request=>{runtimeConstructions++;return advanceGenericGraph({protocolVersion:'adt-runtime-v1',capability:'langgraph:graph',requestId:`pass-c-${runtimeConstructions}`,...request},fetcher)}},step={do:async(_name,...args)=>args.at(-1)(),sleep:async(name)=>{sleeps.push(name)}};
 const clock={value:Date.parse(run.createdAt)},approvals=new D1WorkflowApprovalStore(db,()=>new Date(clock.value).toISOString());return{run,plan,storage,checkpoints,approvals,clock,scopes,sleeps,checkpointRequestBytes,get runtimeConstructions(){return runtimeConstructions},executeWithApproval:(approval)=>executeLangGraphWorkflow({runId:run.id,storage,remote,step,checkpointUrl:'https://adt.example/checkpoints',nodeUrl:'https://adt.example/nodes',checkpointAuthority,nodeAuthority,now:()=>clock.value,suspendedMs:()=>approvals.suspendedMs(run.id),...(approval?{approval}: {})}),execute:(waitForEvent)=>executeLangGraphWorkflow({runId:run.id,storage,remote,step,checkpointUrl:'https://adt.example/checkpoints',nodeUrl:'https://adt.example/nodes',checkpointAuthority,nodeAuthority,now:()=>clock.value,suspendedMs:()=>approvals.suspendedMs(run.id),...(waitForEvent?{approval:{wait:(result,generation)=>waitForApprovalWake({runId:run.id,generation,result,storage,approvals,waitForEvent})}}:{})}),fetcher};
}

const conditionDefinition=()=>workflowDefinitionV2Schema.parse({schemaVersion:2,id:'integrated-condition',name:'Integrated Condition',description:'',status:'draft',nodes:[{id:'entry',blockType:'agent',blockVersion:1,config:{agentId:'agent-entry'}},{id:'condition',blockType:'condition',blockVersion:1,config:{operator:'contains',value:'approved',caseSensitive:false}},{id:'true-agent',blockType:'agent',blockVersion:1,config:{agentId:'agent-true'}},{id:'false-agent',blockType:'agent',blockVersion:1,config:{agentId:'agent-false'}},{id:'finish',blockType:'agent',blockVersion:1,config:{agentId:'agent-finish'}}],edges:[edge('entry','condition'),edge('condition','true-agent','true'),edge('condition','false-agent','false'),edge('true-agent','finish'),edge('false-agent','finish')],limits:{maxStepExecutions:8}});

test('combined production boundary executes only the immutable selected Condition route and resumes checkpoints',async t=>{for(const [label,entryOutput,selected,unselected] of [['true','exact APPROVED text\n','true-agent','false-agent'],['false','exact revision text\n','false-agent','true-agent']])await t.test(label,async t=>{const definition=conditionDefinition(),agents=['entry','true','false','finish'].map(agent),starts=[],inputs=new Map(),fixture=await harness(t,{definition,agents,initialInput:'run input',provider:{start:async call=>{starts.push(call.stepId);inputs.set(call.stepId,call.inputText);return{state:'completed',outputText:call.stepId==='entry'?entryOutput:call.inputText}}}});definition.nodes.find(node=>node.id==='condition').config.value=label==='true'?'never-match':'revision';const result=await fixture.execute(),detail=await fixture.storage.getRun(fixture.run.id);assert.equal(result.status,'succeeded');assert.deepEqual(starts,['entry',selected,'finish']);assert.equal(inputs.get(selected),entryOutput);assert.equal(starts.includes(unselected),false);assert.equal(detail.attempts.some(value=>value.stepId===unselected),false);assert.equal(detail.attempts.some(value=>value.stepId==='condition'),false);assert.ok(fixture.runtimeConstructions>3);assert.equal(detail.attempts.every(value=>value.attempt===1),true)})});

const loopDefinition=maxStepExecutions=>workflowDefinitionV2Schema.parse({schemaVersion:2,id:'integrated-loop',name:'Integrated loop',description:'',status:'draft',nodes:[{id:'draft',blockType:'agent',blockVersion:1,config:{agentId:'agent-draft'}},{id:'review',blockType:'agent',blockVersion:1,config:{agentId:'agent-review'}},{id:'condition',blockType:'condition',blockVersion:1,config:{operator:'contains',value:'approved',caseSensitive:false}},{id:'finish',blockType:'agent',blockVersion:1,config:{agentId:'agent-finish'}}],edges:[edge('draft','review'),edge('review','condition'),edge('condition','finish','true'),edge('condition','draft','false')],limits:{maxStepExecutions}});

test('combined production boundary preserves loop visits, provider retries, and exact activation authority',async t=>{const starts=[],fixture=await harness(t,{definition:loopDefinition(12),agents:['draft','review','finish'].map(agent),initialInput:'start',provider:{start:async call=>{starts.push([call.stepId,call.iteration,call.attempt]);if(call.stepId==='review'&&call.iteration===1&&call.attempt===1)throw Object.assign(Error('temporary'),{category:'provider_unavailable',safeMessage:'Temporary.',retryable:true});if(call.stepId==='review')return{state:'completed',outputText:call.iteration===1?'revise':'approved'};return{state:'completed',outputText:call.stepId==='draft'?`draft-${call.iteration}`:call.inputText}}}}),result=await fixture.execute(),detail=await fixture.storage.getRun(fixture.run.id),drafts=detail.attempts.filter(value=>value.stepId==='draft'),reviews=detail.attempts.filter(value=>value.stepId==='review');assert.equal(result.status,'succeeded');assert.deepEqual(drafts.map(value=>[value.iteration,value.attempt]),[[1,1],[2,1]]);assert.notEqual(drafts[0].graphActivationId,drafts[1].graphActivationId);assert.deepEqual(reviews.map(value=>[value.iteration,value.attempt]),[[1,1],[1,2],[2,1]]);assert.equal(starts.filter(([node])=>node==='draft').length,2);assert.ok(fixture.runtimeConstructions>6);const early=fixture.scopes.find(value=>value.nodeId==='draft'&&value.iteration===1),later=fixture.scopes.find(value=>value.nodeId==='draft'&&value.iteration===2),response=await fixture.fetcher('https://adt.example/nodes',{headers:{authorization:`Bearer ${early.authority}`},body:JSON.stringify({...later,inputText:'draft-1'})});assert.equal(response.status,401);assert.equal((await fixture.storage.getRun(fixture.run.id)).attempts.filter(value=>value.stepId==='draft').length,2)});

test('combined production boundary enforces the semantic execution limit before further admission',async t=>{const starts=[],fixture=await harness(t,{definition:loopDefinition(3),agents:['draft','review','finish'].map(agent),initialInput:'start',provider:{start:async call=>{starts.push(call.stepId);return{state:'completed',outputText:call.stepId==='review'?'revise':call.inputText}}}}),result=await fixture.execute(),detail=await fixture.storage.getRun(fixture.run.id);assert.equal(result.status,'failed');assert.equal(detail.run.failureCode,'internal_error');assert.equal(detail.run.failureMessage,'The workflow execution limit was reached.');assert.deepEqual(starts,['draft','review']);assert.deepEqual(detail.attempts.map(value=>value.stepId),['draft','review']);assert.equal(fixture.scopes.length,2);assert.equal(fixture.sleeps.length,0)});

test('real checkpoint transport remains bounded across consecutive large parallel regions',async t=>{const largeA='a'.repeat(120_000),largeB='b'.repeat(120_000),nodes=['seed','one-a','one-b','bridge','two-a','two-b','finish'].map(id=>({id,blockType:'agent',blockVersion:1,config:{agentId:`agent-${id}`}})),definition=workflowDefinitionV2Schema.parse({schemaVersion:2,id:'integrated-parallel',name:'Integrated parallel',description:'',status:'draft',nodes:[...nodes.slice(0,3),{id:'join-one',blockType:'join',blockVersion:1,config:{}},nodes[3],...nodes.slice(4,6),{id:'join-two',blockType:'join',blockVersion:1,config:{}},nodes[6]],edges:[edge('seed','one-a'),edge('seed','one-b'),edge('one-a','join-one'),edge('one-b','join-one'),edge('join-one','bridge'),edge('bridge','two-a'),edge('bridge','two-b'),edge('two-a','join-two'),edge('two-b','join-two'),edge('join-two','finish')],limits:{maxStepExecutions:13}}),inputs=new Map(),fixture=await harness(t,{definition,agents:['seed','one-a','one-b','bridge','two-a','two-b','finish'].map(agent),initialInput:'start',provider:{start:async call=>{inputs.set(call.stepId,call.inputText);if(call.stepId==='seed')return{state:'completed',outputText:'seed'};if(call.stepId==='one-a')return{state:'completed',outputText:largeA};if(call.stepId==='one-b')return{state:'completed',outputText:largeB};if(call.stepId==='bridge')return{state:'completed',outputText:call.inputText};if(call.stepId==='two-a')return{state:'completed',outputText:`${largeA.slice(0,-1)}2`};if(call.stepId==='two-b')return{state:'completed',outputText:`${largeB.slice(0,-1)}2`};return{state:'completed',outputText:call.inputText}}}}),result=await fixture.execute(),expectedOne=JSON.stringify({inputs:[{sourceNodeId:'one-a',output:largeA},{sourceNodeId:'one-b',output:largeB}]}),expectedTwo=JSON.stringify({inputs:[{sourceNodeId:'two-a',output:`${largeA.slice(0,-1)}2`},{sourceNodeId:'two-b',output:`${largeB.slice(0,-1)}2`}]}),latest=await fixture.checkpoints.execute(fixture.run.id,{operation:'get',threadId:fixture.run.id,payload:{config:{configurable:{thread_id:fixture.run.id}}}});assert.equal(result.status,'succeeded');assert.equal(inputs.get('two-a'),expectedOne);assert.equal(inputs.get('two-b'),expectedOne);assert.equal(inputs.get('finish'),expectedTwo);assert.doesNotMatch(inputs.get('finish'),/one-a|one-b/);assert.ok(Math.max(...fixture.checkpointRequestBytes)<1_000_000);assert.equal(inputs.get('finish').length,expectedTwo.length);assert.deepEqual(latest.checkpoint.channel_values.outputs.map(value=>value.nodeId),['finish']);assert.ok(fixture.runtimeConstructions>8)});

const approvalDefinition=()=>workflowDefinitionV2Schema.parse({schemaVersion:2,id:'integrated-approval',name:'Integrated approval',description:'',status:'draft',nodes:[{id:'agent-a',blockType:'agent',blockVersion:1,config:{agentId:'agent-a'}},{id:'review',blockType:'approval',blockVersion:1,config:{message:'Approve exact A output?'}},{id:'agent-b',blockType:'agent',blockVersion:1,config:{agentId:'agent-b'}}],edges:[edge('agent-a','review'),edge('review','agent-b')],limits:{maxStepExecutions:3}});
test('Phase 14 survives replacement and a long human wait without replaying Agent A',async t=>{const starts=[],inputs=new Map(),fixture=await harness(t,{definition:approvalDefinition(),agents:['a','b'].map(agent),initialInput:'initial bytes\n',provider:{start:async call=>{starts.push(call.stepId);inputs.set(call.stepId,call.inputText);return{state:'completed',outputText:call.stepId==='agent-a'?'A exact output\n\0':call.inputText}}}});let wake,waitEntered;const entered=new Promise(resolve=>waitEntered=resolve),event=new Promise(resolve=>wake=resolve),execution=fixture.execute(async()=>{waitEntered();return event});await entered;let detail=await fixture.storage.getRun(fixture.run.id),approval=await fixture.approvals.active(fixture.run.id);assert.equal(detail.run.status,'waiting_approval');assert.equal(approval.message,'Approve exact A output?');assert.equal(approval.reviewText,'A exact output\n\0');assert.deepEqual(starts,['agent-a']);assert.equal(detail.attempts.some(x=>x.stepId==='review'),false);assert.equal(detail.attempts.some(x=>x.stepId==='agent-b'),false);assert.ok((await fixture.checkpoints.execute(fixture.run.id,{operation:'get',threadId:fixture.run.id,payload:{config:{configurable:{thread_id:fixture.run.id}}}})).checkpoint);fixture.clock.value+=MAX_WORKFLOW_RUN_MS+86_400_000;await fixture.approvals.approve(fixture.run.id,approval.requestId);wake({requestId:approval.requestId});const result=await execution;detail=await fixture.storage.getRun(fixture.run.id);assert.equal(result.status,'succeeded');assert.equal(detail.run.status,'succeeded');assert.deepEqual(starts,['agent-a','agent-b']);assert.equal(inputs.get('agent-b'),'A exact output\n\0');assert.equal(detail.attempts.filter(x=>x.stepId==='agent-a').length,1);assert.equal(detail.attempts.filter(x=>x.stepId==='agent-b').length,1);assert.equal(detail.attempts.some(x=>x.stepId==='review'),false);assert.ok(fixture.runtimeConstructions>=4)});
test('Phase 14 cancellation wakes Approval and never admits Agent B',async t=>{const starts=[],fixture=await harness(t,{definition:approvalDefinition(),agents:['a','b'].map(agent),initialInput:'cancel input',provider:{start:async call=>{starts.push(call.stepId);return{state:'completed',outputText:'A output'}}}});let wake,waitEntered;const entered=new Promise(resolve=>waitEntered=resolve),event=new Promise(resolve=>wake=resolve),execution=fixture.execute(async()=>{waitEntered();return event});await entered;const approval=await fixture.approvals.active(fixture.run.id);assert.deepEqual(starts,['agent-a']);await fixture.storage.requestCancellation(fixture.run.id);wake({requestId:approval.requestId});const result=await execution,detail=await fixture.storage.getRun(fixture.run.id);assert.equal(result.status,'cancelled');assert.equal(detail.run.status,'cancelled');assert.deepEqual(starts,['agent-a']);assert.equal(detail.attempts.some(x=>x.stepId==='agent-b'),false);await assert.rejects(fixture.approvals.approve(fixture.run.id,approval.requestId),/approval_not_pending/)});
test('Phase 14 reconstructs consumed resume identity after outer Workflow invocation loss',async t=>{const starts=[],fixture=await harness(t,{definition:approvalDefinition(),agents:['a','b'].map(agent),initialInput:'outer restart',provider:{start:async call=>{starts.push(call.stepId);return{state:'completed',outputText:call.stepId==='agent-a'?'durable A':call.inputText}}}});let observed;const first=fixture.executeWithApproval({wait:async(result,generation)=>{const decision=await waitForApprovalWake({runId:fixture.run.id,generation,result,storage:fixture.storage,approvals:fixture.approvals,waitForEvent:async()=>{const approval=await fixture.approvals.active(fixture.run.id);await fixture.approvals.approve(fixture.run.id,approval.requestId)}});observed=decision;throw new Error('simulated outer invocation loss')}});await assert.rejects(first,/simulated outer invocation loss/);const consumed=await fixture.approvals.get(observed.requestId),pausedCheckpoint=await fixture.checkpoints.execute(fixture.run.id,{operation:'get',threadId:fixture.run.id,payload:{config:{configurable:{thread_id:fixture.run.id}}}});assert.ok(consumed.consumedAt);assert.equal(consumed.interruptId,observed.interruptId);assert.ok(pausedCheckpoint.checkpoint);assert.deepEqual(starts,['agent-a']);const result=await fixture.execute(async()=>{throw new Error('already consumed decision must not wait')});assert.equal(result.status,'succeeded');assert.deepEqual(starts,['agent-a','agent-b']);assert.equal((await fixture.storage.getRun(fixture.run.id)).attempts.filter(x=>x.stepId==='agent-b').length,1)});
