import test from 'node:test';import {createServer as createHttpServer} from 'node:http';import assert from 'node:assert/strict';import {generateKeyPairSync,createPublicKey,webcrypto} from 'node:crypto';
import {Agent,ModelRefusalError,ModelTimeoutError,Runner} from '@openai/agents';import {ScriptedModel,assistantMessage,functionCall} from '@openai/agents/testing';import OpenAI from 'openai';
import {createRuntimeServer,runtimeBuildRevision,RUNTIME_INBOUND_REQUEST_TIMEOUT_MS,RUNTIME_HEADERS_TIMEOUT_MS,RUNTIME_EXECUTION_RESPONSE_TIMEOUT_MS} from '../dist/server.js';import {executeOpenAIAgents,MAX_TURNS,MODEL_TIMEOUT_MS} from '../dist/openai-agents.js';import {LANGGRAPH_EXECUTE_PATH} from '../dist/langgraph.js';import {AUTH_WINDOW_MS,EXECUTE_PATH,MAX_NONCES,PROTOCOL_VERSION,READINESS_PATH,SECURITY_TEST_PATH,ReplayCache,sha256,signature} from '../dist/protocol.js';
const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048,publicKeyEncoding:{type:'spki',format:'pem'},privateKeyEncoding:{type:'pkcs8',format:'pem'}}),publicDer=createPublicKey(publicKey).export({type:'spki',format:'der'}),keyId=sha256(publicDer),auth='a'.repeat(48);
const request={protocolVersion:PROTOCOL_VERSION,capability:'openai-agents',requestId:'request-identifier-1',idempotencyKey:'run:step:1:1',agentName:'Agent',instructions:'Exact prompt',input:'Exact input',model:'gpt-5',options:{reasoningEffort:'high',verbosity:'low',maxOutputTokens:321}};
async function wrap(credential='provider-secret',id=keyId,aadValue=`${PROTOCOL_VERSION}:openai-agents:${request.idempotencyKey}`){const key=await webcrypto.subtle.importKey('spki',publicDer,{name:'RSA-OAEP',hash:'SHA-256'},false,['encrypt']),content=await webcrypto.subtle.generateKey({name:'AES-GCM',length:256},true,['encrypt']),raw=await webcrypto.subtle.exportKey('raw',content),iv=webcrypto.getRandomValues(new Uint8Array(12)),aad=new TextEncoder().encode(aadValue),cipher=await webcrypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:aad,tagLength:128},content,new TextEncoder().encode(credential)),wrapped=await webcrypto.subtle.encrypt({name:'RSA-OAEP'},key,raw),b=x=>Buffer.from(x).toString('base64url');return{version:1,keyId:id,algorithm:'RSA-OAEP-256+A256GCM',wrappedKey:b(wrapped),nonce:b(iv),ciphertext:b(cipher)}}
function headers(method,path,body,nonce='abcdefghijklmnop'){const timestamp=String(Date.now()),digest=sha256(body);return{'x-adt-protocol':PROTOCOL_VERSION,'x-adt-timestamp':timestamp,'x-adt-nonce':nonce,'x-adt-content-sha256':digest,'x-adt-signature':signature(auth,method,path,timestamp,nonce,digest),'content-type':'application/json'}}
async function fixtureWith(extra={}){const observed={},model=new ScriptedModel([[assistantMessage('bounded output')]]),runtime=await createRuntimeServer({host:'127.0.0.1',port:0,authSecret:auth,privateKeyPem:privateKey,revision:'revision-test',...extra,factories:{client:c=>{observed.client=c;return new OpenAI(c)},provider:c=>{observed.provider=c;return{getModel:async()=>model,close:async()=>{observed.closed=true}}},runner:c=>{observed.runner=c;return new Runner(c)},agent:c=>{observed.agent=c;return new Agent(c)},...extra.factories}});await runtime.listen();const address=runtime.server.address(),base=`http://127.0.0.1:${address.port}`;return{runtime,base,observed,model}}
async function fixture(){return fixtureWith()}
test('image-owned build revision takes precedence while local development retains an explicit fallback',()=>{assert.equal(runtimeBuildRevision({ADT_RUNTIME_REVISION:'operator-stale-secret'},()=> 'built-sha\n'),'built-sha');assert.equal(runtimeBuildRevision({ADT_RUNTIME_REVISION:'local-revision'},()=>{throw new Error('no image file')}),'local-revision');assert.equal(runtimeBuildRevision({},()=>{throw new Error('no image file')}),'development')});
test('official SDK boundary preserves isolated hardened invocation settings',async()=>{const observed={},model=new ScriptedModel([[assistantMessage('  exact SDK output  ')]]);const output=await executeOpenAIAgents({...request,credential:await wrap()},'one-secret',{client:c=>{observed.client=c;return new OpenAI(c)},provider:c=>({getModel:async()=>model,close:async()=>{observed.closed=true}}),runner:c=>{observed.runner=c;return new Runner(c)},agent:c=>{observed.agent=c;return new Agent(c)}});assert.equal(output,'  exact SDK output  ');assert.deepEqual(observed.client,{apiKey:'one-secret',maxRetries:0});assert.equal(observed.runner.tracingDisabled,true);assert.deepEqual(observed.agent.modelSettings,{store:false,parallelToolCalls:false,timeoutMs:30000,maxTokens:321,reasoning:{effort:'high'},text:{verbosity:'low'}});assert.equal(MAX_TURNS,6);assert.equal(MODEL_TIMEOUT_MS,30000);const custom={};await executeOpenAIAgents({...request,executionTimeoutMs:120000,credential:await wrap()},'one-secret',{client:c=>new OpenAI(c),provider:()=>({}),runner:()=>({run:async()=>({finalOutput:'ok'})}),agent:c=>{custom.settings=c.modelSettings;return {}}});assert.equal(custom.settings.timeoutMs,120000);assert.equal(observed.closed,true)});
test('authenticated encrypted HTTP execution succeeds without plaintext credential transport',async t=>{const f=await fixture();t.after(()=>f.runtime.close());const empty='',ready=await fetch(f.base+READINESS_PATH,{method:'GET',headers:headers('GET',READINESS_PATH,empty,'readiness-nonce-1')}),readiness=await ready.json();assert.equal(readiness.protocolVersion,PROTOCOL_VERSION);assert.equal(readiness.runtimeRevision,'revision-test');assert.ok(readiness.capabilities.includes('mcp:streamable-http:discover'));assert.ok(readiness.capabilities.includes('mcp:streamable-http:call'));assert.equal(readiness.credentialWrappingKeyId,keyId);const payload={...request,credential:await wrap()},body=JSON.stringify(payload);assert.doesNotMatch(body,/provider-secret/);const response=await fetch(f.base+EXECUTE_PATH,{method:'POST',headers:headers('POST',EXECUTE_PATH,body,'execution-nonce-1'),body});assert.equal(response.status,200);assert.equal((await response.json()).result.outputText,'bounded output');assert.equal(f.observed.client.apiKey,'provider-secret');assert.equal(f.observed.client.maxRetries,0)});
test('retired linear LangGraph capability is rejected before checkpoint or node work',async t=>{const f=await fixture();t.after(()=>f.runtime.close());const payload={protocolVersion:PROTOCOL_VERSION,capability:'langgraph:linear',requestId:'retired-linear',runId:crypto.randomUUID(),initialInput:'input',plan:{nodes:[{id:'a',agentId:'agent-a'}],edges:[],entryNodeId:'a',terminalNodeId:'a',maxStepExecutions:1},checkpointGateway:{url:'https://unreachable.invalid/checkpoints',authority:'c'.repeat(32)},nodeGateway:{url:'https://unreachable.invalid/nodes'}},body=JSON.stringify(payload),response=await fetch(f.base+LANGGRAPH_EXECUTE_PATH,{method:'POST',headers:headers('POST',LANGGRAPH_EXECUTE_PATH,body,'retired-linear-nonce'),body}),wire=await response.json();assert.equal(response.status,400);assert.equal(wire.error.code,'invalid_request');assert.equal(wire.error.providerExecutionEntered,false)});
test('authentication binds body, method, path and rejects missing, stale, invalid, and replayed metadata',async t=>{const f=await fixture();t.after(()=>f.runtime.close());const body=JSON.stringify({...request,credential:await wrap()});for(const [name,init] of [['missing',{}],['tampered',{headers:headers('POST',EXECUTE_PATH,body),body:body+' '}],['path',{headers:headers('POST','/wrong',body),body}],['method',{method:'PUT',headers:headers('POST',EXECUTE_PATH,body),body}]]){const response=await fetch(f.base+EXECUTE_PATH,{method:'POST',body,...init});assert.equal(response.status,401,name)}const stale=headers('POST',EXECUTE_PATH,body,'stale-nonce-value');stale['x-adt-timestamp']=String(Date.now()-AUTH_WINDOW_MS-1);stale['x-adt-signature']=signature(auth,'POST',EXECUTE_PATH,stale['x-adt-timestamp'],stale['x-adt-nonce'],stale['x-adt-content-sha256']);assert.equal((await fetch(f.base+EXECUTE_PATH,{method:'POST',headers:stale,body})).status,401);const replay=headers('POST',EXECUTE_PATH,body,'replay-nonce-value');assert.equal((await fetch(f.base+EXECUTE_PATH,{method:'POST',headers:replay,body})).status,200);assert.equal((await fetch(f.base+EXECUTE_PATH,{method:'POST',headers:replay,body})).status,401)});
test('replay cache is bounded and credential envelope rejects the wrong key identity',async t=>{const cache=new ReplayCache(3);for(let i=0;i<20;i++)assert.equal(cache.accept(`nonce-${i}`),true);assert.equal(cache.size,3);assert.equal(MAX_NONCES,10000);const f=await fixture();t.after(()=>f.runtime.close());const body=JSON.stringify({...request,credential:await wrap('private-provider-text','wrong-key')});const response=await fetch(f.base+EXECUTE_PATH,{method:'POST',headers:headers('POST',EXECUTE_PATH,body,'wrong-key-nonce-1'),body}),text=await response.text();assert.equal(response.status,400);assert.doesNotMatch(text,/private-provider-text|provider-secret/)});
test('SDK failures are safe, trusted classifications and provider retry is disabled',async()=>{for(const [error,category] of [[new ModelTimeoutError({timeoutMs:30000}),'provider_timeout'],[new ModelRefusalError('private refusal'),'provider_rejected'],[Object.assign(new Error('private'),{status:401}),'authentication_failed'],[Object.assign(new Error('private'),{status:403}),'permission_denied'],[Object.assign(new Error('private'),{status:429}),'rate_limited'],[Object.assign(new Error('private'),{status:503}),'provider_unavailable'],[Object.assign(new Error('private'),{category:'authentication_failed'}),'internal_error']])await assert.rejects(executeOpenAIAgents({...request,credential:await wrap()},'secret',{provider:()=>({getModel:async()=>new ScriptedModel([{type:'error',error}])})}),e=>e.category===category&&e.retryable===false&&!e.safeMessage.includes('private'));let calls=0;await assert.rejects(executeOpenAIAgents({...request,credential:await wrap()},'secret',{client:c=>new OpenAI({...c,fetch:async()=>{calls++;return Response.json({error:{message:'private'}},{status:429})}})}));assert.equal(calls,1)});
test('wrapping fingerprint is derived from the loaded private key and logs stay structured and secret free',async t=>{const events=[],f=await fixtureWith({logger:event=>events.push(event)});t.after(()=>f.runtime.close());assert.equal(f.runtime.keyId,keyId);const body=JSON.stringify({...request,instructions:'sensitive-prompt-fixture',input:'sensitive-input-fixture',credential:await wrap('sensitive-credential-fixture','wrong-key')});const response=await fetch(f.base+EXECUTE_PATH,{method:'POST',headers:headers('POST',EXECUTE_PATH,body,'logging-nonce-value'),body});assert.equal(response.status,400);assert.ok(events.some(event=>event.event==='runtime_request_rejected'&&event.result==='credential_invalid'&&event.providerExecutionEntered===false));const logged=JSON.stringify(events);assert.doesNotMatch(logged,/sensitive-prompt-fixture|sensitive-input-fixture|sensitive-credential-fixture|wrong-key|wrappedKey|ciphertext|x-adt-signature/)});
test('UTF-8 output bounds accept the byte limit and reject multibyte overflow safely',async()=>{for(const [output,category] of [['é'.repeat(131072),undefined],['é'.repeat(131073),'output_too_large']]){const model=new ScriptedModel([[assistantMessage(output)]]),call=executeOpenAIAgents({...request,credential:await wrap()},'secret',{provider:()=>({getModel:async()=>model}),runner:c=>new Runner(c),agent:c=>new Agent(c)});if(category)await assert.rejects(call,error=>error.category===category&&error.retryable===false);else assert.equal(Buffer.byteLength(await call,'utf8'),262144)}});

test('Agents SDK tool call receives bounded gateway content and continues to final text',async()=>{let gateway;const model=new ScriptedModel([[functionCall('artifact_search',{query:'design'},{callId:'call-safe-1'})],[assistantMessage('Used bounded artifact content.')]]),output=await executeOpenAIAgents({...request,tools:['artifact_search'],toolGateway:{url:'https://adt.example/tool',authority:'signed-authority'},credential:await wrap()},'secret',{provider:()=>({getModel:async()=>model}),runner:c=>new Runner(c),agent:c=>new Agent(c),fetcher:async(url,init)=>{gateway={url,headers:init.headers,body:JSON.parse(init.body)};return Response.json({results:[{id:'design',body:'bounded content'}],truncated:false})}});assert.equal(output,'Used bounded artifact content.');assert.equal(gateway.url,'https://adt.example/tool');assert.equal(gateway.headers.authorization,'Bearer signed-authority');assert.deepEqual(gateway.body.arguments,{query:'design'});assert.equal(gateway.body.callId,'call-safe-1');assert.equal(JSON.stringify(gateway).includes('provider-secret'),false)});

test('generic tool security gate preserves the provider call ID around Artifact Search execution',async()=>{const order=[],model=new ScriptedModel([[functionCall('artifact_search',{query:'design'},{callId:'call-gated'})],[assistantMessage('done')]]);await executeOpenAIAgents({...request,tools:['artifact_search'],toolGateway:{url:'https://adt.example/tool',authority:'authority'},credential:await wrap()},'secret',{provider:()=>({getModel:async()=>model}),runner:c=>new Runner(c),agent:c=>new Agent(c),securityGate:{authorize:async value=>{order.push(`gate:${value.name}:${value.callId}`)},completed:async(value,result)=>order.push(`complete:${value.callId}:${result}`)},fetcher:async()=>{order.push('execute');return Response.json({results:[]})}});assert.deepEqual(order,['gate:artifact_search:call-gated','execute','complete:call-gated:{"results":[]}'])});

test('execution-path diagnostic is authenticated, probes every callback, and never enters provider execution',async t=>{const events=[],f=await fixtureWith({logger:event=>events.push(event)});t.after(()=>f.runtime.close());const {EXECUTION_PATH_DIAGNOSTIC_PATH,EXECUTION_PATH_DIAGNOSTIC_CAPABILITY}=await import('../dist/execution-path-diagnostic.js'),gateway=await new Promise(resolve=>{const server=createHttpServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;assert.deepEqual(Object.keys(JSON.parse(raw)).sort(),['operation','target']);assert.equal(req.headers.authorization,'Bearer narrow-token');res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({ok:true,authorityAccepted:true,backendAvailable:true}))}).listen(0,'127.0.0.1',()=>resolve(server))});t.after(()=>new Promise(resolve=>gateway.close(resolve)));const address=gateway.address(),payload={protocolVersion:PROTOCOL_VERSION,capability:EXECUTION_PATH_DIAGNOSTIC_CAPABILITY,requestId:'diagnostic-request',targets:{checkpoint:{url:`http://127.0.0.1:${address.port}/actual-checkpoint`,authority:'narrow-token'},'graph-node':{url:`http://127.0.0.1:${address.port}/actual-graph-node`,authority:'narrow-token'}}},body=JSON.stringify(payload);assert.equal((await fetch(f.base+EXECUTION_PATH_DIAGNOSTIC_PATH,{method:'POST',body})).status,401);const response=await fetch(f.base+EXECUTION_PATH_DIAGNOSTIC_PATH,{method:'POST',headers:headers('POST',EXECUTION_PATH_DIAGNOSTIC_PATH,body,'diagnostic-nonce'),body}),wire=await response.json();assert.equal(response.status,200);assert.equal(wire.results[0].backendAvailable,true);assert.equal(f.observed.client,undefined);assert.ok(events.every(event=>event.providerExecutionEntered!==true));assert.doesNotMatch(JSON.stringify(events),/narrow-token|authorization|actual-checkpoint/)});

test('Runtime keeps inbound protections narrow and applies a fixed response-lifecycle socket ceiling',async t=>{const f=await fixture();t.after(()=>f.runtime.close());assert.equal(f.runtime.server.requestTimeout,RUNTIME_INBOUND_REQUEST_TIMEOUT_MS);assert.equal(f.runtime.server.headersTimeout,RUNTIME_HEADERS_TIMEOUT_MS);assert.equal(f.runtime.server.timeout,RUNTIME_EXECUTION_RESPONSE_TIMEOUT_MS);assert.equal(RUNTIME_INBOUND_REQUEST_TIMEOUT_MS,60000);assert.equal(RUNTIME_HEADERS_TIMEOUT_MS,10000);assert.equal(RUNTIME_EXECUTION_RESPONSE_TIMEOUT_MS,150000);assert.ok(RUNTIME_EXECUTION_RESPONSE_TIMEOUT_MS>126000)});

test('socket response timeout governs active execution independently of inbound request parsing',async t=>{const slow=await fixtureWith({factories:{runner:()=>({run:async()=>{await new Promise(resolve=>setTimeout(resolve,40));return{finalOutput:'slow'}}}),agent:()=>({})}});t.after(()=>slow.runtime.close());slow.runtime.server.timeout=10;const payload={...request,executionTimeoutMs:120000,credential:await wrap()},body=JSON.stringify(payload);await assert.rejects(fetch(slow.base+EXECUTE_PATH,{method:'POST',headers:headers('POST',EXECUTE_PATH,body,'slow-timeout-nonce'),body}));assert.equal(slow.runtime.server.requestTimeout,60000);const allowed=await fixtureWith({factories:{runner:()=>({run:async()=>{await new Promise(resolve=>setTimeout(resolve,20));return{finalOutput:'allowed'}}}),agent:()=>({})}});t.after(()=>allowed.runtime.close());const allowedBody=JSON.stringify({...request,executionTimeoutMs:120000,credential:await wrap()});const response=await fetch(allowed.base+EXECUTE_PATH,{method:'POST',headers:headers('POST',EXECUTE_PATH,allowedBody,'allowed-timeout-nonce'),body:allowedBody});assert.equal(response.status,200);assert.equal((await response.json()).result.outputText,'allowed');assert.equal(allowed.runtime.server.timeout,150000)});

function securityLifecycle(outcome,{readiness=true,shutdown=async()=>{}}={}){const events=[],state={inits:0,events};const verdict={eventId:'event',sessionId:'session',madCode:outcome==='deny'?'M0':'',policy:{mode:1,policyM0:outcome==='deny',policyM2:false,policyM3:false,policyM4:false},hitl:null},handler={handleChatModelStart:async(_model,input,turn)=>events.push(['model-start',turn,input]),handleLLMEnd:async(data,turn)=>events.push(['model-end',turn,data]),handleLLMError:async()=>{},handleToolStart:async(_tool,_args,_run,_parent,metadata)=>events.push(['tool-start',metadata.tool_call_id]),handleToolEnd:async()=>events.push(['tool-end']),handleToolError:async()=>events.push(['tool-error'])},client={waitForPolicyReady:async()=>typeof readiness==='function'?readiness():readiness,loginAcked:()=>true,policyActive:()=>true,waitForToolCallVerdict:async callId=>{events.push(['verdict',callId]);return outcome==='unavailable'?null:verdict}};return{state,runtime:{init:async options=>{state.inits++;state.init=options},shutdown,getHandler:()=>handler,getWebSocketClient:()=>client}}}
async function securedBody(outcomeRequest=request){return JSON.stringify({...outcomeRequest,tools:['artifact_search'],toolGateway:{url:'https://adt.example/tool',authority:'tool-authority'},credential:await wrap('provider-secret',keyId,`${PROTOCOL_VERSION}:openai-agents:${outcomeRequest.idempotencyKey}`),runtimeSecurity:{provider:'adrian',profileId:'production',endpointUrl:'wss://security.example/events',decisionTimeoutMs:250,credential:await wrap('adrian-secret',keyId,`${PROTOCOL_VERSION}:openai-agents:${outcomeRequest.idempotencyKey}:security:adrian`)}})}


async function securityTestBody(id="security-profile-test"){return JSON.stringify({protocolVersion:PROTOCOL_VERSION,capability:"security:adrian:test",requestId:id,profileId:"production",endpointUrl:"wss://security.example/events",decisionTimeoutMs:250,credential:await wrap("adrian-secret",keyId,`${PROTOCOL_VERSION}:security:adrian:test:${id}`)})}

test("Security Profile Test requires the same handler, client, and positive policy readiness as secured execution",async t=>{
 const cases=[
  {name:"ready",handler:true,client:true,policy:true,status:200},
  {name:"missing-handler",handler:false,client:true,policy:true,status:503,code:"execution_failed"},
  {name:"missing-client",handler:true,client:false,policy:true,status:503,code:"execution_failed"},
  {name:"policy-unavailable",handler:true,client:true,policy:false,status:503,code:"adrian_policy_unavailable"},
 ];
 for(const item of cases)await t.test(item.name,async()=>{let providers=0,tools=0;const runtime={init:async()=>{},shutdown:async()=>{},getHandler:()=>item.handler?{}:null,getWebSocketClient:()=>item.client?{waitForPolicyReady:async()=>item.policy}:null},f=await fixtureWith({adrianRuntime:runtime,factories:{provider:()=>{providers++;return{}},fetcher:async()=>{tools++;return Response.json({})}}});t.after(()=>f.runtime.close());const body=await securityTestBody(`test-${item.name}`),response=await fetch(f.base+SECURITY_TEST_PATH,{method:"POST",headers:headers("POST",SECURITY_TEST_PATH,body,`${item.name}-nonce-value`),body}),wire=await response.json();assert.equal(response.status,item.status);if(item.status===200)assert.equal(wire.result.state,"ready");else{assert.equal(wire.error.category,"security_unavailable");assert.equal(wire.error.code,item.code);assert.equal(wire.error.providerExecutionEntered,false)}assert.equal(providers,0);assert.equal(tools,0);assert.doesNotMatch(JSON.stringify(wire),/adrian-secret|wrappedKey|ciphertext|private/)});
});
test('secured Runtime HTTP path correlates model events and exact verdict before one tool side effect',async t=>{for(const outcome of ['allow','deny','unavailable'])await t.test(outcome,async()=>{let tools=0,providers=0;const lifecycle=securityLifecycle(outcome),model=new ScriptedModel([[functionCall('artifact_search',{query:'design'},{callId:'provider-call-secure'})],[assistantMessage('secured final')]]),f=await fixtureWith({adrianRuntime:lifecycle.runtime,factories:{provider:()=>{providers++;return{getModel:async()=>model}},fetcher:async()=>{tools++;return Response.json({results:[]})}}});t.after(()=>f.runtime.close());const body=await securedBody(),response=await fetch(f.base+EXECUTE_PATH,{method:'POST',headers:headers('POST',EXECUTE_PATH,body,`secure-${outcome}-nonce`),body}),wire=await response.json();assert.equal(providers,1);assert.equal(lifecycle.state.inits,1);assert.ok(lifecycle.state.events.some(x=>x[0]==='model-start'));assert.equal(lifecycle.state.events.find(x=>x[0]==='model-end')[2].toolCalls[0].id,'provider-call-secure');assert.ok(lifecycle.state.events.some(x=>x[0]==='verdict'&&x[1]==='provider-call-secure'));assert.equal(tools,outcome==='allow'?1:0);if(outcome==='allow'){assert.equal(response.status,200);assert.equal(wire.result.outputText,'secured final')}else{assert.equal(wire.error.category,outcome==='deny'?'security_denied':'security_unavailable');assert.equal(wire.error.providerExecutionEntered,true)}})});

test('secured Runtime readiness failure blocks provider and tool execution',async t=>{for(const readiness of [false,()=>{throw Error('disconnect')}])await t.test(typeof readiness==='function'?'throws':'false',async()=>{let providers=0,tools=0;const lifecycle=securityLifecycle('allow',{readiness}),f=await fixtureWith({adrianRuntime:lifecycle.runtime,factories:{provider:()=>{providers++;return{getModel:async()=>new ScriptedModel([[assistantMessage('must not run')]])}},fetcher:async()=>{tools++;return Response.json({})}}});t.after(()=>f.runtime.close());const body=await securedBody(),response=await fetch(f.base+EXECUTE_PATH,{method:'POST',headers:headers('POST',EXECUTE_PATH,body,`readiness-${typeof readiness}-nonce`),body}),wire=await response.json();assert.equal(wire.error.category,'security_unavailable');assert.equal(wire.error.providerExecutionEntered,false);assert.equal(providers,0);assert.equal(tools,0)})});

test('concurrent secured HTTP requests fail closed without queueing and release the lease',async t=>{let releaseReady;const hold=new Promise(resolve=>releaseReady=resolve),lifecycle=securityLifecycle('allow',{readiness:async()=>{await hold;return true}}),model=()=>new ScriptedModel([[assistantMessage('done')]]);let providers=0;const f=await fixtureWith({adrianRuntime:lifecycle.runtime,factories:{provider:()=>{providers++;return{getModel:async()=>model()}}}});t.after(()=>f.runtime.close());const send=async(id,secured=true)=>{const changed={...request,requestId:id,idempotencyKey:`run:${id}:1:1`},body=secured?await securedBody(changed):JSON.stringify({...changed,credential:await wrap('provider-secret',keyId,`${PROTOCOL_VERSION}:openai-agents:${changed.idempotencyKey}`)});return fetch(f.base+EXECUTE_PATH,{method:'POST',headers:headers('POST',EXECUTE_PATH,body,`${id}-nonce-value`),body})};const a=send('lease-a');while(lifecycle.state.inits<1)await new Promise(resolve=>setTimeout(resolve,1));const b=await send('lease-b'),bWire=await b.json();assert.equal(bWire.error.category,'security_unavailable');assert.equal(lifecycle.state.inits,1);assert.equal(providers,0);const unsecured=await send('plain',false);assert.equal(unsecured.status,200);assert.equal(providers,1);releaseReady();assert.equal((await a).status,200);const c=await send('lease-c');assert.equal(c.status,200);assert.equal(lifecycle.state.inits,2);assert.equal(providers,3)});

test('protected HTTP lease releases after provider and Adrian shutdown failures',async t=>{
 await t.test('shutdown failure',async()=>{const lifecycle=securityLifecycle('allow',{shutdown:async()=>{throw Error('shutdown failed')}}),f=await fixtureWith({adrianRuntime:lifecycle.runtime,factories:{provider:()=>({getModel:async()=>new ScriptedModel([[assistantMessage('done')]])})}});t.after(()=>f.runtime.close());for(const id of ['shutdown-a','shutdown-b']){const changed={...request,requestId:id,idempotencyKey:`run:${id}:1:1`},body=await securedBody(changed);assert.equal((await fetch(f.base+EXECUTE_PATH,{method:'POST',headers:headers('POST',EXECUTE_PATH,body,`${id}-nonce-value`),body})).status,200)}assert.equal(lifecycle.state.inits,2)});
 await t.test('provider failure',async()=>{const lifecycle=securityLifecycle('allow'),f=await fixtureWith({adrianRuntime:lifecycle.runtime,factories:{runner:()=>({run:async()=>{throw Error('provider failed')}}),agent:()=>({})}});t.after(()=>f.runtime.close());for(const id of ['failure-a','failure-b']){const changed={...request,requestId:id,idempotencyKey:`run:${id}:1:1`},body=await securedBody(changed),response=await fetch(f.base+EXECUTE_PATH,{method:'POST',headers:headers('POST',EXECUTE_PATH,body,`${id}-nonce-value`),body});assert.equal(response.status,422)}assert.equal(lifecycle.state.inits,2)})
});
