import { AppHeader } from "@/components/AppHeader";
import { CatalogueRefreshControls } from "@/components/CatalogueRefresh";
import { DiagnosticStatusBadge } from "@/components/DiagnosticStatusBadge";
import { LocalizedTime } from "@/components/LocalizedTime";
import { requireDiagnosticsAccess } from "@/lib/auth";
import { collectSafeRunnerDiagnostics } from "@/lib/codex-runner-diagnostics";
import { deploymentMetadata, getDeploymentDisplayModel } from "@/lib/deployment-metadata";
import { catalogueRefreshAvailability } from "@/lib/diagnostics-model";
import { authorizationStatusPresentation, cacheStatusPresentation, configurationStatusPresentation, installationStatusPresentation, permissionStatusPresentation, repositoryMatchPresentation, revisionStatusPresentation, validationStatusPresentation } from "@/lib/diagnostics-presentation";
import { deriveOperationalDomains, operationalContributors, operationalOverall, runnerDiagnosticChecks, runtimeDiagnosticChecks, type DiagnosticCheck, type DiagnosticDomain } from "@/lib/operational-diagnostics";
import { generateRepositoryDiagnostics } from "@/lib/repository-diagnostics";
import { diagnoseADTRuntime } from "@/lib/workflow-services";

export const dynamic = "force-dynamic";

function Check({ check }: { check: DiagnosticCheck }) { return <div id={check.id} className="scroll-mt-4 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><div className="flex flex-wrap items-center justify-between gap-2"><b>{check.label}</b><DiagnosticStatusBadge presentation={check.status} /></div>{check.value ? <p className="mt-1 break-all font-mono text-xs text-slate-600 dark:text-slate-300">{check.value}</p> : null}{check.status.description ? <p className="mt-1 text-xs text-slate-600 dark:text-slate-300">{check.status.description}</p> : null}{check.guidance ? <p className="mt-1 text-xs font-semibold">{check.guidance}</p> : null}</div>; }
function Domain({ domain, description, children }: { domain: DiagnosticDomain; description: string; children?: React.ReactNode }) { const badge = domain.state === "healthy" ? { label: "Healthy", tone: "positive" as const } : domain.state === "failed" ? { label: "Needs attention", tone: "negative" as const } : domain.state === "not-configured" ? { label: "Not configured", tone: "neutral" as const } : { label: "Degraded", tone: "warning" as const }; return <section id={domain.key} aria-labelledby={`${domain.key}-heading`} className="scroll-mt-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-soft dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-2"><h2 id={`${domain.key}-heading`} className="text-xl font-black">{domain.title}</h2><DiagnosticStatusBadge presentation={badge} /></div><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{description}</p>{children}</section>; }
function Card({ title, children, id }: { title: string; children: React.ReactNode; id?: string }) { return <section id={id} className="scroll-mt-4 rounded-xl border border-slate-200 p-4 dark:border-slate-700"><h3 className="font-black">{title}</h3><div className="mt-2 space-y-2 text-sm">{children}</div></section>; }
function Status({ label, presentation }: { label: string; presentation: Parameters<typeof DiagnosticStatusBadge>[0]["presentation"] }) { return <p className="flex flex-wrap items-center gap-2"><b>{label}:</b><DiagnosticStatusBadge presentation={presentation} />{presentation.description ? <span className="text-xs text-slate-600 dark:text-slate-300">{presentation.description}</span> : null}</p>; }

export default async function DiagnosticsPage() {
  const session = await requireDiagnosticsAccess();
  const [repositoryResult, runtimeResult, runnerResult] = await Promise.allSettled([generateRepositoryDiagnostics(session), diagnoseADTRuntime(), collectSafeRunnerDiagnostics()]);
  const repository = repositoryResult.status === "fulfilled" ? repositoryResult.value : null;
  const runtime = runtimeResult.status === "fulfilled" ? runtimeResult.value : { configured: true, reachable: false, authenticationAccepted: null, protocolCompatible: false, capabilityAvailable: false, graphCapabilityAvailable: false, wrappingKeyMatches: false, elapsedMs: 0 };
  const runner = runnerResult.status === "fulfilled" ? runnerResult.value : { connection: { state: "unavailable" as const, label: "Runner unavailable" }, capabilities: { state: "unavailable" as const, reason: "unknown" as const }, authentication: { state: "unavailable" as const }, control: { state: "unavailable" as const }, environments: { state: "unavailable" as const }, jobs: { state: "unavailable" as const }, authEnvironment: { state: "unavailable" as const } };
  const domains = deriveOperationalDomains(repository, runtime, runner, Boolean(deploymentMetadata));
  const byKey = Object.fromEntries(domains.map(domain => [domain.key, domain])) as Record<DiagnosticDomain["key"], DiagnosticDomain>;
  const overall = operationalOverall(domains), contributors = operationalContributors(domains);
  const refreshAvailability = repository ? catalogueRefreshAvailability(repository) : { available: false as const, reason: "configuration_invalid" as const };
  const deployed = deploymentMetadata ? getDeploymentDisplayModel(deploymentMetadata) : null;
  return <><AppHeader login={session.login} currentPath="/diagnostics" /><main className="mx-auto min-h-screen max-w-6xl px-4 py-6 sm:px-6">
    <p className="text-sm font-bold uppercase tracking-[.25em] text-sky-700 dark:text-orange-300">Protected operations</p><h1 className="text-3xl font-black">Diagnostics</h1>
    <nav aria-label="Diagnostic domains" className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-sm font-semibold">{domains.map(domain => <a className="underline underline-offset-2" href={`#${domain.key}`} key={domain.key}>{domain.title}</a>)}</nav>
    <section aria-labelledby="overall-heading" className="mt-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-soft dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-center gap-2"><h2 id="overall-heading" className="text-xl font-black">Overall health</h2><DiagnosticStatusBadge presentation={overall.status} /></div><p className="mt-2 text-sm">{overall.status.description}</p>{contributors.contributors.length ? <div className="mt-4"><h3 className="font-bold">Needs attention</h3><ul className="mt-1 list-disc space-y-1 pl-5 text-sm">{contributors.contributors.map(item => <li key={item.id}><a className="underline underline-offset-2" href={item.href}>{item.message}</a></li>)}</ul>{contributors.omittedCount ? <p className="mt-2 text-sm">And {contributors.omittedCount} more diagnostic {contributors.omittedCount === 1 ? "check" : "checks"}.</p> : null}</div> : null}<p className="mt-4 text-xs text-slate-500">Generated <LocalizedTime value={repository?.generatedAt ?? new Date().toISOString()} /></p></section>
    <div className="mt-6 space-y-6">
      <Domain domain={byKey["authentication-access"]} description="Session, GitHub repository authorisation, App installation, permissions, and authentication configuration.">
        {repository ? <div className="mt-4 grid gap-4 md:grid-cols-2"><Card title="Signed-in identity / session" id="session"><Status label="Session" presentation={{ label: "Valid", tone: "positive" }} /><p><b>GitHub login:</b> @{repository.identity.login}</p><p><b>GitHub ID:</b> {repository.identity.githubId}</p></Card><Card title="Repository authorisation" id="authorization"><Status label="Stored" presentation={authorizationStatusPresentation(repository.authorization.storedState)} /><p>Last checked <LocalizedTime value={repository.authorization.lastCheckedAt} /></p><div id="repository-match"><Status label="Configured repository" presentation={repositoryMatchPresentation(repository.authorization.repositoryMatches)} /></div><Status label="Live" presentation={authorizationStatusPresentation(repository.authorization.liveState)} /></Card><Card title="GitHub App" id="installation"><Status label="Installation" presentation={installationStatusPresentation(repository.installation.state)} /><p><b>Repository ID:</b> {repository.installation.repositoryId ?? "unknown"}</p><p><b>Installation ID:</b> {repository.installation.installationId ?? "unknown"}</p></Card><Card title="Effective permissions" id="permissions"><Status label="Contents read" presentation={permissionStatusPresentation(repository.permissions.contentsRead)} /><div id="permissions-write"><Status label="Contents write" presentation={permissionStatusPresentation(repository.permissions.contentsWrite)} /></div>{repository.permissions.checkedAt ? <p>Checked <LocalizedTime value={repository.permissions.checkedAt} /></p> : null}</Card><Card title="Authentication configuration" id="authentication-configuration">{[["github-app-configuration", "GitHub App configuration", ["GITHUB_APP_ID", "GITHUB_APP_CLIENT_ID", "GITHUB_APP_CLIENT_SECRET", "GITHUB_APP_PRIVATE_KEY"]], ["session-configuration", "Session configuration", ["SESSION_SECRET"]], ["token-encryption-configuration", "Token-encryption configuration", ["GITHUB_TOKEN_ENCRYPTION_KEY"]]].map(([id, label, names]) => { const states = (names as string[]).map(name => repository.configuration.authSecrets[name]); const state = states.includes("invalid") ? "invalid" : states.includes("missing") ? "missing" : "configured"; return <div id={id as string} key={id as string}><Status label={label as string} presentation={configurationStatusPresentation(state)} /></div>; })}</Card></div> : <div className="mt-4"><Check check={byKey["authentication-access"].checks[0]} /></div>}
      </Domain>
      <Domain domain={byKey["artifact-library"]} description="Repository → Revision → Catalogue/cache → Content validation.">
        {repository ? <div className="mt-4 grid gap-4 md:grid-cols-2"><Card title="Artifact repository" id="artifact-repository"><Status label="Backend" presentation={repository.configuration.backend === "invalid" ? { label: "Invalid", tone: "negative" } : { label: "Configured", tone: "positive" }} /><p><b>Repository:</b> {repository.configuration.owner ?? "—"}/{repository.configuration.repository ?? "—"}</p><p><b>Branch:</b> {repository.configuration.branch}</p><p><b>Artifact root:</b> {repository.configuration.artifactRoot}</p></Card><Card title="Repository revision" id="repository-revision"><Status label="Revision" presentation={revisionStatusPresentation(repository.repositoryRevision.state)} /><p className="font-mono">{repository.repositoryRevision.value?.slice(0, 12) ?? "unknown"}</p></Card><Card title="Catalogue health" id="catalogue-cache"><div id="cache-binding"><Status label="Cache binding" presentation={configurationStatusPresentation(repository.configuration.cacheBinding)} /></div><Status label="Catalogue" presentation={cacheStatusPresentation(repository.cache.state)} /><p>Artifacts: {repository.cache.artifactCount ?? "unknown"} · Age: {repository.cache.ageSeconds ?? "unknown"}s</p><p>Cache revision: <span className="font-mono">{repository.cache.revision?.slice(0, 12) ?? "unknown"}</span></p><p>Current revision match: {repository.cache.currentRevisionMatches === true ? "Yes" : repository.cache.currentRevisionMatches === false ? "No" : "Unknown"}</p><CatalogueRefreshControls availability={refreshAvailability} /></Card><Card title="Artifact validation" id="artifact-validation"><Status label="Validation" presentation={validationStatusPresentation(repository.validation.state)} /><p>Valid: {repository.validation.validCount ?? "unknown"} · Invalid: {repository.validation.invalidCount ?? "unknown"}</p>{repository.validation.errors?.map((error, index) => <p key={`${error.path}-${index}`}><code>{error.path}</code>: {error.message}</p>)}{repository.validation.omittedErrorCount ? <p>{repository.validation.omittedErrorCount} additional validation errors omitted.</p> : null}</Card></div> : <div className="mt-4"><Check check={byKey["artifact-library"].checks[0]} /></div>}
      </Domain>
      <Domain domain={byKey["application-control-plane"]} description="Safe identity for the Cloudflare-hosted ADT application; no write or workflow probes are performed."><div className="mt-4 grid gap-4 sm:grid-cols-2"><Check check={byKey["application-control-plane"].checks[0]} />{deployed ? <Card title="Deployment metadata"><p><b>Revision:</b> <a className="font-mono underline" href={deployed.commitUrl}>{deployed.shortCommitSha}</a></p><p>Deployed <LocalizedTime value={deployed.deployedAt} /></p>{deployed.pullRequestNumber ? <p><a className="underline" href={deployed.pullRequestUrl}>Pull request #{deployed.pullRequestNumber}</a></p> : null}</Card> : null}</div></Domain>
      <Domain domain={byKey["adt-runtime"]} description="Commissioning/readiness only. This check does not resolve a provider credential or invoke OpenAI, an Agent, or LangGraph."><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{runtimeDiagnosticChecks(runtime).map(check => <Check key={check.id} check={check} />)}</div></Domain>
      <Domain domain={byKey["codex-runner"]} description="Safe connection and compatibility summary for the independently deployed execution boundary. Loading this page never starts a Codex model turn."><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{runnerDiagnosticChecks(runner).map(check => <Check key={check.id} check={check} />)}</div><div className="mt-4 rounded-xl border border-slate-200 p-4 text-sm dark:border-slate-700"><h3 className="font-black">Execution boundary, environments & operations</h3><p className="mt-2">Emergency-stop state, executor health, bounded workspace/sandbox diagnostics, current/stale job observations, and auth-environment diagnostics remain on the detailed operational page.</p><p className="mt-3"><a className="font-bold underline underline-offset-2" href="/workflows/connections/codex-runner/status">Open Codex Runner status</a></p></div></Domain>
    </div>
  </main></>;
}
