import test from "node:test";
import assert from "node:assert/strict";
import {mkdtemp,mkdir,writeFile,readFile,realpath} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {execFileSync} from "node:child_process";
import {generateKeyPairSync} from "node:crypto";
import {ManagedRepositoryService,createRepositoryManagerServer,RepositoryManagerClient} from "../dist/repository-manager.js";

const git=(cwd,...args)=>execFileSync("git",args,{cwd,encoding:"utf8",env:{...process.env,GIT_AUTHOR_NAME:"Test",GIT_AUTHOR_EMAIL:"test@example.invalid",GIT_COMMITTER_NAME:"Test",GIT_COMMITTER_EMAIL:"test@example.invalid"}}).trim();
async function fixture(){const root=await mkdtemp(join(tmpdir(),"adt-rm-")),remote=join(root,"remote.git"),seed=join(root,"seed"),workspaceRoot=join(root,"workspaces"),workspace=join(workspaceRoot,"project");mkdir(seed,{recursive:true});await mkdir(workspace,{recursive:true});git(root,"init","--bare",remote);git(seed,"init","-b","main");await writeFile(join(seed,"README.md"),"one\n");git(seed,"add","README.md");git(seed,"commit","-m","initial");git(seed,"remote","add","origin",remote);git(seed,"push","origin","main");const environment={key:"project",name:"Project",cwd:await realpath(workspace),enabled:true,sandbox:"workspace-write",ready:true,repository:{managed:true,owner:"example",repo:"project",baseBranch:"main"}},service=new ManagedRepositoryService([environment],workspaceRoot,{remote:()=>remote,allowFileProtocol:true});return{root,remote,seed,workspaceRoot,workspace,environment,service}}

test("managed preparation initializes an empty root and is idempotent",async()=>{const f=await fixture(),first=await f.service.prepare({environmentKey:"project",taskId:"task-1",credential:"temporary"}),again=await f.service.prepare({environmentKey:"project",taskId:"task-1",credential:"different"});assert.equal(first.baseSha,git(f.seed,"rev-parse","HEAD"));assert.equal(first.branch,"adt/codex/task-1");assert.equal(again.cwd,first.cwd);assert.equal(await readFile(join(first.cwd,"README.md"),"utf8"),"one\n")});
test("unexpected managed root contents fail without deletion",async()=>{const f=await fixture();await writeFile(join(f.workspace,"keep.txt"),"keep");await assert.rejects(f.service.prepare({environmentKey:"project",taskId:"task-1",credential:"temporary"}),/managed_root_not_empty/);assert.equal(await readFile(join(f.workspace,"keep.txt"),"utf8"),"keep")});
test("new tasks refresh base while active worktrees stay pinned and isolated",async()=>{const f=await fixture(),old=await f.service.prepare({environmentKey:"project",taskId:"old",credential:"temporary"});await writeFile(join(f.seed,"README.md"),"two\n");git(f.seed,"commit","-am","upstream");git(f.seed,"push","origin","main");const next=await f.service.prepare({environmentKey:"project",taskId:"next",credential:"temporary"});assert.notEqual(next.baseSha,old.baseSha);assert.equal(await readFile(join(old.cwd,"README.md"),"utf8"),"one\n");assert.equal(await readFile(join(next.cwd,"README.md"),"utf8"),"two\n");await writeFile(join(old.cwd,"only-old"),"x");assert.equal(await readFile(join(next.cwd,"only-old"),"utf8").catch(()=>"missing"),"missing")});
test("publish detects no changes, commits with ADT identity, and never force pushes",async()=>{const f=await fixture(),prepared=await f.service.prepare({environmentKey:"project",taskId:"publish",credential:"temporary"});assert.equal((await f.service.publish({environmentKey:"project",taskId:"publish",credential:"temporary",message:"Managed change"})).changed,false);await writeFile(join(prepared.cwd,"change.txt"),"ok\n");const result=await f.service.publish({environmentKey:"project",taskId:"publish",credential:"temporary",message:"Managed change"});assert.equal(result.changed,true);assert.match(result.commitSha,/^[a-f0-9]{40}$/);assert.equal(git(prepared.cwd,"show","-s","--format=%an <%ae>"),"ADT Codex Runner <codex-runner@adt.invalid>");assert.equal(git(f.remote,"rev-parse","refs/heads/adt/codex/publish"),result.commitSha)});
test("allowed existing ADT branches can seed a later isolated task and cleanup is bounded",async()=>{const f=await fixture(),first=await f.service.prepare({environmentKey:"project",taskId:"first",credential:"temporary"});await writeFile(join(first.cwd,"change"),"x");await f.service.publish({environmentKey:"project",taskId:"first",credential:"temporary",message:"first"});await f.service.cleanup("project","first");const later=await f.service.prepare({environmentKey:"project",taskId:"later",credential:"temporary",sourceBranch:"adt/codex/first"});assert.equal(await readFile(join(later.cwd,"change"),"utf8"),"x");assert.equal((await f.service.cleanup("project","later")).cleaned,true);assert.equal((await f.service.cleanup("project","later")).cleaned,false);await assert.rejects(f.service.prepare({environmentKey:"project",taskId:"bad/../id",credential:"temporary"}),/invalid_request/)});
test("repository manager reuses signed internal authentication and rejects replay",async()=>{const f=await fixture(),{privateKey,publicKey}=generateKeyPairSync("ed25519"),server=createRepositoryManagerServer({executorVerifyingPublicKey:publicKey.export({type:"spki",format:"pem"}),workspaceRoot:f.workspaceRoot},f.service);await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address(),client=new RepositoryManagerClient(`http://127.0.0.1:${address.port}`,privateKey.export({type:"pkcs8",format:"pem"}));assert.equal((await client.status({environmentKey:"project"})).repositoryManagementConfigured,true);const response=await fetch(`http://127.0.0.1:${address.port}/internal/v1/repositories/status`,{method:"POST",headers:{"content-type":"application/json"},body:'{"environmentKey":"project"}'});assert.equal(response.status,401);await new Promise(resolve=>server.close(resolve))});
