import test from "node:test";import assert from "node:assert/strict";import {mkdtemp,writeFile,chmod} from "node:fs/promises";import {tmpdir} from "node:os";import {join} from "node:path";import {EventEmitter} from "node:events";import {PassThrough} from "node:stream";import {loadSecret} from "../dist/configuration.js";import {createRunnerServer} from "../dist/server.js";import {AppServerRequestError,StdioAppServerClient} from "../dist/app-server-client.js";import {diagnoseAuthEnvironment,classifyNetworkFailure,safeHttpResult,parseRustAuthProbeOutput,classifyRustProbeExecution,EXPECTED_CODEX_VERSION} from "../dist/auth-environment-diagnostics.js";import {validateDeviceAuthSchemas,hasType} from "../dist/validate-device-auth-schema.js";
import schemaFixture from "./fixtures/codex-0.147-device-auth-schemas.json" with {type:"json"};
const mock={async readiness(){return true},async status(){return{connected:true,authMode:"chatgpt",planType:"plus",accessToken:"MUST_NOT_ESCAPE"}},async startDeviceLogin(){return{loginId:"login",verificationUrl:"https://auth.openai.com/device",userCode:"ABCD",accessToken:"MUST_NOT_ESCAPE"}},async logout(){return{refreshToken:"MUST_NOT_ESCAPE"}},async close(){}};
async function withServer(fn,client=mock,diagnostics){const server=createRunnerServer({host:"127.0.0.1",port:1,sharedSecret:"correct",runnerVersion:"sha-test",codexCommand:"codex",requestBodyLimit:32,deviceAuthCompatible:true},client,diagnostics);await new Promise(r=>server.listen(0,"127.0.0.1",r));const {port}=server.address();try{await fn(`http://127.0.0.1:${port}`)}finally{await new Promise(r=>server.close(r))}}
function deviceAuthSchemas(){return structuredClone(schemaFixture.documents)}
function schema(documents,title){return documents.find(value=>value.schema.title===title).schema}
function clientDefinitions(documents){return schema(documents,"ClientRequest").definitions}
function requestBranch(documents,method){return schema(documents,"ClientRequest").oneOf.find(branch=>branch.properties.method.enum.includes(method))}
function responseVariant(documents){return schema(documents,"LoginAccountResponse").oneOf[0]}

test("curated rust-v0.147.0 embedded schema layout contains all device auth contracts",()=>assert.equal(validateDeviceAuthSchemas(deviceAuthSchemas()),true));
test("JSON Schema type detection handles scalar, union, and combinator forms without nested false positives",()=>{
 for(const value of [{type:"string"},{type:["string","null"]},{anyOf:[{type:"string"},{type:"null"}]},{oneOf:[{type:"null"},{type:"string"}]}])assert.equal(hasType(value,"string"),true);
 for(const value of [{type:"number"},{type:["number","null"]},{properties:{nested:{type:"string"}}},{anyOf:[{type:"number"},{type:"null"}]}])assert.equal(hasType(value,"string"),false);
});
test("embedded InitializeParams and GetAccountParams need no standalone documents",()=>{
 const documents=deviceAuthSchemas();
 assert.equal(documents.some(value=>["InitializeParams","GetAccountParams"].includes(value.schema.title)),false);
 assert.equal(validateDeviceAuthSchemas(documents),true);
});
test("optional ClientInfo title may be omitted, while its string/null union is accepted",()=>{
 const documents=deviceAuthSchemas();delete clientDefinitions(documents).ClientInfo.properties.title;
 assert.equal(validateDeviceAuthSchemas(documents),true);
});
for(const [method,error] of [["initialize","initialize_contract"],["account/read","account_read_contract"]])test(`unresolved ${method} params ref fails closed`,()=>{
 const documents=deviceAuthSchemas();requestBranch(documents,method).properties.params.$ref="#/definitions/Missing";
 assert.throws(()=>validateDeviceAuthSchemas(documents),new RegExp(error));
});
for(const field of ["name","version"])test(`ClientInfo ${field} must accept string and remain required`,()=>{
 let documents=deviceAuthSchemas();clientDefinitions(documents).ClientInfo.properties[field]={type:"number"};assert.throws(()=>validateDeviceAuthSchemas(documents),/initialize_contract/);
 documents=deviceAuthSchemas();clientDefinitions(documents).ClientInfo.required=clientDefinitions(documents).ClientInfo.required.filter(value=>value!==field);assert.throws(()=>validateDeviceAuthSchemas(documents),/initialize_contract/);
});
test("InitializeParams must require clientInfo",()=>{const documents=deviceAuthSchemas();clientDefinitions(documents).InitializeParams.required=[];assert.throws(()=>validateDeviceAuthSchemas(documents),/initialize_contract/)});
test("account/read refreshToken must accept boolean",()=>{const documents=deviceAuthSchemas();clientDefinitions(documents).GetAccountParams.properties.refreshToken={type:"string"};assert.throws(()=>validateDeviceAuthSchemas(documents),/account_read_contract/)});
test("RPC method tokens outside top-level ClientRequest variants do not establish routing",()=>{
 for(const method of ["initialize","account/read","account/login/start","account/logout"]){const documents=deviceAuthSchemas();schema(documents,"ClientRequest").oneOf=schema(documents,"ClientRequest").oneOf.filter(branch=>!branch.properties.method.enum.includes(method));clientDefinitions(documents).Unrelated={description:`supports ${method}`,properties:{method:{enum:[method]}}};assert.throws(()=>validateDeviceAuthSchemas(documents))}
});
test("a method branch cannot borrow another method's otherwise-valid params",()=>{const documents=deviceAuthSchemas();requestBranch(documents,"account/read").properties.params.$ref="#/definitions/InitializeParams";assert.throws(()=>validateDeviceAuthSchemas(documents),/account_read_contract/)});
test("cyclic and malformed local refs fail closed",()=>{for(const ref of ["#/definitions/Cycle","#/definitions/Bad~2Pointer","https://example.invalid/schema"]){const documents=deviceAuthSchemas();clientDefinitions(documents).Cycle={$ref:"#/definitions/Cycle"};requestBranch(documents,"initialize").properties.params={$ref:ref};assert.throws(()=>validateDeviceAuthSchemas(documents),/initialize_contract/)}});
test("logout accepts only optional null params from rust-v0.147.0",()=>{
 assert.equal(validateDeviceAuthSchemas(deviceAuthSchemas()),true);
 for(const mutation of [
  branch=>branch.properties.params={type:"object"},
  branch=>branch.required.push("params"),
  branch=>delete branch.properties.params
 ]){const documents=deviceAuthSchemas();mutation(requestBranch(documents,"account/logout"));assert.throws(()=>validateDeviceAuthSchemas(documents),/account_logout_contract/)}
});
test("device request discriminator must exist in both routed params and standalone LoginAccountParams",()=>{
 for(const target of ["embedded","standalone"]){const documents=deviceAuthSchemas();const login=target==="embedded"?clientDefinitions(documents).LoginAccountParams:schema(documents,"LoginAccountParams");login.oneOf[0].properties.type.enum=["missing"];documents.push({filename:"Unrelated.json",schema:{title:"Unrelated",token:"chatgptDeviceCode"}});assert.throws(()=>validateDeviceAuthSchemas(documents),/missing_request_contract/)}
});
for(const field of ["loginId","verificationUrl","userCode"]){
 test(`device response requires ${field} on its own variant`,()=>{const documents=deviceAuthSchemas();delete responseVariant(documents).properties[field];schema(documents,"LoginAccountResponse").oneOf[1].properties[field]={type:"string"};documents.push({filename:"Unrelated.json",schema:{properties:{[field]:{type:"string"}}}});assert.throws(()=>validateDeviceAuthSchemas(documents),new RegExp(`missing_${field}`))});
 test(`device response requires ${field} to accept string`,()=>{const documents=deviceAuthSchemas();responseVariant(documents).properties[field]={type:"number"};assert.throws(()=>validateDeviceAuthSchemas(documents),new RegExp(`missing_${field}`))});
 test(`device response requires ${field} in required`,()=>{const documents=deviceAuthSchemas();responseVariant(documents).required=responseVariant(documents).required.filter(value=>value!==field);assert.throws(()=>validateDeviceAuthSchemas(documents),new RegExp(`missing_${field}`))});
}
test("response discriminator and malformed document sets fail closed",()=>{let documents=deviceAuthSchemas();responseVariant(documents).properties.type.enum=["browser"];assert.throws(()=>validateDeviceAuthSchemas(documents),/response_contract/);for(const malformed of [[],[null],deviceAuthSchemas().filter(value=>value.schema.title!=="LoginAccountResponse")])assert.throws(()=>validateDeviceAuthSchemas(malformed))});
test("Runner source pins and validates the deterministic upstream GNU package",async()=>{const fs=await import("node:fs/promises"),docker=await fs.readFile(new URL("../Dockerfile",import.meta.url),"utf8"),readme=await fs.readFile(new URL("../README.md",import.meta.url),"utf8");assert.match(readme,/experimental GNU\/glibc build/);assert.match(readme,/neither release-equivalent nor an OpenAI-published GNU prebuilt artifact/);assert.equal(EXPECTED_CODEX_VERSION,"0.147.0");for(const required of [/be6e8eac029b183056b7e4402879f15d2c85f61b/,/--target x86_64-unknown-linux-gnu/,/--cargo-profile dev-small/,/CARGO_INCREMENTAL=0 CARGO_BUILD_JOBS=2/,/--package-dir \/out\/codex-package/,/\/out\/codex-package\/codex-package\.json/,/libcap-dev/,/codex-native-libc/,/COPY --from=codex-gnu-build \/out\/codex-package \/opt\/codex/])assert.match(docker,required);assert.doesNotMatch(docker,/V8_FROM_SOURCE=1/);assert.doesNotMatch(docker,/--cargo-profile release/);assert.doesNotMatch(docker,/npm install.*@openai\/codex|npm-musl-confirmation|CODEX_RUNNER_CODEX_LIBC|@openai\/codex@(?:latest|[~^*]|0\.147(?:\s|$)|0\.147\.0-)|@openai\/codex@0\.118\.0/)});
test("final image gates Codex setup and execution in diagnostic order",async()=>{const docker=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../Dockerfile",import.meta.url),"utf8")),runtime=docker.slice(docker.lastIndexOf("FROM node:24-bookworm-slim")),position=token=>{const index=runtime.indexOf(token);assert.notEqual(index,-1,`missing ${token}`);return index},home=position("mkdir -p /data/codex"),path=position("ln -s /opt/codex/bin/codex /usr/local/bin/codex"),runtimePackage=position("apt-get install -y --no-install-recommends libssl3"),ldd=position("ldd /opt/codex/bin/codex"),version=position("codex --version"),schema=position("validate-device-auth-schema.js codex"),marker=position("printf 'glibc\\n' >/etc/codex-runner/codex-native-libc");assert.ok(home<path&&path<runtimePackage&&runtimePackage<ldd&&ldd<version&&version<schema&&schema<marker);assert.match(runtime,/command -v codex/);assert.match(runtime,/test ! -e \/usr\/bin\/codex/);assert.match(runtime,/test ! -e \/usr\/local\/lib\/node_modules\/@openai\/codex/);assert.match(runtime,/codex_runtime_missing_soname=/);assert.match(runtime,/codex_runtime_ldd_failed/);assert.match(runtime,/grep -Fq 'not found'/);assert.doesNotMatch(runtime,/apt-get install[^\n]*(?:libssl-dev|build-essential|clang|pkg-config|git|libcap-dev|openssl(?:[[:space:]]|$))/)});
test("auth probe is persistently exported and validated offline in image and smoke",async()=>{const fs=await import("node:fs/promises"),docker=await fs.readFile(new URL("../Dockerfile",import.meta.url),"utf8"),smoke=await fs.readFile(new URL("../scripts/smoke-image.sh",import.meta.url),"utf8"),builderStart=docker.indexOf("FROM rust:1.93.1-bookworm AS auth-probe-build"),builder=docker.slice(builderStart,docker.indexOf("FROM node:24-bookworm-slim",builderStart));assert.match(builder,/--mount=type=cache,target=\/probe\/target/);assert.match(builder,/install -D -m 0755 target\/release\/adt-codex-auth-probe \/out\/adt-codex-auth-probe/);assert.match(builder,/test -x \/out\/adt-codex-auth-probe/);assert.match(docker,/COPY --from=auth-probe-build \/out\/adt-codex-auth-probe \/usr\/local\/bin\/adt-codex-auth-probe/);for(const source of [docker,smoke]){assert.match(source,/ldd \/usr\/local\/bin\/adt-codex-auth-probe/);assert.match(source,/not found/)}assert.match(smoke,/command -v adt-codex-auth-probe/);assert.doesNotMatch(smoke,/docker run[^\n]*adt-codex-auth-probe(?:\s|$)/)});
test("loads direct and Docker secret-file configuration",async()=>{assert.equal(await loadSecret({CODEX_RUNNER_SHARED_SECRET:" direct "})," direct ");const dir=await mkdtemp(join(tmpdir(),"runner-")),file=join(dir,"secret");await writeFile(file,"file secret\n");assert.equal(await loadSecret({CODEX_RUNNER_SHARED_SECRET_FILE:file}),"file secret")});
test("secret configuration fails closed",async()=>{await assert.rejects(loadSecret({}),/missing/);await assert.rejects(loadSecret({CODEX_RUNNER_SHARED_SECRET:"x",CODEX_RUNNER_SHARED_SECRET_FILE:"x"}),/ambiguous/);await assert.rejects(loadSecret({CODEX_RUNNER_SHARED_SECRET_FILE:"/missing"}),/unreadable/);const dir=await mkdtemp(join(tmpdir(),"runner-")),empty=join(dir,"empty"),unreadable=join(dir,"unreadable");await writeFile(empty,"");await writeFile(unreadable,"x");await chmod(unreadable,0);await assert.rejects(loadSecret({CODEX_RUNNER_SHARED_SECRET_FILE:empty}),/empty/);await assert.rejects(loadSecret({CODEX_RUNNER_SHARED_SECRET_FILE:unreadable},async()=>{throw new Error("denied")}),/unreadable/)});
test("health is public and v1 requires the correct secret",()=>withServer(async base=>{assert.deepEqual(await (await fetch(base+"/health")).json(),{ok:true});assert.equal((await fetch(base+"/v1/capabilities")).status,401);assert.equal((await fetch(base+"/v1/capabilities",{headers:{"x-codex-runner-secret":"wrong"}})).status,401);const response=await fetch(base+"/v1/capabilities",{headers:{"x-codex-runner-secret":"correct"}});assert.equal(response.status,200);assert.deepEqual(await response.json(),{protocolVersion:1,runnerVersion:"sha-test",codexAvailable:true,deviceAuth:true,jobExecution:false})}));
test("auth abstractions allow only safe fields",()=>withServer(async base=>{const headers={"x-codex-runner-secret":"correct","content-type":"application/json"};for(const [path,method] of [["/v1/auth/status","GET"],["/v1/auth/device/start","POST"],["/v1/auth/logout","POST"]]){const response=await fetch(base+path,{method,headers});assert.equal(response.status,200);assert.doesNotMatch(await response.text(),/MUST_NOT_ESCAPE|accessToken|refreshToken/)}const ceremony=await (await fetch(base+"/v1/auth/device/start",{method:"POST",headers})).json();assert.deepEqual(ceremony,{loginId:"login",verificationUrl:"https://auth.openai.com/device",userCode:"ABCD"})}));
test("device ceremony rejects missing or unsafe exact 0.147 fields",async()=>{for(const result of [{verificationUrl:"https://auth.openai.com/device",userCode:"CODE"},{loginId:"id",userCode:"CODE"},{loginId:"id",verificationUrl:"https://auth.openai.com/device"},{loginId:"id",verificationUrl:"http://auth.openai.com/device",userCode:"CODE"},{loginId:"id",verificationUrl:"https://not-openai.example/device",userCode:"CODE"},{id:"legacy",verificationUri:"https://auth.openai.com/device",userCode:"CODE"}])await withServer(async base=>{const response=await fetch(base+"/v1/auth/device/start",{method:"POST",headers:{"x-codex-runner-secret":"correct","content-type":"application/json"}});assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:"device_auth_start_failed",deviceAuthReason:"device_auth_unknown"})},{...mock,async startDeviceLogin(){return result}})});
test("body limits and App Server errors are sanitized",()=>withServer(async base=>fetch(base+"/v1/auth/logout",{method:"POST",headers:{"x-codex-runner-secret":"correct","content-type":"application/json"},body:JSON.stringify({value:"a".repeat(40)})}).then(async response=>{assert.equal(response.status,413);assert.deepEqual(await response.json(),{error:"request_too_large"})}))); 
test("raw App Server failures never escape",()=>withServer(async base=>{const response=await fetch(base+"/v1/auth/status",{headers:{"x-codex-runner-secret":"correct"}});assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:"codex_auth_unavailable"})},{...mock,async status(){throw new Error("token=SECRET raw stack")}}));
test("failed device start returns and logs only bounded safe classification",async()=>{const logs=[],original=console.error;console.error=value=>logs.push(value);try{await withServer(async base=>{const response=await fetch(base+"/v1/auth/device/start",{method:"POST",headers:{"x-codex-runner-secret":"correct","content-type":"application/json"}});assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:"device_auth_start_failed",deviceAuthReason:"device_auth_unknown"})},{...mock,async startDeviceLogin(){throw new Error("raw App Server message token=ACCESS redirect=https://evil.invalid")}})}finally{console.error=original}assert.equal(logs.length,1);assert.deepEqual(JSON.parse(logs[0]),{level:"error",event:"runner_operation_failed",operation:"POST /v1/auth/device/start",category:"device_auth_start_failed",deviceAuthReason:"device_auth_unknown"});assert.doesNotMatch(logs.join(""),/ACCESS|evil|raw App Server/)});
test("safe device failure metadata reaches the bounded response and log",async()=>{const logs=[],original=console.error;console.error=value=>logs.push(value);try{await withServer(async base=>{const response=await fetch(base+"/v1/auth/device/start",{method:"POST",headers:{"x-codex-runner-secret":"correct","content-type":"application/json"}});assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:"device_auth_start_failed",deviceAuthReason:"device_auth_rate_limited",upstreamHttpStatus:429,jsonRpcCode:-32000})},{...mock,async startDeviceLogin(){throw new AppServerRequestError("device_auth_rate_limited",-32000,429)}})}finally{console.error=original}assert.deepEqual(JSON.parse(logs[0]),{level:"error",event:"runner_operation_failed",operation:"POST /v1/auth/device/start",category:"device_auth_start_failed",deviceAuthReason:"device_auth_rate_limited",upstreamHttpStatus:429,jsonRpcCode:-32000})});
test("real wire initializes once before account requests with documented framing",async()=>{const input=new PassThrough(),output=new PassThrough(),stderr=new PassThrough(),child=Object.assign(new EventEmitter(),{stdin:input,stdout:output,stderr,killed:false,kill(){this.killed=true;this.emit("exit",0)}});const sent=[];let buffered="";input.on("data",chunk=>{buffered+=chunk;for(;;){const newline=buffered.indexOf("\n");if(newline<0)break;const message=JSON.parse(buffered.slice(0,newline));buffered=buffered.slice(newline+1);sent.push(message);if(message.id)output.write(`${JSON.stringify({id:message.id,result:message.method==="account/read"?{account:null}:{}})}\n`)}});const client=new StdioAppServerClient("codex","runner-sha",100,()=>child);assert.deepEqual(await client.status(),{account:null});assert.deepEqual(await client.status(),{account:null});assert.deepEqual(sent.map(value=>value.method),["initialize","initialized","account/read","account/read"]);assert.deepEqual(sent[0],{method:"initialize",id:1,params:{clientInfo:{name:"adt_codex_runner",title:"ADT Codex Runner",version:"runner-sha"}}});assert.deepEqual(sent[1],{method:"initialized"});assert.deepEqual(sent[2].params,{refreshToken:false});assert.equal(sent.some(value=>"jsonrpc" in value),false);await client.close()});
test("real wire omits params from the account/logout request",async()=>{const input=new PassThrough(),output=new PassThrough(),stderr=new PassThrough(),child=Object.assign(new EventEmitter(),{stdin:input,stdout:output,stderr,killed:false,kill(){this.killed=true;this.emit("exit",0)}}),sent=[];input.on("data",chunk=>{for(const line of chunk.toString().trim().split("\n")){const message=JSON.parse(line);sent.push(message);if(message.id)output.write(`${JSON.stringify({id:message.id,result:{}})}\n`)}});const client=new StdioAppServerClient("codex","runner-sha",100,()=>child);await client.logout();const message=sent.find(value=>value.method==="account/logout");assert.equal(typeof message.id,"number");assert.equal(Object.hasOwn(message,"params"),false);await client.close()});
test("real wire sends device-code framing and maps its response",async()=>{const input=new PassThrough(),output=new PassThrough(),stderr=new PassThrough(),child=Object.assign(new EventEmitter(),{stdin:input,stdout:output,stderr,killed:false,kill(){this.killed=true;this.emit("exit",0)}}),sent=[];input.on("data",chunk=>{for(const line of chunk.toString().trim().split("\n")){const message=JSON.parse(line);sent.push(message);if(message.id)output.write(`${JSON.stringify({id:message.id,result:message.method==="account/login/start"?{loginId:"login-1",verificationUrl:"https://auth.openai.com/device",userCode:"SAFE-CODE"}:{}})}\n`)}});const client=new StdioAppServerClient("codex","runner-sha",100,()=>child);assert.deepEqual(await client.startDeviceLogin(),{loginId:"login-1",verificationUrl:"https://auth.openai.com/device",userCode:"SAFE-CODE"});assert.deepEqual(sent.find(value=>value.method==="account/login/start"),{method:"account/login/start",id:2,params:{type:"chatgptDeviceCode"}});await client.close()});
for(const [message,reason,status] of [["ChatGPT login is disabled. Use API key login instead.","chatgpt_login_disabled",undefined],["device code login is not enabled for this Codex server. Use the browser login or verify the server URL.","device_auth_not_enabled",undefined],["failed to request device code: device code request failed with status 403 Forbidden","device_auth_upstream_forbidden",403],["failed to request device code: device code request failed with status 429 Too Many Requests","device_auth_rate_limited",429],["failed to request device code: device code request failed with status 500 Internal Server Error","device_auth_upstream_unavailable",500],["failed to request device code: device code request failed with status 502 Bad Gateway","device_auth_upstream_unavailable",502],["failed to request device code: device code request failed with status 503 Service Unavailable","device_auth_upstream_unavailable",503],["failed to request device code: device code request failed with status 404 Not Found","device_auth_upstream_rejected",404],["failed to request device code: device code request failed with status 403","device_auth_upstream_forbidden",403]])test(`classifies exact App Server failure as ${reason}`,async()=>{const input=new PassThrough(),output=new PassThrough(),stderr=new PassThrough(),child=Object.assign(new EventEmitter(),{stdin:input,stdout:output,stderr,killed:false,kill(){this.killed=true;this.emit("exit",0)}});input.on("data",chunk=>{for(const line of chunk.toString().trim().split("\n")){const request=JSON.parse(line);if(request.id)output.write(`${JSON.stringify(request.method==="initialize"?{id:request.id,result:{}}:{id:request.id,error:{code:-32603,message,data:{accessToken:"SECRET"}}})}\n`)}});const client=new StdioAppServerClient("codex","runner-sha",100,()=>child);await assert.rejects(client.startDeviceLogin(),error=>{assert.equal(error.message,"app_server_request_failed");assert.equal(error.reason,reason);assert.equal(error.jsonRpcCode,-32603);assert.equal(error.upstreamHttpStatus,status);assert.doesNotMatch(JSON.stringify(error),/SECRET|evil|private|Forbidden|Requests|Server|Gateway|Unavailable|Not Found/);return true});await client.close()});
for(const message of ["ChatGPT login is disabled","ChatGPT login is disabled. Use API key login instead. token=SECRET","prefix ChatGPT login is disabled. Use API key login instead.","device code login is not enabled","device code login is not enabled for this Codex server. Use the browser login or verify the server URL. suffix=SECRET","failed to request device code: device code request failed with status 099","failed to request device code: device code request failed with status 600","failed to request device code: device code request failed with status nope","failed to request device code: device code request failed with status 403 Too Many Requests","failed to request device code: device code request failed with status 403 Forbidden suffix=SECRET","failed to request device code: device code request failed with status 403 Forbidden https://evil.invalid/private/path?token=SECRET","failed to request device code: device code request failed with status 403 token=SECRET","prefix failed to request device code: device code request failed with status 403 Forbidden","device code request failed with status 403 Forbidden","unknown token=SECRET https://evil.invalid /private/path"])test("near-match App Server failure remains generic",async()=>{const input=new PassThrough(),output=new PassThrough(),stderr=new PassThrough(),child=Object.assign(new EventEmitter(),{stdin:input,stdout:output,stderr,killed:false,kill(){this.killed=true;this.emit("exit",0)}});input.on("data",chunk=>{for(const line of chunk.toString().trim().split("\n")){const request=JSON.parse(line);if(request.id)output.write(`${JSON.stringify(request.method==="initialize"?{id:request.id,result:{}}:{id:request.id,error:{code:-32603,message,data:{accessToken:"SECRET"}}})}\n`)}});const client=new StdioAppServerClient("codex","runner-sha",100,()=>child);await assert.rejects(client.startDeviceLogin(),error=>{assert.equal(error.message,"app_server_request_failed");assert.equal(error.reason,"device_auth_internal");assert.equal(error.jsonRpcCode,-32603);assert.equal(error.upstreamHttpStatus,undefined);assert.doesNotMatch(JSON.stringify(error),/SECRET|evil|private|failed to request|Forbidden|Requests/);return true});await client.close()});
async function classifyMessage(message){const input=new PassThrough(),output=new PassThrough(),stderr=new PassThrough(),child=Object.assign(new EventEmitter(),{stdin:input,stdout:output,stderr,killed:false,kill(){this.killed=true;this.emit("exit",0)}});input.on("data",chunk=>{for(const line of chunk.toString().trim().split("\n")){const request=JSON.parse(line);if(request.id)output.write(`${JSON.stringify(request.method==="initialize"?{id:request.id,result:{}}:{id:request.id,error:{code:-32603,message}})}\n`)}});const client=new StdioAppServerClient("codex","runner-sha",100,()=>child);try{await client.startDeviceLogin()}catch(error){return error}finally{await client.close()}throw new Error("expected failure")}
for(const [message,reason] of [["failed to request device code: error sending request for url (https://auth.openai.com/api/accounts/deviceauth/usercode)","device_auth_transport_error"],["failed to request device code: Failed to read CA certificate file /private/ca.pem selected by CODEX_CA_CERTIFICATE: permission denied","device_auth_ca_configuration"],["failed to request device code: Failed to load CA certificates from /private/ca.pem selected by SSL_CERT_FILE: invalid PEM","device_auth_ca_configuration"],["failed to request device code: Failed to parse certificate #2 from /private/ca.pem selected by CODEX_CA_CERTIFICATE: invalid certificate","device_auth_ca_configuration"],["failed to request device code: Failed to register certificate #1 from /private/ca.pem selected by SSL_CERT_FILE in rustls root store: rejected","device_auth_ca_configuration"],["failed to request device code: Failed to build HTTP client while using CA bundle from /private/ca.pem selected by CODEX_CA_CERTIFICATE: client error","device_auth_http_client_configuration"],["failed to request device code: Failed to build HTTP client while using system root certificates: client error","device_auth_http_client_configuration"]])test(`classifies pinned Codex failure as ${reason}`,async()=>{const error=await classifyMessage(message);assert.equal(error.reason,reason);assert.equal(error.jsonRpcCode,-32603);assert.doesNotMatch(JSON.stringify(error),/private|permission|PEM|certificate|client error|auth\.openai/)})
for(const message of ["failed to request device code: error sending request for url (https://evil.invalid/api/accounts/deviceauth/usercode)","failed to request device code: error sending request for url (https://auth.openai.com/api/accounts/deviceauth/usercode) token=SECRET","failed to request device code: Failed to read CA certificate file /private/ca.pem selected by OTHER_VARIABLE: permission denied","prefix failed to request device code: Failed to build HTTP client while using system root certificates: client error"])test("near-match transport and CA failures remain generic",async()=>{const error=await classifyMessage(message);assert.equal(error.reason,"device_auth_internal");assert.doesNotMatch(JSON.stringify(error),/evil|SECRET|private|client error/)})

test("Rust probe canonical producer output parses and deployed snake_case drift is visible",()=>{const http={outcome:"http_response",status:400,protocol:"http2",cloudflareEdge:true,mitigationChallenge:false,contentKind:"json"},transport={outcome:"transport_error",isTimeout:false,isConnect:true,isRequest:true,ioErrorKind:"other",tlsSourcePresent:false,sourceClass:"unknown"};const parsed=parseRustAuthProbeOutput(JSON.stringify({attempts:[{variant:"baseline",result:transport},{variant:"namedUserAgent",result:http},{variant:"http1Only",result:transport},{variant:"noProxy",result:http},{variant:"forcedIpv4",result:transport}]}));assert.equal(parsed.status,"ok");assert.deepEqual(parsed.matrix?.baseline,transport);assert.deepEqual(parsed.matrix?.forcedIpv4,transport);const snake=JSON.stringify({attempts:[{variant:"baseline",result:{outcome:"http_response",status:400,protocol:"http1",cloudflare_edge:true,mitigation_challenge:false,content_kind:"json"}}]});assert.deepEqual(parseRustAuthProbeOutput(snake),{status:"invalid_shape"});assert.deepEqual(parseRustAuthProbeOutput("{"),{status:"invalid_json"})});
test("Rust probe process failures collapse to bounded statuses without process output",()=>{for(const [error,status]of [[{code:"ENOENT",message:"secret spawn"},"spawn_failed"],[{killed:true,code:"ETIMEDOUT",stderr:"secret timeout"},"timed_out"],[{code:1,stdout:"secret stdout",stderr:"secret stderr"},"nonzero_exit"]]){const result=classifyRustProbeExecution(error,"secret stdout");assert.deepEqual(result,{status});assert.doesNotMatch(JSON.stringify(result),/secret|stdout|stderr|message/)}});
test("auth diagnostics preserve a valid Rust matrix and always expose bounded execution status",async()=>{const matrix=parseRustAuthProbeOutput(JSON.stringify({attempts:[{variant:"baseline",result:{outcome:"transport_error",isTimeout:false,isConnect:true,isRequest:true,ioErrorKind:"other",tlsSourcePresent:false,sourceClass:"unknown"}},{variant:"http1Only",result:{outcome:"http_response",status:400,protocol:"http1",cloudflareEdge:true,mitigationChallenge:false,contentKind:"json"}}]}));const base={environment:{},lookupHost:async()=>[],accessPath:async()=>{},runRustAuthProbe:async()=>matrix,nodeDeviceAuthPost:async()=>({protocol:"http1",responseReceived:true,status:400,mitigationChallenge:false,cloudflareEdge:true,redirectPresent:false})};const ok=await diagnoseAuthEnvironment(base);assert.equal(ok.codexAuthTransportProbeStatus,"ok");assert.equal(ok.codexAuthTransportProbe?.baseline.outcome,"transport_error");assert.equal(ok.codexAuthTransportProbe?.http1Only?.outcome,"http_response");for(const status of ["spawn_failed","timed_out","nonzero_exit","invalid_json","invalid_shape"]){const failed=await diagnoseAuthEnvironment({...base,runRustAuthProbe:async()=>({status})});assert.equal(failed.codexAuthTransportProbeStatus,status);assert.equal(failed.codexAuthTransportProbe,undefined);assert.equal(failed.nodeDeviceAuthPostProbe?.status,400);assert.doesNotMatch(JSON.stringify(failed),/stdout|stderr|secret/)}});
test("auth diagnostics retain HEAD history and add one safe exact-method POST",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../src/auth-environment-diagnostics.ts",import.meta.url),"utf8"));assert.match(source,/connect\(\{host,port,family\}\)/);assert.match(source,/rejectUnauthorized:true/);assert.match(source,/method:"HEAD"/);assert.match(source,/method:"POST"/);assert.match(source,/request\.end\("\{"\)/);assert.doesNotMatch(source,/response\.on\("data"/)});
test("Rust probe is bounded, progressive, and changes one dimension per variant",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../auth-probe/src/main.rs",import.meta.url),"utf8"));assert.match(source,/reqwest/);assert.match(source,/BODY:&str="\{"/);assert.match(source,/Duration::from_secs\(4\)/);assert.match(source,/if matches!\(attempts\[0\]\.result,ResultSummary::Transport/);assert.match(source,/http1_only\(\)/);assert.match(source,/no_proxy\(\)/);assert.match(source,/resolve_to_addrs\(HOST,ipv4\)/);assert.doesNotMatch(source,/response\.text|println!.*error|Debug/)});
test("respect-system-proxy experiment changes only reviewed argv",async()=>{for(const [enabled,expected] of [[false,["app-server"]],[true,["--enable","respect_system_proxy","app-server"]]]){let argv;const child=Object.assign(new EventEmitter(),{stdin:new PassThrough(),stdout:new PassThrough(),stderr:new PassThrough(),killed:false,kill(){this.killed=true;this.emit("exit",0)}});const client=new StdioAppServerClient("codex","test",10,(_command,args)=>{argv=args;return child},enabled);await client.readiness();assert.deepEqual(argv,expected);await client.close()}});
test("auth environment diagnostics separate address-family TCP, TLS, and safe HTTPS results",async()=>{const calls=[],environment={CODEX_CA_CERTIFICATE:"/secret/codex-ca",HTTP_PROXY:"http://secret-proxy.invalid",CODEX_HOME:"/secret/home"};const result=await diagnoseAuthEnvironment({environment,lookupHost:async host=>{calls.push(["dns",host]);return[{address:"192.0.2.1",family:4},{address:"2001:db8::1",family:6}]},connectHost:async(host,port,family,timeout)=>{calls.push(["tcp",host,port,family,timeout]);return family===4?"ok":"timeout"},tlsHost:async(host,port,family,timeout)=>{calls.push(["tls",host,port,family,timeout,true]);return family===4?"failed":"ok"},http1Head:async(path,userAgent)=>{calls.push(["https",path,Boolean(userAgent)]);return{protocol:"http1",responseReceived:true,status:403,mitigationChallenge:true,cloudflareEdge:true,redirectPresent:false}},http2Head:async()=>({protocol:"http2",responseReceived:true,status:403,mitigationChallenge:true,cloudflareEdge:true,redirectPresent:false}),accessPath:async()=>{},codexAppServerReady:async()=>true});assert.equal(result.ipv4TcpConnectivity,"ok");assert.equal(result.ipv6TcpConnectivity,"timeout");assert.equal(result.ipv4TlsConnectivity,"failed");assert.equal(result.ipv6TlsConnectivity,"ok");assert.equal(result.httpsResponseReceived,true);assert.equal(result.httpsStatus,403);assert.equal(result.httpsMitigationChallenge,true);assert.deepEqual(calls.filter(call=>call[0]==="tcp").map(call=>call.slice(1)),[["auth.openai.com",443,4,2000],["auth.openai.com",443,6,2000]]);assert.doesNotMatch(JSON.stringify(result),/secret|192\.0\.2|2001:db8|MUST_NOT_ESCAPE|headers|body/)});
test("unavailable families are never probed and opposite-family failures remain separate",async()=>{const calls=[];const result=await diagnoseAuthEnvironment({environment:{},lookupHost:async()=>[{address:"2001:db8::1",family:6}],connectHost:async(_host,_port,family)=>{calls.push(["tcp",family]);return"failed"},tlsHost:async(_host,_port,family)=>{calls.push(["tls",family]);return"ok"},accessPath:async()=>{}});assert.equal(result.ipv4TcpConnectivity,"unavailable");assert.equal(result.ipv4TlsConnectivity,"unavailable");assert.equal(result.ipv6TcpConnectivity,"failed");assert.equal(result.ipv6TlsConnectivity,"ok");assert.deepEqual(calls,[["tcp",6],["tls",6]])});
test("auth diagnostics are bounded and do not probe HTTPS when DNS has no family",async()=>{const started=Date.now(),calls=[];const result=await diagnoseAuthEnvironment({environment:{SSL_CERT_FILE:"/ssl"},lookupHost:async()=>[],connectHost:async()=>{calls.push("tcp");return"ok"},tlsHost:async()=>{calls.push("tls");return"ok"},httpsHead:async()=>{calls.push("https");return{responseReceived:true,status:200,mitigationChallenge:false}},accessPath:async path=>{if(path==="/ssl")throw new Error("TLS error sentinel")}});assert.equal(result.customCaFileReadable,false);assert.equal(result.ipv4TcpConnectivity,"unavailable");assert.equal(result.ipv6TcpConnectivity,"unavailable");assert.equal(result.httpsResponseReceived,false);assert.deepEqual(calls,[]);assert.ok(Date.now()-started<3000);assert.doesNotMatch(JSON.stringify(result),/\/ssl|sentinel/)});
test("diagnostic endpoint is secret protected and preserves supplied safe diagnostics",()=>{let calls=0;const diagnostics={runnerReachable:true,codexAppServerReady:true,customCaSource:"none",httpProxyConfigured:false,httpsProxyConfigured:false,allProxyConfigured:false,noProxyConfigured:false,dnsResolution:"ok",ipv4Available:true,ipv6Available:false,ipv4TcpConnectivity:"ok",ipv6TcpConnectivity:"unavailable",ipv4TlsConnectivity:"ok",ipv6TlsConnectivity:"unavailable",httpsResponseReceived:true,httpsStatus:403,httpsMitigationChallenge:false,tcpConnectivity:"ok",codexHomeReadable:true,codexHomeWritable:true};return withServer(async base=>{assert.equal((await fetch(base+"/v1/diagnostics/auth-environment")).status,401);const response=await fetch(base+"/v1/diagnostics/auth-environment",{headers:{"x-codex-runner-secret":"correct"}});assert.deepEqual(await response.json(),diagnostics);assert.equal(calls,1)},mock,async()=>{calls++;return diagnostics})});
test("malformed JSON-RPC errors remain generic",async()=>{for(const error of [null,{code:null,message:"device code request failed with status 403"},{code:1.5,message:"device code request failed with status 403"},{code:-32000,message:42}]){const input=new PassThrough(),output=new PassThrough(),stderr=new PassThrough(),child=Object.assign(new EventEmitter(),{stdin:input,stdout:output,stderr,killed:false,kill(){this.killed=true;this.emit("exit",0)}});input.on("data",chunk=>{for(const line of chunk.toString().trim().split("\n")){const request=JSON.parse(line);if(request.id)output.write(`${JSON.stringify(request.method==="initialize"?{id:request.id,result:{}}:{id:request.id,error})}\n`)}});const client=new StdioAppServerClient("codex","runner-sha",100,()=>child);await assert.rejects(client.startDeviceLogin(),failure=>failure.message==="app_server_request_failed"&&!(failure instanceof AppServerRequestError));await client.close()}});
test("RPC timeout clears pending work and a later process can restart",async()=>{let spawns=0;const spawn=()=>{spawns++;const child=Object.assign(new EventEmitter(),{stdin:new PassThrough(),stdout:new PassThrough(),stderr:new PassThrough(),killed:false,kill(){this.killed=true;this.emit("exit",0)}});return child};const client=new StdioAppServerClient("codex","test",10,spawn);assert.equal(await client.readiness(),false);assert.equal(await client.readiness(),false);assert.equal(spawns,2);await client.close()});


test("resolver ordering and image policy effectiveness remain address-free",async()=>{for(const [addresses,first,effective] of [[[],"none",false],[[{address:"secret-v4",family:4}],"ipv4",false],[[{address:"secret-v6",family:6}],"ipv6",false],[[{address:"v4",family:4},{address:"v6",family:6}],"ipv4",true],[[{address:"v6",family:6},{address:"v4",family:4}],"ipv6",false]]){const result=await diagnoseAuthEnvironment({environment:{CODEX_RUNNER_ADDRESS_POLICY:"ipv4_preferred"},lookupHost:async()=>addresses,connectHost:async()=>"ok",tlsHost:async()=>"ok",http1Head:async()=>({protocol:"http1",responseReceived:false,mitigationChallenge:false,cloudflareEdge:false,redirectPresent:false}),http2Head:async()=>({protocol:"http2",responseReceived:false,mitigationChallenge:false,cloudflareEdge:false,redirectPresent:false}),readSystemFile:async()=>"0",codexVersion:async()=>EXPECTED_CODEX_VERSION,accessPath:async()=>{}});assert.equal(result.systemResolverFirstFamily,first);assert.equal(result.runnerAddressPolicyEffective,addresses.some(a=>a.family===4)&&addresses.some(a=>a.family===6)?effective:false);assert.doesNotMatch(JSON.stringify(result),/secret-v4|secret-v6|\"address\"/) }const system=await diagnoseAuthEnvironment({environment:{},lookupHost:async()=>[],readSystemFile:async()=>"1",codexVersion:async()=>undefined,accessPath:async()=>{}});assert.equal(system.runnerAddressPolicyEffective,null);assert.equal(system.kernelIpv6Disabled,true);assert.equal(system.codexVersionMatchesExpected,false)});
test("0.147 diagnostic summary is reachable without claiming device auth success",async()=>{const base={environment:{},lookupHost:async()=>[{address:"v4",family:4}],connectHost:async()=>"ok",tlsHost:async()=>"ok",http1Head:async()=>({protocol:"http1",responseReceived:true,status:405,mitigationChallenge:false,cloudflareEdge:true,redirectPresent:false}),http2Head:async()=>({protocol:"http2",responseReceived:true,status:405,mitigationChallenge:false,cloudflareEdge:true,redirectPresent:false}),accessPath:async()=>{}};const current=await diagnoseAuthEnvironment({...base,codexVersion:async()=>"0.147.0"});assert.equal(current.codexVersionMatchesExpected,true);assert.ok(current.summary.includes("Codex 0.147.0 is active and the OpenAI authentication route is reachable."));assert.doesNotMatch(current.summary.join(" "),/device authentication (?:works|succeeded)/i);const old=await diagnoseAuthEnvironment({...base,codexVersion:async()=>"0.118.0"});assert.equal(old.codexVersionMatchesExpected,false);assert.doesNotMatch(old.summary.join(" "),/Codex 0\.147\.0 is active/)});
test("network errors map to a finite allowlist without escaping text",()=>{for(const [code,expected,tls=false] of [["ENETUNREACH","network_unreachable"],["EHOSTUNREACH","network_unreachable"],["EADDRNOTAVAIL","address_unavailable"],["EAFNOSUPPORT","address_unavailable"],["ECONNREFUSED","connection_refused"],["ECONNRESET","connection_reset"],["ETIMEDOUT","timeout"],["CERT_HAS_EXPIRED","certificate",true],["ERR_SSL_WRONG_VERSION_NUMBER","tls_protocol",true],["PRIVATE_SOCKET_ERROR","other"]])assert.equal(classifyNetworkFailure({code,message:"MUST_NOT_ESCAPE"},tls),expected)});
test("HTTP metadata is bounded and Cloudflare colo discards the ray",()=>{const value=safeHttpResult("http1",302,{"cf-mitigated":"challenge",server:"cloudflare",location:"https://secret.invalid/token","content-type":"text/html; charset=utf-8","cf-ray":"abc123-LHR",cookie:"SECRET"});assert.deepEqual(value,{protocol:"http1",responseReceived:true,status:302,mitigationChallenge:true,cloudflareEdge:true,redirectPresent:true,contentKind:"html",cloudflareColo:"LHR"});assert.doesNotMatch(JSON.stringify(value),/abc123|secret|cookie|location/i);for(const ray of ["abc-lhr","abc-LHRA","1.2.3.4-LHR","host.example-LHR"])assert.equal(safeHttpResult("http2",403,{"cf-ray":ray}).cloudflareColo,undefined)});
test("Runner image installs a complete validated GAI policy without fixed service addresses",async()=>{const fs=await import("node:fs/promises"),docker=await fs.readFile(new URL("../Dockerfile",import.meta.url),"utf8"),gai=await fs.readFile(new URL("../gai.conf",import.meta.url),"utf8"),entries=gai.match(/^precedence\s+/gm)??[];assert.equal(entries.length,5);assert.match(gai,/::ffff:0:0\/96 100/);assert.match(docker,/CODEX_RUNNER_ADDRESS_POLICY=ipv4_preferred/);assert.match(docker,/test "\$\(grep -Ec/);assert.doesNotMatch(gai,/openai|cloudflare|(?:\d{1,3}\.){3}\d{1,3}/i);assert.doesNotMatch(docker,/NODE_TLS_REJECT_UNAUTHORIZED|method:"POST"|Mozilla|Chrome|Firefox|Safari/) });

for(const [libc,applies] of [["musl",false],["glibc",true],["unknown",null]])test(`Codex ${libc} libc has bounded address-policy semantics`,async()=>{const result=await diagnoseAuthEnvironment({environment:{CODEX_RUNNER_ADDRESS_POLICY:"ipv4_preferred",CODEX_RUNNER_CODEX_LIBC:"glibc"},readCodexLibcMarker:async()=>libc,lookupHost:async()=>[{address:"private-v4",family:4},{address:"private-v6",family:6}],connectHost:async()=>"ok",tlsHost:async()=>"ok",http1Head:async()=>({protocol:"http1",responseReceived:false,mitigationChallenge:false,cloudflareEdge:false,redirectPresent:false}),http2Head:async()=>({protocol:"http2",responseReceived:false,mitigationChallenge:false,cloudflareEdge:false,redirectPresent:false}),readSystemFile:async()=>"0",codexVersion:async()=>EXPECTED_CODEX_VERSION,accessPath:async()=>{}});assert.equal(result.runnerAddressPolicyEffective,true);assert.equal(result.systemResolverFirstFamily,"ipv4");assert.equal(result.codexNativeLibc,libc);assert.equal(result.codexAddressPolicyApplies,applies);assert.doesNotMatch(JSON.stringify(result),/private-v4|private-v6|ld-linux|libc\.so|\/opt\//)});

test("native libc classification comes only from the image marker",async()=>{const base={environment:{CODEX_RUNNER_ADDRESS_POLICY:"ipv4_preferred",CODEX_RUNNER_CODEX_LIBC:"glibc"},lookupHost:async()=>[],readSystemFile:async()=>"0",codexVersion:async()=>EXPECTED_CODEX_VERSION,accessPath:async()=>{}};for(const marker of ["", "bogus", "glibc extra"]){const result=await diagnoseAuthEnvironment({...base,readCodexLibcMarker:async()=>marker});assert.equal(result.codexNativeLibc,"unknown");assert.equal(result.codexAddressPolicyApplies,null)}const missing=await diagnoseAuthEnvironment({...base,readCodexLibcMarker:async()=>{throw new Error("missing")}});assert.equal(missing.codexNativeLibc,"unknown");assert.equal(missing.codexAddressPolicyApplies,null);const valid=await diagnoseAuthEnvironment({...base,environment:{...base.environment,CODEX_RUNNER_CODEX_LIBC:"musl"},readCodexLibcMarker:async()=>"glibc\n"});assert.equal(valid.codexNativeLibc,"glibc");assert.equal(valid.codexAddressPolicyApplies,true)});
