import test from "node:test";import assert from "node:assert/strict";import {mkdtemp,writeFile,chmod,rm} from "node:fs/promises";import {tmpdir} from "node:os";import {join} from "node:path";import {EventEmitter} from "node:events";import {PassThrough} from "node:stream";import {loadSecret} from "../dist/configuration.js";import {createRunnerServer,safeAuthDiagnosticsLog} from "../dist/server.js";import {AppServerRequestError,StdioAppServerClient} from "../dist/app-server-client.js";import {diagnoseAuthEnvironment,classifyNetworkFailure,EXPECTED_CODEX_VERSION} from "../dist/auth-environment-diagnostics.js";import {validateDeviceAuthSchemas,validateCodexTestSchemas,hasType} from "../dist/validate-device-auth-schema.js";
import schemaFixture from "./fixtures/codex-0.147-device-auth-schemas.json" with {type:"json"};
const offlineDiagnostics={environment:{},lookupHost:async()=>[],accessPath:async()=>{}};
const mock={async readiness(){return true},async status(){return{connected:true,authMode:"chatgpt",planType:"plus",accessToken:"MUST_NOT_ESCAPE"}},async startDeviceLogin(){return{loginId:"login",verificationUrl:"https://auth.openai.com/device",userCode:"ABCD",accessToken:"MUST_NOT_ESCAPE"}},async logout(){return{refreshToken:"MUST_NOT_ESCAPE"}},async close(){}};
async function withServer(fn,client=mock,diagnostics){const server=createRunnerServer({host:"127.0.0.1",port:1,sharedSecret:"correct",runnerVersion:"sha-test",codexCommand:"codex",requestBodyLimit:32,deviceAuthCompatible:true},client,diagnostics);await new Promise(r=>server.listen(0,"127.0.0.1",r));const {port}=server.address();try{await fn(`http://127.0.0.1:${port}`)}finally{await new Promise(r=>server.close(r))}}
function deviceAuthSchemas(){return structuredClone(schemaFixture.documents)}
function schema(documents,title){return documents.find(value=>value.schema.title===title).schema}
function clientDefinitions(documents){return schema(documents,"ClientRequest").definitions}
function requestBranch(documents,method){return schema(documents,"ClientRequest").oneOf.find(branch=>branch.properties.method.enum.includes(method))}
function responseVariant(documents){return schema(documents,"LoginAccountResponse").oneOf[0]}

test("curated rust-v0.147.0 embedded schema layout contains all device auth contracts",()=>assert.equal(validateDeviceAuthSchemas(deviceAuthSchemas()),true));
test("JSON Schema type detection handles scalar, union, and combinator forms without nested false positives",()=>{
 for(const value of [{type:"string"},{type:["string","null"]},{anyOf:[{type:"string"},{type:"null"}]},{oneOf:[{type:"null"},{type:"string"}]}])assert.equal(hasType(value,"string"),true);
 for(const value of [{type:"number"},{type:["number","null"]},{properties:{nested:{type:"string"}}},{anyOf:[{type:"number"},{type:"null"}]}])assert.equal(hasType(value,"string"),false);
});
test("embedded InitializeParams and GetAccountParams need no standalone documents",()=>{
 const documents=deviceAuthSchemas();
 assert.equal(documents.some(value=>["InitializeParams","GetAccountParams"].includes(value.schema.title)),false);
 assert.equal(validateDeviceAuthSchemas(documents),true);
});
test("optional ClientInfo title may be omitted, while its string/null union is accepted",()=>{
 const documents=deviceAuthSchemas();delete clientDefinitions(documents).ClientInfo.properties.title;
 assert.equal(validateDeviceAuthSchemas(documents),true);
});
for(const [method,error] of [["initialize","initialize_contract"],["account/read","account_read_contract"]])test(`unresolved ${method} params ref fails closed`,()=>{
 const documents=deviceAuthSchemas();requestBranch(documents,method).properties.params.$ref="#/definitions/Missing";
 assert.throws(()=>validateDeviceAuthSchemas(documents),new RegExp(error));
});
for(const field of ["name","version"])test(`ClientInfo ${field} must accept string and remain required`,()=>{
 let documents=deviceAuthSchemas();clientDefinitions(documents).ClientInfo.properties[field]={type:"number"};assert.throws(()=>validateDeviceAuthSchemas(documents),/initialize_contract/);
 documents=deviceAuthSchemas();clientDefinitions(documents).ClientInfo.required=clientDefinitions(documents).ClientInfo.required.filter(value=>value!==field);assert.throws(()=>validateDeviceAuthSchemas(documents),/initialize_contract/);
});
test("InitializeParams must require clientInfo",()=>{const documents=deviceAuthSchemas();clientDefinitions(documents).InitializeParams.required=[];assert.throws(()=>validateDeviceAuthSchemas(documents),/initialize_contract/)});
test("account/read refreshToken must accept boolean",()=>{const documents=deviceAuthSchemas();clientDefinitions(documents).GetAccountParams.properties.refreshToken={type:"string"};assert.throws(()=>validateDeviceAuthSchemas(documents),/account_read_contract/)});
test("RPC method tokens outside top-level ClientRequest variants do not establish routing",()=>{
 for(const method of ["initialize","account/read","account/login/start","account/logout"]){const documents=deviceAuthSchemas();schema(documents,"ClientRequest").oneOf=schema(documents,"ClientRequest").oneOf.filter(branch=>!branch.properties.method.enum.includes(method));clientDefinitions(documents).Unrelated={description:`supports ${method}`,properties:{method:{enum:[method]}}};assert.throws(()=>validateDeviceAuthSchemas(documents))}
});
test("a method branch cannot borrow another method's otherwise-valid params",()=>{const documents=deviceAuthSchemas();requestBranch(documents,"account/read").properties.params.$ref="#/definitions/InitializeParams";assert.throws(()=>validateDeviceAuthSchemas(documents),/account_read_contract/)});
test("cyclic and malformed local refs fail closed",()=>{for(const ref of ["#/definitions/Cycle","#/definitions/Bad~2Pointer","https://example.invalid/schema"]){const documents=deviceAuthSchemas();clientDefinitions(documents).Cycle={$ref:"#/definitions/Cycle"};requestBranch(documents,"initialize").properties.params={$ref:ref};assert.throws(()=>validateDeviceAuthSchemas(documents),/initialize_contract/)}});
test("logout accepts only optional null params from rust-v0.147.0",()=>{
 assert.equal(validateDeviceAuthSchemas(deviceAuthSchemas()),true);
 for(const mutation of [
  branch=>branch.properties.params={type:"object"},
  branch=>branch.required.push("params"),
  branch=>delete branch.properties.params
 ]){const documents=deviceAuthSchemas();mutation(requestBranch(documents,"account/logout"));assert.throws(()=>validateDeviceAuthSchemas(documents),/account_logout_contract/)}
});
test("device request discriminator must exist in both routed params and standalone LoginAccountParams",()=>{
 for(const target of ["embedded","standalone"]){const documents=deviceAuthSchemas();const login=target==="embedded"?clientDefinitions(documents).LoginAccountParams:schema(documents,"LoginAccountParams");login.oneOf[0].properties.type.enum=["missing"];documents.push({filename:"Unrelated.json",schema:{title:"Unrelated",token:"chatgptDeviceCode"}});assert.throws(()=>validateDeviceAuthSchemas(documents),/missing_request_contract/)}
});
for(const field of ["loginId","verificationUrl","userCode"]){
 test(`device response requires ${field} on its own variant`,()=>{const documents=deviceAuthSchemas();delete responseVariant(documents).properties[field];schema(documents,"LoginAccountResponse").oneOf[1].properties[field]={type:"string"};documents.push({filename:"Unrelated.json",schema:{properties:{[field]:{type:"string"}}}});assert.throws(()=>validateDeviceAuthSchemas(documents),new RegExp(`missing_${field}`))});
 test(`device response requires ${field} to accept string`,()=>{const documents=deviceAuthSchemas();responseVariant(documents).properties[field]={type:"number"};assert.throws(()=>validateDeviceAuthSchemas(documents),new RegExp(`missing_${field}`))});
 test(`device response requires ${field} in required`,()=>{const documents=deviceAuthSchemas();responseVariant(documents).required=responseVariant(documents).required.filter(value=>value!==field);assert.throws(()=>validateDeviceAuthSchemas(documents),new RegExp(`missing_${field}`))});
}
test("response discriminator and malformed document sets fail closed",()=>{let documents=deviceAuthSchemas();responseVariant(documents).properties.type.enum=["browser"];assert.throws(()=>validateDeviceAuthSchemas(documents),/response_contract/);for(const malformed of [[],[null],deviceAuthSchemas().filter(value=>value.schema.title!=="LoginAccountResponse")])assert.throws(()=>validateDeviceAuthSchemas(malformed))});
test("Runner source pins and validates the deterministic upstream GNU package",async()=>{const fs=await import("node:fs/promises"),docker=await fs.readFile(new URL("../Dockerfile",import.meta.url),"utf8"),readme=await fs.readFile(new URL("../README.md",import.meta.url),"utf8");assert.match(readme,/experimental GNU\/glibc build/);assert.match(readme,/neither release-equivalent nor an OpenAI-published GNU prebuilt artifact/);assert.equal(EXPECTED_CODEX_VERSION,"0.147.0");for(const required of [/be6e8eac029b183056b7e4402879f15d2c85f61b/,/--target x86_64-unknown-linux-gnu/,/--cargo-profile dev-small/,/CARGO_INCREMENTAL=0 CARGO_BUILD_JOBS=2/,/--package-dir \/out\/codex-package/,/\/out\/codex-package\/codex-package\.json/,/libcap-dev/,/codex-native-libc/,/COPY --from=codex-gnu-build \/out\/codex-package \/opt\/codex/])assert.match(docker,required);assert.doesNotMatch(docker,/V8_FROM_SOURCE=1/);assert.doesNotMatch(docker,/--cargo-profile release/);assert.doesNotMatch(docker,/npm install.*@openai\/codex|npm-musl-confirmation|CODEX_RUNNER_CODEX_LIBC|@openai\/codex@(?:latest|[~^*]|0\.147(?:\s|$)|0\.147\.0-)|@openai\/codex@0\.118\.0/)});
test("final image gates Codex setup and execution in diagnostic order",async()=>{const docker=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../Dockerfile",import.meta.url),"utf8")),runtime=docker.slice(docker.lastIndexOf("FROM node:24-bookworm-slim")),position=token=>{const index=runtime.indexOf(token);assert.notEqual(index,-1,`missing ${token}`);return index},home=position("mkdir -p /data/codex"),path=position("ln -s /opt/codex/bin/codex /usr/local/bin/codex"),runtimePackage=position("apt-get install -y --no-install-recommends libssl3 ca-certificates"),ldd=position("ldd /opt/codex/bin/codex"),version=position("codex --version"),schema=position("validate-device-auth-schema.js codex"),marker=position("printf 'glibc\\n' >/etc/codex-runner/codex-native-libc");assert.ok(home<path&&path<runtimePackage&&runtimePackage<ldd&&ldd<version&&version<schema&&schema<marker);assert.match(runtime,/command -v codex/);assert.match(runtime,/test ! -e \/usr\/bin\/codex/);assert.match(runtime,/test ! -e \/usr\/local\/lib\/node_modules\/@openai\/codex/);assert.match(runtime,/codex_runtime_missing_soname=/);assert.match(runtime,/codex_runtime_ldd_failed/);assert.match(runtime,/grep -Fq 'not found'/);assert.doesNotMatch(runtime,/apt-get install[^\n]*(?:libssl-dev|build-essential|clang|pkg-config|git|libcap-dev|openssl(?:[[:space:]]|$))/)});
test("loads direct and Docker secret-file configuration",async()=>{assert.equal(await loadSecret({CODEX_RUNNER_SHARED_SECRET:" direct "})," direct ");const dir=await mkdtemp(join(tmpdir(),"runner-")),file=join(dir,"secret");await writeFile(file,"file secret\n");assert.equal(await loadSecret({CODEX_RUNNER_SHARED_SECRET_FILE:file}),"file secret")});
test("secret configuration fails closed",async()=>{await assert.rejects(loadSecret({}),/missing/);await assert.rejects(loadSecret({CODEX_RUNNER_SHARED_SECRET:"x",CODEX_RUNNER_SHARED_SECRET_FILE:"x"}),/ambiguous/);await assert.rejects(loadSecret({CODEX_RUNNER_SHARED_SECRET_FILE:"/missing"}),/unreadable/);const dir=await mkdtemp(join(tmpdir(),"runner-")),empty=join(dir,"empty"),unreadable=join(dir,"unreadable");await writeFile(empty,"");await writeFile(unreadable,"x");await chmod(unreadable,0);await assert.rejects(loadSecret({CODEX_RUNNER_SHARED_SECRET_FILE:empty}),/empty/);await assert.rejects(loadSecret({CODEX_RUNNER_SHARED_SECRET_FILE:unreadable},async()=>{throw new Error("denied")}),/unreadable/)});
test("health is public and v1 requires the correct secret",()=>withServer(async base=>{assert.deepEqual(await (await fetch(base+"/health")).json(),{ok:true});assert.equal((await fetch(base+"/v1/capabilities")).status,401);assert.equal((await fetch(base+"/v1/capabilities",{headers:{"x-codex-runner-secret":"wrong"}})).status,401);const response=await fetch(base+"/v1/capabilities",{headers:{"x-codex-runner-secret":"correct"}});assert.equal(response.status,200);assert.deepEqual(await response.json(),{protocolVersion:1,runnerVersion:"sha-test",codexAvailable:true,deviceAuth:true,jobExecution:false})}));
test("auth abstractions allow only safe fields",()=>withServer(async base=>{const headers={"x-codex-runner-secret":"correct","content-type":"application/json"};for(const [path,method] of [["/v1/auth/status","GET"],["/v1/auth/device/start","POST"],["/v1/auth/logout","POST"]]){const response=await fetch(base+path,{method,headers});assert.equal(response.status,200);assert.doesNotMatch(await response.text(),/MUST_NOT_ESCAPE|accessToken|refreshToken/)}const ceremony=await (await fetch(base+"/v1/auth/device/start",{method:"POST",headers})).json();assert.deepEqual(ceremony,{loginId:"login",verificationUrl:"https://auth.openai.com/device",userCode:"ABCD"})}));
test("device ceremony rejects missing or unsafe exact 0.147 fields",async()=>{for(const result of [{verificationUrl:"https://auth.openai.com/device",userCode:"CODE"},{loginId:"id",userCode:"CODE"},{loginId:"id",verificationUrl:"https://auth.openai.com/device"},{loginId:"id",verificationUrl:"http://auth.openai.com/device",userCode:"CODE"},{loginId:"id",verificationUrl:"https://not-openai.example/device",userCode:"CODE"},{id:"legacy",verificationUri:"https://auth.openai.com/device",userCode:"CODE"}])await withServer(async base=>{const response=await fetch(base+"/v1/auth/device/start",{method:"POST",headers:{"x-codex-runner-secret":"correct","content-type":"application/json"}});assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:"device_auth_start_failed",deviceAuthReason:"device_auth_unknown"})},{...mock,async startDeviceLogin(){return result}})});
test("body limits and App Server errors are sanitized",()=>withServer(async base=>fetch(base+"/v1/auth/logout",{method:"POST",headers:{"x-codex-runner-secret":"correct","content-type":"application/json"},body:JSON.stringify({value:"a".repeat(40)})}).then(async response=>{assert.equal(response.status,413);assert.deepEqual(await response.json(),{error:"request_too_large"})})));
test("raw App Server failures never escape",()=>withServer(async base=>{const response=await fetch(base+"/v1/auth/status",{headers:{"x-codex-runner-secret":"correct"}});assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:"codex_auth_unavailable"})},{...mock,async status(){throw new Error("token=SECRET raw stack")}}));
test("failed device start returns and logs only bounded safe classification",async()=>{const logs=[],original=console.error;console.error=value=>logs.push(value);try{await withServer(async base=>{const response=await fetch(base+"/v1/auth/device/start",{method:"POST",headers:{"x-codex-runner-secret":"correct","content-type":"application/json"}});assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:"device_auth_start_failed",deviceAuthReason:"device_auth_unknown"})},{...mock,async startDeviceLogin(){throw new Error("raw App Server message token=ACCESS redirect=https://evil.invalid")}})}finally{console.error=original}assert.equal(logs.length,1);assert.deepEqual(JSON.parse(logs[0]),{level:"error",event:"runner_operation_failed",operation:"POST /v1/auth/device/start",category:"device_auth_start_failed",deviceAuthReason:"device_auth_unknown"});assert.doesNotMatch(logs.join(""),/ACCESS|evil|raw App Server/)});
test("safe device failure metadata reaches the bounded response and log",async()=>{const logs=[],original=console.error;console.error=value=>logs.push(value);try{await withServer(async base=>{const response=await fetch(base+"/v1/auth/device/start",{method:"POST",headers:{"x-codex-runner-secret":"correct","content-type":"application/json"}});assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:"device_auth_start_failed",deviceAuthReason:"device_auth_rate_limited",upstreamHttpStatus:429,jsonRpcCode:-32000})},{...mock,async startDeviceLogin(){throw new AppServerRequestError("device_auth_rate_limited",-32000,429)}})}finally{console.error=original}assert.deepEqual(JSON.parse(logs[0]),{level:"error",event:"runner_operation_failed",operation:"POST /v1/auth/device/start",category:"device_auth_start_failed",deviceAuthReason:"device_auth_rate_limited",upstreamHttpStatus:429,jsonRpcCode:-32000})});
test("real wire initializes once before account requests with documented framing",async()=>{const input=new PassThrough(),output=new PassThrough(),stderr=new PassThrough(),child=Object.assign(new EventEmitter(),{stdin:input,stdout:output,stderr,killed:false,kill(){this.killed=true;this.emit("exit",0)}});const sent=[];let buffered="";input.on("data",chunk=>{buffered+=chunk;for(;;){const newline=buffered.indexOf("\n");if(newline<0)break;const message=JSON.parse(buffered.slice(0,newline));buffered=buffered.slice(newline+1);sent.push(message);if(message.id)output.write(`${JSON.stringify({id:message.id,result:message.method==="account/read"?{account:null}:{}})}\n`)}});const client=new StdioAppServerClient("codex","runner-sha",100,()=>child);assert.deepEqual(await client.status(),{account:null});assert.deepEqual(await client.status(),{account:null});assert.deepEqual(sent.map(value=>value.method),["initialize","initialized","account/read","account/read"]);assert.deepEqual(sent[0],{method:"initialize",id:1,params:{clientInfo:{name:"adt_codex_runner",title:"ADT Codex Runner",version:"runner-sha"}}});assert.deepEqual(sent[1],{method:"initialized"});assert.deepEqual(sent[2].params,{refreshToken:false});assert.equal(sent.some(value=>"jsonrpc" in value),false);await client.close()});
test("real wire omits params from the account/logout request",async()=>{const input=new PassThrough(),output=new PassThrough(),stderr=new PassThrough(),child=Object.assign(new EventEmitter(),{stdin:input,stdout:output,stderr,killed:false,kill(){this.killed=true;this.emit("exit",0)}}),sent=[];input.on("data",chunk=>{for(const line of chunk.toString().trim().split("\n")){const message=JSON.parse(line);sent.push(message);if(message.id)output.write(`${JSON.stringify({id:message.id,result:{}})}\n`)}});const client=new StdioAppServerClient("codex","runner-sha",100,()=>child);await client.logout();const message=sent.find(value=>value.method==="account/logout");assert.equal(typeof message.id,"number");assert.equal(Object.hasOwn(message,"params"),false);await client.close()});
test("real wire sends device-code framing and maps its response",async()=>{const input=new PassThrough(),output=new PassThrough(),stderr=new PassThrough(),child=Object.assign(new EventEmitter(),{stdin:input,stdout:output,stderr,killed:false,kill(){this.killed=true;this.emit("exit",0)}}),sent=[];input.on("data",chunk=>{for(const line of chunk.toString().trim().split("\n")){const message=JSON.parse(line);sent.push(message);if(message.id)output.write(`${JSON.stringify({id:message.id,result:message.method==="account/login/start"?{loginId:"login-1",verificationUrl:"https://auth.openai.com/device",userCode:"SAFE-CODE"}:{}})}\n`)}});const client=new StdioAppServerClient("codex","runner-sha",100,()=>child);assert.deepEqual(await client.startDeviceLogin(),{loginId:"login-1",verificationUrl:"https://auth.openai.com/device",userCode:"SAFE-CODE"});assert.deepEqual(sent.find(value=>value.method==="account/login/start"),{method:"account/login/start",id:2,params:{type:"chatgptDeviceCode"}});await client.close()});
for(const [message,reason,status] of [["ChatGPT login is disabled. Use API key login instead.","chatgpt_login_disabled",undefined],["device code login is not enabled for this Codex server. Use the browser login or verify the server URL.","device_auth_not_enabled",undefined],["failed to request device code: device code request failed with status 403 Forbidden","device_auth_upstream_forbidden",403],["failed to request device code: device code request failed with status 429 Too Many Requests","device_auth_rate_limited",429],["failed to request device code: device code request failed with status 500 Internal Server Error","device_auth_upstream_unavailable",500],["failed to request device code: device code request failed with status 502 Bad Gateway","device_auth_upstream_unavailable",502],["failed to request device code: device code request failed with status 503 Service Unavailable","device_auth_upstream_unavailable",503],["failed to request device code: device code request failed with status 404 Not Found","device_auth_upstream_rejected",404],["failed to request device code: device code request failed with status 403","device_auth_upstream_forbidden",403]])test(`classifies exact App Server failure as ${reason}`,async()=>{const input=new PassThrough(),output=new PassThrough(),stderr=new PassThrough(),child=Object.assign(new EventEmitter(),{stdin:input,stdout:output,stderr,killed:false,kill(){this.killed=true;this.emit("exit",0)}});input.on("data",chunk=>{for(const line of chunk.toString().trim().split("\n")){const request=JSON.parse(line);if(request.id)output.write(`${JSON.stringify(request.method==="initialize"?{id:request.id,result:{}}:{id:request.id,error:{code:-32603,message,data:{accessToken:"SECRET"}}})}\n`)}});const client=new StdioAppServerClient("codex","runner-sha",100,()=>child);await assert.rejects(client.startDeviceLogin(),error=>{assert.equal(error.message,"app_server_request_failed");assert.equal(error.reason,reason);assert.equal(error.jsonRpcCode,-32603);assert.equal(error.upstreamHttpStatus,status);assert.doesNotMatch(JSON.stringify(error),/SECRET|evil|private|Forbidden|Requests|Server|Gateway|Unavailable|Not Found/);return true});await client.close()});
for(const message of ["ChatGPT login is disabled","ChatGPT login is disabled. Use API key login instead. token=SECRET","prefix ChatGPT login is disabled. Use API key login instead.","device code login is not enabled","device code login is not enabled for this Codex server. Use the browser login or verify the server URL. suffix=SECRET","failed to request device code: device code request failed with status 099","failed to request device code: device code request failed with status 600","failed to request device code: device code request failed with status nope","failed to request device code: device code request failed with status 403 Too Many Requests","failed to request device code: device code request failed with status 403 Forbidden suffix=SECRET","failed to request device code: device code request failed with status 403 Forbidden https://evil.invalid/private/path?token=SECRET","failed to request device code: device code request failed with status 403 token=SECRET","prefix failed to request device code: device code request failed with status 403 Forbidden","device code request failed with status 403 Forbidden","unknown token=SECRET https://evil.invalid /private/path"])test("near-match App Server failure remains generic",async()=>{const input=new PassThrough(),output=new PassThrough(),stderr=new PassThrough(),child=Object.assign(new EventEmitter(),{stdin:input,stdout:output,stderr,killed:false,kill(){this.killed=true;this.emit("exit",0)}});input.on("data",chunk=>{for(const line of chunk.toString().trim().split("\n")){const request=JSON.parse(line);if(request.id)output.write(`${JSON.stringify(request.method==="initialize"?{id:request.id,result:{}}:{id:request.id,error:{code:-32603,message,data:{accessToken:"SECRET"}}})}\n`)}});const client=new StdioAppServerClient("codex","runner-sha",100,()=>child);await assert.rejects(client.startDeviceLogin(),error=>{assert.equal(error.message,"app_server_request_failed");assert.equal(error.reason,"device_auth_internal");assert.equal(error.jsonRpcCode,-32603);assert.equal(error.upstreamHttpStatus,undefined);assert.doesNotMatch(JSON.stringify(error),/SECRET|evil|private|failed to request|Forbidden|Requests/);return true});await client.close()});
async function classifyMessage(message){const input=new PassThrough(),output=new PassThrough(),stderr=new PassThrough(),child=Object.assign(new EventEmitter(),{stdin:input,stdout:output,stderr,killed:false,kill(){this.killed=true;this.emit("exit",0)}});input.on("data",chunk=>{for(const line of chunk.toString().trim().split("\n")){const request=JSON.parse(line);if(request.id)output.write(`${JSON.stringify(request.method==="initialize"?{id:request.id,result:{}}:{id:request.id,error:{code:-32603,message}})}\n`)}});const client=new StdioAppServerClient("codex","runner-sha",100,()=>child);try{await client.startDeviceLogin()}catch(error){return error}finally{await client.close()}throw new Error("expected failure")}
for(const [message,reason] of [["failed to request device code: error sending request for url (https://auth.openai.com/api/accounts/deviceauth/usercode)","device_auth_transport_error"],["failed to request device code: Failed to read CA certificate file /private/ca.pem selected by CODEX_CA_CERTIFICATE: permission denied","device_auth_ca_configuration"],["failed to request device code: Failed to load CA certificates from /private/ca.pem selected by SSL_CERT_FILE: invalid PEM","device_auth_ca_configuration"],["failed to request device code: Failed to parse certificate #2 from /private/ca.pem selected by CODEX_CA_CERTIFICATE: invalid certificate","device_auth_ca_configuration"],["failed to request device code: Failed to register certificate #1 from /private/ca.pem selected by SSL_CERT_FILE in rustls root store: rejected","device_auth_ca_configuration"],["failed to request device code: Failed to build HTTP client while using CA bundle from /private/ca.pem selected by CODEX_CA_CERTIFICATE: client error","device_auth_http_client_configuration"],["failed to request device code: Failed to build HTTP client while using system root certificates: client error","device_auth_http_client_configuration"]])test(`classifies pinned Codex failure as ${reason}`,async()=>{const error=await classifyMessage(message);assert.equal(error.reason,reason);assert.equal(error.jsonRpcCode,-32603);assert.doesNotMatch(JSON.stringify(error),/private|permission|PEM|certificate|client error|auth\.openai/)})
for(const message of ["failed to request device code: error sending request for url (https://evil.invalid/api/accounts/deviceauth/usercode)","failed to request device code: error sending request for url (https://auth.openai.com/api/accounts/deviceauth/usercode) token=SECRET","failed to request device code: Failed to read CA certificate file /private/ca.pem selected by OTHER_VARIABLE: permission denied","prefix failed to request device code: Failed to build HTTP client while using system root certificates: client error"])test("near-match transport and CA failures remain generic",async()=>{const error=await classifyMessage(message);assert.equal(error.reason,"device_auth_internal");assert.doesNotMatch(JSON.stringify(error),/evil|SECRET|private|client error/)})

test("malformed JSON-RPC errors remain generic",async()=>{for(const error of [null,{code:null,message:"device code request failed with status 403"},{code:1.5,message:"device code request failed with status 403"},{code:-32000,message:42}]){const input=new PassThrough(),output=new PassThrough(),stderr=new PassThrough(),child=Object.assign(new EventEmitter(),{stdin:input,stdout:output,stderr,killed:false,kill(){this.killed=true;this.emit("exit",0)}});input.on("data",chunk=>{for(const line of chunk.toString().trim().split("\n")){const request=JSON.parse(line);if(request.id)output.write(`${JSON.stringify(request.method==="initialize"?{id:request.id,result:{}}:{id:request.id,error})}\n`)}});const client=new StdioAppServerClient("codex","runner-sha",100,()=>child);await assert.rejects(client.startDeviceLogin(),failure=>failure.message==="app_server_request_failed"&&!(failure instanceof AppServerRequestError));await client.close()}});
test("RPC timeout clears pending work and a later process can restart",async()=>{let spawns=0;const spawn=()=>{spawns++;const child=Object.assign(new EventEmitter(),{stdin:new PassThrough(),stdout:new PassThrough(),stderr:new PassThrough(),killed:false,kill(){this.killed=true;this.emit("exit",0)}});return child};const client=new StdioAppServerClient("codex","test",10,spawn);assert.equal(await client.readiness(),false);assert.equal(await client.readiness(),false);assert.equal(spawns,2);await client.close()});


test("Runner image installs a complete validated GAI policy without fixed service addresses",async()=>{const fs=await import("node:fs/promises"),docker=await fs.readFile(new URL("../Dockerfile",import.meta.url),"utf8"),gai=await fs.readFile(new URL("../gai.conf",import.meta.url),"utf8"),entries=gai.match(/^precedence\s+/gm)??[];assert.equal(entries.length,5);assert.match(gai,/::ffff:0:0\/96 100/);assert.match(docker,/CODEX_RUNNER_ADDRESS_POLICY=ipv4_preferred/);assert.match(docker,/test "\$\(grep -Ec/);assert.doesNotMatch(gai,/openai|cloudflare|(?:\d{1,3}\.){3}\d{1,3}/i);assert.doesNotMatch(docker,/NODE_TLS_REJECT_UNAUTHORIZED|method:"POST"|Mozilla|Chrome|Firefox|Safari/) });




test("final image and smoke gate the packaged Debian trust store without logging it",async()=>{const fs=await import("node:fs/promises"),docker=await fs.readFile(new URL("../Dockerfile",import.meta.url),"utf8"),smoke=await fs.readFile(new URL("../scripts/smoke-image.sh",import.meta.url),"utf8"),runtime=docker.slice(docker.lastIndexOf("FROM node:24-bookworm-slim"));assert.match(runtime,/apt-get install -y --no-install-recommends libssl3 ca-certificates/);assert.doesNotMatch(runtime,/apt-get install[^\n]*(?:libssl-dev|openssl(?:[[:space:]]|$))/);for(const source of [runtime,smoke]){assert.match(source,/dpkg-query[^\n]*ca-certificates/);assert.match(source,/test -r \/etc\/ssl\/certs\/ca-certificates\.crt/);assert.match(source,/test -s \/etc\/ssl\/certs\/ca-certificates\.crt/);assert.match(source,/grep -m 1 -Fq -- ["']-----BEGIN CERTIFICATE-----["']/);assert.doesNotMatch(source,/cat \/etc\/ssl\/certs|openssl x509|fingerprint|subject/)}assert.ok(smoke.includes('-f="\\${Status}\\n" ca-certificates'));assert.ok(smoke.includes('-f="\\${Status}\\n" libssl3'));assert.ok(!smoke.includes('-f="${Status}\\n"'));assert.ok(smoke.indexOf("trap cleanup EXIT")<smoke.indexOf("if ! docker run"));assert.match(smoke,/runner_smoke_system_ca_gate_failed/)});

test("image smoke script has valid Bash syntax",async()=>{const {execFileSync}=await import("node:child_process");assert.doesNotThrow(()=>execFileSync("bash",["-n",new URL("../scripts/smoke-image.sh",import.meta.url).pathname]))});

test("inner smoke shell passes the literal dpkg status format",async()=>{const {execFileSync}=await import("node:child_process"),directory=await mkdtemp(join(tmpdir(),"adt-dpkg-format-")),fake=join(directory,"dpkg-query");try{await writeFile(fake,'#!/bin/sh\nprintf "%s" "$2"\n');await chmod(fake,0o755);const format=execFileSync("/bin/sh",["-c",'dpkg-query -W -f="\\${Status}\\n" ca-certificates'],{encoding:"utf8",env:{PATH:directory}});assert.equal(format,'-f=${Status}\\n')}finally{await rm(directory,{recursive:true,force:true})}});


// Test Codex uses a deterministic fake transport; no test contacts OpenAI.
import {access} from "node:fs/promises";
import testSchemaFixture from "./fixtures/codex-0.147-test-schemas.json" with {type:"json"};
function healthFake(mode="success",requestId="approval-1"){
 const child=Object.assign(new EventEmitter(),{stdin:new PassThrough(),stdout:new PassThrough(),stderr:new PassThrough(),killed:false,kill(){this.killed=true}}),requests=[],cwds=[];
 const send=value=>child.stdout.write(`${JSON.stringify(value)}\n`);
 child.stdin.on("data",chunk=>{
  for(const line of chunk.toString().trim().split("\n")){
   if(!line)continue;
   const message=JSON.parse(line);requests.push(message);
   if(!message.id)continue;
   if(message.method==="initialize")send({id:message.id,result:{}});
   else if(message.method==="account/read"){if(mode==="account_failure")send({id:message.id,error:{code:-32603,message:"private raw error"}});else send({id:message.id,result:{account:{type:"chatgpt"}}})}
   else if(message.method==="thread/start"){
    cwds.push(message.params.cwd);
    if(mode==="thread_failure")send({id:message.id,error:{code:-32603,message:"private raw error"}});else send({id:message.id,result:mode==="bad_thread"?{}:{thread:{id:"thread-secret"}}});
   }else if(message.method==="turn/start"){
    const nonce=message.params.input[0].text.match(/ADT_CODEX_TEST_[a-f0-9]+/)?.[0];
    if(mode==="turn_failure")send({id:message.id,error:{code:-32603,message:"private raw error"}});
    else if(mode==="bad_turn")send({id:message.id,result:{}});
    else if(mode==="approval"||mode==="collision"){
     send({id:mode==="collision"?message.id:requestId,method:"item/commandExecution/requestApproval",params:{threadId:"thread-secret",turnId:"turn-secret",itemId:"item-secret"}});
     setImmediate(()=>send({id:message.id,result:{turn:{id:"turn-secret"}}}));
    }else{
     send({id:message.id,result:{turn:{id:"turn-secret"}}});
     setImmediate(()=>{
      if(mode==="pending"||mode==="timeout")return;
      if(mode==="tool")send({method:"item/started",params:{threadId:"thread-secret",turnId:"turn-secret",item:{type:"fileChange"}}});
      else{send({method:"item/completed",params:{threadId:"thread-secret",turnId:"turn-secret",item:{type:"agentMessage",text:mode==="wrong"?"wrong":nonce}}});send({method:"turn/completed",params:{threadId:"thread-secret",turn:{id:"turn-secret",status:mode==="failed"?"failed":"completed"}}})}
     });
    }
   }else if(message.method==="turn/interrupt")send({id:message.id,result:{}});
  }
 });
 const release=()=>{const turn=requests.filter(x=>x.method==="turn/start").at(-1),nonce=turn?.params.input[0].text.match(/ADT_CODEX_TEST_[a-f0-9]+/)?.[0];send({method:"item/completed",params:{threadId:"thread-secret",turnId:"turn-secret",item:{type:"agentMessage",text:nonce}}});send({method:"turn/completed",params:{threadId:"thread-secret",turn:{id:"turn-secret",status:"completed"}}})};
 return{child,requests,cwds,release};
}
async function healthRun(mode,requestId,healthTimeout=100){const fake=healthFake(mode,requestId),client=new StdioAppServerClient("codex","test",50,()=>fake.child,healthTimeout),result=await client.testCodex();return{...fake,result}}
test("curated exact 0.147 health schemas exercise routed safety contracts",()=>{assert.equal(testSchemaFixture.source.version,"0.147.0");assert.equal(testSchemaFixture.source.commit,"be6e8eac029b183056b7e4402879f15d2c85f61b");assert.equal(validateCodexTestSchemas(testSchemaFixture.documents),true);for(const mutate of [d=>d.find(x=>x.schema.title==="ClientRequest").schema.oneOf.pop(),d=>delete d.find(x=>x.schema.title==="ThreadStartParams").schema.properties.ephemeral,d=>d.find(x=>x.schema.title==="ThreadStartParams").schema.properties.sandbox.oneOf[0].enum=[],d=>{delete d.find(x=>x.schema.title==="ItemCompletedNotification").schema.properties.item;delete d.find(x=>x.schema.title==="ItemStartedNotification").schema.properties.item}]){const docs=structuredClone(testSchemaFixture.documents);mutate(docs);assert.throws(()=>validateCodexTestSchemas(docs))}});
test("health tester uses one safest thread, one nonce turn, and cleans cwd",async()=>{const run=await healthRun("success");assert.equal(run.result.ok,true);const thread=run.requests.find(x=>x.method==="thread/start"),turns=run.requests.filter(x=>x.method==="turn/start");assert.deepEqual({approvalPolicy:thread.params.approvalPolicy,sandbox:thread.params.sandbox,ephemeral:thread.params.ephemeral},{approvalPolicy:"never",sandbox:"read-only",ephemeral:true});assert.match(thread.params.cwd,/^\/tmp\/adt-codex-test-/);assert.equal(turns.length,1);assert.match(turns[0].params.input[0].text,/ADT_CODEX_TEST_[a-f0-9]{36}/);await assert.rejects(access(thread.params.cwd))});
for(const[mode,reason]of[["account_failure","app_server_unavailable"],["thread_failure","thread_start_failed"],["bad_thread","thread_start_failed"],["turn_failure","turn_start_failed"],["bad_turn","turn_start_failed"],["failed","turn_failed"],["wrong","unexpected_output"],["tool","unexpected_tool_activity"],["approval","unexpected_tool_activity"]])test(`health tester bounds ${mode} as ${reason}`,async()=>{const run=await healthRun(mode);assert.deepEqual(run.result,{ok:false,reason});assert.ok(run.requests.filter(x=>x.method==="thread/start").length<=1);assert.ok(run.requests.filter(x=>x.method==="turn/start").length<=1);for(const cwd of run.cwds)await assert.rejects(access(cwd));assert.doesNotMatch(JSON.stringify(run.result),/secret|ADT_CODEX_TEST|raw/)});
test("health tester refuses disconnected accounts before a thread",async()=>{const fake=healthFake();fake.child.stdin.removeAllListeners("data");fake.child.stdin.on("data",chunk=>{for(const line of chunk.toString().trim().split("\n")){const m=JSON.parse(line);fake.requests.push(m);if(m.id)fake.child.stdout.write(`${JSON.stringify({id:m.id,result:m.method==="account/read"?{account:null}:{}})}\n`)}});const result=await new StdioAppServerClient("codex","test",50,()=>fake.child,10).testCodex();assert.deepEqual(result,{ok:false,reason:"codex_not_connected"});assert.equal(fake.requests.some(x=>x.method==="thread/start"),false)});
for(const id of [3,"server-request-id"])test(`server request id ${typeof id} is shape-dispatched and fails closed`,async()=>{const run=await healthRun("collision",id);assert.deepEqual(run.result,{ok:false,reason:"unexpected_tool_activity"});assert.equal(run.requests.filter(x=>x.method==="turn/start").length,1);assert.equal(run.requests.filter(x=>x.method==="turn/interrupt").length,1);assert.equal(run.requests.some(x=>x.result&&x.id===id),false)});
test("health timeout is deterministic, interrupts once, cleans up, and ignores stale completion",async()=>{const fake=healthFake("timeout"),client=new StdioAppServerClient("codex","test",50,()=>fake.child,5),first=await client.testCodex();assert.deepEqual(first,{ok:false,reason:"timeout"});assert.equal(fake.requests.filter(x=>x.method==="turn/start").length,1);assert.equal(fake.requests.filter(x=>x.method==="turn/interrupt").length,1);for(const cwd of fake.cwds)await assert.rejects(access(cwd));fake.release();const third=client.testCodex();while(fake.requests.filter(x=>x.method==="turn/start").length<2)await new Promise(r=>setImmediate(r));fake.release();assert.equal((await third).ok,true)});
test("health single-flight rejects overlap and releases the guard",async()=>{const fake=healthFake("pending"),client=new StdioAppServerClient("codex","test",50,()=>fake.child,100),first=client.testCodex();while(!fake.requests.some(x=>x.method==="turn/start"))await new Promise(r=>setImmediate(r));assert.deepEqual(await client.testCodex(),{ok:false,reason:"test_in_progress"});assert.equal(fake.requests.filter(x=>x.method==="thread/start").length,1);assert.equal(fake.requests.filter(x=>x.method==="turn/start").length,1);fake.release();assert.equal((await first).ok,true);const third=client.testCodex();while(fake.requests.filter(x=>x.method==="turn/start").length<2)await new Promise(r=>setImmediate(r));fake.release();assert.equal((await third).ok,true);assert.equal(fake.requests.filter(x=>x.method==="turn/start").length,2)});

test("reduced diagnostics keep finite address-family, CA, policy, HEAD and home checks",async()=>{const calls=[],result=await diagnoseAuthEnvironment({environment:{CODEX_RUNNER_ADDRESS_POLICY:"ipv4_preferred",HTTP_PROXY:"configured",CODEX_HOME:"/private/home"},lookupHost:async()=>[{address:"private-v4",family:4},{address:"private-v6",family:6}],connectHost:async(_h,_p,f)=>{calls.push(["tcp",f]);return f===4?"ok":"failed"},tlsHost:async(_h,_p,f)=>{calls.push(["tls",f]);return f===4?"ok":"timeout"},deviceAuthHead:async()=>({responseReceived:true,status:405}),accessPath:async()=>{},statPath:async()=>({isFile:()=>true,size:10}),readSystemFile:async path=>path.includes("codex-native-libc")?"glibc":"0",codexVersion:async()=>"0.147.0",codexAppServerReady:async()=>true});assert.equal(result.codexAppServerReady,true);assert.equal(result.codexVersionMatchesExpected,true);assert.equal(result.systemResolverFirstFamily,"ipv4");assert.equal(result.runnerAddressPolicyEffective,true);assert.equal(result.ipv4TlsConnectivity,"ok");assert.equal(result.ipv6TlsConnectivity,"timeout");assert.deepEqual(result.deviceAuthRoute,{responseReceived:true,status:405});assert.equal(result.systemCaBundlePresent,true);assert.equal(result.httpProxyConfigured,true);assert.deepEqual(calls,[["tcp",4],["tcp",6],["tls",4],["tls",6]]);assert.doesNotMatch(JSON.stringify(result),/private-v4|private-v6|private\/home|configured/)});
test("reduced diagnostics skip route HEAD without IPv4 and log only bounded environment fields",async()=>{let head=false;const result=await diagnoseAuthEnvironment({...offlineDiagnostics,deviceAuthHead:async()=>{head=true;return{responseReceived:true,status:200}},statPath:async()=>({isFile:()=>false,size:0}),readSystemFile:async()=>"0"});assert.equal(head,false);assert.deepEqual(result.deviceAuthRoute,{responseReceived:false});const log=safeAuthDiagnosticsLog(result);assert.equal(log.event,"auth_environment_diagnostics");assert.deepEqual(Object.keys(log),["level","event","codexReady","systemCaAvailable","ipv4Tls","ipv6Tls","proxyConfigured"]);assert.doesNotMatch(JSON.stringify(log),/address|url|header|body|error|secret/i)});
test("cleanup sources contain HEAD only and no retired auth experiments",async()=>{const fs=await import("node:fs/promises"),source=(await Promise.all(["../src/auth-environment-diagnostics.ts","../src/app-server-client.ts","../Dockerfile","../scripts/smoke-image.sh"].map(p=>fs.readFile(new URL(p,import.meta.url),"utf8")))).join("\n");assert.match(source,/method:"HEAD"/);assert.doesNotMatch(source,/adt-codex-auth-probe|method:"POST"|client_id|rustlsTls|namedUserAgent|http1Only|forcedIpv4|respect_system_proxy|MALFORMED_BODY/)});
test("network errors retain a finite secret-free classification",()=>{for(const [code,expected,tls=false] of [["ENETUNREACH","network_unreachable"],["EADDRNOTAVAIL","address_unavailable"],["ECONNREFUSED","connection_refused"],["ECONNRESET","connection_reset"],["ETIMEDOUT","timeout"],["CERT_HAS_EXPIRED","certificate",true],["ERR_SSL_BAD","tls_protocol",true],["PRIVATE","other"]])assert.equal(classifyNetworkFailure({code,message:"secret"},tls),expected)});
