import test from "node:test";import assert from "node:assert/strict";import {EventEmitter} from "node:events";import {PassThrough} from "node:stream";import {classifySandboxFailure,diagnoseSandbox,sandboxProbeArguments,SANDBOX_DIAGNOSTIC_OUTPUT_LIMIT} from "../dist/sandbox-diagnostics.js";import {deferred,withDeadline} from "./async-test-helpers.mjs";
const environment=(sandbox="workspace-write")=>({key:"artifact-dev-toolkit",name:"ADT",cwd:"/tmp",enabled:true,ready:true,sandbox});
function probe({code=1,stderr="",stdout="",error,hang=false,closeOnKill=true,lateError=false,lateDelivered}={}){return(_command,args,options)=>{const child=Object.assign(new EventEmitter(),{stdout:new PassThrough(),stderr:new PassThrough(),killed:false,kill(signal){this.killed=signal==="SIGKILL";if(closeOnKill)queueMicrotask(()=>this.emit("close",null,signal));return closeOnKill}});child.invocation={args,options};queueMicrotask(()=>{if(error)return child.emit("error",Object.assign(new Error("RAW SECRET"),{code:error}));child.stdout.end(stdout);child.stderr.end(stderr);if(!hang)child.emit("close",code);else if(lateError)setTimeout(()=>{child.emit("close",1);child.emit("error",new Error("LATE SECRET"));lateDelivered?.resolve()},30)});return child}}
test("pinned 0.147 parser receives no Linux selector and executes only the fixed no-op",()=>{for(const sandbox of ["read-only","workspace-write"]){const args=sandboxProbeArguments(environment(sandbox));assert.deepEqual(args,["-c",`sandbox_mode=\"${sandbox}\"`,"sandbox","--","true"]);assert.equal(args.includes("linux"),false)}});
test("read-only and workspace-write probes reproduce the environment policy",async()=>{for(const sandbox of ["read-only","workspace-write"]){let child;const spawn=(...args)=>(child=probe({code:0})(...args));const value=await diagnoseSandbox(environment(sandbox),"codex",spawn);assert.deepEqual(child.invocation.args,["-c",`sandbox_mode=\"${sandbox}\"`,"sandbox","--","true"]);assert.equal(child.invocation.options.cwd,"/tmp");assert.deepEqual(value,{environmentKey:"artifact-dev-toolkit",status:"available",backend:"unknown",reason:"ok"})}});
test("missing sandbox process is safely classified",async()=>{const value=await diagnoseSandbox(environment(),"private-command",probe({error:"ENOENT"}));assert.equal(value.reason,"sandbox_helper_unavailable");assert.equal(value.backend,"unknown");assert.doesNotMatch(JSON.stringify(value),/RAW|private-command/)});
for(const [message,reason] of [["bwrap: user namespace failed: Operation not permitted","user_namespace_unavailable"],["bwrap: failed to write uid map: Permission denied","uid_mapping_denied"],["bwrap: network namespace failed: Operation not permitted","network_namespace_unavailable"],["loopback configuration failed: Operation not permitted","loopback_configuration_denied"]])test(`classifies ${reason}`,()=>assert.equal(classifySandboxFailure(message),reason));
test("timeout settles and kills even when the child never closes",async()=>{let child;const spawn=(...args)=>(child=probe({hang:true,closeOnKill:false})(...args)),started=Date.now(),value=await diagnoseSandbox(environment(),"codex",spawn,10);assert.equal(child.killed,true);assert.equal(value.reason,"timeout");assert.equal(value.backend,"unknown");assert.ok(Date.now()-started<100)});
test("late close and error after timeout cannot change or crash the result",async()=>{const lateDelivered=deferred(),value=await diagnoseSandbox(environment(),"codex",probe({hang:true,closeOnKill:false,lateError:true,lateDelivered}),5);assert.equal(value.reason,"timeout");await withDeadline(lateDelivered.promise,"late sandbox events were not delivered");assert.equal(value.reason,"timeout")});
test("multibyte oversized streams are byte bounded and never escape",async()=>{const secret="密".repeat(SANDBOX_DIAGNOSTIC_OUTPUT_LIMIT),value=await diagnoseSandbox(environment(),"codex",probe({stdout:secret,stderr:`${secret} bwrap: user namespace failed`}));assert.equal(value.reason,"unknown");assert.equal(value.backend,"unknown");assert.doesNotMatch(JSON.stringify(value),/密|bwrap/)});
test("only an explicit captured helper fingerprint identifies Bubblewrap",async()=>{const value=await diagnoseSandbox(environment(),"codex",probe({stderr:"bwrap: user namespace failed: Operation not permitted"}));assert.equal(value.backend,"bubblewrap");assert.equal(value.reason,"user_namespace_unavailable")});
