import test from "node:test";
import assert from "node:assert/strict";
import {copyFile,mkdtemp,mkdir,readFile,readdir,rename,rm,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {execFileSync} from "node:child_process";
import {bootstrapLegacySqlite,classifyFilesystem,parseMountInfo,SqliteStorageManager} from "../dist/sqlite-storage.js";

const config=root=>({role:"executor",host:"127.0.0.1",port:1,runnerVersion:"test",codexCommand:"codex",requestBodyLimit:1,jobRequestBodyLimit:1,deviceAuthCompatible:true,stateDirectory:join(root,"runner"),jobDurationMs:1000,codexHome:join(root,"codex"),sqliteHome:join(root,"sqlite"),sqliteBackupRoot:join(root,"codex/.adt/sqlite-backups"),sqliteBackupIntervalMs:60000,sqliteBackupRetention:2});
const sqlite=(path,sql)=>execFileSync("sqlite3",[path,sql]).toString().trim();
async function fixture(){const root=await mkdtemp(join(tmpdir(),"adt-storage-test-")),value=config(root);await mkdir(value.codexHome,{recursive:true});return{root,value,cleanup:()=>rm(root,{recursive:true,force:true})}}

test("mount classification selects the deepest mount and rejects network SQLite filesystems",()=>{const mounts=parseMountInfo("1 2 0:1 / / rw - ext4 /dev/root rw\n2 1 0:2 / /data/codex rw - nfs4 server:/codex rw\n3 1 0:3 / /data/codex-sqlite rw - ext4 /dev/vdb rw");assert.equal(classifyFilesystem("/data/codex/state.sqlite",mounts),"network");assert.equal(classifyFilesystem("/data/codex-sqlite/state.sqlite",mounts),"local")});

test("legacy bootstrap copies sidecars, preserves source, and never overwrites initialized state",async()=>{const f=await fixture();try{await writeFile(join(f.value.codexHome,"state.sqlite"),"db");await writeFile(join(f.value.codexHome,"state.sqlite-wal"),"wal");await bootstrapLegacySqlite(f.value);assert.equal(await readFile(join(f.value.sqliteHome,"state.sqlite-wal"),"utf8"),"wal");assert.equal(await readFile(join(f.value.codexHome,"state.sqlite"),"utf8"),"db");await writeFile(join(f.value.sqliteHome,"state.sqlite"),"local");await bootstrapLegacySqlite(f.value);assert.equal(await readFile(join(f.value.sqliteHome,"state.sqlite"),"utf8"),"local")}finally{await f.cleanup()}});

for(const failure of ["promotion","marker"])test(`bootstrap ${failure} failure removes every introduced file and is retryable`,async()=>{const f=await fixture();try{await writeFile(join(f.value.codexHome,"one.sqlite"),"one");await writeFile(join(f.value.codexHome,"two.sqlite"),"two");let promotions=0;const operations={copyFile,writeFile,rename:async(source,target)=>{if(failure==="promotion"&&++promotions===2)throw new Error("injected");if(failure==="marker"&&source.endsWith(".adt-bootstrap-v1"))throw new Error("injected");return rename(source,target)}};await assert.rejects(bootstrapLegacySqlite(f.value,operations),/sqlite_bootstrap_failed/);assert.deepEqual(await readdir(f.value.sqliteHome),[]);await bootstrapLegacySqlite(f.value);assert.deepEqual((await readdir(f.value.sqliteHome)).sort(),[".adt-bootstrap-v1","one.sqlite","two.sqlite"])}finally{await f.cleanup()}});

test("online backups are standalone, checksummed, retained, and traversal is rejected",async(t)=>{try{execFileSync("sqlite3",["-version"],{stdio:"ignore"})}catch{return t.skip("sqlite3 unavailable")};const f=await fixture();try{await mkdir(f.value.sqliteHome,{recursive:true});sqlite(join(f.value.sqliteHome,"state.sqlite"),"PRAGMA journal_mode=WAL; CREATE TABLE value(v); INSERT INTO value VALUES('safe');");const manager=new SqliteStorageManager(f.value,"0.153.4"),first=await manager.createBackup(),second=await manager.createBackup(),third=await manager.createBackup(),listed=await manager.list();assert.equal(listed.length,2);assert.equal(listed[0].backupId,third.backupId);assert.ok(!listed.some(x=>x.backupId===first.backupId));const files=await readdir(join(f.value.sqliteBackupRoot,second.backupId));assert.ok(files.includes("manifest.json"));assert.ok(!files.some(x=>x.endsWith("-wal")||x.endsWith("-shm")));assert.equal(sqlite(join(f.value.sqliteBackupRoot,second.backupId,"state.sqlite"),"PRAGMA integrity_check;"),"ok");await assert.rejects(()=>manager.restore("../../etc",{closeAndWait:async()=>{},ready:async()=>true}),/invalid_backup_id/)}finally{await f.cleanup()}});

test("restore waits for quiescence before replacement and removes stale WAL state",async()=>{const f=await fixture();try{await mkdir(f.value.sqliteHome,{recursive:true});const path=join(f.value.sqliteHome,"state.sqlite");sqlite(path,"CREATE TABLE value(v); INSERT INTO value VALUES('backup');");const manager=new SqliteStorageManager(f.value,"0.153.4"),backup=await manager.createBackup();sqlite(path,"UPDATE value SET v='current'; PRAGMA wal_checkpoint(TRUNCATE);");await writeFile(`${path}-wal`,"stale");let release;const shutdown=new Promise(resolve=>{release=resolve}),restore=manager.restore(backup.backupId,{closeAndWait:()=>shutdown,ready:async()=>true});await new Promise(resolve=>setTimeout(resolve,20));assert.equal(sqlite(path,"SELECT v FROM value;"),"current");release();await restore;assert.equal(sqlite(path,"SELECT v FROM value;"),"backup");assert.equal((await readdir(f.value.sqliteHome)).some(name=>name.endsWith("-wal")||name.endsWith("-shm")),false)}finally{await f.cleanup()}});

test("restore readiness failure rolls back the pre-restore SQLite state",async()=>{const f=await fixture();try{await mkdir(f.value.sqliteHome,{recursive:true});const path=join(f.value.sqliteHome,"state.sqlite");sqlite(path,"CREATE TABLE value(v); INSERT INTO value VALUES('backup');");const manager=new SqliteStorageManager(f.value,"0.153.4"),backup=await manager.createBackup();sqlite(path,"UPDATE value SET v='current';");let readiness=0;await assert.rejects(manager.restore(backup.backupId,{closeAndWait:async()=>{},ready:async()=>++readiness>1}),/restore_failed_rolled_back/);assert.equal(sqlite(path,"SELECT v FROM value;"),"current")}finally{await f.cleanup()}});

test("executor maintenance and execution admission are atomic",async()=>{const {ExecutorAdmissionGate}=await import("../dist/executor.js"),gate=new ExecutorAdmissionGate();gate.reserveRestore();assert.throws(()=>gate.reserveExecution(),/runner_busy/);gate.releaseRestore();gate.reserveExecution();assert.throws(()=>gate.reserveRestore(),/runner_busy/);gate.releaseExecution();gate.reserveRestore();gate.releaseRestore()});
