name: Dispatch Cloudflare deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  actions: write
  contents: read

jobs:
  dispatch:
    name: Dispatch Publish to Cloudflare
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch Cloudflare deployment workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run deploy-cloudflare.yml --ref main
